"""Generate the Q_d certificate modules of the package (THM-4525 upper bounds).

For d = 7, 8, 9 this writes ProcgenSelfieEdim/EdimQ<d>Data.lean (the landmark set and the
precomputed edge keys), EdimQ<d>P<j>.lean (one kernel check per block of 64 edges) and
EdimQ<d>.lean (distinctness by the verified merge sort, and the resolving theorem).
The landmark sets are the edim lane's explicit sets (04-computation/experiments/
procgen_edim_20261001_run.py, section S10). The script asserts that each set is
resolving (exact histograms) before writing anything; the Lean files are trusted only
through the kernel checks, not through this script.

Usage (from the package directory): python3 gen_certificates.py 7 8 9
"""
import sys
from pathlib import Path

CERT = {
    7: [5, 57, 54, 104, 35, 109, 115, 49, 6, 39, 55, 102, 15, 32, 85, 97, 21, 113, 41],
    8: [227, 92, 87, 110, 36, 32, 218, 61, 41, 64, 31, 104, 81, 251, 197, 101, 97, 112, 59, 67,
        231, 242, 80, 212, 47, 52],
    9: [504, 67, 283, 159, 247, 106, 267, 339, 3, 411, 363, 127, 373, 321, 244, 483, 410, 208, 160, 70,
        193, 34, 481, 480, 385, 100, 303, 24, 484, 380, 507, 226, 64, 117, 447, 505, 375, 131],
}
PAPER = {7: 63, 8: 115, 9: 246}
PER_PART = {7: 4, 8: 4, 9: 3}
OUT = Path(__file__).resolve().parent / "ProcgenSelfieEdim"
B = 64

def ham(d, u, v): return bin((u ^ v) & ((1 << d) - 1)).count('1')

def wrap(nums, indent="   ", width=92):
    rows, row, w = [], [], 0
    for k in map(str, nums):
        if w + len(k) + 2 > width:
            rows.append(", ".join(row)); row, w = [], 0
        row.append(k); w += len(k) + 2
    rows.append(", ".join(row))
    return (",\n" + indent).join(rows)

def gen(d):
    S = CERT[d]; m = len(S)
    base = 32 if m < 32 else 64
    assert m < base and len(set(S)) == m and all(0 <= s < 2 ** d for s in S)
    edges = [(u, u + (1 << i)) for u in range(1 << d) for i in range(d) if not (u >> i) & 1]
    E = len(edges)
    assert E == d * 2 ** (d - 1) and E % B == 0
    keys = [sum(base ** min(ham(d, u, s), ham(d, v, s)) for s in S) for (u, v) in edges]
    hists = [tuple(sorted(min(ham(d, u, s), ham(d, v, s)) for s in S)) for (u, v) in edges]
    assert len(set(hists)) == E and len(set(keys)) == E
    R = (E - 1).bit_length()
    nblk = E // B
    n = f"q{d}"
    mods = []
    # data module
    L = ["import ProcgenSelfieEdim.KeyBlocks\n", "set_option autoImplicit false\n",
         f"/-! Data for the `Q_{d}` certificate (THM-4525): the resolving {m}-set and the {E} precomputed",
         f"edge keys `Σ_{{s ∈ S}} {base}^{{d(e,s)}}` in `edgeList {d}` order, in blocks of {B}.",
         "Generated by `gen_certificates.py`. -/\n", "namespace ProcgenSelfieEdim\n",
         f"/-- The edim lane's resolving {m}-set of `Q_{d}` (the paper's certificate had {PAPER[d]} vertices). -/",
         f"def {n}set : List Nat := [{wrap(S)}]\n",
         f"/-- The keys of the {E} canonical edges, in blocks of {B}. -/",
         f"noncomputable def {n}keyBlocks : List (List Nat) := ["]
    L.append(",\n".join("  [" + wrap(keys[i:i + B]) + "]" for i in range(0, E, B)) + "]\n")
    L += [f"noncomputable def {n}keys : List Nat := {n}keyBlocks.flatten\n",
          f"theorem {n}set_is_vertex_set : {n}set.length = {m} ∧ {n}set.Nodup ∧ ∀ s ∈ {n}set, s < 2 ^ {d} := by",
          "  decide\n",
          f"theorem {n}_lengths : (edgeKeys {base} {d} {n}set).length = {E} ∧ {n}keys.length = {E} := by",
          "  decide +kernel\n", "end ProcgenSelfieEdim\n"]
    (OUT / f"EdimQ{d}Data.lean").write_text("\n".join(L), encoding="utf-8")
    mods.append(f"EdimQ{d}Data")
    # part modules
    parts = [list(range(i, min(i + PER_PART[d], nblk))) for i in range(0, nblk, PER_PART[d])]
    for j, blks in enumerate(parts):
        L = [f"import ProcgenSelfieEdim.EdimQ{d}Data\n", "set_option autoImplicit false\n",
             f"/-! `Q_{d}` certificate, key blocks {blks[0]}-{blks[-1]} (one kernel check per block). -/\n",
             "namespace ProcgenSelfieEdim\n"]
        for i in blks:
            L += [f"theorem {n}_block_{i} : eqListR (blk {B} {i} (edgeKeys {base} {d} {n}set)) (blk {B} {i} {n}keys) = true := by",
                  "  decide +kernel\n"]
        L.append("end ProcgenSelfieEdim\n")
        (OUT / f"EdimQ{d}P{j}.lean").write_text("\n".join(L), encoding="utf-8")
        mods.append(f"EdimQ{d}P{j}")
    # assembly
    L = [f"import ProcgenSelfieEdim.EdimQ{d}P{j}" for j in range(len(parts))]
    L += ["", "set_option autoImplicit false\n",
          f"/-!\n# THM-4525: `edim_m(Q_{d}) ≤ {m}`\n",
          f"The {E} edge keys of the explicit {m}-set (`{n}set`) equal the precomputed numbers",
          f"(`{n}_block_0` … `{n}_block_{nblk - 1}`), which are pairwise distinct (verified merge sort,",
          f"{R} rounds, then a strict-increase check). Hence the set is edge-multiset resolving.\n-/\n",
          "namespace ProcgenSelfieEdim\n",
          f"theorem {n}_distinct : strictIncR (msortR {R} {n}keys) = true := by", "  decide +kernel\n",
          f"theorem {n}_keys_eq : edgeKeys {base} {d} {n}set = {n}keys := by",
          f"  apply eq_of_blocks {B} {nblk} _ _ (by rw [{n}_lengths.1]; decide) (by rw [{n}_lengths.2]; decide)",
          "  intro i hi", "  match i, hi with"]
    L += [f"  | {i}, _ => exact eq_of_eqListR _ _ {n}_block_{i}" for i in range(nblk)]
    L += [f"  | _ + {nblk}, h => exact absurd h (by omega)\n",
          f"/-- **THM-4525:** the explicit {m}-set is edge-multiset resolving in `Q_{d}`, so",
          f"`edim_m(Q_{d}) ≤ {m}` (the paper's certificate had {PAPER[d]} vertices). -/",
          f"theorem {n}set_resolving : Resolving {d} {n}set := by",
          f"  apply resolving_of_edgeKeys {base} {d} {n}set",
          f"  rw [{n}_keys_eq]",
          f"  exact nodup_of_msortR {R} {n}keys {n}_distinct\n",
          "end ProcgenSelfieEdim\n"]
    (OUT / f"EdimQ{d}.lean").write_text("\n".join(L), encoding="utf-8")
    mods.append(f"EdimQ{d}")
    print(f"d={d}: |S|={m} base={base} E={E} blocks={nblk} parts={len(parts)} rounds={R}")
    print("MODULES", " ".join(mods))

for d in map(int, sys.argv[1:]):
    gen(d)
