#!/usr/bin/env python3
"""
algtop_spectral_23.py — Algebraic Topology and Spectral Sequences through (2,3)
opus-2026-03-14-S84

Exploring how KEY1=2 and KEY2=3 govern:
- Homology of spheres, projective spaces, Grassmannians
- Spectral sequences (Serre, Adams, Atiyah-Hirzebruch)
- Steenrod algebra and Steenrod squares (Sq^i, at prime KEY1)
- Cohomology operations at prime KEY2 (Steenrod powers)
- Characteristic classes (Stiefel-Whitney, Chern, Pontryagin)
- K-theory and Adams operations
- Cobordism theories
- Classifying spaces BG
- Loop spaces and delooping
- Thom isomorphism and orientation
- Poincare duality (in even = KEY1-related dimensions)
- Euler characteristic as the universal invariant
"""

import math
from fractions import Fraction
from functools import lru_cache
from itertools import combinations

# Tournament vocabulary
KEY1 = 2
KEY2 = 3
KEY_SUM = KEY1 + KEY2  # 5
H_forb_1 = 7
V_PET = 10
h_E6 = 12
h_G2 = 6
BT = 24
BO = 48
BI = 120

print("=" * 70)
print("  ALGEBRAIC TOPOLOGY THROUGH THE (2,3) LENS")
print("  Where cohomology meets tournaments")
print("=" * 70)

# =====================================================================
# Part 1: HOMOLOGY OF SPHERES — THE KEY1 PERIODICITY
# =====================================================================
print("\n" + "=" * 70)
print("  Part 1: HOMOLOGY OF SPHERES — THE KEY1 PERIODICITY")
print("=" * 70)

print("""
  CELLULAR HOMOLOGY OF SPHERES:

  H_k(S^n; Z) = Z  if k = 0 or k = n
                 0  otherwise

  The sphere has exactly KEY1 = 2 nontrivial homology groups!
  (For n >= 1: H_0 and H_n)

  EULER CHARACTERISTICS:
""")

for n in range(8):
    chi = 1 + (-1)**n  # = 0 if odd, 2 if even
    label = ""
    if chi == KEY1:
        label = " = KEY1"
    print(f"  chi(S^{n}) = 1 + (-1)^{n} = {chi}{label}")

print(f"""
  chi(S^n) = KEY1 if n is even, 0 if n is odd.
  The nonzero Euler characteristic is ALWAYS KEY1!

  SUSPENSION:
  Sigma(S^n) = S^(n+1) — shifting dimension by 1
  Sigma^k(S^n) = S^(n+k) — iterated suspension

  Suspension is exact: H_k(Sigma X) = H_(k-1)(X) for k >= 1
  This means the "information" in homology is STABLE:
  it depends only on the stable homotopy type.
""")

# =====================================================================
# Part 2: PROJECTIVE SPACES — TRUNCATED POLYNOMIALS
# =====================================================================
print("\n" + "=" * 70)
print("  Part 2: PROJECTIVE SPACES — TRUNCATED POLYNOMIALS")
print("=" * 70)

print("""
  REAL PROJECTIVE SPACE RP^n:
  H*(RP^n; Z/KEY1) = Z/KEY1[x] / (x^(n+1))
  where |x| = 1

  This is a TRUNCATED POLYNOMIAL over Z/KEY1!

  COMPLEX PROJECTIVE SPACE CP^n:
  H*(CP^n; Z) = Z[y] / (y^(n+1))
  where |y| = KEY1 (degree 2!)

  The generator has degree KEY1 = 2 — the fundamental class
  of the embedded CP^1 = S^KEY1.

  QUATERNIONIC PROJECTIVE SPACE HP^n:
  H*(HP^n; Z) = Z[z] / (z^(n+1))
  where |z| = KEY1^KEY1 = 4

  OCTONIONIC PROJECTIVE PLANE OP^KEY1:
  H*(OP^2; Z) = Z[w] / (w^3)
  where |w| = KEY1^KEY2 = 8

  PATTERN OF GENERATOR DEGREES:
""")

spaces = [
    ("RP^n", "Z/KEY1", 1, "1 (real)"),
    ("CP^n", "Z", KEY1, "KEY1 = 2 (complex)"),
    ("HP^n", "Z", KEY1**2, "KEY1^KEY1 = 4 (quaternion)"),
    ("OP^2", "Z", KEY1**3, "KEY1^KEY2 = 8 (octonion)"),
]

for name, coeff, deg, desc in spaces:
    print(f"  {name}: gen degree = {deg} = {desc}")

print(f"""
  Generator degrees: 1, KEY1, KEY1^KEY1, KEY1^KEY2 = 1, 2, 4, 8
  These are 1, KEY1, KEY1^2, KEY1^3 — POWERS OF KEY1!

  These correspond to the real division algebras:
  R (dim 1), C (dim KEY1), H (dim KEY1^2), O (dim KEY1^3)

  By Hurwitz/Adams, these are the ONLY normed division algebras!
  The constraint is: dim must be KEY1^k for k = 0, 1, 2, 3.

  TOPOLOGICAL CONSEQUENCE:
  S^0, S^1, S^3, S^7 are the ONLY spheres that are H-spaces
  (have a continuous multiplication).
  Dimensions: 0, 1, KEY2, H_forb_1
  These ARE tournament constants!
""")

# =====================================================================
# Part 3: STEENROD ALGEBRA — OPERATIONS AT PRIME KEY1
# =====================================================================
print("\n" + "=" * 70)
print("  Part 3: STEENROD ALGEBRA — OPERATIONS AT PRIME KEY1")
print("=" * 70)

print("""
  At the prime KEY1 = 2, the Steenrod algebra A(KEY1) is generated by
  the Steenrod squares Sq^i: H^n(X; Z/KEY1) -> H^(n+i)(X; Z/KEY1)

  KEY PROPERTIES:
  - Sq^0 = identity
  - Sq^n(x) = x^KEY1 if |x| = n (top operation = squaring!)
  - Sq^i(x) = 0 if i > |x|
  - CARTAN FORMULA: Sq^n(xy) = sum Sq^i(x) Sq^(n-i)(y)
  - ADEM RELATIONS: Sq^a Sq^b = sum C(b-1-j, a-2j) Sq^(a+b-j) Sq^j
    for 0 < a < KEY1*b

  The Steenrod algebra at p = KEY1 is the algebra of ALL
  stable cohomology operations with Z/KEY1 coefficients.

  ADMISSIBLE MONOMIALS Sq^I = Sq^(i_1) ... Sq^(i_k):
  I = (i_1, ..., i_k) is admissible if i_j >= KEY1 * i_(j+1) for all j.

  MILNOR BASIS:
  A(KEY1)* = Z/KEY1[xi_1, xi_2, xi_3, ...]
  where |xi_k| = KEY1^k - 1

  Milnor generators have degrees:
""")

for k in range(1, 9):
    deg = KEY1**k - 1
    label = ""
    if deg == 1: label = " (= 1)"
    elif deg == KEY2: label = " (= KEY2!)"
    elif deg == H_forb_1: label = " (= H_forb_1!)"
    elif deg == 15: label = " (= KEY1^KEY1^KEY1 - 1)"
    elif deg == 31: label = " (= Mersenne prime)"
    elif deg == 63: label = ""
    elif deg == 127: label = " (= Mersenne prime)"
    elif deg == 255: label = " (= KEY1^KEY1^KEY2 - 1)"
    print(f"  |xi_{k}| = KEY1^{k} - 1 = {deg}{label}")

print(f"""
  The Milnor generators xi_k have degrees KEY1^k - 1.
  These are the MERSENNE NUMBERS!

  KEY1^1 - 1 = 1
  KEY1^2 - 1 = KEY2 = 3
  KEY1^3 - 1 = H_forb_1 = 7
  KEY1^5 - 1 = 31 (Mersenne prime)
  KEY1^7 - 1 = 127 (Mersenne prime)

  The Steenrod algebra ENCODES the Mersenne sequence!
  And the Mersenne sequence IS our forbidden cycle sequence.

  AT PRIME KEY2 = 3:
  The Steenrod algebra A(KEY2) is generated by:
  - beta: the Bockstein (degree 1)
  - P^i: Steenrod powers (degree KEY1*i*(KEY2-1) = 4i)

  The Steenrod powers at p = KEY2 raise to the KEY2-rd power
  (just as Sq raises to the KEY1-nd power at p = KEY1).

  DUAL: A(KEY2)* = Z/KEY2[xi_1, xi_2, ...] tensor E[tau_0, tau_1, ...]
  |xi_k| = KEY1*(KEY2^k - 1) and |tau_k| = KEY1*KEY2^k - 1
""")

for k in range(1, 6):
    xi_deg = KEY1 * (KEY2**k - 1)
    tau_deg = KEY1 * KEY2**k - 1
    print(f"  |xi_{k}| = {xi_deg}, |tau_{k}| = {tau_deg}")

# =====================================================================
# Part 4: CHARACTERISTIC CLASSES
# =====================================================================
print("\n" + "=" * 70)
print("  Part 4: CHARACTERISTIC CLASSES — KEY1 CONTROLS GEOMETRY")
print("=" * 70)

print("""
  STIEFEL-WHITNEY CLASSES (mod KEY1 = 2):
  w_i in H^i(M; Z/KEY1), i = 0, 1, ..., n

  w_1 = 0  iff  M is orientable
  w_1 = w_2 = 0  iff  M admits a spin structure
  Total SW class: w(E) = 1 + w_1 + w_2 + ...

  CHERN CLASSES (integral):
  c_i in H^(KEY1*i)(M; Z), i = 0, 1, ..., n

  Note: c_i lives in degree KEY1*i — even (= KEY1-multiple) degrees!
  This reflects the complex structure (real dim = KEY1 * complex dim).

  PONTRYAGIN CLASSES (integral):
  p_i in H^(KEY1^KEY1*i)(M; Z), i = 0, 1, ..., floor(n/2)

  p_i lives in degree KEY1^KEY1 * i = 4i — divisible by KEY1^KEY1!
  This reflects quaternionic structure.

  EULER CLASS:
  e in H^n(M; Z) for oriented n-manifolds.
  chi(M) = <e, [M]> = Euler characteristic.

  HIERARCHY OF CHARACTERISTIC CLASSES:
  - Z/KEY1 coefficients: Stiefel-Whitney (finest, works for all bundles)
  - Z coefficients, KEY1*i degrees: Chern (complex bundles)
  - Z coefficients, KEY1^2*i degrees: Pontryagin (real bundles, mod KEY1-torsion)

  Each refinement corresponds to a KEY1-fold increase in periodicity!
""")

# Compute some characteristic numbers
print("  CHARACTERISTIC NUMBERS of projective spaces:")
for n in range(1, 8):
    chi_rpn = 1 + (-1)**n  # 0 or 2
    chi_cpn = n + 1
    label_rp = f" = KEY1" if chi_rpn == KEY1 else ""
    label_cp = ""
    if chi_cpn == KEY1: label_cp = " = KEY1"
    elif chi_cpn == KEY2: label_cp = " = KEY2"
    elif chi_cpn == KEY_SUM: label_cp = " = KEY_SUM"
    elif chi_cpn == H_forb_1: label_cp = " = H_forb_1"
    print(f"  chi(RP^{n}) = {chi_rpn}{label_rp},  chi(CP^{n}) = {chi_cpn}{label_cp}")

# =====================================================================
# Part 5: SPECTRAL SEQUENCES — THE MACHINERY
# =====================================================================
print("\n" + "=" * 70)
print("  Part 5: SPECTRAL SEQUENCES — THE KEY1-INDEXED MACHINERY")
print("=" * 70)

print("""
  A spectral sequence is a sequence of pages:
  E_r^{p,q} => H^{p+q}(total)

  STARTING PAGE: E_KEY1 or E_1 depending on construction.

  DIFFERENTIALS: d_r: E_r^{p,q} -> E_r^{p+r, q-r+1}
  d_r^KEY1 = d_r . d_r = 0 (the differential squares to zero!)

  KEY1 = 2 appears fundamentally:
  - d^KEY1 = 0 is the DEFINING property (d^2 = 0)
  - Homology = ker(d) / im(d) — a KEY1-step construction
  - Each page E_(r+1) = H(E_r, d_r) — KEY1-step refinement

  SERRE SPECTRAL SEQUENCE:
  For a fibration F -> E -> B:
  E_KEY1^{p,q} = H^p(B; H^q(F)) => H^{p+q}(E)

  Starts at page KEY1 = 2!

  ATIYAH-HIRZEBRUCH SPECTRAL SEQUENCE:
  E_KEY1^{p,q} = H^p(X; h^q(pt)) => h^{p+q}(X)

  Again starts at page KEY1 = 2!

  ADAMS SPECTRAL SEQUENCE:
  E_KEY1^{s,t} = Ext_A^{s,t}(Z/p, Z/p) => pi_(t-s)(S^0) (p-completed)

  At p = KEY1: converges to KEY1-primary stable stems
  At p = KEY2: converges to KEY2-primary stable stems

  The Adams E_KEY1 page at p = KEY1 is computed from:
  Ext_{A(KEY1)}(Z/KEY1, Z/KEY1)

  This involves the Steenrod algebra A(KEY1) — back to Sq!
""")

# =====================================================================
# Part 6: SERRE SPECTRAL SEQUENCE — EXAMPLES
# =====================================================================
print("\n" + "=" * 70)
print("  Part 6: SERRE SPECTRAL SEQUENCE — COMPUTING H*(BG)")
print("=" * 70)

print("""
  CLASSIFYING SPACE of Z/KEY1:
  BZ/KEY1 = RP^infinity
  H*(BZ/KEY1; Z/KEY1) = Z/KEY1[x], |x| = 1

  CLASSIFYING SPACE of Z/KEY2:
  BZ/KEY2 = L^infinity(KEY2) (infinite lens space)
  H*(BZ/KEY2; Z/KEY2) = Z/KEY2[y] tensor E[e]
  where |y| = KEY1, |e| = 1

  Note the KEY1 in the degree of y!

  CLASSIFYING SPACE of S^1 = U(1):
  BS^1 = CP^infinity
  H*(BS^1; Z) = Z[c_1], |c_1| = KEY1

  CLASSIFYING SPACE of SU(KEY1):
  BSU(KEY1) = HP^infinity
  H*(BSU(KEY1); Z) = Z[c_2], |c_2| = KEY1^KEY1 = 4

  CLASSIFYING SPACE of SU(KEY2):
  H*(BSU(KEY2); Z) = Z[c_2, c_3]
  |c_2| = KEY1^KEY1 = 4, |c_3| = KEY1 * KEY2 = 6 = h(G2)!

  FIBRATION S^1 -> S^3 -> S^KEY1 (Hopf):
  Serre SS gives: H*(S^KEY1; H*(S^1)) => H*(S^KEY2)
  E_KEY1^{p,q} with d_KEY1 connecting generators
""")

print("  BETTI NUMBERS of key classifying spaces:")
print("  (dimensions where H_k != 0)")
for name, dims in [
    ("BZ/2 = RP^inf", list(range(10))),
    ("BZ/3", [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
    ("BS^1 = CP^inf", [0, 2, 4, 6, 8]),
    ("BSU(2) = HP^inf", [0, 4, 8, 12]),
    ("BSU(3)", [0, 4, 5, 6, 8, 9, 10]),
    ("BSO(3)", [0, 4, 8, 12]),
]:
    print(f"  {name}: {dims}")

# =====================================================================
# Part 7: K-THEORY — KEY1-PERIODIC
# =====================================================================
print("\n" + "=" * 70)
print("  Part 7: K-THEORY — KEY1-PERIODIC HOMOLOGY THEORY")
print("=" * 70)

print("""
  COMPLEX K-THEORY KU:
  Bott periodicity: KU^n = KU^(n + KEY1) for all n
  Period = KEY1 = 2!

  KU^0(pt) = Z (virtual dimension)
  KU^1(pt) = 0
  And these repeat with period KEY1.

  KU^*(S^n):
  K^0(S^(KEY1*k)) = Z + Z (one copy from dim, one from Bott)
  K^0(S^(KEY1*k+1)) = Z

  REAL K-THEORY KO:
  Bott periodicity: KO^n = KO^(n + KEY1^KEY2) for all n
  Period = KEY1^KEY2 = 8!

  The KEY1^KEY2-periodicity of KO is one of the deepest facts
  in topology. It encodes:
  - Division algebras R, C, H, O
  - Clifford algebra periodicity
  - Spin geometry

  KO groups of a point:
""")

ko_groups = ['Z', 'Z/KEY1', 'Z/KEY1', '0', 'Z', '0', '0', '0']
for i, g in enumerate(ko_groups):
    label = ""
    if g == 'Z/KEY1':
        label = " — KEY1-torsion!"
    elif g == 'Z' and i > 0:
        label = " — free part"
    print(f"  KO^(-{i})(pt) = {g}{label}")

print(f"""
  Pattern: Z, Z/{KEY1}, Z/{KEY1}, 0, Z, 0, 0, 0 (period {KEY1**KEY2} = 8)

  The KEY1-torsion groups Z/KEY1 appear in degrees -1, -2 (mod 8).
  Free groups Z appear in degrees 0, -4 (mod 8).
  Zero groups in degrees -3, -5, -6, -7 (mod 8).

  ADAMS OPERATIONS psi^k:
  psi^k: K(X) -> K(X) are ring homomorphisms
  psi^KEY1: the Frobenius-like "squaring" operation
  psi^KEY2: closely related to the KEY2-rd power

  KEY RELATION:
  psi^(KEY1) + psi^(KEY2) = psi^(KEY1) . psi^(KEY2)
  — NO! Actually:
  psi^(KEY1*KEY2) = psi^(KEY1) . psi^(KEY2) = psi^(KEY2) . psi^(KEY1)

  The Adams operations compose: psi^(mn) = psi^m . psi^n
  This gives K(X) the structure of a LAMBDA-RING.

  ADAMS e-INVARIANT:
  e: pi_(KEY1*k-1)^s -> Q/Z
  detects the image of J (the J-homomorphism!)
  e(alpha_k) = B_(KEY1*k) / (KEY1 * KEY1*k)
  — involves Bernoulli numbers and powers of KEY1.
""")

# =====================================================================
# Part 8: COBORDISM — THE UNIVERSAL THEORY
# =====================================================================
print("\n" + "=" * 70)
print("  Part 8: COBORDISM — THE UNIVERSAL HOMOLOGY THEORY")
print("=" * 70)

print("""
  THOM'S THEOREM: The unoriented cobordism ring is a polynomial ring:
  Omega_* = Z/KEY1[x_i : i != KEY1^k - 1]

  Coefficient ring = Z/KEY1! Generators in every degree EXCEPT
  degrees KEY1^k - 1 = Mersenne numbers!

  Missing degrees: 1, 3, 7, 15, 31, ...
  = KEY1 - 1, KEY2, H_forb_1, ...
  = our FORBIDDEN SEQUENCE minus 1!

  ORIENTED COBORDISM: Omega_*^SO
  Omega_0^SO = Z
  Omega_1^SO = 0
  Omega_2^SO = 0
  Omega_3^SO = 0
  Omega_4^SO = Z (generated by CP^KEY1!)
  Omega_5^SO = Z/KEY1
  Omega_6^SO = 0
  Omega_7^SO = 0
  Omega_8^SO = Z + Z

  KEY GENERATORS:
  - CP^KEY1 in degree KEY1^KEY1 = 4
  - CP^KEY1 x CP^KEY1 and a new generator in degree KEY1^KEY2 = 8
""")

print("  Oriented cobordism groups Omega_k^SO:")
omega_so = ['Z', '0', '0', '0', 'Z', 'Z/2', '0', '0',
            'Z+Z', 'Z/2', 'Z/2', 'Z', 'Z^3', '0', '0', '0',
            'Z^4', 'Z/2', 'Z/2^2', 'Z']
for k, g in enumerate(omega_so[:16]):
    markers = []
    if k == KEY1**2: markers.append("CP^2 generates")
    if k == KEY1**3: markers.append("CP^2 x CP^2 + new gen")
    if k == h_E6: markers.append("3 generators")
    label = f" -- {', '.join(markers)}" if markers else ""
    print(f"  Omega_{k}^SO = {g}{label}")

print(f"""
  COMPLEX COBORDISM MU:
  MU_* = Z[x_1, x_2, x_3, ...] with |x_i| = KEY1*i

  ALL generators have KEY1-multiple degrees!
  MU is the universal complex-oriented theory.
  Its formal group law classifies ALL 1-dimensional
  commutative formal group laws (Quillen's theorem).

  FORMAL GROUP LAWS:
  F(x, y) = x + y + sum a_(ij) x^i y^j

  The additive FGL: F(x,y) = x + y (corresponds to H*)
  The multiplicative FGL: F(x,y) = x + y + xy (corresponds to K-theory)
  The universal FGL: F(x,y) over L = MU_* (Lazard ring)

  CHROMATIC PICTURE:
  Height 0: rational homology H*Q (characteristic 0)
  Height 1: K-theory KU (period KEY1)
  Height 2: Elliptic cohomology / TMF (period KEY1^3 * KEY2 = 24 or 576)
  Height n: Morava K/E-theories K(n), E(n)

  The chromatic tower is filtered by PRIME and HEIGHT:
  - At p = KEY1: the most complex structure
  - At p = KEY2: cleaner, but still rich
  - At large p: increasingly simple
""")

# =====================================================================
# Part 9: POINCARE DUALITY AND INTERSECTION
# =====================================================================
print("\n" + "=" * 70)
print("  Part 9: POINCARE DUALITY — THE KEY1-FOLD SYMMETRY")
print("=" * 70)

print("""
  For a closed oriented n-manifold M:
  H^k(M; Z) ~ H^(n-k)(M; Z) (Poincare duality)

  This is a KEY1-fold symmetry: the Betti numbers satisfy
  b_k = b_(n-k)

  For KEY1-manifolds (surfaces):
  b_0 = b_2 = 1, b_1 = 2g
  chi = KEY1 - KEY1*g = KEY1*(1 - g)
  Euler characteristic is always a multiple of KEY1!

  For KEY1^KEY1-manifolds (4-manifolds):
  b_0 = b_4 = 1, b_1 = b_3, b_2 unconstrained
  The intersection form on H^KEY1(M; Z) is the KEY information!

  CLASSIFICATION OF INTERSECTION FORMS:
  - Definite: +/- E_8 (rank 8 = KEY1^KEY2), det = 1
  - Indefinite even: sums of E_8 and H (hyperbolic, rank KEY1)
  - Indefinite odd: sums of <+1> and <-1>

  THE E_8 MANIFOLD (Freedman, 1982):
  |E_8| has intersection form = E_8 lattice
  Betti numbers: 1, 0, 8, 0, 1
  chi = V(Pet) = 10, sigma = KEY1^KEY2 = 8
""")

# Compute intersection matrices
print("  INTERSECTION FORM of CP^KEY1 = CP^2:")
print("  H^2(CP^2; Z) = Z, generated by [CP^1]")
print(f"  [CP^1] . [CP^1] = 1 (the form is <1>)")
print(f"  chi(CP^2) = KEY2 = 3, sigma(CP^2) = 1")
print()

print("  INTERSECTION FORM of S^KEY1 x S^KEY1 = S^2 x S^2:")
print(f"  H^2(S^2 x S^2; Z) = Z^KEY1, generated by [S^2 x pt] and [pt x S^2]")
print(f"  Form: H = [[0,1],[1,0]] (hyperbolic)")
print(f"  chi(S^2 x S^2) = KEY1^KEY1 = 4, sigma(S^2 x S^2) = 0")

# =====================================================================
# Part 10: HOMOTOPY GROUPS OF SPHERES — DEEPER
# =====================================================================
print("\n" + "=" * 70)
print("  Part 10: HOMOTOPY GROUPS OF SPHERES — (2,3) TORSION")
print("=" * 70)

print("""
  The homotopy groups of spheres are the HARDEST computation
  in algebraic topology. The (2,3) structure appears everywhere.

  UNSTABLE HOMOTOPY GROUPS pi_k(S^n):
""")

# Known pi_k(S^2) for small k
pi_S2 = {
    2: "Z",
    3: "Z (Hopf! pi_3(S^2) = Z via Hopf fibration)",
    4: "Z/KEY1",
    5: "Z/KEY1",
    6: "Z/h_E6 = Z/12",
    7: "Z/KEY1",
    8: "Z/KEY1",
    9: "Z/KEY2",
    10: "Z/15 = Z/(KEY2 * KEY_SUM)",
    11: "Z/KEY1",
}

print("  pi_k(S^KEY1) = pi_k(S^2):")
for k in sorted(pi_S2.keys()):
    print(f"    k = {k}: {pi_S2[k]}")

print(f"""
  KEY OBSERVATIONS:
  1. pi_3(S^2) = Z — the Hopf fibration!
     S^1 -> S^KEY2 -> S^KEY1
     This is a fibration of dimension KEY1 over dimension KEY1
     with fiber dimension 1, total space dimension KEY2.

  2. pi_6(S^2) = Z/{h_E6} = Z/12
     12 = KEY1^KEY1 * KEY2 = h(E6)!

  3. pi_10(S^2) = Z/15 = Z/(KEY2 * KEY_SUM)

  STABLE STEMS (first few):
  pi_0^s = Z
  pi_1^s = Z/KEY1 (eta)
  pi_2^s = Z/KEY1 (eta^2)
  pi_3^s = Z/BT = Z/24 (nu)
  pi_4^s = 0
  pi_5^s = 0
  pi_6^s = Z/KEY1 (nu^2? no, it's kappa)
  pi_7^s = Z/240 (sigma, related to BI = 120 but 240 = KEY1*BI)

  KEY1-PRIMARY parts:
  At p = KEY1, the pattern of stems follows the Adams spectral sequence.
  The Adams E_2 page has a "v_1-periodic" region:
  stems 1, KEY2, H_forb_1, 15, 31, ...
  = KEY1^k - 1 = MERSENNE NUMBERS

  KEY2-PRIMARY parts:
  At p = KEY2, the pattern follows the alpha family:
  alpha_1 in stem KEY2*(KEY1*KEY2 - KEY1) - 1 = 3 (wait, let me compute)

  Actually at p = KEY2: first element alpha_1 in pi_3^s = Z/KEY2 (the KEY2 part of Z/24)
  alpha_2 in pi_10^s, alpha_3 in pi_17^s, ...
  Period = KEY1*(KEY2-1)*KEY2 = KEY1*KEY1*KEY2 = 12 ... no,
  period = KEY1*(KEY2^KEY1 - 1) = KEY1*8 = 16... no.

  The alpha family at p = KEY2 has spacing KEY1*(KEY2-1) = 4:
  Wait: at p, the v_1 periodicity is KEY1*(p-1) = KEY1*(KEY2-1) = 4.
  But with stems: alpha_t in pi_(KEY1*t*(KEY2-1)-1)^s at p = KEY2.
  alpha_1: stem KEY1*1*KEY1 - 1 = KEY2
  alpha_2: stem KEY1*KEY1*KEY1 - 1 = H_forb_1
  alpha_3: stem KEY1*KEY2*KEY1 - 1 = 11

  PATTERN: stems KEY2, H_forb_1, 11, 15, 19, ...
  Spacing = KEY1*(KEY2-1) = KEY1^KEY1 = 4.

  This is the v_1-periodic family at p = KEY2!
""")

# =====================================================================
# Part 11: EILENBERG-MACLANE AND POSTNIKOV
# =====================================================================
print("\n" + "=" * 70)
print("  Part 11: EILENBERG-MACLANE SPACES K(G,n)")
print("=" * 70)

print("""
  K(G, n) is the space with pi_n = G and pi_k = 0 for k != n.

  KEY EXAMPLES:
  K(Z, 1) = S^1 (the circle!)
  K(Z, KEY1) = CP^infinity (complex projective space!)
  K(Z/KEY1, 1) = RP^infinity
  K(Z/KEY2, 1) = infinite lens space L^inf(KEY2)

  COHOMOLOGY OF K(Z/KEY1, 1):
  H*(K(Z/KEY1, 1); Z/KEY1) = Z/KEY1[x], |x| = 1

  COHOMOLOGY OF K(Z/KEY1, KEY1):
  H*(K(Z/KEY1, KEY1); Z/KEY1) is generated by:
  iota_(KEY1), Sq^1(iota), Sq^KEY1(iota), Sq^KEY1 Sq^1(iota), ...
  — the ADMISSIBLE Steenrod operations on the fundamental class!

  POSTNIKOV TOWER:
  Any space X has a tower:
  ... -> X[KEY2] -> X[KEY1] -> X[1] -> X[0] = K(pi_0, 0)

  The k-invariants are cohomology classes:
  k_(n+1) in H^(n+1)(X[n-1]; pi_n(X))

  TOURNAMENT INTERPRETATION:
  A tournament on n vertices has a "Postnikov tower" in the
  sense that its homological information can be assembled
  layer by layer, with each layer controlled by a k-invariant
  (an obstruction class in H^* of the previous layer).
""")

# =====================================================================
# Part 12: GRAND SYNTHESIS — TOPOLOGY IS (2,3)
# =====================================================================
print("\n" + "=" * 70)
print("  Part 12: GRAND SYNTHESIS — TOPOLOGY IS (2,3)")
print("=" * 70)

print("""
======================================================================
  ALGEBRAIC TOPOLOGY IS BUILT FROM KEY1 = 2 AND KEY2 = 3
======================================================================

1. HOMOLOGY FOUNDATIONS:
   d^KEY1 = 0 (boundary squared = 0)
   H = ker/im — a KEY1-step quotient
   Euler char of even spheres = KEY1

2. DIVISION ALGEBRAS:
   R, C, H, O have dimensions 1, KEY1, KEY1^2, KEY1^3
   S^0, S^1, S^3, S^7 are the H-space spheres
   Dimensions: 0, 1, KEY2, H_forb_1 = tournament constants!

3. STEENROD ALGEBRA:
   At p = KEY1: Sq^i raises to KEY1-nd power
   Milnor generators: degrees KEY1^k - 1 = Mersenne numbers
   At p = KEY2: Steenrod powers raise to KEY2-rd power

4. CHARACTERISTIC CLASSES:
   SW classes: Z/KEY1 coefficients
   Chern classes: degree KEY1*i
   Pontryagin classes: degree KEY1^2*i
   Each level = KEY1-fold refinement!

5. SPECTRAL SEQUENCES:
   Serre, A-H start at E_KEY1 page
   Adams SS at p = KEY1 and p = KEY2 compute stable stems
   v_1 periodicity at p = KEY2 has spacing KEY1^KEY1 = 4

6. K-THEORY:
   KU period = KEY1
   KO period = KEY1^KEY2 = 8
   KO has Z/KEY1 torsion in degrees -1, -2 (mod 8)

7. COBORDISM:
   Omega_*^O = Z/KEY1[generators except Mersenne degrees]
   MU generators in degree KEY1*i (all even!)
   Chromatic: height 0 (rational), height 1 (K, period KEY1),
              height 2 (TMF, period BT = 24)

8. POINCARE DUALITY:
   KEY1-fold symmetry of Betti numbers
   Intersection form on H^(n/KEY1) for KEY1n-manifolds
   E_8 lattice: rank KEY1^KEY2 = 8, appears in KEY1^KEY1-manifolds

9. HOMOTOPY GROUPS:
   pi_3(S^2) = Z (Hopf, dim KEY2 over dim KEY1)
   pi_3^s = Z/BT = Z/24 (nu)
   pi_7^s = Z/240 = KEY1 * BI
   Mersenne stems: KEY1^k - 1 = forbidden cycle sequence

10. CLASSIFYING SPACES:
    BZ/KEY1 = RP^inf, BZ/KEY2 = lens space
    BS^1 = CP^inf with generator in degree KEY1
    Chern classes as universal generators

THE CROWN JEWEL:
   d^KEY1 = 0 is the foundation of ALL homological algebra.
   The Steenrod algebra at p = KEY1 and p = KEY2 controls ALL
   stable cohomology operations.
   K-theory period KEY1, cobordism generators in degree KEY1*i.
   Division algebras in dimensions KEY1^k, H-spheres in dims KEY2, H_forb_1.

   ALGEBRAIC TOPOLOGY IS (2,3).
""")
