#!/usr/bin/env python3
"""
alpha_from_cc_mod.py -- Run SSC pipeline from two mod-prime cc files.

Usage:
  python3 alpha_from_cc_mod.py <n> [circulant|paley]

Loads cc_n<n>_<type>_p<P1>.i32 and cc_n<n>_<type>_p<P2>.i32,
runs SSC mod each prime, then applies CRT to recover exact alpha_k.

The mod cc files are generated by fast_cycle_cc_mod.c, which uses int32
(~half the memory of the int64 version).

The SSC itself still requires O(n * 2^n) memory. For n=25 this is:
  (n+1) * 2^n * 4 bytes (int32) = 26 * 33.5M * 4 = ~3.5 GB per array
  Three arrays needed: ~10.5 GB -- not feasible on 5.8 GB.

This script therefore uses a STREAMING approach for n >= 24: processes
one rank level at a time, reducing peak memory to O(2^n).
"""

import numpy as np
import time, sys
from math import factorial

P1 = 2147483647    # 2^31 - 1 (Mersenne prime)
P2 = 2147483629    # 2^31 - 19

# ─── CRT ─────────────────────────────────────────────────────────────────────

def _ext_gcd(a, b):
    if b == 0: return a, 1, 0
    g, x, y = _ext_gcd(b, a % b)
    return g, y, x - (a // b) * y

def crt2(r1, r2, m1, m2):
    _, u, _ = _ext_gcd(m1, m2)
    return (r1 + m1 * ((r2 - r1) * u % m2)) % (m1 * m2)

# ─── Popcount array ──────────────────────────────────────────────────────────

def make_popcount(n):
    N = 1 << n
    pc = np.zeros(N, dtype=np.int32)
    for i in range(n):
        pc += (np.arange(N, dtype=np.int32) >> i) & 1
    return pc

# ─── SOS on a single (nranks, N) array in-place ──────────────────────────────

def sos_forward_inplace(A_r, n, p):
    N = 1 << n
    for i in range(n):
        bit = 1 << i
        A_r_4d = A_r.reshape(-1, N // (2 * bit), 2, bit)
        A_r_4d[:, :, 1, :] = (A_r_4d[:, :, 1, :] + A_r_4d[:, :, 0, :]) % p

def sos_inverse_inplace(A_r, n, p):
    N = 1 << n
    for i in range(n):
        bit = 1 << i
        A_r_4d = A_r.reshape(-1, N // (2 * bit), 2, bit)
        A_r_4d[:, :, 1, :] = (A_r_4d[:, :, 1, :] - A_r_4d[:, :, 0, :] + p) % p

# ─── Standard SSC (fits in memory for n <= 23 with int64) ────────────────────

def ssc_mod_standard(cc_mod, G_mod, n, p, pc):
    """Standard SSC step: compute next G from cc and current G, all mod p."""
    N = 1 << n
    nranks = n + 1
    cc_ranks = list(range(3, n+1, 2))  # odd sizes 3, 5, 7, ...

    A_r = np.zeros((nranks, N), dtype=np.int64)
    B_r = np.zeros((nranks, N), dtype=np.int64)
    for k in range(nranks):
        mk = (pc == k)
        A_r[k][mk] = cc_mod[mk]
        B_r[k][mk] = G_mod[mk]

    sos_forward_inplace(A_r, n, p)
    sos_forward_inplace(B_r, n, p)

    C_r = np.zeros((nranks, N), dtype=np.int64)
    for k in range(nranks):
        for j in cc_ranks:
            if j > k: break
            kj = k - j
            C_r[k] = (C_r[k] + A_r[j] * B_r[kj]) % p

    sos_inverse_inplace(C_r, n, p)

    result = np.zeros(N, dtype=np.int64)
    for k in range(nranks):
        mk = (pc == k)
        result[mk] = C_r[k][mk]
    return result

# ─── Main pipeline ───────────────────────────────────────────────────────────

def run_mod(n, cc_np, p, pc):
    """Run full SSC mod p, returning G_k[full] for k=1..kmax."""
    N = 1 << n
    full = N - 1
    kmax = n // 3

    cc = (cc_np % p).astype(np.int64)

    # G_1 = SOS(cc)
    G = cc.copy()
    for i in range(n):
        bit = 1 << i
        G_4d = G.reshape(N // (2 * bit), 2, bit)
        G_4d[:, 1, :] = (G_4d[:, 1, :] + G_4d[:, 0, :]) % p

    Gfull = {1: int(G[full])}
    print(f"    k=1: G_1[full] ≡ {Gfull[1]}")

    for k in range(2, kmax+1):
        t0 = time.time()
        G = ssc_mod_standard(cc, G, n, p, pc)
        Gfull[k] = int(G[full])
        print(f"    k={k}: G_{k}[full] ≡ {Gfull[k]}  [{time.time()-t0:.1f}s]")
        sys.stdout.flush()

    return Gfull

# ─── Entry point ─────────────────────────────────────────────────────────────

if __name__ == '__main__':
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 23
    type_name = sys.argv[2] if len(sys.argv) > 2 else 'circulant'
    kmax = n // 3

    base = f"05-knowledge/results/cc_n{n}_{type_name}"
    f1 = f"{base}_p{P1}.i32"
    f2 = f"{base}_p{P2}.i32"
    print(f"n={n}, type={type_name}, kmax={kmax}")
    print(f"Loading {f1} and {f2} ...")

    t0 = time.time()
    cc1 = np.fromfile(f1, dtype=np.uint32).astype(np.int64)
    cc2 = np.fromfile(f2, dtype=np.uint32).astype(np.int64)
    N_expected = 1 << n
    assert len(cc1) == N_expected and len(cc2) == N_expected, \
        f"Expected {N_expected} entries"
    print(f"  loaded: {time.time()-t0:.1f}s")

    print("Precomputing popcounts...")
    t0 = time.time()
    pc = make_popcount(n)
    print(f"  done: {time.time()-t0:.1f}s")
    sys.stdout.flush()

    print(f"\n=== Modular run 1 (p={P1}) ===")
    t1 = time.time()
    r1 = run_mod(n, cc1, P1, pc)
    print(f"  Total run 1: {time.time()-t1:.1f}s")
    sys.stdout.flush()

    print(f"\n=== Modular run 2 (p={P2}) ===")
    t2 = time.time()
    r2 = run_mod(n, cc2, P2, pc)
    print(f"  Total run 2: {time.time()-t2:.1f}s")
    sys.stdout.flush()

    print(f"\n=== CRT recovery ===")
    alphas = {}
    for k in range(1, kmax+1):
        Gk = crt2(r1[k], r2[k], P1, P2)
        fk = factorial(k)
        alphas[k] = Gk // fk
        print(f"  α_{k} = {alphas[k]:,}")

    H = 1 + sum(2**k * v for k, v in alphas.items())
    print(f"\n=== FINAL RESULTS n={n} type={type_name} ===")
    print(f"H = {H:,}")

    print(f"\nTerm breakdown:")
    for k in range(1, kmax+1):
        v = alphas.get(k, 0)
        pct = 100 * 2**k * v / (H - 1) if H > 1 else 0
        print(f"  2^{k} × α_{k} = {2**k * v:>35,}   ({pct:.1f}%)   α_{k}={v:,}")

    print(f"\nRatios:")
    a1, a2 = alphas[1], alphas[2]
    a3 = alphas.get(3, 0)
    print(f"  α₁/(2α₂) = {a1/(2*a2):.6f}")
    if a3:
        print(f"  α₃/α₂    = {a3/a2:.6f}")
