#!/usr/bin/env python3
"""
S643 / HYP-2321 — The solvability DICHOTOMY answering the S642 open thread.

OPEN THREAD: is the LRC/tournament shell-tower a SOLVABLE-group filtration, and where
(if anywhere) does a 'perfect group / no formula' (A5-type) obstruction appear?

ANSWER (a clean dichotomy):
  POLYNOMIAL side (roots, S_n): UNSOLVABLE for n>=5 (Abel-Ruffini, S642). Needs involutions
    (transpositions); S_n is generated by swaps.
  TOURNAMENT side (perspectives, Aut(T)): a tournament has NO automorphism of order 2 ->
    |Aut(T)| ODD -> SOLVABLE (Feit-Thompson) -> in fact Aut(T) <= A_n (odd perms are even).
    The arc's involution sigma:v->-v (the swap, S638) is the CONVERSE = an ANTI-automorphism,
    living OUTSIDE Aut(T) -- which is exactly why Aut is odd/solvable.

This script:
  (A) verifies: every tournament on <=6 vertices has ODD-order automorphism group, and
      Aut(T) <= A_n (all automorphisms are even permutations);
  (B) the Paley_7 tournament: Aut = Z/7 |x Z/3, order 21 (= the forbidden value!), a
      solvable tower whose Z/3 layer is the doubling <2> (the cube root, S640);
  (C) the cyclotomic/LRC side: (Z/n)* is abelian => solvable (derived length 1); the
      shell-tower (doubling orbits) lives inside it;
  (D) the bracket: Abel-Ruffini (S_n unsolvable) vs Feit-Thompson (Aut(T) solvable).
No external libs.
"""
from itertools import permutations, product
from math import gcd

# ---------- permutation helpers ----------
def comp(p,q): return tuple(p[q[i]] for i in range(len(p)))
def inv(p):
    r=[0]*len(p)
    for i,x in enumerate(p): r[x]=i
    return tuple(r)
def order(p):
    n=len(p); e=tuple(range(n)); x=p; k=1
    while x!=e: x=comp(x,p); k+=1
    return k
def sign(p):
    # parity via cycle decomposition
    n=len(p); seen=[False]*n; s=1
    for i in range(n):
        if not seen[i]:
            j=i; L=0
            while not seen[j]: seen[j]=True; j=p[j]; L+=1
            if L%2==0: s=-s
    return s

def all_tournaments(n):
    # tournament = orientation of K_n; for each pair i<j choose i->j or j->i
    pairs=[(i,j) for i in range(n) for j in range(i+1,n)]
    for bits in product([0,1], repeat=len(pairs)):
        beats=[[False]*n for _ in range(n)]
        for (i,j),b in zip(pairs,bits):
            if b: beats[i][j]=True
            else: beats[j][i]=True
        yield beats

def aut_group(beats,n):
    auts=[]
    for p in permutations(range(n)):
        ok=all(beats[p[i]][p[j]]==beats[i][j] for i in range(n) for j in range(n))
        if ok: auts.append(p)
    return auts

print("="*68)
print("(A) every tournament on n<=6 vertices: Aut is ODD-order and <= A_n")
print("="*68)
print("  n | #tournaments | all |Aut| odd? | all Aut <= A_n (even perms)? | max|Aut|")
for n in range(1,7):
    cnt=0; allodd=True; alleven=True; maxa=0
    for beats in all_tournaments(n):
        A=aut_group(beats,n); cnt+=1; maxa=max(maxa,len(A))
        if len(A)%2==0: allodd=False
        if any(sign(p)==-1 for p in A): alleven=False
        # also: no involution
        if any(order(p)==2 for p in A): allodd=False
    print(f"  {n} | {cnt:11d} | {str(allodd):>13} | {str(alleven):>28} | {maxa}")
print("  -> CONFIRMED: no tournament has an order-2 automorphism; |Aut| always odd;")
print("     every automorphism is an EVEN permutation (Aut(T) <= A_n).")

print("\n" + "="*68)
print("(B) Paley_7 tournament: Aut = Z/7 |x Z/3, order 21 (the forbidden value)")
print("="*68)
# Paley tournament on Z/7: i->j iff j-i is a QR (={1,2,4}=<2>=cube roots of unity, S638/S640)
QR=set((x*x)%7 for x in range(1,7))
beats7=[[False]*7 for _ in range(7)]
for i in range(7):
    for j in range(7):
        if i!=j and (j-i)%7 in QR: beats7[i][j]=True
A7=aut_group(beats7,7)
print(f"  connection set (QR mod 7) = {sorted(QR)} = <2> = cube roots of unity (S640)")
print(f"  |Aut(Paley_7)| = {len(A7)}   (= 21 = 3*7 = forbidden H-value? {len(A7)==21})")
orders=sorted(set(order(p) for p in A7))
print(f"  element orders in Aut = {orders}  (all ODD; contains order-3 = the cube root)")
# derived series of Aut (as permutation group) -> solvable?
def gen_closure(gens,n):
    e=tuple(range(n)); G={e}; fr=[e]
    while fr:
        x=fr.pop()
        for g in gens:
            y=comp(x,g)
            if y not in G: G.add(y); fr.append(y)
    return G
def derived(G,n):
    return gen_closure({comp(comp(a,b),comp(inv(a),inv(b))) for a in G for b in G},n)
G=set(A7); chain=[len(G)]
H=G
for _ in range(5):
    H2=derived(H,7)
    chain.append(len(H2))
    if H2==H: break
    H=H2
print(f"  derived series orders: {chain}  (reaches 1 => SOLVABLE, NOT perfect)")
print(f"  structure: Z/7 (additive, normal) |x Z/3 (the doubling <2>=cube root); ")
print(f"  derived length 2: peel Z/3 (cube root, top) then Z/7 (bottom) -- a SOLVABLE")
print(f"  shell-tower. The cube root is a SOLVABLE LAYER here, not a no-formula source.")

print("\n" + "="*68)
print("(C) the cyclotomic / LRC side is abelian => solvable (derived length <=1)")
print("="*68)
def units(n): return [k for k in range(1,n) if gcd(k,n)==1]
for n in [7,14,15,22]:
    U=units(n)
    print(f"  (Z/{n})* has order {len(U)}; abelian => solvable (derived length 1). "
          f"<2>-doubling orbit of 1: ", end="")
    o=[1]; x=2%n
    while x!=1 and x not in o: o.append(x); x=(x*2)%n
    print(f"{o} (the LRC shell)")
print("  the LRC cyclotomic Galois group (Z/n)* is ABELIAN: solvable trivially.")
print("  the shell-tower (doubling orbits) is a subgroup chain inside an abelian group.")

print("\n" + "="*68)
print("(D) the bracket: two great solvability theorems, two sides of FTA duality")
print("="*68)
print("  ROOTS  (S_n, generic Galois): Abel-Ruffini -> UNSOLVABLE for n>=5 (needs swaps).")
print("  PERSPECTIVES (Aut(T)): no involution -> ODD order -> Feit-Thompson -> SOLVABLE,")
print("       and Aut(T) <= A_n. The swap sigma is the CONVERSE (anti-automorphism, S638),")
print("       deliberately OUTSIDE Aut. So perspectives never reach a perfect group: the")
print("       'no formula' wall (A_5) is the ONE wall the tournament/LRC arc does NOT cross.")
