"""
Test Grok's SPECIFIC quotient R = B₁ / <Euler, HP 2-cycles, star annihilators>.

Grok claims dim(R) = 3 exactly, independent of tournament and n.

We need to identify what these generators are:
1. "Global Euler": the sum of all ∂₂ columns? Or Euler relation on cycles?
2. "Rédei HP 2-cycles": for a HP v₁→v₂→...→vₙ, consecutive triples
   (vᵢ, vᵢ₊₁, vᵢ₊₂) that are transitive give TT boundaries.
   The "2-cycle" might be the alternating sum along the HP.
3. "Star annihilators": for each vertex v, the star constraint from THM-103
   (HP in out(v) telescopes out-edges).

Strategy: compute B₁, then identify the subspace generated by these
elements, compute the quotient dimension.

opus-2026-03-09-S51i
"""
import numpy as np
from collections import Counter

def tournament_from_bits(n, bits):
    A = np.zeros((n,n), dtype=int)
    idx = 0
    for i in range(n):
        for j in range(i+1, n):
            if bits & (1 << idx): A[i][j] = 1
            else: A[j][i] = 1
            idx += 1
    return A

def get_tts(A, n):
    tts = []
    for a in range(n):
        for b in range(n):
            if b == a or A[a][b] == 0: continue
            for c in range(n):
                if c == a or c == b: continue
                if A[b][c] == 1 and A[a][c] == 1:
                    tts.append((a,b,c))
    return tts

def boundary2_matrix(A, n, edges, tts):
    edge_idx = {e: i for i, e in enumerate(edges)}
    mat = np.zeros((len(edges), len(tts)), dtype=float)
    for j, (a,b,c) in enumerate(tts):
        if (b,c) in edge_idx: mat[edge_idx[(b,c)], j] += 1
        if (a,c) in edge_idx: mat[edge_idx[(a,c)], j] -= 1
        if (a,b) in edge_idx: mat[edge_idx[(a,b)], j] += 1
    return mat

def beta1(A, n):
    edges = [(i,j) for i in range(n) for j in range(n) if i!=j and A[i][j]==1]
    tts = get_tts(A, n)
    if not tts: return len(edges) - (n-1)
    mat = boundary2_matrix(A, n, edges, tts)
    r = np.linalg.matrix_rank(mat, tol=1e-8)
    return len(edges) - (n-1) - r

def find_hamiltonian_path(A, n):
    """Greedy HP construction for tournaments."""
    path = [0]
    for v in range(1, n):
        inserted = False
        for i in range(len(path)):
            if A[v][path[i]] == 1:
                path.insert(i, v)
                inserted = True
                break
        if not inserted:
            path.append(v)
    return path

def compute_h1_generator(A, n):
    edges = [(i,j) for i in range(n) for j in range(n) if i!=j and A[i][j]==1]
    tts = get_tts(A, n)
    if not tts: return edges, None
    mat = boundary2_matrix(A, n, edges, tts)
    U, S, _ = np.linalg.svd(mat)
    rank = np.sum(S > 1e-8)
    cocycles = U[:, rank:]
    if cocycles.shape[1] - (n-1) <= 0: return edges, None
    cob = np.zeros((len(edges), n), dtype=float)
    for v in range(n):
        for i, (a,b) in enumerate(edges):
            if b == v: cob[i,v] += 1
            if a == v: cob[i,v] -= 1
    cc = np.linalg.lstsq(cocycles, cob, rcond=None)[0]
    U2, S2, V2 = np.linalg.svd(cc.T)
    rc = np.sum(S2 > 1e-8)
    h1c = V2[rc:]
    if h1c.shape[0] == 0: return edges, None
    return edges, cocycles @ h1c[0]


# ============================================================
# CONSTRUCT THE QUOTIENT R
# ============================================================

for n in [5, 6]:
    ne = n*(n-1)//2
    print(f"\n{'='*60}")
    print(f"n={n}: CONSTRUCTING QUOTIENT R = B₁ / <generators>")
    print(f"{'='*60}")

    dim_R_hist = Counter()
    tested = 0
    limit = None if n <= 5 else 200

    for bits in range(1 << ne):
        if limit and tested >= limit:
            break

        A = tournament_from_bits(n, bits)
        if beta1(A, n) != 0:
            continue

        edges = [(i,j) for i in range(n) for j in range(n) if i!=j and A[i][j]==1]
        edge_idx = {e: i for i, e in enumerate(edges)}
        tts = get_tts(A, n)
        mat = boundary2_matrix(A, n, edges, tts)
        rank_B1 = np.linalg.matrix_rank(mat, tol=1e-8)

        # B₁ = column space of mat
        # We'll work in the column space coordinates of mat.
        # Each TT boundary ∂(TT_j) = mat[:, j] is a B₁ element.

        # GENERATOR TYPE 1: "Star annihilators"
        # For each vertex v, the star constraint gives:
        # w(v, u_{i+1}) = w(v, u_i) + w(u_i, u_{i+1})
        # In terms of ∂₂: the star of v generates relations among
        # TT boundaries involving v.
        # Concretely: for v with out-neighborhood HP u₁→...→u_d,
        # the TT (v, u_i, u_{i+1}) for i=1,...,d-1 are all transitive.
        # Their boundaries ∂(v, u_i, u_{i+1}) are the star generators.
        star_elements = []
        for v in range(n):
            out_nbrs = [u for u in range(n) if u != v and A[v][u] == 1]
            if len(out_nbrs) < 2:
                continue
            # Find HP in out(v)
            A_out = np.zeros((len(out_nbrs), len(out_nbrs)), dtype=int)
            for i, u in enumerate(out_nbrs):
                for j, w in enumerate(out_nbrs):
                    if u != w:
                        A_out[i][j] = A[u][w]
            hp_out = find_hamiltonian_path(A_out, len(out_nbrs))
            hp_verts = [out_nbrs[i] for i in hp_out]

            for i in range(len(hp_verts)-1):
                u_i, u_ip1 = hp_verts[i], hp_verts[i+1]
                # TT (v, u_i, u_{i+1}) — check it's a TT
                if A[v][u_i] == 1 and A[u_i][u_ip1] == 1 and A[v][u_ip1] == 1:
                    tt = (v, u_i, u_ip1)
                    if tt in tts:
                        j = tts.index(tt)
                        star_elements.append(mat[:, j])

        # GENERATOR TYPE 2: "Rédei HP 2-cycles"
        # For the HP p₁→p₂→...→pₙ, consecutive transitive triples
        # (p_i, p_{i+1}, p_{i+2}) give elements of B₁.
        hp = find_hamiltonian_path(A, n)
        hp_elements = []
        for i in range(len(hp)-2):
            a, b, c = hp[i], hp[i+1], hp[i+2]
            if A[a][b] == 1 and A[b][c] == 1 and A[a][c] == 1:
                tt = (a, b, c)
                if tt in tts:
                    j = tts.index(tt)
                    hp_elements.append(mat[:, j])

        # GENERATOR TYPE 3: "Global Euler"
        # Sum of all TT boundaries? Or the Euler characteristic relation?
        # Try: sum of all ∂₂ columns
        euler_element = np.sum(mat, axis=1)

        # Also try: alternating sum along HP
        hp_alt = np.zeros(len(edges))
        for i in range(len(hp)-2):
            a, b, c = hp[i], hp[i+1], hp[i+2]
            if A[a][b] == 1 and A[b][c] == 1 and A[a][c] == 1:
                tt = (a, b, c)
                if tt in tts:
                    j = tts.index(tt)
                    hp_alt += (-1)**i * mat[:, j]

        # Combine all generators
        generators = []
        for s in star_elements:
            generators.append(s)
        for h in hp_elements:
            generators.append(h)
        generators.append(euler_element)
        generators.append(hp_alt)

        if not generators:
            tested += 1
            continue

        gen_mat = np.array(generators).T  # (|E| × #generators)
        rank_gen = np.linalg.matrix_rank(gen_mat, tol=1e-8)

        # dim(R) = dim(B₁) - dim(B₁ ∩ span(generators))
        # First: project generators onto B₁
        U_B, S_B, _ = np.linalg.svd(mat, full_matrices=True)
        B1_proj = U_B[:, :rank_B1]  # B₁ basis
        gen_in_B1 = B1_proj.T @ gen_mat  # project generators to B₁ coords
        rank_gen_in_B1 = np.linalg.matrix_rank(gen_in_B1, tol=1e-8)

        dim_R = rank_B1 - rank_gen_in_B1

        dim_R_hist[dim_R] += 1

        if tested < 3:
            print(f"\n  Tournament bits={bits}")
            print(f"  dim(B₁)={rank_B1}, #generators={len(generators)}")
            print(f"  rank(generators in B₁)={rank_gen_in_B1}")
            print(f"  dim(R) = {dim_R}")

        tested += 1

    print(f"\nTested: {tested}")
    print(f"dim(R) distribution: {dict(sorted(dim_R_hist.items()))}")

    # Check: is dim(R) always 3?
    if all(d == 3 for d in dim_R_hist.keys()):
        print("*** dim(R) = 3 ALWAYS — Grok's claim CONFIRMED! ***")
    else:
        print(f"*** dim(R) varies: {set(dim_R_hist.keys())} ***")


# ============================================================
# REFINED: Try different generator sets
# ============================================================
print("\n" + "=" * 60)
print("REFINED: WHAT IS THE MINIMAL QUOTIENT?")
print("=" * 60)

print("""
The star elements are ALL TTs with a fixed first vertex.
So "all star generators" = ALL TT boundaries (every TT is in some star).
That means the generators span ALL of B₁, giving dim(R) = 0.

This is too strong — we need a SUBSET of star constraints.
Let me check: what if we use ONLY the HP-consecutive TTs?
""")

for n in [5, 6]:
    ne = n*(n-1)//2
    print(f"\n--- n={n}: HP-consecutive TTs only ---")

    dim_R_hist = Counter()
    tested = 0
    limit = None if n <= 5 else 500

    for bits in range(1 << ne):
        if limit and tested >= limit:
            break

        A = tournament_from_bits(n, bits)
        if beta1(A, n) != 0:
            continue

        edges = [(i,j) for i in range(n) for j in range(n) if i!=j and A[i][j]==1]
        edge_idx = {e: i for i, e in enumerate(edges)}
        tts = get_tts(A, n)
        mat = boundary2_matrix(A, n, edges, tts)
        rank_B1 = np.linalg.matrix_rank(mat, tol=1e-8)

        hp = find_hamiltonian_path(A, n)
        generators = []
        for i in range(len(hp)-2):
            a, b, c = hp[i], hp[i+1], hp[i+2]
            if A[a][b] == 1 and A[b][c] == 1 and A[a][c] == 1:
                if (a,b,c) in tts:
                    j = tts.index((a,b,c))
                    generators.append(mat[:, j])

        if not generators:
            dim_R_hist[rank_B1] += 1
            tested += 1
            continue

        gen_mat = np.array(generators).T
        U_B, S_B, _ = np.linalg.svd(mat, full_matrices=True)
        B1_proj = U_B[:, :rank_B1]
        gen_in_B1 = B1_proj.T @ gen_mat
        rank_gen_in_B1 = np.linalg.matrix_rank(gen_in_B1, tol=1e-8)
        dim_R = rank_B1 - rank_gen_in_B1

        dim_R_hist[dim_R] += 1
        tested += 1

    print(f"  Tested: {tested}")
    print(f"  dim(R) with HP-TTs only: {dict(sorted(dim_R_hist.items()))}")


# ============================================================
# Try: coboundaries as generators (the most natural choice)
# ============================================================
print("\n--- Coboundaries as generators ---")

for n in [5, 6]:
    ne = n*(n-1)//2
    print(f"\n--- n={n} ---")

    dim_R_hist = Counter()
    tested = 0
    limit = None if n <= 5 else 500

    for bits in range(1 << ne):
        if limit and tested >= limit:
            break

        A = tournament_from_bits(n, bits)
        if beta1(A, n) != 0:
            continue

        edges = [(i,j) for i in range(n) for j in range(n) if i!=j and A[i][j]==1]
        tts = get_tts(A, n)
        mat = boundary2_matrix(A, n, edges, tts)
        rank_B1 = np.linalg.matrix_rank(mat, tol=1e-8)

        # Coboundary matrix δ: f ↦ (f(b)-f(a))
        cob = np.zeros((len(edges), n), dtype=float)
        for v in range(n):
            for i, (a, b) in enumerate(edges):
                if b == v: cob[i, v] += 1
                if a == v: cob[i, v] -= 1

        # When β₁=0: B₁ = Z₁ = coboundaries (all 3 are equal)
        # So coboundaries ARE B₁. dim(B₁/cob) = 0.
        # This is trivial.

        # What Grok might mean: quotient by SOME coboundaries?
        # Or: B₁ modulo the coboundary-generated subspace
        # But B₁ = coboundaries when β₁=0!

        # Actually, B₁ ⊂ Z₁ = coboundaries when β₁=0
        # And dim(B₁) = dim(Z₁) - β₁ = C(n,2)-(n-1)
        # And dim(coboundaries) = n-1
        # So B₁ ≠ coboundaries in general!
        # B₁ = im(∂₂), coboundaries = im(δ) = {f(b)-f(a) : f: V→Q}
        # These are DIFFERENT spaces!

        # When β₁=0: im(∂₂) = ker(∂₁) (since H₁=0)
        # ker(∂₁) has dim C(n,2)-(n-1)
        # im(δ) has dim n-1
        # These live in C₁ = R^{C(n,2)} and have different dimensions!

        # Wait... im(δ) ⊂ ker(∂₁)? Not necessarily for path complexes.
        # δf is a coboundary (cohomological), ∂₁ is homological boundary.

        # Actually in path homology: ∂₁(a,b) = b - a
        # δf(a,b) = f(b) - f(a) = ∂₁^*f applied to (a,b)
        # So δf ∈ im(∂₁^*), which is dual to im(∂₁).

        # Let me just compute: dim(B₁ ∩ im(δ))
        U_B, S_B, _ = np.linalg.svd(mat, full_matrices=True)
        B1_basis = U_B[:, :rank_B1]
        cob_in_B1 = B1_basis.T @ cob
        rank_cob_in_B1 = np.linalg.matrix_rank(cob_in_B1, tol=1e-8)
        dim_R = rank_B1 - rank_cob_in_B1

        dim_R_hist[dim_R] += 1
        tested += 1

    print(f"  Tested: {tested}")
    print(f"  dim(B₁ / (B₁∩im(δ))) = dim R: {dict(sorted(dim_R_hist.items()))}")
    print(f"  (This is B₁ modulo its intersection with coboundaries)")
