#!/usr/bin/env python3
"""
beta2_delta_source_proof.py — Prove WHY δ fails at source vertices

THEOREM ATTEMPT: For source v in tournament T on n≥5 vertices,
if β₁(T\v) > 0, then δ: H₂(T,T\v) → H₁(T\v) is the zero map.

Mechanism:
- Source v: all paths using v have v at position 0
- Relative Ω₂ ≅ {(v,b,c) : b→c in T\v} (all TT because v→everyone)
- Relative ∂₂(v,b,c) has T\v face = (b,c), i.e. ALL arcs of T\v
- The connecting map δ: relative Z₂ → Ω₁(T\v) sends Σ α_{bc}(v,b,c) ↦ Σ α_{bc}(b,c)
- The relative cycle condition forces: for each x, Σ_c α_{xc} = Σ_b α_{bx}
- This means Σ α_{bc}(b,c) is a balanced flow (1-cycle) on T\v
- Claim: these specific balanced flows are always BOUNDARIES in T\v

Key insight: The relative Ω₂ condition (not just TT, but Ω₂) imposes
additional constraints beyond flow conservation. But are those enough?

Actually, a simpler approach: ∂₂(v,b,c) = (b,c) - (v,c) + (v,b).
In Ω₁(T), this means the δ-image Σ α_{bc}(b,c) = ∂₂(Σ α_{bc}(v,b,c)) - [v-terms].
If Σ α_{bc}(v,b,c) ∈ Z₂(T) (not just relative Z₂), then ∂₂(lift) = 0 in Ω₁(T).
But we only need it in RELATIVE Z₂: ∂₂(lift) ∈ Ω₁(T\v).
The v-terms must cancel: Σ α_{bc}(v,b) - Σ α_{bc}(v,c) = 0.
Then δ-image = Σ α_{bc}(b,c) ∈ Ω₁(T\v).

For this to be a boundary in T\v, we need Σ α_{bc}(b,c) = ∂₂(Σ γ_{abc}(a,b,c))
for some Ω₂ element of T\v. Since T\v has n-1 vertices and (v source) T\v
is a tournament on n-1 vertices... but Ω₂(T\v) might be much smaller than
the space of balanced flows.

ALTERNATIVE: Maybe δ=0 because the relative H₂ is generated by
boundaries of relative 3-chains (i.e., h₂_rel = 0), not because δ maps to B₁.

Let me check: at the failure cases, is h₂_rel > 0?

Author: opus-2026-03-08-S49
"""
import sys, time
import numpy as np
from collections import Counter
sys.path.insert(0, '04-computation')
sys.stdout.reconfigure(line_buffering=True)

_saved = sys.stdout
sys.stdout = __import__('os').fdopen(__import__('os').open(__import__('os').devnull, __import__('os').O_WRONLY), 'w')
from path_homology_v2 import (
    enumerate_allowed_paths, compute_omega_basis,
    build_full_boundary_matrix
)
sys.stdout = _saved


def dim_om(om):
    return om.shape[1] if om.ndim == 2 and om.shape[0] > 0 else 0

def build_adj(n, bits):
    A = [[0]*n for _ in range(n)]
    idx = 0
    for i in range(n):
        for j in range(i+1, n):
            if bits & (1 << idx): A[i][j] = 1
            else: A[j][i] = 1
            idx += 1
    return A


print("=" * 70)
print("SOURCE VERTEX δ-FAILURE: COMPLETE ANALYSIS")
print("=" * 70)

# The 4 failure cases at n=5: T#36 v=4, T#37 v=4, T#387 v=1, T#586 v=3
failures_n5 = [(36, 4), (37, 4), (387, 1), (586, 3)]

for bits, v in failures_n5:
    n = 5
    A = build_adj(n, bits)
    scores = [sum(A[i][j] for j in range(n) if j!=i) for i in range(n)]
    dv = scores[v]

    others = [i for i in range(n) if i != v]
    n1 = n - 1
    A_sub = [[A[others[i]][others[j]] for j in range(n1)] for i in range(n1)]
    remap = {i: others[i] for i in range(n1)}
    inv_remap = {others[i]: i for i in range(n1)}

    print(f"\n{'─'*50}")
    print(f"T#{bits} v={v} d⁺={dv} scores={scores}")

    # Get all needed data
    ap0_T = enumerate_allowed_paths(A, n, 0)
    ap1_T = enumerate_allowed_paths(A, n, 1)
    ap2_T = enumerate_allowed_paths(A, n, 2)
    ap3_T = enumerate_allowed_paths(A, n, 3)

    ap0_sub = enumerate_allowed_paths(A_sub, n1, 0)
    ap1_sub = enumerate_allowed_paths(A_sub, n1, 1)
    ap2_sub = enumerate_allowed_paths(A_sub, n1, 2)
    ap3_sub = enumerate_allowed_paths(A_sub, n1, 3)

    om1_T = compute_omega_basis(A, n, 1, ap1_T, ap0_T)
    om2_T = compute_omega_basis(A, n, 2, ap2_T, ap1_T) if ap2_T else np.zeros((0,0))
    om3_T = compute_omega_basis(A, n, 3, ap3_T, ap2_T) if ap3_T else np.zeros((0,0))
    om1_sub = compute_omega_basis(A_sub, n1, 1, ap1_sub, ap0_sub)
    om2_sub = compute_omega_basis(A_sub, n1, 2, ap2_sub, ap1_sub) if ap2_sub else np.zeros((0,0))

    ap2_T_list = [tuple(p) for p in ap2_T]
    ap1_T_list = [tuple(p) for p in ap1_T]
    ap1_sub_list = [tuple(p) for p in ap1_sub]

    d2_T = dim_om(om2_T)
    d1_T = dim_om(om1_T)
    d1_sub = dim_om(om1_sub)
    d2_sub = dim_om(om2_sub)
    d3_T = dim_om(om3_T)

    # Paths using v
    paths_v = [(i, p) for i, p in enumerate(ap2_T_list) if v in p]
    paths_notv = [(i, p) for i, p in enumerate(ap2_T_list) if v not in p]

    print(f"  A₂ total: {len(ap2_T_list)}, using v: {len(paths_v)}, not: {len(paths_notv)}")
    print(f"  Ω₂(T) dim: {d2_T}, Ω₂(T\\v) dim: {d2_sub}")

    # Relative Ω₂
    if ap2_sub and d2_sub > 0:
        embed = np.zeros((len(ap2_T_list), d2_sub))
        for j in range(d2_sub):
            for k, path_sub in enumerate(ap2_sub):
                path_T = tuple(remap[x] for x in path_sub)
                if path_T in ap2_T_list:
                    embed[ap2_T_list.index(path_T), j] = om2_sub[k, j]
        phi = np.linalg.lstsq(om2_T, embed, rcond=None)[0]
    else:
        phi = np.zeros((d2_T, 0))

    rk_phi = np.linalg.matrix_rank(phi, tol=1e-8)
    if rk_phi > 0:
        U_phi, _, _ = np.linalg.svd(phi, full_matrices=True)
        Q = U_phi[:, rk_phi:]
    else:
        Q = np.eye(d2_T)

    d_rel = Q.shape[1]
    print(f"  Relative Ω₂ dim: {d_rel}")

    # Show relative Ω₂ basis explicitly (in terms of paths)
    rel_in_paths = om2_T @ Q  # (|A₂|, d_rel)
    for k in range(d_rel):
        col = rel_in_paths[:, k]
        nonzero = [(ap2_T_list[j], col[j]) for j in range(len(ap2_T_list)) if abs(col[j]) > 1e-8]
        print(f"  Rel basis {k}: {[(f'{c:.3f}*{p}') for p, c in nonzero]}")

    # The boundary map ∂₂ in coordinates
    coords2_T = np.linalg.lstsq(om1_T, build_full_boundary_matrix(ap2_T, ap1_T) @ om2_T, rcond=None)[0]

    # δ image: for each relative basis vector, compute ∂₂(lift) as Ω₁(T) element
    # Then restrict to T\v component
    print(f"\n  δ images (in Ω₁(T) arc coordinates):")
    for k in range(d_rel):
        q = Q[:, k]
        bd = coords2_T @ q  # in Ω₁(T) coords
        bd_arcs = om1_T @ bd  # in A₁ coords

        # Separate into T\v arcs and v-arcs
        tv_part = []
        v_part = []
        for j, arc in enumerate(ap1_T_list):
            if abs(bd_arcs[j]) > 1e-8:
                if v in arc:
                    v_part.append((arc, bd_arcs[j]))
                else:
                    tv_part.append((arc, bd_arcs[j]))

        print(f"  δ(rel_{k}):")
        print(f"    T\\v part: {[(f'{c:.3f}*{a}') for a,c in tv_part]}")
        print(f"    v part: {[(f'{c:.3f}*{a}') for a,c in v_part]}")

        # The v-parts should be zero (since we're in relative Z₂)
        v_total = sum(abs(c) for _, c in v_part)
        print(f"    |v-part| = {v_total:.6f}")

        # Check if T\v part is a boundary
        if tv_part:
            # Express in T\v Ω₁ coords
            tv_vec = np.zeros(len(ap1_sub_list))
            for arc, coeff in tv_part:
                # Map T arc to T\v arc
                a_sub = inv_remap.get(arc[0])
                b_sub = inv_remap.get(arc[1])
                if a_sub is not None and b_sub is not None:
                    sub_arc = (a_sub, b_sub)
                    if sub_arc in ap1_sub_list:
                        tv_vec[ap1_sub_list.index(sub_arc)] = coeff

            # Express in Ω₁(T\v) basis
            tv_om1_coords = np.linalg.lstsq(om1_sub, tv_vec, rcond=None)[0]

            # Check if in Z₁(T\v): ∂₁ applied should give 0
            bd1_sub = build_full_boundary_matrix(ap1_sub, ap0_sub)
            residual = bd1_sub @ om1_sub @ tv_om1_coords
            print(f"    ∂₁ of T\\v part: {np.max(np.abs(residual)):.6f} (should be ~0 for cycle)")

            # Check if in B₁(T\v): should be in im(∂₂(T\v))
            if d2_sub > 0:
                bd2_sub = build_full_boundary_matrix(ap2_sub, ap1_sub)
                bd2_in_om1 = np.linalg.lstsq(om1_sub, bd2_sub @ om2_sub, rcond=None)[0]
                # Can we express tv_om1_coords as a linear combination of bd2_in_om1 columns?
                fit, res, _, _ = np.linalg.lstsq(bd2_in_om1, tv_om1_coords, rcond=None)
                actual = bd2_in_om1 @ fit
                diff = np.max(np.abs(actual - tv_om1_coords))
                print(f"    Diff from B₁(T\\v): {diff:.6f} (0 = IS a boundary)")
                if diff < 1e-6:
                    print(f"    => δ image IS a boundary in T\\v (lands in B₁)")
                else:
                    print(f"    => δ image is NOT a boundary (nonzero in H₁)")
            else:
                print(f"    B₁(T\\v) = 0 (no Ω₂)")


print(f"\n{'='*70}")
print("GENERAL SOURCE THEOREM")
print("=" * 70)

# For ALL n=5 tournaments with source v and β₁(T\v) > 0,
# verify: δ maps relative H₂ entirely into B₁(T\v)

n = 5
m = n*(n-1)//2
source_b1_positive = 0
source_delta_in_B1 = 0
source_delta_not_in_B1 = 0

for bits in range(1 << m):
    A = build_adj(n, bits)
    scores = [sum(A[i][j] for j in range(n) if j!=i) for i in range(n)]

    for v in range(n):
        if scores[v] != n-1:
            continue  # only sources

        others = [i for i in range(n) if i != v]
        n1 = n - 1
        A_sub = [[A[others[i]][others[j]] for j in range(n1)] for i in range(n1)]
        remap = {i: others[i] for i in range(n1)}
        inv_remap = {others[i]: i for i in range(n1)}

        ap0_T = enumerate_allowed_paths(A, n, 0)
        ap1_T = enumerate_allowed_paths(A, n, 1)
        ap2_T = enumerate_allowed_paths(A, n, 2)
        ap3_T = enumerate_allowed_paths(A, n, 3)

        ap0_sub = enumerate_allowed_paths(A_sub, n1, 0)
        ap1_sub = enumerate_allowed_paths(A_sub, n1, 1)
        ap2_sub = enumerate_allowed_paths(A_sub, n1, 2)
        ap3_sub = enumerate_allowed_paths(A_sub, n1, 3)

        om1_T = compute_omega_basis(A, n, 1, ap1_T, ap0_T)
        om2_T = compute_omega_basis(A, n, 2, ap2_T, ap1_T) if ap2_T else np.zeros((0,0))
        om1_sub = compute_omega_basis(A_sub, n1, 1, ap1_sub, ap0_sub)
        om2_sub = compute_omega_basis(A_sub, n1, 2, ap2_sub, ap1_sub) if ap2_sub else np.zeros((0,0))

        d2_T = dim_om(om2_T)
        d1_sub = dim_om(om1_sub)
        d2_sub = dim_om(om2_sub)

        if d2_T == 0:
            continue

        ap2_T_list = [tuple(p) for p in ap2_T]
        ap1_T_list = [tuple(p) for p in ap1_T]
        ap1_sub_list = [tuple(p) for p in ap1_sub]

        # Check β₁(T\v)
        bd1_sub = build_full_boundary_matrix(ap1_sub, ap0_sub)
        rk_d1 = np.linalg.matrix_rank(bd1_sub @ om1_sub, tol=1e-8)
        z1_dim = d1_sub - rk_d1
        if d2_sub > 0:
            bd2_sub_full = build_full_boundary_matrix(ap2_sub, ap1_sub)
            bd2_in_om1 = np.linalg.lstsq(om1_sub, bd2_sub_full @ om2_sub, rcond=None)[0]
            rk_d2 = np.linalg.matrix_rank(bd2_in_om1, tol=1e-8)
        else:
            bd2_in_om1 = np.zeros((d1_sub, 0))
            rk_d2 = 0
        beta1 = z1_dim - rk_d2

        if beta1 == 0:
            continue

        source_b1_positive += 1

        # Compute relative Ω₂ basis
        if ap2_sub and d2_sub > 0:
            embed = np.zeros((len(ap2_T_list), d2_sub))
            for j in range(d2_sub):
                for k, path_sub in enumerate(ap2_sub):
                    path_T = tuple(remap[x] for x in path_sub)
                    if path_T in ap2_T_list:
                        embed[ap2_T_list.index(path_T), j] = om2_sub[k, j]
            phi = np.linalg.lstsq(om2_T, embed, rcond=None)[0]
        else:
            phi = np.zeros((d2_T, 0))

        rk_phi = np.linalg.matrix_rank(phi, tol=1e-8)
        if rk_phi > 0:
            U_phi, _, _ = np.linalg.svd(phi, full_matrices=True)
            Q = U_phi[:, rk_phi:]
        else:
            Q = np.eye(d2_T)

        d_rel = Q.shape[1]
        if d_rel == 0:
            continue

        coords2_T = np.linalg.lstsq(om1_T, build_full_boundary_matrix(ap2_T, ap1_T) @ om2_T, rcond=None)[0]

        # For each relative basis vector, compute δ image
        all_in_B1 = True
        for k in range(d_rel):
            q = Q[:, k]
            bd = coords2_T @ q
            bd_arcs = om1_T @ bd

            # Get T\v part
            tv_vec = np.zeros(len(ap1_sub_list))
            for j, arc in enumerate(ap1_T_list):
                if abs(bd_arcs[j]) > 1e-8 and v not in arc:
                    a_sub = inv_remap.get(arc[0])
                    b_sub = inv_remap.get(arc[1])
                    if a_sub is not None and b_sub is not None:
                        sub_arc = (a_sub, b_sub)
                        if sub_arc in ap1_sub_list:
                            tv_vec[ap1_sub_list.index(sub_arc)] = bd_arcs[j]

            if np.max(np.abs(tv_vec)) < 1e-8:
                continue  # δ image is zero, trivially in B₁

            tv_om1 = np.linalg.lstsq(om1_sub, tv_vec, rcond=None)[0]

            if d2_sub > 0:
                fit = np.linalg.lstsq(bd2_in_om1, tv_om1, rcond=None)[0]
                diff = np.max(np.abs(bd2_in_om1 @ fit - tv_om1))
                if diff > 1e-6:
                    all_in_B1 = False
            else:
                all_in_B1 = False

        if all_in_B1:
            source_delta_in_B1 += 1
        else:
            source_delta_not_in_B1 += 1
            print(f"  SOURCE NOT IN B₁: T#{bits} v={v}")

print(f"\nSource v with β₁(T\\v) > 0: {source_b1_positive}")
print(f"  δ image entirely in B₁: {source_delta_in_B1}")
print(f"  δ image NOT in B₁: {source_delta_not_in_B1}")


print(f"\n{'='*70}")
print("REFINED QUESTION: Why does source δ land in B₁?")
print("=" * 70)

# For source v: Ω₂(T) restricted to triples using v = {(v,b,c): b→c in T\v}
# These are ALL transitive triples involving v (since v→b and v→c automatic).
# But Ω₂(T) is NOT just TT triples — it's ker(∂₁ on A₂) / stuff.
#
# Actually, in GLMY: A₂ = {(a,b,c) : a→b, b→c}, and
# Ω₂ = {c ∈ R^{A₂} : ∂₂(c) ∈ R^{A₁} on Ω₁-coords}
#
# For source v, paths (v,b,c) with v→b (auto), b→c. These are ALL A₂ paths starting with v.
# TT = additionally v→c. NT = v←c (but v is source, so c→v impossible — wait, v is source so v→c always).
# ALL paths (v,b,c) are TT for source v!
#
# Now, the Ω₂ condition: ∂₂(v,b,c) = (b,c) - (v,c) + (v,b) must be in im(Ω₁).
# Since Ω₁ = R^{A₁} for this purpose... actually Ω₁ is defined as:
# {c ∈ R^{A₁} : ∂₁(c) ∈ R^{A₀}} and since ∂₁ always lands in R^{A₀}, Ω₁ = R^{A₁}.
# No wait, Ω₁ needs ∂₁(c) to be a linear combination of vertices (A₀ paths).
# ∂₁(a,b) = (b) - (a), which is always in R^{A₀}. So Ω₁ = R^{A₁}.
#
# Then Ω₂ = {c ∈ R^{A₂} : ∂₂(c) ∈ R^{A₁}}. But ∂₂(c) is always in R^{A₁} if we use
# the definition ∂₂(a,b,c) = (b,c) - (a,c) + (a,b). These are all A₁ paths.
# Wait, (a,c) is an A₁ path only if a→c. If a←c, then (a,c) is NOT in A₁.
#
# That's the key: ∂₂(a,b,c) = (b,c) - (a,c) + (a,b).
# (a,c) ∈ A₁ iff a→c (TT case).
# If a←c (NT case), then (a,c) ∉ A₁, and we need ∂₂(c) ∈ span(A₁ arcs).
#
# For the Ω-computation: we work in the A-path basis.
# ∂₂(a,b,c) = (b,c) - ε(a→c)(a,c) + (a,b) where ε=1 if a→c, 0 otherwise...
# NO. The boundary is computed using ALL 2-faces, even non-allowed ones.
# But in the CHAIN complex, we only allow A_p paths.
# The boundary ∂_p: R^{A_p} → R^{A_{p-1}} maps by the simplicial-type boundary
# but only keeps the A_{p-1} components.

# Actually the GLMY definition is:
# ∂_p(v_0,...,v_p) = Σ_{i=0}^{p} (-1)^i (v_0,...,v̂_i,...,v_p)
# where (v_0,...,v̂_i,...,v_p) is set to 0 if it's not an allowed path.
#
# So ∂₂(a,b,c) = (b,c) - (a,c)_{A₁} + (a,b)
# where (a,c)_{A₁} = (a,c) if a→c, else 0.
#
# For TT path (v,b,c): ∂₂ = (b,c) - (v,c) + (v,b)  [all three faces are in A₁]
# For NT path (a,b,c) with a←c: ∂₂ = (b,c) + (a,b)  [face (a,c) is NOT in A₁]
#
# Ω₂ condition: ∂₂(chain) must land in R^{A₁}... but it automatically does
# since we only keep A₁ faces. So what is Ω₂?
#
# Actually, looking at the code: compute_omega_basis computes
# Ω_p = ker(ε_p) where ε_p(v_0,...,v_p) = ∂_{p-1} ∘ ∂_p.
# The condition is ∂_{p-1}(∂_p(chain)) = 0 in R^{A_{p-2}}.
# This is NOT automatic because ∂_p drops some faces.

# Let me re-read the actual computation.
print("Checking the actual Ω₂ computation method...")

# From path_homology_v2.py:
# compute_omega_basis computes Ω_p = {c : ∂_{p-1}(∂_p(c)) = 0}
# So Ω₂ = {c ∈ R^{A₂} : ∂_1(∂_2(c)) = 0 in R^{A_0}}

# ∂₁(a,b) = (b) - (a)
# ∂₂(a,b,c) = (b,c)_{A₁} - (a,c)_{A₁} + (a,b)_{A₁}
# ∂₁(∂₂(a,b,c)) = ∂₁((b,c)) - ∂₁((a,c)_{A₁}) + ∂₁((a,b))
# = [(c)-(b)] - [if a→c: (c)-(a)] + [(b)-(a)]
#
# If a→c (TT): = (c)-(b)-(c)+(a)+(b)-(a) = 0. Always.
# If a←c (NT): = (c)-(b)+0+(b)-(a) = (c)-(a).
#
# So Ω₂ = {chains where the NT paths cancel in the ∂₁∘∂₂ sense}
# Specifically: Σ α_{abc} (c_i - a_i) = 0 summed over NT paths.
# Each NT path (a,b,c) contributes (c) - (a) to ∂₁∘∂₂.
# So: Σ_{NT (a,b,c)} α_{abc} [(c) - (a)] = 0.
# This means: for each vertex w, #{NT paths with c=w} weighted by α = #{NT paths with a=w} weighted by α.
#
# For source v: ALL (v,b,c) paths are TT (since v→c). So the Ω₂ condition
# is automatically satisfied for any combination of source-v paths.
# Ω₂ restricted to v-paths = ALL combinations of (v,b,c) with b→c.

# This is important! For source v, there are NO constraints from the Ω₂ condition.
# The ONLY constraint on the relative 2-cycle comes from the relative boundary condition.

print("\nFor source v:")
print("  ALL paths (v,b,c) are TT (since v→c automatically)")
print("  Ω₂ condition: ∂₁∘∂₂ = 0 is AUTOMATIC for TT paths")
print("  So relative Ω₂ = span{(v,b,c) : b→c in T\\v} / Ω₂(T\\v)")
print("  = ALL combinations of source-v TT triples")
print()
print("For interior v:")
print("  Some paths (a,b,c) using v are NT (the skipped face is NOT an arc)")
print("  Ω₂ condition imposes NONTRIVIAL constraints on NT path coefficients")
print("  This couples the three position types and constrains relative Ω₂")


# Part 2: For interior v, count how many of the v-paths are NT vs TT
print(f"\n{'='*70}")
print("NT/TT counts for interior vs source paths")
print("=" * 70)

n = 5
m = n*(n-1)//2

tt_nt_counts = {'source': Counter(), 'interior': Counter()}

for bits in range(1 << m):
    A = build_adj(n, bits)
    scores = [sum(A[i][j] for j in range(n) if j!=i) for i in range(n)]

    ap2_T = enumerate_allowed_paths(A, n, 2)
    ap2_T_list = [tuple(p) for p in ap2_T]

    for v in range(n):
        dv = scores[v]
        vtype = 'source' if dv == n-1 else ('interior' if 1 <= dv <= n-2 else 'sink')

        if vtype == 'sink':
            continue

        tt_count = 0
        nt_count = 0
        for p in ap2_T_list:
            if v not in p:
                continue
            a, b, c = p
            if A[a][c]:
                tt_count += 1
            else:
                nt_count += 1

        tt_nt_counts[vtype][(tt_count, nt_count)] += 1

print("\nSource vertex (d⁺=n-1):")
for (tt, nt), cnt in sorted(tt_nt_counts['source'].items()):
    print(f"  TT={tt}, NT={nt}: {cnt} cases")

print("\nInterior vertex (1 ≤ d⁺ ≤ n-2):")
for (tt, nt), cnt in sorted(tt_nt_counts['interior'].items())[:20]:
    print(f"  TT={tt}, NT={nt}: {cnt} cases")


print(f"\n{'='*70}")
print("KEY INSIGHT SUMMARY")
print("=" * 70)
print("""
For source v (d⁺=n-1):
  - ALL paths through v are TT → Ω₂ condition is automatic
  - v only at position 0 → limited boundary structure
  - δ-image is a balanced flow on T\\v → can land in B₁
  - RESULT: δ can fail to be injective

For interior v (1 ≤ d⁺ ≤ n-2):
  - Some paths through v are NT → Ω₂ condition CONSTRAINS coefficients
  - v at positions 0, 1, AND 2 → diverse boundary structure
  - δ-image mixes contributions from all position types → harder to be 0
  - RESULT: δ is always injective (HYP-249)

The proof strategy should show:
  (A) The Ω₂ constraint on NT paths using v COUPLES different positions
  (B) This coupling prevents δ from mapping everything to B₁(T\\v)
  (C) Specifically: if δ(z) ∈ B₁, the NT coupling forces z ∈ im(∂₃^rel)

This is analogous to how "mixed-type" constraints in linear programming
prevent degeneracy — the diversity of constraint types ensures full rank.
""")

print("Done.")
