#!/usr/bin/env python3
"""
beta3_rank_saturation.py — opus-2026-03-09-S52

Investigate the rank near-saturation property for d_4:
  beta_3 = ker(d_3) - im(d_4)

For beta_3 in {0,1}, we need im(d_4) = ker(d_3) or ker(d_3)-1 always.

Compute the full chain complex Omega_* and boundary maps d_* for tournaments.
Focus on levels 3,4,5 (the chain around beta_3).
"""

import numpy as np
from itertools import combinations, permutations
from collections import Counter
import sys

def tournament_from_bits(n, bits):
    """Create tournament adjacency matrix from bit pattern."""
    T = [[0]*n for _ in range(n)]
    idx = 0
    for i in range(n):
        for j in range(i+1, n):
            if bits & (1 << idx):
                T[i][j] = 1
            else:
                T[j][i] = 1
            idx += 1
    return T

def is_allowed_path(T, path):
    """Check if path is an allowed p-path in the GLMY sense.
    A p-path (v0, v1, ..., vp) is allowed if:
    1. v_i -> v_{i+1} for all i (directed path)
    2. All vertices distinct
    """
    for i in range(len(path)-1):
        if not T[path[i]][path[i+1]]:
            return False
    return len(path) == len(set(path))

def get_omega_p(T, n, p):
    """Get basis of Omega_p: allowed p-paths modulo non-allowed (p-1)-faces.

    Actually, Omega_p = {f in A_p : all (p-1)-faces of f are in A_{p-1} or
    the face is "not allowed"}.

    More precisely: A p-path sigma is in Omega_p if for every (p-1)-face
    obtained by removing an interior vertex, the face is an allowed (p-1)-path.

    Wait, the GLMY definition:
    Omega_p = {sum c_sigma * sigma : for every not-allowed (p-1)-path tau,
               the coefficient of tau in d_p(sum c_sigma * sigma) is 0}

    So Omega_p is the kernel of the "projection to non-allowed faces" map.
    Equivalently, Omega_p consists of allowed p-paths sigma such that
    all their faces are either allowed or cancel out.

    Actually, let me be more careful. In GLMY:
    - A_p = set of allowed p-paths (directed paths with distinct vertices)
    - R_p = subspace generated by elements whose boundary has non-allowed faces
    - Omega_p = A_p / R_p... no.

    Actually the correct definition:
    - A_p = free abelian group on allowed p-paths
    - d_p: A_p -> A_{p-1} is the usual boundary (alternating sum of face deletions)
    - Some faces may not be allowed paths
    - Omega_p = {x in A_p : d_p(x) has no component in non-allowed (p-1)-paths}
    - Equivalently: Omega_p = intersection of A_p with d_p^{-1}(A_{p-1})
    """
    # Get all allowed p-paths
    allowed_p = []
    for verts in combinations(range(n), p+1):
        for perm in permutations(verts):
            if is_allowed_path(T, perm):
                allowed_p.append(perm)

    if not allowed_p:
        return [], np.zeros((0, 0))

    # Get all allowed (p-1)-paths
    allowed_pm1 = set()
    for verts in combinations(range(n), p):
        for perm in permutations(verts):
            if is_allowed_path(T, perm):
                allowed_pm1.add(perm)

    # For each allowed p-path, compute its boundary faces
    # Face i of (v0,...,vp) = (v0,...,v_{i-1},v_{i+1},...,vp) with sign (-1)^i
    # But we only keep faces that are allowed AND drop those that aren't
    # Actually: Omega_p = {x : all non-allowed faces cancel}

    # Build the "non-allowed face" matrix
    # For each p-path and each face position, check if the face is allowed
    # Omega_p = kernel of the "NA projection" map

    # Collect all non-allowed (p-1)-paths that appear as faces
    na_faces = {}  # na_path -> index
    na_rows = []

    for sigma_idx, sigma in enumerate(allowed_p):
        for i in range(len(sigma)):
            if i == 0 or i == len(sigma)-1:
                continue  # only interior faces matter for GLMY
            face = sigma[:i] + sigma[i+1:]
            if face not in allowed_pm1:
                if face not in na_faces:
                    na_faces[face] = len(na_faces)

    if not na_faces:
        # All faces are allowed, Omega_p = A_p
        return allowed_p, None

    # Build NA matrix: rows = NA faces, cols = allowed p-paths
    na_matrix = np.zeros((len(na_faces), len(allowed_p)), dtype=np.float64)
    for sigma_idx, sigma in enumerate(allowed_p):
        for i in range(len(sigma)):
            if i == 0 or i == len(sigma)-1:
                continue
            face = sigma[:i] + sigma[i+1:]
            if face in na_faces:
                na_matrix[na_faces[face], sigma_idx] += (-1)**i

    # Omega_p = kernel of na_matrix
    if na_matrix.shape[0] == 0:
        return allowed_p, None

    return allowed_p, na_matrix

def compute_chain_complex(T, n, max_p=None):
    """Compute the full GLMY chain complex for tournament T.

    Returns dict with:
    - omega_dim[p] = dim(Omega_p)
    - rank_dp[p] = rank of d_p: Omega_p -> Omega_{p-1}
    - betti[p] = beta_p
    """
    if max_p is None:
        max_p = n - 1

    # Step 1: Find all allowed paths at each level
    all_allowed = {}
    for p in range(0, max_p + 2):  # need p+1 for Omega_p constraint
        paths = []
        for verts in combinations(range(n), p+1):
            for perm in permutations(verts):
                if is_allowed_path(T, perm):
                    paths.append(perm)
        all_allowed[p] = paths

    # Step 2: Build Omega_p for each level
    omega_basis = {}
    for p in range(0, max_p + 1):
        a_p = all_allowed[p]
        if not a_p:
            omega_basis[p] = []
            continue

        a_pm1_set = set(all_allowed[p-1]) if p > 0 else set()

        # Find NA interior faces
        na_faces_map = {}
        for sigma in a_p:
            for i in range(1, len(sigma)-1):  # interior vertices only
                face = sigma[:i] + sigma[i+1:]
                if face not in a_pm1_set and p > 0:
                    if face not in na_faces_map:
                        na_faces_map[face] = len(na_faces_map)

        if not na_faces_map:
            omega_basis[p] = list(range(len(a_p)))
            continue

        # Build NA constraint matrix
        na_mat = np.zeros((len(na_faces_map), len(a_p)))
        for j, sigma in enumerate(a_p):
            for i in range(1, len(sigma)-1):
                face = sigma[:i] + sigma[i+1:]
                if face in na_faces_map:
                    na_mat[na_faces_map[face], j] += (-1)**i

        # Omega_p = ker(na_mat)
        from numpy.linalg import svd
        U, S, Vt = svd(na_mat, full_matrices=True)
        tol = 1e-8
        rank = np.sum(S > tol)
        # Kernel = last (cols - rank) rows of Vt
        null_dim = len(a_p) - rank
        omega_basis[p] = Vt[rank:].T  # columns are basis vectors

        # Store as matrix whose columns are the Omega_p basis
        # Each column is a linear combination of allowed p-paths

    # Step 3: Build boundary maps d_p: Omega_p -> Omega_{p-1}
    results = {'omega_dim': {}, 'rank_dp': {}, 'betti': {}}

    # Recompute more carefully with explicit Omega bases
    # Use the approach: compute d_p on allowed paths, project to Omega

    # For efficiency, let me compute using the raw boundary on allowed paths
    # and then restrict

    # Actually, let me use a simpler approach: compute d_p as matrix on A_p -> A_{p-1}
    # Then restrict rows to Omega_{p-1} and columns to Omega_p

    # Build boundary matrix d_p: A_p -> A_{p-1}
    boundary = {}
    for p in range(1, max_p + 1):
        a_p = all_allowed[p]
        a_pm1 = all_allowed[p-1]
        if not a_p or not a_pm1:
            boundary[p] = np.zeros((len(a_pm1) if a_pm1 else 0, len(a_p) if a_p else 0))
            continue

        idx_pm1 = {path: i for i, path in enumerate(a_pm1)}
        mat = np.zeros((len(a_pm1), len(a_p)))

        for j, sigma in enumerate(a_p):
            for i in range(len(sigma)):
                face = sigma[:i] + sigma[i+1:]
                if face in idx_pm1:
                    mat[idx_pm1[face], j] += (-1)**i

        boundary[p] = mat

    # Now compute Omega_p as ker of NA projection
    omega_projectors = {}  # p -> matrix whose columns span Omega_p in A_p coords

    for p in range(0, max_p + 1):
        a_p = all_allowed[p]
        if not a_p:
            omega_projectors[p] = np.zeros((0, 0))
            results['omega_dim'][p] = 0
            continue

        a_pm1_set = set(all_allowed[p-1]) if p > 0 else set()

        na_faces_map = {}
        for sigma in a_p:
            for i in range(1, len(sigma)-1):
                face = sigma[:i] + sigma[i+1:]
                if p > 0 and face not in a_pm1_set:
                    if face not in na_faces_map:
                        na_faces_map[face] = len(na_faces_map)

        if not na_faces_map:
            omega_projectors[p] = np.eye(len(a_p))
            results['omega_dim'][p] = len(a_p)
            continue

        na_mat = np.zeros((len(na_faces_map), len(a_p)))
        for j, sigma in enumerate(a_p):
            for i in range(1, len(sigma)-1):
                face = sigma[:i] + sigma[i+1:]
                if face in na_faces_map:
                    na_mat[na_faces_map[face], j] += (-1)**i

        U, S, Vt = np.linalg.svd(na_mat, full_matrices=True)
        tol = 1e-8
        rank = int(np.sum(S > tol))
        null_dim = len(a_p) - rank

        if null_dim == 0:
            omega_projectors[p] = np.zeros((len(a_p), 0))
            results['omega_dim'][p] = 0
        else:
            omega_projectors[p] = Vt[rank:].T  # (|A_p| x null_dim)
            results['omega_dim'][p] = null_dim

    # Build restricted boundary: d_p restricted to Omega_p -> Omega_{p-1}
    for p in range(1, max_p + 1):
        Om_p = omega_projectors[p]
        Om_pm1 = omega_projectors[p-1]

        if Om_p.shape[1] == 0 or Om_pm1.shape[1] == 0:
            results['rank_dp'][p] = 0
            continue

        # d_p maps Omega_p into A_{p-1}. We need the component in Omega_{p-1}.
        # d_p|_{Omega_p} = boundary[p] @ Om_p  (in A_{p-1} coords)
        # Project to Omega_{p-1}: Om_pm1.T @ (boundary[p] @ Om_p)

        if p in boundary:
            dp_omega = boundary[p] @ Om_p  # (|A_{p-1}| x dim(Omega_p))
            # Project to Omega_{p-1} basis
            dp_restricted = Om_pm1.T @ dp_omega  # (dim(Omega_{p-1}) x dim(Omega_p))

            S = np.linalg.svd(dp_restricted, compute_uv=False)
            results['rank_dp'][p] = int(np.sum(S > 1e-8))
        else:
            results['rank_dp'][p] = 0

    # Compute Betti numbers
    for p in range(0, max_p + 1):
        ker_dp = results['omega_dim'][p] - results['rank_dp'].get(p, 0)
        im_dp1 = results['rank_dp'].get(p+1, 0)
        results['betti'][p] = ker_dp - im_dp1

    return results

def main():
    print("=" * 70)
    print("BETA_3 RANK SATURATION ANALYSIS")
    print("Goal: show im(d_4) = ker(d_3) or ker(d_3)-1 always")
    print("=" * 70)

    for n in [5, 6, 7]:
        print(f"\n{'='*70}")
        print(f"n = {n}")
        print(f"{'='*70}")

        num_arcs = n*(n-1)//2
        total = 1 << num_arcs

        if n <= 6:
            # Exhaustive
            sample_size = total
            indices = range(total)
            method = "exhaustive"
        else:
            # Sample
            sample_size = min(500, total)
            rng = np.random.RandomState(42)
            indices = rng.randint(0, total, sample_size)
            method = f"sampled ({sample_size})"

        print(f"Method: {method}")

        # For level 3 analysis
        # beta_3 = ker(d_3) - im(d_4)
        # We want: gap = ker(d_3) - im(d_4) in {0, 1}

        gap_counts = Counter()
        beta3_counts = Counter()

        # Track detailed data for beta_3 > 0 cases
        beta3_pos_data = []

        # Also track: dim(Omega_p) for p=3,4,5
        dim_data = {3: [], 4: [], 5: []}
        rank_data = {3: [], 4: [], 5: []}

        max_p = min(n-1, 6)  # don't compute beyond what exists

        for count, bits in enumerate(indices):
            if n <= 6 and count % 5000 == 0 and count > 0:
                print(f"  ... {count}/{sample_size}")
            elif n == 7 and count % 100 == 0 and count > 0:
                print(f"  ... {count}/{sample_size}")

            T = tournament_from_bits(n, bits)
            res = compute_chain_complex(T, n, max_p=max_p)

            beta3 = res['betti'].get(3, 0)
            beta3_counts[beta3] += 1

            ker_d3 = res['omega_dim'].get(3, 0) - res['rank_dp'].get(3, 0)
            im_d4 = res['rank_dp'].get(4, 0)
            gap = ker_d3 - im_d4  # = beta_3
            gap_counts[gap] += 1

            for p in [3, 4, 5]:
                if p in res['omega_dim']:
                    dim_data[p].append(res['omega_dim'][p])
                if p in res['rank_dp']:
                    rank_data[p].append(res['rank_dp'][p])

            if beta3 > 0:
                beta3_pos_data.append({
                    'bits': bits,
                    'omega': {p: res['omega_dim'].get(p, 0) for p in range(max_p+1)},
                    'rank': {p: res['rank_dp'].get(p, 0) for p in range(1, max_p+1)},
                    'betti': {p: res['betti'].get(p, 0) for p in range(max_p+1)},
                    'ker_d3': ker_d3,
                    'im_d4': im_d4,
                    'gap': gap
                })

        print(f"\n  beta_3 distribution: {dict(sorted(beta3_counts.items()))}")
        print(f"  gap = ker(d_3) - im(d_4) distribution: {dict(sorted(gap_counts.items()))}")

        if dim_data[3]:
            print(f"\n  dim(Omega_3): min={min(dim_data[3])}, max={max(dim_data[3])}, "
                  f"mean={np.mean(dim_data[3]):.1f}")
        if dim_data[4]:
            print(f"  dim(Omega_4): min={min(dim_data[4])}, max={max(dim_data[4])}, "
                  f"mean={np.mean(dim_data[4]):.1f}")
        if dim_data[5]:
            print(f"  dim(Omega_5): min={min(dim_data[5])}, max={max(dim_data[5])}, "
                  f"mean={np.mean(dim_data[5]):.1f}")

        if rank_data[3]:
            print(f"\n  rank(d_3): min={min(rank_data[3])}, max={max(rank_data[3])}")
        if rank_data[4]:
            print(f"  rank(d_4): min={min(rank_data[4])}, max={max(rank_data[4])}")
        if rank_data[5]:
            print(f"  rank(d_5): min={min(rank_data[5])}, max={max(rank_data[5])}")

        # Detailed analysis of beta_3 > 0 cases
        if beta3_pos_data:
            print(f"\n  --- beta_3 > 0 cases ({len(beta3_pos_data)}) ---")
            for i, d in enumerate(beta3_pos_data[:10]):
                print(f"    Case {i+1}: omega_dims={[d['omega'].get(p,0) for p in range(max_p+1)]}")
                print(f"      ranks={[d['rank'].get(p,0) for p in range(1,max_p+1)]}")
                print(f"      betti={[d['betti'].get(p,0) for p in range(max_p+1)]}")
                print(f"      ker(d3)={d['ker_d3']}, im(d4)={d['im_d4']}, gap={d['gap']}")

            if len(beta3_pos_data) > 10:
                print(f"    ... ({len(beta3_pos_data) - 10} more)")

            # Check gap distribution for beta_3 > 0
            pos_gaps = Counter(d['gap'] for d in beta3_pos_data)
            print(f"\n    Gap distribution among beta_3>0: {dict(sorted(pos_gaps.items()))}")

            # Check ker(d_3) values
            kd3_vals = Counter(d['ker_d3'] for d in beta3_pos_data)
            print(f"    ker(d_3) values among beta_3>0: {dict(sorted(kd3_vals.items()))}")

            # Check rank(d_4) values relative to dim(Omega_4) and ker(d_3)
            print(f"\n    rank(d_4) / dim(Omega_4) ratios:")
            for d in beta3_pos_data[:5]:
                om4 = d['omega'].get(4, 0)
                rk4 = d['rank'].get(4, 0)
                print(f"      rk(d4)={rk4}, dim(O4)={om4}, ratio={rk4/om4:.3f}" if om4 > 0 else "      dim(O4)=0")

        # KEY ANALYSIS: rank(d_4) takes how many values relative to ker(d_3)?
        if rank_data[4] and rank_data[3]:
            # For each tournament, compute: rank(d_4) - (ker(d_3) - 1)
            # If beta_3 in {0,1}, this should be in {0, 1}
            print(f"\n  --- rank saturation analysis ---")
            sat_vals = Counter()
            for idx in range(len(rank_data[4])):
                ker_d3 = dim_data[3][idx] - rank_data[3][idx] if idx < len(dim_data[3]) else 0
                im_d4 = rank_data[4][idx]
                # rank(d_4) should be ker(d_3) or ker(d_3)-1
                deficit = ker_d3 - im_d4  # = beta_3
                sat_vals[deficit] += 1
            print(f"  Saturation deficit (ker_d3 - rk_d4 = beta_3): {dict(sorted(sat_vals.items()))}")

if __name__ == '__main__':
    main()
