#!/usr/bin/env python3
"""
beta2_explicit_surj.py - Explicit surjectivity construction for d3 -> Z2

Understand the EXACT algebraic structure of d3: Om3 -> Z2 for tournaments.

For n=4, there are 4 tournament types. Show how d3 maps Om3 to Z2
in each case. Then generalize to n=5.

Author: kind-pasteur-2026-03-08-S41
"""
import sys, os, time
import numpy as np
from collections import Counter, defaultdict
sys.path.insert(0, '04-computation')
sys.stdout.reconfigure(line_buffering=True)

_saved = sys.stdout
sys.stdout = open(os.devnull, 'w', encoding='utf-8')
from path_homology_v2 import (
    enumerate_allowed_paths, compute_omega_basis,
    build_full_boundary_matrix, path_betti_numbers
)
sys.stdout = _saved


def build_adj(n, bits):
    A = [[0]*n for _ in range(n)]
    idx = 0
    for i in range(n):
        for j in range(i+1, n):
            if bits & (1 << idx):
                A[i][j] = 1
            else:
                A[j][i] = 1
            idx += 1
    return A


# ============================================================
# n=4: Complete analysis of all tournament types
# ============================================================
print("=" * 70)
print("N=4 TOURNAMENT TYPES: COMPLETE CHAIN COMPLEX ANALYSIS")
print("=" * 70)

n = 4
seen_scores = set()

for bits in range(1 << (n*(n-1)//2)):
    A = build_adj(n, bits)
    scores = tuple(sorted([sum(row) for row in A]))
    if scores in seen_scores:
        continue
    seen_scores.add(scores)

    c3 = sum(1 for i in range(n) for j in range(i+1,n) for k in range(j+1,n)
             if (A[i][j] and A[j][k] and A[k][i]) or (A[j][i] and A[k][j] and A[i][k]))

    a0 = [(i,) for i in range(n)]
    a1 = enumerate_allowed_paths(A, n, 1)
    a2 = enumerate_allowed_paths(A, n, 2)
    a3 = enumerate_allowed_paths(A, n, 3)

    print(f"\n--- Score {scores}, c3={c3} ---")
    print(f"A: {[list(row) for row in A]}")
    print(f"|A0|={len(a0)}, |A1|={len(a1)}, |A2|={len(a2)}, |A3|={len(a3)}")

    om1 = compute_omega_basis(A, n, 1, a1, a0)
    om2 = compute_omega_basis(A, n, 2, a2, a1)
    om3 = compute_omega_basis(A, n, 3, a3, a2)
    d_om1 = om1.shape[1] if om1.ndim == 2 else 0
    d_om2 = om2.shape[1] if om2.ndim == 2 else 0
    d_om3 = om3.shape[1] if om3.ndim == 2 else 0

    bd1 = build_full_boundary_matrix(a1, a0)
    bd2 = build_full_boundary_matrix(a2, a1)

    print(f"Om1={d_om1}, Om2={d_om2}, Om3={d_om3}")

    # Show which 2-paths have junk faces
    print(f"2-paths:")
    for p in a2:
        face_ac = "jk" if A[p[2]][p[0]] else "ok"
        print(f"  {p}: d1=({p[0]},{p[2]}) [{face_ac}]")

    # Show which 3-paths have junk faces
    if a3:
        print(f"3-paths:")
        for p in a3:
            d1_junk = "jk" if A[p[2]][p[0]] else "ok"  # d1 = (a,c,d), junk if c->a
            d2_junk = "jk" if A[p[3]][p[1]] else "ok"  # d2 = (a,b,d), junk if d->b
            dd = "DD" if d1_junk == "ok" and d2_junk == "ok" else ""
            print(f"  {p}: d1=({p[0]},{p[2]},{p[3]})[{d1_junk}], d2=({p[0]},{p[1]},{p[3]})[{d2_junk}] {dd}")

    # Z2 computation
    if d_om2 > 0:
        bd2_om = bd2 @ om2
        S = np.linalg.svd(bd2_om, compute_uv=False)
        rk2 = sum(s > 1e-8 for s in S)
        z2 = d_om2 - rk2
        print(f"rk(d2)={rk2}, Z2={z2}")

        if z2 > 0:
            U, S_vals, Vt = np.linalg.svd(bd2_om, full_matrices=True)
            z2_om = Vt[rk2:].T
            z2_a2 = om2 @ z2_om
            for col in range(z2):
                z = z2_a2[:, col]
                print(f"  Z2[{col}] = ", end="")
                terms = []
                for i in range(len(z)):
                    if abs(z[i]) > 1e-8:
                        terms.append(f"{z[i]:+.3f}*{a2[i]}")
                print(" ".join(terms))

        # d3 map
        if d_om3 > 0:
            bd3 = build_full_boundary_matrix(a3, a2)
            bd3_om = bd3 @ om3
            for col in range(d_om3):
                w = om3[:, col]
                dw = bd3_om[:, col]  # = bd3 @ om3[:, col] in A2 coords
                print(f"  d3(Om3[{col}]) = ", end="")
                terms = []
                for i in range(len(dw)):
                    if abs(dw[i]) > 1e-8:
                        terms.append(f"{dw[i]:+.3f}*{a2[i]}")
                print(" ".join(terms))

    print()


# ============================================================
# PATTERN ANALYSIS: For n=4, what generates Z2?
# ============================================================
print(f"\n{'='*70}")
print("N=4 Z2 GENERATORS")
print("=" * 70)

# Key observation from above:
# Score (0,1,2,3) transitive: Z2=1, generated by formal sum of
# all 2-paths on the 4 vertices with alternating signs.
# This is the "2-simplex boundary" - the Z2 element is the
# simplicial 2-cycle of the 3-simplex.

# Score (1,1,2,2) with c3=2: Z2=1, generated by a specific
# combination of 2-paths related to the two 3-cycles.

# Score (0,2,2,2) and (1,1,1,3): Z2=0!
# These have exactly one 3-cycle, and Z2 is trivial.

# So Z2 = 0 when there's at most one 3-cycle in the 4-vertex tournament.
# Z2 = 1 when there are 0 or 2 3-cycles... wait, (0,1,2,3) has 0 3-cycles
# but Z2=1. Let me re-check.

print("Score -> (c3, Z2) at n=4:")
for bits in range(1 << (n*(n-1)//2)):
    A = build_adj(n, bits)
    scores = tuple(sorted([sum(row) for row in A]))
    c3 = sum(1 for i in range(n) for j in range(i+1,n) for k in range(j+1,n)
             if (A[i][j] and A[j][k] and A[k][i]) or (A[j][i] and A[k][j] and A[i][k]))

    a1 = enumerate_allowed_paths(A, n, 1)
    a2 = enumerate_allowed_paths(A, n, 2)
    om2 = compute_omega_basis(A, n, 2, a2, a1)
    d_om2 = om2.shape[1] if om2.ndim == 2 else 0

    if d_om2 > 0:
        bd2 = build_full_boundary_matrix(a2, a1)
        bd2_om = bd2 @ om2
        S = np.linalg.svd(bd2_om, compute_uv=False)
        rk2 = sum(s > 1e-8 for s in S)
        z2 = d_om2 - rk2
    else:
        z2 = 0

    # Only print unique
    pass

# Summary from above
print("(0,1,2,3), c3=0: Om2=4, Z2=1, Om3=1 => d3 is iso (1-to-1)")
print("(0,2,2,2), c3=1: Om2=3, Z2=0, Om3=0 => trivial")
print("(1,1,1,3), c3=1: Om2=3, Z2=0, Om3=0 => trivial")
print("(1,1,2,2), c3=2: Om2=3, Z2=1, Om3=1 => d3 is iso (1-to-1)")

print("\nKEY INSIGHT: Z2 = 1 iff c3 is even (0 or 2) at n=4")
print("And when Z2=1, Om3=1, and d3 is an isomorphism.")
print("When Z2=0, Om3=0 trivially.")
print("So beta2=0 at n=4 is immediate from the dimension matching!")


# ============================================================
# At n=5: What determines dim(Z2)?
# ============================================================
print(f"\n{'='*70}")
print("N=5: WHAT DETERMINES dim(Z2)?")
print("=" * 70)

n = 5
z2_by_inv = defaultdict(list)
for bits in range(1 << (n*(n-1)//2)):
    A = build_adj(n, bits)
    scores = tuple(sorted([sum(row) for row in A]))
    c3 = sum(1 for i in range(n) for j in range(i+1,n) for k in range(j+1,n)
             if (A[i][j] and A[j][k] and A[k][i]) or (A[j][i] and A[k][j] and A[i][k]))

    a1 = enumerate_allowed_paths(A, n, 1)
    a2 = enumerate_allowed_paths(A, n, 2)
    om2 = compute_omega_basis(A, n, 2, a2, a1)
    d_om2 = om2.shape[1] if om2.ndim == 2 else 0

    bd2 = build_full_boundary_matrix(a2, a1)
    if d_om2 > 0:
        bd2_om = bd2 @ om2
        S = np.linalg.svd(bd2_om, compute_uv=False)
        rk2 = sum(s > 1e-8 for s in S)
        z2 = d_om2 - rk2
    else:
        z2 = 0

    betti = path_betti_numbers(A, n, max_dim=1)
    b1 = betti[1]
    z2_by_inv[(scores, c3, b1)].append(z2)

print(f"{'Scores':<20} {'c3':>3} {'b1':>3} {'Z2 values':<20}")
for (sc, c3, b1) in sorted(z2_by_inv.keys()):
    vals = Counter(z2_by_inv[(sc, c3, b1)])
    print(f"{str(sc):<20} {c3:>3} {b1:>3} {dict(sorted(vals.items()))}")


# ============================================================
# CRITICAL RELATIONSHIP: dim(Z2) = C(n-1,2) - rk(d2|Om2)
# And rk(d2) = dim(Om2) - dim(Z2) = dim(Om2) - (dim(Z1) - beta1)
# Wait: Z2 = dim(Om2) - rk(d2)
# and Z1 = dim(Om1) - rk(d1) = C(n,2) - (n-1)
# and rk(d2) = dim(Z1) - beta1 = C(n,2) - (n-1) - beta1 = C(n-1,2) - beta1
# So Z2 = dim(Om2) - C(n-1,2) + beta1
# And we showed dim(Om2) = |A2| - n_bp
# So Z2 = |A2| - n_bp - C(n-1,2) + beta1
# ============================================================
print(f"\n{'='*70}")
print("Z2 FORMULA")
print("=" * 70)

n = 5
check = 0
total_check = 0
for bits in range(1 << (n*(n-1)//2)):
    A = build_adj(n, bits)
    a1 = enumerate_allowed_paths(A, n, 1)
    a2 = enumerate_allowed_paths(A, n, 2)

    om2 = compute_omega_basis(A, n, 2, a2, a1)
    d_om2 = om2.shape[1] if om2.ndim == 2 else 0

    bd2 = build_full_boundary_matrix(a2, a1)
    if d_om2 > 0:
        S = np.linalg.svd(bd2 @ om2, compute_uv=False)
        rk2 = sum(s > 1e-8 for s in S)
        z2 = d_om2 - rk2
    else:
        z2 = 0

    betti = path_betti_numbers(A, n, max_dim=1)
    b1 = betti[1]

    # n_bp
    bp = 0
    for a in range(n):
        for c in range(n):
            if a != c and A[c][a]:
                if any(A[a][b] and A[b][c] for b in range(n) if b != a and b != c):
                    bp += 1

    # Formula: Z2 = |A2| - n_bp - C(n-1,2) + beta1
    from math import comb
    z2_formula = len(a2) - bp - comb(n-1, 2) + b1
    if z2_formula == z2:
        check += 1
    total_check += 1

print(f"Formula Z2 = |A2| - n_bp - C(n-1,2) + beta1: {check}/{total_check} match")
print(f"  C(n-1,2) = {comb(n-1,2)}")


# Similarly for Om3 and rk(d3):
# beta2 = Z2 - rk(d3) = 0
# So rk(d3) = Z2 = |A2| - n_bp - C(n-1,2) + beta1
# And rk(d3) = dim(Om3) - dim(Z3) = dim(Om3) - beta3
# So: dim(Om3) - beta3 = |A2| - n_bp - C(n-1,2) + beta1
# i.e.: dim(Om3) = |A2| - n_bp - C(n-1,2) + beta1 + beta3

print(f"\nChecking: dim(Om3) = |A2| - n_bp - C(n-1,2) + beta1 + beta3")
check2 = 0
for bits in range(1 << (n*(n-1)//2)):
    A = build_adj(n, bits)
    a1 = enumerate_allowed_paths(A, n, 1)
    a2 = enumerate_allowed_paths(A, n, 2)
    a3 = enumerate_allowed_paths(A, n, 3)

    om3 = compute_omega_basis(A, n, 3, a3, a2)
    d_om3 = om3.shape[1] if om3.ndim == 2 else 0

    betti = path_betti_numbers(A, n, max_dim=3)
    b1 = betti[1]
    b3 = betti[3] if len(betti) > 3 else 0

    bp = 0
    for a in range(n):
        for c in range(n):
            if a != c and A[c][a]:
                if any(A[a][b] and A[b][c] for b in range(n) if b != a and b != c):
                    bp += 1

    om3_formula = len(a2) - bp - comb(n-1, 2) + b1 + b3
    if om3_formula == d_om3:
        check2 += 1

print(f"  Matches: {check2}/{1 << (n*(n-1)//2)}")


print("\n\nDone.")
