#!/usr/bin/env python3
"""
cartan_bridge_deep2.py -- kind-pasteur-2026-03-21-S13

MAJOR DISCOVERY FROM PART 1:
All 2640 regular n=7 tournaments have S_T^2 = -7*I + J (Casimir deviation = 0).
This means ALL regular n=7 tournaments are doubly regular (d=1 for all arcs).
Yet they split into 3 isomorphism classes with H = 171, 175, 189.

CONSEQUENCE: S_T^2 (the Cartan "symmetric sector image") does NOT determine H.
H requires HIGHER-ORDER information from S_T.

This script investigates:
1. At what power k does S_T^k first distinguish the three regular n=7 classes?
2. Does S_T^2 = -n*I+J hold for regular tournaments at other n?
3. The FULL matrix algebra generated by S_T — its dimension tells us the
   minimal information needed beyond S_T^2.
4. The connection to attention matrices: what's the analog of this
   "spectral blindness" for transformer attention?

Author: kind-pasteur-2026-03-21-S13
"""

import numpy as np
from itertools import combinations, permutations
from collections import defaultdict


def binary_to_tournament(bits, n):
    A = np.zeros((n, n), dtype=int)
    pos = 0
    for i in range(n):
        for j in range(i+1, n):
            if bits & (1 << pos):
                A[i][j] = 1
            else:
                A[j][i] = 1
            pos += 1
    return A


def signed_adjacency(A):
    n = A.shape[0]
    S = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if i != j:
                S[i][j] = 2 * A[i][j] - 1
    return S


def count_ham_paths(A):
    n = A.shape[0]
    dp = defaultdict(int)
    for v in range(n):
        dp[(1 << v, v)] = 1
    for mask in range(1, 1 << n):
        for v in range(n):
            if not (mask & (1 << v)):
                continue
            if dp[(mask, v)] == 0:
                continue
            for w in range(n):
                if mask & (1 << w):
                    continue
                if A[v][w]:
                    dp[(mask | (1 << w), w)] += dp[(mask, v)]
    full = (1 << n) - 1
    return sum(dp[(full, v)] for v in range(n))


def paley_tournament(p):
    qr = set()
    for k in range(1, p):
        qr.add((k * k) % p)
    A = np.zeros((p, p), dtype=int)
    for i in range(p):
        for j in range(p):
            if i != j and (j - i) % p in qr:
                A[i][j] = 1
    return A


# ============================================================
# INVESTIGATION A: At what power k does S^k distinguish H classes?
# ============================================================

def investigate_distinguishing_power(n=7):
    """
    For regular n=7 tournaments, S_T^2 is the same for all.
    At what power k does S_T^k first distinguish the three H classes?

    The three classes have H = 171, 175, 189 (from our established results).
    """
    print("=" * 70)
    print(f"INVESTIGATION A: DISTINGUISHING POWER OF S_T^k (n={n})")
    print("=" * 70)

    m = n * (n - 1) // 2
    total = 1 << m

    # Collect regular tournaments grouped by H
    by_H = defaultdict(list)

    for bits in range(total):
        A = binary_to_tournament(bits, n)
        scores = sorted(A.sum(axis=1))
        if not all(s == (n - 1) // 2 for s in scores):
            continue
        H = count_ham_paths(A)
        S = signed_adjacency(A).astype(float)
        by_H[H].append(S)

    print(f"\nRegular tournament classes:")
    for H in sorted(by_H.keys()):
        print(f"  H={H}: {len(by_H[H])} tournaments")

    H_values = sorted(by_H.keys())

    # For each power k, check if trace(S^k) distinguishes the classes
    print(f"\nPower traces by H class:")
    print(f"  {'k':>3s}", end="")
    for H in H_values:
        print(f"  {'H=' + str(H):>12s}", end="")
    print(f"  {'distinct?':>10s}")

    for k in range(1, 2 * n + 1):
        traces = {}
        for H in H_values:
            S = by_H[H][0]  # representative
            Sk = np.linalg.matrix_power(S, k)
            traces[H] = round(np.real(np.trace(Sk)), 4)

        trace_vals = list(traces.values())
        is_distinct = len(set(trace_vals)) == len(trace_vals)
        print(f"  {k:3d}", end="")
        for H in H_values:
            print(f"  {traces[H]:12.1f}", end="")
        print(f"  {'YES' if is_distinct else 'no':>10s}")

    # Also check the FULL matrix S^k, not just trace
    print(f"\nFull matrix signature by H class (using sorted eigenvalues of S^k):")
    for k in [3, 4, 5, 6, 7]:
        sigs = {}
        for H in H_values:
            S = by_H[H][0]
            Sk = np.linalg.matrix_power(S, k)
            # Use sorted absolute values of eigenvalues as signature
            eigvals = sorted(np.abs(np.linalg.eigvals(Sk)))
            sigs[H] = tuple(round(e, 2) for e in eigvals)

        all_same = len(set(sigs.values())) == 1
        print(f"  k={k}: {'ALL SAME' if all_same else 'DIFFERENT'}")
        if not all_same:
            for H in H_values:
                print(f"    H={H}: {sigs[H]}")
            break

    # Check off-diagonal entries of S^k
    print(f"\nOff-diagonal uniqueness of S^k by H class:")
    for k in range(1, 2 * n + 1):
        off_diag_sigs = {}
        for H in H_values:
            S = by_H[H][0]
            Sk = np.linalg.matrix_power(S, k)
            # Sorted off-diagonal entries (as tuple)
            off = sorted(round(np.real(Sk[i][j]), 2)
                         for i in range(n) for j in range(n) if i != j)
            off_diag_sigs[H] = tuple(off)

        distinct = len(set(off_diag_sigs.values()))
        if distinct > 1:
            print(f"  k={k}: {distinct} distinct off-diagonal patterns "
                  f"-- FIRST DISTINCTION!")
            for H in H_values:
                vals = set(off_diag_sigs[H])
                print(f"    H={H}: unique off-diag values = {sorted(vals)}")
            break
        else:
            print(f"  k={k}: all same")


# ============================================================
# INVESTIGATION B: Does S^2 universality hold at other n?
# ============================================================

def investigate_S2_universality():
    """
    Check if S_T^2 = -n*I + J for ALL regular tournaments at various n.

    For doubly regular tournaments: d = (n-3)/4 must be a non-negative integer.
    This requires n = 3 mod 4. So n = 3, 7, 11, 15, 19, 23, ...

    For n NOT = 3 mod 4: d is not an integer, so no DRT exists,
    and S_T^2 should vary among regular tournaments.
    """
    print("\n" + "=" * 70)
    print("INVESTIGATION B: S_T^2 UNIVERSALITY FOR REGULAR TOURNAMENTS")
    print("=" * 70)

    for n in [3, 5, 7, 9]:
        m = n * (n - 1) // 2
        total = 1 << m

        if total > 5000000:
            print(f"\nn={n}: too many tournaments ({total}), skipping")
            continue

        d_expected = (n - 3) / 4.0
        is_int = d_expected == int(d_expected)

        target = -n * np.eye(n) + np.ones((n, n))

        regular_count = 0
        drt_count = 0  # matches S^2 = -nI + J

        H_by_drt = {'yes': [], 'no': []}

        for bits in range(total):
            A = binary_to_tournament(bits, n)
            scores = A.sum(axis=1)
            if not all(s == (n - 1) // 2 for s in scores):
                continue

            regular_count += 1
            S = signed_adjacency(A).astype(float)
            S2 = S @ S

            if np.max(np.abs(S2 - target)) < 0.01:
                drt_count += 1
                H_by_drt['yes'].append(count_ham_paths(A))
            else:
                H_by_drt['no'].append(count_ham_paths(A))

        print(f"\nn={n}: d_expected = {d_expected} "
              f"({'integer' if is_int else 'NOT integer'})")
        print(f"  Regular tournaments: {regular_count}")
        print(f"  With S^2 = -nI+J (DRT): {drt_count} ({100*drt_count/max(regular_count,1):.1f}%)")

        if H_by_drt['yes']:
            print(f"  DRT H values: {sorted(set(H_by_drt['yes']))}")
        if H_by_drt['no']:
            print(f"  Non-DRT H values: {sorted(set(H_by_drt['no']))}")

        if regular_count == drt_count:
            print(f"  *** ALL regular n={n} tournaments are DRT! ***")
        elif drt_count == 0:
            print(f"  *** NO regular n={n} tournaments are DRT ***")


# ============================================================
# INVESTIGATION C: Matrix algebra dimension of S_T
# ============================================================

def investigate_algebra_dimension(n=7):
    """
    The algebra Alg(S_T) = span{I, S_T, S_T^2, ...} has dimension
    equal to the degree of the minimal polynomial of S_T.

    For Paley T_7: min poly = x(x^2+7), degree 3, Alg dim = 3.
    For non-Paley regular: min poly might be different.

    The algebra dimension tells us the minimal information needed
    to reconstruct all of S_T's "directed structure."

    If dim(Alg(S_T)) = d, then d real numbers suffice to encode
    the tournament (up to the information preserved by powers).
    """
    print("\n" + "=" * 70)
    print(f"INVESTIGATION C: ALGEBRA DIMENSION OF S_T (n={n})")
    print("=" * 70)

    m = n * (n - 1) // 2
    total = 1 << m

    dim_by_H = defaultdict(list)
    minpoly_by_H = defaultdict(list)

    for bits in range(total):
        A = binary_to_tournament(bits, n)
        scores = sorted(A.sum(axis=1))
        if not all(s == (n - 1) // 2 for s in scores):
            continue

        H = count_ham_paths(A)
        S = signed_adjacency(A).astype(float)

        # Compute algebra dimension = rank of [I, S, S^2, ..., S^{n-1}]
        basis = []
        Sk = np.eye(n)
        for k in range(n):
            basis.append(Sk.flatten())
            Sk = Sk @ S

        basis_matrix = np.array(basis)
        rank = np.linalg.matrix_rank(basis_matrix, tol=0.01)
        dim_by_H[H].append(rank)

        # Minimal polynomial: find smallest k such that S^k is in span{I,...,S^{k-1}}
        for k in range(1, n + 1):
            test_basis = np.array([np.linalg.matrix_power(S, j).flatten()
                                   for j in range(k)])
            Sk_flat = np.linalg.matrix_power(S, k).flatten()
            # Check if S^k is in span of {I, S, ..., S^{k-1}}
            try:
                coeffs, res, rk, sv = np.linalg.lstsq(test_basis.T, Sk_flat, rcond=None)
                reconstruction = test_basis.T @ coeffs
                error = np.linalg.norm(Sk_flat - reconstruction)
                if error < 0.01:
                    minpoly_by_H[H].append(k)
                    break
            except:
                pass

    print(f"\nAlgebra dimension by H class:")
    for H in sorted(dim_by_H.keys()):
        dims = dim_by_H[H]
        dim_set = sorted(set(dims))
        print(f"  H={H}: dim(Alg(S_T)) = {dim_set} ({len(dims)} tournaments)")

    print(f"\nMinimal polynomial degree by H class:")
    for H in sorted(minpoly_by_H.keys()):
        degs = minpoly_by_H[H]
        deg_set = sorted(set(degs))
        print(f"  H={H}: min poly degree = {deg_set}")

    # For each H class, extract the minimal polynomial
    print(f"\nMinimal polynomial coefficients (representative per class):")
    for H in sorted(dim_by_H.keys()):
        # Get a representative
        found = False
        for bits in range(total):
            A = binary_to_tournament(bits, n)
            scores = sorted(A.sum(axis=1))
            if not all(s == (n - 1) // 2 for s in scores):
                continue
            if count_ham_paths(A) != H:
                continue

            S = signed_adjacency(A).astype(float)

            # Find minimal polynomial via Cayley-Hamilton
            # S satisfies char poly. Find all factors.
            char_poly = np.round(np.real(np.poly(S)), 2)
            eigvals = np.linalg.eigvals(S)

            print(f"\n  H={H}:")
            print(f"    Eigenvalues: ", end="")
            for ev in sorted(eigvals, key=lambda x: (abs(x), x.real)):
                if abs(ev.imag) < 0.001:
                    print(f"{ev.real:.3f}", end=" ")
                else:
                    print(f"({ev.real:.3f}+{ev.imag:.3f}i)", end=" ")
            print()
            print(f"    Char poly coefficients: {char_poly}")

            # Check if min poly is x(x^2+n) = x^3 + nx
            S3 = np.linalg.matrix_power(S, 3)
            check = S3 + n * S
            err = np.max(np.abs(check))
            print(f"    S^3 + {n}*S = 0? error = {err:.4f} "
                  f"({'YES' if err < 0.01 else 'NO'}")

            if err > 0.01:
                # Try other minimal polynomials
                # S^3 + a*S^2 + b*S + c*I = 0
                # Build system: each entry gives an equation
                # S^3[i,j] + a*S^2[i,j] + b*S[i,j] + c*I[i,j] = 0
                S2 = S @ S
                entries = []
                for i in range(n):
                    for j in range(n):
                        entries.append([S2[i,j], S[i,j],
                                       float(i == j), -S3[i,j]])
                entries = np.array(entries)
                try:
                    sol, _, _, _ = np.linalg.lstsq(entries[:, :3],
                                                    entries[:, 3], rcond=None)
                    a, b, c = sol
                    print(f"    Min poly: x^3 + {a:.2f}*x^2 + {b:.2f}*x + {c:.2f}")
                except:
                    print(f"    Could not find degree-3 min poly")

            found = True
            break


# ============================================================
# INVESTIGATION D: What DOES distinguish H classes within DRT?
# ============================================================

def investigate_H_discriminant(n=7):
    """
    If all regular n=7 tournaments have S_T^2 = -7I+J and the same
    eigenvalue spectrum {0, +/-i*sqrt(7)}, what distinguishes the three
    H classes (171, 175, 189)?

    Answer: the EIGENVECTOR structure must differ. The eigenspaces of S_T
    (3-dimensional eigenspace for +i*sqrt(7), 3-dim for -i*sqrt(7))
    have different orientations relative to the vertex basis.

    We can detect this via: higher cycle counts, the "signature" of
    the eigenvector matrix, or the commutant of S_T.
    """
    print("\n" + "=" * 70)
    print(f"INVESTIGATION D: WHAT DISTINGUISHES H CLASSES? (n={n})")
    print("=" * 70)

    m = n * (n - 1) // 2
    total = 1 << m

    by_H = defaultdict(list)

    for bits in range(total):
        A = binary_to_tournament(bits, n)
        scores = A.sum(axis=1)
        if not all(s == (n - 1) // 2 for s in scores):
            continue

        H = count_ham_paths(A)
        S = signed_adjacency(A).astype(float)

        # Higher cycle counts via traces of powers
        traces = []
        Sk = S.copy()
        for k in range(1, n + 1):
            traces.append(round(np.real(np.trace(Sk)), 4))
            Sk = Sk @ S

        # Count directed 3-cycles and 5-cycles
        c3 = 0
        c5 = 0
        for triple in combinations(range(n), 3):
            a, b, c = triple
            if A[a][b] and A[b][c] and A[c][a]:
                c3 += 1
            if A[a][c] and A[c][b] and A[b][a]:
                c3 += 1
        for quint in combinations(range(n), 5):
            for perm in permutations(quint[1:]):
                path = [quint[0]] + list(perm)
                is_cycle = True
                for k2 in range(5):
                    if not A[path[k2]][path[(k2 + 1) % 5]]:
                        is_cycle = False
                        break
                if is_cycle:
                    c5 += 1

        # Commutant dimension: dim of {X : XS = SX}
        # Build commutant equations: (S tensor I - I tensor S^T) vec(X) = 0
        S_kron = np.kron(S, np.eye(n)) - np.kron(np.eye(n), S.T)
        comm_dim = n * n - np.linalg.matrix_rank(S_kron, tol=0.01)

        by_H[H].append({
            'bits': bits, 'c3': c3, 'c5': c5,
            'traces': traces, 'comm_dim': comm_dim
        })

    print(f"\nH class characteristics:")
    print(f"  {'H':>5s} {'count':>6s} {'c3':>5s} {'c5':>5s} "
          f"{'comm_dim':>9s} {'tr(S^4)':>10s} {'tr(S^6)':>10s}")

    for H in sorted(by_H.keys()):
        group = by_H[H]
        rep = group[0]
        print(f"  {H:5d} {len(group):6d} {rep['c3']:5d} {rep['c5']:5d} "
              f"{rep['comm_dim']:9d} {rep['traces'][3]:10.1f} "
              f"{rep['traces'][5]:10.1f}")

    # Key: cycle counts should distinguish them
    print(f"\nCycle counts are the DISCRIMINANT between iso-spectral classes.")
    print(f"Since tr(S^k) is the same for all (same eigenvalues),")
    print(f"the distinction must come from the eigenvector structure,")
    print(f"which is captured by the non-trace invariants of S^k.")


# ============================================================
# INVESTIGATION E: The Cartan bridge for the attention algebra
# ============================================================

def investigate_attention_algebra():
    """
    For a transformer attention matrix A (continuous, row-stochastic),
    the matrix algebra generated by A_anti (the tournament part)
    has finite dimension. This dimension is the key quantity:

    - dim = 1: trivial attention (A_anti = 0, pure similarity)
    - dim = 2: binary attention (one eigenvalue pair)
    - dim = n: generic attention (all eigenvalues distinct)

    For TRAINED attention, we expect dim < n (structured attention).
    For RANDOM attention, we expect dim = n (generic).

    The "Cartan bridge complexity" = dim(Alg(A_anti)) / dim(Alg(A_sym))
    measures the relative complexity of directed vs undirected structure.
    """
    print("\n" + "=" * 70)
    print("INVESTIGATION E: ATTENTION ALGEBRA DIMENSIONS")
    print("=" * 70)

    np.random.seed(42)

    for n in [5, 7, 11]:
        print(f"\nn = {n}:")

        # Random attention
        dims_anti = []
        dims_sym = []
        for trial in range(100):
            logits = np.random.randn(n, n)
            exp_l = np.exp(logits - logits.max(axis=1, keepdims=True))
            A = exp_l / exp_l.sum(axis=1, keepdims=True)

            A_anti = (A - A.T) / 2
            A_sym = (A + A.T) / 2

            # Algebra dimension = number of distinct eigenvalues
            # (for diagonalizable matrices)
            eigvals_anti = np.linalg.eigvals(A_anti)
            eigvals_sym = np.linalg.eigvals(A_sym)

            # Count distinct eigenvalues (up to conjugation for complex)
            # Group by |lambda|
            mags_anti = sorted(set(round(abs(e), 4) for e in eigvals_anti))
            mags_sym = sorted(set(round(abs(e), 4) for e in eigvals_sym))

            dims_anti.append(len(mags_anti))
            dims_sym.append(len(mags_sym))

        print(f"  Random attention (100 trials):")
        print(f"    Anti spectral diversity: "
              f"mean={np.mean(dims_anti):.1f}, "
              f"range=[{min(dims_anti)}, {max(dims_anti)}]")
        print(f"    Sym spectral diversity:  "
              f"mean={np.mean(dims_sym):.1f}, "
              f"range=[{min(dims_sym)}, {max(dims_sym)}]")

        # Paley attention
        if n in [7, 11, 13] and all(n % i != 0 for i in range(2, int(n**0.5)+1)):
            qr = set()
            for k in range(1, n):
                qr.add((k * k) % n)
            A_paley = np.zeros((n, n))
            for i in range(n):
                for j in range(n):
                    if i != j and (j - i) % n in qr:
                        A_paley[i][j] = 1.0
            row_sums = A_paley.sum(axis=1, keepdims=True)
            A_paley = A_paley / np.maximum(row_sums, 1e-10)

            A_anti = (A_paley - A_paley.T) / 2
            A_sym = (A_paley + A_paley.T) / 2

            mags_anti = sorted(set(round(abs(e), 4)
                                   for e in np.linalg.eigvals(A_anti)))
            mags_sym = sorted(set(round(abs(e), 4)
                                  for e in np.linalg.eigvals(A_sym)))

            print(f"  Paley T_{n} attention:")
            print(f"    Anti spectral diversity: {len(mags_anti)} "
                  f"(values: {mags_anti})")
            print(f"    Sym spectral diversity:  {len(mags_sym)} "
                  f"(values: {mags_sym})")
            print(f"    Paley has MINIMAL spectral diversity = "
                  f"MAXIMAL symmetry")


if __name__ == "__main__":
    investigate_distinguishing_power(n=7)
    investigate_S2_universality()
    investigate_algebra_dimension(n=7)
    investigate_H_discriminant(n=7)
    investigate_attention_algebra()
