#!/usr/bin/env python3
"""cayley_helix_s116i.py — The Cayley helix.

The complex plane unifies real addition and rotation via e^{x+iy}.
We need the equivalent: a space that unifies all three modes of accumulation
(growth, rotation, self-similarity) through the Cayley transform.

The complex numbers adjoin i (sqrt(-1)) to solve x^2+1=0.
What do WE need to adjoin to solve ALL equations in the Cayley world?

The answer: the Cayley helix. Not a plane. A HELIX.
Because Q has period 4, the natural geometry is not flat — it spirals.
"""
from math import sqrt, log, exp, pi, atanh, tanh, cos, sin, cosh, sinh
import cmath

phi = (1+sqrt(5))/2

print()
print("  THE CAYLEY HELIX")
print()
print("="*70)
print()

# ============================================================
print("  I. WHAT WE NEED TO SOLVE")
print("  " + "-"*40)
print()
print("  Over the reals, arctanh(x) is defined only for |x| < 1.")
print("  At x = 1: pole. At x > 1: undefined (real-valued).")
print("  But many important quantities LIVE past x = 1:")
print()
print("  - tau (tribonacci) = 1.839: past the pole.")
print("  - phi (golden) = 1.618: past the pole.")
print("  - 2, 3, 7, 21, all integers > 1: past the pole.")
print()
print("  To handle these, we need to EXTEND arctanh beyond [-1,1].")
print()
print("  The complex extension: arctanh(x) = (1/2)*ln((1+x)/(1-x)).")
print("  For x > 1: (1+x)/(1-x) is NEGATIVE.")
print("  ln(negative) = ln(|negative|) + i*pi.")
print("  So: arctanh(x) = (1/2)*ln(|(1+x)/(1-x)|) + i*pi/2.")
print()
print("  The IMAGINARY PART is always +/- pi/2 for x outside [-1,1].")
print("  The REAL PART is (1/2)*ln(|(1+x)/(x-1)|).")
print()

for x in [1.1, 1.5, phi, 2.0, 3.0, 7.0, 21.0]:
    z = complex(x)
    at = cmath.atanh(z)
    print(f"  arctanh({x:.3f}) = {at.real:.6f} + {at.imag/pi:.4f}*pi*i")

print()
print("  For ALL x > 1: imaginary part = pi/2 exactly.")
print("  The real part = (1/2)*ln((x+1)/(x-1)) = arctanh(1/x) + correction.")
print()
print("  Actually: for x > 1,")
print("  arctanh(x) = arctanh(1/x) + i*pi/2.")
print("  PROOF: arctanh(x) = (1/2)*ln((1+x)/(1-x))")
print("  = (1/2)*ln(-(1+x)/(x-1))")
print("  = (1/2)*(ln((1+x)/(x-1)) + i*pi)")
print("  = (1/2)*ln((1+x)/(x-1)) + i*pi/2")
print("  And (1+x)/(x-1) = (1+x)/(x-1) = Q(1/x) (since 1/x < 1).")
print("  So (1/2)*ln(Q(1/x)) = arctanh(1/x).")
print("  Therefore: arctanh(x) = arctanh(1/x) + i*pi/2. QED.")
print()

# Verify
for x in [phi, 2.0, 7.0]:
    lhs = cmath.atanh(x)
    rhs = atanh(1/x) + 1j*pi/2
    print(f"  x={x:.3f}: arctanh(x) = {lhs.real:.6f}+{lhs.imag:.6f}i, "
          f"arctanh(1/x)+ipi/2 = {rhs.real:.6f}+{rhs.imag:.6f}i, "
          f"match: {abs(lhs-rhs) < 1e-10}")

print()

# ============================================================
print()
print("  II. THE HELIX STRUCTURE")
print("  " + "-"*40)
print()
print("  arctanh(x) for x traversing the entire real line:")
print()
print("  x < -1: Re = arctanh(1/x), Im = -pi/2")
print("  -1 < x < 1: Re = arctanh(x), Im = 0")
print("  x > 1: Re = arctanh(1/x), Im = +pi/2")
print()
print("  The imaginary part JUMPS by pi/2 at each pole (x = +/-1).")
print("  Going around the full real line:")
print("  ...(-inf, -1): Im = -pi/2")
print("  (-1, 1): Im = 0")
print("  (1, inf): Im = +pi/2")
print()
print("  If we continue through COMPLEX x, the imaginary part")
print("  wraps around continuously. The full picture is a HELIX:")
print("  the real part increases monotonically,")
print("  the imaginary part spirals with period 2*pi.")
print()
print("  The PERIOD of the spiral: 2*pi*i in the complex logarithm.")
print("  Each full turn of the helix = one period of the imaginary part.")
print("  Q^4 = identity corresponds to the helix advancing by 4 * (pi/2) = 2*pi")
print("  in the imaginary direction = ONE FULL TURN.")
print()
print("  Q^1: advance pi/2 (quarter turn). From real to imaginary.")
print("  Q^2: advance pi (half turn). From real to negative real.")
print("  Q^3: advance 3*pi/2 (three-quarter turn).")
print("  Q^4: advance 2*pi (full turn). Return to start.")
print()
print("  THE PERIOD-4 SYMMETRY OF Q IS THE HELIX MAKING ONE FULL TURN.")
print()

# ============================================================
print()
print("  III. THE THREE MODES OF ACCUMULATION ON THE HELIX")
print("  " + "-"*40)
print()
print("  e: GROWTH. Moving along the REAL axis of the helix.")
print("     The helix stretches but doesn't turn.")
print("     Pure real rapidity. Im = 0.")
print()
print("  pi: ROTATION. Moving along the IMAGINARY axis of the helix.")
print("     The helix turns but doesn't stretch.")
print("     Pure imaginary rapidity. Re = 0.")
print()
print("  phi: SELF-SIMILARITY. Moving along a DIAGONAL of the helix.")
print("     The helix both stretches AND turns.")
print("     Complex rapidity with both real and imaginary parts.")
print()
print("  Wait — phi lives on the real axis (phi > 1).")
print("  arctanh(phi) = arctanh(1/phi) + i*pi/2.")
print(f"  = {atanh(1/phi):.6f} + i*{pi/2:.6f}")
print(f"  = {atanh(1/phi):.6f} + i*pi/2")
print()
print("  phi has BOTH real and imaginary rapidity!")
print("  Real part: arctanh(1/phi) = (3/2)*ln(phi) / something...")
print(f"  arctanh(1/phi) = {atanh(1/phi):.6f}")
print(f"  Compare: ln(phi) = {log(phi):.6f}")
print(f"  arctanh(1/phi) / ln(phi) = {atanh(1/phi)/log(phi):.6f}")
print(f"  = 3/2 = {3/2}. YES!")
print()
print("  arctanh(1/phi) = (3/2)*ln(phi). We proved this earlier.")
print("  So arctanh(phi) = (3/2)*ln(phi) + i*pi/2.")
print()
print("  The golden ratio's rapidity has:")
print("  - Real part (3/2)*ln(phi) ~ 0.722 (the growth)")
print("  - Imaginary part pi/2 ~ 1.571 (the quarter-turn)")
print()
print("  phi IS a helical point. It grows AND rotates.")
print("  It is the DIAGONAL accumulation mode.")
print()

# ============================================================
print()
print("  IV. THE HELIX COORDINATES OF THE KEY CONSTANTS")
print("  " + "-"*40)
print()
print("  Every real number has a position on the Cayley helix:")
print("  (Re(arctanh(x)), Im(arctanh(x)))")
print()
print("  Constant      value      Re           Im        Im/pi")
print("  " + "-"*60)
for name, x in [("0", 0), ("1/3", 1/3), ("1/2", 0.5), ("3/4", 0.75),
                 ("1", 1.0), ("phi", phi), ("2", 2.0),
                 ("e", exp(1)), ("3", 3.0), ("pi", pi),
                 ("7", 7.0), ("21", 21.0)]:
    if x == 1.0:
        print(f"  {'1':<8s}  {1.0:8.4f}    {'inf':>10s}   {'pole':>8s}    {'---':>6s}   POLE")
        continue
    z = cmath.atanh(complex(x))
    im_over_pi = z.imag / pi
    mark = ""
    if name == "3/4": mark = " FORBIDDEN ADDRESS"
    elif name == "7": mark = " FORBIDDEN"
    elif name == "21": mark = " FORBIDDEN"
    elif name == "1": mark = " POLE"
    print(f"  {name:<8s}  {x:8.4f}    {z.real:+10.6f}   {z.imag:+8.4f}    {im_over_pi:+.4f}  {mark}")

print()
print("  THE POLE (x=1) splits the helix into two sheets:")
print("  Sheet 0: |x| < 1. Im = 0. The bounded world.")
print("  Sheet 1: |x| > 1. Im = pi/2. The unbounded world.")
print()
print("  The forbidden numbers (7, 21) live on Sheet 1.")
print("  They are REAL numbers with IMAGINARY rapidity component pi/2.")
print("  They are not 'complex' in the usual sense.")
print("  They have crossed the pole and gained an imaginary phase.")
print()

# ============================================================
print()
print("  V. THE HELIX AND EULER'S FORMULA")
print("  " + "-"*40)
print()
print("  Euler: e^{i*theta} = cos(theta) + i*sin(theta).")
print("  This maps the real line to the unit circle.")
print("  It is PURE ROTATION: |e^{i*theta}| = 1 always.")
print()
print("  Cayley: Q(tanh(t/2)) = e^t for real t.")
print("  This maps the bounded interval to the positive reals.")
print("  It is PURE GROWTH: e^t > 0 always.")
print()
print("  The HELIX combines both:")
print("  Q(tanh((s + i*theta)/2)) = e^{s + i*theta} = e^s * e^{i*theta}.")
print("  This has GROWTH (e^s) AND ROTATION (e^{i*theta}).")
print()
print("  The helix parameter: z = s + i*theta (complex rapidity).")
print("  Real part s: how much growth.")
print("  Imaginary part theta: how much rotation.")
print()
print("  Q = exp when composed with tanh(./2).")
print("  The FULL Cayley helix = the FULL complex exponential")
print("  seen through the tanh/arctanh coordinate system.")
print()

# ============================================================
print()
print("  VI. THE THREE SHEETS")
print("  " + "-"*40)
print()
print("  The complex logarithm has infinitely many sheets")
print("  (differing by 2*pi*i). But Q has period 4 in the real,")
print("  which corresponds to period 2*pi in the imaginary.")
print()
print("  The FUNDAMENTAL DOMAIN of the Cayley helix:")
print("  Re(z) in (-inf, inf)")
print("  Im(z) in [0, 2*pi) (one full turn)")
print()
print("  Within one turn, there are FOUR QUADRANTS (quarter-turns):")
print("  Q0: Im in [0, pi/2)     — the bounded real world")
print("  Q1: Im in [pi/2, pi)    — the unbounded real world (past the pole)")
print("  Q2: Im in [pi, 3*pi/2)  — the bounded imaginary world")
print("  Q3: Im in [3*pi/2, 2*pi)— the unbounded imaginary world")
print()
print("  Q rotates between quadrants: Q0 -> Q1 -> Q2 -> Q3 -> Q0.")
print("  Each application of Q advances by pi/2 = one quarter turn.")
print()
print("  The FOUR FACES of the orbit {x, Q(x), -1/x, Q^{-1}(x)}")
print("  are the FOUR QUADRANTS of the helix.")
print("  Each face lives in a different quadrant.")
print("  The orbit IS the helix, sampled at 4 points.")
print()

# ============================================================
print()
print("  VII. SOLVING EQUATIONS ON THE HELIX")
print("  " + "-"*40)
print()
print("  On the real line: arctanh(x) exists only for |x| < 1.")
print("  On the helix: arctanh(z) exists for ALL z (except z = +/-1).")
print()
print("  The equation Q(v) = n for any n:")
print("  v = Q^{-1}(n) = (n-1)/(n+1). Always real. Always in (-1,1) for n > 0.")
print("  No helix needed for THIS equation.")
print()
print("  But the equation tanh(z) = v for |v| > 1:")
print("  z = arctanh(v) = arctanh(1/v) + i*pi/2. Complex. Needs the helix.")
print()
print("  And the equation Q(v) = -n (negative Q-value):")
print("  v = (-n-1)/(-n+1) = (n+1)/(n-1). This is > 1 for n > 1.")
print("  So v is PAST the pole. Its rapidity is complex.")
print("  arctanh((n+1)/(n-1)) = arctanh((n-1)/(n+1))... no.")
print("  Let me compute: Q(v) = -7. v = (-7-1)/(-7+1) = -8/-6 = 4/3.")
print(f"  Q(4/3) = (1+4/3)/(1-4/3) = (7/3)/(-1/3) = -7. Check.")
print(f"  arctanh(4/3) = {cmath.atanh(4/3).real:.6f} + {cmath.atanh(4/3).imag:.6f}i")
print()
print("  To get Q = -7, you need velocity 4/3 > 1: a TACHYON.")
print("  Its rapidity has imaginary part pi/2: it lives on the upper sheet.")
print()

# ============================================================
print()
print("  VIII. THE HELIX UNIFIES THE THREE ACCUMULATIONS")
print("  " + "-"*40)
print()
print("  On the helix, the three modes are three DIRECTIONS:")
print()
print("  GROWTH: move along the helix axis (increase Re, Im = 0).")
print("    Pure real rapidity. tanh gives bounded progress.")
print("    Characterized by e = exp(1).")
print()
print("  ROTATION: move around the helix circumference (Re = 0, increase Im).")
print("    Pure imaginary rapidity. tanh gives oscillation: tanh(i*t) = i*tan(t).")
print("    Characterized by pi (half-circumference).")
print()
print("  SELF-SIMILARITY: move diagonally (increase BOTH Re and Im).")
print("    Complex rapidity. tanh gives SPIRALING progress.")
print("    Characterized by phi (the golden spiral).")
print()
print("  phi's rapidity: arctanh(phi) = 0.722 + 1.571i")
print(f"  Angle from real axis: arctan(1.571/0.722) = {cmath.phase(complex(atanh(1/phi), pi/2))*180/pi:.1f} degrees")
print()
print("  The golden ratio's helical angle is about 65 degrees from the growth axis.")
print("  It's roughly 2/3 of the way from growth to rotation.")
print()

# ============================================================
print()
print("  IX. THE HELIX IS THE RIEMANN SURFACE OF arctanh")
print("  " + "-"*40)
print()
print("  arctanh is a MULTIVALUED function on C.")
print("  Its Riemann surface is an infinite-sheeted cover of C\\{-1,1}.")
print("  The sheets are indexed by n in Z: arctanh(x) + n*i*pi.")
print()
print("  Our helix is ONE SHEET of this Riemann surface.")
print("  Going around a pole (x = +/-1) advances to the next sheet")
print("  by adding i*pi to the rapidity.")
print()
print("  The two poles are the BRANCH POINTS of the Riemann surface.")
print("  They are where the sheets connect.")
print("  In the tournament metaphor: the poles are the PHASE TRANSITIONS.")
print("  Crossing a pole = changing from bounded to unbounded")
print("  = gaining an imaginary phase = entering a new sheet of reality.")
print()
print("  The forbidden number 7 lives on sheet 1 (one crossing past the pole).")
print("  Its rapidity 0.973 + i*pi/2 says:")
print("  'I am 0.973 units of real effort past the center,")
print("   AND I have crossed one phase boundary.'")
print()

# ============================================================
print()
print("  X. THE COMPLETE PICTURE")
print("  " + "-"*40)
print()
print("  The Cayley helix is the Riemann surface of arctanh.")
print("  It has:")
print("  - An axis (the real rapidity, parametrized by Re)")
print("  - A circumference (the imaginary rapidity, period 2*pi)")
print("  - Branch points at x = +/-1 (the poles of Q)")
print("  - Four quadrants per turn (the period-4 symmetry of Q)")
print("  - Three distinguished directions (e: axial, pi: circumferential, phi: diagonal)")
print()
print("  Every number — rational, irrational, algebraic, transcendental —")
print("  has a position on this helix. Its coordinates are")
print("  (Re(arctanh(x)), Im(arctanh(x))).")
print()
print("  The bounded world is the section Im = 0.")
print("  The unbounded world is the section Im = pi/2.")
print("  They are connected by the branch points at x = +/-1.")
print("  Q rotates between sections, advancing by pi/2 each time.")
print()
print("  The formal group F_h(x,y) = (x+y)/(1+xy) acts on the helix.")
print("  It is ADDITION in the axial coordinate (rapidities add).")
print("  It is TRIVIAL in the circumferential coordinate")
print("  (the imaginary parts just accumulate by pi/2 per pole crossing).")
print()
print("  The helix IS the universal cover of the Cayley transform.")
print("  On the helix, there are no poles, no branch cuts, no forbidden zones.")
print("  Every equation has a solution. Every value is reached.")
print()
print("  The bounded world is not separate from the unbounded world.")
print("  They are two cross-sections of the same helix.")
print("  One at angle 0. The other at angle pi/2.")
print("  The helix connects them.")
print("  Q is the staircase that climbs between floors.")
print("  arctanh is the elevator that knows which floor you're on.")
print()
print("  And the helix never ends.")
print("  It spirals forever: floor after floor after floor.")
print("  Each floor is a copy of the real line.")
print("  Each staircase (Q) connects four consecutive floors.")
print("  The floors are all the same. The staircases are all the same.")
print("  The helix is the same everywhere.")
print("  That is its universality.")
