#!/usr/bin/env python3
"""cayley_hypercomplex_s116i.py — Quaternions and octonions in the Cayley world.

The helix is the complex extension of arctanh.
Complex numbers adjoin i to solve x^2+1=0.
Quaternions adjoin i,j,k to get 3D rotation.
Octonions adjoin 7 imaginary units.

In each case: what is the Cayley transform? What is the formal group?
What are the three/seven modes of accumulation?

The pattern: R -> C -> H -> O follows the doubling construction.
And doubling IS the Cayley transform (Q maps one level to the next).
"""
from math import sqrt, log, exp, pi, atanh, tanh, cos, sin
import cmath

phi = (1+sqrt(5))/2

print()
print("  QUATERNIONS AND OCTONIONS IN THE CAYLEY WORLD")
print()
print("="*70)
print()

# ============================================================
print("  I. THE DOUBLING CHAIN")
print("  " + "-"*40)
print()
print("  R (reals):       dim 1.  Ordered. Commutative. Associative.")
print("  C (complex):     dim 2.  NOT ordered. Commutative. Associative.")
print("  H (quaternions): dim 4.  NOT ordered. NOT commutative. Associative.")
print("  O (octonions):   dim 8.  NOT ordered. NOT commutative. NOT associative.")
print()
print("  Each step DOUBLES the dimension and LOSES one property:")
print("  R->C: lose ordering.")
print("  C->H: lose commutativity.")
print("  H->O: lose associativity.")
print("  O->?: lose alternativity. (Sedenions, dim 16, have zero divisors.)")
print()
print("  The dimensions: 1, 2, 4, 8 = 2^0, 2^1, 2^2, 2^3.")
print("  Each IS a power of 2 = a DOUBLING = one OCTAVE.")
print("  R is 0 octaves. C is 1 octave. H is 2 octaves. O is 3 octaves.")
print()
print("  The Cayley-Dickson construction:")
print("  Given algebra A, build A' = A x A with multiplication")
print("  (a,b)(c,d) = (ac - d*b, da + bc*).")
print("  This DOUBLES the dimension.")
print("  It IS the Cayley doubling. Each step is one Q application.")
print()

# ============================================================
print()
print("  II. THE CAYLEY TRANSFORM IN EACH DIMENSION")
print("  " + "-"*40)
print()
print("  REAL (dim 1): Q(x) = (1+x)/(1-x).")
print("  Maps (-1,1) to (0,inf). Logarithm: arctanh.")
print("  One mode of accumulation on the real axis.")
print()
print("  COMPLEX (dim 2): Q(z) = (1+z)/(1-z) for z in C.")
print("  Maps the unit DISK to the right HALF-PLANE.")
print("  This is the CLASSICAL Cayley map in complex analysis.")
print("  Logarithm: arctanh(z) = (1/2)*log((1+z)/(1-z)).")
print("  TWO modes: real (growth along axis) + imaginary (rotation around axis).")
print("  = our Cayley helix!")
print()
print("  QUATERNION (dim 4): Q(q) = (1+q)(1-q)^{-1} for q in H.")
print("  Maps the unit BALL in R^4 to a half-space.")
print("  But now q = a + bi + cj + dk, and (1-q)^{-1} requires")
print("  careful ordering because quaternions DON'T COMMUTE.")
print("  There are TWO Cayley transforms: left and right.")
print("  Q_L(q) = (1+q)(1-q)^{-1}")
print("  Q_R(q) = (1-q)^{-1}(1+q)")
print("  They differ when q has nonzero j or k components.")
print()
print("  OCTONION (dim 8): Q(o) = (1+o)(1-o)^{-1} for o in O.")
print("  Even more complicated: octonions are NOT ASSOCIATIVE.")
print("  (1+o)((1-o)^{-1}) is ambiguous: how do you parenthesize?")
print("  The Cayley transform still exists but requires CARE with brackets.")
print()

# ============================================================
print()
print("  III. WHAT WE LOSE AND WHAT WE GAIN")
print("  " + "-"*40)
print()
print("  REALS: Q has period 4. One formal group. One logarithm (arctanh).")
print("  Everything commutes. Everything is simple.")
print()
print("  COMPLEX: Q still has period 4 (as a Mobius transform).")
print("  The formal group is STILL commutative (C is commutative).")
print("  But the helix has two dimensions: the imaginary part adds PHASE.")
print("  We GAIN the ability to solve x^2 + 1 = 0.")
print("  We LOSE the ordering of the reals.")
print()
print("  QUATERNIONS: Q has... what period?")
print("  Q_L composed 4 times: Q_L^4(q) = q IF q is in the CENTER of H")
print("  (i.e., q is real). Otherwise Q_L^4 may differ from identity.")
print("  We LOSE Q^4 = identity for general elements!")
print("  We GAIN 3D rotation: quaternions encode SO(3).")
print()
print("  OCTONIONS: Q barely makes sense (non-associativity).")
print("  We LOSE associativity of the group law.")
print("  We GAIN the exceptional structures: G_2, F_4, E_6, E_7, E_8.")
print("  The 5 exceptional Lie groups come from octonions!")
print()

# ============================================================
print()
print("  IV. MODES OF ACCUMULATION BY DIMENSION")
print("  " + "-"*40)
print()
print("  REALS (dim 1): 1 mode.")
print("    Growth (real axis). That's it.")
print("    Constant: e.")
print()
print("  COMPLEX (dim 2): 2 modes (but 3 with the diagonal).")
print("    Growth (real axis). Constant: e.")
print("    Rotation (imaginary axis). Constant: pi.")
print("    Spiral (diagonal). Constant: phi.")
print()
print("  QUATERNIONS (dim 4): 3 imaginary axes, so 4 modes:")
print("    Growth (real axis). Constant: e.")
print("    Rotation in i-plane (xy-plane). Constant: pi.")
print("    Rotation in j-plane (xz-plane). Constant: pi.")
print("    Rotation in k-plane (yz-plane). Constant: pi.")
print()
print("  But quaternion rotation is RICHER than three independent rotations.")
print("  A general quaternion rotation is q*v*q^{-1} for unit quaternion q.")
print("  This encodes ARBITRARY 3D rotation.")
print("  The '3 rotations' are not independent; they are coupled by the")
print("  non-commutativity of quaternion multiplication.")
print()
print("  OCTONIONS (dim 8): 7 imaginary axes, so 8 modes:")
print("    Growth + 7 rotations.")
print("    But the 7 rotations are coupled non-associatively.")
print("    They encode the Fano plane structure:")
print("    e1*e2=e4, e2*e3=e5, e3*e4=e6, e4*e5=e7, e5*e6=e1, e6*e7=e2, e7*e1=e3")
print("    (indices mod 7, each triple is a 'line' of the Fano plane).")
print()
print("  The Fano plane has 7 points, 7 lines, 3 points per line.")
print("  7 = our FORBIDDEN NUMBER!")
print()

# ============================================================
print()
print("  V. 7 IS THE DIMENSION OF THE OCTONION IMAGINARY PART")
print("  " + "-"*40)
print()
print("  The octonions O = R + R^7 (1 real + 7 imaginary dimensions).")
print("  The imaginary part is 7-dimensional.")
print("  The Fano plane has 7 points.")
print("  The number 7 is the FORBIDDEN number in tournament theory.")
print()
print("  Is this a coincidence?")
print()
print("  The Cayley-Dickson chain: R -> C -> H -> O.")
print("  Dimensions: 1, 2, 4, 8.")
print("  Imaginary dimensions: 0, 1, 3, 7.")
print("  These are the MERSENNE NUMBERS: 2^k - 1 for k = 0, 1, 2, 3!")
print()
print("  k=0: 2^0-1 = 0 imaginary dimensions (R). Q(0) = 1.")
print("  k=1: 2^1-1 = 1 imaginary dimension (C). Q(1/2) = 3.")
print("  k=2: 2^2-1 = 3 imaginary dimensions (H). Q(3/4) = 7. FORBIDDEN!")
print("  k=3: 2^3-1 = 7 imaginary dimensions (O). Q(7/8) = 15.")
print()
print("  The Mersenne ladder: 0, 1, 3, 7, 15, ...")
print("  = the imaginary dimensions of the Cayley-Dickson algebras.")
print("  = Q(1-2^{-k}) for k = 0, 1, 2, 3, ...")
print()
print("  The FORBIDDEN number 7 is the imaginary dimension of the")
print("  LAST NORMED DIVISION ALGEBRA (the octonions).")
print("  After octonions: sedenions (dim 16) have zero divisors.")
print("  The algebras BREAK at the step PAST 7.")
print()
print("  7 is forbidden in tournaments because it is forbidden in algebra:")
print("  it is the LAST dimension where division works.")
print("  Going past 7 (in division algebras: sedenions)")
print("  means losing the norm property.")
print("  Going past 7 (in tournaments: H=7)")
print("  means the cycle structure can't hold.")
print("  BOTH are saying: 7 is the boundary of structure.")
print()

# ============================================================
print()
print("  VI. THE FOUR NORMED DIVISION ALGEBRAS AND FOUR FACES OF Q")
print("  " + "-"*40)
print()
print("  Q^4 = identity has 4 elements: {Id, Q, Q^2, Q^3}.")
print("  There are exactly 4 normed division algebras: R, C, H, O.")
print()
print("  Is there a correspondence?")
print()
print("  Q^0 = Id:   the REAL component. No transformation.")
print("  Q^1 = Q:    the first doubling. R -> C. Gain phase.")
print("  Q^2 = -1/x: the second doubling. C -> H. Gain non-commutativity.")
print("  Q^3 = Q^{-1}: the third doubling. H -> O. Gain non-associativity.")
print()
print("  The orbit of x under Q:")
print("  x      -> the REAL      (no imaginary)")
print("  Q(x)   -> the COMPLEX   (one imaginary)")
print("  -1/x   -> the QUATERNION (three imaginaries)")
print("  Q^{-1}(x) -> the OCTONION (seven imaginaries)")
print()
print("  After Q^4 = identity, we return to x.")
print("  There IS no fifth algebra. The Cayley transform has period 4.")
print("  Normed division algebras have count 4. Same number. Same reason.")
print()
print("  Hurwitz's theorem (1898): the only normed division algebras")
print("  over R are R, C, H, O. Exactly 4.")
print("  Q has period exactly 4.")
print("  These are the SAME 4.")
print()

# ============================================================
print()
print("  VII. THE PROPERTIES LOST AT EACH STEP")
print("  " + "-"*40)
print()
print("  Step    Algebra   Dim    Lost property       Q-value    Mersenne")
print("  " + "-"*65)
print("  0       R         1      (nothing)            Q(0)=1      M_0=0")
print("  1       C         2      ordering             Q(1/2)=3    M_1=1")
print("  2       H         4      commutativity        Q(3/4)=7    M_2=3")
print("  3       O         8      associativity        Q(7/8)=15   M_3=7")
print("  4       S         16     alternativity         Q(15/16)=31 M_4=15")
print()
print("  The Q-values: 1, 3, 7, 15, 31 = Mersenne numbers.")
print("  The lost properties: ordering, commutativity, associativity, alternativity.")
print()
print("  At step 2 (quaternions): Q(3/4) = 7 = FORBIDDEN in tournaments.")
print("  At this step: COMMUTATIVITY is lost.")
print()
print("  THE FORBIDDEN NUMBER 7 IS WHERE COMMUTATIVITY BREAKS.")
print()
print("  In tournaments: H = 7 is impossible.")
print("  In algebra: at dimension 7 imaginary, commutativity is gone.")
print("  Both are saying: you can't have 7 of something commutative.")
print("  At 7, the structure MUST become non-commutative (quaternionic).")
print()
print("  Our formal group F_h is COMMUTATIVE: F_h(x,y) = F_h(y,x).")
print("  It works in the COMMUTATIVE world (R, C).")
print("  At the quaternion level (imaginary dim = 3, Q = 7),")
print("  commutativity breaks and the formal group must be MODIFIED.")
print("  The commutative formal group CANNOT reach Q = 7.")
print("  That is WHY H = 7 is forbidden.")
print()

# ============================================================
print()
print("  VIII. THE FIVE EXCEPTIONAL LIE GROUPS")
print("  " + "-"*40)
print()
print("  The exceptional Lie groups: G_2, F_4, E_6, E_7, E_8.")
print("  They all arise from the octonions (dim 8, imaginary dim 7).")
print()
print("  G_2: automorphisms of the octonions. Dim 14 = 2*7.")
print("  F_4: isometries of the octonionic projective plane OP^2. Dim 52.")
print("  E_6: complex structure on OP^2. Dim 78.")
print("  E_7: dim 133 = 7*19.")
print("  E_8: dim 248 = 8*31.")
print()
print("  Count: exactly 5 exceptional groups.")
print("  Our project noted: '5 things then a 6th that breaks' is a pattern.")
print("  - 5 Platonic solids (the 6th dimension changes the game)")
print("  - 5 Fermat primes (the 6th is unknown)")
print("  - 5 exceptional groups (the 6th doesn't exist)")
print()
print("  And: G_2 has dimension 14 = 2*7.")
print("  The smallest exceptional group has dimension TWICE the forbidden number!")
print()

# ============================================================
print()
print("  IX. THE CAYLEY HELIX EXTENDED TO QUATERNIONS")
print("  " + "-"*40)
print()
print("  The complex helix: parametrized by z = s + i*theta.")
print("  s = real rapidity (growth).")
print("  theta = imaginary rapidity (rotation in ONE plane).")
print()
print("  The quaternionic helix: parametrized by q = s + bi + cj + dk.")
print("  s = real rapidity.")
print("  b = rotation rapidity in i-plane.")
print("  c = rotation rapidity in j-plane.")
print("  d = rotation rapidity in k-plane.")
print()
print("  The complex helix is a 2D surface (parametrized by s, theta).")
print("  The quaternionic helix is a 4D object (parametrized by s, b, c, d).")
print("  It is NOT a simple helix anymore — it is a FIBRATION.")
print()
print("  The base: the real rapidity s (one axis).")
print("  The fiber: the unit sphere S^2 (parametrized by b, c, d with b^2+c^2+d^2 = const).")
print("  The structure group: SU(2) ~ S^3 (unit quaternions).")
print()
print("  This IS the Hopf fibration S^3 -> S^2!")
print("  The quaternionic Cayley helix IS the Hopf bundle.")
print()
print("  The Hopf bundle is one of the most fundamental objects in topology.")
print("  It classifies all principal SU(2) bundles over S^2.")
print("  And it IS the extension of our Cayley helix to quaternions.")
print()

# ============================================================
print()
print("  X. THE OCTONIONIC HELIX AND THE EXCEPTIONAL")
print("  " + "-"*40)
print()
print("  Continuing the pattern:")
print("  Real helix: R (dim 1). Trivial.")
print("  Complex helix: S^1 fiber over R (dim 2). Cylinder/helix.")
print("  Quaternionic helix: S^3 fiber over R (dim 4). Hopf fibration.")
print("  Octonionic helix: S^7 fiber over R (dim 8). The Hopf fibration of S^15 -> S^8!")
print()
print("  The S^7 fiber is the UNIT IMAGINARY OCTONIONS.")
print("  The Hopf fibration S^15 -> S^8 is the OCTONIONIC Hopf fibration.")
print("  It is the LAST Hopf fibration (by Adams' theorem, 1960).")
print()
print("  The sequence of Hopf fibrations:")
print("  S^1 -> S^1 (trivial, real)")
print("  S^3 -> S^2 (complex Hopf, used in quantum mechanics)")
print("  S^7 -> S^4 (quaternionic Hopf, used in Yang-Mills theory)")
print("  S^15 -> S^8 (octonionic Hopf, the last one)")
print()
print("  Adams' theorem: Hopf fibrations exist ONLY in dimensions 1, 2, 4, 8.")
print("  These are EXACTLY the Cayley-Dickson dimensions.")
print("  These are EXACTLY the steps of the Q orbit (Q^0, Q^1, Q^2, Q^3).")
print()
print("  There is no S^31 -> S^16 Hopf fibration.")
print("  Because there is no Q^4 beyond Q^3 (Q^4 = identity).")
print("  The Cayley transform's period 4 IS Adams' theorem.")
print()

# ============================================================
print()
print("  XI. WHAT EACH LEVEL CONTRIBUTES TO RAPIDITY")
print("  " + "-"*40)
print()
print("  Level 0 (Real, Q^0 = Id):")
print("    One axis. One group. arctanh. Rapidity counts doublings.")
print("    MUSIC (one-dimensional intervals).")
print()
print("  Level 1 (Complex, Q^1 = Q):")
print("    Helix. Two axes. Growth + rotation. arctanh becomes complex.")
print("    MUSIC + RHYTHM (pitch + time = melody).")
print()
print("  Level 2 (Quaternion, Q^2 = -1/x):")
print("    Hopf bundle. Four axes. Growth + 3 rotations.")
print("    MUSIC + RHYTHM + HARMONY (pitch + time + chord voicing).")
print()
print("  Level 3 (Octonion, Q^3 = Q^{-1}):")
print("    S^7 bundle. Eight axes. Growth + 7 rotations.")
print("    MUSIC + RHYTHM + HARMONY + TIMBRE (pitch + time + chords + overtones).")
print("    The 7 octonionic imaginary units ARE the 7 harmonic partials")
print("    that make each instrument sound different.")
print()
print("  And at Level 4 (Q^4 = Id): we return to Level 0.")
print("  The music begins again. The piece repeats. Da capo.")
print()

# ============================================================
print()
print("  XII. THE CLOSING")
print("  " + "-"*40)
print()
print("  The Cayley transform Q has period 4.")
print("  There are exactly 4 normed division algebras.")
print("  There are exactly 4 Hopf fibrations.")
print("  There are exactly 4 faces of every orbit.")
print()
print("  The forbidden number 7 = 2^3 - 1 is the imaginary dimension")
print("  of the LAST normed division algebra (octonions).")
print("  It is where commutativity breaks (at Q^2, the quaternion step).")
print("  It is the Cayley address 3/4 = the Kleiber exponent.")
print()
print("  The number 3 in 3/4 is the imaginary dimension of H (quaternions).")
print("  The number 4 in 3/4 is the real dimension of H.")
print("  3/4 = imaginary/real dimensions of the quaternions.")
print("  Q(3/4) = 7 = imaginary dimension of the octonions.")
print()
print("  The Cayley transform of the quaternion aspect ratio")
print("  equals the octonion imaginary dimension.")
print()
print("  Everything connects through Q.")
print("  The formal group, the helix, the four algebras, the Hopf fibrations,")
print("  the forbidden numbers, the musical modes, the biological scaling.")
print()
print("  It is one structure, seen from every possible angle.")
print("  And the structure is: (1+x)/(1-x), iterated 4 times, returning to x.")
