#!/usr/bin/env python3
"""Bounded exact Bagshaw-bucket scout for the first open target (11,4).

This is a literal small-universe reconstruction of the p>3 branch of
Bagshaw--Jacobson--Scheidler--Rollick, Algorithm 3.2.  It searches all

    3 <= m1 <= B,  2 <= m2 < m1,
    1 <= lambda1,lambda2 <= 10, gcd(lambda1,lambda2)=1

and every positive divisor pair of

    4*lambda2^2*m1^11 - 4*lambda1^2*m2^11.

Every retained form is checked directly, using the repository's independent
Gauss-composition implementation, to be a nonprincipal class of exact order
11.  We then compute the exact dimension of the subgroup generated by the
forms in each discriminant bucket.  This does *not* compute a full class
group: a bucket of discovered rank two might live in a field of rank three
or four.  The experiment therefore audits the constructive form channel,
not a negative statement about all fields in the discriminant range.

Reproduction:

    python3 04-computation/classrank_ell11_bagshaw_bounded_bucket_scout_20260824.py --bound 64
    python3 -O 04-computation/classrank_ell11_bagshaw_bounded_bucket_scout_20260824.py --bound 64
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from importlib.util import module_from_spec, spec_from_file_location
from math import gcd, isqrt
from pathlib import Path
import subprocess
import sys
from typing import DefaultDict, Dict, Iterable, List, Sequence, Set, Tuple

from flint import fmpz  # type: ignore


HERE = Path(__file__).resolve().parent
CERT_TOOL = HERE / "imaginary_quadratic_class_rank_certificate_tool_20260824.py"
SPEC = spec_from_file_location("classrank_certificate_tool", CERT_TOOL)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"cannot import {CERT_TOOL}")
CERT = module_from_spec(SPEC)
sys.modules[SPEC.name] = CERT
SPEC.loader.exec_module(CERT)
Form = CERT.Form
principal_form = CERT.principal_form


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ArithmeticError(message)


def positive_divisors(n: int) -> Tuple[int, ...]:
    """Return all positive divisors of positive n in increasing order."""
    require(n > 0, "divisor enumeration needs n>0")
    factors = [(int(p), int(e)) for p, e in fmpz(n).factor()]
    divisors = [1]
    for prime, exponent in factors:
        old = tuple(divisors)
        power = 1
        for _ in range(exponent):
            power *= prime
            divisors.extend(value * power for value in old)
    return tuple(sorted(divisors))


def squarefree_part_signed(t: int) -> int:
    """The signed square-free part used by Sage's ``squarefree_part``."""
    require(t != 0, "zero has no square-free part here")
    part = 1
    for prime, exponent in fmpz(abs(t)).factor():
        if int(exponent) & 1:
            part *= int(prime)
    return part if t > 0 else -part


def crt_mod_m_and_4(a: int, e: int, m: int) -> int:
    """Solve x=a (mod m), x=e (mod 4) in [0,4m)."""
    require(gcd(m, 4) == 1, "the even-z branch requires odd m")
    correction = ((e - a) * pow(m, -1, 4)) % 4
    return (a + m * correction) % (4 * m)


def solution_to_form(p: int, y: int, m: int) -> Tuple[int, object] | None:
    """Reconstruct Algorithm 3.2's fundamental delta and quadratic form."""
    t = y * y - 4 * m**p
    if t >= 0:
        return None
    delta = squarefree_part_signed(t)
    if delta % 4 != 1:
        delta *= 4
    if t % delta:
        return None
    quotient = t // delta
    if quotient <= 0:
        return None
    z = isqrt(quotient)
    if z * z != quotient:
        return None
    content = gcd(m, z)
    if delta % content or content % 4 == 0:
        return None

    scale = content ** ((p - 1) // 2)
    if y % scale or z % scale:
        return None
    y_prime = y // scale
    z_prime = z // scale
    parity = 0 if delta % 4 == 0 else 1

    if z_prime & 1:
        modulus = 4 * m
        if gcd(z_prime, modulus) != 1:
            return None
        x = (pow(z_prime, -1, modulus) * y_prime) % modulus
    else:
        if gcd(z_prime, m) != 1:
            return None
        residue = (pow(z_prime, -1, m) * y_prime) % m
        x = crt_mod_m_and_4(residue, parity, m)

    require((x - parity) % 2 == 0, "middle coefficient has wrong parity")
    middle = x if (x - parity) // 2 < m else x - 2 * m
    numerator = middle * middle - delta
    if numerator % (4 * m):
        return None
    form = Form(m, middle, numerator // (4 * m)).reduced()
    form.validate(delta)
    identity = principal_form(delta)
    require(form != identity, "construction unexpectedly returned principal form")
    require(form.power(p) == identity, "constructed form does not have order p")
    return delta, form


def extend_elementary_span(
    span: Set[object], generator: object, p: int, identity: object
) -> Set[object]:
    """Extend an elementary p-span by one independent generator."""
    if generator in span:
        return span
    powers = [identity]
    for _ in range(1, p):
        powers.append(powers[-1].compose(generator))
    extended = {
        old.compose(power)
        for old in span
        for power in powers
    }
    require(len(extended) == p * len(span), "non-elementary span extension")
    return extended


def bucket_rank(forms: Iterable[object], p: int, delta: int) -> int:
    identity = principal_form(delta)
    span: Set[object] = {identity}
    rank = 0
    for form in sorted(set(forms)):
        if form not in span:
            span = extend_elementary_span(span, form, p, identity)
            rank += 1
    require(len(span) == p**rank, "bucket span has wrong cardinality")
    return rank


def pari_bucket_scan(discriminants: Sequence[int], gp: str) -> None:
    """Use PARI only as a second, GRH-assisted full-group discovery path."""
    entries = ",".join(str(D) for D in sorted(discriminants))
    program = f"""
default(parisizemax,2000000000); allocatemem(64000000);
p=11;Ds=[{entries}];checked=0;best=-1;hits=0;hist=vector(12,i,0);
for(i=1,#Ds,{{
  checked++;
  D=Ds[i];q=quadclassunit(-D);
  rk=sum(j=1,#q.cyc,valuation(q.cyc[j],p)>0);
  if(rk+1>#hist,hist=concat(hist,vector(rk+1-#hist)));
  hist[rk+1]++;
  if(rk>best,best=rk;print("PARI_IMPROVE|D=",D,"|cyc=",q.cyc,"|rank=",rk));
  if(rk>=4,hits++;print("PARI_CHALLENGE_HIT|D=",D,"|cyc=",q.cyc,"|rank=",rk))
}});
print("PARI_BUCKET_SUMMARY|checked=",checked,"|best=",best,"|hits=",hits,"|hist=",hist);
quit
"""
    process = subprocess.run(
        [gp, "-fq"],
        input=program,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    require(process.returncode == 0, f"PARI exited with {process.returncode}")
    lines = [
        line.strip()
        for line in process.stdout.splitlines()
        if line.startswith("PARI_")
    ]
    require(
        any(line.startswith("PARI_BUCKET_SUMMARY|") for line in lines),
        "PARI bucket scan did not finish cleanly",
    )
    print("PARI_STATUS=GRH_ASSISTED_DISCOVERY;ANY_RANK4_LINE_REQUIRES_PURE_FORM_REPLAY")
    for line in lines:
        print(line)


def run(bound: int, pari_gp: str | None) -> None:
    p = 11
    require(bound >= 3, "bound must be at least three")
    lambdas = [
        (left, right)
        for left in range(1, 11)
        for right in range(1, 11)
        if gcd(left, right) == 1
    ]
    require(len(lambdas) == 63, "paper lambda universe changed")

    buckets: DefaultDict[int, Set[object]] = defaultdict(set)
    factorization_count = 0
    divisor_pair_count = 0
    congruence_count = 0
    valid_form_count = 0
    tuple_count = 0

    for lambda1, lambda2 in lambdas:
        for m1 in range(3, bound + 1):
            first = 4 * lambda2 * lambda2 * m1**p
            for m2 in range(2, m1):
                tuple_count += 1
                value = first - 4 * lambda1 * lambda1 * m2**p
                if value == 0:
                    continue
                factorization_count += 1
                root = isqrt(abs(value))
                for a in positive_divisors(abs(value)):
                    if a > root:
                        break
                    b = value // a
                    divisor_pair_count += 1

                    if (a + b) % (2 * lambda2) == 0:
                        congruence_count += 1
                        result = solution_to_form(
                            p, (a + b) // (2 * lambda2), m1
                        )
                        if result is not None:
                            delta, form = result
                            buckets[delta].add(form)
                            valid_form_count += 1

                    if a != b and (b - a) % (2 * lambda1) == 0:
                        congruence_count += 1
                        result = solution_to_form(
                            p, (b - a) // (2 * lambda1), m2
                        )
                        if result is not None:
                            delta, form = result
                            buckets[delta].add(form)
                            valid_form_count += 1

    rank_rows: List[Tuple[int, int, int]] = []
    histogram: Dict[int, int] = defaultdict(int)
    for delta, forms in buckets.items():
        rank = bucket_rank(forms, p, delta)
        histogram[rank] += 1
        rank_rows.append((rank, len(forms), delta))
    rank_rows.sort(key=lambda row: (-row[0], -row[1], abs(row[2]), row[2]))

    max_rank = max((row[0] for row in rank_rows), default=0)
    challenge_hits = [row for row in rank_rows if row[0] >= 4]
    if bound >= 64:
        row_by_D = {-delta: (rank, count) for rank, count, delta in rank_rows}
        require(row_by_D.get(126407) == (2, 2), "rank-two source control missing")
        require(
            row_by_D.get(380382704088879299) == (2, 5),
            "five-form rank-two multiplicity hostile missing",
        )
    print("ELL11_BAGSHAW_BOUNDED_BUCKET_SCOUT")
    print("STATUS=FINITE-EXACT_CONSTRUCTIVE_UNIVERSE")
    print(
        f"UNIVERSE=p=11;m1=3..{bound};m2=2..m1-1;"
        "lambda1,lambda2=1..10;gcd=1;all_divisor_pairs"
    )
    print(
        f"COUNTS=lambda_pairs:{len(lambdas)};tuples:{tuple_count};"
        f"factorizations:{factorization_count};divisor_pairs:{divisor_pair_count};"
        f"congruence_hits:{congruence_count};valid_form_occurrences:{valid_form_count};"
        f"discriminant_buckets:{len(buckets)}"
    )
    print(
        "DISCOVERED_RANK_HISTOGRAM="
        + ",".join(f"{rank}:{histogram[rank]}" for rank in sorted(histogram))
    )
    print(f"MAX_DISCOVERED_ORDER11_RANK={max_rank}")
    print(f"CHALLENGE_11_4_HITS={len(challenge_hits)}")
    print("TOP_BUCKETS=rank,unique_forms,D")
    for rank, form_count, delta in rank_rows[:20]:
        print(f"{rank}|{form_count}|{-delta}")
    print(
        "BOUNDARY=rank_is_only_the_span_of_forms_discovered_by_algorithm_3_2;"
        "no_full_class_group_negative_claim"
    )
    if pari_gp:
        pari_bucket_scan(
            [-delta for rank, _, delta in rank_rows if rank >= 2], pari_gp
        )


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bound", type=int, default=64)
    parser.add_argument("--pari-gp")
    args = parser.parse_args(argv)
    run(args.bound, args.pari_gp)


if __name__ == "__main__":
    main()
