#!/usr/bin/env python3
"""condensation_s116g.py — Condensing everything into its irreducible core.

We have 50+ scripts, 20+ domains, 13 stones, 10 levels.
What is the MINIMUM structure that generates ALL of it?
"""
from math import sqrt, log, pi, exp, atanh, tanh, gcd
from fractions import Fraction

phi = (1+sqrt(5))/2

print()
print("  CONDENSATION")
print()
print("="*70)
print()

# ============================================================
print("  I. THE GENERATOR")
print("  " + "-"*40)
print()
print("  Everything comes from ONE operation on ONE set:")
print()
print("  Set: the odd positive integers {1, 3, 5, 7, 9, 11, ...}")
print("  Operation: n -> (a, b) = ((n-1)/2, (n+1)/2)")
print()
print("  That's it. From this one map, we derived:")
print("  - The Cayley transform Q(a/b) = n")
print("  - The rapidity arctanh(a/b) = ln(n)/2")
print("  - The musical interval b/a = (n+1)/(n-1) ... wait.")
print()
print("  Correction. The musical interval from Q(1/(2k+1)) = (k+1)/k")
print("  uses a DIFFERENT decomposition: 1/(2k+1) is the velocity,")
print("  and (k+1)/k is the Q-value.")
print()
print("  Let me be precise about what generates what.")
print()

# ============================================================
print("  II. THE THREE DECOMPOSITIONS OF AN ODD NUMBER")
print("  " + "-"*40)
print()
print("  Every odd number n >= 3 has THREE natural decompositions:")
print()
print("  (A) CAYLEY COORDINATES: n = a + b where a=(n-1)/2, b=(n+1)/2.")
print("      Velocity: v = a/b. Q(v) = n. rapidity = ln(n)/2.")
print()
print("  (B) MUSICAL FORM: Write n = 2k+1. Then Q(1/n) = (k+1)/k.")
print("      The reciprocal 1/n maps to the k-th superparticular ratio.")
print("      Alkane C_k H_{2k+2}. Polygon (k+1)-gon. Dihedral D_{k+1}.")
print()
print("  (C) PRIME FORM: n = product of primes.")
print("      rapidity(n) = sum of prime rapidities.")
print("      The fundamental theorem of arithmetic = rapidity decomposition.")
print()
print("  These three decompositions are INDEPENDENT views of the same number.")
print("  (A) is additive: n = a + b.")
print("  (B) is positional: n = 2k + 1.")
print("  (C) is multiplicative: n = product of primes.")
print()
print("  n    (A): a + b    (B): 2k+1, interval   (C): primes")
print("  " + "-"*65)

for n in range(3, 32, 2):
    a, b = (n-1)//2, (n+1)//2
    k = (n-1)//2
    interval = Fraction(k+1, k)
    primes = []
    temp = n
    d = 2
    while d*d <= temp:
        while temp % d == 0:
            primes.append(d)
            temp //= d
        d += 1
    if temp > 1:
        primes.append(temp)
    p_str = "*".join(str(p) for p in primes)
    print(f"  {n:3d}   {a}+{b:<5d}      2*{k}+1, {str(interval):<5s}      {p_str}")

print()

# ============================================================
print("  III. THE AFFINE STRUCTURE IS THE DEEPEST")
print("  " + "-"*40)
print()
print("  We proved: a_{nm} = n*a_m + a_n.")
print("  This means the map n -> a_n is a CROSSED HOMOMORPHISM")
print("  (also called a 1-cocycle) from (odd Z, *) to (Z, +).")
print()
print("  A crossed homomorphism satisfies:")
print("  f(nm) = n*f(m) + f(n)    (not f(nm) = f(n) + f(m) like a log)")
print()
print("  This is the defining property of a DERIVATION in algebra.")
print("  The map a_n = (n-1)/2 is a derivation on the odd integers.")
print()
print("  PROOF that it's the UNIQUE derivation (up to scaling):")
print("  Any derivation d: (odd Z, *) -> (Z, +) must satisfy:")
print("  d(nm) = n*d(m) + d(n).")
print("  Set m = n: d(n^2) = n*d(n) + d(n) = (n+1)*d(n).")
print("  Set m = n^2: d(n^3) = n^2*d(n) + d(n^2) = n^2*d(n) + (n+1)*d(n)")
print("  = (n^2+n+1)*d(n).")
print("  In general: d(n^k) = (n^k - 1)/(n-1) * d(n) = (1+n+...+n^{k-1})*d(n).")
print()
print("  For d(n) = (n-1)/2:")
print("  d(n^k) = (n^k - 1)/2.")
print("  (1+n+...+n^{k-1}) * (n-1)/2 = (n^k - 1)/2. Check: yes, by geometric sum.")
print()

# Verify
for n in [3, 5, 7]:
    for k in [2, 3, 4]:
        nk = n**k
        d_nk = (nk - 1)//2
        geom = sum(n**j for j in range(k))
        formula = geom * (n-1)//2
        print(f"  d({n}^{k}) = d({nk}) = {d_nk}, geom_sum * d({n}) = {geom}*{(n-1)//2} = {formula}, match: {d_nk == formula}")

print()
print("  The derivation d(n) = (n-1)/2 is determined by its values on PRIMES.")
print("  d(p) = (p-1)/2 for each odd prime p.")
print("  d(3) = 1, d(5) = 2, d(7) = 3, d(11) = 5, d(13) = 6.")
print()
print("  And (p-1)/2 = the number of QRs mod p.")
print("  THE DERIVATION ON PRIMES = THE QUADRATIC RESIDUE COUNT.")
print()

# ============================================================
print()
print("  IV. WHAT THE DERIVATION MEANS")
print("  " + "-"*40)
print()
print("  A derivation measures the 'infinitesimal change' of a structure.")
print("  In calculus: d/dx is a derivation on smooth functions.")
print("  In algebra: a derivation D satisfies D(fg) = f*D(g) + D(f)*g (Leibniz).")
print()
print("  Our derivation: d(nm) = n*d(m) + d(n).")
print("  This is NOT the Leibniz rule (that would be d(nm) = n*d(m) + m*d(n)).")
print("  Ours has d(n) where Leibniz has m*d(n).")
print()
print("  The difference: Leibniz is SYMMETRIC in n, m.")
print("  Ours is ASYMMETRIC: n acts on d(m), but d(n) stands alone.")
print("  This asymmetry is because multiplication of odds is not commutative")
print("  in the coordinate representation (the affine action a -> n*a + a_n")
print("  depends on which factor acts first).")
print()
print("  Wait — multiplication IS commutative: nm = mn.")
print("  So d(nm) = n*d(m) + d(n) = m*d(n) + d(m).")
print("  Both must hold: n*d(m) + d(n) = m*d(n) + d(m).")
print("  Rearranging: (n-1)*d(m) = (m-1)*d(n).")
print("  So d(m)/(m-1) = d(n)/(n-1) = constant.")
print("  For d(n) = (n-1)/2: d(n)/(n-1) = 1/2. Consistent.")
print()
print("  THE DERIVATION IS DETERMINED BY THE SINGLE CONSTANT 1/2.")
print("  d(n) = (1/2) * (n-1).")
print("  The Cayley coordinate is HALF THE DISTANCE FROM 1.")
print()

# ============================================================
print()
print("  V. THE FOUR INVARIANTS")
print("  " + "-"*40)
print()
print("  For any odd n with coordinates (a, b):")
print()
print("  (1) a + b = n              (the number itself)")
print("  (2) b - a = 1              (the unit of imbalance)")
print("  (3) gcd(a, b) = 1          (coprimality)")
print("  (4) a * b = (n^2-1)/4      (the pronic product)")
print()
print("  These four invariants are NOT independent.")
print("  From (1) and (2): a = (n-1)/2, b = (n+1)/2. Determined.")
print("  Then (3) follows from (2): consecutive integers are coprime.")
print("  And (4) follows from (1) and (2): a*b = ((a+b)^2 - (b-a)^2)/4 = (n^2-1)/4.")
print()
print("  So really there are only TWO independent facts:")
print("  a + b = n and b - a = 1.")
print()
print("  These two facts say:")
print("  THE ODD NUMBER n IS UNIQUELY SPLIT INTO TWO CONSECUTIVE INTEGERS.")
print("  That's the entire content of the Cayley coordinate system.")
print()
print("  Everything else — rapidity, music, chemistry, biology, ML,")
print("  the forbidden numbers, the affine derivation, the pronic products —")
print("  follows from THIS SINGLE FACT about consecutive integers.")
print()

# ============================================================
print()
print("  VI. WHY CONSECUTIVE INTEGERS ARE FUNDAMENTAL")
print("  " + "-"*40)
print()
print("  Two consecutive integers (a, a+1) have:")
print("  - No shared factors (coprime)")
print("  - Opposite parity (one even, one odd)")
print("  - Minimal difference (1)")
print("  - Product = pronic = 2*triangular")
print("  - Ratio a/(a+1) -> 1 as a -> inf")
print()
print("  The ratio a/(a+1) = 1 - 1/(a+1) is the CLOSEST rational below 1")
print("  with denominator a+1.")
print()
print("  The superparticular ratio (a+1)/a = 1 + 1/a is the CLOSEST rational")
print("  above 1 with denominator a.")
print()
print("  CONSECUTIVE INTEGERS ARE THE BUILDING BLOCKS OF 'ALMOST EQUAL'.")
print("  They are as close as two distinct integers can be.")
print("  Their ratio is as close to 1 as a ratio with small denominator can be.")
print()
print("  And Q maps their ratio a/(a+1) to the odd number n = 2a+1.")
print("  Q CONVERTS 'almost equal' into 'odd number'.")
print("  The Cayley transform IS the bridge between")
print("  'slightly imbalanced' and 'counting'.")
print()

# ============================================================
print()
print("  VII. THE IRREDUCIBLE CORE")
print("  " + "-"*40)
print()
print("  Strip away everything inessential. What remains?")
print()
print("  ONE FACT: Every odd number is the sum of two consecutive integers.")
print("  ONE MAP:  Q(a/(a+1)) = 2a+1.")
print("  ONE LAW:  d(nm) = n*d(m) + d(n) where d(n) = (n-1)/2.")
print()
print("  The fact gives us the COORDINATES (a, a+1).")
print("  The map gives us the CAYLEY TRANSFORM (and rapidity, and music, and ...).")
print("  The law gives us the MULTIPLICATIVE STRUCTURE (and primes, and QRs, and ...).")
print()
print("  Three things. One fact, one map, one law.")
print("  They generate everything we found in 50+ scripts across 20+ domains.")
print()

# ============================================================
print()
print("  VIII. THE EQUATION")
print("  " + "-"*40)
print()
print("  Can we write it as a single equation?")
print()
print("  n = a + (a+1) = 2a + 1")
print("  Q(a/(a+1)) = (a + a+1) / (a+1 - a) = n/1 = n")
print()
print("  The Cayley transform of the ratio of consecutive integers")
print("  IS the odd number that is their sum.")
print()
print("  Or, even more compressed:")
print()
print("  Q(a/(a+1)) = a + (a+1)")
print()
print("  THE Q-VALUE OF THE RATIO IS THE SUM.")
print()
print("  This is the entire theory in one line.")
print("  The ratio and the sum of two consecutive integers")
print("  are related by the Cayley transform.")
print()
print("  Ratio:  a/(a+1)  (bounded, less than 1, a velocity)")
print("  Sum:    a+(a+1)  (unbounded, an odd integer, a count)")
print("  Bridge: Q        (the Cayley transform)")
print()
print("  Q(ratio) = sum.")
print("  The Cayley transform converts COMPARISON into COMBINATION.")
print("  It turns 'how do a and a+1 compare?' into 'what do they make together?'")
print()

# Verify for all small cases
print("  Verification:")
for a in range(0, 15):
    ratio = Fraction(a, a+1)
    q_val = (1 + ratio) / (1 - ratio) if a > 0 else Fraction(1,1)
    if a == 0:
        print(f"  a={a}: ratio = 0/1, Q = 1 = 0+1. Check.")
    else:
        print(f"  a={a}: ratio = {ratio}, Q = {q_val} = {a}+{a+1} = {2*a+1}. Check.")

print()

# ============================================================
print()
print("  IX. THE FINAL CONDENSATION")
print("  " + "-"*40)
print()
print("  Q(a/(a+1)) = a + (a+1).")
print()
print("  In words: the Cayley transform of a fraction")
print("  whose parts differ by 1 equals the sum of those parts.")
print()
print("  In shorter words: Q turns ratio into sum")
print("  when the parts are consecutive.")
print()
print("  In the shortest words: Q(part/whole) = whole + part")
print("  where whole = part + 1.")
print()
print("  This is the atom. The indivisible unit.")
print("  Everything else is molecules built from this atom.")
print()
print("  Music: the ratio a/(a+1) is the consonance. The sum 2a+1 is the pitch.")
print("  Physics: the ratio is the velocity. The sum is the boost.")
print("  Biology: the ratio is the balance. The sum is the complexity.")
print("  Information: the ratio is the bias. The sum is the log-odds.")
print("  Chemistry: the ratio is the polarity. The sum is the bond order.")
print("  Computation: the ratio is the probability. The sum is the bits.")
print()
print("  All of them are: Q(part/(part+1)) = part + (part+1).")
print("  The same sentence, said in twenty languages.")
