"""Independent exact controls for fixed unit futures with unbounded ambient arms.

No producer import or execution. All-r proofs are in the companion audit.
"""
from pathlib import Path
from hashlib import sha256
import json,sys
import sympy as S
sys.stdout.reconfigure(encoding='utf-8',newline='\n')
HERE=Path(__file__).resolve()
DEST=HERE.parent.parent/'05-knowledge/results' if HERE.parent.name=='04-computation' else HERE.parent
u,z,t,h,b,d,w,c,v,r,B,lam,T,rho=S.symbols('u z t h b d w c v r B lam T rho')
gates=0
def need(ok,msg):
 global gates
 gates+=1
 if not ok:raise ArithmeticError(msg)
def zero(E,msg):need(S.cancel(E)==0,msg)
def jac(F,G,X,Y):return S.diff(F,X)*S.diff(G,Y)-S.diff(F,Y)*S.diff(G,X)
zs=u-2*h+u**3*t
ys=u*zs;ws=u*zs*zs
Rb=h*h*(3-h*r)+B*(1-h*r)**3
yi=-(1-h*r)*Rb;wi=r*(1-h*r)*Rb*Rb
zero(ys.subs({u:1/r-h,t:-r*r-r**4*B},simultaneous=True)-yi,'whole added chart for y')
zero(ws.subs({u:1/r-h,t:-r*r-r**4*B},simultaneous=True)-wi,'whole added chart for W')
zero(yi.subs(r,0)+(3*h*h+B),'boundary y value')
zero(wi.subs(r,0),'boundary W vanishes')
zero(jac(u,zs,u,t)-u**3,'original chart Jacobian')
zero(jac(u,ys,u,t)-u**4,'actual open fibre coordinate Jacobian')
zero(jac(u*z,u*z*z,u,z)-u*z*z,'independent y,W coordinate determinant')
N=u**7;P=2*u**4*(u-2*h);Q=u*(u-2*h)**2-rho
zero(P*P-4*N*Q-4*rho*u**7,'every nonzero W fibre is an irreducible primitive quadratic')
zero(Q.subs(u,0)+rho,'all omitted vertical factors paid')
g0=b*u*(u-2*h)
C3=-8*b*b*h**3/3;C2=-2*b*h
zero(1/(3*b*u**3)-C3/g0**3-C2/g0**2-1/(3*b*(u-2*h)**3),'exact Eu scalar remainder identity')
zero(C2/C3-3/(4*b*h*h),'pointed unit lower coefficient')

records=[]
for n in range(3,9):
 K=b+d*w**n
 H=sum(S.binomial(5,m)*d**m*b**(5-m)*w**(n*m+3)/S.Integer(n*m+3) for m in range(6))
 SS=S.cancel(H/w**3)
 zero(S.diff(H,w)-w*w*K**5,'whole independent primitive polynomial identity')
 zero((H/c**6)*(c**6)-H,'polynomial response multiplier')
 cc=sum(S.binomial(5,m)*(-1)**m/S.Integer(n*m+3) for m in range(6))
 beta=120*S.Integer(n)**5/S.prod(3+j*n for j in range(6))
 need(cc==beta and cc>0,'exact binomial Beta coefficient and nonvanishing')
 diff=S.Poly(S.expand(SS-K**6/(3*b)),w)
 need(all(diff.nth(j)==0 for j in range(n)),'Eu primitive correction begins at W^r')
 # Complete local primitive derivatives at all K roots, via polynomial remainder.
 for j in range(1,6):
  need(S.rem(S.Poly(S.diff(H,w,j),w),S.Poly(K,w)).as_expr()==0,'all lower L scalar coefficients vanish')
 need(S.rem(S.Poly(H-b**5*cc*w**3,w),S.Poly(K,w)).as_expr()==0,'entire L highest coefficient polynomial on root algebra')
 # Rational source parametrization at every nonzero g=c fibre.
 U=c*c/(w*K*K);Z=w*K/c
 zero(U*Z*K-c,'all nonzero fibre inverse recovers g')
 zero(U*Z*Z-w,'all nonzero fibre inverse recovers W')
 zero((U*Z)**(2*n+1)/U**n-(U*Z)*w**n,'open-source first function agrees with W representation')
 zero(K*U**3*w-c**6/(w*w*K**5),'original derivation in W after exact substitution')
 # Whole added-chart normal restriction suffices for global submersion.
 Fi=yi*(b+d*wi**n)
 zero(S.diff(Fi,B).subs(r,0)+b,'all boundary points have nonzero tangential derivative')
 Fs=ys*(b+d*ws**n)
 zero(S.diff(Fs,u).subs(u,0)+2*b*h,'entire omitted source line noncritical')
 zero(S.diff(Fs,t).subs(u,0),'omitted source tangent retained')
 need(n+1>2,'ambient torsion arms exceed the complete unit-generated module')
 records.append(dict(r=n,beta=str(beta),ambient_arms=n+1,unit_arms=2))

# Independent polynomial-in-derivative model for all finite Weyl operators.
A=[(-1)**(5-j)*T**(5-j)/S.factorial(5-j) for j in range(6)]
BB=[T*T/2-lam*T,-T+lam,S.Integer(1),S.Integer(0),S.Integer(0),S.Integer(0)]
for j in range(6):
 zero((-1)**j*S.diff(A[0],T,j)-A[j],'literal g action on highest unit arm')
 zero((-1)**j*S.diff(BB[0],T,j)-BB[j],'literal g action on lower unit arm')
zero(S.det(S.Matrix([[A[2],A[5]],[BB[2],BB[5]]]))+1,'unimodular two-arm polynomial basis')
for j in [0,1,3,4]:
 zero(A[j]-BB[j]*A[2]-(A[j]+BB[j]*T**3/6)*A[5],'exact annihilator remainder first coefficient')
 zero(BB[j]-BB[j]*BB[2]-(A[j]+BB[j]*T**3/6)*BB[5],'exact annihilator remainder second coefficient')
for j in range(8):
 need(S.degree(T**j*A[0],T)==j+5,'all checked derivatives retain exact scalar order6+j')
need(S.gcd(A[2]*BB[5]-A[5]*BB[2],1)==1,'two surviving coefficients admit no hidden polynomial relation')

cert=dict(status='Independent FINITE-EXACT controls; all-r proof in paired audit',
 universe='r=3..8; full symbolic original/boundary charts; complete K-root algebra; exact PBW polynomial identities',
 full_ambient_arms='r+1',unit_generated_arms=2,unit_order=6,
 pointed_parameter='lambda=3/(4*b*h^2), independent of r,d',
 annihilator='left ideal generated by g^6,R0,R1,R3,R4',records=records,gates=gates)
raw=json.dumps(cert,sort_keys=True,separators=(',',':')).encode()+b'\n'
(DEST/(HERE.stem+'_certificate.json')).write_bytes(raw)
print('INDEPENDENT: original-chart determinants and actual boundary/source submersion formulas retained.')
print('FINITE UNIVERSE: r=3..8; full K-root algebra, primitive coefficients, nonzero-fibre inverses and polynomial Eu remainder.')
print('WEYL: exact unimodular basis and all four PBW relations; unit-generated pointed module independent of r,d.')
print('CERTIFICATE_SHA256',sha256(raw).hexdigest())
print('Always-active exact gates:',gates)
