#!/usr/bin/env python3
"""
coset_structure.py — opus-2026-03-12-S69

Investigate the multiplicative coset structure of circulant orientations
and its connection to Q-spectrum structure and chi_per.

Key finding: At p=13, the orbit with chi_per=-17 has S = {1,3,9} ∪ {2,6,5}
= two cosets of the cubic residue subgroup H = <3> ⊂ Z_13*.

Question: Is this a general pattern? At each p, which subgroups of Z_p* give
interesting tournament orientations?

For p prime, Z_p* ≅ Z_{p-1} (cyclic). Its subgroups correspond to divisors of p-1.
A tournament orientation S has |S| = m = (p-1)/2, and is obtained by choosing
one from each pair {d, p-d}. An orientation built from k cosets of a subgroup H
of order h has |S| = k*h. For |S| = m = (p-1)/2, we need k*h = (p-1)/2.

The subgroup structure of Z_p*:
  p=7: Z_6 = Z_2 × Z_3. Subgroups: {1}, {1,6}≅Z_2, {1,2,4}≅Z_3, Z_6.
  p=11: Z_10 = Z_2 × Z_5. Subgroups: {1}, {1,10}≅Z_2, {1,3,9,5,4}≅Z_5, Z_10.
  p=13: Z_12 = Z_4 × Z_3. Subgroups: many more.
"""

import numpy as np
from math import gcd

def is_prime(n):
    if n < 2: return False
    for d in range(2, int(n**0.5)+1):
        if n % d == 0: return False
    return True

def primitive_root(p):
    """Find smallest primitive root mod p."""
    for g in range(2, p):
        seen = set()
        x = 1
        for _ in range(p-1):
            seen.add(x)
            x = (x * g) % p
        if len(seen) == p-1:
            return g
    return None

def subgroups_of_cyclic(n):
    """List all subgroups of Z_n (by their order)."""
    return sorted(d for d in range(1, n+1) if n % d == 0)

def generate_subgroup(g, p, h):
    """Generate subgroup of Z_p* of order h generated by g^((p-1)/h)."""
    gen = pow(g, (p-1)//h, p)
    H = set()
    x = 1
    for _ in range(h):
        H.add(x)
        x = (x * gen) % p
    return frozenset(H)

def cosets(H, p):
    """List all cosets of H in Z_p*."""
    covered = set()
    result = []
    for a in range(1, p):
        if a not in covered:
            coset = frozenset((a * h) % p for h in H)
            result.append(coset)
            covered.update(coset)
    return result

def compute_Q(p, S):
    m = (p-1)//2
    return np.array([abs(sum(np.exp(2j*np.pi*s*k/p) for s in S))**2 for k in range(1, m+1)])

def is_tournament_orientation(S, p):
    """Check if S is a valid tournament orientation: one from each {d, p-d} pair."""
    m = (p-1)//2
    if len(S) != m:
        return False
    for d in range(1, m+1):
        if (d in S) == ((p-d) in S):  # Both or neither
            return False
    return True

for p in [7, 11, 13, 17, 19, 23, 29]:
    if not is_prime(p):
        continue
    m = (p-1)//2
    g = primitive_root(p)
    print(f"\n{'='*70}")
    print(f"p = {p}, m = {m}, primitive root g = {g}")
    print(f"Z_{p-1} subgroup orders: {subgroups_of_cyclic(p-1)}")
    print(f"{'='*70}")

    # For each subgroup H of Z_p*, check if unions of cosets of H
    # can form valid tournament orientations
    for h in subgroups_of_cyclic(p-1):
        if h > m:
            continue
        if m % h != 0:
            continue
        k = m // h  # Need k cosets

        H = generate_subgroup(g, p, h)
        all_cosets = cosets(H, p)
        n_cosets = len(all_cosets)

        print(f"\n  Subgroup H of order {h}: {sorted(H)}")
        print(f"  Number of cosets: {n_cosets}, need {k} cosets for |S|={m}")

        # Enumerate all ways to choose k cosets
        from itertools import combinations
        valid_count = 0
        valid_examples = []

        for combo in combinations(range(n_cosets), k):
            S = frozenset().union(*(all_cosets[i] for i in combo))
            if is_tournament_orientation(S, p):
                valid_count += 1
                if len(valid_examples) < 3:
                    Q = compute_Q(p, S)
                    valid_examples.append({
                        'S': sorted(S),
                        'Q_sorted': sorted(Q, reverse=True),
                        'Q_distinct': len(set(round(q, 4) for q in Q)),
                        'prod_Q': float(np.prod(Q)),
                    })

        print(f"  Valid tournament orientations from {k} cosets: {valid_count}")
        for ex in valid_examples:
            print(f"    S = {ex['S']}")
            print(f"    Q (sorted) = [{', '.join(f'{q:.3f}' for q in ex['Q_sorted'])}]")
            print(f"    #distinct Q = {ex['Q_distinct']}, prod Q = {ex['prod_Q']:.1f}")

        # Special case: H = QR (quadratic residues, order (p-1)/2)
        if h == (p-1)//2:
            print(f"  ** H = QR (quadratic residues) = Paley orientation **")

print("\nDONE.")
