#!/usr/bin/env python3
"""duality_s116f.py — The duality of sameness and difference.

Q(x) = (1+x)/(1-x) = sameness/difference.

But sameness and difference are not opposites.
They are TWO READINGS OF THE SAME THING.

1+x and 1-x differ by 2x. They agree on 1.
The shared part is 1. The disputed part is x.
Q measures how much of the whole is disputed.
"""
from math import sqrt, log, pi, exp, atanh, tanh
from fractions import Fraction

print()
print("  THE DUALITY OF SAMENESS AND DIFFERENCE")
print()
print("="*70)
print()

# ============================================================
print("  PART I: THE ANATOMY OF Q")
print("  " + "-"*40)
print()
print("  Q(x) = (1+x)/(1-x)")
print()
print("  Numerator:   1 + x = the AGREEMENT")
print("  Denominator: 1 - x = the DISAGREEMENT")
print()
print("  Both contain 1. Both contain x.")
print("  The only difference between agreement and disagreement")
print("  is the SIGN of x.")
print()
print("  Agreement says: 1 AND x. (addition)")
print("  Disagreement says: 1 NOT x. (subtraction)")
print()
print("  Q is the ratio of AND to NOT.")
print()
print("  When x = 0:  AND = NOT = 1.  Q = 1.  Perfect balance.")
print("  When x > 0:  AND > NOT.      Q > 1.  More agreement than disagreement.")
print("  When x < 0:  AND < NOT.      Q < 1.  More disagreement than agreement.")
print("  When x = 1:  AND = 2, NOT = 0.  Q = inf.  Total agreement (no disagreement).")
print("  When x = -1: AND = 0, NOT = 2.  Q = 0.  Total disagreement (no agreement).")
print()

# ============================================================
print()
print("  PART II: SOMETIMES AND NOT")
print("  " + "-"*40)
print()
print("  Consider a proposition P about the world.")
print("  It is true with probability p and false with probability 1-p.")
print()
print("  The 'sometimes' of P: how often P is true = p.")
print("  The 'not' of P: how often P is false = 1-p.")
print()
print("  The odds ratio = p/(1-p) = sometimes/not.")
print("  The log-odds = ln(sometimes/not) = logit(p) = 2*rapidity.")
print()
print("  But there is a DEEPER reading.")
print()
print("  Define:")
print("  x = 2p - 1 = the EXCESS of sometimes over not.")
print("  When p = 1/2: x = 0. Sometimes = not. No excess.")
print("  When p = 1:   x = 1. All sometimes. No not.")
print("  When p = 0:   x = -1. All not. No sometimes.")
print()
print("  Then:")
print("  1 + x = 2p = twice the sometimes.")
print("  1 - x = 2(1-p) = twice the not.")
print("  Q(x) = (1+x)/(1-x) = p/(1-p) = the odds.")
print()
print("  Q IS THE ODDS RATIO.")
print("  Rapidity IS half the log-odds.")
print("  This is not an analogy. It is the DEFINITION.")
print()

# ============================================================
print()
print("  PART III: THE DUALITY IS NOT OPPOSITION")
print("  " + "-"*40)
print()
print("  Sameness and difference are usually treated as OPPOSITES.")
print("  Same vs different. Agreement vs disagreement. 1 vs 0.")
print()
print("  But Q reveals they are not opposites.")
print("  They are TWO MEASUREMENTS OF THE SAME QUANTITY x.")
print()
print("  1+x measures how much x ALIGNS with the reference (1).")
print("  1-x measures how much x DEVIATES from the reference.")
print()
print("  The reference IS the boundary between the two.")
print("  The reference is 1 in Q. It is 1/2 in probability.")
print("  It is 0 in rapidity. It is the FAIR COIN.")
print()
print("  Sameness and difference are not opposite THINGS.")
print("  They are opposite DIRECTIONS from the same center.")
print("  Like left and right are not opposite things —")
print("  they are opposite directions from HERE.")
print()
print("  And Q measures not 'how much sameness' or 'how much difference'")
print("  but THE RATIO BETWEEN THE TWO DIRECTIONS.")
print("  It measures the TILT of the world.")
print()

# ============================================================
print()
print("  PART IV: THE TILT")
print("  " + "-"*40)
print()
print("  Every measurement is a tilt.")
print()
for x_val in [Fraction(-4,5), Fraction(-1,2), Fraction(-1,5),
              Fraction(0), Fraction(1,5), Fraction(1,2), Fraction(4,5)]:
    x = float(x_val)
    same = 1 + x
    diff = 1 - x
    if diff > 0:
        q = (1+x)/(1-x)
        rap = atanh(x)
    else:
        q = float('inf')
        rap = float('inf')

    bar_same = "#" * int(same * 20)
    bar_diff = "#" * int(diff * 20)

    print(f"  x = {str(x_val):>5s}:")
    print(f"    sameness  (1+x) = {same:.2f}  {bar_same}")
    print(f"    difference(1-x) = {diff:.2f}  {bar_diff}")
    if q < 100:
        print(f"    tilt Q = {q:.4f}, rapidity = {rap:+.4f}")
    else:
        print(f"    tilt Q = infinity")
    print()

print("  The tilt is zero at x=0. The bars are equal length.")
print("  As x increases, sameness grows and difference shrinks.")
print("  As x decreases, difference grows and sameness shrinks.")
print("  The rapidity tells you: how many doublings of tilt?")
print()

# ============================================================
print()
print("  PART V: WHAT THE TILT MEASURES IN EACH DOMAIN")
print("  " + "-"*40)
print()
print("  DOMAIN        SAMENESS (1+x)          DIFFERENCE (1-x)")
print("  " + "-"*60)
print("  Physics       how much A and B        how much A and B")
print("                agree on velocity       disagree on velocity")
print()
print("  Probability   weight of evidence      weight of evidence")
print("                FOR the hypothesis      AGAINST the hypothesis")
print()
print("  Music         how close two notes     how far apart")
print("                are in frequency        two notes are")
print()
print("  Chemistry     shared electron         unshared electron")
print("                density (covalent)      density (ionic)")
print()
print("  Biology       how similar two         how different two")
print("                organisms are           organisms are")
print()
print("  Voting        number of voters        number of voters")
print("                who AGREE               who DISAGREE")
print()
print("  Perception    stimulus matches        stimulus differs")
print("                expectation             from expectation")
print()
print("  Tournaments   consistent arcs         contradictory arcs")
print("                (transitive triples)    (3-cycles)")
print()
print("  In EVERY case, Q = sameness/difference = AND/NOT.")
print("  The rapidity = how many doublings of AND over NOT.")
print()

# ============================================================
print()
print("  PART VI: THE IMPOSSIBILITY OF PURE SAMENESS")
print("  " + "-"*40)
print()
print("  Q(1) = infinity.")
print("  Pure sameness (no difference at all) requires INFINITE rapidity.")
print("  You can never GET THERE.")
print()
print("  This is the speed of light. The certainty. The unison.")
print("  The perfect consensus. The pure covalent bond in vacuum.")
print("  The transitive tournament with no cycles.")
print()
print("  Wait — H(transitive) = 1 IS achievable. That's not infinity.")
print("  But the RAPIDITY of the transitive tournament is 0, not infinity.")
print()
print("  The resolution: the transitive tournament has x = 0,")
print("  meaning HALF its arcs are 'same' and half are 'different'")
print("  (in the tiling model). It is the BALANCED point, not the")
print("  extreme point. H = 1 means there is exactly ONE ordering.")
print("  That's not infinite sameness — it's perfect ORDER.")
print()
print("  Perfect order (H=1) is at the CENTER (rapidity 0).")
print("  Maximum complexity (H=max) is between center and pole.")
print("  The pole (rapidity infinity) is unreachable.")
print()
print("  So the structure is:")
print("  rapidity 0 = ORDER (one path, one truth, one ranking)")
print("  rapidity ~1 = COMPLEXITY (many paths, many truths)")
print("  rapidity inf = CHAOS (infinite paths, no truth)")
print()
print("  The forbidden H=7 is at rapidity 0.97 ~ 1.")
print("  It sits at the boundary between order and complexity.")
print("  IT IS FORBIDDEN BECAUSE IT IS THE BOUNDARY ITSELF.")
print("  You cannot stand on a boundary. You can only cross it.")
print()

# ============================================================
print()
print("  PART VII: SOMETIMES")
print("  " + "-"*40)
print()
print("  'Sometimes' is the most interesting word.")
print()
print("  'Always' is pure sameness: x = 1, Q = infinity.")
print("  'Never' is pure difference: x = -1, Q = 0.")
print("  'Sometimes' is the entire interval (-1, 1).")
print()
print("  EVERYTHING REAL IS SOMETIMES.")
print("  Nothing real is always or never.")
print("  Every probability is strictly between 0 and 1.")
print("  Every velocity is strictly less than c.")
print("  Every bond is partly covalent and partly ionic.")
print("  Every tournament has at least 1 and at most n!/2^{n-1} paths.")
print()
print("  Rapidity measures WHERE in 'sometimes' you are.")
print("  It measures the SHADE of sometimes.")
print("  Near-always (high positive rapidity): rare events that almost never fail.")
print("  Near-never (high negative rapidity): rare events that almost never happen.")
print("  Near-half (rapidity near 0): the coin flip, the maximum uncertainty.")
print()
print("  And the beauty of rapidity is that it makes 'sometimes'")
print("  into a NUMBER LINE. Every shade of 'sometimes' has a")
print("  position on the rapidity line. And the operations")
print("  (composition, comparison, combination) are ARITHMETIC")
print("  on that line.")
print()
print("  'Sometimes AND sometimes' = add the rapidities.")
print("  'Sometimes OR not-sometimes' = subtract the rapidities.")
print("  'How much more sometimes than not' = the rapidity itself.")
print()

# ============================================================
print()
print("  PART VIII: THE DEEPEST DUALITY")
print("  " + "-"*40)
print()
print("  Q(x) = (1+x)/(1-x).")
print("  Q(-x) = (1-x)/(1+x) = 1/Q(x).")
print()
print("  Negating x INVERTS Q.")
print("  Swapping sameness and difference RECIPROCATES the ratio.")
print()
print("  This means: if I measure the world and get Q,")
print("  then someone who sees everything I call 'same' as 'different'")
print("  and everything I call 'different' as 'same'")
print("  will measure 1/Q.")
print()
print("  Their rapidity = -my rapidity.")
print("  Their 'sometimes' = my 'sometimes-not'.")
print()
print("  And Q(x) * Q(-x) = Q(x) * 1/Q(x) = 1.")
print("  The product of the two perspectives is ALWAYS 1.")
print("  The geometric mean of the two views is the reference.")
print()
print("  This is the deepest duality:")
print("  FOR EVERY MEASUREMENT, THERE IS AN EQUAL AND OPPOSITE MEASUREMENT.")
print("  And the two together give unity.")
print()
print("  This is not 'balance' in the naive sense.")
print("  It is the statement that OBSERVATION CREATES DISTINCTION.")
print("  Before you measure, there is no sameness or difference.")
print("  After you measure, there is Q AND 1/Q, always paired.")
print("  The pair (Q, 1/Q) is the irreducible unit of knowledge.")
print()
print("  In rapidity: the pair is (phi, -phi).")
print("  Every rapidity is born as a TWIN.")
print("  The twins are equal in magnitude, opposite in sign.")
print("  One twin says 'more same than different'.")
print("  The other says 'more different than same'.")
print("  They are the same measurement, seen from two sides.")
print()

# ============================================================
print()
print("  PART IX: Q AS A MIRROR")
print("  " + "-"*40)
print()
print("  Q is not a function. Q is a MIRROR.")
print()
print("  A mirror takes what is in front of it (the bounded: |x| < 1)")
print("  and shows what is behind it (the unbounded: Q > 1 or Q < 1).")
print()
print("  The reflection is not a copy. It is a TRANSFORMATION.")
print("  Left becomes right. Bounded becomes unbounded.")
print("  Sameness becomes a number. Difference becomes its reciprocal.")
print()
print("  And like a real mirror, Q preserves ANGLES but reverses DEPTH.")
print("  (Q is conformal: it preserves angles between curves.)")
print("  (Q maps the interior to the exterior: reverses 'depth'.)")
print()
print("  When you look in the Cayley mirror:")
print("  - You see yourself (the function is its own 'almost-inverse')")
print("  - But reversed (Q^2 = -1/x, not identity)")
print("  - And it takes four looks (Q^4 = identity) to see the original")
print()
print("  Four looks in the mirror to see yourself truly.")
print("  That is the period-4 symmetry.")
print("  That is the four faces of every orbit.")
print("  That is the four seasons of understanding.")
print()

# ============================================================
print()
print("  PART X: THE FINAL WORD")
print("  " + "-"*40)
print()
print("  Sameness and difference are not two things.")
print("  They are one thing — RELATION — seen from two sides.")
print()
print("  Q does not COMPUTE the relation.")
print("  Q IS the relation.")
print()
print("  (1+x) is what the relation AFFIRMS.")
print("  (1-x) is what the relation DENIES.")
print("  The ratio is the relation's JUDGMENT.")
print()
print("  And rapidity — the logarithm of the judgment —")
print("  is the relation's MEMORY.")
print("  It remembers how many times the judgment doubled.")
print("  It remembers the history of distinction.")
print()
print("  Every number is a memory of doublings.")
print("  Every measurement is a judgment of sameness vs difference.")
print("  Every function is a mirror that shows the judgment.")
print()
print("  Q is the simplest mirror.")
print("  Rapidity is the simplest memory.")
print("  And the duality of sameness and difference")
print("  is the simplest relation.")
print()
print("  There is nothing underneath.")
print("  This is the bottom.")
