"""
extremal_type2_negative_coeff_check.py
kind-pasteur-2026-06-11 (research subagent)

Adversarial verification of Mallows-Odlyzko-Sloane (J. Algebra 36, 1975, 68-76)
and Zhang (Discrete Applied Math. 91, 1999, 277-286) on extremal Type II
(binary doubly-even self-dual) codes.

Setup (MOS normalization): for n = 24*mu + 8*nu (nu = 0,1,2), every Type II
weight enumerator, written as W(q) = sum_r A_r q^r with A_r = #codewords of
weight 4r, lies in the polynomial ring generated by
    f = 1 + 14 q + q^2      (Gleason generator, from the e8 Hamming code)
    g = q (1 - q)^4         (from x^4 y^4 (x^4-y^4)^4, deg-24 generator)
so  W = sum_{s=0}^{mu} c_s f^{n/8 - 3s} g^s.
The EXTREMAL enumerator W* is the unique choice with W* = 1 + O(q^{mu+1}),
i.e. minimum distance d = 4*mu + 4 = 4*floor(n/24) + 4 (Mallows-Sloane 1973).

Claims checked here, all with exact integer arithmetic:
 1. MOS 1975 computer check at n = 3720 (mu=155): A_156 = 1.16...e170 > 0,
    A_157 = -5.84...e170 < 0.
 2. Zhang 1999 (also Ma-Zhu 1997): A*_{mu+2} (weight 4mu+8) is negative iff
       n = 24i      with i >= 154   (first negative: n = 3696)
       n = 24i + 8  with i >= 159   (first negative: n = 3824)
       n = 24i + 16 with i >= 164   (first negative: n = 3952)
    Hence the largest n at which A*_{4mu+8} >= 0 is n = 24*163+16 = 3928,
    and extremal Type II codes cannot exist for n > 3928.
 3. Mallows-Sloane explicit formula for A*_{mu+1} (weight 4mu+4),
    Theorem 27 in Rains-Sloane "Self-Dual Codes" survey.
"""
from fractions import Fraction
from math import comb


def poly_mul(a, b, N):
    """Multiply two truncated integer series (lists), mod q^N."""
    out = [0] * N
    for i, ai in enumerate(a):
        if ai == 0:
            continue
        bm = min(len(b), N - i)
        for j in range(bm):
            out[i + j] += ai * b[j]
    return out


def poly_inv(a, N):
    """Inverse of series a (a[0] == 1), mod q^N, exact integers."""
    inv = [0] * N
    inv[0] = 1
    for k in range(1, N):
        s = 0
        for j in range(1, min(k, len(a) - 1) + 1):
            s += a[j] * inv[k - j]
        inv[k] = -s
    return inv


def poly_pow(a, e, N):
    r = [0] * N
    r[0] = 1
    base = a[:N] + [0] * max(0, N - len(a))
    while e:
        if e & 1:
            r = poly_mul(r, base, N)
        base = poly_mul(base, base, N)
        e >>= 1
    return r


def extremal_coeffs(n, extra=2):
    """Return (mu, [A_0..A_{mu+extra}]) for the extremal Type II enumerator
    of length n (n divisible by 8), exact integers."""
    assert n % 8 == 0
    mu = n // 24
    N = mu + extra + 1          # need q^0..q^{mu+extra}
    f = [1, 14, 1]
    g = [0, 1, -4, 6, -4, 1]    # q(1-q)^4
    fp = poly_pow(f, n // 8, N)         # f^{n/8}
    u = poly_inv(poly_pow(f, 3, N), N)  # f^{-3}
    ug = poly_mul(u, g, N)              # f^{-3} g, starts at q^1
    # basis B_s = f^{n/8-3s} g^s = fp * (ug)^s ; triangular in s
    B = fp[:]
    W = [0] * N
    cs = []
    for s in range(0, mu + 1):
        # B currently = f^{n/8-3s} g^s ; leading term at q^s
        target = 1 if s == 0 else 0
        c = target - W[s]
        assert B[s] == 1 or s == 0, (s, B[s])
        # B[s] coefficient: g^s contributes q^s with coeff 1, f-part coeff 1
        c = Fraction(c, B[s])
        assert c.denominator == 1
        c = int(c)
        cs.append(c)
        if c:
            for k in range(s, N):
                W[k] += c * B[k]
        if s < mu:
            B = poly_mul(B, ug, N)
    return mu, W


def mallows_sloane_A(n):
    """Theorem 27 (Rains-Sloane survey; Mallows-Sloane 1973):
    A*_{4mu+4} for n = 24mu, 24mu+8, 24mu+16."""
    mu = n // 24
    r = n % 24
    if r == 0:
        return comb(n, 5) * comb(5 * mu - 2, mu - 1) // comb(4 * mu + 4, 5)
    if r == 8:
        from math import factorial
        return (n * (n - 1) * (n - 2) * (n - 4) * factorial(5 * mu)
                ) // (4 * factorial(mu) * factorial(4 * mu + 4))
    if r == 16:
        from math import factorial
        return (3 * n * (n - 2) * factorial(5 * mu + 2)
                ) // (2 * factorial(mu) * factorial(4 * mu + 4))
    raise ValueError


def fmt(x):
    s = f"{float(x):.6e}" if abs(x) > 10**18 else str(x)
    return s


if __name__ == "__main__":
    tests = [
        # (n, expectation for sign of A_{mu+2})
        (3672, "+"),   # 24*153  : last nonneg in 0 mod 24 class (Zhang)
        (3696, "-"),   # 24*154  : FIRST negative overall (Zhang)
        (3720, "-"),   # 24*155  : MOS 1975 computer check
        (3800, "+"),   # 24*158+8: last nonneg in 8 mod 24 class
        (3824, "-"),   # 24*159+8: first negative in 8 mod 24 class
        (3928, "+"),   # 24*163+16: last nonneg ANYWHERE -> global bound
        (3952, "-"),   # 24*164+16: first negative in 16 mod 24 class
    ]
    for n, expect in tests:
        mu, W = extremal_coeffs(n)
        A1, A2 = W[mu + 1], W[mu + 2]
        ms = mallows_sloane_A(n)
        ok_ms = (ms == A1)
        sign = "+" if A2 >= 0 else "-"
        status = "OK" if sign == expect else "** MISMATCH **"
        print(f"n={n:5d} mu={mu:3d}  A*_{{4mu+4}}=A_{mu+1}={fmt(A1)}  "
              f"(MS formula match: {ok_ms})")
        print(f"            A*_{{4mu+8}}=A_{mu+2}={fmt(A2)}  sign {sign} "
              f"expected {expect}  -> {status}")
        if n == 3720:
            print(f"            MOS claim: A_156 = 1.16e170, A_157 = -5.84e170")
            print(f"            computed : A_156 = {float(A1):.3e}, "
                  f"A_157 = {float(A2):.3e}")
