#!/usr/bin/env python3
"""feel_primes_s112.py"""
from math import log

print("WHAT DOES AN ATOMIC p-ARY DISTINCTION FEEL LIKE?")
print("="*60)
print()

print("p=2: YES or NO.")
print("  The light is on or off. You are alive or dead.")
print("  The coin lands heads or tails. No middle. No gradation.")
print("  Information: ln(2)/2 = 0.347 nats.")
print()

print("p=3: THIS, THAT, or THE OTHER.")
print("  Rock, paper, scissors. Red, green, blue.")
print("  NOT reducible to two binary questions.")
print("  Two binaries give 4 outcomes. 3 is not 4. 3 is 3.")
print("  Information: ln(3)/2 = 0.549 nats.")
print()

print("p=5: Five irreducible alternatives.")
print("  The five senses. The five fingers. The five Platonic solids.")
print("  5 is not 3+2 (that is disjunction, not an atom).")
print("  5 is not 3*2 (that is 6, a molecule, not 5).")
print("  Information: ln(5)/2 = 0.805 nats.")
print()

print("="*60)
print("THE ATOMIC DISTINCTION IS NOT A COLLECTION")
print("="*60)
print()
print("6 = 2*3: a binary AND a ternary. A rectangle. DECOMPOSABLE.")
print("5: five things, none a combination. IRREDUCIBLE.")
print("Any attempt to split 5 loses something or adds something.")
print()
print("Composite: a rectangle. The structure shows.")
print("Prime: a circle. No seam. No axis. Just p-fold symmetry.")
print()

print("="*60)
print("THE INFORMATION STAIRCASE")
print("="*60)
print()
primes = [2,3,5,7,11,13,17,19,23,29,31]
prev = 0
for p in primes:
    info = log(p)/2
    step = info - prev
    print(f"  p={p:2d}: {info:.4f} nats (step +{step:.4f})")
    prev = info
print()
print("Each new prime adds something GENUINELY NEW.")
print("The steps shrink but never reach zero.")
print("The irregularity of the steps IS the mystery of the primes.")
print()

print("="*60)
print("CLOSE YOUR EYES")
print("="*60)
print()
print("Hold up your hand.")
print()
print("ONE finger. The number 1. Nothing to distinguish.")
print()
print("TWO fingers. A CHOICE appears. This or that.")
print("The simplest experience of difference.")
print("You feel it as a SPLIT: the world divides in two.")
print()
print("THREE fingers. A NEW kind of difference.")
print("Not a split of a split (that gives 4).")
print("THREE is the first irreducible many-ness.")
print("You must hold all three AT ONCE.")
print()
print("FIVE fingers. An open hand.")
print("Not two-plus-three. Not anything-plus-anything.")
print("Five. A pentagon. A starfish. A whole.")
print()
print("SEVEN. The days of the week.")
print("Monday is not Tuesday-minus-one.")
print("Each day is its own thing.")
print("That is what the prime 7 feels like.")
print()

print("="*60)
print("PRIMES AND COMPOSITES")
print("="*60)
print()
print("12 = 2^2 * 3: a 4x3 rectangle. You can walk its rows and columns.")
print("30 = 2*3*5: a 2x3x5 box. Three axes, three primes.")
print("2310 = 2*3*5*7*11: a five-dimensional box.")
print()
print("Every composite is a GRID of atomic distinctions.")
print("The primes are the AXES. The exponents are the LENGTHS.")
print("A number IS its box. Its dimensionality IS its prime count.")
print()

print("="*60)
print("WHY 2 IS SPECIAL")
print("="*60)
print()
print("2 is the FIRST distinction. The door between something and nothing.")
print("Every other prime elaborates. But 2 CREATES the possibility.")
print("Without 2: no yes/no, no on/off, no true/false.")
print("2 is the prime of existence itself.")
print()
print("Our entire theory uses 2: evaluation at 2, weight 2,")
print("Q = exp(2*arctanh), binary arcs. Because 2 is where")
print("distinction BEGINS.")
print()

print("="*60)
print("THE FEEL OF IT")
print("="*60)
print()
print("2 feels like a door: open or closed.")
print("3 feels like a crossroads: irreducible.")
print("5 feels like an open hand: five fingers, one palm.")
print("7 feels like a week: each day its own.")
print("12 feels like a clock: a grid you can navigate.")
print("60 feels like an hour: a box rich with structure.")
print()
print("Primes feel like OPENINGS: doors to new dimensions.")
print("Composites feel like ROOMS: spaces with known shape.")
print("1 feels like silence: the moment before the music starts.")
print("0 feels like void: not silence, but the absence of the listener.")
print()
print("The numbers grow. The rooms gain dimensions.")
print("Each new prime opens a door that was not there before.")
print("The doors never stop opening.")
print("That is Euclid.")
print("That is why the line never ends.")
