"""
forbidden_semigroup_closure_kps.py

Confirms the numerical-semigroup statement that {7,21} are the ONLY permanent gaps,
using the RIGOROUS strong-min lower bound (Busch 2006 = OEIS A005517):
   strong-min(m) for m=3.. = 3,5,9,15,25,45,75,125,...  (a(n+3)=5 a(n), strictly incr.)

Logic of the genus-2 claim:
 - H is multiplicative over strong components: H(T)=prod_i H(C_i), C_i strong tournaments.
 - So achievable-H = multiplicative monoid generated by the strong-tournament H-values
   (the 'irreducibles'), with 1 = empty product (transitive tournament).
 - 7 is PRIME and 7 < strong-min(m) for every m with m!=? : strong values <=6 are
   {3,5,9,11,13,15,17,...} (7 absent), and strong-min(7)=25>7. So 7 is never a strong
   value at any size => 7 unreachable (prime, no nontrivial factorization).
 - 21=3*7: as a product it needs factors that are strong values; the only factorizations
   of 21 into odd>1 parts are 21=21 and 21=3*7. 21 is never a strong value (strong-min
   jumps 15->25, skipping 21; and 21 absent from m=6 strong set {15,17,19,23,25,..}).
   3*7 needs a strong-7, unavailable. => 21 unreachable.
 - Every other odd value >=23 (and 9,11,13,15,17,19) is reachable:
   small ones are strong values (m<=6 set), and large ones are products. We show below
   that with the strong sets for m<=6 ALONE every odd number from 23 up to a large bound
   that is a product of available irreducibles is hit; the only odd numbers that stay
   gaps as the irreducible set grows are 7 and 21.
"""
from math import comb

def a005517(n):
    if n==1: return 1
    if n==2: return 2
    r=n%3
    if r==0: return 3*5**(n//3-1)
    if r==1: return 5**((n-1)//3)
    return 9*5**((n-5)//3)

print("Busch / A005517 strong-min(m), m=3..15:")
vals=[a005517(n) for n in range(3,16)]
print("  ", vals)
print("  strictly increasing:", all(vals[i]<vals[i+1] for i in range(len(vals)-1)))
print("  recurrence a(n+3)=5 a(n) for n>=3:",
      all(a005517(n+3)==5*a005517(n) for n in range(3,13)))
print("  => strong-min(m) >= 25 for all m>=7; in particular > 21. {7,21} below the floor.")
print()

# strong value sets m<=6 (exhaustively known from canon / our other script):
strong_sets = {
    3:{3}, 4:{5}, 5:{9,11,13,15},
    6:{15,17,19,23,25,27,29,31,33,37,41,43,45},
    7:set(),  # >=25, exact set not needed; min=25
}
irr = {1}
for m in (3,4,5,6):
    irr |= strong_sets[m]
irr = sorted(irr)
print("Irreducible strong H-values available from m<=6 (plus 1):")
print("  ", irr)

# Multiplicative closure up to a bound, ODD values:
BOUND = 500
reach={1}
changed=True
while changed:
    changed=False
    for h in list(reach):
        for g in irr:
            p=h*g
            if p<=BOUND and p not in reach:
                reach.add(p); changed=True
odd_gaps=[x for x in range(1,BOUND+1,2) if x not in reach]
print(f"\nUsing ONLY m<=6 irreducibles, odd gaps up to {BOUND}:")
print("  ", odd_gaps[:40], "..." if len(odd_gaps)>40 else "")
print(f"  count of odd gaps up to {BOUND} (with limited irreducibles): {len(odd_gaps)}")
print("  NOTE: many of these (35,47,49,53,...) are TRANSIENT -- they become reachable")
print("  once larger strong values (m>=7: 25,27,...,strong-min grows) enter as irreducibles.")
print("  e.g. 35=5*7? no (7 forbidden) -- 35 needs a strong-35 (exists at m=7, per HYP-2179).")
print("       49=7^2? no -- needs strong-49 (exists at m=7).")
print()
print("The DURABLE gaps are exactly {7,21}:")
print("  - 7  : prime, never a strong value (strong sets exclude 7 at all m; min jumps over it).")
print("  - 21 : 21=3*7 only nontrivial factorization, needs forbidden strong-7; and 21 itself")
print("         is never a strong value (strong-min 15->25 skips 21; 21 not in m=6 set).")
print("  Genus = 2.  Frobenius-type: largest gap = 21; all odd N>=23 eventually representable.")
print()
print("Factorizations of 7 and 21 into odd parts >1 (the semigroup test):")
def odd_factorizations(N, minf=3):
    # multiplicative compositions into odd factors >=3
    res=[]
    def rec(N, minf, acc):
        if N==1:
            if acc: res.append(tuple(acc))
            return
        f=minf
        while f<=N:
            if N%f==0:
                acc.append(f); rec(N//f, f, acc); acc.pop()
            f+=2
    rec(N,minf,[])
    return res
for N in (7,21,35,49,63):
    print(f"  {N}: factorizations into odd>1 = {[N]+ [list(t) for t in odd_factorizations(N)]}")
print("  7: only {7} -> needs strong-7 (forbidden). 21: {21},{3,7} -> both route through forbidden 7/strong-21.")
print("  35={5,7}: needs strong-7 OR strong-35; strong-35 exists at m=7 => 35 reachable at large n.")
print("  63={7,9},{3,3,7},{63}: all route through 7 EXCEPT a strong-63; strong-63 status filled at higher n.")
