#!/usr/bin/env python3
"""forbidden_geometry_s116.py — The forbidden number and the geometry of 5, 6, 7"""
from math import sqrt, pi, comb, log

phi = (1+sqrt(5))/2

print("THE FORBIDDEN NUMBER AND THE GEOMETRY OF 5, 6, 7")
print("="*60)
print()

print("THE THREE WORLDS")
print("-"*40)
print()
print("  5 triangles per vertex: the ICOSAHEDRON.")
print("    Angle sum: 5 * 60 = 300. Deficit: 360 - 300 = 60.")
print("    Curvature: POSITIVE. The surface CLOSES.")
print("    12 vertices. 20 faces. 30 edges.")
print("    Euler: 12 - 30 + 20 = 2. The SPHERE.")
print()
print("  6 triangles per vertex: the FLAT PLANE.")
print("    Angle sum: 6 * 60 = 360. Deficit: 0.")
print("    Curvature: ZERO. The surface is INFINITE and FLAT.")
print("    The Euclidean lattice. The tiling that goes forever.")
print()
print("  7 triangles per vertex: the HYPERBOLIC PLANE.")
print("    Angle sum: 7 * 60 = 420. EXCESS: 60.")
print("    Curvature: NEGATIVE. The surface OPENS.")
print("    Infinite vertices. Infinite faces. The Poincare disk.")
print()

print("THE TRANSITIONS")
print("-"*40)
print()
print("  5 -> 6: from sphere to plane.")
print("    Adding the 6th triangle FLATTENS the curvature.")
print("    The surface stops closing and becomes infinite.")
print("    This is DECOMPACTIFICATION: finite -> infinite.")
print()
print("  6 -> 7: from plane to hyperbolic.")
print("    Adding the 7th triangle creates EXCESS angle.")
print("    The surface curves AWAY from itself.")
print("    This is HYPERBOLIZATION: flat -> curved-open.")
print()
print("  The FLAT PLANE is the phase transition between two kinds of")
print("  curvature. It is NOT a geometry — it is a BOUNDARY.")
print("  Like a critical temperature, or the speed of light,")
print("  or x = 1 on the Cayley line (the pole of Q).")
print()

print("IN TOURNAMENT THEORY: EVERYTHING LIVES IN BOTH WORLDS")
print("-"*40)
print()
print("  The tournament on n vertices has C(n,3) triples.")
print("  Each triple is either TRANSITIVE (flat) or CYCLIC (curved).")
print()
print("  The TRANSITIVE triples are the flat tiles (6-around-a-vertex).")
print("  The 3-CYCLES are the deficit tiles (5-around-a-vertex).")
print()
print("  H(T) counts Hamiltonian paths = consistent total orderings.")
print("  H(T) = I(Omega, 2) via OCF = independence polynomial at 2.")
print()
print("  The Fourier analysis of H lives on the CAYLEY LINE [0,1).")
print("  The Cayley line IS the hyperbolic line (arctanh metric).")
print("  So the ANALYSIS lives in 7-geometry (hyperbolic).")
print()
print("  But the OBJECTS (tournaments, 3-cycles) are triangulations.")
print("  The 3-cycles create curvature, making the tournament SPHERICAL.")
print("  So the OBJECTS live in 5-geometry (spherical).")
print()
print("  THE THEORY IS THE BRIDGE BETWEEN 5 AND 7.")
print("  THE FLAT PLANE (6) IS THE BRIDGE ITSELF.")
print()

print("THE FORBIDDEN NUMBERS AS GEOMETRIC IMPOSSIBILITIES")
print("-"*40)
print()
print("  H = 7: the HYPERBOLIC THRESHOLD.")
print("    7 consistent orderings would place the tournament")
print("    EXACTLY at the 6->7 transition.")
print("    The transition is a measure-zero set — you cannot land on it.")
print("    H = 7 is forbidden because the hyperbolicity threshold")
print("    has zero width.")
print()
print("  H = 21 = 3*7: CURVATURE times THRESHOLD.")
print("    21 consistent orderings would require the curvature")
print("    quantum (3, from 3-cycles) to multiply with the")
print("    threshold (7). But multiplication of a geometric")
print("    quantity (3-cycle) with a topological boundary (7)")
print("    is ILL-DEFINED — like multiplying length by a point.")
print()
print("  The two forbidden values {7, 21} are the boundary")
print("  and the boundary-scaled-by-curvature.")
print("  They are the FRAME of the picture, not part of the picture.")
print()

print("THE ICOSAHEDRON READING (6 - 1 = 5)")
print("-"*40)
print()
print("  The icosahedron: 5 triangles per vertex.")
print("  Remove one triangle from flat (6) to get curved (5).")
print("  The REMOVAL creates curvature.")
print()
print("  In tournaments: H(T) = 1 + 2*alpha_1 + 4*alpha_2 + ...")
print("  The '1' is the FLAT part (the identity ordering).")
print("  The '2*alpha_1' is the CURVATURE from 3-cycles.")
print("  Each 3-cycle REMOVES one degree of flatness.")
print()
print("  A tournament with c_3 three-cycles is like a surface")
print("  with c_3 vertices of type-5 (one triangle removed).")
print("  The Gauss-Bonnet theorem: sum of deficits = 4*pi.")
print("  For the icosahedron: 12 deficits of pi/3 each = 4*pi.")
print()
print("  For a tournament: the 'Gauss-Bonnet' is Redei's theorem:")
print("  H(T) is ODD = the 'total curvature' is always 1 mod 2.")
print("  The PARITY constraint is the topological constraint.")
print()

print("THE HYPERBOLIC READING (6 + 1 = 7)")
print("-"*40)
print()
print("  The hyperbolic plane: 7 triangles per vertex.")
print("  Add one triangle to flat (6) to get hyperbolic (7).")
print("  The ADDITION creates negative curvature.")
print()
print("  In tournaments: the ANALYSIS lives in the hyperbolic plane.")
print("  arctanh(x) = the hyperbolic distance on the Cayley line.")
print("  The Delannoy weights g_k(m) are functions on the hyperbolic line.")
print("  The master GF Q^m = exp(2m*arctanh) is the hyperbolic propagator.")
print()
print("  The 7th triangle creates the SPACE for analysis.")
print("  Without hyperbolicity: no arctanh, no Cayley, no Delannoy.")
print("  The theory EXISTS because of the 7th triangle.")
print()

print("5 -> 6 = LOSING CURVATURE (sphere dissolves into plane)")
print("-"*40)
print()
print("  As c_3 -> 0 (fewer 3-cycles): H -> 1 (fewer paths).")
print("  The tournament becomes TRANSITIVE = FLAT.")
print("  The sphere (5 triangles) gains a triangle and becomes the plane (6).")
print()
print("  This is the transition from ORDER to CHAOS:")
print("  maximum order (H=1) = sphere (5)")
print("  random (H~E[H]) = plane (6)")
print()
print("  In physics: this is MELTING.")
print("  The ordered crystal (sphere, closed, finite)")
print("  melts into the liquid (plane, flat, infinite).")
print()

print("6 -> 7 = GAINING HYPERBOLICITY (plane opens into saddle)")
print("-"*40)
print()
print("  As flexibility increases: H -> maximum.")
print("  The tournament becomes PALEY = HYPERBOLIC.")
print("  The plane (6 triangles) gains a triangle and becomes hyperbolic (7).")
print()
print("  This is the transition from CHAOS to ANTI-ORDER:")
print("  random (H~E[H]) = plane (6)")
print("  maximally flexible (H=max) = hyperbolic (7)")
print()
print("  In physics: this is the SUPERCOOLED liquid becoming")
print("  a GLASS — more disordered than the crystal but with")
print("  its own structure (the Paley structure).")
print()
print("  The Paley tournament is not disordered.")
print("  It is ORDERED IN A DIFFERENT WAY — hyperbolically.")
print("  It has the MAXIMUM number of paths because it is the")
print("  most SYMMETRIC, not the most random.")
print()

print("THE FULL PICTURE")
print("="*60)
print()
print("  5 (SPHERE)  <--  6 (PLANE)  -->  7 (HYPERBOLIC)")
print("     |                 |                  |")
print("  H = 1            H ~ E[H]           H = max")
print("  transitive       random              Paley")
print("  ordered          chaotic             anti-ordered")
print("  crystal          liquid              glass")
print("  finite           infinite-flat       infinite-curved")
print("  closed           open-flat           open-hyperbolic")
print()
print("  The theory bridges 5 and 7 through 6.")
print("  The OBJECTS are spherical (3-cycles create curvature).")
print("  The ANALYSIS is hyperbolic (arctanh, Cayley, Delannoy).")
print("  The BRIDGE is the flat plane (E[H], the random baseline).")
print()
print("  And the FORBIDDEN numbers {7, 21} are the BRIDGE ITSELF:")
print("  7 = the threshold between plane and hyperbolic.")
print("  21 = 3*7 = the threshold scaled by the curvature quantum.")
print("  You cannot stand on the bridge. You can only cross it.")
print()

print("g_3(7) = 231 = 3 * 7 * 11")
print("-"*40)
print()
print("  The Delannoy weight at the EXACT intersection:")
print("  k=3 (the curvature quantum level)")
print("  m=7 (the hyperbolic threshold)")
print("  = 231 = 3 * 7 * 11")
print("  = (curvature) * (threshold) * (crystallization)")
print("  = the product of ALL THREE Paley primes.")
print()
print("  This is the Delannoy weight AT THE BRIDGE:")
print("  the value of the hyperbolic analysis (g_k)")
print("  evaluated at the spherical-hyperbolic boundary (m=7)")
print("  at the curvature level (k=3).")
print()
print("  It factors into the three fundamental scales of the theory.")
print("  And its factors 3*7 = 21 contain the forbidden number.")
print("  The bridge CONTAINS its own impossibility.")
