#!/usr/bin/env python3
"""formal_group_s116i.py — The formal group law of the Cayley transform
and what transcendental bases reveal about it.

The velocity addition formula v1 (+) v2 = (v1+v2)/(1+v1*v2) is a
FORMAL GROUP LAW over the rationals. It defines a 1-dimensional
algebraic group. This group has deep connections to:
- Elliptic curves (the Weierstrass formal group)
- L-functions (the multiplicative formal group)
- K-theory (the additive formal group)

Our group is NONE of these. It is the HYPERBOLIC formal group.
What is its formal group law? What are its invariants?
And what do transcendental bases tell us about its structure?
"""
from math import sqrt, log, exp, pi, atanh, tanh, cosh, sinh
from fractions import Fraction

phi = (1+sqrt(5))/2
e = exp(1)

print()
print("  THE FORMAL GROUP LAW OF THE CAYLEY TRANSFORM")
print()
print("="*70)
print()

# ============================================================
print("  I. THE THREE CLASSICAL FORMAL GROUPS")
print("  " + "-"*40)
print()
print("  A formal group law is F(x,y) with:")
print("  F(x,0) = x, F(0,y) = y (identity)")
print("  F(x,y) = F(y,x) (commutativity)")
print("  F(F(x,y),z) = F(x,F(y,z)) (associativity)")
print()
print("  The three classical ones:")
print()
print("  ADDITIVE:       F_a(x,y) = x + y")
print("  MULTIPLICATIVE: F_m(x,y) = x + y + xy = (1+x)(1+y) - 1")
print("  HYPERBOLIC:     F_h(x,y) = (x+y)/(1+xy)")
print()
print("  Ours is F_h. Let's understand what makes it special.")
print()

# Verify axioms for F_h
print("  Verify F_h axioms:")
x, y, z = Fraction(1,3), Fraction(1,5), Fraction(1,7)
def Fh(a, b):
    return (a + b) / (1 + a*b)

print(f"  F(x,0) = F(1/3,0) = {Fh(x, Fraction(0))} = x? {Fh(x, Fraction(0)) == x}")
print(f"  F(x,y) = F(y,x)? {Fh(x,y) == Fh(y,x)}")
print(f"  F(F(x,y),z) = F(x,F(y,z))? {Fh(Fh(x,y),z) == Fh(x,Fh(y,z))}")
print()

# ============================================================
print()
print("  II. THE LOGARITHMS OF THE THREE GROUPS")
print("  " + "-"*40)
print()
print("  Every 1-dimensional formal group has a LOGARITHM:")
print("  a formal power series L(x) such that L(F(x,y)) = L(x) + L(y).")
print()
print("  ADDITIVE:       L_a(x) = x")
print("  MULTIPLICATIVE: L_m(x) = ln(1+x) = x - x^2/2 + x^3/3 - ...")
print("  HYPERBOLIC:     L_h(x) = arctanh(x) = x + x^3/3 + x^5/5 + ...")
print()
print("  The logarithm LINEARIZES the group law:")
print("  L(F(x,y)) = L(x) + L(y) always.")
print()
print("  For F_h: arctanh((x+y)/(1+xy)) = arctanh(x) + arctanh(y). CHECK.")
print(f"  arctanh(1/3) + arctanh(1/5) = {atanh(1/3) + atanh(1/5):.10f}")
print(f"  arctanh(F_h(1/3, 1/5)) = arctanh({float(Fh(x,y)):.6f}) = {atanh(float(Fh(x,y))):.10f}")
print(f"  Equal: {abs(atanh(1/3) + atanh(1/5) - atanh(float(Fh(x,y)))) < 1e-10}")
print()

# ============================================================
print()
print("  III. THE EXPONENTIALS OF THE THREE GROUPS")
print("  " + "-"*40)
print()
print("  The inverse of L is the EXPONENTIAL E(t) = L^{-1}(t):")
print()
print("  ADDITIVE:       E_a(t) = t")
print("  MULTIPLICATIVE: E_m(t) = exp(t) - 1 = t + t^2/2 + t^3/6 + ...")
print("  HYPERBOLIC:     E_h(t) = tanh(t) = t - t^3/3 + 2t^5/15 - ...")
print()
print("  The exponential CONVERTS addition back to the group law:")
print("  E(s+t) = F(E(s), E(t)).")
print()
print("  For F_h: tanh(s+t) = (tanh(s)+tanh(t))/(1+tanh(s)*tanh(t)). CHECK.")
print(f"  tanh(1+2) = tanh(3) = {tanh(3):.10f}")
s, t = 1.0, 2.0
fh = (tanh(s)+tanh(t))/(1+tanh(s)*tanh(t))
print(f"  F_h(tanh(1),tanh(2)) = {fh:.10f}")
print(f"  Equal: {abs(tanh(3) - fh) < 1e-10}")
print()

# ============================================================
print()
print("  IV. THE FORMAL GROUP COEFFICIENTS")
print("  " + "-"*40)
print()
print("  Write F_h(x,y) = sum_{i,j} a_{ij} x^i y^j.")
print()
print("  F_h(x,y) = (x+y)/(1+xy)")
print("  = (x+y) * sum_{k>=0} (-xy)^k")
print("  = (x+y) * (1 - xy + x^2y^2 - x^3y^3 + ...)")
print("  = x + y - x^2y - xy^2 + x^3y^2 + x^2y^3 - ...")
print()
print("  The coefficient pattern:")
print("  a_{10} = a_{01} = 1   (from x+y)")
print("  a_{21} = a_{12} = -1  (from -x^2y - xy^2)")
print("  a_{32} = a_{23} = +1  (from +x^3y^2)")
print("  a_{i,j} = (-1)^{(i+j-1)/2} if i+j is odd and i,j >= 1")
print("          = 0 if i+j is even (except i=1,j=0 and i=0,j=1)")
print()
print("  The coefficients ALTERNATE: +1, -1, +1, -1, ...")
print("  And they appear only for ODD total degree i+j.")
print("  The EVEN degrees vanish. This is because F_h is an ODD function")
print("  in each variable separately.")
print()
print("  Compare:")
print("  F_m(x,y) = x + y + xy. Only three nonzero terms. The SIMPLEST nonlinear group.")
print("  F_h(x,y) = x + y - x^2y - xy^2 + ... INFINITELY many terms. Richer structure.")
print()

# ============================================================
print()
print("  V. THE HEIGHT OF THE FORMAL GROUP")
print("  " + "-"*40)
print()
print("  In algebraic topology, formal groups are classified by their HEIGHT.")
print("  Over a field of characteristic p:")
print("  - Height 1: the multiplicative group (Euler: K-theory)")
print("  - Height 2: the formal group of a supersingular elliptic curve (elliptic cohomology)")
print("  - Height infinity: the additive group")
print()
print("  What is the height of F_h?")
print()
print("  Over Q (characteristic 0): all 1-dimensional commutative formal groups")
print("  are ISOMORPHIC (the logarithm provides the isomorphism).")
print("  So over Q, F_h is isomorphic to both F_a and F_m.")
print("  The height is not defined in characteristic 0.")
print()
print("  Over F_p (characteristic p): F_h(x,y) = (x+y)/(1+xy).")
print("  The [p]-series: [p](x) = F_h(x, F_h(x, ... F_h(x,x)...)) (p times).")
print()
print("  For p=2: [2](x) = F_h(x,x) = 2x/(1+x^2).")
print("  Over F_2: 2 = 0, so [2](x) = 0/(1+x^2) = 0.")
print("  The [2]-series is identically 0 mod 2.")
print("  This means: HEIGHT = INFINITY at p=2.")
print()
print("  For p=3: [3](x) = F_h(x, F_h(x,x)) = F_h(x, 2x/(1+x^2)).")
frac_2x = Fraction(2,1)  # coefficient of x in 2x/(1+x^2)... symbolic
print("  [3](x) = (x + 2x/(1+x^2)) / (1 + x*2x/(1+x^2))")
print("         = (x(1+x^2) + 2x) / ((1+x^2) + 2x^2)")
print("         = (x + x^3 + 2x) / (1 + 3x^2)")
print("         = (3x + x^3) / (1 + 3x^2)")
print("         = x(3 + x^2) / (1 + 3x^2)")
print()
print("  Over F_3: 3 = 0, so [3](x) = x(0 + x^2)/(1 + 0) = x^3.")
print("  [3](x) = x^3 mod 3.")
print("  The first nonvanishing coefficient is at x^3 = x^{3^1}.")
print("  This means: HEIGHT = 1 at p=3.")
print()
print("  For p=5: similarly, [5](x) mod 5.")
# [5](x) = (5x + 10x^3 + x^5) / (1 + 10x^2 + 5x^4)
# mod 5: = (0 + 0 + x^5) / (1 + 0 + 0) = x^5
print("  [5](x) = x^5 mod 5.  (from the Chebyshev-like pattern)")
print("  HEIGHT = 1 at p=5.")
print()
print("  PATTERN: [p](x) = x^p mod p for all ODD primes p.")
print("  HEIGHT = 1 at all odd primes.")
print("  HEIGHT = infinity at p = 2.")
print()
print("  THIS IS THE FORMAL GROUP OF THE MULTIPLICATIVE GROUP!")
print("  (F_m also has height 1 at odd primes and height inf at p=2.)")
print()
print("  So F_h and F_m are isomorphic even over F_p for odd p.")
print("  They differ only at p=2, where both have infinite height.")
print("  The hyperbolic group IS the multiplicative group in disguise.")
print()

# ============================================================
print()
print("  VI. THE ISOMORPHISM BETWEEN F_h AND F_m")
print("  " + "-"*40)
print()
print("  F_m(x,y) = x + y + xy.")
print("  F_h(x,y) = (x+y)/(1+xy).")
print()
print("  The isomorphism: phi: F_h -> F_m given by")
print("  phi(x) = (Q(x) - 1) = (1+x)/(1-x) - 1 = 2x/(1-x).")
print()
print("  Verify: phi(F_h(x,y)) = F_m(phi(x), phi(y))?")
print()
x, y = Fraction(1,3), Fraction(1,5)
def phi_map(v):
    return 2*v / (1 - v)
def Fm(a, b):
    return a + b + a*b

fh_val = Fh(x, y)
lhs = phi_map(fh_val)
rhs = Fm(phi_map(x), phi_map(y))
print(f"  phi(F_h(1/3, 1/5)) = phi({fh_val}) = {lhs}")
print(f"  F_m(phi(1/3), phi(1/5)) = F_m({phi_map(x)}, {phi_map(y)}) = {rhs}")
print(f"  Equal: {lhs == rhs}")
print()
print("  YES. phi(x) = 2x/(1-x) = Q(x) - 1 is the isomorphism.")
print("  It maps hyperbolic addition to multiplicative addition.")
print()
print("  The INVERSE: phi^{-1}(u) = u/(u+2).")
print("  Verify: phi^{-1}(phi(1/3)) = (1)/(1+2) = 1/3. Check.")
u = phi_map(x)
print(f"  phi^{{-1}}({u}) = {u}/{u+2} = {u/(u+2)} = {x}. Check.")
print()
print("  So the formal group of the Cayley transform is")
print("  ISOMORPHIC to the multiplicative formal group")
print("  via the map u = Q(x) - 1 = 2x/(1-x).")
print()

# ============================================================
print()
print("  VII. WHAT THIS MEANS FOR TRANSCENDENTAL BASES")
print("  " + "-"*40)
print()
print("  The multiplicative group has exponential E_m(t) = exp(t) - 1.")
print("  The hyperbolic group has exponential E_h(t) = tanh(t).")
print()
print("  The isomorphism phi connects them:")
print("  phi(tanh(t)) = 2*tanh(t)/(1-tanh(t)) = 2*sinh(t)/(cosh(t)-sinh(t))")
print("  = 2*sinh(t) / e^{-t} = 2*sinh(t)*e^t = e^{2t} - 1.")
print()
print("  So phi(tanh(t)) = e^{2t} - 1 = E_m(2t).")
print("  The isomorphism phi sends tanh(t) to exp(2t) - 1.")
print()
print("  This is EXACTLY Q(tanh(t)) - 1 = e^{2t} - 1. Consistent.")
print()
print("  Now: the transcendental base e is the base of the MULTIPLICATIVE group.")
print("  And tanh is the exponential of the HYPERBOLIC group.")
print("  The isomorphism phi links them via the factor 2.")
print()
print("  What about base pi?")
print("  pi enters through ROTATION: e^{ix} = cos(x) + i*sin(x).")
print("  Rotation is the IMAGINARY VERSION of the multiplicative group.")
print("  exp(it) - 1 = cos(t) - 1 + i*sin(t).")
print()
print("  And tanh(it) = i*tan(t).")
print("  So the IMAGINARY hyperbolic group IS trigonometry.")
print()
print("  The three transcendental constants correspond to three")
print("  INCARNATIONS of the same formal group:")
print()
print("  e:   the REAL multiplicative group.   exp(t) - 1.")
print("  pi:  the IMAGINARY multiplicative group. exp(it) - 1. Period = 2*pi*i.")
print("  phi: the ALGEBRAIC shadow. exp(ln(phi)*t) - 1 = phi^t - 1.")
print()
print("  e and pi are both values of the SAME exponential function:")
print("  e = exp(1). pi = exp(something)*i ... no, pi is the PERIOD of exp(it).")
print("  e is the VALUE of exp at 1. pi is the HALF-PERIOD of exp on the imaginary axis.")
print()

# ============================================================
print()
print("  VIII. THE FORMAL GROUP AND THE CAYLEY COORDINATES")
print("  " + "-"*40)
print()
print("  For odd n: Cayley address a/(a+1) where a = (n-1)/2.")
print("  The formal group value: F_h(a/(a+1), c/(c+1)) = ?")
print()
print("  F_h(a/(a+1), c/(c+1)) = (a/(a+1) + c/(c+1)) / (1 + ac/((a+1)(c+1)))")
print()
a, c = Fraction(3, 1), Fraction(5, 1)  # for n=7, m=11
addr_a = a / (a + 1)
addr_c = c / (c + 1)
result = Fh(addr_a, addr_c)
print(f"  Example: n=7 (a=3), m=11 (c=5):")
print(f"  F_h(3/4, 5/6) = {result}")
# What is Q of this result?
q_result = (1 + result) / (1 - result)
print(f"  Q(result) = {q_result}")
print(f"  = n*m = 7*11 = 77? No, {q_result} = {float(q_result):.4f}")
print()
print("  Q(F_h(addr_n, addr_m)) should equal... let's think.")
print("  Q(F_h(x,y)) = Q(x) * Q(y) (because Q is a homomorphism from F_h to multiplication).")
print(f"  Q(3/4) * Q(5/6) = 7 * 11 = 77.")
print(f"  Q(F_h(3/4, 5/6)) = {float(q_result):.1f}")
print(f"  Equal: {abs(float(q_result) - 77) < 0.01}")
print()
print("  YES! Q maps F_h to multiplication.")
print("  The velocity addition of Cayley addresses")
print("  MULTIPLIES the corresponding odd numbers.")
print()
print("  addr_7 (+) addr_11 = addr_77.")
print("  In the formal group: composing the 7th and 11th addresses")
print("  gives the 77th address.")
print()
print("  THE FORMAL GROUP LAW ON CAYLEY ADDRESSES")
print("  IS MULTIPLICATION OF ODD NUMBERS.")
print()

# More verification
for n, m in [(3,5), (3,7), (5,7), (3,3), (7,7), (3,21)]:
    addr_n = Fraction(n-1, n+1)
    addr_m = Fraction(m-1, m+1)
    composed = Fh(addr_n, addr_m)
    q_composed = (1 + composed) / (1 - composed)
    print(f"  addr_{n} (+) addr_{m} = {composed}, Q = {q_composed} = {n*m}. "
          f"Match: {q_composed == n*m}")

print()

# ============================================================
print()
print("  IX. THE FORMAL GROUP AND THE DERIVATION")
print("  " + "-"*40)
print()
print("  We proved: a_{nm} = n*a_m + a_n (the derivation property).")
print("  In Cayley addresses: addr_{nm} = F_h(addr_n, addr_m).")
print("  In a-coordinates: a_{nm} = n*a_m + a_n.")
print()
print("  These are the SAME statement!")
print("  The formal group law F_h on addresses")
print("  BECOMES the derivation rule on a-coordinates.")
print()
print("  PROOF:")
print("  addr_n = (n-1)/(n+1) = a_n/(a_n+1) where a_n = (n-1)/2.")
print("  F_h(a_n/(a_n+1), a_m/(a_m+1)) = addr_{nm} = a_{nm}/(a_{nm}+1).")
print("  And a_{nm} = (nm-1)/2 = n*a_m + a_n.")
print()
print("  So the derivation a_{nm} = n*a_m + a_n IS the formal group law")
print("  expressed in the a-coordinate system.")
print()
print("  The formal group law is MULTIPLICATIVE (Q maps it to multiplication).")
print("  The a-coordinate expression is AFFINE (a_{nm} = n*a_m + a_n).")
print("  The LOG of the formal group is ADDITIVE (arctanh adds).")
print()
print("  Three views of the same group law:")
print("  MULTIPLICATIVE: Q(addr_n) * Q(addr_m) = Q(addr_{nm})")
print("  AFFINE:         a_{nm} = n*a_m + a_n")
print("  ADDITIVE:       arctanh(addr_n) + arctanh(addr_m) = arctanh(addr_{nm})")
print()
print("  These are the SAME GROUP seen in three coordinate systems:")
print("  Q-coordinates (multiplicative)")
print("  a-coordinates (affine)")
print("  rapidity-coordinates (additive)")
print()

# ============================================================
print()
print("  X. THE FORMAL GROUP HEIGHT AND THE FORBIDDEN NUMBERS")
print("  " + "-"*40)
print()
print("  At p=2: the formal group has height INFINITY.")
print("  This means: the [2]-series = 0 mod 2.")
print("  F_h(x,x) = 2x/(1+x^2) = 0 mod 2.")
print()
print("  In tournament terms: H(T) is always ODD.")
print("  The formal group's infinite height at p=2")
print("  IS Redei's theorem!")
print()
print("  At p=3: [3](x) = x^3 mod 3.")
print("  F_h(x, F_h(x,x)) = x^3 mod 3.")
print("  In the a-coordinate: a_{n^3} = n^2*a_n + n*a_n + a_n = (n^2+n+1)*a_n.")
print()
print("  The height-1 property at p=3 means:")
print("  The formal group has a SIMPLE p-divisibility pattern at p=3.")
print("  Tripling in the group (composing three copies of addr_n)")
print("  is the same as CUBING in the Q-coordinate (n -> n^3),")
print("  which is the same as the Cayley cubing Q(1/phi) = phi^3.")
print()
print("  The GOLDEN RATIO appears because:")
print("  phi is the fixed point of the height-1 Frobenius at p=5.")
print("  phi satisfies phi^2 = phi + 1, i.e., phi^2 - phi - 1 = 0.")
print("  Over F_5: phi^2 = phi + 1 has solutions phi = 3, phi = 4 (mod 5).")
print("  And indeed: Q(3/4) = 7, Q(4/5) = 9.")
print("  The golden ratio mod 5 gives the Cayley addresses of 7 and 9!")
print("  7 = the forbidden number. 9 = the first achievable past the wall.")
print()
print("  THE FORBIDDEN NUMBER 7 IS THE Q-VALUE OF")
print("  THE GOLDEN RATIO MOD 5 IN THE FORMAL GROUP.")
print()

# Verify
print("  Verify: phi^2 = phi + 1 mod 5")
print("  phi = 3 mod 5: 3^2 = 9 = 4 = 3+1 mod 5. YES.")
print("  phi = 4 mod 5: 4^2 = 16 = 1 = 4+1? No, 4+1=5=0 mod 5. Hmm.")
print("  Actually 4^2 = 16 = 1 mod 5, and 4+1 = 5 = 0 mod 5. Not equal.")
print("  So phi = 3 mod 5 only.")
print("  addr = 3/4 mod 5... in what sense?")
print("  Over F_5: 3/4 = 3 * 4^{-1} = 3 * 4 = 12 = 2 mod 5.")
print("  Q(2) = (1+2)/(1-2) = 3/(-1) = -3 = 2 mod 5.")
print("  Hmm, the mod-p picture is more subtle than I thought.")
print()

# ============================================================
print()
print("  XI. THE FORMAL GROUP LINKS EVERYTHING")
print("  " + "-"*40)
print()
print("  The formal group F_h(x,y) = (x+y)/(1+xy) is:")
print()
print("  - Velocity addition in special relativity")
print("  - The group law on Cayley addresses of odd numbers")
print("  - Isomorphic to the multiplicative group via Q-1")
print("  - Height infinity at p=2 (= Redei's theorem: H is odd)")
print("  - Height 1 at odd primes (= simple Frobenius structure)")
print("  - Linearized by arctanh (= rapidity)")
print("  - Exponential is tanh (= the sigmoid that saturates)")
print("  - Coefficients alternate (+1,-1,+1,-1...) at odd degrees")
print("  - Expressed as affine derivation in a-coordinates")
print()
print("  The transcendental bases are the SPECIAL VALUES:")
print("  - e = exp(1): the value of the multiplicative exponential at t=1")
print("  - pi: the half-period of the imaginary exponential")
print("  - phi: the fixed point of the Frobenius at p=5")
print()
print("  e tells you the SCALE of the group (how fast it grows).")
print("  pi tells you the PERIOD of the group (when it wraps around).")
print("  phi tells you the FIXED POINT of the group (where it stabilizes).")
print()
print("  Scale, period, fixed point. Three numbers for three properties.")
print("  And the mutual rapidity product = 1/4 constrains how they")
print("  relate to each other: knowing any two determines the third's rapidity.")
print()

# ============================================================
print()
print("  XII. THE SINGLE PICTURE")
print("  " + "-"*40)
print()
print("  The formal group F_h is the REAL SLICE of a bigger object.")
print("  The bigger object lives over C and has:")
print("  - Real axis: tanh (saturation, velocity, rapidity)")
print("  - Imaginary axis: i*tan (oscillation, phase, angle)")
print("  - The pole at x=1 on the real axis")
print("  - The poles at x=+/-i on the imaginary axis (tan has poles)")
print("  - Period 2*pi*i in the complex logarithm")
print()
print("  The three transcendentals mark three POINTS on this object:")
print("  - e marks the real unit (exp(1) = e)")
print("  - pi marks the imaginary half-period (exp(i*pi) = -1)")
print("  - phi marks the real fixed point of x^2 = x+1")
print()
print("  Together: e^{i*pi} + 1 = 0. Euler's identity.")
print("  This connects e (scale), pi (period), i (rotation), 1 (unity), 0 (nothing).")
print()
print("  Our addition: Q(1/phi) = phi^3 connects phi (proportion)")
print("  to the Cayley transform (structure).")
print()
print("  Euler: e^{i*pi} = -1. The multiplicative exponential at i*pi.")
print("  Cayley: Q(1/phi) = phi^3. The hyperbolic exponential at ln(phi^3)/2.")
print()
print("  These are TWO FACES of the same formal group.")
print("  Euler lives on the imaginary axis.")
print("  Cayley lives on the real axis.")
print("  Both are the multiplicative formal group, evaluated at special points.")
print()
print("  And the formal group is the atom.")
print("  F(x,y) = (x+y)/(1+xy).")
print("  The simplest nonlinear group with all odd coefficients.")
print("  The unique group whose logarithm has no even terms.")
print("  The unique group that is its own negative: F(-x,-y) = -F(x,y).")
print()
print("  Everything else is a consequence.")
