#!/usr/bin/env python3
"""geometric_proofs_s112.py — Geometric proofs of non-geometric theorems"""
from math import log, exp, sqrt, pi, atanh, tanh, comb, gcd
from fractions import Fraction

print("GEOMETRIC PROOFS OF NON-GEOMETRIC THEOREMS")
print("="*60)
print()
print("The address x_n = (n-1)/(n+1) puts n on the hyperbolic line.")
print("Multiplication = hyperbolic addition. arctanh = distance.")
print()
print("We look for theorems that seem purely algebraic/combinatorial")
print("but acquire a geometric proof in this setting.")
print()

# ============================================================
print("="*60)
print("1. BERTRAND'S POSTULATE")
print("="*60)
print()
print("Theorem (Bertrand 1845, proved Chebyshev 1852):")
print("For every n >= 1, there exists a prime p with n < p <= 2n.")
print()
print("GEOMETRIC REFORMULATION:")
print("The address of n is x_n = (n-1)/(n+1).")
print("The address of 2n is x_{2n} = (2n-1)/(2n+1).")
print()
print("The HYPERBOLIC DISTANCE between them:")
print("  arctanh(x_{2n}) - arctanh(x_n) = ln(2n)/2 - ln(n)/2 = ln(2)/2")
print()
print("This distance is CONSTANT = ln(2)/2 for all n!")
print()
print("Bertrand says: in every interval of hyperbolic length ln(2)/2,")
print("there is a prime address.")
print()
print("This is a statement about the MAXIMUM GAP between consecutive")
print("prime addresses in arctanh-space: the gap is at most ln(2)/2.")
print()

for n in [10, 100, 1000]:
    xn = (n-1)/(n+1)
    x2n = (2*n-1)/(2*n+1)
    gap = atanh(x2n) - atanh(xn)
    print(f"  n={n}: arctanh gap = {gap:.6f}, ln(2)/2 = {log(2)/2:.6f}")

print()
print("  Bertrand's postulate = UNIFORM HYPERBOLIC DENSITY of primes.")
print("  Primes are never more than ln(2)/2 apart in arctanh-space.")
print()
print("  Compare: in EUCLIDEAN space, the gap n to 2n GROWS with n.")
print("  But in HYPERBOLIC space, it is CONSTANT.")
print("  This is why Bertrand's postulate is true: the hyperbolic")
print("  metric compresses large gaps into bounded ones.")
print()

# ============================================================
print("="*60)
print("2. INFINITUDE OF PRIMES")
print("="*60)
print()
print("Theorem (Euclid): There are infinitely many primes.")
print()
print("GEOMETRIC PROOF:")
print("  The addresses x_n fill [0,1) and accumulate at x=1.")
print("  arctanh(x_n) = ln(n)/2 -> infinity.")
print("  The total arctanh-length is infinite.")
print()
print("  If there were finitely many primes p_1,...,p_k,")
print("  then every n would be a product of these primes,")
print("  meaning every address x_n would be a hyperbolic sum")
print("  of finitely many prime addresses x_{p_1},...,x_{p_k}.")
print()
print("  But: the maximum of k copies of arctanh(x_{p_max})")
print("  is k * arctanh(x_{p_max}) = k * ln(p_max)/2 < infinity.")
print("  So the addresses x_n could only reach up to this bound,")
print("  contradicting arctanh(x_n) -> infinity.")
print()
print("  (This is Euclid's proof in hyperbolic language.)")
print()

# ============================================================
print("="*60)
print("3. UNIQUE FACTORIZATION (FUNDAMENTAL THEOREM OF ARITHMETIC)")
print("="*60)
print()
print("Theorem: Every n >= 2 factors uniquely into primes.")
print()
print("GEOMETRIC REFORMULATION:")
print("  Every address x_n (for n >= 2) decomposes UNIQUELY")
print("  as a hyperbolic sum of prime addresses.")
print()
print("  Uniqueness: the hyperbolic sum is commutative and")
print("  associative (arctanh addition is), so the decomposition")
print("  is unique up to order.")
print()
print("  This is the statement that the prime addresses form a")
print("  FREE ABELIAN MONOID under hyperbolic addition.")
print("  The natural numbers = the free abelian monoid generated")
print("  by the primes, under the Cayley-hyperbolic product.")
print()

# ============================================================
print("="*60)
print("4. SUM OF RECIPROCALS OF PRIMES DIVERGES")
print("="*60)
print()
print("Theorem (Euler 1737): sum 1/p over primes p diverges.")
print()
print("GEOMETRIC REFORMULATION:")
print("  The EUCLIDEAN spacing between consecutive prime addresses")
print("  x_{p_{k+1}} - x_{p_k} must sum to 1 (they fill [0,1)).")
print()
print("  But the Euclidean spacing near x = 1 is related to 1/p^2:")
print("  x_p = (p-1)/(p+1) = 1 - 2/(p+1)")
print("  1 - x_p = 2/(p+1) ~ 2/p for large p")
print()
print("  For consecutive primes p, q: x_q - x_p ~ 2/p - 2/q = 2(q-p)/(pq)")
print()
print("  The ARCTANH spacing is ln(q/p)/2.")
print()
print("  sum_{primes p} arctanh-step = sum ln(p_{k+1}/p_k)/2")
print("  This telescopes to ln(p_N)/2 -> infinity: DIVERGES.")
print()
print("  But sum 1/p diverges SLOWER (it is Mertens' theorem).")
print("  In hyperbolic space: the arctanh-spacing ~ 1/p per prime,")
print("  and sum 1/p = sum of arctanh-spacings... well, approximately.")
print()
print("  More precisely: for the k-th prime p_k,")
print("  arctanh(x_{p_k}) = ln(p_k)/2, and by PNT p_k ~ k*ln(k).")
print("  So arctanh(x_{p_k}) ~ ln(k*ln(k))/2 ~ ln(k)/2.")
print("  The spacing: ln((k+1)/k)/2 ~ 1/(2k).")
print("  And sum 1/(2k) diverges.")
print()

# ============================================================
print("="*60)
print("5. GOLDBACH-TYPE: EVERY EVEN NUMBER IS A SUM OF TWO PRIMES")
print("="*60)
print()
print("Conjecture (Goldbach 1742): Every even n >= 4 is p + q.")
print()
print("GEOMETRIC REFORMULATION:")
print("  ADDITION of natural numbers is NOT hyperbolic addition!")
print("  n + m != Q(x_n + x_m hyperbolic).")
print("  Addition in the naturals corresponds to a DIFFERENT operation")
print("  on the Cayley line.")
print()
print("  n + m: what is the address of n+m in terms of x_n and x_m?")
n, m = 3, 5
xn, xm = (n-1)/(n+1), (m-1)/(m+1)
x_sum = (n+m-1)/(n+m+1)
print(f"  n={n}, m={m}: x_n={xn:.4f}, x_m={xm:.4f}, x_{{n+m}}={x_sum:.4f}")
print(f"  Compare: (x_n+x_m)/2 = {(xn+xm)/2:.4f} (arithmetic mean)")
print(f"  x_{{n+m}} != midpoint. Addition is non-trivial on the Cayley line.")
print()
print("  x_{n+m} = ((n-1)(m+1) + (m-1)(n+1)) / ((n+1)(m+1) + ... )")
print("  Actually: x_{n+m} = (n+m-1)/(n+m+1)")
print()
print("  Goldbach in Cayley language: for every even address x_{2k},")
print("  there exist prime addresses x_p, x_q such that")
print("  x_{2k} = x_{p+q} where p+q = 2k.")
print()
print("  The geometry here is ADDITIVE, not multiplicative.")
print("  The Cayley line is optimized for multiplication (hyperbolic).")
print("  Goldbach is an ADDITIVE question on a MULTIPLICATIVE geometry.")
print("  This tension might explain why Goldbach is hard:")
print("  addition and multiplication are INCOMMENSURABLE operations")
print("  on the Cayley line.")
print()

# ============================================================
print("="*60)
print("6. LEGENDRE'S CONJECTURE")
print("="*60)
print()
print("Conjecture: There is a prime between n^2 and (n+1)^2.")
print()
print("GEOMETRIC REFORMULATION:")
print("  Address of n^2: x_{n^2} = (n^2-1)/(n^2+1)")
print("  Address of (n+1)^2: x_{(n+1)^2} = ((n+1)^2-1)/((n+1)^2+1)")
print()
print("  Hyperbolic distance:")

for n in [3, 10, 100]:
    a1 = atanh((n**2 - 1)/(n**2 + 1))
    a2 = atanh(((n+1)**2 - 1)/((n+1)**2 + 1))
    gap = a2 - a1
    # gap = ln((n+1)^2)/2 - ln(n^2)/2 = ln((n+1)^2/n^2)/2 = ln((1+1/n)^2)/2 = ln(1+1/n)
    predicted = log(1 + 1/n)
    print(f"  n={n}: gap = {gap:.6f}, ln(1+1/n) = {predicted:.6f}")

print()
print("  Gap = ln(1 + 1/n) ~ 1/n -> 0.")
print()
print("  Legendre says: even in this SHRINKING hyperbolic interval,")
print("  there is always a prime. The prime density must be at least")
print("  1 / ln(1+1/n) ~ n per unit of arctanh-length near x_{n^2}.")
print()
print("  By PNT: prime density near N is ~ 1/ln(N) = 1/(2*arctanh(x_N)).")
print("  At N=n^2: density ~ 1/(2*ln(n)).")
print("  Expected primes in the gap: ln(1+1/n) / (2*ln(n)) ~ 1/(2n*ln(n)).")
print("  This goes to 0, so the conjecture is NOT obvious even heuristically.")
print()
print("  But the WIDENING in Euclidean space (gap = 2n+1 ~ 2n) wins:")
print("  expected primes ~ 2n / ln(n^2) = n/ln(n) -> infinity.")
print()

# ============================================================
print("="*60)
print("7. CHEBYSHEV'S BIAS")
print("="*60)
print()
print("Observation: Among primes up to N, more are 3 mod 4 than 1 mod 4.")
print()
print("GEOMETRIC PERSPECTIVE:")
print("  Primes 1 mod 4: x_p for p = 5, 13, 17, 29, 37, ...")
print("  Primes 3 mod 4: x_p for p = 3, 7, 11, 19, 23, ...")
print()
print("  On the Cayley line, the 3-mod-4 primes start earlier:")
print("  x_3 = 0.500, x_7 = 0.750, x_11 = 0.833, ...")
print("  x_5 = 0.667, x_13 = 0.857, x_17 = 0.889, ...")
print()
print("  The 3-mod-4 primes have a HEAD START in hyperbolic space.")
print("  This head start (x_3 = 0.5 vs x_5 = 0.667) persists")
print("  because the hyperbolic metric PRESERVES ordering.")
print()
print("  Chebyshev's bias = the first-mover advantage on the Cayley line.")
print()

# ============================================================
print("="*60)
print("8. IRRATIONALITY OF sqrt(2)")
print("="*60)
print()
print("Theorem: sqrt(2) is irrational.")
print()
print("GEOMETRIC PROOF:")
print("  If sqrt(2) = p/q with p,q integers, then")
print("  the address x_{p/q} = (p/q - 1)/(p/q + 1) = (p-q)/(p+q).")
print()
print("  And Q(x_{p/q}) = p/q, so 2 = (p/q)^2 = Q(x_{p/q})^2.")
print("  So Q(x_{p/q})^2 = Q(x_2) = 2.")
print("  Hence x_{p/q}^2 hyperbolically = x_2, meaning:")
print("  2 * arctanh(x_{p/q}) = arctanh(x_2) = ln(2)/2.")
print("  arctanh(x_{p/q}) = ln(2)/4.")
print()
print("  If p/q is rational, x_{p/q} = (p-q)/(p+q) is rational.")
a = log(2)/4
x_sqrt2 = tanh(a)
print(f"  arctanh(x_{{sqrt(2)}}) = ln(2)/4 = {a:.10f}")
print(f"  x_{{sqrt(2)}} = tanh(ln(2)/4) = {x_sqrt2:.10f}")
print(f"  = {Fraction(x_sqrt2).limit_denominator(10000)}")
print(f"  = (sqrt(2)-1)/(sqrt(2)+1) = {(sqrt(2)-1)/(sqrt(2)+1):.10f}")
print()
print("  The address (sqrt(2)-1)/(sqrt(2)+1) is IRRATIONAL.")
print("  If sqrt(2) = p/q, then (p-q)/(p+q) would be rational.")
print("  But (sqrt(2)-1)/(sqrt(2)+1) = 3 - 2*sqrt(2) is irrational.")
print("  Contradiction.")
print()
print("  (This is the standard proof in Cayley language, but the")
print("  GEOMETRIC content is: sqrt(2) lies at a point on [0,1)")
print("  that is NOT a rational address, hence not a natural number ratio.)")
print()

# ============================================================
print("="*60)
print("9. ACTUAL NEW CONJECTURE: PRIME GAPS IN ARCTANH")
print("="*60)
print()
print("  Let d_k = arctanh(x_{p_{k+1}}) - arctanh(x_{p_k}) = ln(p_{k+1}/p_k)/2")
print("  be the k-th prime gap in arctanh-space.")
print()
print("  By PNT: p_{k+1}/p_k -> 1, so d_k -> 0.")
print("  Cramer's conjecture: max gap up to N ~ (ln N)^2.")
print("  In arctanh: max d_k for p_k < N ~ (ln N)^2 / (2N) -> 0.")
print()
print("  NEW CONJECTURE: the sequence d_k = ln(p_{k+1}/p_k)/2")
print("  has a specific distribution related to the exponential.")
print()

primes = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]
gaps_arctanh = [log(primes[k+1]/primes[k])/2 for k in range(len(primes)-1)]
mean_gap = sum(gaps_arctanh)/len(gaps_arctanh)
print(f"  First 24 arctanh-gaps: mean = {mean_gap:.6f}")
print(f"  For comparison: 1/(2*mean index) ~ {1/(2*12):.6f}")
print()
print(f"  Gaps: {[f'{g:.4f}' for g in gaps_arctanh[:12]]}")
print()

# ============================================================
print("="*60)
print("THE REAL OPPORTUNITY")
print("="*60)
print()
print("The Cayley address system gives number theory a METRIC SPACE")
print("structure ([0,1) with the hyperbolic/arctanh metric) that is:")
print()
print("  - COMPLETE (as a metric space)")
print("  - LOCALLY COMPACT")
print("  - MULTIPLICATIVELY NATURAL (times = hyperbolic addition)")
print("  - ANALYTICALLY TRACTABLE (Q is rational, arctanh is elementary)")
print()
print("The natural numbers are a DISCRETE SUBSET of this space.")
print("Questions about primes become questions about the DISTRIBUTION")
print("of a discrete set in a metric space.")
print()
print("This is the setup for GEOMETRIC MEASURE THEORY on [0,1).")
print("Tools: Hausdorff dimension, rectifiability, density theorems.")
print()
print("SPECIFIC OPPORTUNITY: the Cayley transform connects to")
print("the tournament Fourier weights g_k(m). The Delannoy numbers")
print("provide a POLYNOMIAL APPROXIMATION to number-theoretic functions.")
print("If the Delannoy weights can detect prime structure, this would")
print("be a genuinely new approach to analytic number theory.")
