#!/usr/bin/env python3
"""graphs_as_numbers_s116k.py — If snarks are primes, what are the other numbers?

The Petersen graph = 2 (the first prime, the atom).
Snarks = primes (irreducible obstructions).
3-edge-colorable cubic graphs = composites (built from colorable pieces).

Then: what is 1? What is 0? What is 3? What is multiplication?
What is the formal group of graphs?
"""
from math import log, sqrt, comb
from fractions import Fraction

print()
print("  GRAPHS AS NUMBERS")
print()
print("="*70)
print()

# ============================================================
print("  I. THE DICTIONARY")
print("  " + "-"*40)
print()
print("  NUMBER          GRAPH ANALOG")
print("  " + "-"*50)
print("  0               the empty graph (no vertices)")
print("  1               K_1 (single vertex, the identity)")
print("  2               the Petersen graph (first snark = first prime)")
print("  3               the Blanusa snarks (next snarks, 18 vertices)")
print("  composites      3-edge-colorable cubic graphs")
print("  primes          snarks")
print("  multiplication  graph product (tensor, Cartesian, or ...)")
print("  addition        disjoint union?")
print("  factorization   decomposition into snark minors")
print()
print("  But this needs refinement. Let me think about what")
print("  MULTIPLICATION should be.")
print()

# ============================================================
print()
print("  II. WHAT IS MULTIPLICATION OF GRAPHS?")
print("  " + "-"*40)
print()
print("  For numbers: n*m counts the elements of an n-by-m grid.")
print("  The grid is the Cartesian product.")
print()
print("  For graphs: the Cartesian product G [] H has vertex set V(G) x V(H)")
print("  with (g1,h1) ~ (g2,h2) iff g1=g2 and h1~h2, or g1~g2 and h1=h2.")
print()
print("  Properties:")
print("  |V(G [] H)| = |V(G)| * |V(H)|   (vertex count multiplies)")
print("  The product is commutative and associative.")
print("  K_1 is the identity: G [] K_1 = G.")
print()
print("  But this doesn't preserve cubicness (3-regularity).")
print("  If G is 3-regular and H is 3-regular,")
print("  G [] H is 6-regular (degrees add in Cartesian product).")
print()
print("  For CUBIC graphs, the right product is the DOT PRODUCT:")
print("  Remove an edge from each graph, then glue along the loose ends.")
print("  This PRESERVES 3-regularity.")
print()
print("  The dot product is to cubic graphs")
print("  what multiplication is to natural numbers.")
print()

# ============================================================
print()
print("  III. WHAT IS ADDITION OF GRAPHS?")
print("  " + "-"*40)
print()
print("  For numbers: n + m.")
print("  The SUCCESSOR n -> n+1 is the most fundamental.")
print()
print("  For graphs: adding one vertex is too crude.")
print("  For cubic graphs: you can't add one vertex and stay cubic")
print("  (you need to add vertices in groups that maintain regularity).")
print()
print("  The natural 'successor' for cubic graphs:")
print("  Take G with n vertices. The NEXT cubic graph has n+2 vertices")
print("  (cubic graphs have even vertex count: 3n/2 edges, so n must be even).")
print()
print("  The cubic graph 'number line':")
print("  n=2: not possible (K_4 is 3-regular but has 4 vertices)")
print("  n=4: K_4 (complete graph on 4 vertices, 3-regular)")
print("  n=6: K_{3,3} (complete bipartite) and the prism graph C_3 [] K_2")
print("  n=8: several cubic graphs")
print("  n=10: includes the PETERSEN GRAPH (first snark)")
print()
print("  So the cubic graph 'integers' start at n=4:")
print("  4, 6, 8, 10, 12, 14, 16, 18, 20, ...")
print("  = the even numbers >= 4.")
print()
print("  The Petersen graph at n=10 is the FOURTH entry (4,6,8,10).")
print("  In our framework: it corresponds to the 4th even number.")
print("  10 is the 4th even number >= 4.  And 4 = the Cayley period.")
print()

# ============================================================
print()
print("  IV. THE CENSUS OF CUBIC GRAPHS")
print("  " + "-"*40)
print()
print("  Number of connected cubic graphs on n vertices:")
print("  n=4:  1 (K_4)")
print("  n=6:  2 (K_{3,3}, prism)")
print("  n=8:  5")
print("  n=10: 19 (including Petersen)")
print("  n=12: 85")
print("  n=14: 509")
print("  n=16: 4060")
print("  n=18: 41301 (including Blanusa snarks)")
print()
cubic_counts = [0, 0, 0, 0, 1, 0, 2, 0, 5, 0, 19, 0, 85, 0, 509, 0, 4060, 0, 41301]
print("  Of these, snarks (non-3-edge-colorable, bridgeless):")
print("  n=10: 1 (Petersen)")
print("  n=18: 2 (Blanusa)")
print("  n=20: 6")
print("  n=22: 20")
print("  n=24: 38")
print("  n=26: 280")
print("  n=28: 2900")
print()
snark_counts = {10: 1, 18: 2, 20: 6, 22: 20, 24: 38, 26: 280, 28: 2900}
print("  Snark density (snarks / total cubic):")
for n, sc in sorted(snark_counts.items()):
    if n < len(cubic_counts) and cubic_counts[n] > 0:
        density = sc / cubic_counts[n]
        print(f"  n={n}: {sc}/{cubic_counts[n]} = {density:.4f}")
    else:
        print(f"  n={n}: {sc} snarks")

print()
print("  The snark density at n=10: 1/19 = 5.3%. About 1 in 20.")
print("  Compare: prime density at n=10: pi(10)/10 = 4/10 = 40%.")
print("  Snarks are RARER than primes at comparable scales.")
print()

# ============================================================
print()
print("  V. THE SNARK 'RAPIDITY'")
print("  " + "-"*40)
print()
print("  If snarks are primes, what is their rapidity?")
print("  rapidity(n) = ln(n)/2 for natural numbers.")
print()
print("  For snarks, the natural 'size' is the vertex count.")
print("  snark_rapidity(G) = ln(|V(G)|)/2.")
print()
print("  Petersen: rap = ln(10)/2 = {:.4f}".format(log(10)/2))
print("  Blanusa:  rap = ln(18)/2 = {:.4f}".format(log(18)/2))
print("  Flower J5: rap = ln(20)/2 = {:.4f}".format(log(20)/2))
print()
print("  The rapidity gap Petersen -> Blanusa:")
print(f"  ln(18)/2 - ln(10)/2 = ln(18/10)/2 = ln(9/5)/2 = {log(9/5)/2:.4f}")
print(f"  9/5 = 1.8. The 'interval' is 9/5 = a minor seventh!")
print(f"  Q^{{-1}}(9/5) = (9/5-1)/(9/5+1) = (4/5)/(14/5) = 4/14 = 2/7.")
print(f"  The Cayley address of the Petersen-to-Blanusa gap is 2/7.")
print(f"  And Q(2/7) = 9/5. The minor seventh.")
print()
print("  The gap from the first to second snark is a MINOR SEVENTH.")
print("  Compare prime gaps: 2 to 3 has gap 1 (half-gap 1, unison).")
print("  The snark gaps are WIDER and more DISSONANT from the start.")
print()

# ============================================================
print()
print("  VI. THE ANALOGY TABLE")
print("  " + "-"*40)
print()
print("  NUMBERS              CUBIC GRAPHS")
print("  " + "-"*55)
print("  1                    K_4 (the identity: every cubic graph 'contains' K_4)")
print("  2 (first prime)      Petersen (first snark)")
print("  3 (second prime)     Blanusa (second snark, comes in 2 versions)")
print("  4 (first composite)  The first NON-snark cubic graph past K_4")
print("  even                 cubic graphs (must have even vertex count)")
print("  odd                  --- (no cubic graph analog)")
print("  prime                snark")
print("  composite            3-edge-colorable")
print("  prime factorization  snark minor decomposition")
print("  fundamental thm      'every cubic graph has a unique snark obstruction set'")
print("  Redei (H is odd)     'every bridgeless cubic graph has ... '")
print("  H(T)                 edge-chromatic index (3 or 4)")
print("  forbidden H=7        ???")
print()

# ============================================================
print()
print("  VII. THE KEY INVARIANT: EDGE-CHROMATIC INDEX")
print("  " + "-"*40)
print()
print("  For a cubic graph: edge-chromatic index chi'(G) = 3 or 4.")
print("  (Vizing's theorem: Delta <= chi' <= Delta+1, and Delta=3.)")
print()
print("  chi' = 3: the graph IS 3-edge-colorable. 'Composite.'")
print("  chi' = 4: the graph is NOT 3-edge-colorable. If also bridgeless: 'snark' = 'prime.'")
print()
print("  This is a BINARY invariant: 3 or 4. Like parity: even or odd.")
print("  But in tournaments, H(T) takes many values (1, 3, 5, 9, ...).")
print()
print("  The richer cubic graph invariant is the RESISTANCE:")
print("  r(G) = minimum number of edges to remove to make G 3-edge-colorable.")
print("  r(G) = 0 iff chi' = 3 (colorable).")
print("  r(Petersen) = 1 (remove one edge and it becomes colorable).")
print()
print("  Resistance is like H(T) for cubic graphs:")
print("  it measures HOW FAR from 'easy' the graph is.")
print("  r = 0: trivially colorable (like H=1: trivially ordered).")
print("  r = 1: one edge away (like H=3: one cycle away from transitive).")
print("  r >= 2: deeply non-colorable (like H >= 9: many cycles).")
print()

# ============================================================
print()
print("  VIII. THE CUBIC GRAPH OCF ANALOG")
print("  " + "-"*40)
print()
print("  In tournaments: H(T) = I(Omega(T), 2) = 1 + 2*a1 + 4*a2 + ...")
print("  The OCF decomposes H into contributions from independent cycle sets.")
print()
print("  For cubic graphs: is there an analogous decomposition?")
print()
print("  The ODDNESS of a cubic graph G:")
print("  o(G) = minimum number of ODD components in any 2-factor.")
print("  (A 2-factor = set of cycles covering all vertices.)")
print()
print("  o(G) = 0 iff G has a perfect 2-factor (all cycles even) iff chi' = 3.")
print("  o(Petersen) = 1 (every 2-factor has exactly 1 odd cycle = a pentagon).")
print()
print("  The oddness is the cubic graph analog of alpha_1 (cycle count)!")
print("  o(G) counts odd components in the best 2-factoring,")
print("  just as alpha_1 counts odd cycles in the tournament.")
print()
print("  Could there be a 'cubic graph OCF':")
print("  chi'(G) - 3 = function of oddness, independence, etc.?")
print("  chi' = 3 + [o(G) > 0] = 3 or 4. TOO COARSE.")
print()
print("  But RESISTANCE gives a richer invariant:")
print("  r(G) = number of edges to remove. Could r have an OCF-like formula?")
print("  r(G) = sum of contributions from 'irreducible non-colorable pieces'?")
print("  If snarks are primes, this would be the FACTORIZATION of resistance.")
print()

# ============================================================
print()
print("  IX. THE PETERSEN NUMBER SYSTEM")
print("  " + "-"*40)
print()
print("  Map each cubic graph to a 'number' based on its snark content.")
print()
print("  The 'Petersen number' P(G) of a cubic graph G:")
print("  P(G) = number of edge-disjoint Petersen minors in G.")
print("  (Loosely defined, but captures the idea.)")
print()
print("  P(K_4) = 0 (too small to contain Petersen).")
print("  P(Petersen) = 1 (contains itself).")
print("  P(Blanusa) = 1 (contains one Petersen minor).")
print("  P(double Petersen) = 2 (two copies glued).")
print()
print("  If the Petersen minor conjecture is true:")
print("  P(G) >= 1 for EVERY snark G.")
print("  Every snark 'contains' at least one copy of Petersen.")
print("  Just as every even number >= 2 contains at least one copy of 2.")
print()
print("  The 'Petersen valuation' v_P(G) = the Petersen minor count.")
print("  Analogous to the 2-adic valuation v_2(n).")
print("  v_2(n) = number of times 2 divides n.")
print("  v_P(G) = number of times Petersen 'divides' G.")
print()

# ============================================================
print()
print("  X. WHAT THE ANALOGY TEACHES US")
print("  " + "-"*40)
print()
print("  If snarks are primes and the Petersen graph is 2, then:")
print()
print("  1. The FUNDAMENTAL THEOREM should say:")
print("     Every non-colorable cubic graph decomposes into snarks")
print("     in an essentially unique way.")
print("     This is CLOSE to known structure theorems but not proved in this form.")
print()
print("  2. The PRIME NUMBER THEOREM analog:")
print("     The density of snarks among cubic graphs on n vertices")
print("     should decrease as 1/ln(n) or similar.")
print("     The data: density drops from 5.3% (n=10) to ... smaller.")
print()
print("  3. The TWIN PRIME analog:")
print("     Are there infinitely many 'twin snarks'")
print("     (snarks whose vertex counts differ by the minimum = 2)?")
print("     The snark counts: n = 10, 18, 20, 22, 24, 26, 28, ...")
print("     After the Petersen-Blanusa gap (10 to 18 = gap 8),")
print("     the gaps are 2, 2, 2, 2, 2, ...")
print("     EVERY even vertex count >= 18 has at least one snark!")
print("     (This is essentially known.)")
print("     So 'twin snarks' are EVERYWHERE — unlike twin primes.")
print()
print("  4. The GOLDBACH analog:")
print("     Can every non-colorable cubic graph be written as")
print("     the 'sum' (disjoint union? dot product?) of two snarks?")
print()
print("  5. The RIEMANN HYPOTHESIS analog:")
print("     Is there a 'zeta function' for cubic graphs")
print("     whose zeros control the distribution of snarks?")
print("     The Ihara zeta function of a graph is a candidate!")
print()

# ============================================================
print()
print("  XI. THE IHARA ZETA AND THE CHORD ZETA")
print("  " + "-"*40)
print()
print("  The Ihara zeta function of a graph G:")
print("  Z_G(u) = prod_{[C]} (1 - u^{|C|})^{-1}")
print("  product over primitive closed cycles C.")
print()
print("  This is EXACTLY the Euler product structure of the Riemann zeta!")
print("  zeta(s) = prod_p (1 - p^{-s})^{-1}.")
print()
print("  For the Petersen graph:")
print("  The shortest cycles have length 5 (the girth).")
print("  Z_Petersen(u) = (1 - u^5)^{-...} * ...")
print()
print("  And our CHORD zeta:")
print("  Z_CHORD(s) = prod_{p>=3} (1 + ((p-1)/(p-2))/(p^s - 1))")
print()
print("  The Ihara zeta products over CYCLES.")
print("  The Chord zeta products over PRIMES.")
print("  The Riemann zeta products over PRIMES.")
print()
print("  If we evaluate the Ihara zeta of a cubic graph at u related to")
print("  the Cayley transform... the Ihara zeta at u = 1/Q(x) = (1-x)/(1+x)...")
print("  this would connect the graph's cycle structure to the Cayley framework.")
print()
print("  The Ihara zeta of Petersen, evaluated at the Cayley velocity of a prime,")
print("  would give a number that encodes how the Petersen graph's cycles")
print("  interact with that prime's rapidity. This is a CONCRETE computation")
print("  that could reveal new structure.")
print()

# ============================================================
print()
print("  XII. THE FULL PICTURE")
print("  " + "-"*40)
print()
print("  NUMBERS            CUBIC GRAPHS         TOURNAMENTS")
print("  " + "-"*60)
print("  0                  empty graph           ---")
print("  1                  K_4                   transitive T (H=1)")
print("  2 (prime)          Petersen (snark)      T_3 (3-cycle, H=3)")
print("  3 (prime)          Blanusa (snark)       T with c3=2 (H=5)")
print("  4 (composite)      K_{3,3} (colorable)   T with H=9")
print("  primes             snarks                max-H tournaments?")
print("  composites         colorable cubics      intermediate-H tournaments")
print("  1 = odd always     chi'=3 or 4           H = odd always (Redei)")
print("  forbidden H=7      ---                   H=7 impossible")
print("  rapidity ln(n)/2   ln(|V|)/2             ln(H)/2")
print("  formal group F_h   graph dot product?    velocity addition")
print("  zeta function      Ihara zeta            chord zeta")
print()
print("  Three parallel worlds: numbers, graphs, tournaments.")
print("  The same structures repeat in each:")
print("  primes, irreducibility, factorization, zeta functions, forbidden values.")
print("  The Cayley transform Q connects them all via rapidity.")
print()
print("  The deepest connection: the OBSTRUCTION in each world is the SAME.")
print("  In numbers: primality. You can't factor further.")
print("  In graphs: snarkness. You can't color further.")
print("  In tournaments: forbiddenness. You can't reach H=7.")
print("  All three are manifestations of the IRREDUCIBLE.")
print("  The place where the structure says: NO FURTHER.")
