#!/usr/bin/env python3
"""
h_spectrum_keller_monoid_boxeph_S146.py  (HYP-8160)

THE H-{7,21} IMPOSSIBILITY AS THE TEMPLATE FOR THE JC2 MAP (owner hint).

TOURNAMENT SIDE (verified here):
  h(T) = #Hamiltonian paths.  (R) Redei: h is ODD.  (M) h is MULTIPLICATIVE over
  the condensation: h(T) = prod h(strong components) (paths traverse components
  in the transitive order, concatenating).  So the attainable set is the
  multiplicative monoid generated by STRONG-attainable values; gaps in the
  strong spectrum propagate: 7 is prime and (verified below) NOT strong-attainable
  at accessible n, and 21 = 3*7 needs a 7 or a strong 21 -- hence H != 7, 21.

KELLER SIDE (the dictionary; proofs/statements in the S146 reflection):
  deg(F o G) = deg F * deg G and Keller o Keller = Keller: cover-degrees of
  Keller self-maps form a multiplicative monoid; "strong tournament" <->
  composition-irreducible Keller map; strong-spectrum gaps <-> the Euler-ledger
  + Ghost exclusions: in dim 2,  sum_i (d - k_i) chi(C_i) = d - 1  (clean case)
  with k_i <= #Fix(local monodromy g_i) and ghosts generating -- which excludes
  d = 2 with smooth asymptotic components (LHS >= 2 > 1) and forces Z/3-d=3 to
  carry a chi = 0 singular ghost.  Redei's parity <-> THE ODD-DEGREE CONJECTURE:
  Keller counterexample cover-degrees are odd (evidence: d = 2 obstructed, the
  kernel d = 3, compositions preserve oddness).

boxeph-2026-07-20-S146.  Pure Python, exact.
"""

import random
from itertools import product

def hpaths(adj, n):
    """#Hamiltonian paths via subset DP.  adj[u] = bitmask of v with u -> v."""
    dp = [[0] * n for _ in range(1 << n)]
    for v in range(n):
        dp[1 << v][v] = 1
    for S in range(1 << n):
        for v in range(n):
            c = dp[S][v]
            if not c or not (S >> v) & 1:
                continue
            rest = ((1 << n) - 1) ^ S
            m = adj[v] & rest
            while m:
                w = (m & -m).bit_length() - 1
                dp[S | (1 << w)][w] += c
                m &= m - 1
    full = (1 << n) - 1
    return sum(dp[full][v] for v in range(n))

def is_strong(adj, n):
    for s in range(n):
        seen = 1 << s
        stack = [s]
        while stack:
            u = stack.pop()
            m = adj[u] & ~seen
            while m:
                w = (m & -m).bit_length() - 1
                seen |= 1 << w
                stack.append(w)
                m &= m - 1
        if seen != (1 << n) - 1:
            return False
    return True

def strong_components_h(adj, n):
    """condensation: h(T) should equal prod over strong components of h."""
    # reachability closure
    reach = [adj[u] | (1 << u) for u in range(n)]
    for _ in range(n):
        for u in range(n):
            m = reach[u]
            acc = m
            mm = m
            while mm:
                w = (mm & -mm).bit_length() - 1
                acc |= reach[w]
                mm &= mm - 1
            reach[u] = acc
    comp = {}
    for u in range(n):
        key = tuple(sorted([v for v in range(n) if (reach[u] >> v) & 1 and (reach[v] >> u) & 1]))
        comp[key] = True
    prod = 1
    for verts in comp:
        k = len(verts)
        idx = {v: i for i, v in enumerate(verts)}
        sub = [0] * k
        for u in verts:
            for v in verts:
                if u != v and (adj[u] >> v) & 1:
                    sub[idx[u]] |= 1 << idx[v]
        prod *= hpaths(sub, k)
    return prod

def all_tournaments(n):
    pairs = [(i, j) for i in range(n) for j in range(i + 1, n)]
    for bits in range(1 << len(pairs)):
        adj = [0] * n
        for k, (i, j) in enumerate(pairs):
            if (bits >> k) & 1:
                adj[i] |= 1 << j
            else:
                adj[j] |= 1 << i
        yield adj

print("=" * 92)
print("TOURNAMENT SIDE: exhaustive h-spectrum n <= 6 (Redei, multiplicativity, gaps)")
print("=" * 92)
attain = {}
strong_attain = {}
for n in range(1, 7):
    vals, svals = set(), set()
    for adj in all_tournaments(n):
        h = hpaths(adj, n)
        assert h % 2 == 1, "REDEI VIOLATED?!"
        vals.add(h)
        if is_strong(adj, n):
            svals.add(h)
    attain[n] = vals
    strong_attain[n] = svals
    print("n=%d: attainable h = %s" % (n, sorted(vals)))
    print("      strong-attainable = %s" % sorted(svals))
A6 = set().union(*attain.values())
S6 = set().union(*strong_attain.values())
print("\nunion n<=6: attainable = %s" % sorted(A6))
print("            strong     = %s" % sorted(S6))
print("7 attainable: %s ; 21 attainable: %s  (IMPOSSIBILITY at n<=6: %s)"
      % (7 in A6, 21 in A6, 7 not in A6 and 21 not in A6))
# monoid check: attainable = monoid generated by strong values (up to n<=6 sizes)
gen = {1}
frontier = True
while frontier:
    frontier = False
    for a in list(gen):
        for s in S6:
            if a * s <= max(A6) and a * s not in gen:
                gen.add(a * s); frontier = True
print("monoid generated by strong values (truncated): %s" % sorted(x for x in gen if x <= max(A6)))
print("matches attainable: %s  (the condensation-monoid law)" % (sorted(x for x in gen if x in A6 or x <= max(A6)) == sorted(gen & set(range(1, max(A6)+1)))))

# multiplicativity spot-check on random tournaments
rng = random.Random(146)
ok = 0
for _ in range(300):
    n = rng.randint(2, 7)
    adj = [0] * n
    for i in range(n):
        for j in range(i + 1, n):
            if rng.random() < 0.5:
                adj[i] |= 1 << j
            else:
                adj[j] |= 1 << i
    if hpaths(adj, n) == strong_components_h(adj, n):
        ok += 1
print("multiplicativity h = prod h(strong comps): %d/300 verified" % ok)
assert ok == 300

print("\n" + "=" * 92)
print("n = 7 sample (60k labeled): does h = 7 or 21 ever appear?")
print("=" * 92)
found = {7: 0, 21: 0}
vals7 = set()
for _ in range(60000):
    adj = [0] * 7
    for i in range(7):
        for j in range(i + 1, 7):
            if rng.random() < 0.5:
                adj[i] |= 1 << j
            else:
                adj[j] |= 1 << i
    h = hpaths(adj, 7)
    vals7.add(h)
    if h in found:
        found[h] += 1
print("hits: h=7: %d, h=21: %d ; smallest attained values at n=7 (sample): %s"
      % (found[7], found[21], sorted(v for v in vals7 if v <= 45)))
print("\nDICTIONARY (details + proofs in reflection): h-monoid <-> Keller-degree monoid;")
print("strong tournaments <-> composition-irreducible Keller maps; strong-spectrum gaps")
print("<-> Euler-ledger/Ghost exclusions (d=2 smooth-caustic IMPOSSIBLE; Z/3-d=3 needs a")
print("chi=0 ghost); Redei odd <-> THE ODD-DEGREE CONJECTURE for Keller counterexamples.")
print("DONE.")
