import sympy as sp
x,u,th = sp.symbols('x u theta', real=True)
P = sp.expand(x*(x**2+7)*(x**4+14*x**2+17))
print("P(x) =", P)
print("odd?  P(-x)+P(x) =", sp.simplify(sp.expand(P.subs(x,-x)+P)))
print()
print("(1) THE u-SUBSTITUTION  u = x^2 + 7")
lhs = sp.expand((x**2+7)**3 - 32*(x**2+7))
print("   (x^2+7)^3 - 32(x^2+7) =", sp.factor(lhs))
print("   so P(x) = x * (u^3 - 32u) with u = x^2+7 :",
      sp.simplify(sp.expand(P - x*lhs)) == 0)
print("   u^3 - 32u is DEPRESSED (no u^2 term), roots {0, +4sqrt2, -4sqrt2} = {0, r, -r}")
print("   -> the SAME 1-fixed + 1-free-2-orbit shape as the JC fibre (THM-1440/1445)")
print("   involution here: u -> -u.  Sum of roots = 0.")
print()
print("(2) ROOTS")
for f,lab in [(x**2+7,'x^2+7'), (x**4+14*x**2+17,'x^4+14x^2+17')]:
    print(f"   {lab}: roots {sp.solve(f,x)}")
print("   x^2 values:", [sp.nsimplify(v) for v in [-7, -7+4*sp.sqrt(2), -7-4*sp.sqrt(2)]])
print("   product of the two quartic x^2 values = (-7)^2-32 =", 49-32)
print()
print("(3) GALOIS GROUPS")
for f,lab in [(x**2+7,'x^2+7'), (x**4+14*x**2+17,'x^4+14x^2+17'), (P,'P')]:
    try:
        G = sp.galois_group(sp.Poly(f,x))
        print(f"   {lab}: {G}")
    except Exception as e:
        print(f"   {lab}: (galois_group unavailable/failed: {type(e).__name__})")
print()
print("(4) IS i*sqrt(7) THE GAUSS SUM OF chi_7?  g(chi_p)=i*sqrt(p) for p=3 mod 4.")
g = sum(sp.legendre_symbol(k,7)*sp.exp(2*sp.pi*sp.I*k/7) for k in range(1,7))
print("   g(chi_7) =", sp.simplify(sp.expand(sp.nsimplify(sp.N(g,30)))), " numerically", sp.N(g,20))
print("   i*sqrt(7) =", sp.N(sp.I*sp.sqrt(7),20))
print("   => roots of x^2+7 are exactly +-g(chi_7).")
print()
print("(5) SIN/COS: is P a multiple-angle polynomial?")
print("   sin(7t) as a polynomial in s=sin t:")
s = sp.symbols('s')
expr = sp.expand(sp.simplify(sp.expand_trig(sp.sin(7*th))))
poly7 = sp.simplify(expr.rewrite(sp.sin).subs(sp.cos(th)**2, 1-sp.sin(th)**2))
print("   sin7t coeffs (in sin t):", sp.Poly(sp.expand(sp.chebyshevu(6,sp.cos(th))*sp.sin(th)).subs(sp.cos(th)**2,1-s**2).subs(sp.sin(th),s), s).all_coeffs() if True else None)
print("   P coeffs:", sp.Poly(P,x).all_coeffs())
print("   -> compare: multiple-angle sin(7t) has coeffs [-64,0,112,0,-56,0,7]; P has [1,0,21,0,115,0,119,0]")
print("      DIFFERENT (P is degree 7 with 4 nonzero odd coeffs but the wrong ones).")
print()
print("(6) THE HEPTAGON SINE PRODUCT (classical): prod_{k=1}^{3} 2 sin(k*pi/7) = sqrt(7)")
pr = sp.prod([2*sp.sin(sp.pi*k/7) for k in range(1,4)])
print("   numeric:", sp.N(pr,20), "   sqrt(7) =", sp.N(sp.sqrt(7),20))
