#!/usr/bin/env python3
"""Exact companion for THM-2700.

The proof is algebraic.  This companion checks the identities, finite group
actions, Smith data, and sharp D4 boundary without numerical approximation.
Every truth-bearing check uses ``require`` and remains active under ``-O``.
"""

from __future__ import annotations

from functools import reduce
from itertools import product
from math import gcd

import sympy as sp
from sympy.matrices.normalforms import smith_normal_form


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def zeta_reduce(expr: sp.Expr, zeta: sp.Symbol) -> sp.Expr:
    poly = sp.Poly(sp.expand(expr), zeta)
    modulus = sp.Poly(zeta**2 + zeta + 1, zeta)
    return sp.factor(poly.rem(modulus).as_expr())


def mat2_mul(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
    return (
        (a[0] * b[0] + a[1] * b[2]) % 2,
        (a[0] * b[1] + a[1] * b[3]) % 2,
        (a[2] * b[0] + a[3] * b[2]) % 2,
        (a[2] * b[1] + a[3] * b[3]) % 2,
    )


def mat2_vec(a: tuple[int, ...], v: tuple[int, int]) -> tuple[int, int]:
    return ((a[0] * v[0] + a[1] * v[1]) % 2,
            (a[2] * v[0] + a[3] * v[1]) % 2)


def generated_group(generators: tuple[tuple[int, ...], ...]) -> set[tuple[int, ...]]:
    identity = (1, 0, 0, 1)
    group = {identity}
    frontier = [identity]
    while frontier:
        left = frontier.pop()
        for right in generators:
            new = mat2_mul(left, right)
            if new not in group:
                group.add(new)
                frontier.append(new)
    return group


def main() -> None:
    x, r, s, G, Q, T, zeta = sp.symbols("x r s G Q T zeta")

    # The three Cardano roots and the full S3 splitting polynomial.
    roots = (
        r + s,
        zeta * r + zeta**2 * s,
        zeta**2 * r + zeta * s,
    )
    e1 = zeta_reduce(sum(roots), zeta)
    e2 = zeta_reduce(sum(roots[i] * roots[j]
                         for i in range(3) for j in range(i + 1, 3)), zeta)
    e3 = zeta_reduce(reduce(lambda u, v: u * v, roots, sp.Integer(1)), zeta)
    require(e1 == 0, "Cardano root sum")
    require(sp.expand(e2 + 3 * r * s) == 0, "Cardano pair sum")
    require(sp.expand(e3 - r**3 - s**3) == 0, "Cardano product")

    cubic = T**3 - 3 * G * T - Q
    cubic_disc = sp.factor(sp.discriminant(cubic, T))
    require(sp.expand(cubic_disc - 27 * (4 * G**3 - Q**2)) == 0,
            "cubic discriminant")
    pulled_disc = sp.factor(cubic_disc.subs({G: r * s, Q: r**3 + s**3}))
    require(sp.expand(pulled_disc + 27 * (r**3 - s**3) ** 2) == 0,
            "pulled-back discriminant square")

    relative_matrix = sp.Matrix([[s, r], [3 * r**2, 3 * s**2]])
    relative_det = sp.factor(relative_matrix.det())
    require(sp.expand(relative_det + 3 * (r**3 - s**3)) == 0,
            "relative different")

    # C3 invariants are generated by r^3,s^3; the reflection swaps them.
    # The displayed recurrence proves every symmetric power sum lies in C[G,Q].
    power_sums = [sp.Integer(2), Q]
    for _ in range(2, 9):
        power_sums.append(sp.expand(Q * power_sums[-1] - G**3 * power_sums[-2]))
    for n, value in enumerate(power_sums):
        specialization = sp.expand(value.subs({G: r * s, Q: r**3 + s**3}))
        require(sp.expand(specialization - r ** (3 * n) - s ** (3 * n)) == 0,
                f"symmetric invariant recurrence n={n}")

    invariant_orbits = 0
    for i in range(13):
        for j in range(i + 1):
            if (i - j) % 3 != 0:
                continue
            invariant_orbits += 1
            if i == j:
                require((r * s) ** i == (r * s) ** j, "diagonal invariant")
            else:
                n = (i - j) // 3
                lhs = r**i * s**j + r**j * s**i
                rhs = (r * s) ** j * power_sums[n]
                rhs = rhs.subs({G: r * s, Q: r**3 + s**3})
                require(sp.expand(lhs - rhs) == 0, "bounded invariant orbit")

    # One-row Smith packets model Cl(R_g)=Z^d/<m_1,...,m_d>.
    packet_count = 0
    even_torsion_count = 0
    bockstein_nonlift_count = 0
    for d in range(1, 6):
        for multiplicities in product(range(1, 7), repeat=d):
            packet_count += 1
            m0 = reduce(gcd, multiplicities)
            has_two_torsion = m0 % 2 == 0
            if has_two_torsion:
                even_torsion_count += 1
                eta = m0 // 2
                require((-eta) % m0 == eta, "reflection fixes the order-two class")
                has_half = any((2 * value - eta) % m0 == 0
                               for value in range(m0))
                require(has_half == (m0 % 4 == 0), "Picard four-divisibility")
                if not has_half:
                    bockstein_nonlift_count += 1
            else:
                require(all((2 * value) % m0 != 0 for value in range(1, m0)),
                        "odd cyclic group has no two-torsion")

    # D4 is the sharp non-Danielewski triality carrier.
    d4 = sp.Matrix([
        [-2, 1, 1, 1],
        [1, -2, 0, 0],
        [1, 0, -2, 0],
        [1, 0, 0, -2],
    ])
    d4_smith = smith_normal_form(d4, domain=sp.ZZ)
    d4_diag = tuple(abs(int(d4_smith[i, i])) for i in range(4))
    require(int(d4.det()) == 4, "D4 determinant")
    require(d4_diag == (1, 1, 2, 2), "D4 discriminant group")

    cycle = (0, 1, 1, 1)       # e_a -> e_b, e_b -> e_a+e_b
    reflection = (0, 1, 1, 0)  # e_a <-> e_b
    group = generated_group((cycle, reflection))
    require(len(group) == 6, "D4 triality image is GL(2,F2)")
    nonzero = {(1, 0), (0, 1), (1, 1)}
    orbit = {mat2_vec(g, (1, 0)) for g in group}
    require(orbit == nonzero, "triality permutes all three nonzero classes")

    # A single moving -2 arm is exactly the even determinant producing W.
    arm = sp.Matrix([[-2]])
    require(int(arm.det()) % 2 == 0, "D4 moving arm has even determinant")

    print("THM-2700 DANIELEWSKI S3 RESOLVENT AUDIT")
    print("group_order=6 invariant_ring=C[x,r^3+s^3]")
    print(f"cubic_discriminant={cubic_disc}")
    print(f"pulled_discriminant={pulled_disc}")
    print(f"relative_different_generator={relative_det}")
    print(f"symmetric_power_sum_recurrence_checked=0..{len(power_sums)-1}")
    print(f"bounded_invariant_orbits_checked={invariant_orbits}")
    print(f"class_group_multiplicity_packets={packet_count}")
    print(f"packets_with_one_trivial_two_torsion_line={even_torsion_count}")
    print(f"packets_with_nonliftable_mu4_line={bockstein_nonlift_count}")
    print(f"d4_det={int(d4.det())} d4_smith={d4_diag}")
    print(f"d4_triality_group_order={len(group)} nonzero_orbit={sorted(orbit)}")
    print("linear_g_boundary=rank_two_S3_reflection_quotient")
    print("constant_g_boundary=one_trivial_unit_squareclass")
    print("PASS")


if __name__ == "__main__":
    main()
