#!/usr/bin/env python3
"""
kind-pasteur-2026-07-19-S128c98 -- HYP-8090: the DESIGN-EQUATION solver.

DISCOVERY (this session): the counterexample is generated by ONE function W and
ONE residue R via the design equations
    B1 = u*W,   B2 = y + k*x*W,   B3 = (R(x,u) - x^k*u*W)/u^k   (must be polynomial),
    A  = (u^k, k*u^{k-1}*x, -x^k),   F = A*z + B,   u = 1+xy.
For the owner's map (k=3): W = y^2(4+3xy), R = x*u*(u+1) = x*u + x*u^2.  The two
fiber conics C1: k*a*x^2 = u(bx - s), C2: a*x^k + g*u^k = R(x,u) are equivalent
to these design equations -- the collapse IS the design.

Solver: parametrize (W, R) with unknown coefficients, impose
  (i)  u^k | (R - x^k u W)      [linear constraints, via y = (v-1)/x]
  (ii) det J(F) == nonzero const [the Keller condition; quadratic in unknowns]
then solve.  k=3 = REDISCOVERY CONTROL (must find the owner's map + report the
solution family's dimension).  k=4 = THE HUNT (a solution would be a NEW
counterexample candidate of field degree 4).  k=2 = Campbell control (any
solution must be injective).  k=5 = parity probe (if k=4 empty).
"""
import sympy as sp
from sympy import symbols, expand, Rational, cancel, together, fraction, Poly, groebner, solve
import itertools, time

x, y, z, v = symbols('x y z v')
u = 1 + x*y

def run_k(k, Wdeg, Rmax, label):
    t0 = time.time()
    print(f"\n==== k = {k} ({label}): W total-deg <= {Wdeg}, R with x-deg <= {Rmax}, u-deg <= {Rmax} ====", flush=True)
    # unknowns
    wsyms = {}
    W = sp.Integer(0)
    for i in range(Wdeg + 1):
        for j in range(Wdeg + 1 - i):
            c = symbols(f'w_{i}_{j}')
            wsyms[(i, j)] = c
            W += c * x**i * y**j
    rsyms = {}
    R = sp.Integer(0)
    for m in range(Rmax + 1):
        for n in range(Rmax + 1):
            c = symbols(f'r_{m}_{n}')
            rsyms[(m, n)] = c
            R += c * x**m * u**n
    unknowns = list(wsyms.values()) + list(rsyms.values())
    print(f"  unknowns: {len(unknowns)}", flush=True)

    # (i) divisibility u^k | (R - x^k u W): substitute y = (v-1)/x, expand in v
    P = sp.expand(R - x**k * u * W)
    Pv = sp.together(P.subs(y, (v - 1)/x))
    num, den = sp.fraction(sp.cancel(Pv))
    num = sp.expand(num)
    # den is a power of x; condition: v^k | num  (u = v on the substituted curve family)
    lin_eqs = []
    pn = sp.Poly(num, v)
    for j in range(min(k, pn.degree() + 1)):
        cj = pn.nth(j)   # coefficient of v^j: polynomial in x, linear in unknowns
        for c_ in sp.Poly(cj, x).all_coeffs():
            if c_ != 0:
                lin_eqs.append(c_)
    lin_eqs = list(dict.fromkeys(lin_eqs))
    sol_lin = sp.solve(lin_eqs, unknowns, dict=True)
    if not sol_lin:
        if lin_eqs and all(e == 0 for e in lin_eqs):
            sub1 = {}
        else:
            print(f"  divisibility system: solve returned none; eqs = {len(lin_eqs)} -- treating as unsolvable", flush=True)
            return None
    else:
        sub1 = sol_lin[0]
    W1 = W.subs(sub1); R1 = R.subs(sub1)
    rem_unk = sorted((W1.free_symbols | R1.free_symbols) - {x, y}, key=str)
    print(f"  after divisibility: {len(rem_unk)} free parameters", flush=True)

    # build the map
    B1 = sp.expand(u * W1)
    B2 = sp.expand(y + k * x * W1)
    B3 = sp.cancel((R1 - x**k * u * W1) / u**k)
    B3n, B3d = sp.fraction(sp.together(B3))
    if B3d != 1:
        B3 = sp.cancel(sp.expand(B3n) / sp.expand(B3d))
        B3n, B3d = sp.fraction(B3)
        if B3d != 1:
            print(f"  WARNING: B3 not polynomial after constraints (den = {B3d}); aborting k={k}", flush=True)
            return None
    F1 = u**k * z + B1
    F2 = k * u**(k-1) * x * z + B2
    F3 = -x**k * z + B3
    J = sp.Matrix([F1, F2, F3]).jacobian([x, y, z])
    d = sp.expand(J.det())
    print(f"  det J computed [{time.time()-t0:.0f}s]; collecting Keller equations...", flush=True)
    dc = d - d.subs({x: 0, y: 0, z: 0})
    pd = sp.Poly(dc, x, y, z)
    eqs = [c_ for c_ in pd.coeffs() if c_ != 0]
    eqs = list(dict.fromkeys(eqs))
    print(f"  Keller system: {len(eqs)} equations in {len(rem_unk)} unknowns (quadratic)", flush=True)
    try:
        sols = sp.solve(eqs, rem_unk, dict=True)
    except Exception as e:
        print(f"  solve failed: {e}; trying groebner...", flush=True)
        try:
            G = sp.groebner(eqs, *rem_unk)
            print(f"  groebner basis size {len(G.exprs)}: {G.exprs[:6]}", flush=True)
            sols = sp.solve(list(G.exprs), rem_unk, dict=True)
        except Exception as e2:
            print(f"  groebner failed too: {e2}", flush=True)
            return None
    print(f"  solution branches: {len(sols)} [{time.time()-t0:.0f}s]", flush=True)
    good = []
    for so in sols:
        dval = sp.simplify(d.subs(so))
        Wv = sp.expand(W1.subs(so)); Rv = sp.expand(R1.subs(so))
        free = sorted(set().union(*[sp.sympify(t).free_symbols for t in ([dval, Wv, Rv])]) - {x, y, z, u.free_symbols and x}, key=str)
        free = [f_ for f_ in free if str(f_).startswith(('w_', 'r_'))]
        if dval.free_symbols - set(free):
            pass
        print(f"   branch: det = {dval}, dim(free params) = {len(free)}, W = {Wv}, R = {sp.factor(Rv)}", flush=True)
        if dval != 0:
            good.append((so, dval, Wv, Rv, free))
        else:
            # det == 0 identically or det depends on free params: check nonzero possible
            if dval.free_symbols:
                good.append((so, dval, Wv, Rv, free))
    print(f"  branches with det != 0 (or param-dependent): {len(good)}", flush=True)
    return dict(k=k, good=good, W1=W1, R1=R1, rem=rem_unk, tsec=time.time()-t0)

# ---- control k=3: must rediscover the owner's map ----
res3 = run_k(3, 4, 2, "REDISCOVERY CONTROL")
if res3:
    Wowner = sp.expand(y**2*(4 + 3*x*y)); Rowner = sp.expand(x*u + x*u**2)
    hit = False
    for so, dval, Wv, Rv, free in res3['good']:
        # try matching owner by substituting free params
        diffW = sp.expand(Wv - Wowner); diffR = sp.expand(Rv - Rowner)
        try:
            m = sp.solve([diffW, diffR], free, dict=True)
        except Exception:
            m = []
        if (diffW == 0 and diffR == 0) or m:
            hit = True
            print(f"  OWNER'S MAP FOUND in branch (det = {dval}); family dim here = {len(free)}", flush=True)
    print(f"  INSTRUMENT GATE: owner-map rediscovered = {hit}", flush=True)

# ---- the hunt k=4 ----
res4 = run_k(4, 5, 3, "THE HUNT")

# ---- Campbell control k=2 ----
res2 = run_k(2, 3, 2, "CAMPBELL CONTROL (solutions must be injective)")

# ---- parity probe k=5 (only if k=4 gave nothing nonzero) ----
if res4 is None or not res4['good']:
    res5 = run_k(5, 6, 3, "PARITY PROBE")

print("\nDONE.", flush=True)
