# P2 of THM-2446 section 5: does D5 = D4 = 0 plus S3 = 0 (C-free part of D3)
# force [w_x, w_y, w] = 0 identically, where w = A x B ?
#
# This script:
#   PART 1  proves the universal first-jet identity
#             [w_x,w_y,w] = [A,B,A_x][A,B,B_y] - [A,B,A_y][A,B,B_x]
#           on 18 independent jet symbols (proof-grade: both sides are
#           polynomial functions of the first jet only, and every first jet
#           is realized).
#   PART 2  exhibits a single first jet with D5 = D4 = S3 = 0 and E = 1,
#           killing every possible multiplier identity
#             E = P*(D5/2) + Q*D4 + R*S3  (any polynomial P,Q,R in any jets).
#   PART 3  THE COUNTEREXAMPLE: A = (x,1,0), B = (y,0,1).
#           D5 = D4 = S3 = 0 identically, E = [w_x,w_y,w] = 1. Refutes P2
#           and the weaker form (D5 = D4 = 0 alone) a fortiori.
#   PART 4  extends the counterexample to a FULL 2-jet Keller map:
#           C = (x*y - x**3 + x, 3*x**2 - 2*y, x) gives det J(F) = -2 for
#           F = A z^2 + B z + C; also computes the explicit polynomial
#           inverse (F is a tame automorphism).
#   PART 5  point-cap stratum (A = f*v): E = 0 with NO constraints at all.
#   PART 6  line-cap sub-stratum with B coplanar to A: E = 0.
#
# All checks are hard asserts; final line ALL CHECKS PASSED.

import sympy as sp

x, y, z = sp.symbols('x y z')

def V(pref):
    return sp.Matrix(3, 1, [sp.Symbol(pref + str(i)) for i in (1, 2, 3)])

def br(u, v, w):
    return sp.Matrix.hstack(u, v, w).det()

def cross(u, v):
    return sp.Matrix(3, 1, [u[1]*v[2] - u[2]*v[1],
                            u[2]*v[0] - u[0]*v[2],
                            u[0]*v[1] - u[1]*v[0]])

def D5h(A, Ax, Ay):                       # D5/2
    return br(Ax, Ay, A)

def D4f(A, Ax, Ay, B, Bx, By):
    return br(Ax, Ay, B) + 2*br(Ax, By, A) + 2*br(Bx, Ay, A)

def S3f(A, Ax, Ay, B, Bx, By):            # C-free part of D3
    return br(Ax, By, B) + br(Bx, Ay, B) + 2*br(Bx, By, A)

def Ef(A, Ax, Ay, B, Bx, By):             # [w_x, w_y, w],  w = A x B
    w  = cross(A, B)
    wx = cross(Ax, B) + cross(A, Bx)
    wy = cross(Ay, B) + cross(A, By)
    return br(wx, wy, w)

def PSQRf(A, Ax, Ay, B, Bx, By):
    P = br(A, B, Ax); Q = br(A, B, Ay)
    R = br(A, B, Bx); S = br(A, B, By)
    return P*S - Q*R

# ---------------------------------------------------------------- PART 1
A  = V('A');  B  = V('B')
Ax = V('Ax'); Ay = V('Ay')
Bx = V('Bx'); By = V('By')

lhs = Ef(A, Ax, Ay, B, Bx, By)
rhs = PSQRf(A, Ax, Ay, B, Bx, By)
assert sp.expand(lhs - rhs) == 0
print("PART 1: universal identity  [w_x,w_y,w] = [A,B,A_x][A,B,B_y]"
      " - [A,B,A_y][A,B,B_x]  on 18 free jet symbols: VERIFIED")

# ---------------------------------------------------------------- PART 2
jet = {}
for vec, val in ((A, (0, 1, 0)), (Ax, (1, 0, 0)), (Ay, (0, 0, 0)),
                 (B, (0, 0, 1)), (Bx, (0, 0, 0)), (By, (1, 0, 0))):
    for i in range(3):
        jet[vec[i]] = val[i]

d5 = D5h(A, Ax, Ay).subs(jet)
d4 = D4f(A, Ax, Ay, B, Bx, By).subs(jet)
s3 = S3f(A, Ax, Ay, B, Bx, By).subs(jet)
e  = Ef(A, Ax, Ay, B, Bx, By).subs(jet)
assert (d5, d4, s3) == (0, 0, 0) and e == 1
print("PART 2: jet A=(0,1,0), A_x=(1,0,0), A_y=0, B=(0,0,1), B_x=0,"
      " B_y=(1,0,0):")
print("        D5/2 = %s, D4 = %s, S3 = %s, but E = %s" % (d5, d4, s3, e))
print("        => E is NOT in the ideal (nor radical) generated by"
      " D5, D4, S3 in any jet ring;")
print("           no multiplier identity E = P*D5 + Q*D4 + R*S3 can exist.")

# ---------------------------------------------------------------- PART 3
Ac = sp.Matrix([x, sp.Integer(1), sp.Integer(0)])
Bc = sp.Matrix([y, sp.Integer(0), sp.Integer(1)])

def jets(M):
    return M, M.diff(x), M.diff(y)

Aa, Aax, Aay = jets(Ac)
Bb, Bbx, Bby = jets(Bc)

d5 = sp.expand(D5h(Aa, Aax, Aay))
d4 = sp.expand(D4f(Aa, Aax, Aay, Bb, Bbx, Bby))
s3 = sp.expand(S3f(Aa, Aax, Aay, Bb, Bbx, Bby))
w  = cross(Ac, Bc)
E  = sp.expand(br(w.diff(x), w.diff(y), w))
assert d5 == 0 and d4 == 0 and s3 == 0 and E == 1
print("PART 3: COUNTEREXAMPLE  A = (x, 1, 0),  B = (y, 0, 1):")
print("        D5/2 = %s, D4 = %s, S3 = %s identically" % (d5, d4, s3))
print("        w = A x B =", list(w))
print("        E = [w_x,w_y,w] =", E, " (nonzero constant)")
print("        => P2 REFUTED; the weaker form D5 = D4 = 0 alone is refuted"
      " a fortiori.")

# ---------------------------------------------------------------- PART 4
Cc = sp.Matrix([x*y - x**3 + x, 3*x**2 - 2*y, x])
F  = Ac*z**2 + Bc*z + Cc
J  = F.jacobian(sp.Matrix([x, y, z]))
detJ = sp.expand(J.det())
assert detJ == -2
print("PART 4: full Keller extension  C = (x*y - x**3 + x, 3*x**2 - 2*y, x):")
print("        F = A z^2 + B z + C =", list(F))
print("        det J(F) =", detJ, " (nonzero constant: F is a genuine 2-jet"
      " Keller map)")

# graded cross-check against THM-2446 (1)-(2)
Cx, Cy = Cc.diff(x), Cc.diff(y)
D5 = 2*br(Aax, Aay, Ac)
D4 = br(Aax, Aay, Bc) + 2*br(Aax, Bby, Ac) + 2*br(Bbx, Aay, Ac)
D3 = (br(Aax, Bby, Bc) + br(Bbx, Aay, Bc)
      + 2*(br(Aax, Cy, Ac) + br(Cx, Aay, Ac) + br(Bbx, Bby, Ac)))
D2 = (br(Bbx, Bby, Bc) + br(Aax, Cy, Bc) + br(Cx, Aay, Bc)
      + 2*(br(Bbx, Cy, Ac) + br(Cx, Bby, Ac)))
D1 = br(Bbx, Cy, Bc) + br(Cx, Bby, Bc) + 2*br(Cx, Cy, Ac)
D0 = br(Cx, Cy, Bc)
graded = [sp.expand(t) for t in (D5, D4, D3, D2, D1, D0)]
assert graded == [0, 0, 0, 0, 0, -2]
assert sp.expand(detJ - (D0 + D1*z + D2*z**2 + D3*z**3 + D4*z**4 + D5*z**5)) == 0
print("        graded slots (D5,...,D0) =", graded,
      " -- matches THM-2446 (1)-(2)")

# explicit inverse: from F3 = x + z and F2 = z^2 + 3x^2 - 2y
u1, u2, u3 = sp.symbols('u1 u2 u3')
zx = u3 - x                              # z in terms of u3 and x
yx = (zx**2 + 3*x**2 - u2)/2             # y in terms of u2, u3, x
e1 = sp.expand(F[0].subs({z: zx, y: yx}) - u1)
assert sp.degree(sp.Poly(e1, x), x) == 1
xsol = sp.solve(e1, x)[0]
ysol = sp.expand(yx.subs(x, xsol))
zsol = sp.expand(zx.subs(x, xsol))
G = sp.Matrix([xsol, ysol, zsol])
back = sp.expand(G.subs({u1: F[0], u2: F[1], u3: F[2]}, simultaneous=True))
assert list(back) == [x, y, z]
print("        explicit polynomial inverse verified: G o F = id, with")
print("          x =", sp.factor(xsol))
print("        => F is a (tame) polynomial automorphism with det J = -2,")
print("           yet its plane map w = A x B has [w_x,w_y,w] = 1.")

# ---------------------------------------------------------------- PART 5
f, fx, fy = sp.symbols('f fx fy')          # first jet of a scalar f
vv = V('v')                                # constant direction vector
Ap, Apx, Apy = f*vv, fx*vv, fy*vv          # first jet of A = f*v
e_point = Ef(Ap, Apx, Apy, B, Bx, By)
assert sp.expand(e_point) == 0
print("PART 5: point cap A = f*v (rank-1 A): E = 0 identically for ARBITRARY"
      " B, no constraints needed: VERIFIED")

# ---------------------------------------------------------------- PART 6
A2  = sp.Matrix([sp.Symbol('A1'),  sp.Symbol('A2'),  0])
A2x = sp.Matrix([sp.Symbol('Ax1'), sp.Symbol('Ax2'), 0])
A2y = sp.Matrix([sp.Symbol('Ay1'), sp.Symbol('Ay2'), 0])
B2  = sp.Matrix([sp.Symbol('B1'),  sp.Symbol('B2'),  0])
B2x = sp.Matrix([sp.Symbol('Bx1'), sp.Symbol('Bx2'), 0])
B2y = sp.Matrix([sp.Symbol('By1'), sp.Symbol('By2'), 0])
e_plane = Ef(A2, A2x, A2y, B2, B2x, B2y)
assert sp.expand(e_plane) == 0
print("PART 6: A and B both valued in a common plane: E = 0 identically:"
      " VERIFIED")

print("ALL CHECKS PASSED")
