#!/usr/bin/env python3
"""Exact companion for THM-3695.

This script verifies the bracket-compatible collision-ring embedding into the
squarefree exponent-two Danielewski Poisson surface and mechanically checks the support
partition corollary of THM-3569/3583/3592.  The universal support theorems are
proved in their own cited files; this companion does not re-prove them.
"""

from __future__ import annotations

import ast
import hashlib
from pathlib import Path

import sympy as sp


CHECKS = 0


def require(condition: bool, detail: object) -> None:
    global CHECKS
    CHECKS += 1
    if not condition:
        raise RuntimeError(detail)


def source_bracket(first: sp.Expr, second: sp.Expr, x: sp.Symbol, z: sp.Symbol) -> sp.Expr:
    return sp.expand(
        sp.diff(first, x) * sp.diff(second, z)
        - sp.diff(first, z) * sp.diff(second, x)
    )


def main() -> None:
    x, z = sp.symbols("x z")
    beta = 1 - x**2 * z
    c = x
    e = sp.expand(z * (2 - x**2 * z))
    sigma = 1 - beta**2

    A = sp.expand(3 * z * (2 - x**2 * z))
    B = sp.expand(2 * x * z * (2 - x**2 * z))
    C = sp.expand(x * (1 - x**2 * z))

    # The Danielewski equation and Poisson structure survive literally under
    # beta -> 1-x^2 z, c -> x, e -> z(2-x^2 z).
    require(sp.expand(c**2 * e - sigma) == 0, "Danielewski equation")
    require(source_bracket(beta, c, x, z) == c**2, "{beta,c}")
    require(source_bracket(c, e, x, z) == 2 * beta, "{c,e}")
    require(sp.expand(source_bracket(beta, e, x, z) + 2 * c * e) == 0, "{beta,e}")

    # The collision ring is the graded subalgebra generated by these three
    # homogeneous elements.  It need not be closed under the ambient bracket;
    # bracket compatibility of D with the source is the property used below.
    require(sp.expand(A - 3 * e) == 0, "A=3e")
    require(sp.expand(B - 2 * c * e) == 0, "B=2ce")
    require(sp.expand(C - beta * c) == 0, "C=beta*c")
    require(
        sp.expand(16 * A**3 * C**2 + 27 * B**4 - 36 * A * B**2) == 0,
        "collision-ring hypersurface relation",
    )
    weights = {"beta": 0, "c": 1, "e": -2, "A": -2, "B": -1, "C": 1}
    require(
        (weights["A"], weights["B"], weights["C"]) == (-2, -1, 1),
        "grading",
    )

    # The source collision is retained by every element of C[A,B,C].
    collision_left = tuple(value.subs({x: 1, z: 0}) for value in (A, B, C))
    collision_right = tuple(value.subs({x: -1, z: 2}) for value in (A, B, C))
    require(collision_left == collision_right == (0, 0, 1), "retained collision")

    # Sigma is the squarefree quadratic required by the universal theorems.
    T = sp.symbols("T")
    sigma_abstract = 1 - T**2
    require(sp.degree(sigma_abstract, T) == 2, "degree of Sigma")
    require(sp.gcd(sigma_abstract, sp.diff(sigma_abstract, T)) == 1, "Sigma squarefree")

    # Corollary ledger.  THM-3569 closes a one-piece output and 2x3;
    # THM-3583 closes 2x4; THM-3592 closes 3x3.  Hence every positive support
    # partition of total at most six is excluded, and the first unevaluated
    # total-seven partitions are 2x5 and 3x4, up to output exchange.
    def gate(first: int, second: int) -> str:
        low, high = sorted((first, second))
        if low == 1:
            return "THM-3569-one-by-arbitrary"
        if low == 2 and high <= 3:
            return "THM-3569-two-by-three"
        if low == 2 and high == 4:
            return "THM-3583-two-by-four"
        if low == high == 3:
            return "THM-3592-three-by-three"
        return "OPEN-BY-THIS-COROLLARY"

    closed = []
    for total in range(2, 7):
        for first in range(1, total):
            second = total - first
            certificate = gate(first, second)
            require(certificate != "OPEN-BY-THIS-COROLLARY", (first, second))
            closed.append(f"{first}x{second}:{certificate}")

    total_seven = [(first, 7 - first, gate(first, 7 - first)) for first in range(1, 7)]
    survivors = [(first, second) for first, second, result in total_seven if result == "OPEN-BY-THIS-COROLLARY"]
    require(survivors == [(2, 5), (3, 4), (4, 3), (5, 2)], "total-seven frontier")

    source = Path(__file__).read_text(encoding="utf-8")
    require(
        not any(isinstance(node, ast.Assert) for node in ast.walk(ast.parse(source))),
        "inactive Python assert found",
    )

    semantic_rows = [
        "embedding:beta=1-x^2z,c=x,e=z(2-x^2z)",
        "relation:c^2e=1-beta^2",
        "brackets:{beta,c}=c^2;{c,e}=2beta;{beta,e}=-2ce",
        "subalgebra:A=3e;B=2ce;C=beta*c",
        "collision:(1,0),(-1,2)->(0,0,1)",
        *closed,
        "total-seven-survivors=2x5,3x4,4x3,5x2",
    ]
    semantic_hash = hashlib.sha256("\n".join(semantic_rows).encode()).hexdigest()

    print("theorem=THM-3695-y0-collision-danielewski-embedding")
    print("ambient=D=C[beta,c,e]/(c^2*e-(1-beta^2));Sigma=1-beta^2;squarefree_degree=2")
    print("embedding=beta->1-x^2*z;c->x;e->z*(2-x^2*z)")
    print("poisson={beta,c}=c^2;{c,e}=2*beta;{beta,e}=-2*c*e")
    print("collision_ring=R=C[A,B,C]=C[3e,2ce,beta*c] graded_subalgebra_of_D")
    print("grading=wt(beta,c,e)=(0,1,-2);wt(A,B,C)=(-2,-1,1)")
    print("retained_collision=(1,0),(-1,2)->(A,B,C)=(0,0,1)")
    print("support_floor=7;dependencies=THM-3569,THM-3583,THM-3592")
    print("first_unevaluated_partitions_up_to_swap=2x5,3x4")
    print(f"semantic_sha256={semantic_hash}")
    print(f"CHECKS={CHECKS}")
    print("RESULT=PASS")


if __name__ == "__main__":
    main()
