#!/usr/bin/env python3
"""Exact companion for THM-3754's affine-variable classification."""

from __future__ import annotations

import ast
import hashlib
from itertools import product
from pathlib import Path

import sympy as sp


CHECKS = 0


def gate(condition: bool, message: str) -> None:
    global CHECKS
    CHECKS += 1
    if not condition:
        raise RuntimeError(message)


X, T = sp.symbols("X T")


def jac(first: sp.Expr, second: sp.Expr) -> sp.Expr:
    return sp.expand(
        sp.diff(first, X) * sp.diff(second, T)
        - sp.diff(first, T) * sp.diff(second, X)
    )


def is_zero(expression: sp.Expr) -> bool:
    return sp.expand(expression) == 0


def predicted_nonsingular(f: sp.Expr, g: sp.Expr) -> bool:
    """The exact algebraically closed criterion in THM-3754."""
    f_poly = sp.Poly(sp.expand(f), X, domain=sp.QQ)
    g_poly = sp.Poly(sp.expand(g), X, domain=sp.QQ)
    if g_poly.is_zero:
        derivative = sp.Poly(sp.diff(f_poly.as_expr(), X), X, domain=sp.QQ)
        return derivative.degree() == 0 and not derivative.is_zero
    if g_poly.degree() == 0:
        return True
    derivative_g = sp.Poly(sp.diff(g_poly.as_expr(), X), X, domain=sp.QQ)
    radical = sp.exquo(g_poly, sp.gcd(g_poly, derivative_g))
    all_roots_multiple = sp.rem(derivative_g, radical).is_zero
    derivative_f = sp.Poly(sp.diff(f_poly.as_expr(), X), X, domain=sp.QQ)
    avoids_f_derivative = sp.gcd(g_poly, derivative_f).degree() == 0
    return all_roots_multiple and avoids_f_derivative


# The top-T coefficient is a logarithmic-derivative equation at every depth.
f_function = sp.Function("f")(X)
g_function = sp.Function("g")(X)
for depth in range(1, 8):
    coefficient_functions = [
        sp.Function(f"p_{depth}_{index}")(X)
        for index in range(depth + 1)
    ]
    prospective = sum(
        coefficient_functions[index] * T**index
        for index in range(depth + 1)
    )
    component = f_function + T * g_function
    top = sp.expand(jac(prospective, component)).coeff(T, depth)
    expected = (
        g_function * sp.diff(coefficient_functions[depth], X)
        - depth * sp.diff(g_function, X) * coefficient_functions[depth]
    )
    gate(sp.simplify(top - expected) == 0, "universal top-T descent equation")
    replacement = sp.Symbol(f"lambda_{depth}") * g_function**depth
    gate(
        sp.simplify(expected.subs(coefficient_functions[depth], replacement))
        == 0,
        "kernel is generated by the top coefficient of Q^N",
    )
    gate(sp.simplify(jac(component**depth, component)) == 0,
         "subtracting a power of Q preserves the Jacobian equation")

# Euclidean division is the exact triangular-source normal form.  The
# derivative sidecar is unchanged on a multiple root of g.
normal_form_checks = 0
for f_value, g_value in (
    (1 + 2 * X + 3 * X**2 + 5 * X**4, X**3),
    (2 - X + X**3 + X**5, (X**2 - 1) ** 2),
    (X + 4 * X**2 - 2 * X**5, X**2 * (X - 1) ** 2),
):
    quotient, remainder = sp.div(f_value, g_value, domain=sp.QQ)
    gate(
        sp.expand(f_value + T * g_value - (remainder + (T + quotient) * g_value))
        == 0,
        "Euclidean source-shear normal form",
    )
    derivative_difference = sp.expand(sp.diff(f_value - remainder, X))
    gate(
        sp.expand(
            derivative_difference
            - sp.diff(quotient, X) * g_value
            - quotient * sp.diff(g_value, X)
        )
        == 0,
        "derivative residue identity",
    )
    normal_form_checks += 1

# Exhaust all coefficient vectors of degree at most three over {-1,0,1}.
# A direct two-variable Groebner unit-ideal test agrees with the root criterion.
values = (-1, 0, 1)
grid_total = 0
grid_nonsingular = 0
grid_predicted = 0
for f_coefficients in product(values, repeat=4):
    f_value = sum(f_coefficients[index] * X**index for index in range(4))
    for g_coefficients in product(values, repeat=4):
        g_value = sum(g_coefficients[index] * X**index for index in range(4))
        component = sp.expand(f_value + T * g_value)
        critical_ideal = sp.groebner(
            (sp.diff(component, X), sp.diff(component, T)), X, T, order="lex"
        )
        nonsingular = critical_ideal.contains(sp.Integer(1))
        predicted = predicted_nonsingular(f_value, g_value)
        gate(nonsingular == predicted, "degree-three affine-variable classification")
        grid_total += 1
        grid_nonsingular += int(nonsingular)
        grid_predicted += int(predicted)

# Boundary examples: the quartic is the first Euclidean residue not reducible
# to the monomial Broughton family when g is a pure power.
smooth_examples = (
    X + X**2 * T,
    X + X**2 + X**3 * T,
    X + T * (X**2 - 1) ** 2,
    X**2 + T,
)
singular_examples = (
    X + T * (X**2 - 1),
    X**2 + X**2 * T,
    X**2,
)
for component in smooth_examples:
    critical_ideal = sp.groebner(
        (sp.diff(component, X), sp.diff(component, T)), X, T, order="lex"
    )
    gate(critical_ideal.contains(sp.Integer(1)), "smooth boundary control")
for component in singular_examples:
    critical_ideal = sp.groebner(
        (sp.diff(component, X), sp.diff(component, T)), X, T, order="lex"
    )
    gate(not critical_ideal.contains(sp.Integer(1)), "singular boundary control")

# Finite mate systems guard the exact descent on three nonconstant-g smooth
# controls.  The theorem itself is all-degree because the T-degree decreases.
mate_obstructions = 0
for component in smooth_examples[:3]:
    for bound in range(0, 8):
        basis = [
            X**i * T**j
            for i in range(bound + 1)
            for j in range(bound + 1 - i)
        ]
        coefficients = sp.symbols(
            f"mate_{mate_obstructions}_0:{len(basis)}"
        )
        prospective = sum(
            coefficient * monomial
            for coefficient, monomial in zip(coefficients, basis)
        )
        equation = sp.Poly(jac(prospective, component) - 1, X, T)
        system = [coefficient for _, coefficient in equation.terms()]
        gate(
            sp.linsolve(system, coefficients) == sp.EmptySet,
            "finite nonconstant-g mate obstruction",
        )
        mate_obstructions += 1

# Positive controls for both coordinate boundaries.
for f_value, g_value in ((X**5 + 2 * X + 1, 3), (2 * X - 7, 0)):
    component = f_value + T * g_value
    mate = X / g_value if g_value else -T / 2
    gate(sp.expand(jac(mate, component) - 1) == 0,
         "constant-g or linear-zero-g positive mate")

semantic_rows = (
    "smooth:g_constant_nonzero_or_g_zero_f_affine_or_every_g_root_multiple_and_avoids_fprime",
    "mate:g_constant_nonzero_or_g_zero_f_affine",
    "descent:g*pNprime-N*gprime*pN=0;pN=lambda*g^N;subtract_lambda*Q^N",
    "normal_form:f_mod_g;minimal_nonradial=X+X^2+X^3*T",
)
semantic = hashlib.sha256("\n".join(semantic_rows).encode()).hexdigest()

source = Path(__file__).read_text(encoding="utf-8")
gate(
    not any(isinstance(node, ast.Assert) for node in ast.walk(ast.parse(source))),
    "inactive Python assert",
)

print("theorem=THM-3754-affine-variable-Euclidean-descent-classification")
print("scope=algebraically_closed_characteristic_zero;arbitrary_f,g_in_k[X]")
print("nonsingular=rootwise_multiple_g_and_fprime_avoidance_with_constant_boundaries")
print("jacobian_mate=iff_g_nonzero_constant_or_g_zero_and_f_affine_nonconstant")
print("mechanism=top_T_logarithmic_derivative_and_subtract_powers_of_Q")
print("normal_form=f_mod_g_under_triangular_source_shear")
print(
    f"degree_three_grid={grid_total};nonsingular={grid_nonsingular};"
    f"predicted={grid_predicted}"
)
print(
    f"normal_forms={normal_form_checks};smooth_controls={len(smooth_examples)};"
    f"singular_controls={len(singular_examples)};mate_obstructions={mate_obstructions}"
)
print(f"semantic_sha256={semantic}")
print(f"CHECKS={CHECKS}")
print("RESULT=PASS")
