#!/usr/bin/env python3
"""Independent exact audit for THM-3868.

This companion deliberately reconstructs the fixed-seed barrier from a
different direction than the primary script.  It checks the cubic cover by
elimination/resultants, verifies that the Russell generator bracket descends
through its defining equation, compares direct and convolutional formal
density coefficients, and audits the genuinely mixed hostile in the Laurent
UFD where its pole divisor lives.

The two non-computational inputs are explicitly isolated: smoothness implies
normality for the Russell ring, and THM-3785 proves B^*=k^*.  All assertions
remain active under ``python -O``.
"""

from __future__ import annotations

import hashlib

import sympy as sp


CHECKS = 0


def require(label: str, condition: object) -> None:
    """Optimization-safe exact assertion."""

    global CHECKS
    CHECKS += 1
    if condition is True or condition == sp.S.true:
        return
    if isinstance(condition, sp.Basic) and sp.simplify(condition) == 0:
        return
    raise RuntimeError(f"CHECK FAILED: {label}: {condition}")


def require_zero(label: str, expression: sp.Expr) -> None:
    require(label, sp.cancel(sp.factor(expression)) == 0)


def jac(left: sp.Expr, right: sp.Expr, first: sp.Symbol, second: sp.Symbol) -> sp.Expr:
    """Jacobian in the coordinate order (first, second)."""

    return sp.factor(
        sp.diff(left, first) * sp.diff(right, second)
        - sp.diff(left, second) * sp.diff(right, first)
    )


# ---------------------------------------------------------------------------
# I. Reconstruct the fixed nodal seed as an exact monogenic cubic cover.
# ---------------------------------------------------------------------------

c = sp.symbols("c", nonzero=True)
S, Z, T = sp.symbols("S Z T")
Aind, Cind = sp.symbols("Aind Cind")
w0 = 1 / (2 * c**3)

A0 = 9 * c**6 * S**2 - Z / (3 * c**3)
C0 = 27 * c**9 * S**3 - 3 * c**3 * S - sp.Rational(3, 2) * S * Z

require_zero("seed Jacobian density", jac(A0, C0, Z, S) - (1 + w0 * Z))
require_zero("polynomial recovery of Z", (27 * c**9 * S**2 - 3 * c**3 * A0) - Z)

p = (2 - 3 * Aind) / (9 * c**6)
q = 2 * Cind / (27 * c**9)
f = T**3 + p * T + q
f_on_seed = f.subs({T: S, Aind: A0, Cind: C0})
require_zero("monic cubic vanishes on seed", f_on_seed)

# Compute the discriminant two independent ways: the library discriminant and
# the signed resultant.  For a monic cubic Disc(f)=-Res(f,f').
disc_formula = -4 * ((2 - 3 * Aind) ** 3 + 27 * Cind**2) / (729 * c**18)
disc_direct = sp.factor(sp.discriminant(f, T))
disc_resultant = sp.factor(-sp.resultant(f, sp.diff(f, T), T))
require_zero("cubic discriminant formula", disc_direct - disc_formula)
require_zero("discriminant equals signed resultant", disc_resultant - disc_formula)

fprime_seed = sp.diff(f, T).subs({T: S, Aind: A0})
require_zero(
    "power-basis derivative is scalar seed Jacobian",
    fprime_seed - 2 * (1 + w0 * Z) / (9 * c**6),
)
require_zero(
    "power-basis derivative has linear Z factor",
    fprime_seed - (Z + 2 * c**3) / (9 * c**9),
)

# At the derivative divisor Z=-2c^3, eliminate S and recover the cusp image.
Abranch = sp.factor(A0.subs(Z, -2 * c**3))
Cbranch = sp.factor(C0.subs(Z, -2 * c**3))
require_zero("ramification line maps into cusp", (3 * Abranch - 2) ** 3 - 27 * Cbranch**2)
branch_elimination = sp.factor(
    sp.resultant(
        3 * Aind - 3 * Abranch,
        Cind - Cbranch,
        S,
    )
)
require_zero(
    "resultant recovers cusp equation up to its scalar",
    branch_elimination
    - 729 * c**18 * ((3 * Aind - 2) ** 3 - 27 * Cind**2),
)

# SymPy's exact QQ(p,q) factor test supplies a computational hostile check on
# the valuation proof that T^3+pT+q has no rational root.
pp, qq = sp.symbols("pp qq")
generic_cubic = sp.Poly(
    T**3 + pp * T + qq,
    T,
    domain=sp.QQ.frac_field(pp, qq),
)
require("generic depressed cubic irreducible", generic_cubic.is_irreducible is True)
for order in range(-12, 13):
    valuations = (3 * order, order, -1)
    require(
        f"q-infinity minimum unique at root order {order}",
        valuations.count(min(valuations)) == 1,
    )


# ---------------------------------------------------------------------------
# II. Independently descend the Poisson bracket to the Russell ring.
# ---------------------------------------------------------------------------

r, z, e = sp.symbols("r z e")
F = r**2 * e - z**3 + c**3 * r


def russell_bracket(left: sp.Expr, right: sp.Expr) -> sp.Expr:
    """Biderivation generated by the Russell Poisson packet."""

    rz = 3 * r**2
    re = 9 * z**2
    ze = 3 * c**3 + 6 * e * r
    return sp.factor(
        rz * (sp.diff(left, r) * sp.diff(right, z) - sp.diff(left, z) * sp.diff(right, r))
        + re * (sp.diff(left, r) * sp.diff(right, e) - sp.diff(left, e) * sp.diff(right, r))
        + ze * (sp.diff(left, z) * sp.diff(right, e) - sp.diff(left, e) * sp.diff(right, z))
    )


require_zero("packet bracket r,z", russell_bracket(r, z) - 3 * r**2)
require_zero("packet bracket r,e", russell_bracket(r, e) - 9 * z**2)
require_zero("packet bracket z,e", russell_bracket(z, e) - (3 * c**3 + 6 * e * r))
for generator in (r, z, e):
    require_zero(f"defining ideal is Poisson for {generator}", russell_bracket(F, generator))

# A second derivation uses the rational arm chart with {z,s}=1.
s = sp.symbols("s")
den = c**3 + 3 * s * z**3
r_chart = z**3 / den
e_chart = 3 * c**3 * s + 9 * s**2 * z**3
require_zero("arm chart lies on Russell surface", F.subs({r: r_chart, e: e_chart}))
require_zero("arm identity er=3sz^3", e_chart * r_chart - 3 * s * z**3)
require_zero("chart bracket r,z", jac(r_chart, z, z, s) - 3 * r_chart**2)
require_zero("chart bracket r,e", jac(r_chart, e_chart, z, s) - 9 * z**2)
require_zero(
    "chart bracket z,e",
    jac(z, e_chart, z, s) - (3 * c**3 + 6 * e_chart * r_chart),
)

# Smoothness has a one-line exact certificate: dF/de=0 and dF/dz=0 force
# r=z=0, where dF/dr=c^3 is nonzero.  Normality and the unit calculation are
# theorem inputs, but the divisor identity used by the latter is checked.
dFr, dFz, dFe = (sp.diff(F, variable) for variable in (r, z, e))
require_zero("partial F/e", dFe - r**2)
require_zero("partial F/z", dFz + 3 * z**2)
require_zero("partial F/r on r=z=0", dFr.subs({r: 0, z: 0}) - c**3)
require_zero("triple-arm divisor identity", r * (c**3 + r * e) - z**3 - F)


# ---------------------------------------------------------------------------
# III. Direct formal rows versus an independently coded convolution formula.
# ---------------------------------------------------------------------------

w = sp.symbols("w", nonzero=True)
u, v, p5, q6, t7 = [sp.Function(name)(s) for name in ("uu", "vv", "pp", "qq6", "tt")]
h, k3, ell, m5, n6 = [sp.Function(name)(s) for name in ("hh", "kk", "ll", "mm", "nn")]

Zshort = z - w * z**2 / 2 + u * z**3 + v * z**4 + p5 * z**5 + q6 * z**6 + t7 * z**7
Sshort = s + h * z**2 + k3 * z**3 + ell * z**4 + m5 * z**5 + n6 * z**6
Dshort = sp.expand((1 + w * Zshort) * jac(Zshort, Sshort, z, s) - 1)

expected_rows = {
    2: 3 * u + sp.diff(h, s) - 3 * w**2 / 2,
    3: 4 * v + sp.diff(k3, s) + 4 * w * u + w**3 / 2,
    4: (
        5 * p5
        + sp.diff(ell, s)
        + 5 * w * v
        - 5 * w**2 * u / 2
        + (3 * u - 3 * w**2 / 2) * sp.diff(h, s)
        - 2 * h * sp.diff(u, s)
    ),
    5: (
        6 * q6
        + sp.diff(m5, s)
        - 3 * w**2 * v
        + 6 * w * p5
        + 3 * w * u**2
        + (3 * u - 3 * w**2 / 2) * sp.diff(k3, s)
        - (2 * w * h + 3 * k3) * sp.diff(u, s)
        + (w**3 / 2 + 4 * w * u + 4 * v) * sp.diff(h, s)
        - 2 * h * sp.diff(v, s)
    ),
    6: (
        7 * t7
        + sp.diff(n6, s)
        - 7 * w**2 * p5 / 2
        + 7 * w * q6
        + 7 * w * u * v
        + (3 * u - 3 * w**2 / 2) * sp.diff(ell, s)
        - (2 * w * h + 3 * k3) * sp.diff(v, s)
        + (w**3 / 2 + 4 * w * u + 4 * v) * sp.diff(k3, s)
        + (w**2 * h - 3 * w * k3 - 4 * ell) * sp.diff(u, s)
        + (-5 * w**2 * u / 2 + 5 * w * v + 5 * p5) * sp.diff(h, s)
        - 2 * h * sp.diff(p5, s)
    ),
}

require_zero("formal density z^0", Dshort.coeff(z, 0))
require_zero("formal density z^1", Dshort.coeff(z, 1))
for degree, row in expected_rows.items():
    require_zero(f"displayed mixed row E{degree}", Dshort.coeff(z, degree) - row)

# Generic independent coefficient engine.  J_n is assembled from the two
# convolution sums before multiplication by 1+wZ.
N = 10
aa = [sp.Integer(0), sp.Integer(1)] + [sp.Function(f"a{i}")(s) for i in range(2, N + 2)]
bb = [s, sp.Integer(0)] + [sp.Function(f"b{i}")(s) for i in range(2, N + 1)]
Zgeneric = sum(aa[i] * z**i for i in range(1, N + 2))
Sgeneric = sum(bb[j] * z**j for j in range(0, N + 1))
Dgeneric = sp.expand((1 + w * Zgeneric) * jac(Zgeneric, Sgeneric, z, s))


def jac_coefficient(degree: int) -> sp.Expr:
    total = sp.Integer(0)
    for i in range(1, degree + 2):
        j = degree + 1 - i
        if 0 <= j < len(bb):
            total += i * aa[i] * sp.diff(bb[j], s) - j * sp.diff(aa[i], s) * bb[j]
    return sp.expand(total)


def density_coefficient(degree: int) -> sp.Expr:
    total = jac_coefficient(degree)
    for i in range(1, degree + 1):
        total += w * aa[i] * jac_coefficient(degree - i)
    return sp.expand(total)


for degree in range(0, 9):
    direct = sp.expand(Dgeneric).coeff(z, degree)
    convolved = density_coefficient(degree)
    require_zero(f"direct/convolution row {degree}", direct - convolved)
    if degree >= 2:
        require(
            f"row {degree} coefficient of new normal variable",
            sp.diff(convolved, aa[degree + 1]) == degree + 1,
        )
        require(
            f"row {degree} coefficient of new tangent derivative",
            sp.diff(convolved, sp.diff(bb[degree], s)) == 1,
        )


# ---------------------------------------------------------------------------
# IV. A genuinely mixed exact rational hostile and its unavoidable divisor.
# ---------------------------------------------------------------------------

eta = sp.symbols("eta", nonzero=True)
D = 1 - eta * s * z**2
x = z / D**2
y = s * D**3
require_zero("mixed Hamiltonian precursor is symplectic", jac(x, y, z, s) - 1)

H = D**2 + w * z / 2
G = D**2 + 3 * w * z / 2
Zm = z / H
Sm = s * H**3 / (D * G)
require_zero("mixed control equals vertical control in x", Zm - x / (1 + w * x / 2))
require_zero(
    "mixed S equals vertical control in x,y",
    Sm - y * (1 + w * x / 2) ** 3 / (1 + 3 * w * x / 2),
)
require_zero("mixed weighted density", (1 + w * Zm) * jac(Zm, Sm, z, s) - 1)

Zjet = sp.series(Zm, z, 0, 6).removeO().expand()
Sjet = sp.series(Sm, z, 0, 5).removeO().expand()
expected_Zjet = (
    z
    - w * z**2 / 2
    + (w**2 / 4 + 2 * eta * s) * z**3
    - (w**3 / 8 + 2 * eta * w * s) * z**4
    + (w**4 / 16 + 3 * eta * w**2 * s / 2 + 3 * eta**2 * s**2) * z**5
)
expected_Sjet = (
    s
    + (3 * w**2 * s / 4 - 3 * eta * s**2) * z**2
    - w**3 * s * z**3
    + (3 * w**4 * s / 2 + 3 * eta * w**2 * s**2 / 4 + 3 * eta**2 * s**3) * z**4
)
require_zero("mixed Z jet through order five", Zjet - expected_Zjet)
require_zero("mixed S jet through order four", Sjet - expected_Sjet)
require("mixed derivative absent below z^3", sp.diff(Zjet.coeff(z, 2), s) == 0)
require("mixed derivative nonzero at z^3", sp.diff(Zjet.coeff(z, 3), s) == 2 * eta)
require_zero(
    "mixed jet satisfies first formal row",
    expected_rows[2].subs(
        {
            u: Zjet.coeff(z, 3),
            h: Sjet.coeff(z, 2),
            sp.diff(h, s): sp.diff(Sjet.coeff(z, 2), s),
        }
    ),
)

# Directly differentiate the composite seed as an independent chain-rule
# hostile.  The nodal value w=1/(2c^3) is imposed only at the final step.
Am = A0.subs({S: Sm, Z: Zm})
Cm = C0.subs({S: Sm, Z: Zm})
require_zero("genuinely mixed nodal composite is rational Keller", jac(Am, Cm, z, s).subs(w, w0) - 1)

# Move to B_{rz}=k[r^+-1,z^+-1].  Here all denominators used to clear H are
# Laurent units, so an irreducible factor of N is a genuine height-one prime.
s_torus = (z**3 - c**3 * r) / (3 * r * z**3)
dtilde = 3 * r * z + eta * c**3 * r - eta * z**3
Neta = sp.expand(4 * c**3 * dtilde**2 + 9 * r**2 * z**3)
H_torus = sp.factor(H.subs({s: s_torus, w: w0}))
require_zero(
    "Laurent clearing identity for moved H divisor",
    H_torus - Neta / (36 * c**3 * r**2 * z**2),
)

Npoly = sp.Poly(Neta, r, z, domain=sp.QQ.frac_field(c, eta))
require("moved divisor numerator has multiple Laurent monomials", len(Npoly.terms()) > 1)
require_zero("Neta at r=0 has nonzero z^6 term", Neta.subs(r, 0) - 4 * c**3 * eta**2 * z**6)
require_zero("Neta at z=0 has nonzero r^2 term", Neta.subs(z, 0) - 4 * eta**2 * c**9 * r**2)

domain = sp.QQ.frac_field(c, eta)


def gcd_is_one(label: str, left: sp.Expr, right: sp.Expr) -> None:
    common = sp.gcd(sp.Poly(left, r, z, domain=domain), sp.Poly(right, r, z, domain=domain))
    require(label, common.total_degree() == 0)


gcd_is_one("H divisor avoids D", Neta, dtilde)
Gnumerator = sp.expand(Neta + 18 * r**2 * z**3)
gcd_is_one("H divisor avoids G", Neta, Gnumerator)
s_numerator = z**3 - c**3 * r
gcd_is_one("H divisor avoids s", Neta, s_numerator)
require_zero("H restricted to s=0", H.subs(s, 0) - (1 + w * z / 2))
require_zero("vertical specialization of moved divisor", Neta.subs(eta, 0) - 9 * r**2 * z**2 * (z + 4 * c**3))

# The valuation conclusion is represented by an exact principal-part split:
# the S^2 term has H-order +6, while -Z/(3c^3) has H-order -1.
require_zero(
    "mixed A principal-part decomposition",
    Am - 9 * c**6 * s**2 * H**6 / (D**2 * G**2) + z / (3 * c**3 * H),
)

# The density can be linearized, but integral recovery is the non-discardable
# sidecar: Tcontrol must remain divisible by 1+wZ in B.
Zfun = sp.Function("Zfun")(z, s)
Sfun = sp.Function("Sfun")(z, s)
Tcontrol = (1 + w * Zfun) * Sfun
require_zero(
    "weighted density linearization",
    jac(Zfun, Tcontrol, z, s) - (1 + w * Zfun) * jac(Zfun, Sfun, z, s),
)


SEMANTIC_FACTS = "\n".join(
    [
        "audit=independent-fixed-nodal-seed-barrier",
        "seed-cover=finite-monic-generic-degree-three",
        "recovery=S-integral-then-Z-polynomial",
        "different=fprime=scalar-times-1-plus-Z-over-2c3",
        "normality=input=THM-3785-smooth-Russell-ring",
        "poisson-closure=verified-by-ideal-and-arm-chart",
        "unit-input=B-star-equals-k-star",
        "contradiction=unit-density-forces-Z-constant",
        "formal-rows=direct-and-convolution-through-order-eight",
        "formal-recursion=one-free-polynomial-per-order",
        "mixed-hostile=exact-Zs-begins-order-three",
        "mixed-pole=nonunit-Laurent-divisor-avoids-D-G-s-r-z",
        "scope=fixed-seed-rational-controls-only",
        "not-covered=different-seed-algebraic-control-arbitrary-Darboux-pair",
        "jc2=open",
    ]
)
semantic_sha256 = hashlib.sha256(SEMANTIC_FACTS.encode("utf-8")).hexdigest()

print("THM-3868 INDEPENDENT FIXED-NODAL-SEED BARRIER AUDIT")
print("MONIC_RECOVERY=PASS;GENERIC_CUBIC=IRREDUCIBLE;DIFFERENT=PASS")
print("NORMALITY_INPUT=THM-3785;POISSON_CLOSURE=PASS;UNIT_TRAP=PASS")
print("FORMAL_ROWS=PASS;DIRECT_CONVOLUTION_ORDERS=0..8;NEW_PAIR_AFFINE")
print("GENUINELY_MIXED_HOSTILE=PASS;FIRST_ZS_ORDER=3;LAURENT_POLE=PASS")
print("SCOPE=FIXED_SEED_RATIONAL_PRECOMPOSITION_ONLY;DIFFERENT_SEED_OPEN;JC2_OPEN")
print(f"SEMANTIC_SHA256={semantic_sha256}")
print(f"CHECKS={CHECKS}")
print("ALL INDEPENDENT CHECKS PASSED")
