#!/usr/bin/env python3
"""Assertion-free exact gates for the THM-3914 proof candidate.

The companion freezes the degree-ten boundary discriminant generator, its
index-three hyperbolic saturation, the cubic-root identities, and the full
mod-three residue enumeration.

Reproduction:
  python3 04-computation/jc2_decic_boundary_hyperbolic_saturation_thm3914.py
  python3 -O 04-computation/jc2_decic_boundary_hyperbolic_saturation_thm3914.py
"""

from __future__ import annotations

import ast
import hashlib
import json
from pathlib import Path

import sympy as sp
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ


CHECKS = 0


def gate(condition: bool, label: str) -> None:
    global CHECKS
    CHECKS += 1
    if condition is not True and condition != sp.S.true:
        raise RuntimeError(f"{label}: failed")


def equal(label: str, left: object, right: object) -> None:
    gate(left == right, f"{label}: {left!r} != {right!r}")


K = sp.Matrix([[-4, 5], [5, -4]])
B_plus = sp.Matrix([1, 0])
B_minus = sp.Matrix([0, 1])
T = B_plus + B_minus
w = B_plus - B_minus


def pairing(x: sp.Matrix, y: sp.Matrix) -> sp.Expr:
    return sp.factor((x.T * K * y)[0])


# ---------------------------------------------------------------------------
# 1. Boundary discriminant group and its unique order-three residue.
# ---------------------------------------------------------------------------

equal("boundary_determinant", int(K.det()), -9)
equal("boundary_smith", smith_normal_form(K, domain=ZZ), sp.diag(1, 9))
equal("T_square", pairing(T, T), 2)
equal("w_square", pairing(w, w), -18)
equal("T_w_orthogonal", pairing(T, w), 0)

v = w / 3
equal("v_pairings", K * v, sp.Matrix([-3, 3]))
equal("v_square", pairing(v, v), -2)
gate(any(entry.q != 1 for entry in v), "v is not in the original boundary lattice")
equal("three_v_is_w", 3 * v, w)

# Enumerate every residue y mod 3 for which y/3 lies in the dual lattice.
dual_residues: list[tuple[int, int]] = []
isotropic_nonzero: list[tuple[int, int]] = []
for a in range(3):
    for b in range(3):
        y = sp.Matrix([a, b])
        if all(int(value) % 3 == 0 for value in K * y):
            dual_residues.append((a, b))
            square_numerator = int(pairing(y, y))
            if (a, b) != (0, 0) and square_numerator % 9 == 0:
                isotropic_nonzero.append((a, b))

equal("all_order_three_dual_residues", dual_residues, [(0, 0), (1, 2), (2, 1)])
equal("nonzero_isotropic_residues", isotropic_nonzero, [(1, 2), (2, 1)])


# ---------------------------------------------------------------------------
# 2. The cubic-root classes and the hyperbolic enlargement.
# ---------------------------------------------------------------------------

D_minus = B_minus + v
D_plus = B_plus - v
U = sp.Matrix([[0, 1], [1, 0]])

equal("D_sum_is_T", D_plus + D_minus, T)
equal("D_difference_is_v", D_plus - D_minus, v)
equal("three_D_minus", 3 * D_minus, T + B_minus)
equal("three_D_plus", 3 * D_plus, T + B_plus)
equal("boundary_from_D_plus", 2 * D_plus - D_minus, B_plus)
equal("boundary_from_D_minus", 2 * D_minus - D_plus, B_minus)

D_basis = sp.Matrix.hstack(D_plus, D_minus)
equal("D_gram_is_U", sp.simplify(D_basis.T * K * D_basis), U)
equal("D_plus_T_degree", pairing(D_plus, T), 1)
equal("D_minus_T_degree", pairing(D_minus, T), 1)
equal("D_plus_negative_boundary", pairing(D_plus, B_plus), -1)
equal("D_minus_negative_boundary", pairing(D_minus, B_minus), -1)

# Columns are B_+,B_- in the ordered basis D_+,D_-.
embedding = sp.Matrix([[2, -1], [-1, 2]])
equal("boundary_embedding_determinant", int(embedding.det()), 3)
equal("boundary_gram_from_U", embedding.T * U * embedding, K)
equal("D_basis_from_boundary", D_basis, embedding.inv())


# ---------------------------------------------------------------------------
# 3. Freeze source discipline and the semantic payload.
# ---------------------------------------------------------------------------

source_text = Path(__file__).read_text(encoding="utf-8")
gate(
    not any(isinstance(node, ast.Assert) for node in ast.walk(ast.parse(source_text))),
    "inactive Python assert",
)

semantic = {
    "boundary": "K10=[[-4,5],[5,-4]], SNF=(1,9), discriminant order 9",
    "residue": "unique nonzero order-3 subgroup is generated by (B+-B-)/3 with square -2",
    "globalization": "Cl[3] under Pic[3]=0 and 3-prime orthogonal remainder iff B+-B- is 3-divisible",
    "cubic_root": "3D-=T+B-, 3D+=T+B+",
    "saturation": "K10 embeds at index 3 in U generated by D+,D-",
    "scope": "D classes are not automatically effective and are not nef",
}
semantic_blob = json.dumps(semantic, sort_keys=True, separators=(",", ":")).encode()

print("theorem=THM-3914-decic-boundary-three-class-degree-one-isotropic-divisor")
print("boundary_gram=[[-4,5],[5,-4]]")
print("boundary_snf=[1,9]")
print("order3_generator=(B_plus-B_minus)/3")
print("order3_generator_square=-2")
print("saturated_gram=[[0,1],[1,0]]")
print("boundary_index_in_U=3")
print("cubic_roots=3D_plus:T+B_plus;3D_minus:T+B_minus")
print("degree_one_isotropic=D_plus,D_minus")
print("effectivity_or_fibration=NOT_IMPLIED")
print(f"semantic_sha256={hashlib.sha256(semantic_blob).hexdigest()}")
print(f"CHECKS={CHECKS}")
print("RESULT=PASS")
