#!/usr/bin/env python3
"""Exact scout for the confluent quadratic higher-pole Hermite carrier.

This is deliberately a theorem-candidate companion without a theorem ID.  It
checks the quadratic spectral collision, the two new polynomial quotients,
the singular completion and its normalization, the saturated smooth model,
its three plane charts, and the surviving moving-arm de Rham residue.
"""

from __future__ import annotations

import hashlib
import json

import sympy as sp


CHECKS = 0


def check(condition: object, label: str) -> None:
    global CHECKS
    if condition is not True and condition != sp.S.true:
        raise AssertionError(label)
    CHECKS += 1


T, b = sp.symbols("T b")
g_b = 10 * b**2 - 5 * b + 1


def reduce_b(expr: sp.Expr) -> sp.Expr:
    """Reduce a polynomial/rational-constant expression modulo g_b."""

    num, den = sp.together(sp.expand(expr)).as_numer_denom()
    check(not den.has(b), "reduce_b denominator independent of b")
    return sp.expand(sp.rem(num, g_b, b) / den)


def same_mod(lhs: sp.Expr, rhs: sp.Expr, label: str) -> None:
    num, _den = sp.together(sp.cancel(lhs - rhs)).as_numer_denom()
    check(sp.expand(sp.rem(num, g_b, b)) == 0, label)


# The exact collision locus.
q = sp.expand((T - 1) * (T - b))
Q = sp.expand(T * (T - 1) ** 3 * (2 * T + 1 - 5 * b) / 10)
ell = sp.expand(b * (b - 1) ** 3 * (1 - 3 * b) / 10)
R_b = sp.expand(
    sp.Rational(1, 5) * T**2
    + (b - 5) * T / 10
    - sp.Rational(3, 100) * (5 * b - 11)
)

same_mod(sp.diff(Q, T), q**2, "Q'=q^2")
same_mod(Q.subs(T, 0), 0, "Q(0)=0")
same_mod(Q.subs(T, 1), 0, "Q(1)=0")
same_mod(Q.subs(T, b), ell, "Q(b)=ell")
same_mod(Q - ell, (T - b) ** 3 * R_b, "critical-b cubic factor")
check(sp.discriminant(g_b, b) == -15, "two distinct quadratic parameters")
check(sp.solve(g_b, b) == [sp.Rational(1, 4) - sp.sqrt(15) * sp.I / 20,
                           sp.Rational(1, 4) + sp.sqrt(15) * sp.I / 20],
      "normalized b values")
check(sp.resultant(g_b, sp.together(ell).as_numer_denom()[0], b) != 0,
      "ell nonzero on collision locus")
check(sp.resultant(g_b, b * (b - 1), b) != 0,
      "q(0) and root separation nonzero")

# At w=ell the residual quadratic has no critical root.  At w=0 the
# residual simple root also has q!=0.
residual_resultant = sp.resultant(R_b, q, T)
check(sp.resultant(g_b, sp.together(residual_resultant).as_numer_denom()[0], b) != 0,
      "ell residual roots noncritical")
r_zero = (5 * b - 1) / 2
check(sp.resultant(g_b, sp.together(q.subs(T, r_zero)).as_numer_denom()[0], b) != 0,
      "zero residual root noncritical")


# Source polynomial quotients.
x, y = sp.symbols("x y")
t = x**2 * (1 + x * y)
q_t = sp.expand(q.subs(T, t))
Q_t = reduce_b(Q.subs(T, t))
F = sp.expand(x * q_t)
W = Q_t

# Since Q=T(T-1)^3 h/10 and Q-ell=(T-b)^3 R_b, cancellation of q^2
# leaves the following polynomial M exactly.
h_t = sp.expand((2 * T + 1 - 5 * b).subs(T, t))
Rb_t = sp.expand(R_b.subs(T, t))
M0 = reduce_b((1 + x * y) * h_t * Rb_t / 10)  # M/q(t)
M = reduce_b(q_t * M0)
same_mod(F**2 * M, W * (W - ell), "first confluent quotient M")

# The boundary values of (w,m) are (0,-ell),(0,0),(ell,0).  Their
# vanishing ideal is generated by w(w-ell), wm,m(m+ell).  The first two
# divided quotients are already fM and Z+fM; the third is the genuinely new
# jet N.
M_plus = reduce_b(M + ell)
check(M_plus.subs(x, 0) == 0, "M+ell vanishes on axis")
C_axis = sp.cancel(M_plus / x)
check(sp.denom(C_axis) == 1, "(M+ell)/x polynomial")
W_minus_F2_over_x = sp.cancel(reduce_b(W - F**2) / x)
check(sp.denom(W_minus_F2_over_x) == 1, "(W-F^2)/x polynomial")
N = reduce_b(M0 * C_axis)
Z = reduce_b(M0 * W_minus_F2_over_x)
same_mod(F * N, M * (M + ell), "second confluent quotient N")
same_mod(F * Z, (W - F**2) * M, "singular-completion coordinate Z")
same_mod(W * M / F, Z + F * M, "wm/f is not a new generator")

# Exact boundary packets.  The axis is filled, while the two critical arms
# are punctured inverse-cube covers.
same_mod(M.subs(x, 0), -ell, "axis M=-ell")
same_mod(b * N.subs(x, 0), ell**2 * y, "axis N=(ell^2/b)y")
same_mod(Z.subs(x, 0), 0, "axis Z=0")

M0_T = T * (2 * T + 1 - 5 * b) * R_b / (10 * x**2)
same_mod(M0_T.subs(T, 1), -ell / (3 * (1 - b) * x**2),
         "root-1 M/q lead")
same_mod(M0_T.subs(T, b), ell / (3 * (b - 1) * x**2),
         "root-b M/q lead")
critical_constant = ell**2 / (3 * (b - 1) * x**3)
same_mod(
    M0_T.subs(T, 1) * ell / x,
    critical_constant,
    "root-1 N boundary",
)
same_mod(
    M0_T.subs(T, b) * ell / x,
    critical_constant,
    "root-b N boundary",
)
same_mod(Q.subs(T, 1) / x, 0, "root-1 Z boundary zero")
same_mod(
    M0_T.subs(T, b) * Q.subs(T, b) / x,
    critical_constant,
    "root-b Z=N boundary",
)


# Abstract singular completion and its normalization.
f, w, m, n, z, u, L = sp.symbols("f w m n z u L")
D0 = sp.expand(f**3 * z - (w - f**2) * w * (w - L))
same_D0 = {
    "D_z": sp.diff(D0, z),
    "D_f": sp.diff(D0, f),
    "D_w": sp.diff(D0, w),
}
check(sp.expand(same_D0["D_z"] - f**3) == 0, "singular completion D_z")
check(sp.expand(same_D0["D_f"] - 3 * f**2 * z - 2 * f * w * (w - L)) == 0,
      "singular completion D_f")
check(sp.factor(same_D0["D_w"].subs(f, 0)) == -w * (3 * w - 2 * L),
      "singular completion boundary D_w")
check(D0.subs({f: 0, w: 0}) == 0, "singular line lies on D0")
check(all(expr.subs({f: 0, w: 0}) == 0 for expr in same_D0.values()),
      "singular line gradient zero")
check(same_D0["D_w"].subs({f: 0, w: L}) == -L**2,
      "other arm smooth")

u_rat = w * (w - L) / f
z_rat = (w - f**2) * w * (w - L) / f**3
check(sp.cancel(u_rat**2 - f * (w - L) * (z_rat + u_rat)) == 0,
      "normalization element monic equation")
check(sp.cancel(f * u_rat - w * (w - L)) == 0,
      "normalization relation one")
check(sp.cancel(f**2 * (z_rat + u_rat) - w * u_rat) == 0,
      "normalization relation two")

# The normalization has two arms and one A1 point.  With
# v=(w-L)(z+u), its completed local equation is exactly u^2=fv.
A_norm = f * u - w * (w - L)
B_norm = f**2 * (z + u) - w * u
C_norm = u**2 - f * (w - L) * (z + u)
p0 = {f: 0, w: 0, u: 0, z: 0}
J_norm = sp.Matrix([[sp.diff(R, V).subs(p0) for V in (f, w, u, z)]
                    for R in (A_norm, B_norm, C_norm)])
check(J_norm.rank() == 1, "normalization A1 point singular")
check(sp.diff(A_norm, w).subs(p0) == L, "normalization eliminates w locally")
check(C_norm == u**2 - f * (w - L) * (z + u), "normalization A1 equation")

# The first nonfinite affine modification B0[M] is already smooth, although
# it still collapses the two confluent source components.  Its saturated
# three-relation presentation has a constant nonzero Jacobian minor on each
# special-fibre line.
C1_r1 = f**2 * m - w * (w - L)
C1_r2 = f * z - (w - f**2) * m
C1_r3 = (w - L) * (f * m + z) - f * m**2
C1_axis = {f: 0, w: 0, z: 0}
C1_critical = {f: 0, w: L, m: 0}
C1_axis_minor = sp.Matrix(
    [[sp.diff(R, V).subs(C1_axis) for V in (w, z)] for R in (C1_r1, C1_r3)]
).det()
C1_critical_minor = sp.Matrix(
    [[sp.diff(R, V).subs(C1_critical) for V in (w, m)] for R in (C1_r1, C1_r2)]
).det()
check(sp.expand(C1_axis_minor + L**2) == 0, "first modification axis smooth")
check(sp.expand(C1_critical_minor - L**2) == 0,
      "first modification critical arm smooth")


# Saturated presentation of the final two-step affine modification
# R=k[f,w,m,n,z].
r1 = f**2 * m - w * (w - L)
r2 = f * n - m * (m + L)
r3 = f * z - (w - f**2) * m
r4 = (m + L) * (f * m + z) - n * w
r5 = (w - L) * (f * m + z) - f * m**2
r6 = n * w * (w - L) - f * m**2 * (m + L)
relations = (r1, r2, r3, r4, r5, r6)

inv = sp.symbols("inv")
G_sat = sp.groebner(
    [r1, r2, r3, inv * f - 1],
    inv, z, n, m, w, f,
    order="lex",
)
for i, relation in enumerate(relations):
    check(G_sat.reduce(relation)[1] == 0, f"saturated relation {i}")
eliminated = [P.as_expr() for P in G_sat.polys if not P.as_expr().has(inv)]
check(len(eliminated) == 6, "six-element saturated Groebner packet")
G_rel = sp.groebner(relations, z, n, m, w, f, order="lex")
for i, relation in enumerate(eliminated):
    check(G_rel.reduce(relation)[1] == 0, f"presentation generates saturation {i}")

# The special fibre is exactly three affine lines:
# A=(w,m,z)=(0,-L,0), C=(0,0,0), B=(L,0,n-z).
aa = sp.symbols("aa")
arms = (
    {f: 0, w: 0, m: -L, z: 0, n: aa},
    {f: 0, w: 0, m: 0, z: 0, n: aa},
    {f: 0, w: L, m: 0, n: aa, z: aa},
)
for j, arm in enumerate(arms):
    for i, relation in enumerate(relations):
        check(sp.expand(relation.subs(arm)) == 0, f"arm {j} relation {i}")


# Poisson packet inherited from {f,w}=f^3.  Two minors already certify
# nondegeneracy on all three boundary arms.
m_rat = w * (w - L) / f**2
n_rat = m_rat * (m_rat + L) / f
z_rat2 = (w - f**2) * m_rat / f


def bracket(A: sp.Expr, B: sp.Expr) -> sp.Expr:
    return sp.cancel(
        f**3 * (sp.diff(A, f) * sp.diff(B, w) - sp.diff(A, w) * sp.diff(B, f))
    )


check(sp.cancel(bracket(f, n_rat) - (2 * w - L) * (2 * m_rat + L)) == 0,
      "Poisson {f,n}")
fz_expected = L * f**2 - 2 * L * w - 2 * f**2 * w + 3 * w**2
check(sp.cancel(bracket(f, z_rat2) - fz_expected) == 0, "Poisson {f,z}")
check(((2 * w - L) * (2 * m + L)).subs(arms[0]) == L**2,
      "axis Poisson unit")
check(((2 * w - L) * (2 * m + L)).subs(arms[1]) == -L**2,
      "root-1 Poisson unit")
check(fz_expected.subs(arms[2]) == L**2, "root-b Poisson unit")


# Explicit plane charts.  They share D(f) and retain respectively the
# moving axis arm beta=f^2, the root-1 arm beta=0, and the root-b arm beta=L.
def verify_chart(values: dict[sp.Symbol, sp.Expr], tag: str) -> None:
    for i, relation in enumerate(relations):
        check(sp.expand(relation.subs(values)) == 0, f"{tag} relation {i}")


s0 = 1 + f * aa
m0 = sp.expand(s0 * (f**2 * s0 - L))
chart_axis = {
    w: f**2 * s0,
    m: m0,
    n: sp.expand(m0 * (f * s0**2 - L * aa)),
    z: sp.expand(f**2 * aa * m0),
}
verify_chart(chart_axis, "axis chart")
check(chart_axis[n].subs(f, 0) == L**2 * aa, "axis chart boundary coordinate")

r1c = f**3 * aa - L
m1 = sp.expand(f * aa * r1c)
chart_one = {
    w: f**3 * aa,
    m: m1,
    n: sp.expand(aa * r1c * (L + f * aa * r1c)),
    z: sp.expand(f**2 * aa * r1c * (f * aa - 1)),
}
verify_chart(chart_one, "root-1 chart")
check(chart_one[n].subs(f, 0) == -L**2 * aa, "root-1 chart boundary coordinate")

rbc = L + f**3 * aa
mb = sp.expand(f * aa * rbc)
chart_b = {
    w: rbc,
    m: mb,
    n: sp.expand(aa * rbc * (L + f * aa * rbc)),
    z: sp.expand(aa * rbc * (L + f**3 * aa - f**2)),
}
verify_chart(chart_b, "root-b chart")
check(chart_b[n].subs(f, 0) == L**2 * aa, "root-b N boundary coordinate")
check(chart_b[z].subs(f, 0) == L**2 * aa, "root-b Z boundary coordinate")

# On every chart omega=df^dw/f^3=df^da.  Primitive transitions see the
# f^2 coefficient vector (1,0,0), so the smooth modification still has a
# nonzero algebraic de Rham class.
beta = (f**2, sp.Integer(0), L)
rho = tuple(sp.expand(B).coeff(f, 2) for B in beta)
check(rho == (1, 0, 0), "resonant jet vector")
for i in range(3):
    for j in range(i + 1, 3):
        ai = (w - beta[i]) / f**3
        aj = (w - beta[j]) / f**3
        check(sp.cancel(aj - ai - (beta[i] - beta[j]) / f**3) == 0,
              f"chart transition {i},{j}")
        residue = sp.expand((beta[j] - beta[i]) / f**3).coeff(f, -1)
        check(residue == rho[j] - rho[i], f"primitive residue {i},{j}")
check(len(set(rho)) > 1, "de Rham class nonzero modulo constants")


semantic = {
    "atlas": "three_A2_charts_with_beta=(f^2,0,ell);source_etale;two_missing_points",
    "collision": "q=(T-1)(T-b);10b^2-5b+1=0;Q(0)=Q(1)=0;Q(b)=ell!=0",
    "derham": "rho=[f^2]beta=(1,0,0)_mod_constants;nonzero;no_Darboux_pair",
    "final_ring": "k[F,W,M,N,Z];F^2M=W(W-ell);FN=M(M+ell);FZ=(W-F^2)M",
    "normalization": "u=W(W-ell)/F_integral;one_A1_point",
    "quotients": "M=W(W-ell)/F^2;N=M(M+ell)/F;WM/F=Z+FM",
    "singular_completion": "F^3Z=(W-F^2)W(W-ell);Sing=(F,W)=0",
}
semantic_blob = json.dumps(semantic, sort_keys=True, separators=(",", ":")).encode()

print("scout=confluent_quadratic_higher_pole_hermite")
print("parameters=b=(5+-sqrt(-15))/20; q=(T-1)(T-b)")
print("spectrum=Q(0)=Q(1)=0;Q(b)=ell!=0")
print("singular_completion=F^3Z=(W-F^2)W(W-ell);Sing_line=(F,W)=0")
print("normalization=u=W(W-ell)/F;one_A1_point")
print("new_quotients=M=W(W-ell)/F^2;N=M(M+ell)/F")
print("smooth_model=k[F,W,M,N,Z];three_plane_charts")
print("image=smooth_model_minus_root1_origin_and_rootb_origin")
print("poisson={F,N}=(2W-ell)(2M+ell);boundary_units=ell^2,-ell^2")
print("derham=resonant_vector_(1,0,0)_mod_constants;no_Darboux_pair")
print(f"CHECKS={CHECKS}")
print(f"semantic_sha256={hashlib.sha256(semantic_blob).hexdigest()}")
