#!/usr/bin/env python3
"""Finite-field primitivity probe for all three coordinates of fixed F^3.

The pinned THM-3495 split-fibre audit supplies a lawful target over F_101,
three first preimages, and nine second preimages.  Above each second point is
one separable cubic algebra.  This companion reconstructs y and z as exact
rational functions of the cubic x-coordinate inside each quotient, computes
the 3x3 regular-representation characteristic polynomial of x, y, and z,
and multiplies the nine local polynomials.

If all three products are squarefree of degree 27, the specialized rank-27
fibre algebra is generated by each coordinate.  Nonvanishing of the three
power-basis determinants then proves generic primitivity in characteristic
zero.  Combined with THM-3495 and trace-form congruence, this would put all
three minimal-polynomial discriminants in the square class [-2J].

Scope: the fixed sporadic map at level three only.  No higher-level,
arbitrary-Keller, infinite-family, or Jacobian-conjecture conclusion.
"""

from __future__ import annotations

import ast
import contextlib
import hashlib
import io
import runpy
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARENT_PATH = ROOT / "04-computation/jc_level3_degree27_split_finite_field_audit_20260816.py"
PARENT_SHA256 = "9f8b6b4aad75b17eed8a6fd618cb661f3e61b85361b44ba676462148a2c5afc5"
EXPECTED_PRODUCT_HASHES = (
    "306dc5831a989a0fe953ae5eb6127d26bd6ff07f8cc4e25d54dc0f65e53e5e19",
    "aba63853d168e670461e67b67e42d26380e18c62b363c8931aa187f1a97d4e51",
    "b8a09c5bfed7affdabbbb3fcf222002a3a7c11c8d55cb19bcc949494725bb51d",
)
EXPECTED_SEMANTIC_SHA256 = "61ddcb9dbd3c7582a514bf1a42bbff3cd9ca7d052ea9620721979ed6c8138245"


def require(condition: bool, payload: object) -> None:
    if not condition:
        raise RuntimeError(payload)


def lf_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


require(lf_sha256(PARENT_PATH) == PARENT_SHA256, "parent split-fibre hash drift")
captured = io.StringIO()
with contextlib.redirect_stdout(captured):
    N = runpy.run_path(str(PARENT_PATH))
require(
    captured.getvalue().rstrip().endswith("all independent audit checks passed"),
    "parent split-fibre replay failed",
)

P = N["P"]
TARGET = N["target"]
LEVEL_TWO = tuple(N["level_two"])
require(P == 101 and len(LEVEL_TWO) == 9, (P, len(LEVEL_TWO)))


def trim(poly: list[int] | tuple[int, ...]) -> list[int]:
    result = [value % P for value in poly]
    while len(result) > 1 and result[-1] == 0:
        result.pop()
    return result


def add(left: list[int], right: list[int]) -> list[int]:
    size = max(len(left), len(right))
    return trim([
        (left[index] if index < len(left) else 0)
        + (right[index] if index < len(right) else 0)
        for index in range(size)
    ])


def negate(poly: list[int]) -> list[int]:
    return trim([-value for value in poly])


def subtract(left: list[int], right: list[int]) -> list[int]:
    return add(left, negate(right))


def scale(poly: list[int], scalar: int) -> list[int]:
    return trim([scalar * value for value in poly])


def multiply(left: list[int], right: list[int]) -> list[int]:
    result = [0] * (len(left) + len(right) - 1)
    for i, x in enumerate(left):
        for j, y in enumerate(right):
            result[i + j] = (result[i + j] + x * y) % P
    return trim(result)


def inverse_scalar(value: int) -> int:
    require(value % P != 0, "scalar inverse of zero")
    return pow(value, P - 2, P)


def divide_with_quotient(numerator: list[int], denominator: list[int]) -> tuple[list[int], list[int]]:
    remainder = trim(numerator)
    divisor = trim(denominator)
    require(divisor != [0], "polynomial division by zero")
    if len(remainder) < len(divisor):
        return [0], remainder
    quotient = [0] * (len(remainder) - len(divisor) + 1)
    inverse_lead = inverse_scalar(divisor[-1])
    while len(remainder) >= len(divisor) and remainder != [0]:
        shift = len(remainder) - len(divisor)
        factor = remainder[-1] * inverse_lead % P
        quotient[shift] = factor
        for index, coefficient in enumerate(divisor):
            remainder[index + shift] = (
                remainder[index + shift] - factor * coefficient
            ) % P
        remainder = trim(remainder)
    return trim(quotient), remainder


def remainder(numerator: list[int], denominator: list[int]) -> list[int]:
    return divide_with_quotient(numerator, denominator)[1]


def gcd(left: list[int], right: list[int]) -> list[int]:
    x, y = trim(left), trim(right)
    while y != [0]:
        x, y = y, remainder(x, y)
    return scale(x, inverse_scalar(x[-1]))


def derivative(poly: list[int]) -> list[int]:
    return trim([index * poly[index] for index in range(1, len(poly))])


def extended_gcd(left: list[int], right: list[int]) -> tuple[list[int], list[int], list[int]]:
    old_r, r = trim(left), trim(right)
    old_s, s = [1], [0]
    old_t, t = [0], [1]
    while r != [0]:
        quotient, new_r = divide_with_quotient(old_r, r)
        old_r, r = r, new_r
        old_s, s = s, subtract(old_s, multiply(quotient, s))
        old_t, t = t, subtract(old_t, multiply(quotient, t))
    factor = inverse_scalar(old_r[-1])
    return scale(old_r, factor), scale(old_s, factor), scale(old_t, factor)


def quotient_reduce(poly: list[int], cubic: list[int]) -> list[int]:
    reduced = remainder(poly, cubic)
    return reduced + [0] * (3 - len(reduced))


def quotient_multiply(left: list[int], right: list[int], cubic: list[int]) -> list[int]:
    return quotient_reduce(multiply(left, right), cubic)


def quotient_inverse(element: list[int], cubic: list[int]) -> list[int]:
    divisor, coefficient, _other = extended_gcd(element, cubic)
    require(divisor == [1], ("quotient nonunit", element, cubic, divisor))
    answer = quotient_reduce(coefficient, cubic)
    require(quotient_multiply(element, answer, cubic) == [1, 0, 0],
            ("bad quotient inverse", element))
    return answer


def quotient_power(element: list[int], exponent: int, cubic: list[int]) -> list[int]:
    answer = [1, 0, 0]
    base = quotient_reduce(element, cubic)
    while exponent:
        if exponent & 1:
            answer = quotient_multiply(answer, base, cubic)
        base = quotient_multiply(base, base, cubic)
        exponent //= 2
    return answer


def matrix_multiply(left: list[list[int]], right: list[list[int]]) -> list[list[int]]:
    return [
        [
            sum(left[i][k] * right[k][j] for k in range(len(right))) % P
            for j in range(len(right[0]))
        ]
        for i in range(len(left))
    ]


def determinant3(matrix: list[list[int]]) -> int:
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    return (a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)) % P


def multiplication_matrix(element: list[int], cubic: list[int]) -> list[list[int]]:
    basis = ([1, 0, 0], [0, 1, 0], [0, 0, 1])
    columns = [quotient_multiply(element, vector, cubic) for vector in basis]
    return [[columns[column][row] for column in range(3)] for row in range(3)]


def characteristic_polynomial(element: list[int], cubic: list[int]) -> list[int]:
    matrix = multiplication_matrix(element, cubic)
    square = matrix_multiply(matrix, matrix)
    trace = sum(matrix[index][index] for index in range(3)) % P
    trace_square = sum(square[index][index] for index in range(3)) % P
    second = (trace * trace - trace_square) * inverse_scalar(2) % P
    answer = [(-determinant3(matrix)) % P, second, (-trace) % P, 1]

    # Cayley--Hamilton in the quotient is an independent local check.
    evaluation = [0, 0, 0]
    for coefficient in reversed(answer):
        evaluation = quotient_multiply(evaluation, element, cubic)
        evaluation = add(evaluation, [coefficient])
        evaluation += [0] * (3 - len(evaluation))
    require(evaluation == [0, 0, 0], ("Cayley-Hamilton", element, answer, evaluation))
    return answer


def map_in_quotient(
    x: list[int], y: list[int], z: list[int], cubic: list[int]
) -> tuple[list[int], list[int], list[int]]:
    one = [1, 0, 0]
    unit = add(one, quotient_multiply(x, y, cubic))
    unit2 = quotient_power(unit, 2, cubic)
    unit3 = quotient_multiply(unit2, unit, cubic)
    y2 = quotient_power(y, 2, cubic)
    xy = quotient_multiply(x, y, cubic)
    four_plus_3xy = add([4, 0, 0], scale(xy, 3))
    first = add(
        quotient_multiply(unit3, z, cubic),
        quotient_multiply(quotient_multiply(y2, unit, cubic), four_plus_3xy, cubic),
    )
    second = add(
        y,
        add(
            scale(quotient_multiply(quotient_multiply(x, unit2, cubic), z, cubic), 3),
            scale(quotient_multiply(quotient_multiply(quotient_multiply(x, y2, cubic), four_plus_3xy, cubic), [1, 0, 0], cubic), 3),
        ),
    )
    third = subtract(
        subtract(scale(x, 2), scale(quotient_multiply(quotient_power(x, 2, cubic), y, cubic), 3)),
        quotient_multiply(quotient_power(x, 3, cubic), z, cubic),
    )
    return tuple(quotient_reduce(value, cubic) for value in (first, second, third))


def local_coordinate_data(target: tuple[int, int, int]) -> tuple[object, ...]:
    a, b, c = target
    cubic = trim(N["core_coefficients"](target))
    require(len(cubic) == 4 and gcd(cubic, derivative(cubic)) == [1],
            ("bad cubic", target, cubic))
    x = [0, 1, 0]
    x2 = quotient_power(x, 2, cubic)
    denominator = add(add(scale(x2, 12 * a - b * b), scale(x, b)), [2])
    denominator_inverse = quotient_inverse(denominator, cubic)
    numerator = scale(
        quotient_multiply(x, add(scale(x, 9 * a * c - b), [2]), cubic),
        3 * a,
    )
    y = subtract([b, 0, 0], quotient_multiply(numerator, denominator_inverse, cubic))
    y = quotient_reduce(y, cubic)
    x3_inverse = quotient_inverse(quotient_power(x, 3, cubic), cubic)
    z_numerator = subtract(
        subtract(scale(x, 2), [c, 0, 0]),
        scale(quotient_multiply(x2, y, cubic), 3),
    )
    z = quotient_multiply(z_numerator, x3_inverse, cubic)
    images = map_in_quotient(x, y, z, cubic)
    expected = tuple([value % P, 0, 0] for value in target)
    require(images == expected, ("map replay", target, images, expected))
    charpolys = tuple(characteristic_polynomial(value, cubic) for value in (x, y, z))
    require(all(len(poly) == 4 and gcd(poly, derivative(poly)) == [1] for poly in charpolys),
            ("local coordinate nonprimitive", target, charpolys))
    return target, tuple(cubic), tuple(tuple(value) for value in (x, y, z)), tuple(tuple(poly) for poly in charpolys)


def product_data(rows: tuple[object, ...]) -> tuple[tuple[tuple[int, ...], ...], tuple[tuple[int, ...], ...]]:
    products = []
    derivative_gcds = []
    for coordinate in range(3):
        product = [1]
        for row in rows:
            product = multiply(product, list(row[3][coordinate]))
        require(len(product) == 28, ("product degree", coordinate, len(product) - 1))
        products.append(tuple(product))
        derivative_gcds.append(tuple(gcd(product, derivative(product))))
    return tuple(products), tuple(derivative_gcds)


fixed_rows = tuple(local_coordinate_data(target) for target in LEVEL_TWO)
fixed_products, fixed_gcds = product_data(fixed_rows)
fixed_hashes = tuple(
    hashlib.sha256(
        "\n".join(f"{index}:{coefficient}" for index, coefficient in enumerate(product)).encode("ascii")
    ).hexdigest()
    for product in fixed_products
)
require(
    all(
        list(row[3][0])
        == scale(list(row[1]), inverse_scalar(row[1][-1]))
        for row in fixed_rows
    ),
    "monic x characteristic polynomials do not normalize the parent cores",
)
require(fixed_gcds[0] == (1,), ("parent x lost squarefreeness", fixed_gcds[0]))


def find_all_coordinate_witness() -> tuple[object, ...]:
    state = 1
    seen: set[int] = set()
    split_depth_two = 0
    lawful_nine_blocks = 0
    local_coordinate_generators = 0
    for iteration in range(P**3):
        state = (742939 * state + 2311) % (P**3)
        if state in seen:
            break
        seen.add(state)
        target = (state % P, (state // P) % P, (state // (P * P)) % P)
        first = N["split_level"](target)
        if first is None:
            continue
        second_blocks = []
        for point in first:
            children = N["split_level"](point)
            if children is None:
                break
            second_blocks.append(children)
        if len(second_blocks) != 3:
            continue
        split_depth_two += 1
        second_points = tuple(point for block in second_blocks for point in block)
        if len(second_points) != 9 or any(N["l_value"](point) == 0 for point in second_points):
            continue
        lawful_nine_blocks += 1
        try:
            rows = tuple(local_coordinate_data(point) for point in second_points)
        except RuntimeError:
            continue
        local_coordinate_generators += 1
        products, derivative_gcds = product_data(rows)
        if derivative_gcds == ((1,), (1,), (1,)):
            return (
                iteration + 1,
                len(seen),
                split_depth_two,
                lawful_nine_blocks,
                local_coordinate_generators,
                target,
                tuple(first),
                tuple(tuple(block) for block in second_blocks),
                second_points,
                rows,
                products,
                derivative_gcds,
            )
    raise RuntimeError((
        "no all-coordinate witness",
        len(seen),
        split_depth_two,
        lawful_nine_blocks,
        local_coordinate_generators,
    ))


witness = find_all_coordinate_witness()
(
    search_iterations,
    search_seen,
    split_depth_two,
    lawful_nine_blocks,
    local_coordinate_generators,
    witness_target,
    witness_level_one,
    witness_level_two_blocks,
    witness_level_two,
    local_rows,
    products,
    product_gcds,
) = witness
require(product_gcds == ((1,), (1,), (1,)), ("witness gcds", product_gcds))

product_hashes = tuple(
    hashlib.sha256(
        "\n".join(f"{index}:{coefficient}" for index, coefficient in enumerate(product)).encode("ascii")
    ).hexdigest()
    for product in products
)
if EXPECTED_PRODUCT_HASHES != "TO_BE_PINNED":
    require(product_hashes == EXPECTED_PRODUCT_HASHES,
            ("product hashes", product_hashes))

semantic = (
    PARENT_SHA256,
    P,
    (TARGET, LEVEL_TWO, fixed_hashes, fixed_gcds),
    (search_iterations, search_seen, split_depth_two, lawful_nine_blocks,
     local_coordinate_generators),
    witness_target,
    witness_level_one,
    witness_level_two_blocks,
    witness_level_two,
    local_rows,
    tuple(products),
    product_hashes,
    "all three degree-27 coordinate products squarefree at one lawful good-reduction fibre",
)
semantic_hash = hashlib.sha256(repr(semantic).encode("utf-8")).hexdigest()
if EXPECTED_SEMANTIC_SHA256 != "TO_BE_PINNED":
    require(semantic_hash == EXPECTED_SEMANTIC_SHA256,
            ("semantic hash", semantic_hash))

tree = ast.parse(Path(__file__).read_text(encoding="utf-8"))
require(not any(isinstance(node, ast.Assert) for node in ast.walk(tree)),
        "assert node")

print("== fixed F^3 all-coordinate finite-field primitivity probe ==")
print(f"dependency={PARENT_PATH.name}:{PARENT_SHA256}")
print(f"parent_target_hostile=(target={TARGET},coordinate_hashes={fixed_hashes},derivative_gcd_degrees={tuple(len(value)-1 for value in fixed_gcds)})")
print(f"search_census=(iterations={search_iterations},seen={search_seen},split_depth_two={split_depth_two},lawful_nine_blocks={lawful_nine_blocks},local_coordinate_generators={local_coordinate_generators})")
print(f"field=F_{P}; witness_target={witness_target}; level_one={witness_level_one}")
print(f"witness_level_two_blocks={witness_level_two_blocks}")
print("fibre_algebra=nine separable rank-three cubic quotients; total rank=27")
print("each local x,y,z multiplication characteristic polynomial has degree 3 and is squarefree")
print("each global x,y,z product has degree 27 and is squarefree; every coordinate separates all 27 geometric points")
print(f"coordinate_product_sha256=(x,y,z)={product_hashes}")
print(f"local_row_sha256={hashlib.sha256(repr(local_rows).encode('utf-8')).hexdigest()}")
print(f"semantic_sha256={semantic_hash}")
print("generic consequence candidate=K(x)=K(y)=K(z) for fixed F^3; trace-form congruence gives common class [-2J]")
print("scope=no exact discriminant multiplicities, level-four/all-level, arbitrary Keller, outside-family, JC(2), or LRC consequence")
print("all exact checks passed")
