from fractions import Fraction as F
from math import gcd
LAM=F(1,14)
def teeth01(x):
    w=LAM/x; out=[]
    for j in range(0,x+1):
        a,b=max(F(j,x)-w,F(0)), min(F(j,x)+w,F(1))
        if a<b: out.append((a,b))
    return out
def inter(u,v):
    out,i,j=[],0,0
    while i<len(u) and j<len(v):
        a,b=max(u[i][0],v[j][0]), min(u[i][1],v[j][1])
        if a<b: out.append((a,b))
        if u[i][1]<v[j][1]: i+=1
        else: j+=1
    return out
def exact2(a,b): return sum(y-x for x,y in inter(teeth01(a),teeth01(b)))
IND=(2*LAM)**2
print("(6) EXACT-INDEPENDENCE CRITERION FROM THE LATTICE")
print("    The pair lattice is generated by (b/g, -a/g), g = gcd(a,b).")
print("    Every vector is s*(b/g, -a/g); it contributes only if 7 does not")
print("    divide s*b/g AND does not divide s*a/g.  So ALL vectors die iff")
print("            7 | (a/g)   or   7 | (b/g).")
print("    Predicted: mu(D_a n D_b) = (2lam)^2 = 1/49 EXACTLY in that case.")
print()
print("    (a,b)       a/g  b/g   pred-indep   mu exact      = 1/49 ?")
bad=0
for (a,b) in [(5,7),(7,5),(1,7),(3,7),(2,14),(6,14),(14,21),(7,14),
              (2,3),(3,5),(4,6),(10,15),(9,11),(7,9),(5,35),(4,28)]:
    g=gcd(a,b); ap,bp=a//g,b//g
    pred = (ap%7==0) or (bp%7==0)
    mu=exact2(a,b); is_ind = (mu==IND)
    ok = (pred==is_ind)
    if not ok: bad+=1
    print(f"    {str((a,b)):11s} {ap:3d}  {bp:3d}   {str(pred):10s}  {str(mu):12s} {str(is_ind):6s} {'' if ok else '<-- MISMATCH'}")
print(f"    mismatches: {bad}/16")
print()
print("(7) DILATION INVARIANCE, EXPLAINED IN ONE LINE")
print("    Lam(k*a) = {n : sum n_i (k a_i) = 0} = {n : k * sum n_i a_i = 0} = Lam(a).")
print("    The resonance lattice does not see the scale k at all, so every")
print("    quantity built from it is dilation-invariant.  THM-1050 is immediate,")
print("    and THM-1055's 'no speed threshold' follows: the lattice is an")
print("    ARITHMETIC object and magnitude is not one of its inputs.")
for A in [(2,3),(4,6),(6,9),(10,15),(20,30)]:
    print(f"      mu{str(A):10s} = {str(exact2(*A))}")
