#!/usr/bin/env python3
"""
laplace_moment_engine_boxeph_S188.py  (HYP-8600, THM-1800 part 1)

THE LAPLACE MOMENT ENGINE — the S187 executed telescoping, generalized to
ANY monomial support. Input: P = sum_i c_i Z^{a_i} W^{b_i}. Then
  Lambda(u,w) = sum_i c_i w^{nu_i} u^{d_i},  nu_i = a_i+b_i, d_i = a_i-b_i,
  mu_m = E[P^m] = int_0^inf e^{-w^2/2} CT_u[Lambda^m] w dw.
Auxiliaries N_m(j,k) = int e^{-w^2/2} w^k CT[u^j Lambda^m] dw; mu = N(0,1).

RELATION FAMILIES (each instance a proved identity):
 (E)  N_m(j,k)   = sum_i c_i N_{m-1}(j+d_i, k+nu_i)
 (U)  0          = j N_m(j,k) + m sum_i c_i d_i N_{m-1}(j+d_i, k+nu_i)
 (W)  N_m(j,k+1) = k N_m(j,k-1) + m sum_i c_i nu_i N_{m-1}(j+d_i, k+nu_i-1)
      (boundary-free: k >= 1 always; k = 0 valid for m >= 1 iff
       min_i nu_i >= 1, true for any nonconstant P)
Sector: the rational sector is determined by parity classes of
(j, k) reachable; the engine works in the sector of (0,1) under the
lattice generated by (d_i, nu_i) — handled by parity bookkeeping mod 2.

ELIMINATION: at fixed m0, build all in-window instances, find the left
combination supported on {N_l(0,1)}; interpolate coefficients in m;
verify against exact moments; analyze leading coefficient; report the
finite moment test bound and the nullcone-by-recurrence conditions.

BATTERY: 4 validation supports (S186 H1-H4) + new: asymmetric span
aZ^2 + bZW + cW (charges 2,0,-1); the S186r hijack witness
P4 = ZW + Z^9W^7 + W; and aZ + bW^3. Parametric demo on aZ+b+cW.

boxeph-2026-07-20-S188. Pure python, exact Fractions.
"""
from fractions import Fraction
import math
import itertools


def fact(n):
    return math.factorial(n)


def Iw(K):
    # int_0^inf e^{-w^2/2} w^K dw: odd K = 2kap+1 -> 2^kap kap! (rational)
    if K % 2 == 0:
        return None
    kap = (K - 1) // 2
    return Fraction(2) ** kap * fact(kap)


class Engine:
    def __init__(self, terms):
        # terms: list of (c_i as Fraction, a_i, b_i)
        self.terms = [(Fraction(c), a, b) for (c, a, b) in terms]
        self.mono = [(a - b, a + b) for (_, a, b) in self.terms]  # (d_i, nu_i)

    def exactN(self, m, j, k):
        key = (m, j, k)
        if not hasattr(self, '_cache'):
            self._cache = {}
        if key in self._cache:
            return self._cache[key]
        # sum over multi-indices alpha (composition of m over terms) with
        # sum alpha_i d_i = -j ; weight w^{sum alpha_i nu_i + k}
        tot = Fraction(0)
        n = len(self.terms)

        def rec(i, rem, dsum, nusum, coef):
            nonlocal tot
            if i == n - 1:
                al = rem
                d, nu = self.mono[i]
                if dsum + al * d != -j:
                    return
                K = nusum + al * nu + k
                w = Iw(K)
                if w is None:
                    return
                c = self.terms[i][0]
                tot += coef * c ** al / fact(al) * w
                return
            d, nu = self.mono[i]
            c = self.terms[i][0]
            f = Fraction(1)
            for al in range(rem + 1):
                if al > 0:
                    f = f * c / al
                rec(i + 1, rem - al, dsum + al * d, nusum + al * nu, coef * f)

        rec(0, m, 0, 0, Fraction(fact(m)))
        self._cache[key] = tot
        return tot

    def mu(self, m):
        return self.exactN(m, 0, 1)

    def derive(self, m0, levels=4, JMAX=None, KMAX=None):
        ds = [d for d, nu in self.mono]
        nus = [nu for d, nu in self.mono]
        if JMAX is None:
            JMAX = max(2, max(abs(d) for d in ds) + 1)
        if KMAX is None:
            KMAX = 2 * max(nus) + 3
        idx = {}
        for l in range(m0 - levels + 1, m0 + 1):
            for j in range(-JMAX, JMAX + 1):
                for k in range(0, KMAX + 1):
                    idx[(l, j, k)] = len(idx)
        nu_ = len(idx)
        rows = []

        def add_row(termlist):
            row = {}
            for (l, j, k), co in termlist:
                if abs(j) > JMAX or k > KMAX or k < 0 or not (m0 - levels + 1 <= l <= m0):
                    return
                row[idx[(l, j, k)]] = row.get(idx[(l, j, k)], Fraction(0)) + co
            rows.append(row)

        for l in range(m0 - levels + 2, m0 + 1):
            for j in range(-JMAX, JMAX + 1):
                for k in range(0, KMAX + 1):
                    # E
                    add_row([((l, j, k), Fraction(1))] +
                            [((l - 1, j + d, k + nu), -c)
                             for (c, a, b), (d, nu) in zip(self.terms, self.mono)])
                    # U
                    add_row([((l, j, k), Fraction(j))] +
                            [((l - 1, j + d, k + nu), Fraction(l) * c * d)
                             for (c, a, b), (d, nu) in zip(self.terms, self.mono)])
                    # W (index at (j,k): relates k+1, k-1 at level l)
                    if k >= 1:
                        add_row([((l, j, k + 1), Fraction(1)),
                                 ((l, j, k - 1), -Fraction(k))] +
                                [((l - 1, j + d, k + nu - 1), -Fraction(l) * c * nu)
                                 for (c, a, b), (d, nu) in zip(self.terms, self.mono)])

        S = [idx[(l, 0, 1)] for l in range(m0 - levels + 1, m0 + 1)]
        Sset = set(S)
        # left kernel: solve (A restricted to non-S columns)^T y = 0
        # build sparse columns list per row; do dense over used columns
        used = sorted(set(c for row in rows for c in row if c not in Sset))
        colpos = {c: i for i, c in enumerate(used)}
        M = [[Fraction(0)] * len(rows) for _ in range(len(used))]
        for r, row in enumerate(rows):
            for c, v in row.items():
                if c in colpos:
                    M[colpos[c]][r] = v
        ncols = len(rows)
        R = M
        piv_of_col = [-1] * ncols
        r = 0
        for cc in range(ncols):
            piv = None
            for rr in range(r, len(R)):
                if R[rr][cc] != 0:
                    piv = rr
                    break
            if piv is None:
                continue
            R[r], R[piv] = R[piv], R[r]
            pv = R[r][cc]
            R[r] = [x / pv for x in R[r]]
            for rr in range(len(R)):
                if rr != r and R[rr][cc] != 0:
                    f = R[rr][cc]
                    R[rr] = [x - f * y for x, y in zip(R[rr], R[r])]
            piv_of_col[cc] = r
            r += 1
            if r == len(R):
                break
        free = [cc for cc in range(ncols) if piv_of_col[cc] < 0]
        for fc in free:
            y = [Fraction(0)] * ncols
            y[fc] = Fraction(1)
            for cc in range(ncols):
                pr = piv_of_col[cc]
                if pr >= 0:
                    y[cc] = -R[pr][fc]
            cS = []
            for si in S:
                tot = Fraction(0)
                for rr in range(len(rows)):
                    if y[rr] != 0 and si in rows[rr]:
                        tot += y[rr] * rows[rr][si]
                cS.append(tot)
            if any(x != 0 for x in cS):
                return cS
        return None

    def recurrence(self, m0s=None, levels=4, verify_to=45):
        if m0s is None:
            m0s = list(range(10, 17))
        recs = {}
        for m0 in m0s:
            cS = self.derive(m0, levels=levels)
            if cS is None:
                continue
            nz = [x for x in cS if x != 0]
            top = cS[-1] if cS[-1] != 0 else nz[-1]
            recs[m0] = [x / top for x in cS]
        if len(recs) < 3:
            return None, None, "no relation found"
        ms = sorted(recs)
        L = len(recs[ms[0]])
        polys = []
        for pos in range(L):
            pts = [(m0, recs[m0][pos]) for m0 in ms]
            coeffs = [Fraction(0)] * len(pts)
            for i, (xi, yi) in enumerate(pts):
                basis = [Fraction(1)]
                for jj, (xj, _) in enumerate(pts):
                    if jj == i:
                        continue
                    nb = [Fraction(0)] * (len(basis) + 1)
                    for t, bt in enumerate(basis):
                        nb[t + 1] += bt
                        nb[t] -= bt * xj
                    basis = nb
                den = Fraction(1)
                for jj, (xj, _) in enumerate(pts):
                    if jj != i:
                        den *= (xi - xj)
                for t in range(len(basis)):
                    coeffs[t] += yi * basis[t] / den
            while len(coeffs) > 1 and coeffs[-1] == 0:
                coeffs.pop()
            polys.append(coeffs)
        # verify
        mus = {m: self.mu(m) for m in range(0, verify_to + 1)}
        ok = True
        firstbad = None
        for m0 in range(L, verify_to + 1):
            tot = Fraction(0)
            for pos in range(L):
                l = m0 - (L - 1) + pos
                co = sum(polys[pos][d] * Fraction(m0) ** d
                         for d in range(len(polys[pos])))
                tot += co * mus[l]
            if tot != 0:
                ok = False
                firstbad = m0
                break
        return polys, ok, firstbad


def pshow(coeffs):
    return " + ".join("(%s)m^%d" % (c, d) for d, c in enumerate(coeffs) if c != 0) or "0"


print("=" * 78)
print("THE LAPLACE MOMENT ENGINE — general executed telescoping")
print("=" * 78)

F = Fraction
BATTERY = [
    ("H1: aZ + b + cW", [(F(3, 2), 1, 0), (F(-2, 3), 0, 0), (F(5, 4), 0, 1)]),
    ("H2: aZ + bW^2 + c", [(F(3, 2), 1, 0), (F(-2, 3), 0, 2), (F(5, 4), 0, 0)]),
    ("H4: aZ + bZW + cW", [(F(3, 2), 1, 0), (F(-2, 3), 1, 1), (F(5, 4), 0, 1)]),
    ("NEW: aZ^2 + bZW + cW (span 2,0,-1)", [(F(3, 2), 2, 0), (F(-2, 3), 1, 1), (F(5, 4), 0, 1)]),
    ("NEW: aZ + bW^3", [(F(3, 2), 1, 0), (F(5, 4), 0, 3)]),
    ("hijack-flavor: ZW + Z^4W^2 + W", [(F(1), 1, 1), (F(1), 4, 2), (F(1), 0, 1)]),
]

for name, terms in BATTERY:
    eng = Engine(terms)
    print("\n--- %s ---" % name)
    import time as _t
    t0 = _t.time()
    if "Z^4" in name:
        polys, ok, bad = eng.recurrence(m0s=list(range(8, 14)), levels=5, verify_to=24)
    else:
        polys, ok, bad = eng.recurrence(m0s=list(range(9, 15)), verify_to=32)
    print("  [%.1fs]" % (_t.time() - t0))
    if polys is None:
        print("  engine: no relation found in default window (raise limits)")
        continue
    L = len(polys)
    print("  recurrence order %d; coefficients (level offsets %s):" %
          (L - 1, list(range(-(L - 1), 1))))
    for pos in range(L):
        print("    q[%+d](m) = %s" % (pos - (L - 1), pshow(polys[pos])))
    print("  verified against exact moments: %s%s" %
          (ok, "" if ok else " (first fail m=%s)" % bad))
    lead = polys[-1]
    if len(lead) == 1:
        print("  leading coefficient CONSTANT -> finite moment test M = %d (all coefficients)" % (L - 1))
    else:
        print("  leading coefficient nonconstant: %s" % pshow(lead))
    # two-line nullcone read for small orders: mu_1..mu_{L-1} in terms of coeffs
    mus = [eng.mu(m) for m in range(1, L)]
    print("  first moments mu_1..mu_%d = %s" % (L - 1, ["%s" % x for x in mus]))

print("\n--- PARAMETRIC DEMO on aZ + b + cW: engine at 6 triples, fit q's in (a,b,c) ---")
import random
random.seed(7)
triples = [(F(1), F(1), F(1)), (F(2), F(1), F(3)), (F(1, 2), F(-1), F(1)),
           (F(3), F(2), F(-1)), (F(-1), F(1, 3), F(2)), (F(1), F(-2), F(5, 2))]
rows = []
for (a, b, c) in triples:
    eng = Engine([(a, 1, 0), (b, 0, 0), (c, 0, 1)])
    polys, ok, bad = eng.recurrence(m0s=list(range(8, 13)), levels=3, verify_to=22)
    rows.append(((a, b, c), polys, ok))
    print("  (a,b,c)=(%s,%s,%s): order %d, ok=%s, q[-1](m)=%s, q[-2](m)=%s" %
          (a, b, c, len(polys) - 1, ok, pshow(polys[-2]), pshow(polys[0])))
print("  prediction (S186 H1 exact law): mu_m = b mu_{m-1} + 4ac(m-1) mu_{m-2}")
print("  engine q[-1] should equal -b, q[-2] should equal -4ac(m-1): check per triple above.")

print("\nDONE.")
