#!/usr/bin/env python3
"""ln2_s112.py — Deep exploration of ln(2) in tournament theory"""
from math import log, atanh, pi, comb
from fractions import Fraction

ln2 = log(2)

print("ln(2) AND THE TOURNAMENT")
print("="*60)

print("""
THREE SERIES FROM THE NATURALS:

  ln(2)      = 1 - 1/2 + 1/3 - 1/4 + 1/5 - ...  (ALL naturals, alternating)
  pi/4       = 1 - 1/3 + 1/5 - 1/7 + ...          (ODD naturals, alternating)
  arctanh(1) = 1 + 1/3 + 1/5 + 1/7 + ...          (ODD naturals, positive, DIVERGES)

Tournaments use ODD naturals (arctanh).
Circles use ODD naturals alternating (arctan -> pi/4).
ln(2) uses ALL naturals alternating.
""")

print("="*60)
print("THE IDENTITY: arctanh(1/3) = ln(2)/2")
print("="*60)
print()
print(f"  Q(1/3) = (1 + 1/3)/(1 - 1/3) = (4/3)/(2/3) = 2")
print(f"  arctanh(1/3) = (1/2)*ln(Q(1/3)) = (1/2)*ln(2)")
print(f"  arctanh(1/3) = {atanh(1/3):.10f}")
print(f"  ln(2)/2      = {ln2/2:.10f}")
print(f"  Match: {abs(atanh(1/3) - ln2/2) < 1e-14}")
print()
print("  The coupling x = 1/3 gives Q = 2: the tournament alphabet.")
print("  At x = 1/3, each interaction carries ln(2)/2 nats: HALF a bit.")

print()
print("="*60)
print("Q(1/3)^m = 2^m: POWERS OF 2 FROM THE CAYLEY TRANSFORM")
print("="*60)
print()
print("  The master GF at x = 1/3:")
print("  Q(1/3)^m = 2^m = 1 + 2*sum g_k(m)/3^k")
print("  => sum g_k(m)/3^k = (2^m - 1)/2")
print()
for m in [1, 2, 3, 5, 10]:
    lhs = sum(Fraction(1, 3**k) * sum(Fraction(comb(k-1,j-1)*comb(m,j))*2**(j-1)
              for j in range(1,min(k,m)+1)) for k in range(1, 25))
    rhs = Fraction(2**m - 1, 2)
    print(f"  m={m}: sum g_k/3^k = {float(lhs):.6f}, (2^m-1)/2 = {float(rhs):.1f}, match={lhs==rhs}")

print()
print("  PROVED: sum_{k>=1} g_k(m) / 3^k = (2^m - 1) / 2")

print()
print("="*60)
print("ln(2) = TOTAL EXCESS OF DIRECTION OVER SYMMETRY")
print("="*60)
print()
print("  ln(2) = (1 - 1/2) + (1/3 - 1/4) + (1/5 - 1/6) + ...")
print("        = sum_{k>=1} 1/((2k-1)(2k))")
print()
print("  Each term pairs ODD (directed) with EVEN (undirected):")
print("    1/1 - 1/2: direction at scale 1 minus symmetry at scale 2")
print("    1/3 - 1/4: direction at scale 3 minus symmetry at scale 4")
print("    1/5 - 1/6: direction at scale 5 minus symmetry at scale 6")
print()
print("  ln(2) = the total EXCESS of direction over symmetry")
print("  across all interaction scales.")
print()
print("  And ln(2) = the information content of one binary decision.")
print()
print("  THE INFORMATION IN A BINARY DECISION EQUALS THE TOTAL")
print("  EXCESS OF DIRECTION OVER SYMMETRY ACROSS ALL SCALES.")

print()
print("="*60)
print("THE FOUR EVALUATIONS OF Q")
print("="*60)
print()
print(f"  Q(0)   = 1      arctanh(0)   = 0          [no coupling]")
print(f"  Q(1/3) = 2      arctanh(1/3) = ln(2)/2    [binary alphabet]")
print(f"  Q(i)   = i      arctanh(i)   = i*pi/4     [circle]")
print(f"  Q(1)   = inf    arctanh(1)   = infinity    [full coupling]")
print()
print("  The four cardinal points of the Cayley transform:")
print("  0: nothing.  1/3: binary.  i: circle.  1: everything.")
print()
print("  The FOUR CONSTANTS:")
print(f"    0     (zero)")
print(f"    ln(2) = {ln2:.6f} (information)")
print(f"    pi    = {pi:.6f} (geometry)")
print(f"    inf   (totality)")
print()
print("  These four are produced by arctanh at 0, 1/3, i, 1.")
print("  They are the CARDINAL NUMBERS of comparison theory:")
print("  nothing, one bit, one circle, everything.")

print()
print("="*60)
print("THE TRILOGY: pi, ln(2), arctanh(1)")
print("="*60)
print()
print("  ALL three series use the reciprocal naturals 1/k:")
print()
print("  pi/4       = sum (-1)^{k+1} / (2k-1)  [ODD k, alternating]")
print("  ln(2)      = sum (-1)^{k+1} / k        [ALL k, alternating]")
print("  arctanh(1) = sum 1 / (2k-1)            [ODD k, positive, DIVERGES]")
print()
print("  Sign pattern determines convergence:")
print("    Alternating + odd only = CONVERGES to pi/4 (space)")
print("    Alternating + all      = CONVERGES to ln(2) (information)")
print("    Positive + odd only    = DIVERGES (time)")
print()
print("  pi = geometry of space")
print("  ln(2) = geometry of information")
print("  arctanh(1) = geometry of time (infinite)")
print()
print("  Together: space + information + time = the complete universe")
print("  of binary comparison.")

print()
print("="*60)
print("ln(2) AS THE MIDPOINT")
print("="*60)
print()
print("  ln(2) sits BETWEEN pi/4 and arctanh(1):")
print()
print(f"    pi/4       = {pi/4:.6f}  (space)")
print(f"    ln(2)      = {ln2:.6f}  (information)")
print(f"    arctanh(1) = infinity    (time)")
print()
print("  ln(2) > pi/4: information exceeds spatial extent.")
print("  ln(2) < infinity: information is finite.")
print()
print("  ln(2) is the FINITE measure of what is DIRECTIONAL")
print("  in the comparison. It is what remains after the spatial")
print("  part (pi/4) is subtracted from the infinite temporal part.")
print()
print("  More precisely: the EVEN terms of the alternating harmonic")
print("  series (1/2 + 1/4 + 1/6 + ...) also diverge.")
print("  But paired with the odd terms: 1-1/2, 1/3-1/4, 1/5-1/6, ...")
print("  the excess is FINITE and equals ln(2).")
print()
print("  Infinity - infinity = ln(2).")
print("  Direction minus symmetry = one bit.")

print()
print("="*60)
print("CONSERVATION OF INFORMATION")
print("="*60)
print()
print("  Q(1/3) = 2,  Q(-1/3) = 1/2")
print("  Q(1/3) * Q(-1/3) = 2 * 1/2 = 1")
print()
print("  ln(Q(1/3)) + ln(Q(-1/3)) = ln(2) + ln(1/2) = 0")
print()
print("  A tournament and its complement carry EQUAL AND OPPOSITE")
print("  information. The total is zero: CONSERVATION.")
print()
print("  This is why Redei's theorem works:")
print("  H(T) is odd because the information in the last bit")
print("  is FIXED (= 0 entropy), and the conservation law")
print("  forces this fixedness across all tournaments.")

print()
print("="*60)
print("THE DEEPEST ln(2) IDENTITY")
print("="*60)
print()
print("  2 * arctanh(1/3) = ln(2)")
print()
print("  In tournament language:")
print("    The coupling 1/3 balances win, lose, and memory (3 states).")
print("    At this balance: arctanh = half a bit.")
print("    Two such half-bits = one full bit = ln(2).")
print("    The factor 2 is the BINARY: two halves make a whole.")
print()
print("  In the master GF:")
print("    Q(1/3)^m = 2^m")
print("    g_k evaluated at x=1/3 gives powers of 2.")
print("    The Delannoy weights at ternary coupling = binary powers.")
print()
print("  3 generates 2 through arctanh.")
print("  The ternary creates the binary.")
print("  And the bridge between them is ln(2)/2: half a bit,")
print("  the minimal quantum of directional information.")
