#!/usr/bin/env python3
"""
lonely_runner_bohr_descent_s362.py

codex-2026-05-30 S362

Formal probe for the LRC Bohr-boundary descent program.

The script has three jobs:

1. verify THM-358's initial-segment unit skeleton computationally;
2. build a finite endpoint/interval protection core and run a conservative
   leaf-peeling process;
3. record quotient-layer data for the tight and near-tight examples used in
   the recent LRC sessions.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from fractions import Fraction
from importlib.machinery import SourceFileLoader
from itertools import combinations
from math import gcd
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
S356 = SourceFileLoader(
    "lonely_runner_residue_probe_s356",
    str(ROOT / "04-computation" / "lonely_runner_residue_probe_s356.py"),
).load_module()
S360 = SourceFileLoader(
    "lonely_runner_endpoint_protection_s360",
    str(ROOT / "04-computation" / "lonely_runner_endpoint_protection_s360.py"),
).load_module()

ONE = Fraction(1, 1)


@dataclass(frozen=True, order=True)
class IntervalKey:
    speed: int
    center: int


@dataclass(frozen=True)
class PeelLayer:
    step: int
    removed_endpoints: int
    removed_intervals: int
    remaining_endpoints: int
    remaining_intervals: int
    removed_gcd_residue: int
    removed_subgroup_modulus: int


@dataclass(frozen=True)
class DescentSummary:
    speeds: tuple[int, ...]
    n: int
    q: int
    classification: str
    forbidden_length: Fraction
    endpoint_count: int
    interval_count: int
    unprotected_count: int
    unit_skeleton: bool
    quotient_layer: str
    peel_layers: tuple[PeelLayer, ...]
    core_endpoint_count: int
    core_interval_count: int
    core_gcd_residue: int
    core_subgroup_modulus: int


def circle_point(x: Fraction) -> Fraction:
    return x % ONE


def circular_distance(x: Fraction, y: Fraction) -> Fraction:
    diff = circle_point(x - y)
    return min(diff, ONE - diff)


def fmt_frac(x: Fraction | None) -> str:
    return S356.fmt_frac(x)


def unit_values(n: int) -> set[Fraction]:
    return {Fraction(a, n) for a in range(1, n) if gcd(a, n) == 1}


def residue(q: int, t: Fraction) -> int:
    return int((circle_point(t) * q) % q)


def subgroup_modulus(q: int, values: set[Fraction]) -> int:
    """Return the order of the subgroup generated by residues of values."""

    if not values:
        return 1
    g = q
    for value in values:
        g = gcd(g, residue(q, value))
    return q // g


def residue_gcd(q: int, values: set[Fraction]) -> int:
    if not values:
        return q
    g = q
    for value in values:
        g = gcd(g, residue(q, value))
    return g


def quotient_layer(n: int, q: int, values: set[Fraction]) -> str:
    if not values:
        return "empty"
    if all((value * n).denominator == 1 for value in values):
        residues = sorted(int((value * n) % n) for value in values)
        units = sorted(a for a in range(1, n) if gcd(a, n) == 1)
        if residues == units:
            return f"unit_mod_{n}"
        return f"mod_{n}_residues_{residues}"
    denoms = sorted({value.denominator for value in values})
    if len(denoms) <= 4:
        return "higher_denoms_" + ",".join(str(d) for d in denoms)
    return f"higher_denoms_{len(denoms)}_types"


def interval_keys(speeds: tuple[int, ...]) -> list[IntervalKey]:
    return [IntervalKey(v, a) for v in speeds for a in range(v)]


def interval_center(interval: IntervalKey) -> Fraction:
    return Fraction(interval.center, interval.speed)


def interval_radius(speeds: tuple[int, ...], interval: IntervalKey) -> Fraction:
    return Fraction(1, (len(speeds) + 1) * interval.speed)


def interval_endpoint_values(
    speeds: tuple[int, ...], interval: IntervalKey
) -> tuple[Fraction, Fraction]:
    center = interval_center(interval)
    radius = interval_radius(speeds, interval)
    return (circle_point(center - radius), circle_point(center + radius))


def interval_contains_endpoint(
    speeds: tuple[int, ...], interval: IntervalKey, endpoint: Fraction
) -> bool:
    return circular_distance(endpoint, interval_center(interval)) < interval_radius(
        speeds, interval
    )


def build_endpoint_system(
    speeds: tuple[int, ...],
) -> tuple[
    set[Fraction],
    set[IntervalKey],
    dict[Fraction, set[IntervalKey]],
    dict[Fraction, set[IntervalKey]],
    dict[IntervalKey, set[Fraction]],
]:
    intervals = set(interval_keys(speeds))
    endpoints: set[Fraction] = set()
    owners: dict[Fraction, set[IntervalKey]] = {}
    boundary: dict[IntervalKey, set[Fraction]] = {}

    for interval in intervals:
        values = set(interval_endpoint_values(speeds, interval))
        boundary[interval] = values
        for value in values:
            endpoints.add(value)
            owners.setdefault(value, set()).add(interval)

    protectors: dict[Fraction, set[IntervalKey]] = {value: set() for value in endpoints}
    for value in endpoints:
        for interval in intervals:
            if interval_contains_endpoint(speeds, interval, value):
                protectors[value].add(interval)

    return endpoints, intervals, owners, protectors, boundary


def peel_protection_core(
    q: int,
    endpoints: set[Fraction],
    intervals: set[IntervalKey],
    protectors: dict[Fraction, set[IntervalKey]],
    boundary: dict[IntervalKey, set[Fraction]],
) -> tuple[tuple[PeelLayer, ...], set[Fraction], set[IntervalKey]]:
    remaining_endpoints = set(endpoints)
    remaining_intervals = set(intervals)
    layers: list[PeelLayer] = []
    step = 0

    while True:
        dead_endpoints = {
            endpoint
            for endpoint in remaining_endpoints
            if not (protectors[endpoint] & remaining_intervals)
        }
        if not dead_endpoints:
            break

        next_endpoints = remaining_endpoints - dead_endpoints
        dead_intervals = {
            interval
            for interval in remaining_intervals
            if boundary[interval] & dead_endpoints
        }
        next_intervals = remaining_intervals - dead_intervals

        layers.append(
            PeelLayer(
                step=step,
                removed_endpoints=len(dead_endpoints),
                removed_intervals=len(dead_intervals),
                remaining_endpoints=len(next_endpoints),
                remaining_intervals=len(next_intervals),
                removed_gcd_residue=residue_gcd(q, dead_endpoints),
                removed_subgroup_modulus=subgroup_modulus(q, dead_endpoints),
            )
        )
        remaining_endpoints = next_endpoints
        remaining_intervals = next_intervals
        step += 1

    return tuple(layers), remaining_endpoints, remaining_intervals


def summarize(raw_speeds: list[int]) -> DescentSummary:
    protection = S360.summarize(raw_speeds)
    speeds = protection.speeds
    n = len(speeds) + 1
    q = protection.boundary_modulus
    endpoints, intervals, _owners, protectors, boundary = build_endpoint_system(speeds)
    unprotected = {
        endpoint for endpoint in endpoints if not protectors[endpoint]
    }
    layers, core_endpoints, core_intervals = peel_protection_core(
        q, endpoints, intervals, protectors, boundary
    )
    return DescentSummary(
        speeds=speeds,
        n=n,
        q=q,
        classification=protection.classification,
        forbidden_length=protection.forbidden_length,
        endpoint_count=len(endpoints),
        interval_count=len(intervals),
        unprotected_count=len(unprotected),
        unit_skeleton=unprotected == unit_values(n),
        quotient_layer=quotient_layer(n, q, unprotected),
        peel_layers=layers,
        core_endpoint_count=len(core_endpoints),
        core_interval_count=len(core_intervals),
        core_gcd_residue=residue_gcd(q, core_endpoints),
        core_subgroup_modulus=subgroup_modulus(q, core_endpoints),
    )


def print_summary(label: str, speeds: list[int]) -> None:
    summary = summarize(speeds)
    print(f"[{label}]")
    print(f"  speeds={summary.speeds}")
    print(
        "  "
        f"classification={summary.classification} "
        f"forbidden_length={fmt_frac(summary.forbidden_length)} "
        f"n={summary.n} Q={summary.q}"
    )
    print(
        "  "
        f"endpoints={summary.endpoint_count} intervals={summary.interval_count} "
        f"unprotected={summary.unprotected_count} "
        f"unit_skeleton={summary.unit_skeleton} "
        f"quotient_layer={summary.quotient_layer}"
    )
    print(
        "  "
        f"peel_depth={len(summary.peel_layers)} "
        f"core_endpoints={summary.core_endpoint_count} "
        f"core_intervals={summary.core_interval_count} "
        f"core_subgroup_modulus={summary.core_subgroup_modulus}"
    )
    if summary.peel_layers:
        for layer in summary.peel_layers[:8]:
            print(
                "    "
                f"layer={layer.step} "
                f"removed_E={layer.removed_endpoints} "
                f"removed_I={layer.removed_intervals} "
                f"remaining_E={layer.remaining_endpoints} "
                f"remaining_I={layer.remaining_intervals} "
                f"removed_subgroup_modulus={layer.removed_subgroup_modulus}"
            )
    print()


def verify_initial_segments(max_n: int = 36) -> None:
    failures = []
    for n in range(2, max_n + 1):
        summary = summarize(list(range(1, n)))
        if (
            summary.classification != "boundary_only"
            or not summary.unit_skeleton
            or summary.core_endpoint_count != 0
        ):
            failures.append((n, summary))

    print("THM-358 computational audit")
    print(f"  checked_initial_segments_n=2..{max_n}")
    print(f"  failures={len(failures)}")
    if failures:
        for n, summary in failures[:5]:
            print(
                "  "
                f"n={n} classification={summary.classification} "
                f"unit_skeleton={summary.unit_skeleton} "
                f"core_endpoints={summary.core_endpoint_count}"
            )
    print()


def scan_full_measure_boxes() -> None:
    print("Full-measure primitive-box peeling audit")
    for k, max_speed in [
        (3, 24),
        (4, 24),
        (5, 20),
        (6, 16),
        (7, 14),
    ]:
        full_measure = 0
        nonempty_core = 0
        unit_skeleton = 0
        depth_hist: Counter[int] = Counter()
        core_hist: Counter[int] = Counter()
        examples: list[DescentSummary] = []
        for combo in combinations(range(1, max_speed + 1), k):
            if not S360.primitive(combo):
                continue
            row = S356.report("scan", list(combo))
            if row.forbidden_length < ONE:
                continue
            full_measure += 1
            summary = summarize(list(combo))
            unit_skeleton += int(summary.unit_skeleton)
            depth_hist[len(summary.peel_layers)] += 1
            core_hist[summary.core_endpoint_count] += 1
            if summary.core_endpoint_count:
                nonempty_core += 1
                examples.append(summary)

        print(f"  k={k} max_speed={max_speed}")
        print(f"    full_measure={full_measure}")
        print(f"    unit_skeleton={unit_skeleton}/{full_measure}")
        print(f"    nonempty_cores={nonempty_core}")
        print(f"    peel_depth_hist={dict(sorted(depth_hist.items()))}")
        print(f"    core_endpoint_hist={dict(sorted(core_hist.items()))}")
        if examples:
            for summary in examples[:3]:
                print(
                    "    nonempty_example="
                    f"{summary.speeds} core_E={summary.core_endpoint_count} "
                    f"core_I={summary.core_interval_count}"
                )
    print()


def main() -> None:
    print("Lonely Runner Bohr-boundary descent probe (codex-2026-05-30 S362)")
    print("Exact Fraction arithmetic; endpoint/interval core peeling.\n")

    verify_initial_segments()

    examples = [
        ("initial k=3", [1, 2, 3]),
        ("initial k=7", [1, 2, 3, 4, 5, 6, 7]),
        ("sporadic n=5", [1, 3, 4, 7]),
        ("sporadic n=6", [1, 3, 4, 5, 9]),
        ("sporadic n=8 A", [1, 4, 5, 6, 7, 11, 13]),
        ("sporadic n=8 B", [1, 2, 3, 4, 5, 7, 12]),
        ("near tight positive k=4", [7, 10, 17, 24]),
        ("CRT positive k=8", [5, 8, 13, 21, 34, 55, 89, 144]),
    ]
    for label, speeds in examples:
        print_summary(label, speeds)

    scan_full_measure_boxes()

    print("Interpretation")
    print("  The proved initial-segment equality case is the unit quotient layer.")
    print("  In every scanned full-measure case, conservative endpoint/interval")
    print("  peeling empties the protection core. No all-protected core appeared.")


if __name__ == "__main__":
    main()
