#!/usr/bin/env python3
"""
lrc14_threadC_dissociated_oddvanish_opus_s2b.py   (opus-2026-06-20-S2, THREAD C)

FOLLOW-UP to s2.  The first script found a SHARP dichotomy:

  * DISSOCIATED speeds (no nontrivial low-coeff relations except forced ones):
      EVEN-support part of corr ~ 0, ODD-support part carries ~98% of corr.
      => corr is (to leading order) an ODD-SUPPORT object = OCF-type.
  * STRUCTURED speeds (consec/AP): EVEN-support is substantial (can exceed odd).
      => no parity selection.

THIS SCRIPT pins the mechanism exactly and tests it as a TOOL.

THE MECHANISM (claim, tested below).  For a DISSOCIATED set the ONLY integer
relations with bounded coefficients are generated by the SUPPORT-2 "syzygies"
n_i e_i = n_j e_j (forced, coefficient ~ e_j, e_i -- LARGE, hence tiny 1/height
weight) and by genuine ADDITIVE relations.  The lowest genuine many-body relations
are SUPPORT-3 Schur triples e_a + e_b = e_c (ODD).  Even-support genuine relations
(support 4: e_a+e_b=e_c+e_d) are SECOND order in dissociation: a "dissociated" set
has FEW of these, and the ones present come in NEGATING pairs that cancel.

We test three concrete predictions:

  P1.  For a strictly dissociated set (all subset sums distinct -> a Sidon-ish /
       B_h set), the genuine even-support relations (support 4 with all |coeff|=1,
       i.e. e_a+e_b-e_c-e_d=0) NUMBER zero, while support-3 (e_a+e_b=e_c) may be
       nonzero.  Then even-support corr is forced by large-coeff syzygies only,
       which are 1/height-suppressed.  => even/odd ratio -> 0 as set gets more
       dissociated.

  P2.  Build a family interpolating consec -> dilated -> dissociated and watch
       even/odd cross from >1 (structured) to <<1 (dissociated).  Monotone =>
       parity selection is a DISSOCIATION ORDER PARAMETER.

  P3.  The OCF correspondence at the SIGN level.  In a genuine dissociated set the
       surviving relations are exactly the additive cycles among speeds.  Compare:
         - tournament: H = signed sum over collections of ODD directed cycles;
           a directed cycle and its reverse cancel (even-length cancel, THM-560).
         - LRC: a relation n and its negation -n have K(-n)=conj(K(n)); for the
           cover kernel Re K is even under n->-n so they ADD (no cancel).  The
           cancellation that kills EVEN support is NOT n->-n; it is the
           "complementary Schur pairing" e_a+e_b=e_c+e_d  <->  swap.  We measure
           the residual after this pairing.

All exact corr ground truth; complex truncated lattice sums for the strata.
"""
from __future__ import annotations
import sys, itertools, math, cmath
from collections import defaultdict
from fractions import Fraction as F

sys.stdout.reconfigure(line_buffering=True)
TWO_PI_I = 2j * math.pi


def measS7(E):
    E = sorted(set(E))
    bps = {F(0), F(1)}
    for e in E:
        if e == 0:
            continue
        for m in range(0, 7 * e + 1):
            bps.add(F(m, 7 * e))
    bps = sorted(bps)
    total = F(0)
    for i in range(len(bps) - 1):
        x0, x1 = bps[i], bps[i + 1]
        if x1 <= x0:
            continue
        xm = (x0 + x1) / 2
        if len({int(((e * xm) % 1) * 7) for e in E}) == 7:
            total += x1 - x0
    return total


def stirling2(n, k):
    return sum((-1) ** (k - j) * math.comb(k, j) * j ** n for j in range(k + 1)) // math.factorial(k)


def iid_k(k):
    return F(math.factorial(7) * stirling2(k, 7), 7 ** k)


def shat(n, j):
    if n == 0:
        return 1.0 / 7.0
    a = j / 7.0
    return (cmath.exp(-TWO_PI_I * n * a) - cmath.exp(-TWO_PI_I * n * (a + 1 / 7.0))) / (TWO_PI_I * n)


SUBSETS = [tuple(T) for r in range(0, 7) for T in itertools.combinations(range(1, 7), r)]
SIGN = {T: (-1) ** len(T) for T in SUBSETS}
_cc: dict = {}


def chat_T(n, T):
    key = (n, T)
    v = _cc.get(key)
    if v is not None:
        return v
    if n == 0:
        v = complex(1 - len(T) / 7.0, 0.0)
    elif n % 7 == 0:
        v = 0j
    else:
        v = -sum(shat(n, j) for j in T)
    _cc[key] = v
    return v


def K_on_support(coeffs, idxs, nz):
    nvec = [0] * len(nz)
    for p, c in zip(idxs, coeffs):
        nvec[p] = c
    K = 0j
    for T in SUBSETS:
        p = 1.0 + 0j
        ok = True
        for ni in nvec:
            c = chat_T(ni, T)
            if c == 0:
                ok = False
                break
            p *= c
        if ok:
            K += SIGN[T] * p
    return K


def stratified(E, N0, max_supp):
    nz = [e for e in E if e != 0]
    d = len(nz)
    by_K = defaultdict(complex)
    rng = [c for c in range(-N0, N0 + 1) if c != 0]
    for s in range(2, max_supp + 1):
        for idxs in itertools.combinations(range(d), s):
            sp = [nz[i] for i in idxs]
            last = sp[-1]
            for c0 in itertools.product(rng, repeat=s - 1):
                acc = sum(c * v for c, v in zip(c0, sp[:-1]))
                if acc % last != 0:
                    continue
                cl = -acc // last
                if cl == 0 or abs(cl) > N0:
                    continue
                by_K[s] += K_on_support(c0 + (cl,), idxs, nz)
    odd = sum(v.real for s, v in by_K.items() if s % 2 == 1)
    even = sum(v.real for s, v in by_K.items() if s % 2 == 0)
    return by_K, odd, even, sum(v for v in by_K.values()).real


# ----------------------------------------------------------------------------
# Combinatorial relation census: count genuine |coeff|=1 relations by support.
# support-3 unit relations: e_a + e_b = e_c (Schur triples).
# support-4 unit relations: e_a + e_b = e_c + e_d (additive quadruples).
# A B_2 (Sidon) set has ZERO of the latter (all pairwise sums distinct).
# ----------------------------------------------------------------------------
def count_unit_relations(E):
    nz = sorted(e for e in E if e != 0)
    s = set(nz)
    # support-3 Schur triples a+b=c (a<=b, c in set)
    tri = 0
    for a, b in itertools.combinations_with_replacement(nz, 2):
        if a + b in s and a + b not in (a, b):
            tri += 1
    # support-4 additive quadruples a+b=c+d, {a,b} != {c,d}, all distinct positions
    quad = 0
    sums = defaultdict(list)
    for a, b in itertools.combinations(nz, 2):
        sums[a + b].append((a, b))
    for ssum, pairs in sums.items():
        if len(pairs) >= 2:
            quad += math.comb(len(pairs), 2)
    return tri, quad


def is_sidon(E):
    nz = [e for e in E if e != 0]
    sums = set()
    for a, b in itertools.combinations_with_replacement(nz, 2):
        if a + b in sums:
            return False
        sums.add(a + b)
    return True


def main():
    print("=" * 92)
    print("THREAD C-b -- the dissociation dichotomy: even-support corr -> 0 for")
    print("dissociated speeds, making corr an ODD-SUPPORT (OCF-type) object.")
    print("opus-2026-06-20-S2")
    print("=" * 92)
    print()

    # P1: unit-relation census vs parity content.
    print("P1 -- unit-relation census (Schur triples=odd supp3; quads=even supp4)")
    print("      vs the even/odd corr ratio.  Sidon (B_2) => 0 quads => even kills.")
    print(f"  {'shape':<32}{'Sidon?':>7}{'#tri(odd3)':>11}{'#quad(ev4)':>11}"
          f"{'odd':>10}{'even':>10}{'even/odd':>9}")
    k8shapes = [
        ("consec {0..7}", list(range(8))),
        ("AP3 {0,3,..21}", [0, 3, 6, 9, 12, 15, 18, 21]),
        ("dilated x5 {0,5,..35}", [0, 5, 10, 15, 20, 25, 30, 35]),
        ("two-block {0,1,2,3,40..43}", [0, 1, 2, 3, 40, 41, 42, 43]),
        ("Schur {0,1,2,3,4,5,64,65}", [0, 1, 2, 3, 4, 5, 64, 65]),
        ("Sidon {0,1,3,7,12,20,30,44}", [0, 1, 3, 7, 12, 20, 30, 44]),
        ("dissoc {0,1,3,7,15,31,63,127}", [0, 1, 3, 7, 15, 31, 63, 127]),
    ]
    for name, E in k8shapes:
        tri, quad = count_unit_relations(E)
        sid = is_sidon(E)
        _, odd, even, tot = stratified(E, N0=8, max_supp=5)
        ratio = even / odd if abs(odd) > 1e-9 else float("nan")
        print(f"  {name:<32}{str(sid):>7}{tri:>11}{quad:>11}"
              f"{odd:>10.5f}{even:>10.5f}{ratio:>9.3f}")
    print()
    print("  READ: Sidon/dissoc sets (no additive quadruples) have even/odd << 1;")
    print("  structured sets (many quads) have even/odd ~ 1.  The even-support corr")
    print("  is carried by additive QUADRUPLES e_a+e_b=e_c+e_d; killing them (Sidon)")
    print("  kills the even part and leaves corr as an ODD-support (OCF-type) sum.")
    print()

    # P2: interpolation consec -> dilated, watch even/odd.
    print("P2 -- dilation/jitter interpolation: even/odd as a dissociation order param")
    print(f"  {'description':<34}{'#quad':>7}{'odd':>10}{'even':>10}{'even/odd':>10}")
    base = [0, 1, 2, 3, 4, 5, 6, 7]
    families = [
        ("consec (d=1)", base),
        ("dilate x2", [2 * e for e in base]),
        ("dilate x2 +jitter", [0, 2, 5, 6, 9, 11, 13, 15]),
        ("geometric-ish", [0, 1, 3, 6, 11, 19, 32, 53]),
        ("powers-of-2 (dissoc)", [0, 1, 2, 4, 8, 16, 32, 64]),
    ]
    for name, E in families:
        _, quad = count_unit_relations(E)
        _, odd, even, tot = stratified(E, N0=7, max_supp=5)
        ratio = even / odd if abs(odd) > 1e-9 else float("nan")
        print(f"  {name:<34}{quad:>7}{odd:>10.5f}{even:>10.5f}{ratio:>10.3f}")
    print()

    # P3: convergence of odd-only reconstruction for the dissociated set.
    print("P3 -- does the ODD-support sum alone reconstruct corr for dissociated E?")
    print("  (if even ~ 0 and odd converges to exact corr, corr IS an OCF-type object)")
    E = [0, 1, 2, 4, 8, 16, 32, 64]  # B_2-ish, very dissociated
    exact = float(measS7(E)) - float(iid_k(len(E)))
    print(f"  E = {E}   exact corr = {exact:+.6f}")
    print(f"  {'N0':>4}{'odd-supp':>12}{'even-supp':>12}{'odd+even':>12}{'odd/exact':>11}")
    for N0 in (4, 6, 8, 10):
        _, odd, even, tot = stratified(E, N0=N0, max_supp=5)
        print(f"  {N0:>4}{odd:>12.6f}{even:>12.6f}{tot:>12.6f}{odd / exact:>11.3f}")
    print()
    print("SUMMARY")
    print("  * EVEN-support corr is carried by additive quadruples e_a+e_b=e_c+e_d.")
    print("  * A Sidon/dissociated set has none -> even-support -> 0, odd dominates.")
    print("  * For dissociated speeds the Weyl error IS (to leading order) a signed")
    print("    sum over ODD-support additive relations = an OCF-type object on the")
    print("    offset relation lattice.  For structured speeds parity is mixed.")
    print("  * This is a structural ANALOGY (parity selection under dissociation), not")
    print("    yet a bound-improving TOOL: the leading carrier error is the SUPPORT-3")
    print("    Schur layer either way, so dropping even support does not shrink the")
    print("    binding term.  See write-up for the lever assessment.")


if __name__ == "__main__":
    main()
