#include <algorithm>
#include <array>
#include <bit>
#include <cstdint>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <set>
#include <sstream>
#include <string>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>

// Independent exact referee for the q=50 zero-original minimal-anchor lane.
//
// This implementation deliberately starts from the circle arrangement.  It
// does not consume a repair-edge list, anchor list, cover list, or body list.
// Every wall has the form (14k+1)/(14s) or (14k+13)/(14s), and all lengths
// are accumulated on their common integer ruler.  Repair layers are then
// generated by literal fixed-cardinality deletion enumeration.  Hitting sets
// are checked by complete combination enumeration rather than a recursive
// transversal certificate search.

namespace {

using Mask = std::uint32_t;
using I64 = std::int64_t;
using U64 = std::uint64_t;

constexpr std::array<int, 30> P = {
    8, 10, 15, 16, 20, 30, 40, 42, 60, 63,
    80, 84, 85, 88, 95, 120, 126, 132, 143, 145,
    168, 170, 176, 190, 193, 240, 252, 264, 286, 290};
constexpr int Q = 50;
constexpr std::array<int, 3> A0 = {120, 126, 143};
constexpr std::uint16_t FULL_DIVISOR_MASK = (1u << 13) - 1u;

std::uint16_t divisor_mask(int value) {
  std::uint16_t result = 0;
  for (int m = 2; m <= 14; ++m) {
    if (value % m == 0) result |= std::uint16_t(1u << (m - 2));
  }
  return result;
}

bool is_original_value(int value) {
  return std::find(A0.begin(), A0.end(), value) != A0.end();
}

std::string mask_string(Mask mask) {
  std::ostringstream out;
  out << "{";
  bool first = true;
  for (int i = 0; i < int(P.size()); ++i) {
    if ((mask & (Mask(1) << i)) == 0) continue;
    if (!first) out << ",";
    first = false;
    out << P[i];
  }
  out << "}";
  return out.str();
}

U64 fnv1a_byte(U64 h, std::uint8_t byte) {
  constexpr U64 prime = 1099511628211ULL;
  h ^= byte;
  h *= prime;
  return h;
}

U64 fnv1a_u32(U64 h, std::uint32_t value) {
  for (int shift = 0; shift < 32; shift += 8) {
    h = fnv1a_byte(h, std::uint8_t((value >> shift) & 0xffu));
  }
  return h;
}

struct Arrangement {
  I64 ruler = 1;
  std::size_t wall_count = 0;
  std::size_t atom_count = 0;
  std::unordered_map<Mask, I64> q_safe_weight;

  Arrangement() {
    std::vector<int> speeds(P.begin(), P.end());
    speeds.push_back(Q);
    for (int speed : speeds) {
      const I64 term = I64(14) * speed;
      ruler = std::lcm(ruler, term);
    }

    std::vector<I64> walls = {0, ruler};
    for (int speed : speeds) {
      const I64 denominator = I64(14) * speed;
      const I64 scale = ruler / denominator;
      for (int k = 0; k < speed; ++k) {
        walls.push_back(I64(14 * k + 1) * scale);
        walls.push_back(I64(14 * k + 13) * scale);
      }
    }
    std::sort(walls.begin(), walls.end());
    walls.erase(std::unique(walls.begin(), walls.end()), walls.end());
    wall_count = walls.size();
    atom_count = walls.size() - 1;

    q_safe_weight.reserve(16384);
    q_safe_weight.max_load_factor(0.65f);
    const I64 twice_ruler = I64(2) * ruler;
    auto unsafe_at_midpoint = [twice_ruler](int speed, I64 midpoint_numerator) {
      const I64 residue = I64((__int128(speed) * midpoint_numerator) % twice_ruler);
      const I64 distance = std::min(residue, twice_ruler - residue);
      return I64(14) * distance < twice_ruler;
    };

    for (std::size_t j = 0; j + 1 < walls.size(); ++j) {
      const I64 left = walls[j];
      const I64 right = walls[j + 1];
      const I64 midpoint_numerator = left + right;  // denominator 2*ruler
      if (unsafe_at_midpoint(Q, midpoint_numerator)) continue;
      Mask unsafe = 0;
      for (int i = 0; i < int(P.size()); ++i) {
        if (unsafe_at_midpoint(P[i], midpoint_numerator)) {
          unsafe |= Mask(1) << i;
        }
      }
      q_safe_weight[unsafe] += right - left;
    }
  }

  I64 mass_numerator(Mask deletion) const {
    I64 total = 0;
    Mask sub = deletion;
    while (true) {
      const auto found = q_safe_weight.find(sub);
      if (found != q_safe_weight.end()) total += found->second;
      if (sub == 0) break;
      sub = (sub - 1) & deletion;
    }
    return total;
  }
};

struct EdgeLayer {
  int depth = 0;
  U64 candidates = 0;
  U64 equality_count = 0;
  I64 minimum_edge_delta = std::numeric_limits<I64>::max();
  I64 maximum_nonedge_delta = std::numeric_limits<I64>::min();
  std::vector<Mask> edges;
  U64 bytewise_fnv1a64 = 14695981039346656037ULL;
};

template <class Callback>
void combinations_from_indices(const std::vector<int>& indices, int choose,
                               Callback&& callback) {
  std::function<void(int, int, Mask)> visit = [&](int start, int left, Mask mask) {
    if (left == 0) {
      callback(mask);
      return;
    }
    const int last = int(indices.size()) - left;
    for (int j = start; j <= last; ++j) {
      visit(j + 1, left - 1, mask | (Mask(1) << indices[j]));
    }
  };
  visit(0, choose, 0);
}

EdgeLayer build_edge_layer(const Arrangement& arrangement, int depth) {
  EdgeLayer layer;
  layer.depth = depth;
  std::vector<int> all_indices(P.size());
  std::iota(all_indices.begin(), all_indices.end(), 0);
  combinations_from_indices(all_indices, depth, [&](Mask deletion) {
    ++layer.candidates;
    const I64 numerator = arrangement.mass_numerator(deletion);
    const I64 delta = I64(63) * numerator - I64(4) * arrangement.ruler;
    if (delta >= 0) {
      layer.edges.push_back(deletion);
      layer.minimum_edge_delta = std::min(layer.minimum_edge_delta, delta);
      if (delta == 0) ++layer.equality_count;
    } else {
      layer.maximum_nonedge_delta = std::max(layer.maximum_nonedge_delta, delta);
    }
  });
  for (Mask edge : layer.edges) {
    layer.bytewise_fnv1a64 = fnv1a_u32(layer.bytewise_fnv1a64, edge);
  }
  return layer;
}

bool primitive_divisor_complete(Mask mask) {
  int g = 0;
  std::uint16_t coverage = 0;
  for (int i = 0; i < int(P.size()); ++i) {
    if ((mask & (Mask(1) << i)) == 0) continue;
    g = std::gcd(g, P[i]);
    coverage |= divisor_mask(P[i]);
  }
  return g == 1 && coverage == FULL_DIVISOR_MASK;
}

struct MinimalAnchorCensus {
  std::map<int, std::vector<Mask>> by_size;
  U64 search_nodes = 0;
  U64 valid_stop_nodes = 0;
};

MinimalAnchorCensus find_all_minimal_anchors() {
  MinimalAnchorCensus census;
  int forced_index = -1;
  std::vector<int> others;
  for (int i = 0; i < int(P.size()); ++i) {
    if (is_original_value(P[i])) continue;
    if (P[i] == 286) forced_index = i;
    else others.push_back(i);
  }
  if (forced_index < 0) throw std::runtime_error("286 absent from U");
  for (int i = 0; i < int(P.size()); ++i) {
    if (is_original_value(P[i]) || i == forced_index) continue;
    if (P[i] % 13 == 0) throw std::runtime_error("unexpected second 13-pin in U");
  }

  std::vector<std::uint16_t> suffix_coverage(others.size() + 1, 0);
  std::vector<int> suffix_gcd(others.size() + 1, 0);
  for (int pos = int(others.size()) - 1; pos >= 0; --pos) {
    suffix_coverage[pos] = suffix_coverage[pos + 1] | divisor_mask(P[others[pos]]);
    suffix_gcd[pos] = std::gcd(suffix_gcd[pos + 1], P[others[pos]]);
  }

  const Mask forced_mask = Mask(1) << forced_index;
  const std::uint16_t forced_coverage = divisor_mask(P[forced_index]);
  std::function<void(int, Mask, std::uint16_t, int)> visit =
      [&](int pos, Mask mask, std::uint16_t coverage, int g) {
        ++census.search_nodes;
        if (coverage == FULL_DIVISOR_MASK && g == 1) {
          ++census.valid_stop_nodes;
          bool minimal = true;
          Mask remaining = mask;
          while (remaining != 0) {
            const Mask bit = remaining & (~remaining + 1u);
            if (primitive_divisor_complete(mask ^ bit)) {
              minimal = false;
              break;
            }
            remaining ^= bit;
          }
          if (minimal) census.by_size[std::popcount(mask)].push_back(mask);
          return;  // Every descendant contains this valid set.
        }
        if (pos == int(others.size())) return;
        if ((coverage | suffix_coverage[pos]) != FULL_DIVISOR_MASK) return;
        if (std::gcd(g, suffix_gcd[pos]) != 1) return;

        visit(pos + 1, mask, coverage, g);
        const int index = others[pos];
        visit(pos + 1, mask | (Mask(1) << index),
              std::uint16_t(coverage | divisor_mask(P[index])),
              std::gcd(g, P[index]));
      };
  visit(0, forced_mask, forced_coverage, P[forced_index]);

  for (auto& [size, anchors] : census.by_size) {
    std::sort(anchors.begin(), anchors.end());
  }
  return census;
}

bool contains_mask(Mask container, Mask contained) {
  return (container & contained) == contained;
}

struct BodyCensus {
  U64 candidates = 0;
  U64 valid = 0;
  std::array<U64, 7> first_anchor_size{};
  std::array<U64, 7> contains_anchor_size{};
  std::array<U64, 7> presentation_count{};
  std::map<int, U64> total_multiplicity_histogram;
  std::map<int, U64> four_anchor_multiplicity_histogram;
  U64 bytewise_fnv1a64 = 14695981039346656037ULL;
  bool has_uncovered = false;
  Mask first_uncovered = 0;
};

BodyCensus count_bodies(const MinimalAnchorCensus& anchors) {
  BodyCensus census;
  std::vector<int> u_indices;
  for (int i = 0; i < int(P.size()); ++i) {
    if (!is_original_value(P[i])) u_indices.push_back(i);
  }

  std::function<void(int, int, Mask, std::uint16_t, int)> visit =
      [&](int start, int left, Mask mask, std::uint16_t coverage, int g) {
        if (left == 0) {
          ++census.candidates;
          if (coverage != FULL_DIVISOR_MASK || g != 1) return;
          ++census.valid;
          std::array<int, 7> multiplicities{};
          for (int size = 4; size <= 6; ++size) {
            const auto found = anchors.by_size.find(size);
            if (found == anchors.by_size.end()) continue;
            for (Mask anchor : found->second) {
              if (contains_mask(mask, anchor)) ++multiplicities[size];
            }
            if (multiplicities[size] != 0) ++census.contains_anchor_size[size];
            census.presentation_count[size] += U64(multiplicities[size]);
          }
          int first_size = 0;
          int total_multiplicity = 0;
          for (int size = 4; size <= 6; ++size) {
            total_multiplicity += multiplicities[size];
            if (first_size == 0 && multiplicities[size] != 0) first_size = size;
          }
          if (first_size == 0) {
            census.has_uncovered = true;
            if (census.first_uncovered == 0) census.first_uncovered = mask;
          } else {
            ++census.first_anchor_size[first_size];
          }
          ++census.total_multiplicity_histogram[total_multiplicity];
          ++census.four_anchor_multiplicity_histogram[multiplicities[4]];
          census.bytewise_fnv1a64 = fnv1a_u32(census.bytewise_fnv1a64, mask);
          census.bytewise_fnv1a64 = fnv1a_u32(
              census.bytewise_fnv1a64, std::uint32_t(multiplicities[4]));
          census.bytewise_fnv1a64 = fnv1a_u32(
              census.bytewise_fnv1a64, std::uint32_t(multiplicities[5]));
          census.bytewise_fnv1a64 = fnv1a_u32(
              census.bytewise_fnv1a64, std::uint32_t(multiplicities[6]));
          return;
        }
        const int last = int(u_indices.size()) - left;
        for (int j = start; j <= last; ++j) {
          const int index = u_indices[j];
          visit(j + 1, left - 1, mask | (Mask(1) << index),
                std::uint16_t(coverage | divisor_mask(P[index])),
                std::gcd(g, P[index]));
        }
      };
  visit(0, 10, 0, 0, 0);
  return census;
}

bool is_cover(const std::vector<Mask>& global_edges, Mask anchor_and_choice) {
  for (Mask edge : global_edges) {
    if ((edge & anchor_and_choice) == 0) return false;
  }
  return true;
}

std::pair<U64, Mask> disjoint_edge_count_and_first(
    const std::vector<Mask>& global_edges, Mask body) {
  U64 count = 0;
  Mask first = 0;
  for (Mask edge : global_edges) {
    if ((edge & body) != 0) continue;
    if (count == 0) first = edge;
    ++count;
  }
  return {count, first};
}

struct CoverPresentation {
  Mask anchor = 0;
  Mask choice = 0;
  int choice_size = 0;
};

struct CoverCensus {
  std::map<int, U64> size_histogram;
  std::vector<CoverPresentation> all;
  std::vector<CoverPresentation> next_layer_survivors;
  std::map<Mask, U64> survivor_body_multiplicity;
  U64 bytewise_fnv1a64 = 14695981039346656037ULL;
  int anchors_with_cover = 0;
};

CoverCensus enumerate_covers(const std::vector<Mask>& anchors,
                             int budget,
                             const std::vector<Mask>& first_edges,
                             const std::vector<Mask>& next_edges) {
  CoverCensus census;
  for (Mask anchor : anchors) {
    std::vector<int> available;
    for (int i = 0; i < int(P.size()); ++i) {
      if ((anchor & (Mask(1) << i)) == 0) available.push_back(i);
    }
    U64 row_cover_count = 0;
    for (int size = 0; size <= budget; ++size) {
      combinations_from_indices(available, size, [&](Mask choice) {
        const Mask body = anchor | choice;
        if (!is_cover(first_edges, body)) return;
        ++row_cover_count;
        ++census.size_histogram[size];
        census.all.push_back({anchor, choice, size});
        census.bytewise_fnv1a64 = fnv1a_u32(census.bytewise_fnv1a64, anchor);
        census.bytewise_fnv1a64 = fnv1a_u32(census.bytewise_fnv1a64, choice);
        census.bytewise_fnv1a64 = fnv1a_u32(census.bytewise_fnv1a64,
                                            std::uint32_t(size));
        if (is_cover(next_edges, body)) {
          census.next_layer_survivors.push_back({anchor, choice, size});
          ++census.survivor_body_multiplicity[body];
        }
      });
    }
    if (row_cover_count != 0) ++census.anchors_with_cover;
  }
  return census;
}

void print_histogram(const std::map<int, U64>& histogram) {
  bool first = true;
  std::cout << "{";
  for (const auto& [key, count] : histogram) {
    if (!first) std::cout << ",";
    first = false;
    std::cout << key << ":" << count;
  }
  std::cout << "}";
}

void print_fraction(I64 numerator, I64 denominator) {
  const I64 divisor = std::gcd(numerator, denominator);
  std::cout << numerator / divisor << "/" << denominator / divisor;
}

}  // namespace

int main() {
  std::cout << "q50 zero-original minimal-anchor independent referee\n";
  std::cout << "method=direct exact circle arrangement + literal combinations\n";

  const Arrangement arrangement;
  std::cout << "ruler=" << arrangement.ruler
            << " walls=" << arrangement.wall_count
            << " atoms=" << arrangement.atom_count
            << " q_safe_masks=" << arrangement.q_safe_weight.size() << "\n";
  I64 q_safe_total = 0;
  for (const auto& [mask, weight] : arrangement.q_safe_weight) {
    (void)mask;
    q_safe_total += weight;
  }
  std::cout << "q_safe_total=";
  print_fraction(q_safe_total, arrangement.ruler);
  std::cout << "\n";

  const EdgeLayer e5 = build_edge_layer(arrangement, 5);
  const EdgeLayer e6 = build_edge_layer(arrangement, 6);
  const EdgeLayer e7 = build_edge_layer(arrangement, 7);
  for (const EdgeLayer* layer : {&e5, &e6, &e7}) {
    std::cout << "E" << layer->depth
              << " candidates=" << layer->candidates
              << " edges=" << layer->edges.size()
              << " equalities=" << layer->equality_count
              << " min_edge_delta=" << layer->minimum_edge_delta
              << " max_nonedge_delta=" << layer->maximum_nonedge_delta
              << " bytewise_fnv1a64=0x" << std::hex << std::setw(16)
              << std::setfill('0') << layer->bytewise_fnv1a64 << std::dec
              << std::setfill(' ') << "\n";
  }

  // Two inherited depth-seven repair controls, evaluated from the new wall path.
  auto mask_of_values = [](std::initializer_list<int> values) {
    Mask result = 0;
    for (int value : values) {
      const auto found = std::find(P.begin(), P.end(), value);
      if (found == P.end()) throw std::runtime_error("control label absent");
      result |= Mask(1) << int(found - P.begin());
    }
    return result;
  };
  for (Mask control : {
           mask_of_values({8, 10, 15, 20, 143, 176, 290}),
           mask_of_values({10, 15, 20, 85, 120, 143, 176})}) {
    std::cout << "control " << mask_string(control) << " mass=";
    print_fraction(arrangement.mass_numerator(control), arrangement.ruler);
    std::cout << "\n";
  }

  const MinimalAnchorCensus anchors = find_all_minimal_anchors();
  std::cout << "minimal_anchor_search_nodes=" << anchors.search_nodes
            << " valid_stop_nodes=" << anchors.valid_stop_nodes << "\n";
  std::cout << "minimal_anchor_sizes=";
  {
    std::map<int, U64> histogram;
    for (const auto& [size, rows] : anchors.by_size) histogram[size] = rows.size();
    print_histogram(histogram);
    std::cout << "\n";
  }

  const BodyCensus bodies = count_bodies(anchors);
  std::cout << "body_candidates=" << bodies.candidates
            << " valid_bodies=" << bodies.valid
            << " uncovered=" << (bodies.has_uncovered ? 1 : 0) << "\n";
  if (bodies.has_uncovered) {
    std::cout << "first_uncovered_body=" << mask_string(bodies.first_uncovered) << "\n";
  }
  std::cout << "body_first_anchor_size={4:" << bodies.first_anchor_size[4]
            << ",5:" << bodies.first_anchor_size[5]
            << ",6:" << bodies.first_anchor_size[6] << "}\n";
  std::cout << "body_contains_anchor_size={4:" << bodies.contains_anchor_size[4]
            << ",5:" << bodies.contains_anchor_size[5]
            << ",6:" << bodies.contains_anchor_size[6] << "}\n";
  std::cout << "body_anchor_presentations={4:" << bodies.presentation_count[4]
            << ",5:" << bodies.presentation_count[5]
            << ",6:" << bodies.presentation_count[6] << "}\n";
  std::cout << "four_anchor_body_multiplicity=";
  print_histogram(bodies.four_anchor_multiplicity_histogram);
  std::cout << "\nall_anchor_body_multiplicity=";
  print_histogram(bodies.total_multiplicity_histogram);
  std::cout << "\nbody_bytewise_fnv1a64=0x" << std::hex << std::setw(16)
            << std::setfill('0') << bodies.bytewise_fnv1a64 << std::dec
            << std::setfill(' ') << "\n";

  const auto& anchors5 = anchors.by_size.at(5);
  const auto& anchors6 = anchors.by_size.at(6);
  const CoverCensus covers5 = enumerate_covers(anchors5, 5, e5.edges, e6.edges);
  std::cout << "size5_E5_covers=" << covers5.all.size() << " histogram=";
  print_histogram(covers5.size_histogram);
  std::cout << " anchors_with_cover=" << covers5.anchors_with_cover
            << " bytewise_fnv1a64=0x" << std::hex << std::setw(16)
            << std::setfill('0') << covers5.bytewise_fnv1a64 << std::dec
            << std::setfill(' ') << "\n";
  std::cout << "size5_E6_survivors=" << covers5.next_layer_survivors.size()
            << " bodies=" << covers5.survivor_body_multiplicity.size() << "\n";
  for (const auto& [body, multiplicity] : covers5.survivor_body_multiplicity) {
    const auto [repair_count, first_repair] =
        disjoint_edge_count_and_first(e7.edges, body);
    std::cout << "size5_survivor_body=" << mask_string(body)
              << " presentation_multiplicity=" << multiplicity
              << " E7_disjoint_repairs=" << repair_count
              << " first_E7_repair=" << mask_string(first_repair) << "\n";
  }
  for (const CoverPresentation& row : covers5.next_layer_survivors) {
    const bool survives_e7 = is_cover(e7.edges, row.anchor | row.choice);
    std::cout << "size5_survivor_presentation A=" << mask_string(row.anchor)
              << " K=" << mask_string(row.choice)
              << " |K|=" << row.choice_size
              << " E7_cover=" << (survives_e7 ? 1 : 0) << "\n";
  }

  const CoverCensus covers6 = enumerate_covers(anchors6, 4, e5.edges, e6.edges);
  std::cout << "size6_E5_covers=" << covers6.all.size() << " histogram=";
  print_histogram(covers6.size_histogram);
  std::cout << " anchors_with_cover=" << covers6.anchors_with_cover
            << " anchors_without_cover=" << anchors6.size() - covers6.anchors_with_cover
            << " bytewise_fnv1a64=0x" << std::hex << std::setw(16)
            << std::setfill('0') << covers6.bytewise_fnv1a64 << std::dec
            << std::setfill(' ') << "\n";
  std::cout << "size6_E6_survivors=" << covers6.next_layer_survivors.size()
            << " bodies=" << covers6.survivor_body_multiplicity.size() << "\n";
  for (const CoverPresentation& row : covers6.all) {
    const auto [repair_count, first_repair] =
        disjoint_edge_count_and_first(e6.edges, row.anchor | row.choice);
    std::cout << "size6_E5_cover A=" << mask_string(row.anchor)
              << " K=" << mask_string(row.choice)
              << " |K|=" << row.choice_size
              << " E6_disjoint_repairs=" << repair_count
              << " first_E6_repair=" << mask_string(first_repair) << "\n";
  }

  const bool exact_structure =
      anchors.by_size.size() == 3 && anchors.by_size.at(4).size() == 32 &&
      anchors5.size() == 297 && anchors6.size() == 24 &&
      !bodies.has_uncovered &&
      covers5.next_layer_survivors.size() == 15 &&
      covers5.survivor_body_multiplicity.size() == 2 &&
      covers6.next_layer_survivors.empty();
  std::cout << "structural_self_check=" << (exact_structure ? "PASS" : "FAIL") << "\n";
  return exact_structure ? 0 : 2;
}
