#!/usr/bin/env python3
"""Exact linear-algebra audit of the THM-2701 guard/source debt cone.

The probe separates three questions which are easy to conflate:

1. the two debt states do form a signed chronological two-cycle;
2. the complete THM-2350 endpoint-covector bank has rank two; but
3. the operator span generated by toggling only the guard and source-owner
   roles has target rank zero.

It also verifies the stronger THM-2461 anchor statement: every off-diagonal
factor-repair table K(r,s), K(r,0)=0, pulls back identically to zero through
either target-neutral debt role.  A target-active graft role gives a nonzero
formal pullback, while a lawful physical target action requires its paired
blocker to co-translate.  No existence of that paired action on the
THM-2701 ancestry is asserted here.
"""


P = 13
ROLES = ("H", "j", "k_a", "k_b", "a", "c")


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def matmul(left, right, modulus=P):
    require(left and right and len(left[0]) == len(right),
            "matrix product shape mismatch")
    return tuple(
        tuple(sum(left[i][k] * right[k][j]
                  for k in range(len(right))) % modulus
              for j in range(len(right[0])))
        for i in range(len(left))
    )


def rank_mod(matrix, modulus=P):
    rows = [list(value % modulus for value in row) for row in matrix]
    if not rows:
        return 0
    width = len(rows[0])
    rank = 0
    for column in range(width):
        pivot = next((index for index in range(rank, len(rows))
                      if rows[index][column]), None)
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        inverse = pow(rows[rank][column], -1, modulus)
        rows[rank] = [(inverse * value) % modulus
                      for value in rows[rank]]
        for index in range(len(rows)):
            if index == rank or not rows[index][column]:
                continue
            scale = rows[index][column]
            rows[index] = [
                (value - scale * pivot_value) % modulus
                for value, pivot_value in zip(rows[index], rows[rank])
            ]
        rank += 1
        if rank == len(rows):
            break
    return rank


def audit_debt_complex():
    # Vertices are B_debt=(guard danger, source safe) and
    # A_debt=(guard safe, source danger/shifted-safe).  The two chronological
    # arrows have opposite cellular boundaries.
    # Rows: (B,A); columns: (B->A,A->B).
    boundary = (
        (-1, 1),
        (1, -1),
    )
    require(rank_mod(boundary) == 1,
            "two-edge debt cycle stopped having boundary rank one")
    # dim H0=2-rank=1 and dim H1=2-rank=1.
    homology = (2 - rank_mod(boundary), 2 - rank_mod(boundary))
    require(homology == (1, 1), "debt-cycle homology changed")

    # Role increments of the arrows.  B->A turns guard danger to safe and
    # source safe to danger; A->B reverses both.  Rows use ROLES.
    role_incidence = (
        (-1, 1),   # H
        (1, -1),   # source owner j
        (0, 0),    # k_a
        (0, 0),    # k_b
        (0, 0),    # target a
        (0, 0),    # target c
    )
    require(rank_mod(role_incidence) == 1,
            "reduced debt-role line changed")
    return boundary, homology, role_incidence


def audit_target_span(role_incidence):
    # THM-2461 (35), in role order H,j,k_a,k_b,a,c.
    target_covectors = (
        (0, 0, -1, 0, 1, 0),
        (0, 0, 0, -1, 0, 1),
    )
    require(rank_mod(target_covectors) == 2,
            "complete endpoint-covector span stopped being the target plane")

    debt_image = matmul(target_covectors, role_incidence)
    require(debt_image == ((0, 0), (0, 0))
            and rank_mod(debt_image) == 0,
            "guard/source debt acquired a target covector")

    # Adding one active graft role is the smallest formal rank-one escape,
    # but is not yet a lawful physical dipole.
    active_grafts = (
        (0, 0),  # H
        (0, 0),  # j
        (1, 0),  # k_a
        (0, 1),  # k_b
        (0, 0),  # a
        (0, 0),  # c
    )
    formal_active_image = matmul(target_covectors, active_grafts)
    require(formal_active_image == ((-1 % P, 0), (0, -1 % P))
            and rank_mod(formal_active_image) == 2,
            "formal graft-role target span changed")

    # The minimum-support lawful directions are the paired blocker--graft
    # dipoles D_a=e_a-e_(k_a), D_c=e_c-e_(k_b).  Their image is 2I; 2 is a
    # unit modulo thirteen, so the lawful paired bank also spans the plane.
    paired_dipoles = (
        (0, 0),    # H
        (0, 0),    # j
        (-1, 0),   # k_a
        (0, -1),   # k_b
        (1, 0),    # a
        (0, 1),    # c
    )
    lawful_image = matmul(target_covectors, paired_dipoles)
    require(lawful_image == ((2, 0), (0, 2))
            and rank_mod(lawful_image) == 2,
            "paired target-dipole span changed")
    return (target_covectors, debt_image, formal_active_image,
            lawful_image)


def audit_anchored_pullbacks():
    # Use the basis of the full space of anchored repair tables:
    # K_(r0,s0)=1 for one s0!=0 and zero elsewhere.  Pullback along a role
    # covector lambda evaluates K(r,lambda(delta)).  If lambda=0, every
    # target point samples s=0 and the whole anchored table vanishes.
    deltas = tuple((u, v) for u in range(P) for v in range(P))

    def scalar(covector, delta):
        return sum(a * b for a, b in zip(covector, delta)) % P

    def pulled_basis_support(covector, r0, s0):
        require(s0 != 0, "anchored repair basis cannot use s=0")
        return tuple(delta for delta in deltas
                     if scalar(covector, delta) == s0)

    zero_covector = (0, 0)
    active_covectors = ((-1, 0), (0, -1))
    for r0 in range(P):
        for s0 in range(1, P):
            require(not pulled_basis_support(zero_covector, r0, s0),
                    "target-neutral anchored repair stopped pulling back to zero")
            for covector in active_covectors:
                support = pulled_basis_support(covector, r0, s0)
                require(len(support) == P,
                        "nonzero target line stopped having thirteen-point fibres")

    anchored_dimension = P * (P - 1)
    neutral_pullback_rank = 0
    active_pullback_rank = anchored_dimension
    require((anchored_dimension, neutral_pullback_rank, active_pullback_rank)
            == (156, 0, 156), "anchored pullback rank ledger changed")
    return anchored_dimension, neutral_pullback_rank, active_pullback_rank


def main():
    boundary, homology, role_incidence = audit_debt_complex()
    (target_covectors, debt_image, formal_active_image,
     lawful_image) = audit_target_span(role_incidence)
    pullback_ranks = audit_anchored_pullbacks()

    print("LRC14 signed guard/source-clock debt cone target-span probe")
    print("status=PROVED-ELEMENTARY exact stopping certificate")
    print(f"field=F_{P}; roles={ROLES}")
    print(f"debt_boundary_rows_BA={boundary}; (dim_H0,dim_H1)={homology}")
    print(f"debt_role_incidence_rows={role_incidence}")
    print(f"target_covector_matrix={target_covectors}; rank="
          f"{rank_mod(target_covectors)}")
    print(f"target_of_debt_edges={debt_image}; rank={rank_mod(debt_image)}")
    print("common_ancestry_anchor=K_f^+(r,0)=0; lambda_H=lambda_j=0; "
          "therefore Ktilde_f(r,delta)=0 for every target delta")
    print(f"anchored_table_dimensions=(domain,neutral_image,active_image)="
          f"{pullback_ranks}")
    print(f"formal_active_graft_image={formal_active_image}; rank="
          f"{rank_mod(formal_active_image)}")
    print(f"lawful_paired_dipole_image={lawful_image}; rank="
          f"{rank_mod(lawful_image)}")
    print("verdict=the full endpoint bank spans F13^2, but the currently "
          "generated guard/source debt operator span maps identically to zero")
    print("minimal_formal_escape=one of k_a,k_b; minimal lawful escape="
          "co-translate its paired blocker on the same ancestry")
    print("typing_boundary=THM2379 moves the graft complement while freezing "
          "the paired blocker; THM2563 supplies a paired moving endpoint on "
          "another old-head packet, not a chain map from the THM2701 debt SCC")
    print("cheapest_test=insert the paired table "
          "u_1(a*x-s/13)u_L(k_a*x+s/13) into the exact debt cylinder and "
          "retain the left residue eta.u before endpoint completion")
    print("SCOPE: generated-operator-span no-go only; no abstract linear-map "
          "no-go, scalar-row exclusion, or LRC14 conclusion")
    print("ALL CHECKS PASSED")


if __name__ == "__main__":
    main()
