#!/usr/bin/env python3
"""Exact scratch audit of the THM-2825 Schur/scale boundary.

This script deliberately reuses only the public reconstruction functions of
the primary THM-2825 companion.  It checks three claims not printed there:

1. the signed semantic-parity symbol has an explicit norm-one gamma_2
   factorization and is a Schur tripotent;
2. exact half-step offsets partition the relation into pairwise Schur-
   orthogonal partial matchings;
3. the algebra generated by cell and semantic-colour masks cannot contain
   either metric collar, while ordinary matrix composition of the two collar
   matchings produces a rank-587 common-side partial translation.

No Python ``assert`` is used.
"""

from collections import Counter, defaultdict
from hashlib import sha256
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
COMP = ROOT / "04-computation"
sys.path.insert(0, str(COMP))


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


PRIMARY_NAME = "lrc14_nearest_half_step_common_right_collar_thm2825.py"
PRIMARY_SHA256 = (
    "bd9ffe7f6815b5c563bd483c300118fbdd683f3d9303babbab7912e031747c9a"
)
actual_primary_hash = sha256(
    (COMP / PRIMARY_NAME).read_bytes().replace(b"\r\n", b"\n")
).hexdigest()
require(
    actual_primary_hash == PRIMARY_SHA256,
    f"primary companion changed: {actual_primary_hash}",
)


import lrc14_nearest_half_step_common_right_collar_thm2825 as collar


def colour(value):
    """Encode the two delayed semantic values by unit signs."""
    if value == (collar.copies.C, collar.copies.C):
        return 1
    if value == (0, 0):
        return -1
    raise RuntimeError(f"unexpected semantic value {value}")


def forward_offset(rleft, mleft):
    """Centered half-step displacement from a right row to a common column."""
    difference = mleft - rleft
    require(difference % collar.H == 0, "edge left the half-step lattice")
    offset = (difference // collar.H) % collar.PERIOD_STEPS
    if offset > collar.PERIOD_STEPS // 2:
        offset -= collar.PERIOD_STEPS
    return offset


def directed_chain_histogram(arrows):
    """Return edge-length census for a finite partial permutation."""
    successor = {}
    predecessor = {}
    for source, target in arrows:
        require(source not in successor, "partial translation forked")
        require(target not in predecessor, "partial translation merged")
        successor[source] = target
        predecessor[target] = source

    seen_edges = set()
    chains = Counter()
    for source in successor:
        if source in predecessor:
            continue
        length = 0
        cursor = source
        while cursor in successor:
            edge = (cursor, successor[cursor])
            require(edge not in seen_edges, "chain traversal repeated an edge")
            seen_edges.add(edge)
            cursor = successor[cursor]
            length += 1
        chains[length] += 1

    cycles = 0
    for source, target in arrows:
        edge = (source, target)
        if edge in seen_edges:
            continue
        cycles += 1
        cursor = source
        while True:
            edge = (cursor, successor[cursor])
            require(edge not in seen_edges, "cycle traversal repeated early")
            seen_edges.add(edge)
            cursor = successor[cursor]
            if cursor == source:
                break

    require(len(seen_edges) == len(arrows), "chain decomposition lost edges")
    return chains, cycles


def main():
    (
        _module,
        _rails,
        _present,
        details,
        full_module,
        e3,
        clocks,
        q_pairs,
        _delayed,
        _source_weight,
        _target_weight,
        _rail_common,
    ) = collar.copies.physical_setup()

    edge_count = 0
    signed_factor_failures = 0
    parity_failures = 0
    offset_supports = defaultdict(set)
    edge_to_offset = {}
    semantic_atoms = []
    j1_support = set()
    j2_support = set()
    j1_images = set()
    j2_images = set()
    common_translation_arrows = []
    row_translation_arrows = []
    semantic_caches = tuple({} for _clock in range(7))

    for clock in range(7):
        for sigma in collar.COMMON_S:
            for target in collar.COMMON_T:
                cell = (clock, sigma, target)
                _source, _target, common, right = collar.cell_objects(
                    details,
                    full_module,
                    e3,
                    clocks,
                    clock,
                    sigma,
                    target,
                )
                if not right:
                    continue

                cache = semantic_caches[clock]
                common_by_left = {piece[0]: piece for piece in common}
                row_colours = defaultdict(list)
                column_colours = defaultdict(list)

                for row_index, rpiece in enumerate(right):
                    rcolour = colour(
                        collar.semantic_value(rpiece, q_pairs[clock], cache)
                    )
                    row = (cell, "R", row_index, rpiece[0], rcolour)
                    row_colours[rcolour].append(row)

                    m1 = common_by_left.get(rpiece[0] + collar.H)
                    m2 = common_by_left.get(rpiece[0] + 2 * collar.H)
                    require(m1 is not None and m2 is not None, "collar vanished")
                    m1_index = common.index(m1)
                    m2_index = common.index(m2)
                    col1_colour = colour(
                        collar.semantic_value(m1, q_pairs[clock], cache)
                    )
                    col2_colour = colour(
                        collar.semantic_value(m2, q_pairs[clock], cache)
                    )
                    col1 = (cell, "M", m1_index, m1[0], col1_colour)
                    col2 = (cell, "M", m2_index, m2[0], col2_colour)
                    require(
                        col1_colour == -rcolour
                        and col2_colour == rcolour,
                        "relative semantic two-state collar changed",
                    )
                    j1_support.add((row, col1))
                    j2_support.add((row, col2))
                    j1_images.add(col1)
                    j2_images.add(col2)
                    common_translation_arrows.append((col2, col1))

                for column_index, mpiece in enumerate(common):
                    mcolour = colour(
                        collar.semantic_value(mpiece, q_pairs[clock], cache)
                    )
                    column = (
                        cell,
                        "M",
                        column_index,
                        mpiece[0],
                        mcolour,
                    )
                    column_colours[mcolour].append(column)

                for rcolour, rows in row_colours.items():
                    for mcolour, columns in column_colours.items():
                        semantic_atoms.append(
                            (
                                cell,
                                rcolour,
                                mcolour,
                                len(rows),
                                len(columns),
                            )
                        )

                for row_index, rpiece in enumerate(right):
                    rcolour = colour(
                        collar.semantic_value(rpiece, q_pairs[clock], cache)
                    )
                    row = (cell, "R", row_index, rpiece[0], rcolour)
                    for column_index, mpiece in enumerate(common):
                        mcolour = colour(
                            collar.semantic_value(
                                mpiece, q_pairs[clock], cache
                            )
                        )
                        column = (
                            cell,
                            "M",
                            column_index,
                            mpiece[0],
                            mcolour,
                        )
                        edge = (row, column)
                        offset = forward_offset(rpiece[0], mpiece[0])
                        edge_count += 1
                        offset_supports[offset].add(edge)
                        require(edge not in edge_to_offset, "edge offset repeated")
                        edge_to_offset[edge] = offset
                        sign = 1 if rcolour == mcolour else -1
                        if sign != rcolour * mcolour:
                            signed_factor_failures += 1
                        if sign != (1 if offset % 2 == 0 else -1):
                            parity_failures += 1

    require(edge_count == 195517, "relation edge census changed")
    row_universe = {row for row, _column in edge_to_offset}
    column_universe = {column for _row, column in edge_to_offset}
    require(
        (len(row_universe), len(column_universe)) == (587, 63308),
        "global labelled row/column universe changed",
    )
    require(not signed_factor_failures, "row/column sign factorization failed")
    require(not parity_failures, "offset parity law failed")
    require(
        sum(len(support) for support in offset_supports.values()) == edge_count,
        "offset matching partition lost edges",
    )

    # A fixed translation is injective on both coordinates, hence every exact
    # offset support is a partial matching.
    for offset, support in offset_supports.items():
        rows = [row for row, _column in support]
        columns = [column for _row, column in support]
        require(len(rows) == len(set(rows)), f"offset {offset} repeats a row")
        require(
            len(columns) == len(set(columns)),
            f"offset {offset} repeats a column",
        )

    require(len(j1_support) == 587 and len(j2_support) == 587, "collar size")
    require(
        (len(j1_images), len(j2_images)) == (587, 587),
        "collar column injections changed",
    )
    require(
        j1_support == offset_supports[1],
        "+h collar is not the exact offset-one matching",
    )
    require(
        j2_support == offset_supports[2],
        "+2h collar is not the exact offset-two matching",
    )
    require(not (j1_support & j2_support), "collar Schur supports overlap")
    require(not (j1_images & j2_images), "collar column ranges overlap")

    # Every semantic atom is an all-one rectangle.  The two collar supports
    # meet exactly one semantic atom for each nonempty right colour class, but
    # only in a graph of size |rows| rather than the full |rows|*|columns|.
    atom_size_histogram = Counter()
    atom_sign_histogram = Counter()
    partial_j1_atoms = 0
    partial_j2_atoms = 0
    j1_atom_counts = Counter(
        (row[0], row[-1], column[-1]) for row, column in j1_support
    )
    j2_atom_counts = Counter(
        (row[0], row[-1], column[-1]) for row, column in j2_support
    )
    for (
        cell,
        row_colour,
        column_colour,
        row_count,
        column_count,
    ) in semantic_atoms:
        sign = row_colour * column_colour
        atom_size_histogram[row_count, column_count] += 1
        atom_sign_histogram[sign] += 1
        atom_key = (cell, row_colour, column_colour)
        j1_part = j1_atom_counts[atom_key]
        j2_part = j2_atom_counts[atom_key]
        if j1_part:
            require(
                j1_part == row_count
                and j1_part < row_count * column_count,
                "j1 stopped being a strict graph inside a semantic atom",
            )
            partial_j1_atoms += 1
        if j2_part:
            require(
                j2_part == row_count
                and j2_part < row_count * column_count,
                "j2 stopped being a strict graph inside a semantic atom",
            )
            partial_j2_atoms += 1

    require(
        (partial_j1_atoms, partial_j2_atoms) == (207, 207),
        "collars no longer cut all 207 relevant semantic atoms",
    )
    require(
        len(semantic_atoms) == 414
        and atom_sign_histogram == Counter({-1: 207, 1: 207})
        and min(column_count for *_head, column_count in semantic_atoms) == 94,
        "semantic rectangle algebra census changed",
    )

    # J1^* J2 maps j2(r) to j1(r), a common-side translation by -h.
    require(
        len(common_translation_arrows)
        == len(set(common_translation_arrows))
        == 587,
        "common-side partial translation lost rank",
    )
    common_chain_histogram, common_cycles = directed_chain_histogram(
        common_translation_arrows
    )

    # J1 J2^* is nonzero precisely when im(J1) and im(J2) overlap.
    j1_preimage = {column: row for row, column in j1_support}
    j2_preimage = {column: row for row, column in j2_support}
    for column in j1_images & j2_images:
        row_translation_arrows.append(
            (j2_preimage[column], j1_preimage[column])
        )
    row_chain_histogram, row_cycles = directed_chain_histogram(
        row_translation_arrows
    )

    offset_count_histogram = Counter(
        len(support) for support in offset_supports.values()
    )
    local_offsets = tuple(
        (offset, len(offset_supports.get(offset, ())))
        for offset in range(-14, 15)
    )
    full_offsets = tuple(
        sorted(
            offset
            for offset, support in offset_supports.items()
            if len(support) == 587
        )
    )
    require(
        full_offsets == (1, 2),
        "the uniform two-layer collar acquired another full offset",
    )
    maximum_nonfull_support = max(
        len(support)
        for offset, support in offset_supports.items()
        if offset not in full_offsets
    )
    require(
        maximum_nonfull_support == 527,
        "largest nonsaturating offset support changed",
    )
    row_positive_offsets = defaultdict(set)
    for (row, _column), offset in edge_to_offset.items():
        if offset > 0:
            row_positive_offsets[row].add(offset)
    collar_depths = Counter()
    for row in {edge[0] for edge in edge_to_offset}:
        depth = 0
        while depth + 1 in row_positive_offsets[row]:
            depth += 1
        require(depth >= 2, "uniform two-layer collar broke")
        collar_depths[depth] += 1
    require(sum(collar_depths.values()) == 587, "collar depth census")
    negative_offsets = tuple(
        sorted(offset for offset in offset_supports if offset < 0)
    )
    positive_offsets = tuple(
        sorted(offset for offset in offset_supports if offset > 0)
    )
    require(negative_offsets, "hostile negative-offset control vanished")
    require(
        len(negative_offsets) + len(positive_offsets) == 1043
        and 0 not in offset_supports,
        "offset sign partition changed",
    )
    nearest_negative = negative_offsets[-1]
    require(
        positive_offsets == tuple(range(1, 583))
        and nearest_negative == -50,
        "one-sided exact-offset boundary changed",
    )
    offset_census = tuple(
        (offset, len(offset_supports[offset]))
        for offset in sorted(offset_supports)
    )
    offset_census_sha256 = sha256(repr(offset_census).encode("ascii")).hexdigest()
    require(
        offset_census_sha256
        == "7040911c43ec268ba5ff6c547e092ad3706e2b37eeae9f1a05843dfcd54f62e0",
        "full exact-offset census changed",
    )
    even_edges = sum(
        len(support)
        for offset, support in offset_supports.items()
        if offset % 2 == 0
    )
    odd_edges = edge_count - even_edges
    require((even_edges, odd_edges) == (97661, 97856), "parity census")

    # The factorization S(r,m)=u_r(cell)*v_m(cell) has one unit coordinate
    # per cell.  Thus max row and column vector norms are exactly one; a
    # nonzero entry gives the reverse lower bound.  This proves gamma_2(S)=1.
    print("THM-2825 SCHUR/SCALE ALGEBRA SCRATCH AUDIT")
    print(
        f"primary_sha256={actual_primary_hash};"
        f"rows={len(row_universe)};columns={len(column_universe)};"
        f"edges={edge_count};semantic_atoms={len(semantic_atoms)}"
    )
    print(
        "signed_symbol_factorization="
        "S(row,column)=row_colour*column_colour on the unique cell;"
        "max_row_norm=1;max_column_norm=1;max_entry=1;"
        "gamma2=schur_norm=1"
    )
    print(
        "schur_polynomial="
        "S^2=E;S^3=S;"
        "P_equal=(E+S)/2;P_opposite=(E-S)/2;"
        "P_equal*P_opposite=0"
    )
    print(
        f"semantic_atom_signs={tuple(sorted(atom_sign_histogram.items()))};"
        f"semantic_atom_sizes={tuple(sorted(atom_size_histogram.items()))}"
    )
    print(
        f"collar_atom_cuts=j1:{partial_j1_atoms},j2:{partial_j2_atoms};"
        "verdict=neither collar belongs to the cell+colour Schur algebra"
    )
    print(
        f"exact_offsets={len(offset_supports)};"
        f"negative_offsets={len(negative_offsets)};"
        f"positive_offsets={len(positive_offsets)};"
        f"offset_range=({min(offset_supports)},{max(offset_supports)});"
        f"offset_census_sha256={offset_census_sha256};"
        f"offset_support_size_histogram="
        f"{tuple(sorted(offset_count_histogram.items()))}"
    )
    print(f"local_offset_counts={local_offsets}")
    print(
        f"full_587_offsets={full_offsets};"
        f"maximum_nonfull_support={maximum_nonfull_support};"
        "full_offset_intersection=intersection_over_rows_available_offsets"
    )
    print(
        f"positive_initial_collar_depths={tuple(sorted(collar_depths.items()))};"
        f"nearest_negative_offset={nearest_negative};"
        "uniform_depth=2"
    )
    print(
        f"offset_parity_edges=even:{even_edges},odd:{odd_edges};"
        "distinct_exact-offset matchings are Schur-orthogonal"
    )
    print(
        "ordinary_common_composition="
        f"rank(J1^*J2)=587;image_overlap={len(j1_images & j2_images)};"
        f"chain_edge_lengths={tuple(sorted(common_chain_histogram.items()))};"
        f"cycles={common_cycles};displacement=-h"
    )
    print(
        "ordinary_row_composition="
        f"rank(J1J2^*)={len(row_translation_arrows)};"
        f"chain_edge_lengths={tuple(sorted(row_chain_histogram.items()))};"
        f"cycles={row_cycles}"
    )
    print(
        "linking_algebra="
        "V_ij=J_i^*J_j (i,j in {1,2});"
        "V_ij V_kl=delta_(j,k)V_il;"
        "span(V_ij)=M2 tensor I_587 on the 1174-column collar;"
        "X=V_12+V_21,Z=V_22-V_11,X^2=Z^2=Q,XZ=-ZX"
    )
    print(
        "BOUNDARY: Schur composition is entrywise, so it annihilates distinct "
        "offset matchings and retains only parity in <E,S>. Ordinary matrix "
        "composition recovers a partial translation only after the metric "
        "collars J1,J2 have already been supplied. Positively, among all "
        "1043 exact-offset matchings, domain saturation plus parity selects "
        "J1 and J2 uniquely without a nearest-distance comparison."
    )
    print("ALL EXACT CHECKS PASSED")
if __name__ == "__main__":
    main()
