#!/usr/bin/env python3
"""Exact LP for the q0/Vitali atom-cone tax constants.

For a signed missed-count atom displacement q_t on t=0..6, normalize q_0=1.
If low factorial moments through order r are invisible, the non-origin atoms
must solve

    sum_{t=1}^6 binom(t,0) q_t = -1,
    sum_{t=1}^6 binom(t,i) q_t = 0, 1 <= i <= r.

This script minimizes sum_{t=1}^6 |q_t| exactly.  The constants are the
smallest possible non-origin "Vitali tax" for hiding a unit q0 move from low
factorial observers.  They are LP facts about the abstract atom cone, not a
proof that every optimum is generated by LRC carrier words.
"""

from __future__ import annotations

import itertools
import math
from fractions import Fraction as F


M = 6


def fmt(q: F) -> str:
    return f"{q} ({float(q):.9f})"


def solve_linear(A: list[list[F]], b: list[F]) -> list[F] | None:
    n = len(b)
    aug = [row[:] + [rhs] for row, rhs in zip(A, b)]
    for col in range(n):
        pivot = None
        for row in range(col, n):
            if aug[row][col]:
                pivot = row
                break
        if pivot is None:
            return None
        if pivot != col:
            aug[col], aug[pivot] = aug[pivot], aug[col]
        div = aug[col][col]
        aug[col] = [x / div for x in aug[col]]
        for row in range(n):
            if row == col:
                continue
            fac = aug[row][col]
            if fac:
                aug[row] = [x - fac * y for x, y in zip(aug[row], aug[col])]
    return [aug[i][-1] for i in range(n)]


def constraints(r: int, support: tuple[int, ...], signs: tuple[int, ...]) -> tuple[list[list[F]], list[F]]:
    A = []
    for i in range(r + 1):
        A.append([F(s * math.comb(t, i)) for t, s in zip(support, signs)])
    b = [F(-1)] + [F(0) for _ in range(r)]
    return A, b


def min_tax(r: int) -> tuple[F, dict[int, F]]:
    n_constraints = r + 1
    best: tuple[F, dict[int, F]] | None = None
    atoms = tuple(range(1, M + 1))
    for support in itertools.combinations(atoms, n_constraints):
        for signs in itertools.product((-1, 1), repeat=n_constraints):
            A, b = constraints(r, support, signs)
            y = solve_linear(A, b)
            if y is None:
                continue
            if any(v < 0 for v in y):
                continue
            q = {t: F(0) for t in atoms}
            for t, s, mag in zip(support, signs, y):
                q[t] = F(s) * mag
            tax = sum(abs(v) for v in q.values())
            if best is None or tax < best[0]:
                best = (tax, q)
    assert best is not None
    return best


def finite_difference_tax(r: int) -> tuple[F, dict[int, F]]:
    """Tax of the local B_{r+1} move supported on 0..r+1."""
    j = r + 1
    q = {t: F(0) for t in range(1, M + 1)}
    for t in range(1, min(j, M) + 1):
        q[t] = F(((-1) ** (j - t)) * math.comb(j, t))
    return sum(abs(v) for v in q.values()), q


def check_solution(r: int, q: dict[int, F]) -> None:
    assert sum(q.values()) == -1
    for i in range(1, r + 1):
        assert sum(F(math.comb(t, i)) * q[t] for t in range(1, M + 1)) == 0


def main() -> None:
    print("HYP-2721/S70 q0 Vitali-cone minimum tax LP")
    print("Normalize q0=1; minimize sum_{t>0}|q_t| while preserving W_1..W_r.\n")
    print("  r  min_tax        support q_t                         local_B_tax")
    for r in range(0, M):
        tax, q = min_tax(r)
        check_solution(r, q)
        b_tax, b_q = finite_difference_tax(r)
        support = " ".join(f"q{t}={q[t]}" for t in range(1, M + 1) if q[t])
        print(f"  {r}  {fmt(tax):18s} {support:45s} {fmt(b_tax)}")
        if tax < b_tax:
            b_support = " ".join(f"q{t}={b_q[t]}" for t in range(1, M + 1) if b_q[t])
            print(f"      cheaper than local finite difference B_{r+1}: {b_support}")

    print("\nSYNTHESIS")
    print("  The local finite-difference B_{r+1} is the canonical hidden move, but")
    print("  it is not always the cheapest abstract cone move once high t atoms are")
    print("  allowed.  High missed-count atoms can cancel low factorial moments with")
    print("  less non-origin L1 tax.  Therefore a proof cannot use the abstract atom")
    print("  cone alone: it must retain generated-word compatibility and high-tail")
    print("  Bonferroni/transfer constraints before evaluating Q0.")


if __name__ == "__main__":
    main()
