"""
mac-mini-2026-07-07-S41 (HYP-4837, part 2) -- the E[U] floor: adversarial descents at the
right functionals + the balanced-lattice truncation (provability test).

DERIVED IDENTITY (this session):
  E[U_u](E) = sum_{T subset E} (-1)^{|T|} (1-u)^{13-|T|} * L_T(u),
  L_T(u) = sum_{m in (Z\0)^T : sum m_i e_i = 0, sum m_i = 0} prod_i phi_u(m_i),
  phi_u(m) = (1 - e^{-2 pi i m u})/(2 pi i m),  phi_u(0) = u.
  - |T|=1: no solutions.  |T|=2: m(e_i - e_j) = 0 -> DEAD (pairs never contribute).
  - |T|=3 on (a,b,c): rank-1 solution lattice generated by w = (b-c, c-a, a-b)/gcd;
    3-APs give the primitive harmonic (1,-2,1) (largest terms); all triples contribute
    with 1/|w|^3-type decay.
  - |T|>=4: rank >= 2; enumerate small-coefficient solutions.
TARGETS:  mu_{1/7} >= (7/6) E[U_{1/7}]  (Markov with the sharp sup U <= 1 - theta = 6/7)
          => the k=13 hlarge bar mu >= m_P reduces to E[U_{1/7}] >= (6/7) m_P = 0.048417.
          PZ refinement mu >= E[U]^2/E[U^2] >= (7/6)E[U] always (U <= 6/7 pointwise).
Q1: true empirical inf_E E[U_{1/7}] (descent on E[U] itself; jump moves per MISTAKE-119).
Q2: robust PZ floor (longer descent).
Q3: how much of the deficit main - E[U] is captured by weight-3 (+ small weight-4)
    balanced relations?  (If most: the floor is a provable-shaped truncated-lattice bound.)
"""
import numpy as np
from math import gcd
from functools import reduce
from itertools import combinations
import random as rnd
rnd.seed(4141)

THETA = 1/7
MP = 14249/252252
BAR_EU = (6/7)*MP

GRID_F = 200_000
xs_f = (np.arange(GRID_F)+0.5)/GRID_F
GRID_C = 30_000
xs_c = (np.arange(GRID_C)+0.5)/GRID_C

def U_stats(E, xs):
    ph = np.mod(np.outer(xs, np.array(E,float)), 1.0); ph.sort(axis=1)
    g = np.concatenate([np.diff(ph,axis=1),(ph[:,0]+1-ph[:,-1])[:,None]],axis=1)
    U = np.clip(g-THETA,0,None).sum(axis=1)
    EU = U.mean(); EU2 = (U*U).mean()
    return EU, EU2, (U>0).mean()

def norm(E):
    E=sorted(set(E)); E=[e-E[0] for e in E]
    g=reduce(gcd,E[1:]) if len(E)>1 else 1
    return tuple(e//g for e in E) if g else tuple(E)

def descend(obj, starts, iters=800, label=''):
    results=[]
    for E0 in starts:
        E=list(E0); cur=obj(E)
        for it in range(iters):
            i=rnd.randrange(13); cand=E.copy()
            mv = rnd.random()
            if mv < 0.5: cand[i]=max(0,cand[i]+rnd.choice([-2,-1,1,2]))
            elif mv < 0.8: cand[i]=max(0,cand[i]+rnd.choice([-9,-6,-4,4,6,9]))
            else: cand[i]=rnd.randint(0,120)   # jump moves (MISTAKE-119 lesson)
            if len(set(cand))<13: continue
            cv=obj(cand)
            if cv<cur: E,cur=cand,cv
        results.append((cur,norm(E)))
    results.sort()
    return results

STARTS = [
    list(range(1,14)),
    [2,4,6,8,10,11,12,13,14,16,18,20,22],          # monad record
    [0]+list(range(2,13))+[17,28],                  # opus stretched
    [6,8,10,11,12,13,14,16,18,25,36,43,61],         # monad S1-min
    sorted(rnd.sample(range(1,150),13)),
    sorted(rnd.sample(range(1,40),13)),
]

print("=== Q1: adversarial inf of E[U_{1/7}] (bar 6/7*m_P = %.6f) ===" % BAR_EU)
resU = descend(lambda E: U_stats(E,xs_c)[0], STARTS, iters=800)
for cur,E in resU[:4]: print(f"  coarse E[U]={cur:.5f}  {E}")
bestU_E = list(resU[0][1])
EU,EU2,mu = U_stats(bestU_E, xs_f)
print(f"finalist fine-grid: E[U]={EU:.5f} (bar {BAR_EU:.5f}, ratio {EU/BAR_EU:.2f}x)  "
      f"PZ={EU*EU/EU2:.4f}  mu={mu:.4f}  first-moment mu-bound=(7/6)E[U]={7*EU/6:.5f} (m_P={MP:.5f})")

print("\n=== Q2: adversarial inf of PZ=E[U]^2/E[U^2] (bar m_P = %.5f) ===" % MP)
def pzobj(E):
    EU,EU2,_=U_stats(E,xs_c); return EU*EU/EU2 if EU2>0 else 9.9
resPZ = descend(pzobj, STARTS, iters=800)
for cur,E in resPZ[:4]: print(f"  coarse PZ={cur:.5f}  {E}")
bestPZ_E=list(resPZ[0][1])
EU,EU2,mu = U_stats(bestPZ_E, xs_f)
print(f"finalist fine-grid: PZ={EU*EU/EU2:.5f} (ratio {(EU*EU/EU2)/MP:.2f}x over m_P)  "
      f"E[U]={EU:.5f}  mu={mu:.4f}")

# ---------- Q3: balanced-lattice truncation ----------
print("\n=== Q3: balanced-lattice truncation of E[U_{1/7}] ===")
def phi(m,u=THETA):
    if m==0: return complex(u,0)
    return (1-np.exp(-2j*np.pi*m*u))/(2j*np.pi*m)

def triple_sum(E,u=THETA,TMAX=60):
    """sum over all triples and harmonics t of prod phi(t*w_i); sign (-1)^3."""
    tot=0.0
    for (a,b,c) in combinations(E,3):
        w=(b-c, c-a, a-b)
        g=reduce(gcd,[abs(v) for v in w])
        w=tuple(v//g for v in w)
        s=0.0
        for t in range(1,TMAX+1):
            term=phi(t*w[0],u)*phi(t*w[1],u)*phi(t*w[2],u)
            s+=2*term.real   # t and -t are conjugates
        tot+=s
    return -tot   # (-1)^{|T|=3}

def quad_sum(E,u=THETA,MMAX=4):
    """small-coefficient weight-4 balanced relations (all m_i nonzero, |m_i|<=MMAX),
    with primitive-solution deduplication via set of solution tuples."""
    tot=0.0
    Earr=list(E)
    for idx in combinations(range(13),4):
        e=[Earr[i] for i in idx]
        seen=set()
        for m1 in range(-MMAX,MMAX+1):
            if m1==0: continue
            for m2 in range(-MMAX,MMAX+1):
                if m2==0: continue
                for m3 in range(-MMAX,MMAX+1):
                    if m3==0: continue
                    m4=-(m1+m2+m3)
                    if m4==0 or abs(m4)>MMAX: continue
                    if m1*e[0]+m2*e[1]+m3*e[2]+m4*e[3]!=0: continue
                    key=(m1,m2,m3,m4)
                    if key in seen: continue
                    seen.add(key)
                    term=phi(m1,u)*phi(m2,u)*phi(m3,u)*phi(m4,u)
                    tot+=term.real
    return tot   # (-1)^{|T|=4} = +1

BANK = {
    'AP {1..13}':                 list(range(1,14)),
    'monad record evens+{11,13}': [2,4,6,8,10,11,12,13,14,16,18,20,22],
    'opus stretched {0,2..12,17,28}': [0]+list(range(2,13))+[17,28],
    'E[U]-descent finalist':      bestU_E,
    'random big':                 sorted(rnd.sample(range(1,2000),13)),
}
main=(1-THETA)**13
print(f"main=(6/7)^13={main:.5f}; deficit budget to bar: {main-BAR_EU:.5f}")
print(f"{'family':34s} {'E[U] grid':>9s} {'main+w3':>9s} {'main+w3+w4':>10s} {'grid-w3 err':>11s} {'grid-w34 err':>12s}")
for name,E in BANK.items():
    EU,_,_ = U_stats(E,xs_f)
    w3=triple_sum(E)
    w4=quad_sum(E)
    a3=main+w3; a34=main+w3+w4
    print(f"{name:34s} {EU:9.5f} {a3:9.5f} {a34:10.5f} {EU-a3:11.5f} {EU-a34:12.5f}")

# unsigned triple mass: the provability margin for a crude bound
print("\nunsigned triple mass (crude-bound feasibility): sum |per-triple sums|")
for name,E in BANK.items():
    tot=0.0
    for (a,b,c) in combinations(E,3):
        w=(b-c,c-a,a-b); g=reduce(gcd,[abs(v) for v in w]); w=tuple(v//g for v in w)
        s=sum(2*(phi(t*w[0])*phi(t*w[1])*phi(t*w[2])).real for t in range(1,60))
        tot+=abs(s)
    print(f"  {name:34s} unsigned-w3 mass = {tot:.5f}  (budget {main-BAR_EU:.5f}) {'OK' if tot<main-BAR_EU else 'exceeds -> need signs/quad'}")

# sanity: window identity at one x
E=list(range(1,14)); x=0.2371
pts=sorted((e*x)%1.0 for e in E)
g=[pts[0]+1-pts[-1]]+[pts[i+1]-pts[i] for i in range(12)]
Udirect=sum(max(0,gg-THETA) for gg in g)
ss=np.linspace(0,1,200001)[:-1]
empt=0
for s in ss[::40]:  # subsample for speed
    a,bnd=s,(s+THETA)%1.0
    if a<bnd: ok=all(not(a<p<bnd) for p in pts)
    else: ok=all(not(p>a or p<bnd) for p in pts)
    empt+=ok
print(f"\nsanity window-identity: U direct={Udirect:.5f} vs window-frac={empt/len(ss[::40]):.5f}")
