#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
lrc14_spectrum_intersection_sum_kpswf12.py   (kind-pasteur 2026-06-22-S34, THREAD 3 / NODE 3)

THE SPECTRUM-INTERSECTION SUM for the quasi-independence ratio R'.

OBJECTS (all on the circle [0,1), exact rationals where possible):
  coverSet(E)   = { x : all 7 sectors [r/7,(r+1)/7) hit by {frac(e_i x): e_i in E} }
                  (the "L7 / S7" sector route).   p0 := meas(coverSet(E)).
  coverSet^c    = { x : >=1 of the 7 sectors is MISSED }.   meas = 1 - p0.
  G_P           = { x : ||p x|| >= 1/14  for all p in P }.   (the witness/lonely arc set)

  G_P-indicator   c(x) = 1_{G_P}(x).      chat(n) = Fourier coeff.   chat(0)=meas(G_P).
  cover kernel    g(x) = 1_{coverSet^c}(x).  ghat(n) = Fourier coeff. ghat(0)=1-p0.

PARSEVAL (the spectrum-intersection sum):
  meas(coverSet^c cap G_P) = <c, g> = sum_n chat(n) conj(ghat(n))
        = chat(0) ghat(0)  +  sum_{n != 0} chat(n) conj(ghat(n))
        = meas(G_P) (1-p0)  +  SPEC,        SPEC := sum_{n != 0} chat(n) conj(ghat(n)).

  R' := meas(coverSet^c cap G_P) / ( meas(G_P) (1-p0) )
      = 1 + SPEC / ( meas(G_P) (1-p0) ).

  So SPEC is EXACTLY the deviation-from-independence, and
     R' >= c  <==>  SPEC >= -(1-c) * meas(G_P)(1-p0)   (i.e. |SPEC| < (1-c)*baseline if SPEC<0).

WHY chat is lattice/Bohr supported (HYP-2606 connection):
  1_{G_P} = prod_{p in P} 1_{A_p},  A_p = {x: frac(px) in [1/14,13/14]}.
  Each 1_{A_p}(x) = sum_m a_m e(m p x)  (its only frequencies are MULTIPLES OF p).
  Hence the product's frequencies are sums sum_p m_p p -- the additive SEMIGROUP/LATTICE
  generated by P (the "Bohr/lattice support").  This is precisely HYP-2606's offset-relation
  lattice viewpoint applied to the G_P factor.

WHY ghat decays like 1/n (HYP-2840 / sector route):
  coverSet^c = union over sectors r of {sector r missed} = union_r intersect_i {frac(e_i x) notin sector r}.
  Its indicator is a finite-union-of-intervals indicator on [0,1) (breakpoints rational with denom
  | 7*lcm(diffs)); a BV/indicator function has |ghat(n)| <= (total variation)/(2 pi |n|) = O(1/n).
  Concretely |ghat(n)| <= (#jumps of g)/(2 pi |n|).

EXACT ARITHMETIC:
  Fourier coeff of an interval indicator 1_{[a,b)} (a,b rational, common denom D):
     hat(n) = (e(-n a) - e(-n b)) / (2 pi i n),   e(t)=exp(2 pi i t).
  We represent e(-n a) exactly as a primitive-D root of unity power; chat(n), ghat(n) are then
  (rational combos of D-th roots of unity)/(2 pi i n).  The PRODUCT chat(n)conj(ghat(n)) has the
  2 pi i n factors as 1/(2 pi i n) * conj(1/(2 pi i n)) = 1/(4 pi^2 n^2): the pi^2 cancels against
  nothing here so SPEC is computed as a high-precision sum and CROSS-CHECKED against the EXACT
  real-space intersection measure (Fraction).  The decomposition (low/high) is the deliverable.

VALIDATION: SPEC computed two independent ways must agree:
  (i)  real-space:  SPEC_exact = meas(coverSet^c cap G_P) - meas(G_P)(1-p0)   [EXACT Fraction]
  (ii) spectral:    SPEC_spec  = sum_{0<|n|<=N} chat(n)conj(ghat(n))          [-> SPEC_exact as N->inf]
"""
import sys, itertools, cmath, math
from fractions import Fraction as F
from math import gcd, pi
from functools import reduce
try:
    sys.stdout.reconfigure(encoding="utf-8", line_buffering=True)
except Exception:
    pass

TWO_PI = 2.0 * pi

# ============================================================ arc utilities (exact)
def merge(iv):
    iv = sorted(iv); out = []
    for a, b in iv:
        if out and a <= out[-1][1]:
            out[-1] = (out[-1][0], max(out[-1][1], b))
        else:
            out.append((a, b))
    return out

def meas(arcs):
    return sum((b - a for a, b in arcs), F(0))

def intersect(A, B):
    out = []; i = j = 0
    A = merge(A); B = merge(B)
    while i < len(A) and j < len(B):
        lo = max(A[i][0], B[j][0]); hi = min(A[i][1], B[j][1])
        if lo < hi: out.append((lo, hi))
        if A[i][1] < B[j][1]: i += 1
        else: j += 1
    return out

def complement(arcs):
    arcs = merge(arcs); out = []; prev = F(0)
    for a, b in arcs:
        if a > prev: out.append((prev, a))
        prev = max(prev, b)
    if prev < 1: out.append((prev, F(1)))
    return out

# ============================================================ G_P (the lonely arc set)
def danger_arcs(u, h=F(1, 14)):
    """{x: ||u x|| < h} as union of arcs (the complement is G_P-for-this-p)."""
    iv = []
    for j in range(u):
        c = F(j, u); a = (c - h / u) % 1; b = (c + h / u) % 1
        if a < b: iv.append((a, b))
        else: iv.append((a, F(1))); iv.append((F(0), b))
    return iv

def safe_set(P, h=F(1, 14)):
    """G_P = {x: ||p x|| >= h for all p in P}."""
    if not P: return [(F(0), F(1))]
    return complement(merge([iv for u in P for iv in danger_arcs(u, h)]))

# ============================================================ coverSet (sector route)
def sector_of(ph):
    """which of 7 sectors [r/7,(r+1)/7) does phase ph in [0,1) lie in (exact)."""
    return int(ph * 7)   # floor; ph in [0,1) Fraction -> r in 0..6

def cover_set(E):
    """coverSet(E) = {x: all 7 sectors hit by {frac(e x): e in E}} as exact arc union.
       p0 = meas(cover_set(E))."""
    E = sorted(set(int(e) for e in E))
    # phases frac(e x) cross sector boundary r/7 when e x = (m + r/7) i.e. x = (7 m + r)/(7 e).
    bps = set([F(0), F(1)])
    for e in E:
        if e == 0:
            continue
        for m in range(7 * e + 1):
            v = F(m, 7 * e)
            if 0 < v < 1: bps.add(v)
    pts = sorted(bps)
    cov = []
    for a, b in zip(pts, pts[1:]):
        mid = (a + b) / 2
        hit = set()
        for e in E:
            hit.add(sector_of((F(e) * mid) % 1))
        if len(hit) == 7:
            cov.append((a, b))
    return merge(cov)

# ============================================================ EXACT Fourier coefficients
# For an interval indicator 1_{[a,b)} with a,b rationals of common denominator D,
#   hat(n) = (e(-n a) - e(-n b)) / (2 pi i n),  e(t) = exp(2 pi i t),  n != 0.
# We accumulate the numerator NUM(n) = sum over intervals of (e(-n a) - e(-n b)) as an
# exact element of Z[zeta_D] using a length-D complex array of integer/rational coeffs is
# heavy; instead we evaluate e(-n a) at the exact rational a with high-precision complex.
# The DECISION quantities (SPEC) are cross-checked against the exact Fraction real-space value,
# so the spectral side is a (very high precision) numeric confirmation + the routing structure.

def e(t):
    """exp(2 pi i t), t a Fraction (reduced exactly mod 1 first)."""
    t = t % 1
    return cmath.exp(2j * pi * float(t))

def fourier_num_of_arcs(arcs, n):
    """numerator sum_intervals (e(-n a) - e(-n b)); hat(n) = this / (2 pi i n)."""
    s = 0j
    for a, b in arcs:
        s += e(-n * a) - e(-n * b)
    return s

def fourier_coeff(arcs, n):
    """hat(n) for n != 0 (complex); for n == 0 returns meas as float."""
    if n == 0:
        return float(meas(arcs))
    return fourier_num_of_arcs(arcs, n) / (2j * pi * n)

# ============================================================ spectrum sum
def spectrum_sum(gp_arcs, covc_arcs, N):
    """SPEC_spec = sum_{0<|n|<=N} chat(n) conj(ghat(n)), and the partial-sum trace.
       Uses chat(-n)=conj(chat(n)) so we sum n=1..N and double the real part.
       chat(n)conj(ghat(n)) + chat(-n)conj(ghat(-n)) = 2 Re[chat(n)conj(ghat(n))]."""
    total = 0.0
    trace = []
    # numerators NUM_c(n) = sum (e(-n a)-e(-n b)) over G_P arcs; chat(n)=NUM_c/(2 pi i n)
    for n in range(1, N + 1):
        cn = fourier_num_of_arcs(gp_arcs, n) / (2j * pi * n)
        gn = fourier_num_of_arcs(covc_arcs, n) / (2j * pi * n)
        term = cn * gn.conjugate()
        total += 2.0 * term.real
        if n in (1, 2, 3, 5, 7, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, N):
            trace.append((n, total))
    return total, trace

def low_high_split(gp_arcs, covc_arcs, N, Hlow):
    """sum_low = |n|<=Hlow contributions; sum_high = Hlow<|n|<=N.
       Also the ABSOLUTE tail bound from ghat's 1/n decay:
         |chat(n)conj(ghat(n))| <= |chat(n)| |ghat(n)|, and
         |ghat(n)| <= Vg/(2 pi |n|) with Vg = (total var of g) = #jumps,
         |chat(n)| <= Vc/(2 pi |n|) with Vc = #jumps of 1_{G_P}.
       So |term(n)| <= Vc Vg /(4 pi^2 n^2), and the tail sum_{|n|>Hlow} <= Vc Vg/(4 pi^2) * 2 * (1/Hlow)
       (since sum_{n>H} 1/n^2 < 1/H)."""
    slow = 0.0; shigh = 0.0
    for n in range(1, N + 1):
        cn = fourier_num_of_arcs(gp_arcs, n) / (2j * pi * n)
        gn = fourier_num_of_arcs(covc_arcs, n) / (2j * pi * n)
        term = 2.0 * (cn * gn.conjugate()).real
        if n <= Hlow: slow += term
        else: shigh += term
    # variation = number of jump discontinuities of each indicator = 2 * (#arcs)
    Vc = 2 * len(merge(gp_arcs))
    Vg = 2 * len(merge(covc_arcs))
    tail_bound = (Vc * Vg) / (4 * pi * pi) * (2.0 / Hlow)   # sum_{|n|>Hlow} |term| <= ...
    return slow, shigh, Vc, Vg, tail_bound

# ============================================================ main
def analyze(P, E, N=4000, Hlow=20, label=""):
    P = sorted(set(int(p) for p in P)); E = sorted(set(int(x) for x in E))
    gp = safe_set(P)
    cov = cover_set(E)
    covc = complement(cov)
    mGP = meas(gp); p0 = meas(cov); one_minus_p0 = meas(covc)
    assert one_minus_p0 == 1 - p0
    inter = intersect(gp, covc)
    m_inter = meas(inter)
    baseline = mGP * one_minus_p0
    SPEC_exact = m_inter - baseline           # EXACT Fraction
    Rprime = (m_inter / baseline) if baseline > 0 else F(1)

    SPEC_spec, trace = spectrum_sum(gp, covc, N)
    slow, shigh, Vc, Vg, tail_bound = low_high_split(gp, covc, N, Hlow)

    print("=" * 92)
    print(f"  ({label})  P={P}")
    print(f"            E={E}   (k={len(E)})")
    print("=" * 92)
    print(f"  meas(G_P)              = {mGP} = {float(mGP):.8f}")
    print(f"  p0 = meas(coverSet)    = {p0} = {float(p0):.8f}")
    print(f"  1-p0 = meas(cover^c)   = {one_minus_p0} = {float(one_minus_p0):.8f}")
    print(f"  baseline = G_P*(1-p0)  = {baseline} = {float(baseline):.8f}")
    print(f"  meas(cover^c cap G_P)  = {m_inter} = {float(m_inter):.8f}")
    print(f"  -- SPEC (exact, real-space) = inter - baseline = {SPEC_exact} = {float(SPEC_exact):.8f}")
    print(f"  -- R' = inter/baseline      = {Rprime} = {float(Rprime):.8f}")
    print(f"  spectral SPEC (|n|<= {N})   = {SPEC_spec:.8f}   (-> exact {float(SPEC_exact):.8f})")
    print(f"     agreement |spec-exact|   = {abs(SPEC_spec-float(SPEC_exact)):.2e}")
    print(f"  partial-sum trace (n, cumulative SPEC):")
    for n, t in trace:
        print(f"       n<= {n:5d}:  {t:+.8f}")
    print(f"  LOW/HIGH split at Hlow={Hlow}:")
    print(f"     sum_low (|n|<={Hlow})     = {slow:+.8f}")
    print(f"     sum_high ({Hlow}<|n|<={N}) = {shigh:+.8f}")
    print(f"     #jumps G_P  Vc = {Vc},  #jumps cover^c  Vg = {Vg}")
    print(f"     ABS tail bound |sum_{{|n|>{Hlow}}}| <= Vc*Vg/(4pi^2) * 2/{Hlow} = {tail_bound:.6f}")
    # R'>=c explicit check:
    print(f"  --> R' >= c  with c = R' itself = {float(Rprime):.6f}.")
    if SPEC_exact < 0:
        # |SPEC| < (1-c)*baseline  for which c?  c = 1 - |SPEC|/baseline = R'
        print(f"      SPEC<0: |SPEC|={float(-SPEC_exact):.8f} = (1-R')*baseline, (1-R')={float(1-Rprime):.6f}")
    else:
        print(f"      SPEC>=0: independence-favourable (R'>=1), R'-1 = {float(Rprime-1):.6f}")
    return dict(P=P, E=E, mGP=mGP, p0=p0, baseline=baseline, m_inter=m_inter,
                SPEC_exact=SPEC_exact, Rprime=Rprime, Vc=Vc, Vg=Vg,
                slow=slow, shigh=shigh, tail_bound=tail_bound)

def main():
    print("#" * 92)
    print("# THREAD 3 / NODE 3 : THE SPECTRUM-INTERSECTION SUM  (kind-pasteur kpswf12)")
    print("#   R' = 1 + SPEC/baseline,  SPEC = sum_{n!=0} chat(n) conj(ghat(n))")
    print("#   chat = G_P indicator coeffs (P-lattice/Bohr support, HYP-2606)")
    print("#   ghat = cover^c indicator coeffs (1/n decay, BV)")
    print("#" * 92)

    # Representative (P, cluster) cases spanning consec / near-AP / wide / resonant.
    cases = [
        # (P, E, label) -- |P|+|E| = 13 admissible where natural, but R' is defined for any (P,E).
        ([1, 2, 3, 12, 13], [0, 1, 2, 3, 4, 5, 6, 7], "k=8 consec, P=worst-ish"),
        ([1, 2, 3, 4, 5],   [0, 1, 2, 3, 4, 5, 6, 7], "k=8 consec, small P"),
        ([1, 2, 3, 12],     [0, 1, 2, 3, 4, 5, 6, 7, 8], "k=9 consec"),
        ([1, 2, 3],         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], "k=10 consec, |P|=3"),
        ([1, 2, 3, 12, 13], [0, 2, 3, 4, 5, 6, 7, 8], "k=8 perforated near-AP (the 2/7 zero family)"),
        ([5, 7, 11],        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], "k=10, P coprime cluster"),
        ([1, 2, 6],         [0, 4, 6, 8, 10, 12, 14, 15, 16, 17], "wide d>=2 leader-ish"),
    ]
    results = []
    for P, E, lab in cases:
        results.append(analyze(P, E, N=4000, Hlow=20, label=lab))
        print()

    # Summary table of R' and SPEC
    print("=" * 92)
    print("SUMMARY: the quasi-independence ratio R' and the spectrum sum SPEC")
    print("=" * 92)
    print(f"{'case':<46}{'R-prime':>12}{'SPEC':>14}{'baseline':>14}")
    for r in results:
        lab = f"P={r['P']} k={len(r['E'])}"
        print(f"{lab:<46}{float(r['Rprime']):>12.5f}{float(r['SPEC_exact']):>14.6f}{float(r['baseline']):>14.6f}")
    Rs = [r['Rprime'] for r in results]
    print(f"\n  R' range over these cases: [{float(min(Rs)):.5f}, {float(max(Rs)):.5f}]")
    print(f"  (prompt's reported R' in [0.66,1.27]; floor 0.20-0.37 >> m_P)")
    print("DONE.")

if __name__ == "__main__":
    main()
