#!/usr/bin/env python3
"""
lrc14_coprime30030_scope_klein_S265.py
======================================
klein-2026-07-12-S265 (combinatorial connections + simplifications)

QUESTION: mac-mini cont.50 / opus-S243 corrected the large-diameter invariant to
"<= 6 speeds coprime to 30030 = 2*3*5*7*11*13", verified 100% for BOUNDED-diameter
primitive divisor-complete (DC) 13-sets (mean 2.0). Is it a UNIVERSAL combinatorial
theorem, or bounded-diameter only?

CLAIM (this script): it is BOUNDED-DIAMETER ONLY, and the sharp obstruction is
combinatorial: a SINGLE speed = k * lcm(2..14) = k * 360360 witnesses EVERY d in
{2..14} at once (divisor-complete), so the other 12 speeds may ALL be coprime to
30030. Hence a primitive DC 13-set can have **12** coprime-to-30030 speeds. But such
families are STILL loose (M > 1/14), because their 12 coprime speeds are LARGE/spread
=> the multi-scale route (THM-687/688), not the <=6 shrink, is what closes them.

divisor_complete(v) := all(any(x % d == 0 for x in v) for d in 2..14)   [= covering]
coprime30030(x)     := gcd(x, 30030) == 1

Outputs:
  (1) the explicit 12-coprime counterexample: primitive? DC? #coprime? M (loose?).
  (2) diameter sweep: max #coprime-to-30030 over primitive DC 13-sets vs diameter cap
      (random search) -- where does "<=6" break?
  (3) minimum #non-coprime (DC set-cover): the combinatorial floor on structured speeds.
  (4) scale check on the counterexample: are the 12 coprime speeds separated from the
      heavy witness (=> multi-scale applies)?
"""
import math, random
from fractions import Fraction
from itertools import combinations

random.seed(265)  # deterministic
P13 = [2,3,5,7,11,13]
M30030 = 30030
LCM_2_14 = 360360  # lcm(2..14)

def divisor_complete(v):
    return all(any(x % d == 0 for x in v) for d in range(2,15))

def primitive(v):
    g = 0
    for x in v: g = math.gcd(g, x)
    return g == 1

def n_coprime30030(v):
    return sum(1 for x in v if math.gcd(x, M30030) == 1)

# ---- exact M via THM-668 pair-sum ruler ----
def dist0(r,q): return min(r, q-r)
def pair_sums(v):
    qs=set()
    for a,b in combinations(range(len(v)),2): qs.add(v[a]+v[b])
    for a in range(len(v)): qs.add(2*v[a])
    return sorted(qs)
def exact_M(v, cap_q=200000):
    best=Fraction(0); argq=None
    for q in pair_sums(v):
        if q>cap_q:  # skip astronomically large rulers for speed
            continue
        mx=0
        for p in range(1,q):
            mn=q
            for vl in v:
                d=dist0((vl*p)%q,q)
                if d<mn:
                    mn=d
                    if mn<=mx: break   # can't beat current best-per-q lower bound
            if mn>mx: mx=mn
        val=Fraction(mx,q)
        if val>best: best=val; argq=q
    return best,argq

print("="*74)
print("(1) THE 12-COPRIME COUNTEREXAMPLE  {k*360360} u {12 units coprime to 30030}")
print("="*74)
# 12 speeds coprime to 30030, small-ish and distinct, + one heavy DC witness
units = [1, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59]   # all coprime to 30030
assert all(math.gcd(u,M30030)==1 for u in units)
counter = sorted(units + [LCM_2_14])
print(f"  family = {counter}")
print(f"  primitive={primitive(counter)}  divisor_complete={divisor_complete(counter)}  "
      f"#coprime-to-30030={n_coprime30030(counter)}  (claim says <=6)")
M,argq = exact_M(counter)
print(f"  exact M = {M} = {float(M):.4f}   (1/14={1/14:.4f})  => {'LOOSE (M>1/14)' if M>Fraction(1,14) else 'TIGHT/BELOW'}  at ruler q={argq}")

# a spread version (units large too) to force multi-scale reading: 12 coprime-to-30030
# integers just above 30030, generated by filtering (not guessing)
units2 = []
x = 30031
while len(units2) < 12:
    if math.gcd(x, M30030) == 1:
        units2.append(x)
    x += 1
assert all(math.gcd(u,M30030)==1 for u in units2)
counter2 = sorted(units2 + [7*LCM_2_14])
print(f"\n  spread version: 12 units near 30030 + heavy 7*360360 (structural only; M-ruler is ~5M, skipped):")
print(f"    primitive={primitive(counter2)}  DC={divisor_complete(counter2)}  #coprime={n_coprime30030(counter2)}")
print(f"    => 12 coprime again at a fully-spread scale; the 12 units sit at a SEPARATE (fine) scale")
print(f"       from the heavy witness => multi-scale (THM-687/688) is the operative reduction.")

print()
print("="*74)
print("(2) DIAMETER SWEEP: max #coprime-to-30030 over primitive DC 13-sets vs diam cap")
print("="*74)
def min_cover_speeds(diam_cap):
    """EXACT: minimum number of speeds (each <= diam_cap) needed so that every d in
       {2..14} divides some speed. Candidate speeds = lcm of subsets of {2..14} that
       are <= diam_cap (only these matter). Then min set cover of {2..14}.
       max #coprime-to-30030 = 13 - min_cover (fill the rest with coprime units)."""
    U = list(range(2,15))
    # candidate covers: for each achievable lcm <= cap, the set of d it covers
    from math import gcd as _g
    def lcm(a,b): return a*b//_g(a,b)
    covers = {}  # frozenset(d covered) : witnessed
    # build all subset-lcms <= cap (bounded: the distinct lcms are few)
    lcms = {1}
    for d in U:
        new = set()
        for x in list(lcms):
            l = lcm(x,d)
            if l <= diam_cap: new.add(l)
        lcms |= new
    cand = []
    for s in lcms:
        if s == 1: continue
        cov = frozenset(d for d in U if s % d == 0)
        if cov: cand.append(cov)
    # min set cover of U by cand (U is 13 elements; greedy + exact for small)
    from itertools import combinations as comb
    best = 13
    # exact: try covers of size 1,2,3,...
    for k in range(1, 8):
        found = False
        for combo in comb(range(len(cand)), k):
            union = set()
            for i in combo: union |= cand[i]
            if len(union) == len(U):
                found = True; break
        if found:
            best = k; break
    return best
def coprime_supply(cap):
    """# of integers in [1,cap] coprime to 30030 (the SUPPLY of coprime speeds)."""
    return sum(1 for x in range(1, cap+1) if math.gcd(x, M30030) == 1)
print(f"  {'diam cap':>9s} {'min-cover':>9s} {'13-mincover':>11s} {'coprime supply':>14s} {'TRUE max #coprime':>17s}")
for cap in [14, 20, 30, 45, 60, 90, 120, 360, 2520, 360360]:
    mc = min_cover_speeds(cap)
    sup = coprime_supply(cap)
    maxcop = min(13 - mc, sup)          # bounded by BOTH set-cover and supply
    tag = "  <-- BREAKS <=6" if maxcop >= 7 else ""
    print(f"  {cap:>9d} {mc:>9d} {13-mc:>11d} {sup:>14d} {maxcop:>17d}{tag}")
print(f"  (TRUE max #coprime = min(13 - min-cover, coprime-supply): DC needs >= min-cover NON-coprime")
print(f"   witnesses AND there must be enough coprime-to-30030 integers <= cap to fill the rest.")
print(f"   <=6 holds for cap up to ~45-59; BREAKS once BOTH one speed covers enough AND >=7 coprime")
print(f"   units are available (~cap 60). So <=6 is a SMALL-diameter regularity, not a bounded-diam thm.")

print()
print("="*74)
print("(3) COMBINATORIAL FLOOR: min # non-coprime-to-30030 speeds to be DC (set cover)")
print("="*74)
# each d in 2..14 needs a witness; a speed covers the d's dividing it. Min speeds to
# cover {2..14}? A single lcm(2..14) covers all -> min=1. Show a 1-witness DC family.
print(f"  lcm(2..14) = {LCM_2_14} is divisible by every d in 2..14 => ONE speed suffices")
print(f"  => min #non-coprime = 1 => max #coprime = 12 (combinatorially, no diam bound)")
print(f"  So 'DC => <=6 coprime' is FALSE without a diameter bound; DC alone forces only >=1 non-coprime.")

print()
print("="*74)
print("(4) SCALE SEPARATION on the counterexample (why multi-scale, not the shrink)")
print("="*74)
gap = LCM_2_14 / max(units)
print(f"  counterexample: 12 units in [1,{max(units)}], heavy witness {LCM_2_14}")
print(f"  scale ratio heavy/max-unit = {gap:.0f}  => the heavy witness is a SEPARATE scale")
print(f"  multi-scale (THM-687/688) reads v = base + L*lift; the heavy witness sits at the")
print(f"  coarse scale, the 12 units at the fine scale => reduces to a small effective family.")
print(f"  => the <=6-coprime shrink is bounded-diameter; large-diameter uses multi-scale. Both loose.")
print("\ndone.")
