#!/usr/bin/env python3
"""HYP-2697 / T933 / S62: arbitrary bounded cluster-shape compression scout.

THM-557 proves the coherent-block quotient: once every far cluster is a
consecutive block, the single block is the exact decorrelated maximizer.  The
remaining HYP-2694 gap is to compress arbitrary bounded shapes into that
coherent-block quotient.

This scout tests several possible meanings of "compression":

1. Coordinatewise residual-capacity dominance.
   For a shape C and residual sector set R, q_C(R) is the probability, averaged
   over slow x and carrier phase phi, that C covers every sector in R.  If
   q_C(R) <= q_K(R) for all R, with K={0,...,|C|-1}, then K can replace C in any
   independent context.  This turns out to be FALSE.

2. Full-cover scalar dominance.
   The same q_C(R), but only for R=all six inner sectors.  This is the scalar
   one-cluster cover.  Consecutive remains the winner in the bounded grid boxes
   tested here.

3. Context-weighted compression.
   Actual HYP-2694 contexts do not use arbitrary nonnegative weights on R; they
   use residual profiles generated by other clusters.  Beam scans of split
   contexts keep the split below the one-block value.  This suggests the right
   theorem is a cone statement: decorrelated LRC contexts lie in a large-residual
   cone where the consecutive block maximizes the weighted capacity functional.

The broad scans are midpoint-grid scouts, not proofs.  The small dominance
failures and named context checks are exact Fractions.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
from fractions import Fraction as F
from itertools import combinations, permutations
from math import gcd


INNER = tuple(range(1, 7))
FULL_MASK = (1 << 6) - 1
NX = 42
NPHI = 42


def mask_to_sectors(mask: int) -> tuple[int, ...]:
    return tuple(i + 1 for i in range(6) if mask & (1 << i))


def mask_size(mask: int) -> int:
    return mask.bit_count()


def primitive(shape: tuple[int, ...]) -> bool:
    g = 0
    for x in shape:
        g = gcd(g, x)
    return g == 1


def bounded_shapes(size: int, span: int) -> list[tuple[int, ...]]:
    if size == 1:
        return [(0,)]
    out: list[tuple[int, ...]] = []
    for rest in combinations(range(1, span + 1), size - 1):
        shape = (0,) + rest
        if primitive(shape):
            out.append(shape)
    return out


@lru_cache(maxsize=None)
def exact_breakpoints(shape: tuple[int, ...]) -> tuple[F, ...]:
    bps = {F(0), F(1)}
    for d in shape:
        if d == 0:
            continue
        for a in range(7 * d + 1):
            bps.add(F(a, 7 * d))
    return tuple(sorted(bps))


@lru_cache(maxsize=None)
def exact_dist_at_x(shape: tuple[int, ...], x: F) -> tuple[tuple[int, F], ...]:
    base = tuple((d * x) % 1 for d in shape)
    cuts = {F(0), F(1)}
    for b in base:
        for s in range(7):
            cuts.add((F(s, 7) - b) % 1)
    cuts = sorted(cuts)
    dist: dict[int, F] = defaultdict(F)
    for lo, hi in zip(cuts, cuts[1:]):
        if hi <= lo:
            continue
        mid = (lo + hi) / 2
        mask = 0
        for b in base:
            sec = int(((b + mid) % 1) * 7)
            if 1 <= sec <= 6:
                mask |= 1 << (sec - 1)
        dist[mask] += hi - lo
    return tuple(sorted(dist.items()))


@lru_cache(maxsize=None)
def exact_capacity_vector(shape: tuple[int, ...]) -> tuple[F, ...]:
    """q_C(R) for every residual mask R, exact."""
    total = [F(0) for _ in range(64)]
    xs = exact_breakpoints(shape)
    for lo, hi in zip(xs, xs[1:]):
        if hi <= lo:
            continue
        mid = (lo + hi) / 2
        dist = exact_dist_at_x(shape, mid)
        for hit, mass in dist:
            sub = hit
            while True:
                total[sub] += (hi - lo) * mass
                if sub == 0:
                    break
                sub = (sub - 1) & hit
    return tuple(total)


@lru_cache(maxsize=None)
def grid_distributions(shape: tuple[int, ...]) -> tuple[tuple[float, ...], ...]:
    """Midpoint grid law of hit masks for each slow-x grid point."""
    rows: list[tuple[float, ...]] = []
    for ix in range(NX):
        x = (ix + 0.5) / NX
        base = tuple((d * x) % 1.0 for d in shape)
        counts = [0] * 64
        for ip in range(NPHI):
            phi = (ip + 0.5) / NPHI
            mask = 0
            for b in base:
                sec = int(((phi + b) % 1.0) * 7)
                if 1 <= sec <= 6:
                    mask |= 1 << (sec - 1)
            counts[mask] += 1
        rows.append(tuple(c / NPHI for c in counts))
    return tuple(rows)


def zeta_capacity_float(dist: tuple[float, ...]) -> list[float]:
    cap = [0.0] * 64
    for hit, mass in enumerate(dist):
        if mass == 0.0:
            continue
        sub = hit
        while True:
            cap[sub] += mass
            if sub == 0:
                break
            sub = (sub - 1) & hit
    return cap


@lru_cache(maxsize=None)
def grid_capacity_vector(shape: tuple[int, ...]) -> tuple[float, ...]:
    total = [0.0] * 64
    for dist in grid_distributions(shape):
        cap = zeta_capacity_float(dist)
        for i, v in enumerate(cap):
            total[i] += v
    return tuple(v / NX for v in total)


def grid_pcover(shapes: tuple[tuple[int, ...], ...]) -> float:
    """Grid pcover for independent carriers sharing slow x."""
    dists = [grid_distributions(shape) for shape in shapes]
    total = 0.0
    for ix in range(NX):
        cur = [0.0] * 64
        cur[0] = 1.0
        for ds in dists:
            nxt = [0.0] * 64
            dist = ds[ix]
            for old, old_mass in enumerate(cur):
                if old_mass == 0.0:
                    continue
                for hit, hit_mass in enumerate(dist):
                    if hit_mass:
                        nxt[old | hit] += old_mass * hit_mass
            cur = nxt
        total += cur[FULL_MASK]
    return total / NX


def exact_named_failures() -> None:
    print("PART A -- exact failures of naive residual-vector dominance")
    named = [
        ((0, 1, 2), (0, 1, 3)),
        ((0, 1, 2, 3), (0, 1, 2, 4)),
        ((0, 1, 2, 3, 4), (0, 1, 2, 3, 5)),
    ]
    for consec, challenger in named:
        vc = exact_capacity_vector(consec)
        vv = exact_capacity_vector(challenger)
        gains = [(vv[r] - vc[r], r) for r in range(1, 64) if vv[r] > vc[r]]
        gains.sort(reverse=True)
        print(f"  size={len(consec)} consec={consec} challenger={challenger}")
        print(f"    full-cover: challenger-consec = {vv[FULL_MASK] - vc[FULL_MASK]}")
        for diff, mask in gains[:5]:
            print(
                f"    residual {mask_to_sectors(mask)} gain = {diff} ({float(diff):+.9f})"
            )
    print("  Conclusion: compression cannot be coordinatewise stochastic dominance.")
    print()


def grid_full_cover_scan() -> dict[int, tuple[float, tuple[int, ...], int, tuple[float, tuple[int, ...], int]]]:
    print("PART B -- grid scan: full-cover scalar compression")
    print(f"  midpoint grid NX={NX}, Nphi={NPHI}; these rows are scouting evidence")
    summary = {}
    for size, span in ((6, 11), (7, 12), (8, 11), (9, 11)):
        consec = tuple(range(size))
        cv = grid_capacity_vector(consec)
        best = (cv[FULL_MASK], consec, 0)
        max_gain = (0.0, consec, 0)
        viol = 0
        rows = bounded_shapes(size, span)
        for shape in rows:
            vv = grid_capacity_vector(shape)
            if vv[FULL_MASK] > best[0]:
                best = (vv[FULL_MASK], shape, 0)
            gains = [(vv[r] - cv[r], r) for r in range(1, 64) if vv[r] > cv[r] + 1e-12]
            if gains:
                viol += 1
                gain, mask = max(gains)
                if gain > max_gain[0]:
                    max_gain = (gain, shape, mask)
        summary[size] = (cv[FULL_MASK], best[1], viol, max_gain)
        print(
            f"  size={size}, span<={span}, shapes={len(rows)}: "
            f"consec_full={cv[FULL_MASK]:.9f}, best_full={best[1]} {best[0]:.9f}, "
            f"vector_violators={viol}, max_residual_gain={max_gain[0]:.9f} "
            f"at {max_gain[1]} for R={mask_to_sectors(max_gain[2])}"
        )
    print("  Read: full-cover scalar favors consecutive, but residual-vector gains persist.")
    print()
    return summary


def grid_split_beam() -> None:
    print("PART C -- grid beam: arbitrary split contexts vs one coherent block")
    print("  Candidate shapes per size are top 8 by full-cover scalar in a small span box.")
    for total in range(7, 12):
        single = (tuple(range(total)),)
        single_value = grid_pcover(single)
        best = (0.0, None)
        for left_size in range(1, total):
            right_size = total - left_size
            left_span = min(10, left_size + 4)
            right_span = min(10, right_size + 4)
            left_shapes = bounded_shapes(left_size, left_span)
            right_shapes = bounded_shapes(right_size, right_span)
            left_shapes = sorted(
                left_shapes, key=lambda s: grid_capacity_vector(s)[FULL_MASK], reverse=True
            )[:8]
            right_shapes = sorted(
                right_shapes, key=lambda s: grid_capacity_vector(s)[FULL_MASK], reverse=True
            )[:8]
            for left in left_shapes:
                for right in right_shapes:
                    value = grid_pcover((left, right))
                    if value > best[0]:
                        best = (value, (left_size, right_size, left, right))
        print(
            f"  m={total}: one-block={single_value:.9f}, "
            f"best split beam={best[0]:.9f}, gap={single_value - best[0]:+.9f}, "
            f"arg={best[1]}"
        )
    print("  Read: the dangerous split is singleton + large block, matching THM-557.")
    print()


def exact_context_checks() -> None:
    print("PART D -- exact named context checks using the THM-557 engine")
    # Importing by path avoids making 04-computation a package.
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "s61", "04-computation/lrc14_single_block_extremality_margin_codex_s61.py"
    )
    s61 = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(s61)

    singleton = (0,)
    shapes = [
        tuple(range(10)),
        (0, 1, 2, 3, 4, 5, 6, 7, 8, 10),
        (0, 2, 3, 4, 5, 6, 7, 8, 9, 10),
    ]
    for shape in shapes:
        value = s61.p0_decorr(((0,), singleton, shape))
        print(f"  singleton + {shape}: {value} ({float(value):.9f})")
    single = s61.p0_decorr(((0,), tuple(range(11))))
    print(f"  one coherent size-11 block: {single} ({float(single):.9f})")
    print("  Exact read: nonconsecutive large-block perturbations do not beat the consecutive")
    print("  large block in this singleton context, and the split stays below one block.")
    print()


def tournament_stats(names: list[str], edge_score) -> None:
    edges = {name: set() for name in names}
    for a, b in combinations(names, 2):
        sa, sb = edge_score(a), edge_score(b)
        if sa > sb:
            edges[a].add(b)
        elif sb > sa:
            edges[b].add(a)
        else:
            # deterministic tie path
            edges[a].add(b)
    scores = {name: len(edges[name]) for name in names}
    hist = Counter(scores.values())
    cycles = 0
    for a, b, c in combinations(names, 3):
        triples = ((a, b, c), (a, c, b))
        cyc = False
        for x, y, z in triples:
            if y in edges[x] and z in edges[y] and x in edges[z]:
                cyc = True
        cycles += int(cyc)

    # Hamiltonian path count by brute force; small tournaments only.
    hpaths = 0
    for perm in permutations(names):
        if all(perm[i + 1] in edges[perm[i]] for i in range(len(perm) - 1)):
            hpaths += 1
    print(f"    scores={scores}")
    print(f"    score_hist={dict(sorted(hist.items()))} directed_3cycles={cycles}")
    print(f"    Hamiltonian_path_count={hpaths}")


def tournament_analysis() -> None:
    print("PART E -- Tournament Analysis: what should be a vertex?")
    print("  Shape tournament, size 8.  Vertices are cluster shapes, not runners.")
    shapes = [
        tuple(range(8)),
        (0, 2, 3, 4, 5, 6, 8, 10),
        (0, 1, 2, 3, 4, 5, 6, 8),
        (0, 1, 2, 3, 4, 5, 7, 8),
        (0, 1, 2, 3, 4, 6, 7, 8),
        (0, 1, 2, 4, 5, 6, 7, 8),
    ]
    name = {shape: "K8" if shape == tuple(range(8)) else str(shape) for shape in shapes}
    names = [name[s] for s in shapes]
    by_name = {name[s]: s for s in shapes}
    print("  Switch 1: full-cover scalar q_C(all six); larger wins.")
    tournament_stats(names, lambda n: grid_capacity_vector(by_name[n])[FULL_MASK])
    print("  Switch 2: residual-majority; larger number of residual masks won vs K8 proxy.")

    def residual_majority_score(n: str) -> int:
        shape = by_name[n]
        vec = grid_capacity_vector(shape)
        # Score each vertex by total wins against all other vertices over residual masks.
        wins = 0
        for other_name in names:
            if other_name == n:
                continue
            other = grid_capacity_vector(by_name[other_name])
            wins += sum(1 for r in range(1, 64) if vec[r] > other[r] + 1e-12)
        return wins

    tournament_stats(names, residual_majority_score)
    print("  Lens tournament.  Vertices are proof obligations; larger tuple wins.")
    lenses = {
        "coordinatewise_residual_dominance": (0, 5, 1),
        "full_cover_scalar": (3, 3, 2),
        "context_weighted_cone": (4, 4, 4),
        "split_vs_single_margin": (5, 3, 5),
        "single_block_diagonal_freeze": (5, 2, 4),
        "joint_multi_carrier_error": (2, 5, 5),
    }
    print("    observable=(proved_or_supported, generality, proof_reach)")
    print("    switch: lexicographic proof-usefulness; tie path is listed order")
    tournament_stats(list(lenses), lambda n: lenses[n])
    print()


def main() -> None:
    print("HYP-2697 / T933 / S62 -- arbitrary bounded cluster-shape compression scout")
    print("Goal: refine HYP-2694 beyond THM-557's coherent-block quotient.")
    print()
    exact_named_failures()
    grid_full_cover_scan()
    grid_split_beam()
    exact_context_checks()
    tournament_analysis()
    print("SYNTHESIS")
    print("  Naive coordinatewise residual dominance is false: spread shapes can cover")
    print("  small specified residual sets better than the consecutive block.")
    print("  The full-cover scalar and the HYP-2694 split-context beam still point to")
    print("  consecutive/coherent blocks as the dangerous shapes.")
    print("  New proof target: characterize the residual-profile cone generated by")
    print("  decorrelated LRC contexts and prove consecutive maximizes the weighted")
    print("  capacity functional on that cone.  Then combine with THM-557's split")
    print("  gaps and the joint carrier error budget.")
    print("  No LRC14 proof is claimed.")


if __name__ == "__main__":
    main()
