#!/usr/bin/env python3
"""
lrc14_safecert_codegen_macmini_S65cont22.py -- the hB certificate table emitter.

For each subset S of {1..13} with |S| = size, emits a Lean theorem
    safe_s<size>_<p...> : (capRat(13-size) : R) <= (slowmu (safeSet S)).toReal
proved via MomentFloorRepair.measGP_ge_of_sorted_bands on the cont.16 engine's exact
component list.  The capRat ladder is exactly the per-|S| minima (engine-verified,
cont.22): every family passes with margin, the argmin with equality.

Usage: python3 ... <size> [chunk_first_element]
Emits 04-computation/lean/TournamentH7/TournamentH7/LRCSafeCertSize<size>[_c<e>].lean
"""
import sys
import importlib.util
from fractions import Fraction as F
from itertools import combinations

spec = importlib.util.spec_from_file_location(
    "engine", "/Users/e/Documents/GitHub/math/04-computation/lrc14_interval_measure_engine_macmini_S65cont16.py")
eng = importlib.util.module_from_spec(spec)
spec.loader.exec_module(eng)

CAP = {8: F(2243, 5880), 9: F(1979, 4004), 10: F(55, 91), 11: F(66, 91), 12: F(6, 7), 13: F(1)}

def components(S):
    cur = eng.bands(S[0])
    for p in S[1:]:
        cur = eng.inter(cur, eng.bands(p))
    return sorted(cur)

def safe_j(p, a, b):
    j = (p * a).__floor__()
    assert F(j) + F(1, 14) <= p * a and p * b <= F(j) + F(13, 14), (p, a, b, j)
    return j

def rl(x):
    return f"({x.numerator}/{x.denominator} : ℝ)" if x.denominator != 1 else f"({x.numerator} : ℝ)"

def emit_family(S, cap):
    comps = components(S)
    total = sum(b - a for a, b in comps)
    assert total >= cap, (S, total, cap)
    L = ", ".join(f"({rl(a)}, {rl(b)})" for a, b in comps)
    name = "safe_s" + str(len(S)) + "_" + "_".join(str(p) for p in S)
    Plist = "[" + ",".join(str(p) for p in S) + "]"
    # hcert bullets: per component, per p
    qblocks = []
    for a, b in comps:
        pbullets = "\n".join(
            f"        · exact ⟨{safe_j(p, a, b)}, by norm_num, by norm_num⟩" for p in S)
        qblocks.append(f"""      · intro p hp
        fin_cases hp
{pbullets}""")
    qcases = "\n".join(qblocks)
    return f"""theorem {name} :
    ((({cap.numerator} : ℝ)/{cap.denominator})) ≤ (slowμ (safeSet ({Plist} : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ({Plist} : List ℤ) [{L}]
    (by decide)
    (by
      intro q hq
      fin_cases hq
{qcases})
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([{L}] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = ({total.numerator}/{total.denominator} : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith
"""

def main():
    size = int(sys.argv[1])
    chunk = sys.argv[2] if len(sys.argv) > 2 else None
    cap = CAP[13 - size]
    fams = [list(S) for S in combinations(range(1, 14), size)]
    if chunk is not None:
        if "-" in chunk:
            lo, hi = (int(t) for t in chunk.split("-"))
            fams = [S for S in fams if lo <= S[0] <= hi]
            suffix = f"Size{size}_g{lo}to{hi}"
        else:
            fams = [S for S in fams if S[0] == int(chunk)]
            suffix = f"Size{size}_c{chunk}"
    else:
        suffix = f"Size{size}" 
    thms = [emit_family(S, cap) for S in fams]
    ncomps = sum(len(components(S)) for S in fams)
    body = "\n".join(thms)
    lean = f"""/-
  TournamentH7.LRCSafeCert{suffix} — hB certificate table, |S| = {size}
  (mac-mini-2026-07-09-S65 cont.22, MACHINE-GENERATED by
  lrc14_safecert_codegen_macmini_S65cont22.py from the cont.16 engine).

  {len(fams)} families, {ncomps} components; each theorem floors
  `(slowμ (safeSet S)).toReal` by `capRat {13 - size} = {cap}` (the exact per-|S| minimum,
  attained; every certificate is a rational band check).
-/
import Mathlib
import TournamentH7.LRCMomentFloorRepair

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace SafeCert

open DenseCovers MeasureTheory MomentFloorRepair

{body}
end SafeCert
end LRC14
end LonelyRunner
"""
    outpath = f"/Users/e/Documents/GitHub/math/04-computation/lean/TournamentH7/TournamentH7/LRCSafeCert{suffix}.lean"
    open(outpath, "w").write(lean)
    print(f"wrote {outpath}: {len(fams)} families, {ncomps} components, cap {cap}")

if __name__ == "__main__":
    main()
