#!/usr/bin/env python3
"""
lrc14_mpcert_codegen_macmini_S65cont25.py -- the hsmall discharge certificate layer.

Emits three Lean files:
1. LRCMPCertSize10.lean -- 286 theorems: m_P = 14249/252252 <= mu(safeSet S) for every
   size-10 subset S of {1..13} (m_P is the exact min over |S| <= 10, attained at
   {1,2,3,5,7,8,9,11,12,13}; every family passes, the argmin with equality).
2. LRCAnchor12Certs.lean -- 13 theorems: anchor-length <= mu(safeSet F_m) for the
   twelve-element families F_m = {1..13} minus m (positivity anchors for hk12).
3. LRCMPLeafTrees.lean -- interval_cases trees over sorted tuples, sizes 6..10:
   size-10 leaves cite (1); sizes 6..9 leaves complete to a canonical size-10
   superset via measGP_anti + decide; plus anchor_pos_of_missing (13-way dispatch
   from a missing element to the anchor certificates).

Usage: python3 ... {certs10 | anchors | trees | all}
"""
import sys
import importlib.util
from fractions import Fraction as F
from itertools import combinations

spec = importlib.util.spec_from_file_location(
    "engine", "/Users/e/Documents/GitHub/math/04-computation/lrc14_interval_measure_engine_macmini_S65cont16.py")
eng = importlib.util.module_from_spec(spec)
spec.loader.exec_module(eng)

MP = F(14249, 252252)
LEAN_DIR = "/Users/e/Documents/GitHub/math/04-computation/lean/TournamentH7/TournamentH7/"

def components(S):
    cur = eng.bands(S[0])
    for p in S[1:]:
        cur = eng.inter(cur, eng.bands(p))
    return sorted(cur)

def safe_j(p, a, b):
    j = (p * a).__floor__()
    assert F(j) + F(1, 14) <= p * a and p * b <= F(j) + F(13, 14), (p, a, b, j)
    return j

def rl(x):
    return f"({x.numerator}/{x.denominator} : ℝ)" if x.denominator != 1 else f"({x.numerator} : ℝ)"

def header(name, desc):
    return f"""/-
  TournamentH7.{name} — {desc}
  (mac-mini-2026-07-09-S65 cont.25, MACHINE-GENERATED by
  lrc14_mpcert_codegen_macmini_S65cont25.py from the cont.16 engine).
-/
import Mathlib
import TournamentH7.LRCMomentCitation

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace MPCert

open DenseCovers MeasureTheory MomentFloorRepair

"""

FOOTER = """end MPCert
end LRC14
end LonelyRunner
"""

def emit_floor_theorem(name, S, floor, comps):
    """floor <= mu(safeSet S) via measGP_ge_of_sorted_bands over comps."""
    total = sum(b - a for a, b in comps)
    assert total >= floor, (S, total, floor)
    L = ", ".join(f"({rl(a)}, {rl(b)})" for a, b in comps)
    Plist = "[" + ",".join(str(p) for p in S) + "]"
    qblocks = []
    for a, b in comps:
        pbullets = "\n".join(
            f"        · exact ⟨{safe_j(p, a, b)}, by norm_num, by norm_num⟩" for p in S)
        qblocks.append(f"""      · intro p hp
        fin_cases hp
{pbullets}""")
    qcases = "\n".join(qblocks)
    return f"""theorem {name} :
    (({floor.numerator} : ℝ)/{floor.denominator}) ≤ (slowμ (safeSet ({Plist} : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ({Plist} : List ℤ) [{L}]
    (by decide)
    (by
      intro q hq
      fin_cases hq
{qcases})
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([{L}] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = ({total.numerator}/{total.denominator} : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith
"""

def mp_name(S):
    return "mp_s10_" + "_".join(str(p) for p in S)

def do_certs10():
    fams = [list(S) for S in combinations(range(1, 14), 10)]
    thms, mn = [], None
    for S in fams:
        comps = components(S)
        total = sum(b - a for a, b in comps)
        mn = total if mn is None or total < mn else mn
        thms.append(emit_floor_theorem(mp_name(S), S, MP, comps))
    assert mn == MP, (mn, MP)
    body = "\n".join(thms)
    open(LEAN_DIR + "LRCMPCertSize10.lean", "w").write(
        header("LRCMPCertSize10", "the m_P certificate table, |S| = 10 (286 families; min attained = m_P exactly)")
        + body + FOOTER)
    print(f"wrote LRCMPCertSize10.lean: {len(fams)} families, min total = {mn} = m_P")

def do_anchors():
    thms = []
    for m in range(1, 14):
        S = [p for p in range(1, 14) if p != m]
        comps = components(S)
        a, b = max(comps, key=lambda iv: iv[1] - iv[0])
        thms.append(emit_floor_theorem(f"anchor_s12_missing_{m}", S, b - a, [(a, b)]))
        print(f"  anchor missing={m}: [{a},{b}] len {b-a}")
    body = "\n".join(thms)
    open(LEAN_DIR + "LRCAnchor12Certs.lean", "w").write(
        header("LRCAnchor12Certs", "positivity anchors for the 13 twelve-element families (hk12 dispatch)")
        + body + FOOTER)
    print("wrote LRCAnchor12Certs.lean: 13 anchors")

def complete10(T):
    """Canonical size-10 superset: add smallest unused values of {1..13}."""
    Tset = set(T)
    extra = [p for p in range(1, 14) if p not in Tset]
    out = sorted(T + extra[:10 - len(T)])
    assert len(out) == 10
    return out

def tree(fixed, level, l, lo, indent):
    pad = " " * indent
    hi = 13 - (l - level)
    lines = [f"{pad}have hu{level} : p{level} ≤ {hi} := by omega",
             f"{pad}interval_cases p{level}"]
    for val in range(lo, hi + 1):
        if level == l:
            T = fixed + [val]
            if l == 10:
                lines.append(f"{pad}· exact {mp_name(T)}")
            else:
                Tp = complete10(T)
                lines.append(f"{pad}· exact le_trans {mp_name(Tp)} (measGP_anti (by decide))")
        else:
            lines.append(f"{pad}· -- p{level} = {val}")
            lines.extend(tree(fixed + [val], level + 1, l, val + 1, indent + 2))
    return lines

def do_trees():
    parts = []
    # anchor_pos_of_missing: 13-way dispatch
    bullets = []
    for m in range(1, 14):
        Fm = [p for p in range(1, 14) if p != m]
        Flist = "[" + ",".join(str(p) for p in Fm) + "]"
        bullets.append(f"""  · have hmem : ∀ p ∈ P, p ∈ ({Flist} : List ℤ) := by
      intro p hp
      have hb := hbounds p hp
      have hne : p ≠ {m} := fun h => hnotin (h ▸ hp)
      simp only [List.mem_cons, List.not_mem_nil, or_false]
      omega
    exact lt_of_lt_of_le (by norm_num) (le_trans anchor_s12_missing_{m} (measGP_anti hmem))""")
    parts.append(f"""/-- **Positivity from a missing element**: any speed list inside `[1,13]` missing some
value `m` contains a twelve-element anchor family, whose anchor interval is positive. -/
theorem anchor_pos_of_missing (P : List ℤ) (hbounds : ∀ p ∈ P, 1 ≤ p ∧ p ≤ 13)
    (m : ℤ) (h1 : 1 ≤ m) (h13 : m ≤ 13) (hnotin : m ∉ P) :
    (0 : ℝ) < (slowμ (safeSet P)).toReal := by
  interval_cases m
{chr(10).join(bullets)}
""")
    # trees for sizes 6..10, split by head
    for l in range(6, 11):
        hi1 = 13 - (l - 1)
        for c in range(1, hi1 + 1):
            vars_ = " ".join(f"p{i}" for i in range(2, l + 1))
            binders = [f"(hb2 : ({c} : ℤ) < p2)"]
            for i in range(2, l):
                binders.append(f"(h{i}{i+1} : p{i} < p{i+1})")
            binders.append(f"(hbtop : p{l} ≤ 13)")
            lst = ", ".join([str(c)] + [f"p{i}" for i in range(2, l + 1)])
            body = "\n".join(tree([c], 2, l, c + 1, 2))
            parts.append(f"""theorem mp_floor_s{l}_head{c} ({vars_} : ℤ) {" ".join(binders)} :
    (({MP.numerator} : ℝ)/{MP.denominator}) ≤ (slowμ (safeSet ([{lst}] : List ℤ))).toReal := by
{body}
""")
        vars_ = " ".join(f"p{i}" for i in range(1, l + 1))
        binders = [f"(hb1 : 1 ≤ p1)"]
        for i in range(1, l):
            binders.append(f"(h{i}{i+1} : p{i} < p{i+1})")
        binders.append(f"(hbtop : p{l} ≤ 13)")
        lst = ", ".join(f"p{i}" for i in range(1, l + 1))
        args = " ".join(f"p{i}" for i in range(2, l + 1))
        hargs = " ".join([f"h{i}{i+1}" for i in range(1, l)] + ["hbtop"])
        leaves = "\n".join(f"  · exact mp_floor_s{l}_head{c} {args} {hargs}"
                           for c in range(1, hi1 + 1))
        parts.append(f"""/-- m_P leaf tree, length {l} (combined over the head element). -/
theorem mp_floor_sorted_len{l} ({vars_} : ℤ) {" ".join(binders)} :
    (({MP.numerator} : ℝ)/{MP.denominator}) ≤ (slowμ (safeSet ([{lst}] : List ℤ))).toReal := by
  have hu1 : p1 ≤ {hi1} := by omega
  interval_cases p1
{leaves}
""")
    body = "\n".join(parts)
    hdr = header("LRCMPLeafTrees", "the m_P dispatch trees (sizes 6..10; completion leaves via measGP_anti) + anchor_pos_of_missing")
    hdr = hdr.replace("import TournamentH7.LRCMomentCitation",
                      "import TournamentH7.LRCMomentCitation\nimport TournamentH7.LRCMPCertSize10\nimport TournamentH7.LRCAnchor12Certs")
    open(LEAN_DIR + "LRCMPLeafTrees.lean", "w").write(hdr + body + FOOTER)
    nleaves = body.count("exact le_trans mp_s10") + body.count("· exact mp_s10")
    print(f"wrote LRCMPLeafTrees.lean: sizes 6..10, {nleaves} table-citing leaves (expect 1716+1716+1287+715+286 = 5720)")

if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "all"
    if mode in ("certs10", "all"):
        do_certs10()
    if mode in ("anchors", "all"):
        do_anchors()
    if mode in ("trees", "all"):
        do_trees()
