#!/usr/bin/env python3
"""
klein-2026-07-02-S112 (HYP-4017) - W=22 band emitter.

Extends the censused window from W=20 (kps-S17, 6084 rows) to W=22 (31471 rows):
enumerate all covering 13-subsets of [1..22] (primitivity automatic below max 26),
find an exact rational kernel-gate witness for each via the breakpoint grid, and
emit LRCWindowData22.lean in kps's WinRow chunked-data format.

Witness grid: the max-min of t |-> min_i ||v_i t|| is attained at a breakpoint of the
lower envelope: a crossing of two runner curves (t = a/(u+v) or a/(v-u)) or a peak of
one curve (t = a/(2u)). All breakpoint denominators are <= 44, so the grid is
exhaustive: if the optimum is >= 1/14 (i.e. the family is lonely at the band radius),
the grid contains a passing witness. Gate mirror is EXACTLY Lean's KernelGate.speedOK:
(den : int) <= 14 * min((s*num) % den, den - (s*num) % den)  [Python % == Int.emod
for positive den].
"""
from itertools import combinations
from math import gcd
import sys, time

W = 22
OUT = "04-computation/lean/TournamentH7/TournamentH7/LRCWindowData22.lean"
CHUNK = 600

def covering(S):
    return all(any(s % q == 0 for s in S) for q in range(2, 15))

def gate_ok(S, a, q):
    # mirror of KernelGate.speedOK for all speeds
    for s in S:
        m = (s * a) % q
        if 14 * min(m, q - m) < q:
            return False
    return True

def find_witness(S):
    # candidate denominators from breakpoints
    qs = set()
    for i, u in enumerate(S):
        qs.add(2 * u)
        for v in S[i+1:]:
            qs.add(u + v)
            qs.add(v - u)
    qs.discard(0)
    best = None
    for q in sorted(qs):
        for a in range(1, q):
            if gcd(a, q) != 1:
                continue
            if gate_ok(S, a, q):
                return (a, q)
    return None

t0 = time.time()
rows = []
fails = []
n_seen = 0
for S in combinations(range(1, W + 1), 13):
    if not covering(S):
        continue
    n_seen += 1
    w = find_witness(S)
    if w is None:
        fails.append(S)
    else:
        rows.append((S, w[0], w[1]))
    if n_seen % 2000 == 0:
        print(f"  {n_seen} covering rows, {len(fails)} fails, {time.time()-t0:.0f}s", flush=True)

print(f"TOTAL: {len(rows)} rows with witnesses, {len(fails)} FAILURES, {time.time()-t0:.0f}s")
if fails:
    print("FAILED ROWS (would disprove LRC14 if the grid is exhaustive!):")
    for S in fails[:20]:
        print("  ", S)
    sys.exit(1)

# emit
chunks = [rows[i:i+CHUNK] for i in range(0, len(rows), CHUNK)]
L = []
L.append("""/-
  TournamentH7.LRCWindowData22 — THE W = 22 BAND (klein-2026-07-02-S112, HYP-4017).
  Single-writer satellite extending kps-S17's W = 20 band: all 31471 covering
  13-subsets of [1..22] with exact rational kernel-gate witnesses (primitivity is
  automatic below max 26: thirteen distinct positive entries with gcd >= 2 need
  max >= 26).  Same WinRow data + one-gate-evaluation pattern; same enumeration-
  completeness reflection; closes the bounded window at W = 22 and shrinks the
  covering-far surface from cut 20 to cut 22.
  Generated by 04-computation/lrc14_window_data_emitter_klein_S112_W22.py.
-/
import TournamentH7.LRCWindowData
import TournamentH7.LRC14CoveringFarSurface

namespace LonelyRunner
namespace WindowData
""")
for ci, ch in enumerate(chunks, 1):
    L.append("set_option maxRecDepth 4096 in")
    L.append(f"def winData22_{ci} : List WinRow :=")
    body = ",\n   ".join(
        "⟨[" + ", ".join(str(x) for x in S) + f"], {a}, {q}⟩" for (S, a, q) in ch)
    L.append("  [" + body + "]")
    L.append("")
L.append("def winData22 : List WinRow :=")
L.append("  " + " ++ ".join(f"winData22_{i}" for i in range(1, len(chunks) + 1)))
L.append("""
/-- Every W = 22 row passes the kernel gate. -/
theorem winData22_ok : winData22.all (fun r => decide (winRowOK r)) = true := by
  native_decide

/-- The W = 22 window range as concrete integers. -/
def windowRange22 : List ℤ :=
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

theorem mem_windowRange22 {x : ℤ} : x ∈ windowRange22 ↔ 1 ≤ x ∧ x ≤ 22 := by
  simp only [windowRange22, List.mem_cons, List.not_mem_nil, or_false]
  omega

/-- The W = 22 window universe: length-13 ascending sublists of [1,…,22]. -/
def windowUniverse22 : List (List ℤ) :=
  windowRange22.sublistsLen 13

/-- **Completeness of the W = 22 band** (one finite check over C(22,13) = 497420
candidates): every covering candidate has a row. -/
theorem winData22_complete :
    windowUniverse22.all
      (fun T => !(decide (coveringL T)) || winData22.any (fun r => decide (r.speeds = T)))
      = true := by
  native_decide

/-- **The W = 22 dispatcher**: every strictly monotone positive covering tuple bounded
by 22 is lonely, from the band data. -/
theorem hdistinct22_from_data :
    ∀ u : Fin 13 → ℤ, (∀ i, 0 < u i) → StrictMono u → (∀ i, u i ≤ 22) →
      LRC14.CoveringFamily u → LRC14.tupleGcd u = 1 → ∃ t : ℝ, Lonely 14 u t := by
  intro u hpos hsm h22 hcov _
  set T : List ℤ := List.ofFn u with hT
  have hTlen : T.length = 13 := by simp [hT]
  have hTpw : T.Pairwise (· < ·) := by
    rw [hT, List.pairwise_ofFn]
    intro i j hij
    exact hsm hij
  have hUpw : windowRange22.Pairwise (· < ·) := by decide
  have hTsub : ∀ x ∈ T, x ∈ windowRange22 := by
    intro x hx
    rw [hT, List.mem_ofFn] at hx
    obtain ⟨i, rfl⟩ := hx
    have h1 := hpos i
    have h2 := h22 i
    rw [mem_windowRange22]
    omega
  have hTsl : T.Sublist windowRange22 :=
    sorted_subset_sublist _ T hTpw hUpw hTsub
  have hTuniv : T ∈ windowUniverse22 := by
    unfold windowUniverse22
    rw [List.mem_sublistsLen]
    exact ⟨hTsl, hTlen⟩
  have hTcov : coveringL T := by
    intro q hq2 hq14
    obtain ⟨i, hdvd⟩ := hcov q hq2 hq14
    exact ⟨u i, by rw [hT]; exact List.mem_ofFn.mpr ⟨i, rfl⟩, hdvd⟩
  have hall := List.all_eq_true.mp winData22_complete T hTuniv
  rw [Bool.or_eq_true, Bool.not_eq_true', decide_eq_false_iff_not] at hall
  rcases hall with hnc | hany
  · exact absurd hTcov hnc
  · rw [List.any_eq_true] at hany
    obtain ⟨r, hrmem, hrT⟩ := hany
    have hrT' : r.speeds = T := of_decide_eq_true hrT
    have hrOK : winRowOK r := by
      have := List.all_eq_true.mp winData22_ok r hrmem
      exact of_decide_eq_true this
    refine ⟨_, winRow_lonely r hrOK u ?_⟩
    intro i
    rw [hrT', hT]
    have hlt : (i : ℕ) < (List.ofFn u).length := by simp
    rw [List.getD_eq_getElem (List.ofFn u) 0 hlt]
    fin_cases i <;> rfl

/-- The W-generic normalized-window closure (the HWindow20 argument with the cut
as a parameter): distinct census + citation node ⟹ the full bounded window. -/
theorem hwindowW_closed (W : ℤ) (cite : LRCUpTo13)
    (hdistinct : ∀ u : Fin 13 → ℤ, (∀ i, 0 < u i) → StrictMono u →
      (∀ i, u i ≤ W) → LRC14.CoveringFamily u → LRC14.tupleGcd u = 1 →
      ∃ t : ℝ, Lonely 14 u t) :
    ∀ v : Fin 13 → ℤ, (∀ i, v i ≠ 0) → (∀ i, |v i| ≤ W) → ∃ t : ℝ, Lonely 14 v t := by
  apply LRC14.hwindow_of_normalized_census W
  intro u hpos hmono hle hcov hprim
  by_cases hrep : ∃ i j : Fin 13, i ≠ j ∧ u i = u j
  · obtain ⟨i, j, hij, hval⟩ := hrep
    exact lonely14_of_repeat cite u (fun k => (hpos k).ne') hij hval
  · push Not at hrep
    have hsm : StrictMono u := by
      intro a b hab
      rcases lt_or_eq_of_le (hmono (le_of_lt hab)) with h | h
      · exact h
      · exact absurd h (hrep a b (ne_of_lt hab))
    exact hdistinct u hpos hsm hle hcov hprim

/-- **The bounded window at W = 22, fully discharged.** -/
theorem hwindow22_closed (cite : LRCUpTo13) :
    ∀ v : Fin 13 → ℤ, (∀ i, v i ≠ 0) → (∀ i, |v i| ≤ 22) → ∃ t : ℝ, Lonely 14 v t :=
  hwindowW_closed 22 cite hdistinct22_from_data

/-- **LRC(14) from the citation node + the covering-far surface at W = 22** — the
leanest endgame in the corpus: the 25387 covering families with max ∈ (20, 22] move
from hypothesis to machine-checked. -/
theorem lrc14_of_covering_far_22 (cite : LRCUpTo13)
    (hcovfar : LRC14.CoveringFarLonely 22) : LRC14.LRC14Statement :=
  LRC14.lrc14_of_covering_far_of_window 22 (hwindow22_closed cite) hcovfar

end WindowData
end LonelyRunner
""")
with open(OUT, "w") as f:
    f.write("\n".join(L))
print(f"emitted {OUT}: {len(chunks)} chunks, {len(rows)} rows")
