#!/usr/bin/env python3
"""Exact depth-four scalar hinge/Gram audit on the 13-adic carrier.

This is a neutral computation artifact, not a theorem dependency.  It audits
the scalar blocker profiles (3,3,4), (2,3,4), and (2,2,4) at N=13^5.

The signed primitive unit group

    G = (Z/NZ)^*/{+/-1}

is cyclic of order 6*13^4, generated by 2.  If ``c`` is the guard row and
``d`` is the unit-danger row in exponent coordinates, every singleton
capacity is the exact cyclic correlation

    C(j) = 2 * sum_e c(e) safe(e) d(e+j).

The correlations are computed over the finite field F_5767169 by a
length-2^19 number-theoretic transform.  The linear coefficients are at
most |G|=171366<5767169, so their canonical residues are the exact integer
coefficients.  There is no floating-point arithmetic or rounding.

For singleton rows X,Y and theta=33150, the certificate uses

    Top_5(min(X,Y))
      <= 5 theta + sum_q ceil(sqrt((X_q-theta)_+(Y_q-theta)_+)).

All square roots are integer square roots.  The three complete pair
universes include diagonal shallow-mask classes.  Direct strict-residue
controls independently replay the named hostile rows.

No Python ``assert`` is load bearing, so all checks remain active under
``python -O``.
"""

from __future__ import annotations

import hashlib
import struct

import numpy as np
from numba import get_num_threads, njit, prange, set_num_threads


P = 13
N = P**5
SIGNED_ORDER = 6 * P**4
GENERATOR = 2

THETA = 33150
TERMINAL_COUNT = 5

# 5767169 = 11*2^19+1 is prime and 3 is a primitive root.
NTT_LENGTH = 1 << 19
NTT_MODULUS = 5767169
NTT_ROOT = 3
NTT_BITS = 19
NTT_INVERSE_LENGTH = pow(NTT_LENGTH, NTT_MODULUS - 2, NTT_MODULUS)


def require(condition, message):
    """Raise on an exact audit failure, including under ``python -O``."""
    if not condition:
        raise RuntimeError(message)


def is_prime_trial(n):
    """Small deterministic primality check for the fixed NTT modulus."""
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    divisor = 3
    while divisor * divisor <= n:
        if n % divisor == 0:
            return False
        divisor += 2
    return True


def norm_numerators(values, modulus):
    """Return modulus times the circle norm of integer numerators."""
    residues = values % modulus
    return np.minimum(residues, modulus - residues)


def canonical_sign_label(value, modulus):
    """Least positive representative modulo sign."""
    residue = int(value) % modulus
    return min(residue, modulus - residue)


def build_bit_reversal():
    """Bit-reversal permutation for the fixed radix-two NTT length."""
    reversal = np.empty(NTT_LENGTH, dtype=np.int64)
    for value in range(NTT_LENGTH):
        source = value
        target = 0
        for _ in range(NTT_BITS):
            target = (target << 1) | (source & 1)
            source >>= 1
        reversal[value] = target
    return reversal


@njit
def ntt_from_natural_order(source, target, reversal, stage_roots, inverse):
    """Exact radix-two NTT from natural input to natural output order."""
    size = reversal.size
    for index in range(size):
        target[index] = source[reversal[index]]

    length = 2
    stage = 0
    while length <= size:
        half = length // 2
        root_step = stage_roots[stage]
        for block in range(0, size, length):
            root_power = 1
            for offset in range(half):
                left = target[block + offset]
                right = (
                    target[block + offset + half] * root_power
                ) % NTT_MODULUS

                total = left + right
                if total >= NTT_MODULUS:
                    total -= NTT_MODULUS
                difference = left - right
                if difference < 0:
                    difference += NTT_MODULUS

                target[block + offset] = total
                target[block + offset + half] = difference
                root_power = (root_power * root_step) % NTT_MODULUS
        stage += 1
        length *= 2

    if inverse:
        for index in range(size):
            target[index] = (
                target[index] * NTT_INVERSE_LENGTH
            ) % NTT_MODULUS


@njit(parallel=True)
def exact_cyclic_correlations(
    rows,
    danger_transform,
    reversal,
    forward_roots,
    inverse_roots,
):
    """Return exact signed cyclic correlations with the fixed danger row."""
    batch_size = rows.shape[0]
    answers = np.empty((batch_size, SIGNED_ORDER), dtype=np.int32)

    for row_index in prange(batch_size):
        padded = np.zeros(NTT_LENGTH, dtype=np.int64)
        transformed = np.empty(NTT_LENGTH, dtype=np.int64)

        # a[k]=row[-k] turns convolution with d into
        # sum_e row[e] d[e+j].
        padded[0] = rows[row_index, 0]
        for exponent in range(1, SIGNED_ORDER):
            padded[exponent] = rows[
                row_index, SIGNED_ORDER - exponent
            ]

        ntt_from_natural_order(
            padded, transformed, reversal, forward_roots, False
        )
        for index in range(NTT_LENGTH):
            transformed[index] = (
                transformed[index] * danger_transform[index]
            ) % NTT_MODULUS
        ntt_from_natural_order(
            transformed, padded, reversal, inverse_roots, True
        )

        # Fold the exact linear convolution modulo x^M-1.
        for shift in range(SIGNED_ORDER):
            coefficient = padded[shift]
            if shift + SIGNED_ORDER < NTT_LENGTH:
                coefficient += padded[shift + SIGNED_ORDER]
            answers[row_index, shift] = coefficient

    return answers


@njit
def integer_square_root(value):
    """Floor square root by the restoring binary algorithm."""
    remainder = value
    result = 0
    bit = 1 << 62
    while bit > remainder:
        bit >>= 2
    while bit != 0:
        if remainder >= result + bit:
            remainder -= result + bit
            result = (result >> 1) + bit
        else:
            result >>= 1
        bit >>= 2
    return result


@njit
def ceiling_square_root(value):
    """Exact integer ceiling of a square root."""
    if value == 0:
        return 0
    root = integer_square_root(value)
    if root * root < value:
        root += 1
    return root


@njit
def tail_intersection_value(
    left_indptr,
    left_indices,
    left_values,
    left_row,
    right_indptr,
    right_indices,
    right_values,
    right_row,
):
    """Integer-ceiling Hellinger tail intersection for two sparse rows."""
    left_position = left_indptr[left_row]
    left_end = left_indptr[left_row + 1]
    right_position = right_indptr[right_row]
    right_end = right_indptr[right_row + 1]
    total = 0

    while left_position < left_end and right_position < right_end:
        left_index = left_indices[left_position]
        right_index = right_indices[right_position]
        if left_index < right_index:
            left_position += 1
        elif right_index < left_index:
            right_position += 1
        else:
            product = (
                left_values[left_position]
                * right_values[right_position]
            )
            total += ceiling_square_root(product)
            left_position += 1
            right_position += 1
    return total


@njit(parallel=True)
def tail_intersection_matrix(
    left_indptr,
    left_indices,
    left_values,
    right_indptr,
    right_indices,
    right_values,
):
    """All exact integer-ceiling Hellinger intersections."""
    left_rows = left_indptr.size - 1
    right_rows = right_indptr.size - 1
    answer = np.empty((left_rows, right_rows), dtype=np.int64)
    for left_row in prange(left_rows):
        for right_row in range(right_rows):
            answer[left_row, right_row] = tail_intersection_value(
                left_indptr,
                left_indices,
                left_values,
                left_row,
                right_indptr,
                right_indices,
                right_values,
                right_row,
            )
    return answer


def build_signed_group():
    """Exponent representatives and the two strict base predicates."""
    representatives = np.empty(SIGNED_ORDER, dtype=np.int64)
    representatives[0] = 1
    for exponent in range(1, SIGNED_ORDER):
        representatives[exponent] = (
            representatives[exponent - 1] * GENERATOR
        ) % N

    require(
        pow(GENERATOR, SIGNED_ORDER, N) == N - 1,
        "2 did not have the required signed order",
    )
    require(
        len(np.unique(representatives)) == SIGNED_ORDER,
        "signed exponent representatives collided",
    )

    norms = norm_numerators(representatives, N)
    guard = 7 * norms > N
    danger = 14 * norms < N
    labels = np.minimum(representatives, N - representatives)

    require(2 * int(guard.sum()) == 244810, "bad guard universe")
    require(N % 7 != 0 and N % 14 != 0, "torsion endpoint risk")
    return representatives, labels, guard, danger


def build_ntt_data(danger):
    """Exact transform of the fixed terminal-danger row."""
    require(NTT_LENGTH >= 2 * SIGNED_ORDER - 1, "NTT padding too short")
    require(
        NTT_MODULUS == 11 * NTT_LENGTH + 1,
        "unexpected NTT modulus factorization",
    )
    require(is_prime_trial(NTT_MODULUS), "NTT modulus is not prime")
    require(
        pow(NTT_ROOT, (NTT_MODULUS - 1) // 2, NTT_MODULUS) != 1
        and pow(
            NTT_ROOT, (NTT_MODULUS - 1) // 11, NTT_MODULUS
        )
        != 1,
        "fixed NTT root is not primitive",
    )
    require(
        SIGNED_ORDER < NTT_MODULUS,
        "one modulus no longer determines correlation coefficients",
    )

    reversal = build_bit_reversal()
    forward_roots = np.asarray(
        [
            pow(
                NTT_ROOT,
                (NTT_MODULUS - 1) // (1 << stage),
                NTT_MODULUS,
            )
            for stage in range(1, NTT_BITS + 1)
        ],
        dtype=np.int64,
    )
    inverse_roots = np.asarray(
        [
            pow(int(root), NTT_MODULUS - 2, NTT_MODULUS)
            for root in forward_roots
        ],
        dtype=np.int64,
    )

    padded = np.zeros(NTT_LENGTH, dtype=np.int64)
    padded[:SIGNED_ORDER] = danger.astype(np.int64)
    danger_transform = np.empty(NTT_LENGTH, dtype=np.int64)
    ntt_from_natural_order(
        padded,
        danger_transform,
        reversal,
        forward_roots,
        False,
    )
    return reversal, forward_roots, inverse_roots, danger_transform


def blocker_carrier(depth):
    """Canonical shallow labels and their periodic exact safe masks."""
    reduced_power = 5 - depth
    modulus = P**reduced_power
    period = 6 * P ** (reduced_power - 1)

    residues = np.empty(period, dtype=np.int64)
    residues[0] = 1
    for exponent in range(1, period):
        residues[exponent] = (
            residues[exponent - 1] * GENERATOR
        ) % modulus
    require(
        pow(GENERATOR, period, modulus) == modulus - 1,
        "bad reduced signed order",
    )

    exponent_by_label = {
        canonical_sign_label(residue, modulus): exponent
        for exponent, residue in enumerate(residues)
    }
    require(
        len(exponent_by_label) == period,
        "reduced sign labels collided",
    )
    labels = tuple(sorted(exponent_by_label))
    base_danger = (
        14 * norm_numerators(residues, modulus) < modulus
    )
    base_exponents = np.arange(period, dtype=np.int64)
    safe = np.asarray(
        [
            ~base_danger[
                (base_exponents + exponent_by_label[label]) % period
            ]
            for label in labels
        ],
        dtype=np.bool_,
    )
    return labels, period, safe


def exact_guard_weights(guard, period):
    """Guard counts on exponent classes, using integer arithmetic only."""
    require(
        SIGNED_ORDER % period == 0,
        "blocker period did not divide the signed group order",
    )
    return guard.reshape(-1, period).sum(axis=0, dtype=np.int64)


def csr_from_tail_lists(index_lists, value_lists):
    """Pack sorted sparse tail rows into deterministic CSR arrays."""
    indptr = [0]
    flat_indices = []
    flat_values = []
    for indices, values in zip(index_lists, value_lists):
        flat_indices.extend(map(int, indices))
        flat_values.extend(map(int, values))
        indptr.append(len(flat_indices))
    return (
        np.asarray(indptr, dtype=np.int64),
        np.asarray(flat_indices, dtype=np.int64),
        np.asarray(flat_values, dtype=np.int64),
    )


def singleton_rows(
    depth,
    labels,
    period,
    safe,
    guard,
    ntt_data,
):
    """Compute exact singleton rows, Ky--Fan sums, and sparse theta tails."""
    reversal, forward_roots, inverse_roots, danger_transform = ntt_data
    exponent_classes = np.arange(SIGNED_ORDER, dtype=np.int64) % period
    top_five_sums = np.empty(len(labels), dtype=np.int64)
    tail_indices = []
    tail_values = []
    table_digest = hashlib.sha256()

    batch_size = 26
    for start in range(0, len(labels), batch_size):
        stop = min(start + batch_size, len(labels))
        rows = np.asarray(
            [
                guard & safe[index, exponent_classes]
                for index in range(start, stop)
            ],
            dtype=np.bool_,
        )
        sign_capacities = exact_cyclic_correlations(
            rows,
            danger_transform,
            reversal,
            forward_roots,
            inverse_roots,
        )
        capacities = sign_capacities * 2

        for local_index, row in enumerate(capacities):
            owner_index = start + local_index
            largest = np.partition(row, -TERMINAL_COUNT)[
                -TERMINAL_COUNT:
            ]
            top_five_sums[owner_index] = int(largest.sum())
            active = np.flatnonzero(row > THETA)
            tail_indices.append(active.astype(np.int64))
            tail_values.append(
                (row[active].astype(np.int64) - THETA)
            )

            table_digest.update(
                struct.pack("<q", int(labels[owner_index]))
            )
            table_digest.update(
                row.astype("<i4", copy=False).tobytes(order="C")
            )

            require(
                int(row.max()) < NTT_MODULUS,
                "capacity could have wrapped modulo the NTT prime",
            )

    csr = csr_from_tail_lists(tail_indices, tail_values)
    return top_five_sums, csr, table_digest.hexdigest()


def residual_matrices(
    guard,
    safe_depth_two,
    safe_depth_three,
):
    """Exact W tables for 334, 234, and 224."""
    weight_three = exact_guard_weights(guard, safe_depth_three.shape[1])
    weighted_three = (
        safe_depth_three.astype(np.int64)
        * weight_three[None, :]
    )
    residual_334 = (
        2
        * (
            weighted_three
            @ safe_depth_three.astype(np.int64).T
        )
    )

    period_two = safe_depth_two.shape[1]
    period_three = safe_depth_three.shape[1]
    weight_two = exact_guard_weights(guard, period_two)
    lifted_three = safe_depth_three[
        :, np.arange(period_two, dtype=np.int64) % period_three
    ]
    weighted_two = (
        safe_depth_two.astype(np.int64) * weight_two[None, :]
    )
    residual_234 = (
        2 * (weighted_two @ lifted_three.astype(np.int64).T)
    )
    residual_224 = (
        2
        * (
            weighted_two
            @ safe_depth_two.astype(np.int64).T
        )
    )
    return residual_334, residual_234, residual_224


def audit_pair_table(
    name,
    left_labels,
    right_labels,
    residual,
    hellinger,
    symmetric,
):
    """Check every pair and freeze a stable binary table digest."""
    digest = hashlib.sha256()
    minimum_margin = None
    minimum_record = None
    minimizers = 0
    pair_count = 0

    for left_index, left_label in enumerate(left_labels):
        first_right = left_index if symmetric else 0
        for right_index in range(first_right, len(right_labels)):
            right_label = right_labels[right_index]
            weight = int(residual[left_index, right_index])
            tail = int(hellinger[left_index, right_index])
            bound = TERMINAL_COUNT * THETA + tail
            margin = weight - bound
            require(margin > 0, f"{name} had a nonpositive margin")
            pair_count += 1

            digest.update(
                struct.pack(
                    "<6q",
                    int(left_label),
                    int(right_label),
                    weight,
                    tail,
                    bound,
                    margin,
                )
            )
            record = (
                int(left_label),
                int(right_label),
                weight,
                tail,
                bound,
            )
            if minimum_margin is None or margin < minimum_margin:
                minimum_margin = margin
                minimum_record = record
                minimizers = 1
            elif margin == minimum_margin:
                minimizers += 1

    expected_pairs = (
        len(left_labels) * (len(left_labels) + 1) // 2
        if symmetric
        else len(left_labels) * len(right_labels)
    )
    require(pair_count == expected_pairs, f"{name} pair count changed")
    return (
        pair_count,
        minimum_margin,
        minimum_record,
        minimizers,
        digest.hexdigest(),
    )


def audit_one_owner_bound(
    name,
    left_labels,
    right_labels,
    residual,
    left_ky_fan,
    right_ky_fan,
    symmetric,
):
    """Audit W-Top5(singleton meet) via the simpler one-owner Ky--Fan cap."""
    minimum = None
    minimizers = 0
    record = None
    for left_index, left_label in enumerate(left_labels):
        first_right = left_index if symmetric else 0
        for right_index in range(first_right, len(right_labels)):
            bound = min(
                int(left_ky_fan[left_index]),
                int(right_ky_fan[right_index]),
            )
            margin = int(residual[left_index, right_index]) - bound
            require(margin > 0, f"{name} one-owner bound failed")
            candidate = (
                int(left_label),
                int(right_labels[right_index]),
                int(residual[left_index, right_index]),
                bound,
            )
            if minimum is None or margin < minimum:
                minimum = margin
                minimizers = 1
                record = candidate
            elif margin == minimum:
                minimizers += 1
    return minimum, record, minimizers


def direct_singleton_capacity(
    representatives,
    guard,
    depth,
    blocker_label,
    terminal_label,
):
    """Definition-level exact singleton capacity on signed residues."""
    labels, period, safe = blocker_carrier(depth)
    blocker_index = labels.index(blocker_label)
    exponents = np.arange(SIGNED_ORDER, dtype=np.int64)
    residual = guard & safe[blocker_index, exponents % period]
    products = (int(terminal_label) * representatives) % N
    dangerous = 14 * norm_numerators(products, N) < N
    return 2 * int(np.sum(residual & dangerous))


def direct_pair_control(
    name,
    representatives,
    terminal_labels,
    guard,
    left_depth,
    left_label,
    right_depth,
    right_label,
    expected_residual,
    expected_top_five,
    expected_margin,
    ntt_data,
):
    """Exact NTT row plus independent direct counts for every named winner."""
    left_labels, left_period, left_safe = blocker_carrier(left_depth)
    right_labels, right_period, right_safe = blocker_carrier(right_depth)
    left_index = left_labels.index(left_label)
    right_index = right_labels.index(right_label)
    exponents = np.arange(SIGNED_ORDER, dtype=np.int64)
    residual = (
        guard
        & left_safe[left_index, exponents % left_period]
        & right_safe[right_index, exponents % right_period]
    )
    residual_size = 2 * int(residual.sum())
    require(residual_size == expected_residual, f"{name} residual changed")

    reversal, forward_roots, inverse_roots, danger_transform = ntt_data
    sign_capacities = exact_cyclic_correlations(
        residual[None, :],
        danger_transform,
        reversal,
        forward_roots,
        inverse_roots,
    )[0]
    capacities = sign_capacities * 2
    candidate_indices = np.argpartition(
        capacities, -TERMINAL_COUNT
    )[-TERMINAL_COUNT:]
    candidate_indices = candidate_indices[
        np.lexsort(
            (
                terminal_labels[candidate_indices],
                -capacities[candidate_indices],
            )
        )
    ]
    top_five = tuple(
        (
            int(capacities[index]),
            int(terminal_labels[index]),
        )
        for index in candidate_indices
    )
    require(top_five == expected_top_five, f"{name} top five changed")
    margin = residual_size - sum(capacity for capacity, _ in top_five)
    require(margin == expected_margin, f"{name} margin changed")

    for capacity, terminal_label in top_five:
        products = (terminal_label * representatives) % N
        dangerous = 14 * norm_numerators(products, N) < N
        direct = 2 * int(np.sum(residual & dangerous))
        require(
            direct == capacity,
            f"{name} direct terminal capacity changed",
        )
    return residual, capacities, top_five


def exact_family_energy_bound(capacities):
    """Five-label knapsack bound from exact 13-lift sums and energies."""
    base_order = 6 * P**3
    require(
        capacities.size == 13 * base_order,
        "bad thirteen-lift family shape",
    )
    families = capacities.reshape(13, base_order)
    sums = families.sum(axis=0, dtype=np.int64)
    sum_squares = (
        families.astype(np.int64) ** 2
    ).sum(axis=0, dtype=np.int64)
    # T=13E=13*sum c_l^2-S^2.
    energy_numerators = 13 * sum_squares - sums * sums
    require(
        np.all(energy_numerators >= 0),
        "negative lift-family energy",
    )

    options = np.zeros((base_order, TERMINAL_COUNT + 1), dtype=np.int64)
    for family in range(base_order):
        for chosen in range(1, TERMINAL_COUNT + 1):
            radicand = (
                chosen
                * (13 - chosen)
                * int(energy_numerators[family])
            )
            radical = ceiling_square_root(radicand)
            upper = (
                chosen * int(sums[family]) + radical + 12
            ) // 13
            options[family, chosen] = min(
                int(sums[family]), upper
            )

    negative = -10**18
    dynamic = [0] + [negative] * TERMINAL_COUNT
    for family in range(base_order):
        updated = dynamic.copy()
        for already in range(TERMINAL_COUNT + 1):
            if dynamic[already] == negative:
                continue
            for chosen in range(1, TERMINAL_COUNT - already + 1):
                candidate = (
                    dynamic[already] + int(options[family, chosen])
                )
                if candidate > updated[already + chosen]:
                    updated[already + chosen] = candidate
        dynamic = updated

    # Maximize T/(13S^2) exactly by cross multiplication.
    maximum_family = None
    maximum_numerator = None
    maximum_denominator = None
    for family in range(base_order):
        denominator = 13 * int(sums[family]) ** 2
        numerator = int(energy_numerators[family])
        if denominator == 0:
            continue
        if (
            maximum_family is None
            or numerator * maximum_denominator
            > maximum_numerator * denominator
        ):
            maximum_family = family
            maximum_numerator = numerator
            maximum_denominator = denominator
    return (
        int(dynamic[TERMINAL_COUNT]),
        int(maximum_family),
        int(maximum_numerator),
        int(maximum_denominator),
    )


def direct_tail_control(
    name,
    representatives,
    guard,
    left_depth,
    left_label,
    right_depth,
    right_label,
    left_csr,
    right_csr,
    left_labels,
    right_labels,
    expected_tail,
):
    """Directly replay every singleton entry contributing to a min Gram row."""
    left_index = left_labels.index(left_label)
    right_index = right_labels.index(right_label)
    (
        left_indptr,
        left_indices,
        left_values,
    ) = left_csr
    (
        right_indptr,
        right_indices,
        right_values,
    ) = right_csr

    left_position = int(left_indptr[left_index])
    left_end = int(left_indptr[left_index + 1])
    right_position = int(right_indptr[right_index])
    right_end = int(right_indptr[right_index + 1])
    total = 0
    intersection_count = 0

    while left_position < left_end and right_position < right_end:
        left_terminal = int(left_indices[left_position])
        right_terminal = int(right_indices[right_position])
        if left_terminal < right_terminal:
            left_position += 1
        elif right_terminal < left_terminal:
            right_position += 1
        else:
            terminal_label = canonical_sign_label(
                representatives[left_terminal], N
            )
            direct_left = direct_singleton_capacity(
                representatives,
                guard,
                left_depth,
                left_label,
                terminal_label,
            )
            direct_right = direct_singleton_capacity(
                representatives,
                guard,
                right_depth,
                right_label,
                terminal_label,
            )
            left_excess = int(left_values[left_position])
            right_excess = int(right_values[right_position])
            require(
                direct_left - THETA == left_excess,
                f"{name} left tail direct replay failed",
            )
            require(
                direct_right - THETA == right_excess,
                f"{name} right tail direct replay failed",
            )
            total += ceiling_square_root(left_excess * right_excess)
            intersection_count += 1
            left_position += 1
            right_position += 1

    require(total == expected_tail, f"{name} direct tail changed")
    return intersection_count


def run():
    require(
        SIGNED_ORDER == 171366 and N == 371293,
        "fixed carrier constants changed",
    )
    representatives, terminal_labels, guard, danger = build_signed_group()
    ntt_data = build_ntt_data(danger)

    # Keep parallel results deterministic: each output coefficient is owned
    # by exactly one worker and contains only modular integer arithmetic.
    set_num_threads(min(12, get_num_threads()))

    depth_two_labels, period_two, safe_two = blocker_carrier(2)
    depth_three_labels, period_three, safe_three = blocker_carrier(3)
    require(
        len(depth_two_labels) == period_two == 1014,
        "bad depth-two shallow universe",
    )
    require(
        len(depth_three_labels) == period_three == 78,
        "bad depth-three shallow universe",
    )

    ky_fan_three, csr_three, digest_three = singleton_rows(
        3,
        depth_three_labels,
        period_three,
        safe_three,
        guard,
        ntt_data,
    )
    ky_fan_two, csr_two, digest_two = singleton_rows(
        2,
        depth_two_labels,
        period_two,
        safe_two,
        guard,
        ntt_data,
    )
    require(
        len(csr_three[1]) == 711
        and digest_three
        == "9b37be73cfe5646dbf0595c6668ab5ff63a85784be1caacac1f39194bfcdb3d9",
        "depth-three singleton table changed",
    )
    require(
        len(csr_two[1]) == 16216
        and digest_two
        == "3e655cc2563ad2ae6b1f3e412f8a299c1b37bb05690d6cdcdb1a011dd686077a",
        "depth-two singleton table changed",
    )

    residual_334, residual_234, residual_224 = residual_matrices(
        guard, safe_two, safe_three
    )
    hellinger_334 = tail_intersection_matrix(
        *csr_three, *csr_three
    )
    hellinger_234 = tail_intersection_matrix(
        *csr_two, *csr_three
    )
    hellinger_224 = tail_intersection_matrix(
        *csr_two, *csr_two
    )

    audit_334 = audit_pair_table(
        "depth-(3,3,4)",
        depth_three_labels,
        depth_three_labels,
        residual_334,
        hellinger_334,
        True,
    )
    audit_234 = audit_pair_table(
        "depth-(2,3,4)",
        depth_two_labels,
        depth_three_labels,
        residual_234,
        hellinger_234,
        False,
    )
    audit_224 = audit_pair_table(
        "depth-(2,2,4)",
        depth_two_labels,
        depth_two_labels,
        residual_224,
        hellinger_224,
        True,
    )

    require(
        audit_334[:4]
        == (3081, 3347, (1, 14, 172610, 3513, 169263), 1),
        "depth-(3,3,4) minimum changed",
    )
    require(
        audit_234[:4]
        == (79092, 5277, (466, 41, 175278, 4251, 170001), 1),
        "depth-(2,3,4) minimum changed",
    )
    require(
        audit_224[:4]
        == (514605, 4876, (550, 719, 177938, 7312, 173062), 1),
        "depth-(2,2,4) minimum changed",
    )
    require(
        audit_334[4]
        == "45a92892c1fe6c939f8ffc30dcf91223bfcecf14325a6491520d5cffb25a8431",
        "depth-(3,3,4) pair digest changed",
    )
    require(
        audit_234[4]
        == "4b1c0599c4fbd69b0cb4b1e4227630956980480fc8fb3e352b9bbe1b0b43f942",
        "depth-(2,3,4) pair digest changed",
    )
    require(
        audit_224[4]
        == "2de536ab4586b9ede50ecbdac26fd2eef3d88a38fcb84c1ba3bf98ef715bda54",
        "depth-(2,2,4) pair digest changed",
    )

    one_owner_234 = audit_one_owner_bound(
        "depth-(2,3,4)",
        depth_two_labels,
        depth_three_labels,
        residual_234,
        ky_fan_two,
        ky_fan_three,
        False,
    )
    one_owner_224 = audit_one_owner_bound(
        "depth-(2,2,4)",
        depth_two_labels,
        depth_two_labels,
        residual_224,
        ky_fan_two,
        ky_fan_two,
        True,
    )
    require(
        one_owner_234
        == (2170, (170, 1, 175248, 173078), 10),
        "depth-(2,3,4) one-owner minimum changed",
    )
    require(
        one_owner_224
        == (3530, (508, 1015, 177888, 174358), 1),
        "depth-(2,2,4) one-owner minimum changed",
    )

    residual_hostile_334, capacities_hostile_334, top_334 = (
        direct_pair_control(
            "depth-(3,3,4) hostile",
            representatives,
            terminal_labels,
            guard,
            3,
            1,
            3,
            84,
            188290,
            (
                (33928, 2198),
                (33918, 2196),
                (32518, 1098),
                (32496, 1099),
                (31408, 6),
            ),
            24022,
            ntt_data,
        )
    )
    residual_hostile_234, capacities_hostile_234, top_234 = (
        direct_pair_control(
            "depth-(2,3,4) hostile",
            representatives,
            terminal_labels,
            guard,
            2,
            844,
            3,
            1,
            175248,
            (
                (29664, 142637),
                (29646, 2198),
                (29646, 142635),
                (29628, 2196),
                (29224, 6),
            ),
            27440,
            ntt_data,
        )
    )
    residual_hostile_224, _, top_224 = direct_pair_control(
        "depth-(2,2,4) one-owner minimizer",
        representatives,
        terminal_labels,
        guard,
        2,
        508,
        2,
        1015,
        177888,
        (
            (29662, 171534),
            (29648, 30941),
            (29644, 6),
            (29620, 85853),
            (29612, 171536),
        ),
        29702,
        ntt_data,
    )

    direct_tail_counts = (
        direct_tail_control(
            "depth-(3,3,4) min Gram row",
            representatives,
            guard,
            3,
            1,
            3,
            14,
            csr_three,
            csr_three,
            depth_three_labels,
            depth_three_labels,
            3513,
        ),
        direct_tail_control(
            "depth-(2,3,4) min Gram row",
            representatives,
            guard,
            2,
            466,
            3,
            41,
            csr_two,
            csr_three,
            depth_two_labels,
            depth_three_labels,
            4251,
        ),
        direct_tail_control(
            "depth-(2,2,4) min Gram row",
            representatives,
            guard,
            2,
            550,
            2,
            719,
            csr_two,
            csr_two,
            depth_two_labels,
            depth_two_labels,
            7312,
        ),
    )

    # The deepest depth-four blocker is safe at every primitive residue.
    for unit_part in range(1, 7):
        products = (P**4 * unit_part * representatives) % N
        require(
            not np.any(14 * norm_numerators(products, N) < N),
            "depth-four blocker was dangerous at a primitive residue",
        )

    energy_334 = exact_family_energy_bound(capacities_hostile_334)
    energy_234 = exact_family_energy_bound(capacities_hostile_234)
    require(
        direct_tail_counts == (3, 4, 8),
        "direct minimum-tail control counts changed",
    )
    require(
        energy_334
        == (220540, 0, 10079244328, 1572362069200),
        "depth-(3,3,4) family-energy control changed",
    )
    require(
        energy_234
        == (205311, 0, 8741366936, 1363643623888),
        "depth-(2,3,4) family-energy control changed",
    )

    print("EXACT DEPTH-FOUR HINGE/GRAM CORRELATION AUDIT")
    print("carrier N / signed order / generator =",
          (N, SIGNED_ORDER, GENERATOR))
    print("guard universe / theta / terminal count =",
          (2 * int(guard.sum()), THETA, TERMINAL_COUNT))
    print("NTT modulus / length / primitive root =",
          (NTT_MODULUS, NTT_LENGTH, NTT_ROOT))
    print("arithmetic = exact finite-field/integer; floating point = none")
    print("singleton depth-3 rows / tail entries / digest =",
          (len(depth_three_labels), len(csr_three[1]), digest_three))
    print("singleton depth-2 rows / tail entries / digest =",
          (len(depth_two_labels), len(csr_two[1]), digest_two))
    print("334 pair audit =", audit_334)
    print("234 pair audit =", audit_234)
    print("224 pair audit =", audit_224)
    print("234 one-owner audit =", one_owner_234)
    print("224 one-owner audit =", one_owner_224)
    print("334 hostile top five =", top_334)
    print("234 hostile top five =", top_234)
    print("224 one-owner-minimizer top five =", top_224,
          "residual =", 2 * int(residual_hostile_224.sum()))
    print("direct min-row tail intersection counts =", direct_tail_counts)
    print("334 hostile family-energy audit =", energy_334,
          "residual =", 2 * int(residual_hostile_334.sum()))
    print("234 hostile family-energy audit =", energy_234,
          "residual =", 2 * int(residual_hostile_234.sum()))
    print("pair digest schema = little-endian <6q:"
          " left,right,W,H,5theta+H,margin")
    print("singleton digest schema = <q owner label"
          " then exponent-ordered <i4 capacities")
    print("VERDICT = all 334, 234, and 224 pair margins are positive")


if __name__ == "__main__":
    run()
