#!/usr/bin/env python3
"""
lrc14_dispatcher_codegen_macmini_S65cont23.py -- the hB dispatcher LEAF TREES.

Emits LRCSafeCertLeafTrees.lean: for each length l = 1..5 a lemma
    safe_floor_sorted_len<l> (p1 ... pl) (1 <= p1 < p2 < ... < pl <= 13) :
        capConst(l) <= (slowmu (safeSet [p1,...,pl])).toReal
proved by explicit nested interval_cases trees whose C(13,l) leaves cite the
cont.22 certificate table (safe_s<l>_...).  Lengths 3..5 are split into
per-first-element sub-lemmas + a combiner, keeping every declaration under
the heartbeat budget.  The spine (LRCSafeCertDispatch.lean) consumes these.
"""
from fractions import Fraction as F

CAPCONST = {1: F(6, 7), 2: F(66, 91), 3: F(55, 91), 4: F(1979, 4004), 5: F(2243, 5880)}

def cap_lit(l):
    c = CAPCONST[l]
    return f"(({c.numerator} : ℝ)/{c.denominator})"

def tree(fixed, level, l, lo, indent):
    """Emit the interval_cases tree: fixed = chosen values so far, level = index of
    the variable being cased (1-based over the ORIGINAL p1..pl), lo = min value."""
    pad = " " * indent
    hi = 13 - (l - level)  # p_level <= 13 - (l - level)
    lines = []
    lines.append(f"{pad}have hu{level} : p{level} ≤ {hi} := by omega")
    lines.append(f"{pad}interval_cases p{level}")
    for val in range(lo, hi + 1):
        if level == l:
            leaf = "safe_s" + str(l) + "_" + "_".join(str(x) for x in fixed + [val])
            lines.append(f"{pad}· exact {leaf}")
        else:
            lines.append(f"{pad}· -- p{level} = {val}")
            lines.extend(tree(fixed + [val], level + 1, l, val + 1, indent + 2))
    return lines

def hyps(l, start_var, lo_bound_name=True):
    """Hypothesis binders for variables p<start_var>..p<l> with lower bound name."""
    hs = []
    for i in range(start_var, l + 1):
        if i == start_var and lo_bound_name:
            pass
    return hs

def emit_len_single(l):
    vars_ = " ".join(f"p{i}" for i in range(1, l + 1))
    binders = [f"(hb1 : 1 ≤ p1)"]
    for i in range(1, l):
        binders.append(f"(h{i}{i+1} : p{i} < p{i+1})")
    binders.append(f"(hbtop : p{l} ≤ 13)")
    lst = ", ".join(f"p{i}" for i in range(1, l + 1))
    body = "\n".join(tree([], 1, l, 1, 2))
    return f"""/-- Leaf tree, length {l}: every sorted tuple dispatches to its table certificate. -/
theorem safe_floor_sorted_len{l} ({vars_} : ℤ) {" ".join(binders)} :
    {cap_lit(l)} ≤ (slowμ (safeSet ([{lst}] : List ℤ))).toReal := by
{body}
"""

def emit_len_split(l):
    """Per-first-element sub-lemmas + combiner for length l."""
    out = []
    hi1 = 13 - (l - 1)
    for c in range(1, hi1 + 1):
        vars_ = " ".join(f"p{i}" for i in range(2, l + 1))
        binders = [f"(hb2 : ({c} : ℤ) < p2)"]
        for i in range(2, l):
            binders.append(f"(h{i}{i+1} : p{i} < p{i+1})")
        binders.append(f"(hbtop : p{l} ≤ 13)")
        lst = ", ".join([str(c)] + [f"p{i}" for i in range(2, l + 1)])
        body = "\n".join(tree([c], 2, l, c + 1, 2))
        out.append(f"""theorem safe_floor_s{l}_head{c} ({vars_} : ℤ) {" ".join(binders)} :
    {cap_lit(l)} ≤ (slowμ (safeSet ([{lst}] : List ℤ))).toReal := by
{body}
""")
    # combiner
    vars_ = " ".join(f"p{i}" for i in range(1, l + 1))
    binders = [f"(hb1 : 1 ≤ p1)"]
    for i in range(1, l):
        binders.append(f"(h{i}{i+1} : p{i} < p{i+1})")
    binders.append(f"(hbtop : p{l} ≤ 13)")
    lst = ", ".join(f"p{i}" for i in range(1, l + 1))
    args = " ".join(f"p{i}" for i in range(2, l + 1))
    hargs = " ".join([f"h{i}{i+1}" for i in range(1, l)] + ["hbtop"])
    leaves = "\n".join(f"  · exact safe_floor_s{l}_head{c} {args} {hargs}"
                       for c in range(1, hi1 + 1))
    out.append(f"""/-- Leaf tree, length {l} (combined over the head element). -/
theorem safe_floor_sorted_len{l} ({vars_} : ℤ) {" ".join(binders)} :
    {cap_lit(l)} ≤ (slowμ (safeSet ([{lst}] : List ℤ))).toReal := by
  have hu1 : p1 ≤ {hi1} := by omega
  interval_cases p1
{leaves}
""")
    return "\n".join(out)

parts = [emit_len_single(1), emit_len_single(2), emit_len_split(3), emit_len_split(4), emit_len_split(5)]

lean = f"""/-
  TournamentH7.LRCSafeCertLeafTrees — the hB dispatcher leaf trees
  (mac-mini-2026-07-09-S65 cont.23, MACHINE-GENERATED by
  lrc14_dispatcher_codegen_macmini_S65cont23.py).

  For each length 1..5, `safe_floor_sorted_len<l>` sends EVERY sorted tuple
  `1 ≤ p1 < ⋯ < pl ≤ 13` to its cont.22 table certificate by an explicit
  interval_cases tree (2380 leaves total).  Lengths 3–5 are split by head
  element to keep each declaration inside the heartbeat budget.
-/
import Mathlib
import TournamentH7.LRCSafeCertSize1
import TournamentH7.LRCSafeCertSize2
import TournamentH7.LRCSafeCertSize3
import TournamentH7.LRCSafeCertSize4_g1to2
import TournamentH7.LRCSafeCertSize4_g3to10
import TournamentH7.LRCSafeCertSize5_c1
import TournamentH7.LRCSafeCertSize5_g2to3
import TournamentH7.LRCSafeCertSize5_g4to9

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace SafeCert

open DenseCovers MeasureTheory

{chr(10).join(parts)}
end SafeCert
end LRC14
end LonelyRunner
"""
outpath = "/Users/e/Documents/GitHub/math/04-computation/lean/TournamentH7/TournamentH7/LRCSafeCertLeafTrees.lean"
open(outpath, "w").write(lean)
nleaves = sum(1 for part in parts for line in part.splitlines() if "exact safe_s" in line)
print(f"wrote {outpath}")
print(f"table-citing leaves: {nleaves} (expect 13+78+286+715+1287 = 2379)")
