#!/usr/bin/env python3
"""
lrc14_leg_codegen_macmini_S65cont21.py -- ENGINE-LISTS-IN, PROOF-OUT made literal.

Generates a complete Lean certificate file for one witness-floor leg instance:
family P = [1..10] (small speeds), E = [0,1,2] (the consecutive large cluster,
klein-S236's measured extremal class; realizable as speeds {1..10, V-2, V-1, V}).

Pipeline: cont.16 engine computes the exact rational safeSet component list;
each component gets a TOOTH from E (tooth 2 on [0,3/7), tooth 1 on (1/7,6/7),
tooth 0 on (4/7,1) -- goodSet([0,1,2]) covers the whole circle) plus per-difference
bandCert j's and per-speed safe-band j's; the emitted Lean theorem consumes
GoodSetBand.witnessG2_ge_of_sorted_bands (cont.21) whose measure floor is
brick (iii) (cont.20 / opus-S204).

Output: 05-knowledge/results/lrc14_leg_codegen_macmini_S65cont21.out (data)
        04-computation/lean/TournamentH7/TournamentH7/LRCLegDemo.lean (proof text)
"""
from fractions import Fraction as F
import sys, importlib.util
spec = importlib.util.spec_from_file_location(
    "engine", "/Users/e/Documents/GitHub/math/04-computation/lrc14_interval_measure_engine_macmini_S65cont16.py")
eng = importlib.util.module_from_spec(spec)
spec.loader.exec_module(eng)

P = list(range(1, 11))
E = [0, 1, 2]

# --- exact safeSet component list (sorted, disjoint, closed rational intervals) ---
cur = eng.bands(P[0])
for p in P[1:]:
    cur = eng.inter(cur, eng.bands(p))
cur = sorted(cur)
total = sum(b - a for a, b in cur)
print(f"safeSet P={P}: {len(cur)} components, measure = {total}")
for a, b in cur:
    print(f"  [{a}, {b}]  len {b-a}")

# --- tooth selection + certificates ---
# goodSet tooth coverage (E = [0,1,2]):
#   tooth 2: down-bands e=2 (b=0): j=0 needs 2*beta <= 6/7  -> beta <= 3/7
#            down-band  e=1 (b=1): j=0 needs beta <= 6/7
#   tooth 1: down-band  e=1 (b=0): j=0 needs beta <= 6/7
#            up-band    e=1 (b=2): j=0 needs alpha > 1/7, beta <= 1
#   tooth 0: up-band    e=1 (b=1): j=0 needs alpha > 1/7, beta <= 1
#            up-band    e=2 (b=2): j=1 needs alpha > 4/7, beta <= 1
def tooth_for(a, b):
    if b <= F(3, 7):
        return 2
    if a > F(1, 7) and b <= F(6, 7):
        return 1
    if a > F(4, 7):
        return 0
    raise SystemExit(f"NO TOOTH COVERS [{a},{b}] -- component crosses tooth boundaries; split needed")

def up_j(e, a, b):
    # need j with j + 1/7 < e*a and e*b <= j + 1; try j = floor(e*a)
    j = (e * a).__floor__()
    assert j + F(1, 7) < e * a and e * b <= j + 1, (e, a, b, j)
    return j

def down_j(e, a, b):
    j = (e * a).__floor__()
    assert j <= e * a and e * b <= j + F(6, 7), (e, a, b, j)
    return j

def safe_j(p, a, b):
    j = (p * a).__floor__()
    assert F(j) + F(1, 14) <= p * a and p * b <= F(j) + F(13, 14), (p, a, b, j)
    return j

rows = []
for a, b in cur:
    t = tooth_for(a, b)
    cert = {}
    for bb in E:
        if bb == t:
            cert[bb] = ("eq", None)
        elif bb > t:
            cert[bb] = ("up", up_j(bb - t, a, b))
        else:
            cert[bb] = ("down", down_j(t - bb, a, b))
    sjs = [safe_j(p, a, b) for p in P]
    rows.append((a, b, t, cert, sjs))
    print(f"  cert [{a},{b}]: tooth {t}, bands {cert}, safe js {sjs}")

# --- emit Lean ---
def rl(x):  # rational literal in R
    return f"({x.numerator}/{x.denominator} : \u211d)" if x.denominator != 1 else f"({x.numerator} : \u211d)"

L_list = ", ".join(f"({rl(a)}, {rl(b)})" for a, b, *_ in rows)
sum_lengths = sum(b - a for a, b, *_ in rows)
PLIST = "[" + ",".join(str(p) for p in P) + "]"
ELIST = "[" + ",".join(str(e) for e in E) + "]"

def band_term(kind, j):
    if kind == "eq":
        return "Or.inl rfl"
    if kind == "up":
        return f"Or.inr (Or.inl \u27e8by norm_num, \u27e8{j}, by norm_num, by norm_num\u27e9\u27e9)"
    return f"Or.inr (Or.inr \u27e8by norm_num, \u27e8{j}, by norm_num, by norm_num\u27e9\u27e9)"

blocks = []
for a, b, t, cert, sjs in rows:
    bullets_b = "\n".join(f"        \u00b7 exact {band_term(*cert[bb])}" for bb in E)
    bullets_p = "\n".join(f"        \u00b7 exact \u27e8{j}, by norm_num, by norm_num\u27e9" for j in sjs)
    blocks.append(
f"""    \u00b7 refine \u27e8{t}, by decide, ?_, ?_\u27e9
      \u00b7 intro b hb
        fin_cases hb
{bullets_b}
      \u00b7 intro p hp
        fin_cases hp
{bullets_p}""")
cert_blocks = "\n".join(blocks)

lean = f"""/-
  TournamentH7.LRCLegDemo \u2014 the first end-to-end leg instance (mac-mini-2026-07-09-S65
  cont.21): engine-lists-in, proof-out, MACHINE-GENERATED by
  lrc14_leg_codegen_macmini_S65cont21.py from the cont.16 exact-rational engine.

  Family: P = [1..10], E = [0,1,2] (consecutive large cluster; realizable as
  speeds {{1..10, V-2, V-1, V}}).  Theorem: witnessG2 \u2265 {sum_lengths} = the exact
  slow\u03bc(goodSet E \u2229 safeSet P) (goodSet([0,1,2]) covers the circle via teeth 2/1/0,
  so the bound equals the full safeSet measure, 20 components).
  Every certificate is a rational band check discharged by norm_num.
-/
import Mathlib
import TournamentH7.LRCGoodSetBand

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace LegDemo

open GoodSetBand

/-- The engine's sorted component list for `safeSet [1..10]`. -/
noncomputable def demoL : List (\u211d \u00d7 \u211d) := [{L_list}]

/-- **The first machine-generated leg instance**: `witnessG2 \u2265 {sum_lengths}` for the
consecutive-cluster family `([1..10], [0,1,2])`. -/
theorem witnessG2_ge_demo :
    ({sum_lengths.numerator}/{sum_lengths.denominator} : \u211d) \u2264
      witnessG2 (({PLIST} : List \u2124), ({ELIST} : List \u2124)) := by
  have hposP : \u2200 p \u2208 ({PLIST} : List \u2124), (0:\u2124) < p := by decide
  have hin : \u2200 q \u2208 demoL, 0 \u2264 q.1 \u2227 q.1 \u2264 q.2 \u2227 q.2 \u2264 1 := by
    intro q hq
    unfold demoL at hq
    fin_cases hq <;> norm_num
  have hsorted : demoL.Pairwise (fun q r => q.2 \u2264 r.1) := by
    unfold demoL
    norm_num [List.pairwise_cons]
  have hcert : \u2200 q \u2208 demoL, \u2203 a \u2208 ({ELIST} : List \u2124),
      (\u2200 b \u2208 ({ELIST} : List \u2124), bandCert a b q.1 q.2) \u2227
      (\u2200 p \u2208 ({PLIST} : List \u2124), \u2203 j : \u2124,
        (j:\u211d) + 1/14 \u2264 (p:\u211d) * q.1 \u2227 (p:\u211d) * q.2 \u2264 (j:\u211d) + 13/14) := by
    intro q hq
    unfold demoL at hq
    fin_cases hq
{cert_blocks}
  have h := witnessG2_ge_of_sorted_bands (({PLIST} : List \u2124), ({ELIST} : List \u2124))
    demoL hposP hcert hin hsorted
  have hsum : (demoL.map (fun q => q.2 - q.1)).sum
      = ({sum_lengths.numerator}/{sum_lengths.denominator} : \u211d) := by
    unfold demoL
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  exact h

end LegDemo
end LRC14
end LonelyRunner
"""
outpath = "/Users/e/Documents/GitHub/math/04-computation/lean/TournamentH7/TournamentH7/LRCLegDemo.lean"
open(outpath, "w").write(lean)
print(f"wrote {outpath}")
print(f"sum of lengths = {sum_lengths}")
