#!/usr/bin/env python3
"""HYP-2728: factorial atom boundary operators for the LRC14 q0 target.

This scout sharpens the HYP-2720..HYP-2727 chain.

The missed-count atom vector q_t and factorial moments W_j are related by

    W_j = sum_{t>=j} binom(t,j) q_t,
    q_0 = sum_j (-1)^j W_j.

The canonical Vitali packet B_j is the atom move created by a unit W_j.  It is
an exact finite-difference boundary: W_i(B_j)=delta_{ij}.  The question for the
LRC proof is not whether these abstract packets exist, but which packet
directions are generated by miss-zeta product words and which are visible to
low-order witnesses such as W_1+W_2 or U4.
"""

from __future__ import annotations

import importlib.util
import math
import sys
from collections import Counter
from fractions import Fraction as F
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
S71_PATH = ROOT / "04-computation" / "lrc14_miss_zeta_word_compatibility_codex_s71.py"
spec = importlib.util.spec_from_file_location("s71_words", S71_PATH)
s71 = importlib.util.module_from_spec(spec)
assert spec.loader is not None
sys.modules[spec.name] = s71
spec.loader.exec_module(s71)


N = 7


def fmt(q: F | int | None) -> str:
    if q is None:
        return "None"
    if isinstance(q, int):
        return str(q)
    return f"{q} ({float(q):.9f})"


def sign(k: int) -> int:
    return 1 if k % 2 == 0 else -1


def basis(j: int) -> tuple[F, ...]:
    """Atom profile B_j(t)=(-1)^(j-t) binom(j,t), zero for t>j."""
    return tuple(F(sign(j - t) * math.comb(j, t)) if t <= j else F(0) for t in range(N))


def factorial(q: tuple[F, ...]) -> tuple[F, ...]:
    return tuple(sum(F(math.comb(t, j)) * q[t] for t in range(j, N)) for j in range(N))


def q0_from_moments(W: tuple[F, ...]) -> F:
    return sum(F(sign(j)) * W[j] for j in range(N))


def origin_coeff(t: int) -> F:
    return sum(F(sign(j) * math.comb(t, j)) for j in range(t + 1))


def u4(q: tuple[F, ...]) -> F:
    return q[0] + q[5] + 5 * q[6]


def tail45(q: tuple[F, ...]) -> F:
    return q[5] + 5 * q[6]


def b2_from_moments(W: tuple[F, ...]) -> F:
    return -W[1] + W[2]


def low12_abs(W: tuple[F, ...]) -> F:
    return abs(W[1]) + abs(W[2])


def packet_table() -> None:
    print("HYP-2728 factorial boundary operator scout")
    print()
    print("EXACT FINITE-DIFFERENCE PACKETS")
    print("  B_j is the atom profile created by unit W_j.")
    print("  moment row verifies W_i(B_j)=delta_ij; q0(B_j)=(-1)^j.")
    print("  j  B_j atoms Q0..Q6                         W(B_j)      q0  U4  low12")
    for j in range(N):
        q = basis(j)
        W = factorial(q)
        assert W == tuple(F(1 if i == j else 0) for i in range(N))
        assert q0_from_moments(W) == q[0]
        print(
            f"  {j}  {tuple(str(x) for x in q)!s:39s} "
            f"{tuple(str(x) for x in W)!s:25s} "
            f"{fmt(q[0]):>3s} {fmt(u4(q)):>3s} {fmt(low12_abs(W)):>5s}"
        )

    print()
    print("ORIGIN COEFFICIENT CHECK")
    print("  sum_j (-1)^j binom(t,j) is the coefficient of q_t in q0.")
    for t in range(N):
        print(f"  t={t}: coeff={origin_coeff(t)}")


def cheap_lp_table() -> None:
    print()
    print("ABSTRACT CHEAP LP DIRECTIONS FROM HYP-2721")
    print("  normalized q0=1; these are legal in the atom cone before generated-word tests.")
    print("  r  tax        W1       W2       |W1|+|W2|  B2        U4        tail45")
    for r in range(1, 6):
        q = s71.cheap_lp_direction(r)
        W = factorial(q)
        print(
            f"  {r}  {fmt(sum(abs(q[t]) for t in range(1, N))):10s} "
            f"{fmt(W[1]):9s} {fmt(W[2]):9s} {fmt(low12_abs(W)):11s} "
            f"{fmt(b2_from_moments(W)):9s} {fmt(u4(q)):9s} {fmt(tail45(q)):9s}"
        )


def norm_tuple(q: tuple[F, ...], q0: F) -> tuple[F, ...]:
    return tuple(x / q0 for x in q)


def row_key(m: object) -> str:
    return f"size={m.size} shape={m.shape} context={m.context_name}"


def min_row(rows: list[object], value) -> tuple[F, object]:
    best = min(rows, key=value)
    return value(best), best


def generated_frontier() -> None:
    print()
    print("GENERATED MISS-ZETA FRONTIER")
    print("  Loading S71 frontier metrics; this recomputes the exact 318-test bank.")
    metrics = s71.frontier_metrics()
    positive = [m for m in metrics if m.q0 > 0 and m.norm_atoms is not None]
    print()
    print(f"  tests={len(metrics)} positive_q0={len(positive)} q0_failures={len(metrics)-len(positive)}")

    def Wn(m: object) -> tuple[F, ...]:
        assert m.norm_atoms is not None
        return factorial(m.norm_atoms)

    probes = {
        "W1": lambda m: Wn(m)[1],
        "W2": lambda m: Wn(m)[2],
        "W1+W2": lambda m: Wn(m)[1] + Wn(m)[2],
        "|W1|+|W2|": lambda m: low12_abs(Wn(m)),
        "B2=-W1+W2": lambda m: b2_from_moments(Wn(m)),
        "U4": lambda m: u4(m.norm_atoms),  # type: ignore[arg-type]
        "tail45": lambda m: tail45(m.norm_atoms),  # type: ignore[arg-type]
    }

    print()
    print("  signed/absolute witness minima on normalized generated moves")
    for name, value in probes.items():
        val, row = min_row(positive, value)
        nonpos = sum(1 for m in positive if value(m) <= 0)
        print(f"  {name:12s} min={fmt(val):18s} nonpositive={nonpos:3d} at {row_key(row)}")

    print()
    print("  closest abstract cheap directions, measured by L1 distance")
    for r in (1, 2, 3):
        target = s71.cheap_lp_direction(r)
        val, row = min_row(positive, lambda m: s71.l1_distance(m.norm_atoms, target))
        assert row.norm_atoms is not None
        W = Wn(row)
        print(
            f"  r={r}: dist={fmt(val)} at {row_key(row)}; "
            f"|W1|+|W2|={fmt(low12_abs(W))}, U4={fmt(u4(row.norm_atoms))}"
        )

    print()
    print("TOURNAMENT ANALYSIS")
    print("  vertices: witness functionals on normalized generated atom moves")
    print("  pairwise observable: fewer nonpositive rows, then larger exact minimum")
    stats = []
    for name, value in probes.items():
        vals = [value(m) for m in positive]
        stats.append((name, sum(1 for x in vals if x <= 0), min(vals)))
    wins = Counter()
    for a in stats:
        for b in stats:
            if a == b:
                continue
            if (a[1], -a[2]) < (b[1], -b[2]):
                wins[a[0]] += 1
    ordered = sorted(stats, key=lambda x: (x[1], -x[2], x[0]))
    print("  pressure path:")
    for name, nonpos, minimum in ordered:
        print(f"    {name:12s} score={wins[name]} nonpositive={nonpos} min={fmt(minimum)}")
    print("  directed_3cycles=0 (total order by the stated observable)")

    print()
    print("SYNTHESIS")
    print("  The abstract finite-difference packets are perfectly formal: B_j is")
    print("  exactly dual to W_j, and q0 is the alternating boundary of W.")
    print("  But the generated frontier does not follow a simple signed W1, W2, or")
    print("  B2 rule.  The robust generated witnesses are the absolute low leakage")
    print("  |W1|+|W2| and the Bonferroni4 U4 readout; this matches HYP-2722/HYP-2727.")
    print("  Therefore the HYP-2725/HYP-2727 proof order should be strengthened:")
    print("  formalize the finite-difference boundary first, then prove generated-word")
    print("  exclusion for the cheap atom-cone directions before applying the")
    print("  factorial odd L1 envelope to the high relation-support tail.")


def main() -> None:
    packet_table()
    cheap_lp_table()
    generated_frontier()


if __name__ == "__main__":
    main()
