#!/usr/bin/env python3
"""
lrc14_lonely_emitter_macmini_S65cont28.py -- UNCONDITIONAL per-family LRC(14) theorems.

The certificate-supply de-citation made concrete: for any given 13-speed family, this
emitter computes an exact rational strict-safe interval [x/D, y/D] (the interior middle
third of the largest full-family safe component), the 13 SafeIvStrict floor-witnesses,
and the grid modulus q -- and emits a COMPLETE Lean theorem

    theorem <fam>_lonely : exists t, Lonely 14 <fam> t

with NO hypotheses and NO citations: klein's strictWitness_of_cert (S242) turns the
certificates into a StrictWitness; my minReach/Mreach bridges (cont.26/27) finish.
Families whose largest safe component is degenerate (tight, M = 1/14) are rejected
honestly -- no strict certificate exists for them.

Output: 04-computation/lean/TournamentH7/TournamentH7/LRCLonelyInstances.lean
"""
from fractions import Fraction as F
from math import gcd, lcm
import importlib.util

spec = importlib.util.spec_from_file_location(
    "engine", "/Users/e/Documents/GitHub/math/04-computation/lrc14_interval_measure_engine_macmini_S65cont16.py")
eng = importlib.util.module_from_spec(spec)
spec.loader.exec_module(eng)

FAMILIES = [
    ("deepWell",   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 182]),
    ("legDemoFam", [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 9998, 9999, 10000]),
    ("multiScale", [1, 2, 3, 4, 5, 50, 51, 52, 5000, 5001, 5002, 5003, 5004]),
    ("coveringShift", [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]),
    ("allOdd",     [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25]),
]

def strict_interval(speeds):
    cur = eng.bands(speeds[0])
    for v in speeds[1:]:
        cur = eng.inter(cur, eng.bands(v))
    if not cur:
        return None
    a, b = max(cur, key=lambda iv: iv[1] - iv[0])
    if b <= a:
        return None
    lo = a + (b - a) / 3
    hi = b - (b - a) / 3
    D = lcm(lo.denominator, hi.denominator)
    x = lo.numerator * (D // lo.denominator)
    y = hi.numerator * (D // hi.denominator)
    assert F(x, D) == lo and F(y, D) == hi and 0 <= x < y < D
    return D, x, y

def certs(speeds, D, x, y):
    out = []
    for v in speeds:
        j = (v * x) // D
        # strict: D < 14(vx - jD)  and  14(vy - jD) < 13D
        assert D < 14 * (v * x - j * D), (v, "lo")
        assert 14 * (v * y - j * D) < 13 * D, (v, "hi")
        out.append(j)
    return out

def emit(name, speeds):
    si = strict_interval(speeds)
    if si is None:
        print(f"  {name}: NO strict component (tight family) -- SKIPPED")
        return None
    D, x, y = si
    js = certs(speeds, D, x, y)
    q = D // (y - x) + 1
    assert D < (y - x) * q
    lst = ", ".join(str(v) for v in speeds)
    distinct_js = sorted(set(js))
    alts = "\n".join(f"        | exact ⟨{j}, by decide⟩" for j in distinct_js)
    print(f"  {name}: interval [{x}/{D}, {y}/{D}] (len {F(y-x, D)}), q = {q}, js = {js}")
    return f"""/-- `{name}` = `{speeds}`. -/
def {name} : Fin 13 → ℤ := ![{lst}]

/-- **UNCONDITIONAL**: the family `{name}` has a 14-lonely time.  Certificate:
the strict-safe interval `[{x}/{D}, {y}/{D}]`, grid modulus `{q}`. -/
theorem {name}_cert : ∀ i, MeasureTransfer.SafeIvStrict ({name} i) {D} {x} {y} := by
  intro i
  fin_cases i <;>
    first
{alts}

theorem {name}_lonely : ∃ t : ℝ, Lonely 14 {name} t := by
  have hv : ∀ i, {name} i ≠ 0 := by intro i; fin_cases i <;> decide
  have hpos : ∀ i, 0 < {name} i := by intro i; fin_cases i <;> decide
  have hsw : LRC14Grand.StrictWitness {name} :=
    MeasureTransfer.strictWitness_of_cert {name} {D} {x} {y} {q} hpos
      (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      {name}_cert
  obtain ⟨τ, hτ⟩ := LRC14.ReachDecitation.minReach_ge_of_strictWitness hsw
  exact LRC14.lonely_of_Mreach_ge {name} hv (LRC14.ReachCitation.Mreach_ge_of_minReach {name} τ hτ)
"""

thms = []
for nm, sp in FAMILIES:
    t = emit(nm, sp)
    if t:
        thms.append(t)

lean = f"""/-
  TournamentH7.LRCLonelyInstances — UNCONDITIONAL LRC(14) instances
  (mac-mini-2026-07-09-S65 cont.28, MACHINE-GENERATED by
  lrc14_lonely_emitter_macmini_S65cont28.py).

  The certificate-supply de-citation made concrete: each theorem below is a
  COMPLETE, HYPOTHESIS-FREE `∃ t, Lonely 14 v t` for a concrete 13-speed family —
  no citations, no sorries.  The engine computes the strict-safe interval and the
  thirteen SafeIvStrict floor-witnesses; klein's transfer (S242) and the
  cont.26/27 reach bridges do the rest.  The emitter REJECTS tight families
  (no strict component) honestly.

  These are, to our knowledge, the first fully unconditional 14-runner
  loneliness theorems in the tree — the per-family output shape of the
  `THM527ACertificateSupply` citation, produced on demand.
-/
import Mathlib
import TournamentH7.LRCReachDecitation

set_option maxHeartbeats 1600000

namespace LonelyRunner
namespace LRC14
namespace LonelyInstances

open LonelyRunner

{chr(10).join(thms)}
end LonelyInstances
end LRC14
end LonelyRunner
"""
outpath = "/Users/e/Documents/GitHub/math/04-computation/lean/TournamentH7/TournamentH7/LRCLonelyInstances.lean"
open(outpath, "w").write(lean)
print(f"wrote {outpath}: {len(thms)} unconditional instances")
