#!/usr/bin/env python3
"""
lrc_tetration_hyper_lacunary_s551.py    codex-2026-06-01-S551

Explore level-4 (tetration) speed families as the hyper-lacunary extreme of
the LRC hyperoperation ladder.

Interpretation used here:
  H1/H2 runner clearance: a runner speed s contributes a level-2 clearance
      factor c_s(t), sampled as a condition ||s t|| >= 1/(m+1).
  H3 cascade product: adding runners closes those factors under repeated
      multiplication, |SAFE| = prod_k c_k.
  H4 tetration speeds: speed families generated by a^^k are so lacunary that,
      modulo ordinary sampling grids, they should behave like near-independent
      clearance clocks except where finite-modulus aliasing folds the tower.

Tournament Analysis declaration:
  Vertices:
    speed families (AP, Fibonacci, geometric bases 2/3, tetration bases 2/3).
  Pairwise observable:
    sampled cascade product, product/independence credit, danger-overlap ratio,
    mean half-turn tournament H-entropy, and free energy -log(product).
  Switch/gauge:
    A -> B if A wins a majority of the "looser/easier" signs:
      product higher, product/credit higher, overlap ratio lower, entropy lower,
      free energy lower.
  Tie Hamiltonian path:
    tetration-3 -> tetration-2 -> geometric-3 -> geometric-2 -> Fibonacci -> AP.

Assumption challenge:
  We considered runner vertices, clearance-factor vertices, cascade prefixes, speed
  families, gap cells, danger arcs, Fourier modes, and proof obligations. This script
  uses speed-family vertices plus within-family clearance factors. It preserves the
  LRC predicate "sampled lonely measure is positive and how far from independent
  credit it lies" while destroying exact endpoint geometry, exact residues beyond
  the chosen finite moduli, and proof-level set-vs-measure distinctions.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd, log, log2
from functools import reduce
from collections import Counter, defaultdict

SAMPLES = 5003
DENOM = 2 * SAMPLES
H_SAMPLES = 401
H_DENOM = H_SAMPLES


@dataclass(frozen=True)
class Tower:
    base: int
    height: int

    def label(self) -> str:
        return f"{self.base}^^{self.height}"


def tower_exact(base: int, height: int, limit: int = 10**100) -> int | None:
    """Return base tetrated to height if it stays below limit."""
    x = base
    if height == 1:
        return x
    for _ in range(2, height + 1):
        if x > 10**6:
            return None
        x = base**x
        if x > limit:
            return None
    return x


def phi(n: int) -> int:
    out = n
    p = 2
    x = n
    while p * p <= x:
        if x % p == 0:
            out -= out // p
            while x % p == 0:
                x //= p
        p += 1 if p == 2 else 2
    if x > 1:
        out -= out // x
    return out


def tower_mod(base: int, height: int, mod: int) -> int:
    """Compute base^^height modulo mod for the small tower heights used here."""
    if mod == 1:
        return 0
    if height == 1:
        return base % mod

    exact_exp = tower_exact(base, height - 1, limit=10**30)
    if exact_exp is not None:
        return pow(base, exact_exp, mod)

    # Fallback for genuinely huge towers. The +phi lift is a conservative stable
    # exponent for non-coprime moduli; here it is only a backup path.
    ph = phi(mod)
    return pow(base, tower_mod(base, height - 1, ph) + ph, mod)


def speed_mod(speed: int | Tower, mod: int) -> int:
    if isinstance(speed, Tower):
        return tower_mod(speed.base, speed.height, mod)
    return speed % mod


def speed_label(speed: int | Tower) -> str:
    if isinstance(speed, Tower):
        return speed.label()
    return str(speed)


def family_label(speeds: tuple[int | Tower, ...]) -> str:
    return "(" + ",".join(speed_label(s) for s in speeds) + ")"


def h_count(adj: list[list[int]], n: int) -> int:
    full = (1 << n) - 1
    dp = [[0] * n for _ in range(1 << n)]
    for v in range(n):
        dp[1 << v][v] = 1
    for mask in range(1 << n):
        for v in range(n):
            c = dp[mask][v]
            if not c:
                continue
            for u in range(n):
                if mask & (1 << u):
                    continue
                if adj[v][u]:
                    dp[mask | (1 << u)][u] += c
    return sum(dp[full][v] for v in range(n))


def half_turn_tournament(phases: list[int], denom: int) -> list[list[int]]:
    n = len(phases)
    adj = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            d = (phases[j] - phases[i]) % denom
            if d == 0 or 2 * d == denom:
                winner, loser = i, j
            elif 2 * d < denom:
                winner, loser = i, j
            else:
                winner, loser = j, i
            adj[winner][loser] = 1
    return adj


def mean_h_entropy(speeds: tuple[int | Tower, ...]) -> float:
    n = len(speeds)
    total = 0.0
    count = 0
    mods = [speed_mod(s, H_DENOM) for s in speeds]
    for k in range(H_SAMPLES):
        phases = [(m * (k + 1)) % H_DENOM for m in mods]
        h = h_count(half_turn_tournament(phases, H_DENOM), n)
        if h:
            total += log2(h)
            count += 1
    return total / count if count else 0.0


def danger_vector(speed: int | Tower, n_total: int) -> list[bool]:
    smod = speed_mod(speed, DENOM)
    vec: list[bool] = []
    for j in range(SAMPLES):
        num = 2 * j + 1
        r = (smod * num) % DENOM
        dist_num = min(r, DENOM - r)
        vec.append(dist_num * n_total < DENOM)
    return vec


def clearance_stats(speeds: tuple[int | Tower, ...]) -> dict[str, object]:
    m = len(speeds)
    n_total = m + 1
    danger = [danger_vector(s, n_total) for s in speeds]
    surviving = [True] * SAMPLES
    clearances = []
    prefix_products = []
    prev = SAMPLES
    for vec in danger:
        cur = 0
        for i, bad in enumerate(vec):
            if surviving[i] and bad:
                surviving[i] = False
            if surviving[i]:
                cur += 1
        c = cur / prev if prev else 0.0
        clearances.append(c)
        prefix_products.append(cur / SAMPLES)
        prev = cur

    product = prefix_products[-1]
    credit = ((n_total - 2) / n_total) ** m
    free_energy = float("inf") if product <= 0 else -log(product)

    overlap_ratios = []
    for a in range(m):
        pa = sum(danger[a]) / SAMPLES
        for b in range(a + 1, m):
            pb = sum(danger[b]) / SAMPLES
            pab = sum(1 for i in range(SAMPLES) if danger[a][i] and danger[b][i]) / SAMPLES
            denom = pa * pb
            if denom:
                overlap_ratios.append(pab / denom)
    overlap = sum(overlap_ratios) / len(overlap_ratios)

    return {
        "n_total": n_total,
        "clearances": clearances,
        "prefix_products": prefix_products,
        "product": product,
        "credit": credit,
        "credit_ratio": product / credit if credit else 0.0,
        "free_energy": free_energy,
        "overlap_ratio": overlap,
        "mean_h_entropy": mean_h_entropy(speeds),
    }


def strongly_connected_components(adj: list[list[int]]) -> list[list[int]]:
    n = len(adj)
    order = []
    seen = [False] * n

    def dfs(v: int) -> None:
        seen[v] = True
        for u, edge in enumerate(adj[v]):
            if edge and not seen[u]:
                dfs(u)
        order.append(v)

    for v in range(n):
        if not seen[v]:
            dfs(v)

    radj = [[adj[j][i] for j in range(n)] for i in range(n)]
    seen = [False] * n
    comps = []

    def rdfs(v: int, comp: list[int]) -> None:
        seen[v] = True
        comp.append(v)
        for u, edge in enumerate(radj[v]):
            if edge and not seen[u]:
                rdfs(u, comp)

    for v in reversed(order):
        if not seen[v]:
            comp: list[int] = []
            rdfs(v, comp)
            comps.append(sorted(comp))
    return comps


def count_directed_triangles(adj: list[list[int]]) -> int:
    n = len(adj)
    c3 = 0
    for i in range(n):
        for j in range(i + 1, n):
            for k in range(j + 1, n):
                e = adj[i][j] + adj[j][k] + adj[k][i]
                if e in (0, 3):
                    c3 += 1
    return c3


def tournament_fingerprint(adj: list[list[int]], names: list[str], tie_order: list[str]) -> dict[str, object]:
    scores = [sum(row) for row in adj]
    tie_rank = {name: i for i, name in enumerate(tie_order)}
    flips = []
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            expected = i if tie_rank[names[i]] < tie_rank[names[j]] else j
            actual = i if adj[i][j] else j
            if actual != expected:
                flips.append(f"{names[actual]}>{names[expected]}")
    return {
        "scores": dict(zip(names, scores)),
        "score_hist": dict(sorted(Counter(scores).items())),
        "c3": count_directed_triangles(adj),
        "sccs": [[names[i] for i in comp] for comp in strongly_connected_components(adj)],
        "hamiltonian_paths": h_count(adj, len(names)),
        "edge_flips_vs_tie_path": flips,
    }


def family_tournament(stats: dict[str, dict[str, object]], tie_order: list[str]) -> list[list[int]]:
    names = list(stats)
    n = len(names)
    tie_rank = {name: i for i, name in enumerate(tie_order)}
    adj = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            a, b = names[i], names[j]
            sa, sb = stats[a], stats[b]
            votes_a = 0
            votes_b = 0
            comparisons = [
                (sa["product"], sb["product"], "high"),
                (sa["credit_ratio"], sb["credit_ratio"], "high"),
                (sa["overlap_ratio"], sb["overlap_ratio"], "low"),
                (sa["mean_h_entropy"], sb["mean_h_entropy"], "low"),
                (sa["free_energy"], sb["free_energy"], "low"),
            ]
            for va, vb, mode in comparisons:
                if va == vb:
                    continue
                if mode == "high":
                    votes_a += va > vb
                    votes_b += vb > va
                else:
                    votes_a += va < vb
                    votes_b += vb < va
            if votes_a == votes_b:
                winner = a if tie_rank[a] < tie_rank[b] else b
            else:
                winner = a if votes_a > votes_b else b
            wi, li = (i, j) if winner == a else (j, i)
            adj[wi][li] = 1
    return adj


def fmt_float(x: float) -> str:
    if x == float("inf"):
        return "inf"
    if abs(x) >= 100:
        return f"{x:.2f}"
    if abs(x) >= 1:
        return f"{x:.4f}"
    return f"{x:.6f}"


def main() -> None:
    families: dict[str, tuple[int | Tower, ...]] = {
        "L2_AP": (1, 2, 3, 4, 5, 6),
        "L2_Fibonacci": (1, 2, 3, 5, 8, 13),
        "L3_geom2": (1, 2, 4, 8, 16, 32),
        "L3_geom3": (1, 3, 9, 27, 81, 243),
        "L4_tetr2": (1, 2, 4, 16, 65536, Tower(2, 5)),
        "L4_tetr3": (1, 3, 27, 3**27, Tower(3, 4), Tower(3, 5)),
    }
    tie_order = ["L4_tetr3", "L4_tetr2", "L3_geom3", "L3_geom2", "L2_Fibonacci", "L2_AP"]

    print("Level-4 tetration as the hyper-lacunary LRC extreme (codex-S551)")
    print(f"sample grid: {SAMPLES} midpoints, threshold=1/(m+1) with m=6 runners")
    print("cascade reading: runner clearances c_k are level-2 factors; prod_k c_k is the level-3 repeated-x closure\n")

    stats = {name: clearance_stats(speeds) for name, speeds in families.items()}

    print("Family clearance ledger")
    for name, speeds in families.items():
        st = stats[name]
        cs = ", ".join(fmt_float(c) for c in st["clearances"])
        pp = ", ".join(fmt_float(p) for p in st["prefix_products"])
        print(f"  {name:12s} speeds={family_label(speeds)}")
        print(
            f"    product={fmt_float(st['product'])}  credit={fmt_float(st['credit'])}  "
            f"product/credit={fmt_float(st['credit_ratio'])}  free_energy={fmt_float(st['free_energy'])}"
        )
        print(
            f"    danger_overlap={fmt_float(st['overlap_ratio'])}  "
            f"mean_H_entropy={fmt_float(st['mean_h_entropy'])}"
        )
        print(f"    c_k=[{cs}]")
        print(f"    prefix prod=[{pp}]")

    adj = family_tournament(stats, tie_order)
    names = list(stats)
    fp = tournament_fingerprint(adj, names, tie_order)
    edges = []
    for i, a in enumerate(names):
        for j, b in enumerate(names):
            if adj[i][j]:
                edges.append(f"{a}->{b}")

    print("\nTournament Analysis")
    print("  vertices: speed families")
    print("  observable: product high, product/credit high, danger-overlap low, mean H low, free energy low")
    print("  switch: majority vote over the five signs; tie path = " + " > ".join(tie_order))
    print("  edges: " + ", ".join(edges))
    print(f"  scores: {fp['scores']}")
    print(f"  score_hist: {fp['score_hist']}")
    print(f"  directed_3_cycles: {fp['c3']}")
    print(f"  SCCs: {fp['sccs']}")
    print(f"  Hamiltonian_path_count: {fp['hamiltonian_paths']}")
    print(f"  edge_flips_vs_tie_path: {fp['edge_flips_vs_tie_path']}")

    best_product = max(stats, key=lambda k: stats[k]["product"])
    best_entropy = min(stats, key=lambda k: stats[k]["mean_h_entropy"])
    print("\nSynthesis")
    print(
        "  Tetration does what the ladder predicts qualitatively: it is the hyper-lacunary "
        "edge of the speed spectrum, with low H-entropy and a positive sampled cascade."
    )
    print(
        "  The finite modulus still matters: towers fold modulo the sampling denominators, "
        "so a tetration family can reduce entropy without automatically maximizing the "
        "product. It is best read as the decorrelation extreme whose remaining "
        "obstructions are aliasing events."
    )
    print(f"  Best sampled product: {best_product}; lowest mean H-entropy: {best_entropy}.")
    print(
        "  Cascade product = repeated multiplication of runner clearances; the proof target "
        "is to show finite aliasing cannot create an AP-like zero factor outside the "
        "additive/tight regime."
    )


if __name__ == "__main__":
    main()
