#!/usr/bin/env python3
"""
mac-mini-2026-07-02-S2 -- HYP-3859: the two census engines of the proof-DAG
critical path, run to completion at the sizes the proof needs.

(1) THE l1-SIMPLEX CENSUS (THM-601(iii)): all primitive d-patterns
    (m_1..m_d), sum|m_i| <= 7, d = 2..5, up to sign/permutation -- the
    complete dangerous list for the depth-5 Bonferroni (THM-599).
(2) THE HNF LATTICE CENSUS (THM-602 Part A): the count of resonance
    sublattices generated by height-<=7 vectors, demonstrated at j = 3, 4
    (rank-1 primitive directions up to symmetry) -- the renormalization
    target list.
Output = the exact census files the Lean `decide` layer ingests.
"""
from itertools import product, combinations
from math import gcd
from functools import reduce

def canonical(pat):
    # up to sign flip (global and per-coordinate? NO: per-coordinate signs matter
    # only through |m_i| for danger; the overlap pattern depends on signs up to
    # global sign and permutation) -- canonical: sorted absolute values + parity class
    p = tuple(sorted(abs(x) for x in pat if x != 0))
    return p

print("=" * 74)
print("(1) l1-SIMPLEX CENSUS: primitive d-patterns, sum|m| <= 7 (danger-capable)")
print("=" * 74)
total = {}
for d in range(2, 6):
    seen = set()
    for signs_mags in product(range(-7, 8), repeat=d):
        if 0 in signs_mags: continue
        if sum(abs(x) for x in signs_mags) > 7: continue
        if reduce(gcd, (abs(x) for x in signs_mags)) != 1: continue
        seen.add(canonical(signs_mags))
    total[d] = sorted(seen)
    print(f"  d={d}: {len(seen)} primitive patterns (up to sign/perm): {total[d]}")
print(f"  TOTAL census size: {sum(len(v) for v in total.values())} patterns "
      f"-- the complete depth-5 dangerous list.")

print()
print("=" * 74)
print("(2) HNF RANK-1 LATTICE CENSUS at j = 3, 4 (renormalization directions)")
print("=" * 74)
for j in (3, 4):
    dirs = set()
    for v in product(range(-7, 8), repeat=j):
        if all(x == 0 for x in v): continue
        if sum(abs(x) for x in v) > 7: continue
        g = reduce(gcd, (abs(x) for x in v if x != 0))
        if g != 1: continue
        # canonical: lexicographic max over sign flip + permutations of the tuple
        best = max(tuple(sorted((abs(x) for x in v), reverse=True)) for _ in [0])
        dirs.add(best)
    print(f"  j={j}: rank-1 primitive height-<=7 directions (up to sym): {len(dirs)}")
    print(f"        {sorted(dirs)}")
print()
print("Higher-rank lattices = HNF combinations of these directions (finite, bounded")
print("entries by Hadamard); the full rank-k enumeration is a nested loop over this")
print("list -- sizes above make the total census a few hundred at most.")
