#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
lrc_threadA_modular_residue_kpswf5.py  (kind-pasteur 2026-06-21, THREAD A)

THREAD A: the MODULAR / X(7) structure of the L7 residue discrepancy.

Background (canon):
  HYP-2739 (PROVED): D_{p,q} = S(p%7,q%7)/(7pq), S = 4 f(||p||_7,||q||_7),
    ||x||_7 = min(x%7, 7-x%7) in {0,1,2,3}.
  HYP-2742: S(p,q) on (Z/7)^2 is invariant under the order-? group generated by
    transpose (p,q)->(q,p), negations (p,q)->(-p,q), and modular S (p,q)->(q,-p);
    NOT invariant under doubling z->2z.  Conjectured X(7)/PSL(2,7) shadow.

This script does the THREE THREAD-A tasks, all in EXACT integer arithmetic:

  (1) For each odd prime P (and a few composites for contrast), build the full
      PxP integer residue table S_P(a,b) = sum_j |P*c_{0j} - p*q| for (p,q) in the
      residue class (a,b) with gcd(p,q)=1, p/q < P (so the cov closed form is valid).
      Then:
        - confirm S_P factors through ||.||_P x ||.||_P (the <-1> quotient on each coord),
        - find a closed form f_P(a,b) on the reduced range a,b in {0..(P-1)/2},
        - determine the FULL symmetry group of S_P as a function on (Z/P)^2 / acting,
          in particular whether it is invariant under the modular involutions
          (transpose=inversion z->1/z, negation z->-z, S: z->-1/z) and NOT under
          doubling / general F_P^* scaling.

  (2) GENERAL-P LAW: extract f_P for P=3,5,7,11,13 and look for a uniform formula
      S_P(a,b) = (closed form in a,b,P).  Test the user's candidate shape
      c*f_P(||p||,||q||) and the P=7 specific f.

  (3) MODULAR characterization for P=7: realize S as a function on P^1(F_7) (8 slopes
      including infinity), identify the orbit structure under PGL_2 subgroups, and the
      <z->-z, z->1/z> Klein-4 quotient.  Cross-check against zonal/spherical function
      candidates and the "antidiagonal of the S-table = the 12,20,24 sharp constants".

Everything saved; honest labels only.
"""
from math import gcd
from fractions import Fraction as Fr
from collections import defaultdict
import itertools


# ----------------------------------------------------------------------
# Core: row-0 integer counts on the Ppq grid via the verified cov model.
# (matches HYP-2739 / general_prime script; cov-model == direct grid == closed form)
# ----------------------------------------------------------------------
def cmatrix_row0(p, q, P):
    """row 0 of the P-sector integer matrix on the Ppq grid (cov model)."""
    r = [0] * P
    for a in range(q):
        for t in range(p):
            v = (P * a + t) % (P * q)
            r[v // q] += 1
    return r


def S_of_pq(p, q, P):
    """full-matrix defect S = sum_ij |P c_ij - pq|.
    By cyclic-shift collapse (Lemma B), every row is a shift of row 0 when P nmid q,
    so S = P * sum_j |P c_0j - pq|.  We compute row 0 and multiply by P."""
    r0 = cmatrix_row0(p, q, P)
    rowdef = sum(abs(P * x - p * q) for x in r0)
    return P * rowdef, rowdef


def norm_P(x, P):
    """||x||_P = min(x%P, P-x%P) in {0,...,(P-1)/2}."""
    m = x % P
    return min(m, P - m)


# ----------------------------------------------------------------------
# (1)+(2): build residue tables S_P, check residue-only, factor through ||.||,
# extract reduced f_P, and search for a uniform closed form.
# ----------------------------------------------------------------------
def build_residue_table(P, qmax=24):
    """For each residue class (a,b)=(p%P,q%P) collect the value S_P (= P*rowdef).
    Returns dict (a,b)->set of S values (should be singletons => residue-only)."""
    table = defaultdict(set)
    rowtable = defaultdict(set)
    n = 0
    for q in range(1, qmax + 1):
        for p in range(q + 1, P * q):  # window 1 < p/q < P (cov form valid)
            if gcd(p, q) != 1:
                continue
            S, rowdef = S_of_pq(p, q, P)
            table[(p % P, q % P)].add(S)
            rowtable[(p % P, q % P)].add(rowdef)
            n += 1
    return table, rowtable, n


def reduce_to_norm(P, table):
    """Check S_P(a,b) factors through (||a||,||b||); return reduced f-table on
    {0..(P-1)/2}^2 of the *rowdef* value (S/P) for cleanliness, plus consistency flag."""
    half = (P - 1) // 2
    fred = {}  # (||a||,||b||) -> rowdef value
    consistent = True
    for (a, b), Sset in table.items():
        if len(Sset) != 1:
            consistent = False
            continue
        S = next(iter(Sset))
        rowdef = S // P
        key = (norm_P(a, P), norm_P(b, P))
        if key in fred and fred[key] != rowdef:
            consistent = False
        fred[key] = rowdef
    return fred, half, consistent


def grid_print(P, fred):
    """Pretty-print the reduced f_P table (rowdef = S/P) over ||a||,||b|| in 0..half."""
    half = (P - 1) // 2
    print(f"  reduced rowdef table f_P (=S/P) for P={P}, indices ||.||_P in 0..{half}:")
    header = "      " + "".join(f"{b:5d}" for b in range(half + 1))
    print(header)
    for a in range(half + 1):
        row = "".join(f"{fred.get((a, b), -1):5d}" for b in range(half + 1))
        print(f"   a={a}: {row}")
    # also S = P * rowdef table max
    Smax = max(P * v for v in fred.values())
    print(f"   max S_P = {Smax}  (= P*{Smax//P})")
    return Smax


# ----------------------------------------------------------------------
# (1) symmetry group of S_P as function on (Z/P)^2.
# Test invariance under the natural PGL_2(F_P) generators acting on the slope p/q.
# We treat (p,q) as homogeneous coords of slope z=p/q in P^1(F_P).
# ----------------------------------------------------------------------
def symmetry_report(P, table):
    """Report which slope-transformations preserve S_P.
    Represent S as a function on P^1(F_P) where possible (p,q with q!=0 -> z=p/q;
    plus q=0 means infinity). Within our window q>=1, but residue q%P can be 0.
    We test maps on the residue pair (a,b)=(p%P,q%P)."""
    # canonical value function on residue pairs (only where defined & singleton)
    val = {}
    for (a, b), Sset in table.items():
        if len(Sset) == 1:
            val[(a, b)] = next(iter(Sset))

    def test_map(name, fn):
        ok = True
        checked = 0
        for (a, b), v in val.items():
            na, nb = fn(a, b)
            na %= P
            nb %= P
            if (na, nb) in val:
                checked += 1
                if val[(na, nb)] != v:
                    ok = False
                    break
        return ok, checked

    maps = {
        "transpose (p,q)->(q,p)  [z->1/z]": lambda a, b: (b, a),
        "neg-p     (p,q)->(-p,q) [z->-z] ": lambda a, b: (-a, b),
        "neg-q     (p,q)->(p,-q) [z->-z] ": lambda a, b: (a, -b),
        "modular S (p,q)->(q,-p) [z->-1/z]": lambda a, b: (b, -a),
        "double-p  (p,q)->(2p,q) [z->2z] ": lambda a, b: (2 * a, b),
        "scale2    (p,q)->(2p,2q)[z->z]  ": lambda a, b: (2 * a, 2 * b),
        "scale-by-g g=primroot   [z->z]  ": None,  # filled below
        "shift     (p,q)->(p+q,q)[z->z+1]": lambda a, b: (a + b, b),
        "U: (p,q)->(p,p+q)       [z->z/(z+1)]": lambda a, b: (a, a + b),
    }
    # primitive-root scaling on BOTH coords leaves slope fixed -> should be invariant trivially.
    # primitive-root scaling on numerator only = doubling-like.
    print(f"  symmetry of S_P, P={P} (residue-pair invariance test):")
    for name, fn in maps.items():
        if fn is None:
            continue
        ok, ch = test_map(name, fn)
        print(f"     {name:38s}: invariant={ok}   ({ch} pairs checked)")
    # full automorphism: which F_P^* scalings of the NUMERATOR preserve S?
    # (scaling numerator p->c p with q fixed = the slope map z->c z)
    print(f"     -- slope-scaling z->c z, c in F_{P}^* (which c preserve S):")
    good_c = []
    for c in range(1, P):
        ok, ch = test_map(f"z->{c}z", lambda a, b, c=c: (c * a, b))
        if ok:
            good_c.append(c)
    print(f"        preserved by c in {good_c}  (out of 1..{P-1})")
    return good_c, val


# ----------------------------------------------------------------------
# (3) P^1(F_7) realization for P=7 + Klein-4 quotient orbit structure.
# ----------------------------------------------------------------------
def p1_F7_analysis(P, val):
    """Express S as a function of the slope z=p/q in P^1(F_P) (8 points for P=7),
    and report the orbits under <z->-z, z->1/z> (Klein 4-group) and PSL_2 pieces."""
    if P != 7:
        return
    print("  P^1(F_7) slope realization (z = p q^{-1} mod 7; q-residue invertible):")
    # for each residue pair with b!=0 invertible, slope z = a * inv(b)
    inv = {b: pow(b, -1, P) for b in range(1, P)}
    slope_val = {}
    for (a, b), v in val.items():
        if b % P == 0:
            z = "inf"
        else:
            z = (a * inv[b % P]) % P
        # S should depend only on z up to the quotient; collect
        slope_val.setdefault(z, set()).add(v)
    print("     slope z -> set of S values seen (if not singleton, S is NOT a pure")
    print("     function of the slope -> it needs the FULL P^1 quotient, not just z):")
    for z in sorted(slope_val, key=lambda x: (x == "inf", x)):
        print(f"        z={str(z):>4s}: S in {sorted(slope_val[z])}")
    # Klein-4 group on P^1(F_7): generated by sigma: z->-z and tau: z->1/z
    pts = list(range(P)) + ["inf"]

    def neg(z):
        return "inf" if z == "inf" else (-z) % P

    def inv_map(z):
        if z == "inf":
            return 0
        if z == 0:
            return "inf"
        return pow(z, -1, P)

    # build the group <neg, inv>
    def compose_orbit(z):
        seen = set()
        frontier = {z}
        while frontier:
            w = frontier.pop()
            if w in seen:
                continue
            seen.add(w)
            frontier.add(neg(w))
            frontier.add(inv_map(w))
        return frozenset(seen)

    orbits = set()
    for z in pts:
        orbits.add(compose_orbit(z))
    print(f"  orbits of P^1(F_7) under <z->-z, z->1/z> (Klein 4-grp):")
    for o in sorted(orbits, key=lambda s: (len(s), str(sorted(map(str, s))))):
        # pick S value of a representative if defined
        rep_vals = set()
        for z in o:
            if z in slope_val:
                rep_vals |= slope_val[z]
        print(f"     orbit {sorted(o, key=str)}  ->  S {sorted(rep_vals) if rep_vals else '(inf, q=0)'}")
    # the +- / inversion quotient maps z to the pair (||num||,||den||) up to swap
    print("  => the quotient P^1(F_7)/<+-,inv> has orbits indexed by the UNORDERED")
    print("     pair {||p||,||q||}; that is exactly the symmetry of the f-table.")


def main():
    print("=" * 78)
    print("THREAD A: modular / X(7) structure of the L7 residue discrepancy")
    print("=" * 78)

    primes = [3, 5, 7, 11, 13]
    freds = {}
    for P in primes:
        print(f"\n----- P = {P} -----")
        table, rowtable, n = build_residue_table(P, qmax=26)
        fred, half, consistent = reduce_to_norm(P, table)
        print(f"  residue classes filled: {len(table)} ; window ratios used: {n}")
        print(f"  S_P residue-only (each class a singleton): "
              f"{all(len(v) == 1 for v in table.values())}")
        print(f"  S_P factors through (||.||_P, ||.||_P): {consistent}")
        Smax = grid_print(P, fred)
        freds[P] = (fred, half, Smax)
        symmetry_report(P, table)
        if P == 7:
            _, val = symmetry_report(P, table) if False else (None, {
                (a, b): next(iter(s)) for (a, b), s in table.items() if len(s) == 1})
            p1_F7_analysis(P, val)

    # ---- (2) GENERAL-P LAW: search for uniform closed form of rowdef f_P(a,b) ----
    print("\n" + "=" * 78)
    print("(2) GENERAL-P LAW: uniform closed form for f_P(a,b)=S_P/P on a,b in 1..(P-1)/2")
    print("=" * 78)
    # The P=7 form (rowdef = S/7): f(a,b)= 0 if ab=0; ab+3 if a!=b; ab+4-2|a-2| if a=b.
    # Generalize candidate: rowdef = a*b + g(a,b,P).  Print rowdef and a*b and the
    # residual r = rowdef - a*b to see the structure.
    for P in primes:
        fred, half, Smax = freds[P]
        print(f"\n  P={P}: rowdef table and residual (rowdef - a*b) for a,b in 1..{half}:")
        print("      a  b  rowdef  a*b  resid")
        for a in range(1, half + 1):
            for b in range(1, half + 1):
                rd = fred.get((a, b), None)
                if rd is None:
                    continue
                print(f"     {a:2d} {b:2d}  {rd:5d}  {a*b:4d}  {rd - a*b:4d}")

    # uniform-formula hypothesis tests
    print("\n  --- testing uniform closed-form hypotheses ---")
    # Hypothesis A (diagonal vs off-diagonal split, P-dependent additive const):
    #   off-diagonal a!=b: rowdef = a*b + K(P)
    #   diagonal     a==b: rowdef = a*b + L(P) - 2|a - c(P)|   (P=7: K=3, L=4, c=2)
    for P in primes:
        fred, half, Smax = freds[P]
        # off-diagonal residuals
        offres = set()
        for a in range(1, half + 1):
            for b in range(1, half + 1):
                if a != b and (a, b) in fred:
                    offres.add(fred[(a, b)] - a * b)
        diag = {a: fred[(a, a)] - a * a for a in range(1, half + 1) if (a, a) in fred}
        print(f"   P={P}: off-diagonal (rowdef-a*b) values = {sorted(offres)}  "
              f"(uniform K?) ; diagonal (rowdef-a*a) by a = {diag}")
    print("\n  done.")


if __name__ == "__main__":
    main()
