#!/usr/bin/env python3
"""
claudebox-2026-06-03-S596 : rigidity IS orbit-type. Seeing everything as orbits of group actions
on the phase ring Z/n, and reading the LRC frontier off the orbit degeneracies.

Beyond local (fixed-point) and global (cascade) rigidity, this organizes ALL the repo's rigidities
as orbit-type statements of group actions, and finds the 2-adic seam where they all degenerate.

The phases of the runners live in Z/n. Three group actions act:
  <-1>  reflection (the witness symmetry, S593): orbits = ±-pairs {x, n-x}; fixed pts {x:2x=0}.
  <2>   doubling   (the binary phase dynamics, HYP-2117): orbits = cyclotomic cosets; degenerate
        (2-adic collapse) iff n even.
  (Z/n)* full dilation (G is dilation-invariant): orbits = the divisor-classes.

KEY UNIFICATION (verified below):
  * APEX = the SECOND fixed point n/2 of <-1>, which exists IFF n is even.
  * <2> is a permutation iff n is odd; it collapses (2-adic) iff n even — the SAME even-n condition.
  * EVEN n  <=>  <-1> gains the apex fixed point  AND  <2> degenerates  <=>  the hard LRC frontier.
  * Among odd n, "2 a primitive root" = ONE maximal mixing orbit on the units = the easiest/most
    ergodic ("fractal-regular") case.

RIGIDITY = ORBIT-TYPE dictionary (the taxonomy):
  fixed point (size-1 orbit) ........ LOCAL/pinning rigidity (apex)
  large free orbit .................. GLOBAL/cascade rigidity (±-pair); cure arity = orbit size
  large stabilizer (orbit-stab dual). witness-rigid (symmetric/tight); trivial stab = generic
  confined orbit closure ............ DYNAMICAL rigidity (rational/Lemma B) vs dense (Lemma A)
  invariant-fiber ................... SPECTRAL/determination rigidity (score- vs cycle-determined)
  <2>-orbit type .................... PHASE rigidity (mixing cycle vs 2-adic collapse = apex)
"""
from math import gcd

def closure_orbits(n, gens):
    """orbits of Z/n under the SUBGROUP of (Z/n)* generated by gens (units) — true group action."""
    seen = set(); orbs = []
    for x in range(n):
        if x in seen: continue
        orb = {x}
        stack = [x]
        while stack:
            y = stack.pop()
            for g in gens:
                z = (g * y) % n
                if z not in orb:
                    orb.add(z); stack.append(z)
        seen |= orb; orbs.append(sorted(orb))
    return orbs

def reflection_fixed(n):
    return [x for x in range(n) if (2 * x) % n == 0]   # x ≡ -x

def doubling_is_perm(n):
    return n % 2 == 1   # x->2x mod n is a bijection iff gcd(2,n)=1

def two_primitive_root(n):
    """is 2 a primitive root mod n (odd prime): <2> = all (n-1) units."""
    if n < 3 or n % 2 == 0: return False
    units = [u for u in range(1, n) if gcd(u, n) == 1]
    seen = set(); x = 1
    for _ in range(len(units)):
        x = (x * 2) % n; seen.add(x)
    return len(seen) == len(units)

def v2(n):
    e = 0
    while n % 2 == 0: n //= 2; e += 1
    return e

def main():
    print("=" * 96)
    print("S596  rigidity = orbit-type; the 2-adic seam unifies the apex, the doubling collapse")
    print("=" * 96)

    print("\n[1] THE REFLECTION <-1>: apex = the second fixed point n/2, exists IFF n even")
    print("  n | fixed pts of x->-x | #±-pairs | apex present?")
    for n in range(3, 19):
        fx = reflection_fixed(n)
        pairs = (n - len(fx)) // 2
        print(f"  {n:2d} | {str(fx):14s} | {pairs:7d}  | {'YES (apex='+str(n//2)+')' if n%2==0 else 'no'}")

    print("\n[2] THE DOUBLING <2>: permutation (odd) vs 2-adic collapse (even); mixing if 2 prim root")
    print("  n | n factored | doubling perm? | 2 prim root? | <2>-orbit sizes on units")
    for n in range(3, 25):
        units = [u for u in range(1, n) if gcd(u, n) == 1]
        # cyclotomic cosets of <2> on units (only meaningful when gcd(2,n)=1)
        if n % 2 == 1:
            seen = set(); sizes = []
            for u in units:
                if u in seen: continue
                orb = set(); x = u
                while x not in orb:
                    orb.add(x); x = (x * 2) % n
                seen |= orb; sizes.append(len(orb))
            sizes.sort(reverse=True)
        else:
            sizes = ['2-ADIC COLLAPSE']
        fac = []; m = n; p = 2
        while m > 1:
            e = 0
            while m % p == 0: m //= p; e += 1
            if e: fac.append(f'{p}^{e}' if e > 1 else f'{p}')
            p += 1
        print(f"  {n:2d} | {'·'.join(fac):8s} | {str(doubling_is_perm(n)):5s}          | "
              f"{str(two_primitive_root(n)):5s}        | {sizes}")

    print("\n[3] THE FRONTIER as orbit-degeneracy: classify n by (v2, odd-part-type)")
    print("  n | v2(n) | class | LRC reading")
    for n in [5, 7, 8, 10, 11, 13, 14, 16, 17, 18, 22, 23]:
        odd = n // (2 ** v2(n))
        if n % 2 == 1:
            cls = "ODD: 2-prim-root MAX-MIXING (easiest)" if two_primitive_root(n) else "ODD: <2> splits (cyclotomic cosets)"
        elif v2(n) == 1 and is_prime(odd):
            cls = "2·prime: APEX + single 2-collapse = HARD FRONTIER"
        else:
            cls = f"2^{v2(n)}·{odd}: deep 2-adic seam"
        print(f"  {n:2d} | {v2(n):4d}  | {cls}")

    print("\n[4] ORBIT-COUNT = a rigidity invariant (Burnside flavor): #orbits of <-1>, <2>, units")
    print("  n | #<-1>-orbits | #units-orbits | (orbit count drops as symmetry rises)")
    for n in range(3, 19):
        ro = len(closure_orbits(n, [(n - 1) % n]))
        units = [u for u in range(1, n) if gcd(u, n) == 1]
        uo = len(closure_orbits(n, units)) if units else 1
        print(f"  {n:2d} | {ro:11d}  | {uo:12d}")

def is_prime(m):
    if m < 2: return False
    d = 2
    while d * d <= m:
        if m % d == 0: return False
        d += 1
    return True

if __name__ == "__main__":
    main()
