#!/usr/bin/env python3
r"""
metagraph_rigid_towers_kps_S131b.py
(kind-pasteur-2026-07-26-S131b; companion to THM-2450)

THM-2444 left open: which classes are the rigid stratum (self-converse,
H = |Aut|) that carries the whole pure-blue count?  Answer verified
here: through n = 10 they are EXACTLY the classes generated by the
tower grammar

    T ::= 1  |  stack(T1, T2)  |  C3[T1, T2, T3]

(stack = transitive join, all arcs forward; C3 = three blocks arranged
cyclically).  For every n in 3..10 the grammar's rigid-SC classes
match the exhaustive blue-cube census of THM-2444 in count AND in the
multiset of H values: counts 2,1,2,2,3,3,5,4; H-multisets [1,3], [1],
[1,3], [1,9], [1,3,9], [1,9,9], [1,3,9,9,27], [1,9,9,9].

Universe: the full isomorphism-deduplicated grammar closure through
n = 10 (1; 1; 2; 4; 9; 24; 65; 182; 528; 1558 classes), each tested
exactly for H, |Aut|, and self-converseness.

Controls:
  * stack multiplicativity H(stack(A,B)) = H(A)H(B) and
    |Aut(stack(A,B))| = |Aut(A)||Aut(B)| verified exhaustively on all
    stack pairs with |A|+|B| <= 7;
  * hostile: the Paley circulant T_5 (quadratic-residue tournament,
    the unique NONRIGID pure-blue class per THM-2444) is verified to
    be (H,|Aut|) = (15,5) and NOT isomorphic to any grammar class --
    the grammar does not overgenerate into the nonrigid stratum;
  * census comparison is exact per n, hard failure on any mismatch.

Reproduction: python 04-computation/metagraph_rigid_towers_kps_S131b.py
"""
import sys
sys.setrecursionlimit(10000)

def stack(A, B):
    na, nb = len(A), len(B)
    n = na + nb
    M = [[0] * n for _ in range(n)]
    for i in range(na):
        Ai = A[i]
        Mi = M[i]
        for j in range(na):
            Mi[j] = Ai[j]
        for j in range(nb):
            Mi[na + j] = 1
    for i in range(nb):
        Bi = B[i]
        Mi = M[na + i]
        for j in range(nb):
            Mi[na + j] = Bi[j]
    return M

def c3(A, B, C):
    parts = [A, B, C]
    sizes = [len(p) for p in parts]
    off = [0, sizes[0], sizes[0] + sizes[1]]
    n = sum(sizes)
    M = [[0] * n for _ in range(n)]
    for b, P in enumerate(parts):
        for i in range(sizes[b]):
            for j in range(sizes[b]):
                M[off[b] + i][off[b] + j] = P[i][j]
    for b in range(3):
        nb = (b + 1) % 3
        for i in range(sizes[b]):
            for j in range(sizes[nb]):
                M[off[b] + i][off[nb] + j] = 1
    return M

def wl_colors(n, A, rounds=3):
    col = [sum(A[i]) for i in range(n)]
    for _ in range(rounds):
        nxt = []
        for i in range(n):
            outs = tuple(sorted(col[j] for j in range(n) if A[i][j]))
            ins = tuple(sorted(col[j] for j in range(n) if j != i and not A[i][j]))
            nxt.append(hash((col[i], outs, ins)))
        uniq = {c: k for k, c in enumerate(sorted(set(nxt)))}
        col = [uniq[c] for c in nxt]
    return col

def fingerprint(n, A):
    col = wl_colors(n, A)
    return (n, tuple(sorted(zip(col, [sum(A[i]) for i in range(n)]))))

def iso_map(n, A, B):
    ca, cb = wl_colors(n, A), wl_colors(n, B)
    if sorted(ca) != sorted(cb):
        return False
    cand = [[j for j in range(n) if cb[j] == ca[i]] for i in range(n)]
    order = sorted(range(n), key=lambda i: len(cand[i]))
    mapping = [-1] * n
    used = [False] * n
    def bt(k):
        if k == n:
            return True
        i = order[k]
        for j in cand[i]:
            if used[j]:
                continue
            ok = True
            for k2 in range(k):
                i2 = order[k2]
                if A[i][i2] != B[j][mapping[i2]] or A[i2][i] != B[mapping[i2]][j]:
                    ok = False
                    break
            if ok:
                mapping[i] = j; used[j] = True
                if bt(k + 1):
                    return True
                used[j] = False; mapping[i] = -1
        return False
    return bt(0)

def aut_size(n, A):
    col = wl_colors(n, A)
    cand = [[j for j in range(n) if col[j] == col[i]] for i in range(n)]
    order = sorted(range(n), key=lambda i: len(cand[i]))
    mapping = [-1] * n
    used = [False] * n
    cnt = 0
    def bt(k):
        nonlocal cnt
        if k == n:
            cnt += 1
            return
        i = order[k]
        for j in cand[i]:
            if used[j]:
                continue
            ok = True
            for k2 in range(k):
                i2 = order[k2]
                if A[i][i2] != A[j][mapping[i2]] or A[i2][i] != A[mapping[i2]][j]:
                    ok = False
                    break
            if ok:
                mapping[i] = j; used[j] = True
                bt(k + 1)
                used[j] = False; mapping[i] = -1
    bt(0)
    return cnt

def ham(n, A):
    full = (1 << n) - 1
    dp = [[0] * n for _ in range(1 << n)]
    for i in range(n):
        dp[1 << i][i] = 1
    for mask in range(1 << n):
        row = dp[mask]
        for last in range(n):
            c = row[last]
            if not c:
                continue
            Al = A[last]
            for nx in range(n):
                if Al[nx] and not (mask >> nx) & 1:
                    dp[mask | (1 << nx)][nx] += c
    return sum(dp[full][i] for i in range(n))

def is_sc(n, A):
    Aop = [[A[j][i] for j in range(n)] for i in range(n)]
    return iso_map(n, A, Aop)

N = 10
gen = {1: [[[0]]]}
for n in range(2, N + 1):
    buckets = {}
    out = []
    def add(M):
        fp = fingerprint(n, M)
        lst = buckets.setdefault(fp, [])
        for X in lst:
            if iso_map(n, M, X):
                return
        lst.append(M)
        out.append(M)
    for a in range(1, n):
        for A in gen[a]:
            for B in gen[n - a]:
                add(stack(A, B))
    for a in range(1, n - 1):
        for b in range(1, n - a):
            c = n - a - b
            if c < 1:
                continue
            for A in gen[a]:
                for B in gen[b]:
                    for C in gen[c]:
                        add(c3(A, B, C))
    gen[n] = out
    print(f"n={n}: grammar classes {len(out)}", flush=True)

def fail(msg):
    raise SystemExit("CHECK FAILED: " + msg)

# ---- control 1: stack multiplicativity, exhaustive |A|+|B| <= 7 ----
mult_checks = 0
for na in range(1, 7):
    for nb in range(1, 8 - na):
        for A in gen[na]:
            for B in gen[nb]:
                S = stack(A, B)
                n = na + nb
                if ham(n, S) != ham(na, A) * ham(nb, B):
                    fail("H stack multiplicativity")
                if aut_size(n, S) != aut_size(na, A) * aut_size(nb, B):
                    fail("Aut stack multiplicativity")
                mult_checks += 1
print(f"control: stack multiplicativity on {mult_checks} pairs: PASS", flush=True)

# ---- control 2: Paley T5 is nonrigid and outside the grammar ----
T5 = [[1 if (j - i) % 5 in (1, 2) else 0 for j in range(5)] for i in range(5)]
h5, a5 = ham(5, T5), aut_size(5, T5)
if (h5, a5) != (15, 5):
    fail(f"T5 invariants wrong: {(h5, a5)}")
if any(iso_map(5, T5, M) for M in gen[5]):
    fail("T5 unexpectedly inside the tower grammar")
print("control: Paley T5 = (H,|Aut|) = (15,5), outside grammar: PASS", flush=True)

OBS = {3: 2, 4: 1, 5: 2, 6: 2, 7: 3, 8: 3, 9: 5, 10: 4}
OBS_H = {3: [1, 3], 4: [1], 5: [1, 3], 6: [1, 9], 7: [1, 3, 9],
         8: [1, 9, 9], 9: [1, 3, 9, 9, 27], 10: [1, 9, 9, 9]}
mismatch = False
for n in range(3, N + 1):
    rig = []
    for M in gen[n]:
        H = ham(n, M)
        if H > 100:          # observed rigid H are powers of 3 <= 27; cheap gate
            continue
        au = aut_size(n, M)
        if H == au and is_sc(n, M):
            rig.append(H)
    rig.sort()
    ok = (len(rig) == OBS[n]) and (rig == OBS_H[n])
    if not ok:
        mismatch = True
    match = "MATCH" if ok else f"MISMATCH (census {OBS[n]} {OBS_H[n]})"
    print(f"n={n}: rigid-SC in grammar = {len(rig)} {rig} {match}", flush=True)
if mismatch:
    fail("grammar/census mismatch")
print("ALL CHECKS PASSED", flush=True)
