"""
Final synthesis: the metallic mean M_n - 1 and tournament constraint geometry.

ESTABLISHED FACTS:
1. x_n = (n-2+√(n²+4))/2 = M_n - 1 satisfies x² = (n-2)x + n
2. [[n-2, n], [1, 0]] has eigenvalues x_n and -n/x_n
3. For transitive tournament: C^T C = n · P (P = projection onto rank-E-(n-1) subspace)
4. max_rank / C(n,3) = 3/n exactly
5. Dependencies indexed by 4-vertex subsets = simplicial 3-chains
6. THM-217 transfer matrix factors via metallic mean ONLY at n=6

NEW TEST: The "defect propagation operator."

When we remove one transitive triple (make it cyclic), the rank MIGHT drop.
The question: given the first triple is cyclic, how many OTHER triples become
"effectively independent" of the remaining constraints?

This propagation could follow a_{k+1} = (n-2)a_k + n·a_{k-1} if:
- n-2 = number of triples sharing 2 vertices with the removed triple  
- n = total vertex count (governs "restart" from disjoint region)
"""
import numpy as np
from math import comb

# How many triples share exactly 2 vertices with a given triple {a,b,c}?
# Another triple {a,b,d} for d ∉ {a,b,c}: there are n-3 choices for d,
# and 3 ways to pick which 2 of {a,b,c} to keep. So 3(n-3) triples share 2 vertices.
# Of these, some share the SAME pair, giving overlapping constraints.

for n in range(4, 10):
    shared_2 = 3*(n-3)  # triples sharing 2 vertices with a given triple
    shared_1 = 3*comb(n-3, 2)  # triples sharing 1 vertex
    shared_0 = comb(n-3, 3)  # disjoint triples
    total = comb(n,3) - 1  # other triples
    print(f"n={n}: shared_2={shared_2}, shared_1={shared_1}, shared_0={shared_0}, total={total}")
    print(f"  shared_2/(n-2) = {shared_2/(n-2):.3f}")
    print(f"  shared_2 + shared_0 = {shared_2 + shared_0}")
    
    x_n = (n-2 + np.sqrt(n**2 + 4)) / 2
    print(f"  x_n = {x_n:.4f}")

# At n=6: shared_2 = 9, shared_1 = 9, shared_0 = 1. 
# Interesting: shared_2 = 9 = C(n,2) - n + 1 = the target rank at n=6? No, target rank = 10.

# KEY: shared_2 = 3(n-3) and the number of independent constraints among them
# Each pair {a,b} from the original triple contributes n-3 triples.
# Within pair {a,b}'s triples: {a,b,d} for d = 1,...,n-3.
# These are all independent of each other (different "d" means different constraint).
# But there are dependencies ACROSS pairs.

# Actually, let me think about the MATROID structure.
# If we remove the constraint for triple τ₀ = {a,b,c} from C,
# does rank drop? It drops iff τ₀'s row is NOT in the span of other rows.

# From the simplicial structure: the dependencies are generated by 4-subsets.
# Triple τ₀ = {a,b,c} appears in 3-chains for each 4-subset containing it.
# There are n-3 such 4-subsets: {a,b,c,d} for d ∉ {a,b,c}.
# Each gives a dependency: τ₀ ~ τ₁ + τ₂ - τ₃ (alternating sum of the other 3 triples).

# So τ₀ IS in the span of other rows (via any of the n-3 dependency relations).
# This means removing ONE constraint NEVER drops the rank in the transitive tournament.

# But for a general tournament, some of the other triples in the dependency 
# relation might ALSO be cyclic. Then the relation doesn't help.

# Critical question: can ALL n-3 dependency relations for τ₀ be broken?
# Relation for 4-subset {a,b,c,d}: τ₀ = {a,b,c}, τ₁ = {a,b,d}, τ₂ = {a,c,d}, τ₃ = {b,c,d}
# For the relation to be "broken," at least one of τ₁, τ₂, τ₃ must be cyclic.
# For ALL n-3 relations to be broken: for each d, at least one of 
# {a,b,d}, {a,c,d}, {b,c,d} is cyclic.

print("\n=== For rank to drop when removing one TT constraint ===")
print("Need: for EVERY d ∉ {a,b,c}, at least one of")
print("  {a,b,d}, {a,c,d}, {b,c,d} is cyclic.")
print("This means d cannot be 'fully transitive' with all pairs from {a,b,c}.")
print()

# At n=5: need this for d ∈ {one vertex}. So ONE of {a,b,d}, {a,c,d}, {b,c,d} cyclic.
# This is easy to satisfy.
# At n=6: need it for d ∈ {two vertices d₁, d₂}. Both d₁ and d₂ must each have
# at least one cyclic triple with a pair from {a,b,c}.
# Still pretty easy.

# The hard part is: even when all direct dependency relations are broken,
# INDIRECT dependencies through chains of relations might still hold.
# The rank drops only if the row is not in the span of ALL other rows,
# not just not in the direct dependency relations.

# This suggests a CONNECTION to connectivity in the "dependency graph":
# vertices = transitive triples of T, edges = pairs sharing a 4-subset.
# If this graph is connected and includes enough constraints, rank is maintained.

# THE METALLIC MEAN HYPOTHESIS:
# The spectral gap of this dependency graph governs the probability of rank drop.
# The dependency graph for a random tournament has expected degree 3(n-3)·(3/4)
# (each shared-2-vertex triple is transitive with prob 3/4).

print("\n=== Dependency graph expected degree ===")
for n in range(4, 12):
    shared_2 = 3*(n-3)
    # Each shared triple is present (transitive) with prob 3/4
    exp_degree = shared_2 * 3/4
    x_n = (n-2 + np.sqrt(n**2 + 4)) / 2
    print(f"n={n}: shared_2={shared_2}, E[degree]={exp_degree:.1f}, "
          f"x_n={x_n:.3f}, E[degree]/x_n={exp_degree/x_n:.4f}")

# Hmm, E[degree]/x_n doesn't converge to anything clean.

# Let me try a COMPLETELY different angle.
# What if x_n appears in the RECURRENCE for dim(Ω_k)?

# For the QR_p tournament (p prime ≡ 3 mod 4):
# Score sequence is regular: every vertex has out-degree (p-1)/2.
# The number of transitive k-subsets follows a specific pattern.

# For QR_7 (Paley tournament on 7 vertices):
# Known: β₃ = 1, β₁ = 0 (from our data)
# Ω dims?

import sys
sys.path.insert(0, '04-computation')

# Build QR_7
n = 7
qr = set()
for i in range(1, n):
    qr.add((i*i) % n)
print(f"\nQR residues mod {n}: {sorted(qr)}")

adj = [[0]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        if i != j and ((j-i) % n) in qr:
            adj[i][j] = 1

# Count transitive sub-tournaments of each size
for size in range(2, n+1):
    from itertools import combinations
    count = 0
    for subset in combinations(range(n), size):
        # Check if it's a transitive tournament
        transitive = True
        # Need: there's a total order consistent with the edges
        # Equivalent: no 3-cycle in the subtournament
        for a, b, c in combinations(subset, 3):
            if adj[a][b] and adj[b][c] and adj[c][a]:
                transitive = False
                break
            if adj[a][c] and adj[c][b] and adj[b][a]:
                transitive = False
                break
        if transitive:
            count += 1
    print(f"QR_7: transitive {size}-subsets (Ω_{size-1}): {count}")

# Check the recurrence: Ω_{k+1} = (n-2)·Ω_k + n·Ω_{k-1}?
print()
omega_7 = []  # Will collect from the loop above

# Also compute for transitive T_7
print("\nTransitive T_7: Ω_k = C(7,k+1)")
for k in range(7):
    print(f"  Ω_{k} = C(7,{k+1}) = {comb(7,k+1)}")

# GOLDEN RATIO AT n=4:
# x_4 = 1+√5 = 2φ ≈ 3.236
# Does this appear anywhere at n=4?
print(f"\n=== Special values ===")
print(f"n=4: x = 1+√5 = 2φ = {1+np.sqrt(5):.6f}")
print(f"  φ = {(1+np.sqrt(5))/2:.6f}")
print(f"  This is the 'golden rectangle' ratio in a different guise")
print(f"  x² = 2x + 4 → x(x-2) = 4 → (excess)·(capacity) = (vertices)")
print()
print(f"n=5: x = (3+√29)/2 = {(3+np.sqrt(29))/2:.6f}")
print(f"  x² = 3x + 5 → x(x-3) = 5")
print()
print(f"n=6: x = 2+√10 = {2+np.sqrt(10):.6f}")
print(f"  x² = 4x + 6 → x(x-4) = 6")
print(f"  UNIQUE: factors THM-217 transfer matrix at x=18")
print()

# The equation x(x-(n-2)) = n has a beautiful interpretation:
# "The product of a quantity and its excess over the free dimension equals the total vertices."
# Free dimension = n-2 = number of vertices NOT endpoints of a fixed edge.

# In constraint propagation terms:
# x = propagation rate
# x - (n-2) = excess propagation beyond the "one hop" reach
# n = total system size
# Balance: propagation × excess = system size

# This means: if propagation rate < n-2, excess is negative, 
# and we can't cover the whole system → rank drops → β₁ = 1.
# If propagation rate > n-2, excess is positive → full coverage → β₁ = 0.
# The CRITICAL rate is x_n, at which propagation EXACTLY balances.

print("=== INTERPRETATION ===")
print("""
x(x-(n-2)) = n

CONSTRAINT PROPAGATION MODEL:
- Start with one known edge value h(a,b)
- Propagation rate per step: each known edge determines ~x new edge values
  via transitive triple constraints
- "Free reach" per step: x - (n-2) beyond the immediate neighborhood
- Total system size: n vertices
- BALANCE CONDITION: x·(x-(n-2)) = n

At the critical rate x_n:
- If effective propagation > x_n: system is over-determined → rank maximal → β₁=0
- If effective propagation < x_n: system under-determined → rank deficient → β₁=1

The FRACTION of β₁=1 tournaments depends on how often the 
random tournament's constraint structure falls below this threshold.
""")

# VERIFICATION: at n=4, x=1+√5≈3.24. 
# A 4-tournament has 6 edges. Constraint propagation from one edge:
# edge (a,b) participates in n-2=2 transitive triples (if both triples are transitive).
# So from 1 edge, we get 2 more edge values.
# Then from those 2, we get up to 2×2=4 more...
# But the system only has 6 edges total and rank target is 2.
# Growth rate 3.24 > n-2 = 2, so typically overcomes.

# At n=3, x≈2.30. n-2=1. x(x-1)=2.30·1.30=3≈n. 
# From 1 edge, propagation rate ~2.30. Only need rank 1.
# But 1/4 of tournaments are pure 3-cycles (no transitive triples) → β₁=1.

# Key question: does Pr[β₁=1] → 0 as n → ∞?
# Answer: YES, because the constraint redundancy ratio (n-3)/n → 1.
# Even with 1/4 of triples being cyclic, the remaining 3/4 give enough constraints.
# The metallic mean governs the RATE of this convergence.

print("=== Convergence rate ===")
for n in range(3, 20):
    # Prob all n-3 dependency relations for a random triple are "broken"
    # Each relation needs at least 1 of 3 specific triples to be cyclic
    # P(at least 1 cyclic) = 1 - (3/4)³ = 1 - 27/64 = 37/64 ≈ 0.578
    # P(all n-3 broken) ≈ (37/64)^(n-3) 
    p_all_broken = (37/64)**(n-3)
    x_n = (n-2 + np.sqrt(n**2 + 4)) / 2
    # But this is too crude. More refined:
    # P(relation d broken) = 1 - P(all 3 triples transitive)
    # The 3 triples sharing the pair: not independent since they share edges.
    # Crude: P(each is transitive) = 3/4, independence ≈ P(all 3) = (3/4)³ = 27/64
    # P(not all broken) = 1 - P(all broken) ≈ 1 - (37/64)^(n-3)
    # For large n, P(β₁=1 for this triple's row) ≈ (37/64)^(n-3)
    # Since we need ANY row to cause rank drop, and there are ~C(n,3)/4 cyclic triples:
    # P(β₁=1) ~ C(n,3)/4 · (37/64)^(n-3) 
    p_beta1_crude = comb(n,3)/4 * (37/64)**(n-3)
    print(f"n={n}: P(β₁=1)_crude ≈ {min(p_beta1_crude, 1):.6f}, "
          f"1/x_n = {1/x_n:.6f}")

