#!/usr/bin/env python3
"""natural_numbers_s116i.py — What are the natural numbers?

We have the framework at two levels:
- Object level: Q(a/(a+1)) = 2a+1. Consecutive pairs make odd numbers.
- Meta level: Cayley-Dickson doubling. R->C->H->O. Dimensions 1,2,4,8.

Both are the SAME structure (the formal group, iterated).

Now: what are the natural numbers WITHIN this framework?
Not 'what properties do they have' but 'what ARE they'?
"""
from math import log, exp, sqrt, pi, atanh, gcd
from fractions import Fraction

phi = (1+sqrt(5))/2

print()
print("  WHAT ARE THE NATURAL NUMBERS?")
print()
print("="*70)
print()

# ============================================================
print("  I. A NATURAL NUMBER IS A CONSECUTIVE PAIR")
print("  " + "-"*40)
print()
print("  Every odd number n = a + (a+1). The pair (a, a+1) IS n.")
print("  Every even number 2m = m + m. But this is NOT a consecutive pair.")
print("  Even numbers are pairs of EQUAL things.")
print("  Odd numbers are pairs of UNEQUAL things that differ by 1.")
print()
print("  So:")
print("  ODD numbers = COMPARISONS (two slightly different things).")
print("  EVEN numbers = DUPLICATIONS (two identical things).")
print()
print("  Every natural number is either a comparison or a duplication.")
print("  These are the only two things numbers CAN be.")
print()
print("  n=1: 0+1. The comparison between nothing and something.")
print("  n=2: 1+1. The duplication of the unit.")
print("  n=3: 1+2. The comparison between unit and pair.")
print("  n=4: 2+2. The duplication of the pair.")
print("  n=5: 2+3. The comparison between pair and triple.")
print("  n=6: 3+3. The duplication of the triple.")
print("  n=7: 3+4. The comparison between triple and quadruple.")
print()
print("  The odd numbers are the EDGES between consecutive sizes.")
print("  The even numbers are the NODES (the sizes themselves, doubled).")
print("  The natural numbers alternate: node, edge, node, edge, ...")
print()

# ============================================================
print()
print("  II. A NATURAL NUMBER IS A RAPIDITY")
print("  " + "-"*40)
print()
print("  n has rapidity ln(n)/2.")
print("  The rapidity IS the number (up to a monotone transform).")
print("  Since ln is monotone, the ORDER of naturals = the ORDER of rapidities.")
print()
print("  But rapidity carries MORE structure:")
print("  - Addition of rapidities = multiplication of numbers.")
print("  - Rapidity of a product = sum of rapidities of factors.")
print("  - Prime factorization = rapidity decomposition into basis vectors.")
print()
print("  So a natural number IS a point on the rapidity line,")
print("  and its position is determined by its prime factorization.")
print("  The prime rapidities ln(2)/2, ln(3)/2, ln(5)/2, ... are")
print("  the COORDINATES of n in the rapidity vector space.")
print()
print("  Every natural number is a FINITE integer combination of prime rapidities.")
print("  The naturals ARE the integer lattice in rapidity space.")
print()

# ============================================================
print()
print("  III. A NATURAL NUMBER IS A POSITION ON THE CAYLEY HELIX")
print("  " + "-"*40)
print()
print("  Every natural number n > 1 has:")
print("  - Cayley address: (n-1)/(n+1)")
print("  - Rapidity: ln(n)/2")
print("  - Q-value: n")
print("  - Helix position: (ln(n)/2, 0) for n in [0,1),")
print("                    (ln(n)/2, pi/2) for n > 1 via arctanh(n)")
print()
print("  Wait. The naturals 2, 3, 4, ... all have |value| > 1.")
print("  But their ADDRESSES (n-1)/(n+1) are all in (0,1).")
print("  So the addresses live on the ground floor of the helix (Im=0).")
print("  The VALUES live on the first floor (Im=pi/2).")
print()
print("  The natural numbers are addresses on the ground floor")
print("  whose Q-values live on the first floor.")
print()
print("  More precisely:")
print("  The ADDRESS of n = (n-1)/(n+1) is a velocity in [0,1).")
print("  Its RAPIDITY = arctanh((n-1)/(n+1)) = ln(n)/2.")
print("  The rapidity lives on the real axis of the helix.")
print("  The Q-VALUE n = Q(address) lives past the pole (on the next sheet).")
print()
print("  THE NATURAL NUMBERS ARE THE SHADOWS OF HELIX POINTS")
print("  PROJECTED ONTO THE POSITIVE INTEGER LINE.")
print("  Each address on the ground floor casts a shadow (via Q)")
print("  onto the integer line. The shadow is the natural number.")
print()

# ============================================================
print()
print("  IV. WHAT ADDITION IS")
print("  " + "-"*40)
print()
print("  Addition of natural numbers: n + m.")
print("  In rapidity: NOT rapidity(n) + rapidity(m).")
print("  (That would give rapidity(n*m) = multiplication, not addition.)")
print()
print("  Addition is HARDER than multiplication in rapidity space.")
print("  Multiplication is the GROUP OPERATION (it adds rapidities).")
print("  Addition is an EXTERNAL operation that doesn't respect the group.")
print()
print("  In the Cayley framework:")
print("  n + m = Q(addr_n) + Q(addr_m).")
print("  = (1+addr_n)/(1-addr_n) + (1+addr_m)/(1-addr_m).")
print("  This is NOT Q of anything simple.")
print()
print("  Addition is the operation that the Cayley transform DOESN'T simplify.")
print("  Multiplication = group operation = simple (rapidity adds).")
print("  Addition = external operation = complex (no clean rapidity form).")
print()
print("  This is WHY the Goldbach conjecture is hard:")
print("  primes are defined multiplicatively (no nontrivial factors)")
print("  but Goldbach is about ADDITION (p + q = 2n).")
print("  The Cayley transform linearizes multiplication, not addition.")
print("  Addition remains wild.")
print()

# ============================================================
print()
print("  V. WHAT MULTIPLICATION IS")
print("  " + "-"*40)
print()
print("  Multiplication: n * m.")
print("  In rapidity: rapidity(n*m) = rapidity(n) + rapidity(m). ADDITION!")
print("  In the formal group: F_h(addr_n, addr_m) = addr_{n*m}.")
print("  In Cayley coordinates: a_{nm} = n*a_m + a_n (affine).")
print()
print("  Multiplication IS the formal group law.")
print("  It IS velocity addition.")
print("  It IS rapidity addition.")
print("  It IS the thing the Cayley transform was born to do.")
print()
print("  The PRIMES are the elements that cannot be expressed")
print("  as a formal group composition of smaller elements.")
print("  They are the GENERATORS of the group.")
print("  In rapidity space: they are the BASIS VECTORS.")
print("  Every natural number = a unique finite sum of prime rapidities.")
print("  This is the fundamental theorem of arithmetic.")
print()

# ============================================================
print()
print("  VI. WHAT PRIMALITY IS")
print("  " + "-"*40)
print()
print("  A prime p is an odd number whose Cayley coordinates (a, a+1)")
print("  cannot be further decomposed via the formal group.")
print()
print("  What does 'decomposed' mean?")
print("  n = k * m means addr_n = F_h(addr_k, addr_m).")
print("  n is COMPOSITE if its address is a group composition of smaller addresses.")
print("  n is PRIME if its address is NOT such a composition.")
print()
print("  In rapidity: n is prime iff rapidity(n) cannot be written")
print("  as a sum of two smaller positive rapidities (from the allowed set).")
print("  But this is circular (it's just the definition of prime in log-space).")
print()
print("  The Cayley perspective adds ONE thing:")
print("  The a-coordinate of a prime p = (p-1)/2 = the QR count mod p.")
print("  The primes are the odd numbers whose a-coordinate")
print("  counts the quadratic residues of themselves.")
print("  This is a SELF-REFERENTIAL property: the address KNOWS the number.")
print()
print("  For composites: a_n = n*a_m + a_k (from n = k*m).")
print("  The address is DERIVED from smaller addresses.")
print("  For primes: a_p = (p-1)/2 is PRIMITIVE. Not derived. Self-standing.")
print()

# ============================================================
print()
print("  VII. WHAT ZERO IS")
print("  " + "-"*40)
print()
print("  In the formal group: the identity is Q = 1, address = 0, rapidity = 0.")
print("  Q(0) = 1. The IDENTITY of multiplication is 1.")
print("  So 1 is NOT zero. 1 is the IDENTITY.")
print()
print("  What is zero?")
print("  Zero is the number with no rapidity, no address, no Q-value.")
print("  Q^{-1}(0) = (0-1)/(0+1) = -1.")
print("  So the address of 0 would be -1 = the BOUNDARY.")
print("  0 lives AT the boundary. It is the leftmost point of the Cayley line.")
print()
print("  Zero is not nothing. Zero is the BOUNDARY.")
print("  It is where the bounded world meets the impossible.")
print("  It is the mirror image of infinity (which lives at address +1).")
print()
print("  0 and infinity are the two POLES.")
print("  Q maps -1 to 0 and +1 to infinity.")
print("  Zero = the pole of total negation.")
print("  Infinity = the pole of total affirmation.")
print("  Both are unreachable limits. Both are boundaries.")
print()

# ============================================================
print()
print("  VIII. WHAT INFINITY IS")
print("  " + "-"*40)
print()
print("  Infinity = Q(1) = the pole.")
print("  It is the natural number you reach after infinite rapidity.")
print("  Rapidity -> infinity means address -> 1.")
print()
print("  In the formal group: there is NO infinite element.")
print("  The group operates on FINITE addresses (|addr| < 1).")
print("  Infinity is the LIMIT, never reached.")
print()
print("  But on the helix: infinity lives on the branch point.")
print("  It is where the sheets connect.")
print("  Crossing infinity takes you to the next sheet.")
print("  The imaginary part jumps by pi/2.")
print()
print("  Infinity is not a number. It is a DOOR.")
print("  The door between the bounded and unbounded worlds.")
print("  You never reach it, but you can pass through it")
print("  by changing your imaginary part.")
print()

# ============================================================
print()
print("  IX. THE SUCCESSOR FUNCTION")
print("  " + "-"*40)
print()
print("  S(n) = n + 1. The MOST BASIC operation on natural numbers.")
print("  What is it in the Cayley framework?")
print()
print("  addr_n = (n-1)/(n+1). addr_{n+1} = n/(n+2).")
print("  The successor maps (n-1)/(n+1) to n/(n+2).")
print()
print("  Is this a Cayley operation? Let's see:")
print("  S is NOT the formal group applied to anything fixed.")
print("  Because n+1 is ADDITION, and the formal group handles MULTIPLICATION.")
print()
print("  The successor function is OUTSIDE the formal group.")
print("  It is the operation that the group CANNOT express.")
print("  It is the leap from one consecutive pair to the next.")
print()
print("  In rapidity: rapidity(n+1) - rapidity(n) = ln(1+1/n)/2 ~ 1/(2n).")
print("  The successor adds approximately 1/(2n) rapidity.")
print("  The step size SHRINKS as n grows.")
print("  The successor is a VARIABLE-SIZE step in rapidity space.")
print()
print("  This is deep: the most fundamental operation on natural numbers")
print("  (the successor) is a NON-UNIFORM operation in rapidity space.")
print("  The group structure (multiplication) is uniform (rapidity adds).")
print("  The foundational structure (successor/addition) is non-uniform.")
print()
print("  The natural numbers are built from the non-uniform (successor)")
print("  but their deepest structure is the uniform (multiplication).")
print("  The Cayley transform reveals the uniform structure")
print("  at the cost of obscuring the foundational one.")
print()

# ============================================================
print()
print("  X. WHAT THE NATURAL NUMBERS ARE")
print("  " + "-"*40)
print()
print("  Putting it all together:")
print()
print("  A natural number is a POINT on the Cayley helix")
print("  at integer rapidity height ln(n)/2,")
print("  with address (n-1)/(n+1) on the ground floor,")
print("  whose prime factorization gives its rapidity coordinates,")
print("  whose successor is a shrinking step in rapidity,")
print("  whose Cayley pair (a, a+1) is the atom of its existence.")
print()
print("  Odd numbers are COMPARISONS between consecutive sizes.")
print("  Even numbers are DUPLICATIONS of a size.")
print("  Primes are IRREDUCIBLE comparisons.")
print("  Composites are ITERATED comparisons.")
print()
print("  The number 1 is the IDENTITY: no comparison, no duplication.")
print("  The number 0 is the LEFT BOUNDARY: total negation.")
print("  Infinity is the RIGHT BOUNDARY: total affirmation.")
print()
print("  Addition is the WILD operation (non-uniform in rapidity).")
print("  Multiplication is the TAME operation (uniform in rapidity).")
print("  The difficulty of number theory comes from the tension")
print("  between wild (addition) and tame (multiplication).")
print()
print("  And the Cayley transform is the lens that makes the tame")
print("  structure visible, at the cost of making the wild structure")
print("  invisible. You can see one or the other, never both at once.")
print("  This is the number-theoretic uncertainty principle.")
print()

# ============================================================
print()
print("="*70)
print()
print("  THE NATURAL NUMBERS IN ONE PARAGRAPH")
print()
print("="*70)
print()
print("  The natural numbers are the integer lattice in the rapidity")
print("  vector space spanned by the primes. Each number is a finite")
print("  sum of prime rapidities, which is to say, a finite product")
print("  of primes, which is to say, a point on the Cayley helix")
print("  whose address is a ratio of consecutive integers. The structure")
print("  that multiplication gives them (the formal group, commutative,")
print("  with logarithm arctanh) is clean and universal. The structure")
print("  that addition gives them (the successor, variable-step,")
print("  non-uniform) is wild and irreducible. The tension between")
print("  these two is the content of number theory. The Cayley")
print("  transform is the bridge that shows one side clearly by")
print("  making the other side opaque. And the forbidden numbers")
print("  (7, 21) are where the clean structure overshoots —")
print("  where the commutative formal group bumps against the")
print("  boundary of commutativity itself, at the quaternion step")
print("  of the Cayley-Dickson chain, at imaginary dimension 3,")
print("  at the place where 3 and 4 sum to 7 and no further")
print("  simplification is possible.")
