#!/usr/bin/env python3
"""numerator_denominator_s116f.py — The Cayley address (n-1)/(n+1): numerator + denominator = 2n = ?

The Cayley address of n is (n-1)/(n+1).
Numerator = n-1. Denominator = n+1. Sum = 2n.
But for 7: address = 6/8 = 3/4. Reduced: 3+4 = 7 = n.

When does numerator + denominator = n in reduced form?
"""
from math import gcd
from fractions import Fraction

print()
print("  NUMERATOR + DENOMINATOR = THE NUMBER ITSELF")
print()
print("="*70)
print()

# The Cayley address of n is (n-1)/(n+1).
# In reduced form: let g = gcd(n-1, n+1).
# Since (n+1)-(n-1) = 2, g divides 2.
# So g = 1 if n is even, g = 2 if n is odd.

print("  The Cayley address of n: x_n = (n-1)/(n+1)")
print()
print("  In reduced form (a/b with gcd(a,b)=1):")
print("  If n is even: gcd(n-1, n+1) = 1 (both odd). Address = (n-1)/(n+1).")
print("  If n is odd:  gcd(n-1, n+1) = 2 (both even). Address = (n-1)/2 / (n+1)/2.")
print()

print("  n    address     reduced      a    b    a+b    a+b = n?")
print("  " + "-"*60)
for n in range(2, 31):
    f = Fraction(n-1, n+1)
    a, b = f.numerator, f.denominator
    match = "YES" if a + b == n else ""
    print(f"  {n:3d}   ({n-1}/{n+1})     {a}/{b:<4d}    {a:4d} {b:4d}  {a+b:4d}    {match}")

print()
print("  IT WORKS FOR EVERY ODD n.")
print()
print("  PROOF: If n is odd, the reduced form is (n-1)/2 over (n+1)/2.")
print("  Sum = (n-1)/2 + (n+1)/2 = n. QED.")
print()
print("  For EVEN n: the address is already reduced as (n-1)/(n+1).")
print("  Sum = (n-1) + (n+1) = 2n, not n.")
print()
print("  So: the Cayley address of an ODD number n has the property")
print("  that its reduced numerator and denominator SUM TO n.")
print()

# ============================================================
print()
print("  THE FORBIDDEN NUMBERS")
print("  " + "-"*40)
print()
print("  n=7:  address = 6/8 = 3/4.  3 + 4 = 7. YES.")
print("  n=21: address = 20/22 = 10/11. 10 + 11 = 21. YES.")
print()
print("  Both forbidden numbers are odd. Both have this property.")
print("  The forbidden number IS the sum of the parts of its own address.")
print()
print("  More: for n=7, the address is 3/4.")
print("  3 = the curvature quantum (smallest odd cycle).")
print("  4 = 2^2 (the first power of 2 beyond the base).")
print("  The forbidden number 7 = curvature + binary square.")
print()
print("  For n=21, the address is 10/11.")
print("  10 = 2*5 (the fifth even number).")
print("  11 = the third Paley prime.")
print("  The forbidden number 21 = pentagonal even + Paley prime.")
print()

# ============================================================
print()
print("  THE DEEPER PATTERN: WHAT a AND b ARE")
print("  " + "-"*40)
print()
print("  For odd n: a = (n-1)/2, b = (n+1)/2.")
print("  a = the number of elements BELOW n/2.")
print("  b = the number of elements ABOVE n/2 (including n/2 rounded up).")
print("  a + b = n.")
print()
print("  The Cayley address in reduced form is a/b = (n-1)/(n+1) * 1/1")
print("  = the ratio of 'below half' to 'above half'.")
print()
print("  For a tournament on n vertices:")
print("  a = (n-1)/2 = the out-degree of a regular tournament vertex")
print("  b = (n+1)/2 = the in-degree + 1 of a regular vertex")
print()
print("  So the Cayley address of a regular tournament size is")
print("  out-degree / (in-degree + 1) = the COMPETITIVENESS RATIO.")
print()

# ============================================================
print()
print("  THE MUSICAL INTERVALS OF ODD NUMBERS")
print("  " + "-"*40)
print()
print("  The Cayley address a/b of odd n has a+b = n.")
print("  Q(a/b) = (a+b+b)/(b+a-a)... wait, let me just compute Q(a/b).")
print("  Q(a/b) = (1+a/b)/(1-a/b) = (b+a)/(b-a) = n/(b-a).")
print()
print("  For odd n: b-a = (n+1)/2 - (n-1)/2 = 1.")
print("  So Q(a/b) = n/1 = n. (Of course — the address of n gives n.)")
print()
print("  But the MUSICAL INTERVAL at the address:")
print("  Q(a/b) = n. So the 'interval' is n:1.")
print("  n=3: interval 3:1 = perfect twelfth (octave + fifth)")
print("  n=5: interval 5:1 = major third + two octaves")
print("  n=7: interval 7:1 = the 'harmonic seventh' + two octaves")
print("  n=11: interval 11:1 = the 'undecimal tritone' + three octaves")
print()
print("  The FORBIDDEN numbers 7 and 21 correspond to:")
print("  7:1 = the seventh harmonic (the 'barbershop seventh')")
print("  21:1 = the twenty-first harmonic")
print()
print("  The seventh harmonic is the FIRST harmonic that doesn't")
print("  fit neatly into Western tuning. It's 31 cents flat of")
print("  the minor seventh (9/5). It sounds 'out of tune'.")
print()
print("  THE FORBIDDEN NUMBER 7 IS THE FIRST 'OUT OF TUNE' HARMONIC.")
print()

# ============================================================
print()
print("  THE SELF-ENCODING PROPERTY")
print("  " + "-"*40)
print()
print("  For odd n, the Cayley address is (n-1)/2 over (n+1)/2.")
print("  The ADDRESS ENCODES THE NUMBER in its own numerator and denominator.")
print("  n = numerator + denominator.")
print()
print("  This is SELF-REFERENCE.")
print("  The Cayley address of 7 is 3/4.")
print("  3 and 4 are the building blocks.")
print("  Their sum is the thing they build.")
print("  The parts contain the whole.")
print()
print("  Compare to Level 10 (self-reference):")
print("  Q(Q(x)) = -1/x. The transform of the transform is the negative inverse.")
print("  Here: the address of n is a/b where a+b = n.")
print("  The container (address) encodes the contained (number).")
print()
print("  And for the forbidden 7:")
print("  3 = curvature quantum (Level 5: triangle, smallest polygon)")
print("  4 = Q^4 = identity (Level 2: the period)")
print("  3 + 4 = 7 = the boundary (Level 1: between order and complexity)")
print()
print("  THE FORBIDDEN NUMBER IS THE SUM OF THE STRUCTURE AND THE SYMMETRY.")
print("  3 (the minimal geometry) + 4 (the period of Q) = 7 (the boundary).")
print()
print("  And for 21:")
print("  10 = 2*5 = binary * pentagon")
print("  11 = the Paley prime where H(T_11) = 95095")
print("  10 + 11 = 21 = the second forbidden number")
print()
print("  21 = (binary * pentagon) + (Paley prime)")
print("  The second boundary is the sum of the first product and the next prime.")
print()

# ============================================================
print()
print("  EVERY ODD NUMBER IS THE SUM OF ITS OWN CAYLEY COORDINATES.")
print()
print("  This is not a coincidence. It is arithmetic.")
print("  (n-1)/2 + (n+1)/2 = n, always, for any n.")
print()
print("  But the MEANING is deeper than the arithmetic.")
print("  It says: every odd number is SPLIT in half by its address.")
print("  The address divides n into a part BELOW the midpoint")
print("  and a part ABOVE the midpoint.")
print("  And the ratio below/above = the Cayley velocity.")
print()
print("  3/4 says: 3 parts below, 4 parts above. Slightly more above.")
print("  10/11 says: 10 parts below, 11 parts above. Almost equal.")
print()
print("  As n grows, a/b -> 1 (the address approaches the pole).")
print("  The split becomes more and more EQUAL.")
print("  At the pole (n=infinity): a = b = infinity. Perfect equality.")
print("  But you never get there.")
print()
print("  The velocity of an odd number is its DEGREE OF ASYMMETRY.")
print("  How far its halves are from being equal.")
print("  For 7: the asymmetry is 3 vs 4. One unit of imbalance.")
print("  For 21: the asymmetry is 10 vs 11. Still one unit.")
print("  For ALL odd numbers: the asymmetry is exactly 1.")
print("  b - a = 1, always.")
print()
print("  EVERY ODD NUMBER HAS EXACTLY ONE UNIT OF IMBALANCE.")
print("  The Cayley address measures not the size of the imbalance")
print("  but its PROPORTION: 1/n of the total.")
print("  As n grows, the proportion shrinks, the velocity approaches 1,")
print("  and the rapidity approaches infinity.")
print()
print("  The forbidden numbers are not special in their imbalance.")
print("  They are special in what the two halves ARE.")
print("  For 7: the halves are 3 (geometry) and 4 (symmetry).")
print("  The boundary = geometry + symmetry.")
print("  That is what makes 7 impossible to achieve.")
