"""
omega_palindrome_proof.py — Investigate proof of Omega palindrome for Paley T_p

Conjecture (HYP-431): For Paley T_p (p prime, p=3 mod 4, p>=7):
  dim(Omega_k) = dim(Omega_{p-k}) for k=1,...,p-1

This would follow from an involution phi: Omega_k -> Omega_{p-k} that is
a linear isomorphism.

Approach 1: Path reversal. If phi(v_0,...,v_k) = (v_k,...,v_0) in T^op,
and T_p = T_p^op (Paley is self-converse since -1 is NQR for p=3 mod 4),
then phi maps k-paths of T to k-paths of T^op = T. But does phi preserve Omega?

Approach 2: The map phi that sends a k-path to a (p-1-k)-path by
complementing: using the remaining p-1-k vertices in some order.

Approach 3: Check computationally whether the two chain complexes
Omega_k and Omega_{p-k} are isomorphic as modules over the group ring Z[Z_p].

Let me test the path reversal approach.

Author: kind-pasteur-2026-03-10-S50
"""
import sys
sys.path.insert(0, '04-computation')
sys.stdout.reconfigure(line_buffering=True)

from tournament_utils import full_chain_complex_modp, enumerate_all_allowed


def paley_adj(p):
    qr = set()
    for i in range(1, p):
        qr.add((i * i) % p)
    A = [[0] * p for _ in range(p)]
    for i in range(p):
        for j in range(p):
            if i != j and (j - i) % p in qr:
                A[i][j] = 1
    return A


def check_self_converse(A, p):
    """Verify T_p is self-converse (T = T^op up to relabeling)."""
    # T^op has A^op[i][j] = A[j][i]
    # T_p is self-converse because the map i -> -i mod p sends arc (i,j) to (-i,-j)
    # and (-i)->(-j) iff (j-i) is QR iff (-j-(-i)) = -(j-i) is NQR for T^op
    # Wait: T_p has i->j iff (j-i) in QR. T_p^op has i->j iff (i-j) in QR iff -(j-i) in QR.
    # Since p=3 mod 4: -1 is NQR, so -(j-i) in QR iff (j-i) in NQR.
    # So T^op = complement of T (arcs reversed) = tournament where i->j iff (j-i) in NQR.
    # This is the Paley tournament with connection set NQR (same as relabeling i -> -i).
    # Under the map sigma: i -> -i mod p, the arc (i,j) in T maps to (-i,-j) in T^op.
    # T_p is self-converse, confirming sigma: T_p -> T_p^op is an isomorphism.

    # Verify: sigma(i) = -i mod p is an anti-automorphism
    # A[sigma(i)][sigma(j)] in T^op iff A[j][i] in T iff (i-j) in QR iff (j-i) in NQR
    # A[sigma(i)][sigma(j)] in T iff (-i -> -j) iff (-j - -i) in QR iff (j-i) in QR
    # For sigma to be anti-aut: (i->j in T) iff (sigma(j)->sigma(i) in T)
    # sigma(j)->sigma(i) = (-j)->(-i) iff (-i-(-j)) = j-i in QR iff i->j in T.
    print(f"T_{p} is self-converse via sigma: i -> -i mod p")

    # Verify numerically
    sigma = [((-i) % p) for i in range(p)]
    errors = 0
    for i in range(p):
        for j in range(p):
            if i == j: continue
            si, sj = sigma[i], sigma[j]
            # i->j iff sj->si (anti-aut = reversal isomorphism)
            if A[i][j] != A[sj][si]:
                errors += 1
    print(f"  Anti-automorphism verification: {errors} errors (should be 0)")
    return errors == 0


def path_reversal_test(p, max_k=5):
    """Test if path reversal gives a bijection Omega_k <-> Omega_{p-k}."""
    # Under sigma: i -> -i mod p, the path (v_0,...,v_k) maps to (sigma(v_0),...,sigma(v_k))
    # = (-v_0,...,-v_k). This is a k-path in T^op = T (anti-automorphism).
    # So path reversal + sigma gives: (v_0,...,v_k) -> (sigma(v_k),...,sigma(v_0))
    # = (-v_k,...,-v_0), which is a k-path in T.

    # But this maps Omega_k to Omega_k, not Omega_k to Omega_{p-k}.
    # The palindrome Omega_k = Omega_{p-k} suggests a DIFFERENT involution.

    print(f"\nPath reversal: maps Omega_k -> Omega_k (not Omega_k -> Omega_{{p-k}})")
    print("This doesn't directly prove the palindrome.")
    print()
    print("Alternative: complement path involution.")
    print("A k-path (v_0,...,v_k) uses k+1 vertices, leaving p-k-1 unused.")
    print("A (p-k)-path uses p-k+1 vertices... different number!")
    print("So a simple bijection Omega_k <-> Omega_{p-k} can't be pointwise.")
    print()
    print("The palindrome must come from CHAIN-LEVEL isomorphism (on vector spaces),")
    print("not element-level bijection.")
    print()

    # Check: is the boundary operator d_k: A_k -> A_{k-1} related to d_{p-k}: A_{p-k} -> A_{p-k-1}?
    # For Paley T_p with Fourier decomposition:
    # The chain complex decomposes into p eigenspaces for Z_p.
    # Eigenspace k (for k=0,...,p-1): generated by e_omega^k elements.
    # The palindrome might follow from the symmetry omega_k <-> omega_{p-k} (complex conjugate).

    print("Fourier explanation:")
    print("The chain complex decomposes as direct sum over Z_p eigenspaces.")
    print("Eigenspace k and eigenspace p-k are related by complex conjugation (omega_k = conj(omega_{p-k})).")
    print("Since the tournament is real, dim(Omega_k^{eig k}) = dim(Omega_{p-k-?}^{eig p-k}) ...")
    print("This might explain Omega_k^{total} = Omega_{p-k}^{total} via pairing of eigenspaces.")


def compute_and_verify_palindrome(p, max_k=None):
    """Compute Omega dims and verify palindrome."""
    if max_k is None:
        max_k = p - 1

    A = paley_adj(p)
    cc = full_chain_complex_modp(A, p, max_p=max_k)
    omega = cc['omega_dims']

    print(f"\nT_{p}: Omega dims (up to k={max_k})")
    for k in range(max_k + 1):
        print(f"  Omega_{k} = {omega.get(k, 0)}")

    print(f"\nPalindrome check Omega_k = Omega_{{p-k}}:")
    for k in range(1, min(max_k + 1, p)):
        sym = p - k
        if sym <= max_k:
            ok = omega.get(k, 0) == omega.get(sym, 0)
            print(f"  Omega_{k}={omega.get(k,0)} vs Omega_{sym}={omega.get(sym,0)}: {'OK' if ok else 'FAIL'}")
        else:
            print(f"  Omega_{k}={omega.get(k,0)} vs Omega_{sym}=??? (not computed)")


def main():
    print("OMEGA PALINDROME PROOF INVESTIGATION")
    print("=" * 60)

    for p in [7]:
        A = paley_adj(p)
        check_self_converse(A, p)
        path_reversal_test(p)
        compute_and_verify_palindrome(p, max_k=p-1)

    print("\n" + "=" * 60)
    print("Fourier eigenspace approach to palindrome:")
    print("=" * 60)
    print("""
For Paley T_p, the cyclic group Z_p acts on the chain complex.
The k-th eigenspace (for character omega_j) of the action on A_m is
the set of m-chains e = sum_{v in Z_p} alpha_v * tau^v(P) where tau is shift.

The chain complex of eigenspace j has:
  dim(Omega_m^{(j)}) = some function of j and m

For j != 0: the eigenspace chain complex is a twisted complex.
The palindrome Omega_k = Omega_{p-k} would follow if:
  sum_j dim(Omega_k^{(j)}) = sum_j dim(Omega_{p-k}^{(j)})

For real tournaments with Z_p symmetry: eigenspaces j and p-j
are complex conjugates, so dim(Omega_k^{(j)}) = dim(Omega_k^{(p-j)}).

But this gives Omega_k = Omega_k (trivially), not Omega_k = Omega_{p-k}.

The actual palindrome must come from a deeper structural isomorphism
between the degree-k and degree-(p-k) eigenspaces.

OPEN: Prove dim(Omega_k^{(j)}) = dim(Omega_{p-k}^{(p-j)}) for all j.
This would combine the Z_p symmetry with a "Poincare duality" type argument.
""")


if __name__ == '__main__':
    main()
    print("\nDONE.")
