#!/usr/bin/env python3
"""Orbit-functor atlas for LRC rigidity.

This is a small finite audit around HYP-2124/2125/2126/2127.

The point is not to run an exact LRC search.  It asks which *actions* on the
same witness payload preserve, split, or forget the labels that make a local
rigidity event useful.

Assumption challenge: the Tournament Analysis vertices below are proof lenses,
not runners or arcs.  The quotient preserves an LRC predicate only when the
lens keeps the observer/source, denominator, endpoint, pincer, or CRT label
needed by the corresponding closure rule.
"""

from __future__ import annotations

from collections import Counter
from math import gcd


def units(n: int) -> list[int]:
    return [x for x in range(1, n) if gcd(x, n) == 1]


def v2(n: int) -> int:
    c = 0
    while n % 2 == 0:
        n //= 2
        c += 1
    return c


def factor_pp(n: int) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    p = 2
    m = n
    while p * p <= m:
        if m % p == 0:
            a = 0
            while m % p == 0:
                m //= p
                a += 1
            out.append((p, a))
        p += 1 if p == 2 else 2
    if m > 1:
        out.append((m, 1))
    return out


def prime_power(p: int, a: int) -> int:
    return p**a


def orbits_by_maps(domain: list[int], n: int, maps) -> list[list[int]]:
    """Undirected components generated by the supplied maps."""
    S = set(domain)
    seen: set[int] = set()
    orbits: list[list[int]] = []
    for x in sorted(S):
        if x in seen:
            continue
        stack = [x]
        comp: set[int] = set()
        seen.add(x)
        while stack:
            y = stack.pop()
            comp.add(y)
            for f in maps:
                z = f(y) % n
                if z in S and z not in seen:
                    seen.add(z)
                    stack.append(z)
        orbits.append(sorted(comp))
    return orbits


def cyclic_orbits_by_multiplier(domain: list[int], n: int, mult: int) -> list[list[int]]:
    S = set(domain)
    if any((mult * x) % n not in S for x in S):
        return [[x] for x in sorted(S)]
    return orbits_by_maps(domain, n, [lambda y: (mult * y) % n])


def reflect_orbits(domain: list[int], n: int) -> list[list[int]]:
    return orbits_by_maps(domain, n, [lambda y: -y])


def full_unit_orbits(domain: list[int], n: int) -> list[list[int]]:
    U = units(n)
    return orbits_by_maps(domain, n, [lambda y, u=u: u * y for u in U])


def crt_signature(n: int) -> str:
    pieces = []
    for p, a in factor_pp(n):
        mod = prime_power(p, a)
        projected = sorted({x % mod for x in units(n)})
        if p == 2:
            if mod == 2:
                pieces.append(f"mod {mod}: unit point {projected}, x2 collapses to 0")
            else:
                pieces.append(f"mod {mod}: {len(projected)} odd units, x2 exits unit fiber")
        else:
            orbs = cyclic_orbits_by_multiplier(projected, mod, 2)
            pieces.append(f"mod {mod}: x2 cycles {orbs}")
    return "; ".join(pieces)


def short_orbit_summary(orbits: list[list[int]]) -> str:
    sizes = [len(o) for o in orbits]
    if len(orbits) <= 4 and max(sizes, default=0) <= 8:
        return str(orbits)
    return f"{len(orbits)} comps, sizes {sizes}"


def witness_clock_ap(n: int) -> list[int]:
    # HYP-2124 exact AP result: j/n is lonely iff gcd(j,n)=1.
    return units(n)


def directed_3_cycles(edges: dict[tuple[str, str], str], names: list[str]) -> int:
    count = 0
    for i, a in enumerate(names):
        for j, b in enumerate(names):
            if j <= i:
                continue
            for k, c in enumerate(names):
                if k <= j:
                    continue
                ab = edges[(a, b)] == a
                bc = edges[(b, c)] == b
                ca = edges[(c, a)] == c
                if ab and bc and ca:
                    count += 1
                if (not ab) and (not bc) and (not ca):
                    count += 1
    return count


def sccs(edges: dict[tuple[str, str], str], names: list[str]) -> list[list[str]]:
    adj = {x: [] for x in names}
    for a in names:
        for b in names:
            if a == b:
                continue
            if edges[(a, b)] == a:
                adj[a].append(b)

    def reach(start: str) -> set[str]:
        todo = [start]
        seen = {start}
        while todo:
            x = todo.pop()
            for y in adj[x]:
                if y not in seen:
                    seen.add(y)
                    todo.append(y)
        return seen

    remaining = set(names)
    comps = []
    while remaining:
        x = sorted(remaining)[0]
        rx = reach(x)
        comp = sorted(y for y in remaining if x in reach(y) and y in rx)
        comps.append(comp)
        remaining.difference_update(comp)
    return comps


def tournament_analysis() -> None:
    print("Tournament Analysis: proof lenses as vertices")
    print("pair observable = (payload_retention, orbit_connectedness,")
    print("                   defect_localization, proof_maturity, -cost)")
    print("switch = lexicographic dominance; tie Hamiltonian path = listed order")

    lenses = [
        ("labelled_source_cascade", (5, 4, 5, 5, -3)),
        ("pincer_denominator_endpoint", (5, 4, 5, 4, -3)),
        ("CRT_factor_projection", (4, 3, 5, 4, -2)),
        ("quotient_fiber_transport", (4, 2, 5, 3, -3)),
        ("static_unit_clock", (4, 5, 4, 5, -1)),
        ("dihedral_reflection_pincer", (4, 3, 4, 3, -1)),
        ("dynamical_doubling_action", (3, 4, 4, 4, -1)),
        ("spectral_character_blocks", (3, 4, 4, 2, -2)),
        ("isostatic_constraint_graph", (3, 3, 3, 2, -2)),
        ("cyclic_polygon_action", (3, 5, 2, 5, -1)),
        ("dihedral_bracelet_action", (3, 3, 3, 4, -1)),
        ("raw_unmarked_shadow", (1, 1, 1, 5, 0)),
    ]
    names = [x for x, _ in lenses]
    score = {x: v for x, v in lenses}
    edges: dict[tuple[str, str], str] = {}
    outdeg = Counter()
    edge_flips_vs_cost = 0
    for a in names:
        for b in names:
            if a == b:
                continue
            winner = a if score[a] > score[b] else b
            edges[(a, b)] = winner
            if winner == a:
                outdeg[a] += 1
            cost_winner = a if score[a][-1] > score[b][-1] else b
            if winner != cost_winner:
                edge_flips_vs_cost += 1

    ordered = sorted(names, key=lambda x: score[x], reverse=True)
    print("  Hamiltonian path:")
    print("    " + " > ".join(ordered))
    print(f"  score histogram: {dict(Counter(outdeg[x] for x in names))}")
    print(f"  directed 3-cycles: {directed_3_cycles(edges, names)}")
    print(f"  SCCs: {sccs(edges, names)}")
    print(f"  edge flips versus cost-only switch: {edge_flips_vs_cost // 2}")
    print()


def print_rigidity_type_atlas() -> None:
    rows = [
        (
            "static multiplicative",
            "(Z/n)* acts on j/n",
            "AP unit witnesses, local straddle pins",
            "nonunit clocks and endpoint payload",
        ),
        (
            "dynamical doubling",
            "x -> 2x on witness residues",
            "odd-n propagation and binary IFS",
            "even-n unit fiber; n=14 fragments",
        ),
        (
            "dihedral reflective",
            "j <-> -j",
            "antipodal jaws and pincer symmetry",
            "orientation/source side unless labelled",
        ),
        (
            "CRT channel",
            "projection to prime-power factors",
            "localizes defects to one block",
            "cross-factor owner/endpoint coupling",
        ),
        (
            "quotient transport",
            "object -> fiber bucket",
            "empty/rigid/leaking/transport rows",
            "mixed predicate values in forgotten fibers",
        ),
        (
            "monodromy",
            "loop in quotient lifts to label permutation",
            "trivial holonomy gives cascade",
            "nontrivial loop hides observer coupling",
        ),
        (
            "isostatic",
            "constraint graph on active obligations",
            "critical rigidity counts",
            "over/underconstrained local cover cores",
        ),
        (
            "spectral character",
            "Fourier/Dirichlet blocks on orbit",
            "block-diagonal defect ledger",
            "gcd>1 and 2-adic leakage",
        ),
        (
            "fiber stiffness",
            "boundary vs inner label flips",
            "anisotropy of a fixed class",
            "ensemble isotropy hides class stiffness",
        ),
        (
            "source functor",
            "delete/add marked source",
            "exact fixed-point cascade",
            "generic rooted shadows without incidents",
        ),
    ]
    print("Rigidity type atlas")
    for name, action, keeps, loses in rows:
        print(f"  {name:23s} | {action:34s} | keeps: {keeps}")
        print(f"  {'':23s} | {'':34s} | loses: {loses}")
    print()


def print_clock_table() -> None:
    print("AP unit-clock orbit table")
    header = (
        "n  phi  v2  odd-core  static        doubling                  "
        "reflect        CRT defect"
    )
    print(header)
    print("-" * len(header))
    for n in [7, 8, 9, 10, 12, 14, 15, 16, 18, 21, 27, 28, 30]:
        U = witness_clock_ap(n)
        static = short_orbit_summary(full_unit_orbits(U, n))
        doub = cyclic_orbits_by_multiplier(U, n, 2)
        if gcd(2, n) != 1:
            doub_s = f"fragments {len(doub)} singleton"
        else:
            doub_s = short_orbit_summary(doub)
        refl = short_orbit_summary(reflect_orbits(U, n))
        odd_core = n >> v2(n)
        defect = "none" if n % 2 else f"2-block height {v2(n)}"
        print(
            f"{n:<2} {len(U):<4} {v2(n):<3} {odd_core:<8} "
            f"{static:<13} {doub_s:<25} {refl:<14} {defect}"
        )
    print()


def print_n14_forensic() -> None:
    n = 14
    U = witness_clock_ap(n)
    print("n=14 forensic")
    print(f"  unit witnesses: {U}")
    print(f"  static unit orbit: {full_unit_orbits(U, n)}")
    print("  doubling x2 on units: illegal inside the unit fiber;")
    print(f"    resulting witness fragments: {cyclic_orbits_by_multiplier(U, n, 2)}")
    print(f"  reflection/antipodal pairs: {reflect_orbits(U, n)}")
    print(f"  CRT signature: {crt_signature(n)}")
    print(
        "  reading: the q=7 coordinate still has two x2 cycles, while the"
    )
    print(
        "    mod-2 coordinate collapses.  Thus n=14 is statically rigid,"
    )
    print("    reflectively paired, and dynamically broken in one 2-adic bit.")
    print()


def print_hypotheses() -> None:
    print("New falsifiable hypotheses suggested by the atlas")
    print(
        "  H7 monodromy rigidity: any residual LRC counterexample core must"
    )
    print(
        "     contain a nontrivial label-monodromy loop in an observer-marked"
    )
    print(
        "     quotient.  Trivial monodromy should let source/denominator/"
        "endpoint labels cascade to a witness or positive Phi escape."
    )
    print(
        "  H8 dihedral pincer rigidity: even-n doubling fragments are still"
    )
    print(
        "     paired by j <-> -j.  A labelled pincer proof should discharge"
    )
    print(
        "     each antipodal pair unless a CRT/endpoint owner loop exports a"
        " middle-state core."
    )
    print(
        "  H9 fiber-stiffness criterion: hard buckets are maximally stiff in"
    )
    print(
        "     the observer fiber, not necessarily maximally symmetric.  The"
    )
    print(
        "     ratio of boundary-label flips to inner flips should predict"
        " which quotient fibers leak."
    )
    print(
        "  H10 character leakage: for n=2q, all non-principal orbit-defect"
    )
    print(
        "      mass is carried by the 2-adic character block; the q-block is"
    )
    print("      already prime/odd and should be certifiable by existing clocks.")


def main() -> None:
    print("ORBIT RIGIDITY FUNCTOR ATLAS -- codex-2026-06-03-S590")
    print()
    print_clock_table()
    print_n14_forensic()
    print_rigidity_type_atlas()
    tournament_analysis()
    print_hypotheses()


if __name__ == "__main__":
    main()
