#!/usr/bin/env python3
"""Complete pair controls for the uniform H4 mixed (3)(2) equality theorem.
No ambient cutoff is used for the theorem: each PAIR has union size <=10.
"""
from collections import Counter
from hashlib import sha256
from itertools import combinations
import json

GATES = 0

def need(condition, label):
    global GATES
    GATES += 1
    if not condition:
        raise RuntimeError(label)

def mul(p, q):
    return tuple(p[i] for i in q)

def inv(p):
    ans = [0]*len(p)
    for i, j in enumerate(p):
        ans[j] = i
    return tuple(ans)

def power(p, n):
    ans = tuple(range(len(p)))
    for _ in range(n):
        ans = mul(ans, p)
    return ans

def cycle(d, labels):
    ans = list(range(d))
    for x, y in zip(labels, labels[1:]+labels[:1]):
        ans[x] = y
    return tuple(ans)

def support(p):
    return frozenset(i for i, j in enumerate(p) if i != j)

def cycles(p):
    unseen = set(range(len(p)))
    out = []
    while unseen:
        x = min(unseen)
        row = []
        while x not in row:
            row.append(x)
            unseen.remove(x)
            x = p[x]
        if len(row) > 1:
            out.append([i+1 for i in row])
    return out

def alternating(a, b, length):
    ans = tuple(range(len(a)))
    for i in range(length):
        ans = mul(ans, a if i % 2 == 0 else b)
    return ans

def letter_word(a, b, length):
    # Independent path: apply each word to each label, rightmost first.
    ans = []
    for x in range(len(a)):
        for position in reversed(range(length)):
            x = (a if position % 2 == 0 else b)[x]
        ans.append(x)
    return tuple(ans)

def braid(a, b, length):
    return alternating(a,b,length) == alternating(b,a,length)

def commuting(a, b):
    return mul(a,b) == mul(b,a)

def typed_partners(d):
    for three in combinations(range(d), 3):
        rest = tuple(i for i in range(d) if i not in three)
        for orientation in (three, (three[0],three[2],three[1])):
            p = cycle(d, orientation)
            for two in combinations(rest, 2):
                yield mul(p,cycle(d,two))

def pieces(p):
    return power(p,4), power(p,3)

def cell(sigma, tau):
    p,q = pieces(sigma)
    r,s = pieces(tau)
    return (len(support(p)&support(r)), len(support(p)&support(s)),
            len(support(q)&support(r)), len(support(q)&support(s)))

D = 10
identity = tuple(range(D))
sigma = mul(cycle(D,(0,1,2)),cycle(D,(3,4)))
partners = list(typed_partners(D))
partner_set = frozenset(partners)
need(len(partners) == len(set(partners)) == 5040, 'complete raw pair universe')
sp,sq = pieces(sigma)
expected = {
    3: {(3,0,0,2):1,(3,0,0,1):10,(2,0,0,2):15,(2,0,0,1):120},
    5: {(3,0,0,2):1,(2,1,1,1):6,(2,1,1,0):30,(1,0,0,2):60}}
tables = {3:Counter(),5:Counter()}
power_pass = Counter()
rows = []
for tau in partners:
    tp,tq = pieces(tau)
    need(sorted(map(len,cycles(tau))) == [2,3], 'literal partner cycle type')
    need(mul(tp,tq) == tau and not support(tp)&support(tq), 'canonical disjoint factors')
    entry = {'tau':tau,'cell':cell(sigma,tau)}
    for length in (3,5):
        left,right = alternating(sigma,tau,length),alternating(tau,sigma,length)
        need(left == letter_word(sigma,tau,length) and right == letter_word(tau,sigma,length),
             'independent rightmost-first literal action')
        ok = left == right
        entry[str(length)] = ok
        if not ok:
            continue
        tables[length][entry['cell']] += 1
        r = (length-1)//2
        g = power(mul(sigma,tau),r)
        need(mul(g,sigma) == mul(tau,g), 'independent odd conjugator predicate')
        pp = braid(sq,tq,length)
        power_pass[length] += pp
        if length == 3:
            need(not support(sp)&support(tq) and not support(sq)&support(tp), 'ordinary cross-length separation')
            need(braid(sp,tp,3) and braid(sq,tq,3), 'ordinary restriction to each cycle length')
        elif not support(sp)&support(tq):
            need(not support(sq)&support(tp) and sq == tq, 'five-edge one missing cross intersection')
    rows.append(entry)
for length in (3,5):
    need(dict(tables[length]) == expected[length], 'complete pair support-cell table')
need(dict(power_pass) == {3:146,5:61}, 'literal power-transfer outcomes')

# A second complete universe path: all centralizer orbits, without a braid filter.
# C(sigma)=C3 x C2 x S5, generated by the two cycles and adjacent outside swaps.
generators = [cycle(D,(0,1,2)),cycle(D,(3,4))]
generators += [cycle(D,(i,i+1)) for i in range(5,9)]
for gen in generators:
    need(commuting(gen,sigma), 'centralizer generator')
unseen = set(partners)
orbit_rows = []
weighted = {3:Counter(),5:Counter()}
while unseen:
    seed = min(unseen)
    orbit,queue = {seed},[seed]
    for current in queue:
        for gen in generators:
            nxt = mul(mul(gen,current),inv(gen))
            need(nxt in partner_set, 'orbit stays in complete partner universe')
            if nxt not in orbit:
                orbit.add(nxt)
                queue.append(nxt)
    need(orbit <= unseen, 'complete disjoint centralizer orbit')
    unseen -= orbit
    entry = {'size':len(orbit),'representative':cycles(seed),'cell':cell(sigma,seed)}
    for length in (3,5):
        accepted = braid(sigma,seed,length)
        need(all(braid(sigma,p,length) == accepted for p in orbit), 'centralizer predicate invariance')
        need(all(cell(sigma,p) == entry['cell'] for p in orbit), 'centralizer cell invariance')
        entry[str(length)] = accepted
        if accepted:
            weighted[length][entry['cell']] += len(orbit)
    orbit_rows.append(entry)
need(len(orbit_rows) == 64 and sum(r['size'] for r in orbit_rows) == 5040, 'complete orbit partition')
for length in (3,5):
    need(weighted[length] == tables[length], 'second universe count reconstruction')

# The minimal five-letter power-transfer hostile, on its actual support.
s5 = mul(cycle(5,(0,1,2)),cycle(5,(3,4)))
t5 = mul(cycle(5,(0,1,3)),cycle(5,(2,4)))
need(braid(s5,t5,5), 'minimal braid-five hostile')
need(not braid(power(s5,3),power(t5,3),5), 'cubing does not preserve braid-five')
need(support(s5) == support(t5) == frozenset(range(5)), 'minimal support size five')

# Tiny orientation certificate used in the ordinary 3-cycle A3 lemma.
p = cycle(4,(0,1,2)); p_inv = power(p,2)
q_plus = cycle(4,(0,1,3)); q_minus = cycle(4,(0,3,1))
need(not braid(p,q_plus,3) and braid(p,q_minus,3), 'two shared-pair orientations')
need(not braid(p_inv,q_minus,3), 'inverse cannot braid with same external 3-cycle')
# All 3-cycle A3 triples on their union (at most nine labels); pair reduction
# in the proof already forces both leaf supports equal or disjoint. The
# four-letter orientation check is the entire remaining overlapping case.

# Optional bounded full-tuple control. It is NOT the unbounded proof.
ordinary = [p for p in partners if braid(p,sigma,3)]
last = [p for p in partners if commuting(p,sigma)]
need(len(ordinary)==146 and len(last)==62, 'declared necessary full-tuple filters')
full = []
for aa in ordinary:
    for cc in ordinary:
        if not commuting(aa,cc):
            continue
        for dd in last:
            if not commuting(aa,dd) or not braid(cc,dd,5):
                continue
            full.append((aa,sigma,cc,dd))
            need(aa == sigma == cc == dd, 'bounded H4 equality control')
need(len(full)==1, 'complete bounded full-tuple control')

# Positive equality control for arbitrary padding: the cyclic image has two
# separate nontrivial orbits, so is never a transitive degree-five action.
for ambient in (5,6,11,25):
    p = mul(cycle(ambient,(0,1,2)),cycle(ambient,(3,4)))
    need(braid(p,p,3) and braid(p,p,5) and commuting(p,p), 'equal-generator positive control')
    need(sorted(map(len,cycles(p))) == [2,3], 'positive control distinct orbit lengths')

report = {
    'scope':'uniform H4 (3)(2) generators all equal; finite-reduced pair supplier',
    'pair_universe':5040, 'centralizer_orbits':len(orbit_rows),
    'pair_tables':{str(length):[{'cell':key,'count':value} for key,value in sorted(tables[length].items())]
                   for length in (3,5)},
    'power_pass':dict(power_pass),
    'minimal_hostile':{'sigma':cycles(s5),'tau':cycles(t5),'braid_length':5},
    'bounded_full_tuples':len(full), 'always_active_gates':GATES,
    'raw_pair_sha256':sha256(json.dumps(rows,sort_keys=True,separators=(',',':')).encode()).hexdigest(),
    'orbit_sha256':sha256(json.dumps(orbit_rows,sort_keys=True,separators=(',',':')).encode()).hexdigest(),
    'positive_orbits':[r for r in orbit_rows if r['3'] or r['5']]}
print(json.dumps(report,sort_keys=True,indent=2))
