#!/usr/bin/env python3
"""Exact two-chart controls for a DG V4 surface and its carrier collapse.

No alleged Keller map or classification of possible finite envelopes.
"""
import hashlib
import json
import sympy as S

x,t,r,b,s,z,q = S.symbols('x t r b s z q')
gates=0

def check(test,label):
 global gates
 gates+=1
 if not test: raise RuntimeError(label)

def eq(a,c,label): check(S.cancel(S.together(a-c))==0,label)

def sub(f,values): return f.subs(values,simultaneous=True)

tr={x:1/r,t:-r**2-r**4*b}
back={r:1/x,b:-x**2-x**4*t}
for v in (x,t): eq(sub(tr[v],back),v,'inverse original '+str(v))
for v in (r,b): eq(sub(back[v],tr),v,'inverse boundary '+str(v))

# Recover the transition from both original graph-complement coordinates.
eq(1/(b/(1+r*r*b)-1/r**2),tr[t],'graph complement transition')
eq((x*x+1/t)/(1-(x*x+1/t)/x**2),back[b],'graph complement inverse transition')
eq((b/(1+r*r*b))/(1-r*r*(b/(1+r*r*b))),b,'boundary-chart coordinate inverse')
eq(1/((s*s+1/t)-s*s),t,'finite-chart coordinate inverse')
# The homogeneous coordinate pairs [1+x^2*t:t] and [b:1+r^2*b]
# never have a common zero; these identities witness the unit ideals.
eq((1+x*x*t)-x*x*t,1,'finite projective coordinate pair has no base point')
eq((1+r*r*b)-r*r*b,1,'boundary projective coordinate pair has no base point')

dx_dr=S.diff(tr[x],r); dx_db=S.diff(tr[x],b)
dt_dr=S.diff(tr[t],r); dt_db=S.diff(tr[t],b)
eq(dx_dr*dt_db-dx_db*dt_dr,r*r,'volume form gluing')
ar=S.cancel(tr[x]*dt_dr); ab=S.cancel(tr[x]*dt_db)
eq(ar,-2-4*r*r*b,'primitive dr coefficient')
eq(ab,-r**3,'primitive db coefficient')
eq(S.diff(ab,r)-S.diff(ar,b),r*r,'global exact volume form')
check(S.Poly(ar,r,b).is_multivariate and S.Poly(ab,r,b) is not None,'primitive is regular')

u=x*x*t; p=t*(1+u); y=x*t*p
ui=-1-r*r*b; pi=r**4*b*(1+r*r*b); yi=-r**5*b*(1+r*r*b)**2
for left,right,name in [(u,ui,'u'),(p,pi,'p'),(y,yi,'y')]:
 eq(sub(left,tr),right,'carrier extension '+name)
 check(S.denom(S.cancel(right))==1,'carrier regular '+name)
for f,val in [(ui,-1),(pi,0),(yi,0)]: eq(f.subs(r,0),val,'boundary carrier constant')
eq((1+ui)*yi**2-ui*pi**3,0,'carrier algebra relation')
sep=x*x*(1+u)
eq(sub(sep,tr),-b,'global boundary separator')
check(S.diff(-b,b)==-1,'separator nonconstant along boundary')

# Arbitrary symbolic polynomial coefficients; all-degree extension and
# collapse follow from the algebra generated by these three functions.
h0,h1,h2,h3=S.symbols('h0 h1 h2 h3')
H=h0+h1*p+h2*y+h3*p*y
G=-u/2+H
boundary=lambda f:S.cancel(S.together(sub(f,tr))).subs(r,0)
eq(boundary(G),S.Rational(1,2)+h0,'source-form boundary value')
Bsample=3+u**2+2*u*p+y+p*y**2
eq(boundary(Bsample),4,'polynomial carrier boundary control')
# The finite test uses two distinct boundary points; the analytic proof
# covers every polynomial in the carrier, not just this sample.
eq(boundary(Bsample).subs(b,0),boundary(Bsample).subs(b,1),
   'same carrier images at distinct boundary points')
check((-b).subs(b,0)!=(-b).subs(b,1),'full global algebra separates those points')

# Constant nodal-defect value does not force constant coordinates.
P=lambda A,C:C*C-A**3+S.Rational(3,4)*A+S.Rational(1,4)
Aq=q*q-1; Cq=q*(q*q-S.Rational(3,2))
eq(P(Aq,Cq),S.Rational(1,2),'nonconstant nodal boundary parametrization')
check(S.diff(Aq,q)!=0 and S.diff(Cq,q)!=0,'both boundary coordinates vary')

# All-order changed-carrier operation. First verify the rational transition
# for a completely symbolic increment, before specializing any polynomial.
delta,h,c=S.symbols('delta h c')
bb=b+2*delta/r*(1+2*r*r*b)+delta**2*(5+6*r*r*b)+4*r*(1+r*r*b)*delta**3+r*r*(1+r*r*b)*delta**4
rr=r/(1+r*delta)
eq(sub(-(x+delta)**2-(x+delta)**4*t,tr),bb,'general shear boundary formula')
eq(sub(1/(x+delta),tr),rr,'general shear base formula')
regular_bb=S.cancel(S.together(bb.subs(delta,r*r*h)))
check(S.denom(regular_bb)==1,'every increment divisible by r^2 has regular b image')
eq(regular_bb.subs(r,0),b,'admissible shear fixes boundary pointwise')
eq(S.cancel(S.together(r*bb.subs(delta,c+r*r*h))).subs(r,0),2*c,
   'nonzero constant increment has unavoidable simple pole')

c1,c2,c3=S.symbols('c1 c2 c3')
f=c1*t+c2*t*t+c3*t**3
Fx=x+f
eq(S.diff(Fx,x),1,'polynomial shear source Jacobian one')
eq(sub(Fx,{x:x-f,t:t}),x,'polynomial shear inverse')
potential=c1*t*t/2+c2*t**3/3+c3*t**4/4
eq(S.diff(potential,t),f,'global primitive changes by exact differential')
for ff in [t,t**2,t+t**3]:
 boundary_delta=S.cancel(S.together(sub(ff,tr)))
 transformed_b=S.cancel(S.together(bb.subs(delta,boundary_delta)))
 check(S.denom(transformed_b)==1,'named shear extends b')
 eq(transformed_b.subs(r,0),b,'named shear fixes D')
 mm=S.cancel(S.together(sub(sub(p,{x:x+ff,t:t}),{x:q,t:-q**-2})))
 expected=2*q**-3*ff.subs(t,-q**-2)+q**-4*ff.subs(t,-q**-2)**2
 eq(mm,expected,'changed carrier on old collapsed M')
 check(S.diff(mm,q)!=0,'named shear fails old carrier descent')

# Boundary-constant restrictions survive every automorphism fixing D.
# The analytic note applies this to the algebra generated by all translates.
eq(sub(ui,{r:0,b:b}),-1,'orbit carrier u remains boundary constant')
eq(sub(pi,{r:0,b:b}),0,'orbit carrier p remains boundary constant')
eq(sub(yi,{r:0,b:b}),0,'orbit carrier y remains boundary constant')

# Pic(P1xP1)=Z^2. Quotient by graph (2,1) has primitive generator (1,0).
def quotient(v): return v[0]-2*v[1]
check(quotient((2,1))==0,'graph class killed')
check(quotient((1,0))==1,'boundary class primitive generator')
check(quotient((-2,-2))==2,'canonical class coefficient two')
check(S.Matrix([[1,2],[0,1]]).det()==1,'integral boundary-graph basis')
check(2*2*1==4,'graph self intersection')
check(4-2==1+1==2,'two independent Euler decompositions')

payload={'transition':[str(tr[x]),str(tr[t])],
         'primitive':[str(ar),str(ab)],'carrier':[str(ui),str(pi),str(yi)],
         'separator':'-b','Pic':'Z[D]','canonical':'2[D]','Euler':2,
         'shear_boundary':str(bb),'shear_criterion':'f(0)=0'}
print('STATUS: exact two-chart surface and carrier controls PASS')
print('surface: (P1_s x P1_z) minus graph z=s^2; ample class(2,1), square4; DG V4')
print('boundary: D={r=0}=A1, complement U0=A2; Pic=Z[D], K=2[D], Euler=2')
print('volume: dx wedge dt=r^2 dr wedge db; primitive=(-2-4r^2*b)dr-r^3 db')
print('carrier on D: (u,p,y)=(-1,0,0); every G_H=1/2+H(0,0)')
print('separator: x^2(1+u)=-b; this global function is outside k[u,p,y]')
print('finite-map obstruction: both coordinates in k[u,p,y] collapse D')
print('hostile: constant nodal-defect value 1/2 permits nonconstant boundary coordinates')
print('all-order shear classification: (x+f(t),t) extends to W iff f(0)=0; D fixed pointwise')
print('shear operation: Jacobian1, inverse -f, primitive changes by d integral(f dt)')
print('changed carrier: nonzero f fails old A descent; every shear-orbit carrier still collapses D')
print('scope: explicit surface only; no identification with actual Keller envelope or Keller pair')
print('semantic_sha256='+hashlib.sha256(json.dumps(payload,sort_keys=True,separators=(',',':')).encode()).hexdigest())
print('PASS gates='+str(gates))
