#!/usr/bin/env python3
"""prime_gap_extended_s116k.py — Extending the prime gap chord theory.

We proved: CHORD(g) = prod_{p|g, p odd} f(p-2) = prod (p-1)/(p-2).
The velocities used are 1/3, 1/7, 1/11, ... which use primes 3, 7, 11 = Paley primes.

Now: what else can we extract from this?
"""
from math import log, sqrt, pi, log2, gcd, exp, atanh
from fractions import Fraction
from collections import Counter

def primes_up_to(n):
    sieve = [True]*(n+1)
    sieve[0] = sieve[1] = False
    for i in range(2, int(sqrt(n))+1):
        if sieve[i]:
            for j in range(i*i, n+1, i):
                sieve[j] = False
    return [i for i in range(2, n+1) if sieve[i]]

def odd_prime_factors(n):
    factors = []
    d = 3
    temp = n
    while d*d <= temp:
        if temp % d == 0:
            factors.append(d)
            while temp % d == 0:
                temp //= d
        d += 2
    if temp > 2:
        factors.append(temp)
    return factors

def chord(g):
    c = Fraction(1)
    for p in odd_prime_factors(g):
        c *= Fraction(p-1, p-2)
    return c

print()
print("  EXTENDING THE PRIME GAP CHORD THEORY")
print()
print("="*70)
print()

# ============================================================
print("  I. THE CHORD AS A CAYLEY COMPOSITION")
print("  " + "-"*40)
print()
print("  CHORD(g) = prod f(p-2) over odd primes p dividing g.")
print("  f(n) = (n+1)/n is our superparticular homomorphism.")
print("  f(a(+)b) = f(a)*f(b) where (+) is rapidity composition.")
print()
print("  So: CHORD(g) = f(c) where c = rapidity composition of")
print("  all (p-2) values for odd primes p dividing g.")
print()
print("  For g = 3*5*7 = 105:")
print("  Factors give p-2 values: 1, 3, 5.")
print("  Rapidity composition: 1 (+) 3 (+) 5.")
print("  1 (+) 3 = 1*3/(1+3+1) = 3/5.")
print("  3/5 (+) 5 = (3/5)*5/(3/5+5+1) = 3/(3/5+6) = 3/(33/5) = 15/33 = 5/11.")
c1 = Fraction(1*3, 1+3+1)
c2 = (c1 * 5) / (c1 + 5 + 1)
print(f"  1(+)3 = {c1}")
print(f"  {c1}(+)5 = {c2}")
print(f"  f({c2}) = {(c2+1)/c2} = {Fraction(c2.numerator+c2.denominator, c2.numerator)}")
print(f"  CHORD(105) = {float(chord(105)):.4f}")
print(f"  f(5/11) = 16/11? No... f(n) = (n+1)/n. f(5/11) = (5/11+1)/(5/11) = (16/11)/(5/11) = 16/5.")
print(f"  CHORD(105) = {chord(105)} = {float(chord(105)):.4f}. CHECK: 16/5 = {16/5}.")
print()
print("  The composed rapidity velocity for g=105 is 5/11.")
print("  Q(5/11) = (1+5/11)/(1-5/11) = (16/11)/(6/11) = 16/6 = 8/3.")
print(f"  Q(5/11) = {Fraction(16,6)} = {Fraction(8,3)}")
print()
print("  And CHORD(105) = f(5/11) = (5/11+1)/(5/11) = 16/5.")
print("  Hmm, f is defined for integers. Let me reconsider.")
print()
print("  Actually: CHORD(g) = prod f(p_i - 2).")
print("  And f(a)*f(b) = f(a(+)b) by our homomorphism theorem.")
print("  So CHORD = f(combined), where combined = rapidity composition of all (p_i-2).")
print()
print("  For g=105: combined = 1(+)3(+)5 = 5/11.")
print("  f(5/11) = (5/11+1)/(5/11) = 16/5. Not quite right since f is for integers.")
print()
print("  EXTEND f to rationals: f(x) = (x+1)/x = 1 + 1/x. Works for all x != 0.")
print("  Then f(5/11) = 1 + 11/5 = 16/5. And CHORD(105) = 16/5. MATCHES.")
print()
print("  So the EXTENDED homomorphism f(x) = 1 + 1/x works for rational x too!")
print("  And the rapidity composition (+) extends to rationals too.")
print("  The CHORD of any g is f of the rapidity composition of all (p-2).")
print()

# ============================================================
print()
print("  II. THE RAPIDITY OF EACH GAP'S CHORD")
print("  " + "-"*40)
print()
print("  The chord rapidity = arctanh(velocity of composed (p-2) values).")
print("  = sum of arctanh(1/(2p-3)) over odd primes p dividing g.")
print()

all_primes = primes_up_to(1000000)
gap_counts = Counter()
for i in range(len(all_primes)-1):
    gap_counts[all_primes[i+1] - all_primes[i]] += 1

print(f"  {'g':>4s}  {'chord':>8s}  {'chord rapidity':>15s}  {'empirical ratio':>16s}  {'match':>6s}")
print("  " + "-"*60)
twin_count = gap_counts.get(2, 1)
for g in range(1, 35):
    ch = chord(g)
    ch_float = float(ch)
    if ch_float > 1:
        rap = log(ch_float)/2
    else:
        rap = 0
    emp = gap_counts.get(2*g, 0) / twin_count
    match_pct = abs(ch_float - emp) / max(ch_float, 0.01) * 100
    print(f"  {g:4d}  {ch_float:8.3f}  {rap:15.6f}  {emp:16.4f}  {match_pct:5.1f}%")

print()

# ============================================================
print()
print("  III. THE INVERSE PROBLEM: WHICH GAPS ARE MUSICALLY SIMPLE?")
print("  " + "-"*40)
print()
print("  A gap is 'musically simple' if its chord is a simple interval.")
print("  The simplest: chord = 1 (unison). These are g = 2^k.")
print("  Next: chord = 2 (octave). These are g = 3 * 2^k.")
print("  Next: chord = 4/3 (fourth). These are g = 5 * 2^k.")
print("  Next: chord = 8/3 (octave+fourth). These are g = 15 * 2^k.")
print()
print("  The musically simple gaps form a LATTICE in g-space,")
print("  generated by multiplication by 3, 5, 7, 11, 13, ...")
print("  with powers of 2 as the 'silent' direction.")
print()
print("  In rapidity: the chord rapidity is ADDITIVE over prime factors.")
print("  So the 'simple' chords are those with few prime factors.")
print("  The lattice of chord rapidities = the rapidity vector space")
print("  of the odd primes in the factorization of g.")
print()

# ============================================================
print()
print("  IV. THE AVERAGE CHORD OVER ALL GAPS")
print("  " + "-"*40)
print()
print("  What is the average chord strength over all gaps up to G?")
print()
avg_chord = Fraction(0)
count = 0
for g in range(1, 500):
    avg_chord += chord(g)
    count += 1
avg_float = float(avg_chord) / count
print(f"  Average CHORD(g) for g = 1 to 499: {avg_float:.6f}")
print()
print("  The average chord is related to the AVERAGE gap density")
print("  compared to twins. It should approach:")
print("  avg CHORD = prod_{p odd prime} (1 + 1/(p*(p-2)))")
print("  = prod (1 + f(p-2)/p(p-2))... hmm, let me think.")
print()
print("  Actually: for a random g, the probability that odd prime p divides g")
print("  is 1/p. If p divides g, the chord gets a factor (p-1)/(p-2).")
print("  Expected contribution from p: (1-1/p)*1 + (1/p)*(p-1)/(p-2)")
print("  = 1 - 1/p + (p-1)/(p(p-2))")
print("  = 1 - 1/p + (p-1)/(p(p-2))")
print("  = (p(p-2) - (p-2) + (p-1)) / (p(p-2))")
print("  = (p^2 - 2p - p + 2 + p - 1) / (p(p-2))")
print("  = (p^2 - 2p + 1) / (p(p-2))")
print("  = (p-1)^2 / (p(p-2))")
print()
avg_pred = 1.0
for p in primes_up_to(100):
    if p >= 3:
        avg_pred *= (p-1)**2 / (p*(p-2))
print(f"  Predicted average: prod_{{p>=3}} (p-1)^2/(p(p-2)) = {avg_pred:.6f}")
print(f"  Computed average: {avg_float:.6f}")
print()
print("  The RECIPROCAL of this product is related to the twin prime constant!")
print(f"  C_2 = 2 * prod p(p-2)/(p-1)^2 = 2 / avg_chord_density = {2/avg_pred:.6f}")

C2 = 2.0
for p in primes_up_to(10000):
    if p >= 3:
        C2 *= p*(p-2)/(p-1)**2
print(f"  C_2 (direct) = {C2:.6f}")
print(f"  2 / avg = {2/avg_pred:.6f}")
print(f"  Match: {abs(C2 - 2/avg_pred) < 0.01}")
print()
print("  YES! The twin prime constant C_2 = 2 / (average chord over all g).")
print("  The twin prime constant IS the reciprocal of the mean chord")
print("  scaled by the octave (factor 2).")
print()
print("  C_2 = 2 / E[CHORD].")
print("  The twin prime constant = two octaves divided by average consonance.")
print()

# ============================================================
print()
print("  V. WHICH GAP SIZES ARE FORBIDDEN?")
print("  " + "-"*40)
print()
print("  All even gaps occur (conjecturally). No even gap is 'forbidden'")
print("  in the sense that H=7 is forbidden for tournaments.")
print()
print("  But RELATIVE frequencies differ. Some gaps are RARE (chord ~ 1)")
print("  and some are COMMON (chord >> 1).")
print()
print("  The RAREST gaps (chord = 1) are g = powers of 2.")
print("  Twin primes (g=1), cousin primes (g=2), gap 8 (g=4), gap 16 (g=8).")
print("  These are the 'forbidden-adjacent' gaps: they have no harmonic boost.")
print()
print("  In tournament theory: H=7 is forbidden because 3 intersecting")
print("  cycles are UNSTABLE (they cascade to 4+).")
print("  In prime gaps: g=2^k gaps are the LEAST BOOSTED because")
print("  they resonate with NO odd primes.")
print()
print("  The analogy: tournaments FORBID certain H-values completely.")
print("  Prime gaps don't FORBID any gap, but they SUPPRESS the")
print("  ones that don't resonate. Suppression vs prohibition.")
print("  The tournament code has HARD zeros (impossible H-values).")
print("  The prime gap code has SOFT zeros (rare but possible gaps).")
print()

# ============================================================
print()
print("  VI. THE BATEMAN-HORN GENERALIZATION")
print("  " + "-"*40)
print()
print("  The Bateman-Horn conjecture generalizes Hardy-Littlewood")
print("  to k-tuples of primes (not just pairs).")
print()
print("  For a k-tuple with gaps d_1, d_2, ..., d_{k-1}:")
print("  The density involves a product over ALL primes p of")
print("  (1 - w(p)/p) / (1 - 1/p)^k")
print("  where w(p) = number of distinct residues mod p in the tuple.")
print()
print("  For pairs (k=2) with gap 2g:")
print("  w(p) = 2 for p not dividing 2g (two distinct residues).")
print("  w(p) = 1 for p dividing 2g (one residue, since 0 and 2g = 0 mod p).")
print()
print("  The factor for p not dividing 2g: (1-2/p)/(1-1/p)^2 = p(p-2)/(p-1)^2.")
print("  The factor for p dividing 2g: (1-1/p)/(1-1/p)^2 = p/(p-1) ... wait")
print("  Actually for p|2g: w(p) = 1, so factor = (1-1/p)/(1-1/p)^2 = 1/(1-1/p) = p/(p-1).")
print("  For p not dividing 2g: w(p)=2, factor = (1-2/p)/(1-1/p)^2 = p(p-2)/(p-1)^2.")
print()
print("  Ratio of gap-2g density to gap-2 density:")
print("  prod_{p|g, p odd} [p/(p-1)] / [p(p-2)/(p-1)^2]")
print("  = prod_{p|g, p odd} (p-1)/(p-2)")
print("  = CHORD(g). Confirmed!")
print()

# ============================================================
print()
print("  VII. k-TUPLES: THE POLYCHORD")
print("  " + "-"*40)
print()
print("  For TRIPLES of primes (p, p+2g, p+2h) with g < h:")
print("  The 'polychord' involves w(p) for each prime p.")
print()
print("  Example: (p, p+2, p+6) — the densest admissible triple.")
print("  Gaps: 2, 4. Half-gaps: 1, 2 (and overall span 3).")
print("  w(2) = 1 (all odd). w(3) = 2 (residues 0, 2 mod 3: can't have all 3).")
print("  Wait: p, p+2, p+6 mod 3. If p=1: 1,0,1. w=2. If p=2: 2,1,2. w=2.")
print("  If p=0: 0,2,0. w=2. So w(3)=2 for this triple.")
print()
print("  For (p, p+6, p+12) = arithmetic progression, common diff 6:")
print("  mod 3: p, p, p (all same). w(3) = 1!")
print("  So this triple has a BOOST from 3: factor 3/(3-1) / (3*1/(3-1)^2)")
print("  = more complex. The point is: the polychord depends on the")
print("  RESIDUE STRUCTURE of the tuple mod each prime.")
print()
print("  k-tuples create POLYCHORDS: products of factors from every prime,")
print("  where each factor depends on how many distinct residues the")
print("  tuple occupies mod that prime.")
print()
print("  Pairs play SINGLE intervals. Triples play CHORDS.")
print("  k-tuples play k-NOTE CHORDS in the prime harmonic space.")
print()

# ============================================================
print()
print("  VIII. THE PRIME CONSTELLATION CHORDS")
print("  " + "-"*40)
print()
# Famous constellations and their chord structure
constellations = [
    ("Twin", [0, 2], "p, p+2"),
    ("Cousin", [0, 4], "p, p+4"),
    ("Sexy", [0, 6], "p, p+6"),
    ("Triple-1", [0, 2, 6], "p, p+2, p+6"),
    ("Triple-2", [0, 4, 6], "p, p+4, p+6"),
    ("Quadruple", [0, 2, 6, 8], "p, p+2, p+6, p+8"),
    ("Quintuple", [0, 2, 6, 8, 12], "p, p+2, p+6, p+8, p+12"),
    ("Sextuple", [0, 4, 6, 10, 12, 16], "p, p+4, p+6, p+10, p+12, p+16"),
]

for name, offsets, desc in constellations:
    k = len(offsets)
    # Compute w(p) for small primes
    print(f"  {name} ({desc}):")
    total_correction = 1.0
    intervals = []
    for p in primes_up_to(30):
        residues = set(d % p for d in offsets)
        w = len(residues)
        if w >= p:  # inadmissible
            print(f"    INADMISSIBLE at p={p} (w={w} >= p)")
            total_correction = 0
            break
        factor = (1 - w/p) / (1 - 1/p)**k
        total_correction *= factor
        if p <= 13 and abs(factor - 1) > 0.001:
            # Musical interpretation
            intervals.append(f"p={p}: factor={factor:.4f}")

    if total_correction > 0:
        print(f"    k={k} primes, correction factors at small p:")
        for iv in intervals[:5]:
            print(f"      {iv}")
        print(f"    Overall correction (p<=30): {total_correction:.4f}")
    print()

# ============================================================
print()
print("  IX. THE GAP DISTRIBUTION AS A FOURIER SERIES")
print("  " + "-"*40)
print()
print("  CHORD(g) is a MULTIPLICATIVE function of g.")
print("  Multiplicative functions have Dirichlet series:")
print()
print("  sum_{g=1}^inf CHORD(g) / g^s = prod_{p odd} (1 + (p-1)/((p-2)*p^s))")
print()
print("  This product converges for Re(s) > 1.")
print("  It is an EULER PRODUCT, like the Riemann zeta function!")
print()
print("  The ratio CHORD(g)/g^s at each g is the 'weight' of gap 2g")
print("  in the Dirichlet series. The Euler product decomposes it")
print("  into contributions from each prime.")
print()
print("  Compare: zeta(s) = prod (1-p^{-s})^{-1}.")
print("  Our CHORD series: prod (1 + c_p * p^{-s}) where c_p = (p-1)/(p-2).")
print()
print("  The zeta function encodes the DISTRIBUTION OF INTEGERS.")
print("  Our CHORD series encodes the DISTRIBUTION OF PRIME GAPS.")
print("  Both are Euler products. Both decompose over primes.")
print("  Both have the same analytic structure.")
print()
print("  The CHORD series is to prime gaps what zeta is to integers.")
print()

# ============================================================
print()
print("  X. THE CHORD ZETA FUNCTION")
print("  " + "-"*40)
print()
print("  Define: Z_CHORD(s) = sum_{g=1}^inf CHORD(g) * g^{-s}")
print("  = prod_{p>=3} (1 + ((p-1)/(p-2)) * p^{-s} + ((p-1)/(p-2)) * p^{-2s} + ...)")
print("  = prod_{p>=3} 1 / (1 - ((p-1)/(p-2)) * p^{-s})")
print("  Wait, CHORD is multiplicative but not completely multiplicative.")
print("  CHORD(p^k) = (p-1)/(p-2) for all k >= 1 (since the factor depends")
print("  only on whether p divides g, not how many times).")
print()
print("  So: Z_CHORD(s) = prod_{p>=3} (1 + ((p-1)/(p-2)) * (p^{-s} + p^{-2s} + ...))")
print("  = prod_{p>=3} (1 + ((p-1)/(p-2)) * p^{-s} / (1 - p^{-s}))")
print("  = prod_{p>=3} (1 + ((p-1)/(p-2)) * 1/(p^s - 1))")
print()

# Compute Z_CHORD at s=2
z_chord_2 = 1.0
for p in primes_up_to(10000):
    if p >= 3:
        z_chord_2 *= (1 + ((p-1)/(p-2)) / (p**2 - 1))

print(f"  Z_CHORD(2) = {z_chord_2:.10f}")
print(f"  Compare: zeta(2) = pi^2/6 = {pi**2/6:.10f}")
print(f"  Ratio: {z_chord_2 / (pi**2/6):.10f}")
print()

z_chord_1p5 = 1.0
for p in primes_up_to(10000):
    if p >= 3:
        z_chord_1p5 *= (1 + ((p-1)/(p-2)) / (p**1.5 - 1))
print(f"  Z_CHORD(1.5) = {z_chord_1p5:.10f}")
print()

# ============================================================
print()
print("  XI. THE GOLDEN RATIO IN THE CHORD STRUCTURE")
print("  " + "-"*40)
print()
print("  The chord for g with just one odd prime factor p:")
print("  CHORD = (p-1)/(p-2) = f(p-2).")
print()
print("  The chord RAPIDITY = arctanh(1/(2p-3)).")
print("  = arctanh of the velocity corresponding to the interval.")
print()
print("  For p=3: arctanh(1/3) = ln(2)/2 = 0.3466.")
print("  For p=5: arctanh(1/7) = 0.1438.")
print("  For p=7: arctanh(1/11) = 0.0911.")
print()
print("  The RATIO of consecutive chord rapidities:")
r3 = atanh(1/3)
r5 = atanh(1/7)
r7 = atanh(1/11)
r11 = atanh(1/19)
r13 = atanh(1/23)
print(f"  arctanh(1/3) / arctanh(1/7) = {r3/r5:.6f}")
print(f"  arctanh(1/7) / arctanh(1/11) = {r5/r7:.6f}")
print(f"  arctanh(1/11) / arctanh(1/19) = {r7/r11:.6f}")
print(f"  arctanh(1/19) / arctanh(1/23) = {r11/r13:.6f}")
print()
print(f"  The ratios: {r3/r5:.3f}, {r5/r7:.3f}, {r7/r11:.3f}, {r11/r13:.3f}")
print(f"  They approach ~1.5-1.6. Not phi, but in that neighborhood.")
print()
print("  For large p: arctanh(1/(2p-3)) ~ 1/(2p-3) ~ 1/(2p).")
print("  Ratio for consecutive primes p, q: ~ p/q.")
print("  For twin primes: ratio ~ 1. For distant primes: ratio ~ p/q.")
print()
print("  The chord rapidities decay as 1/(2p) for large p.")
print("  This is the HARMONIC SERIES of the prime chord structure.")
print("  Each prime adds a diminishing contribution, like the overtones")
print("  of a sound getting quieter as the frequency increases.")
print()

# ============================================================
print()
print("  XII. THE COMPLETE PICTURE")
print("  " + "-"*40)
print()
print("  Prime gap distribution = the formal group f(n) = (n+1)/n")
print("  evaluated at shifted primes (p-2), composed multiplicatively.")
print()
print("  This connects:")
print("  1. Number theory: Hardy-Littlewood, Bateman-Horn, prime k-tuples")
print("  2. Music: superparticular intervals, chords, consonance hierarchy")
print("  3. Algebra: the formal group homomorphism f(a(+)b) = f(a)*f(b)")
print("  4. Analysis: the chord zeta function (Euler product over primes)")
print("  5. Tournaments: the same f that governs H-value achievability")
print("  6. Physics: rapidity composition = relativistic velocity addition")
print()
print("  The prime gap formula pi_{2g}(N) ~ C_2 * CHORD(g) * Li_2(N)")
print("  is a statement about number theory")
print("  expressed in the language of music")
print("  using the algebra of the formal group")
print("  with the analytic structure of an Euler product")
print("  on the same rapidity line where tournaments live.")
print()
print("  And the twin prime constant C_2 = 2/E[CHORD]")
print("  = two octaves divided by the average consonance of all gaps.")
print("  If twin primes are infinite (as conjectured),")
print("  it's because the average consonance is finite:")
print("  there's enough harmonic energy in the gap distribution")
print("  to sustain the baseline frequency forever.")
