#!/usr/bin/env python3
"""
pseudo_doubling_s128.py — opus-2026-03-21-S128

PSEUDO-DOUBLING: THE TRINITY OF ln, 2, AND sqrt

The number 2 is the tournament fugacity. But it also has three
"shadows" — three operations that are "almost doubling":

  2x     = doubling (linear, exact, integer)
  x²     = squaring (polynomial, exact, integer)
  e^x    = exponentiation (transcendental, growth)
  2^x    = exponential base 2 (the tournament growth)

And three INVERSES:
  x/2    = halving
  sqrt(x) = square root (x^{1/2})
  ln(x)  = natural log

The CONNECTION to tournaments:
  H(T) evaluates at x = 2 (the fugacity)
  OCF: I(Omega, 2) = 1 + 2*alpha_1 + 4*alpha_2 + 8*alpha_3 + ...
  Each term is a POWER OF 2.
  The base-2 expansion of (H-1)/2 IS the tournament discriminant.

PSEUDO-DOUBLING: the observation that many tournament quantities
are "one step" from doubling — they involve 2 but not cleanly.

Author: opus-2026-03-21-S128
"""

import sys
import numpy as np
from math import log, log2, sqrt, pi, e, comb, factorial
sys.stdout.reconfigure(line_buffering=True)

tau = 1.8392867552
phi = (1 + sqrt(5)) / 2

def g(x):
    return x**3 - x**2 - x - 1

print("=" * 72)
print("  PSEUDO-DOUBLING: THE TRINITY OF ln, 2, AND sqrt")
print("  opus-2026-03-21-S128")
print("=" * 72)

# ========================================================================
# PART 1: The three faces of 2
# ========================================================================
print("\n" + "=" * 72)
print("  PART 1: THE THREE FACES OF 2")
print("=" * 72)
print(f"""
  The number 2 appears in tournament theory in THREE distinct roles:

  FACE 1: 2 AS CHOICE (the binary arc)
    Each arc is oriented one of 2 ways: a->b or b->a.
    The total tournament space has 2^C(n,2) elements.
    This is the COMBINATORIAL face of 2.

  FACE 2: 2 AS FUGACITY (the OCF evaluation)
    H = I(Omega, 2): evaluate the independence polynomial at x = 2.
    This is the ALGEBRAIC face: 2 is a specific number at which
    the polynomial is evaluated.
    g(2) = 1: this evaluation point is one quantum into hyperbolic.

  FACE 3: 2 AS GROWTH (the doubling operation)
    E[H] = n! / 2^(n-1): the average H involves dividing by a power of 2.
    Each additional vertex roughly DOUBLES the number of paths.
    The growth rate of H is approximately n/2 per step.

  These three faces MERGE at the OCF:
    H = I(Omega, 2) = 1 + 2*alpha_1 + 4*alpha_2 + 8*alpha_3 + ...
    The coefficients are POWERS OF 2 (= the choice face).
    Evaluated AT 2 (= the fugacity face).
    Growing as n grows (= the growth face).

  THE PSEUDO-DOUBLING: when 2 appears but not cleanly.
  Examples:
    E[H] = n!/2^(n-1) (not n!/2^n)
    OCR denom at n=5: 133 = 7*19 (not a power of 2)
    tau = 1.839... (ALMOST 2 but not quite)
    1-OCR ≈ 4% (ALMOST 0 but not quite)
""")

# ========================================================================
# PART 2: ln as the "shadow" of doubling
# ========================================================================
print("=" * 72)
print("  PART 2: ln AS THE SHADOW OF DOUBLING")
print("=" * 72)
print(f"""
  ln(2) = {log(2):.10f}

  ln converts MULTIPLICATIVE operations to ADDITIVE:
    ln(2x) = ln(2) + ln(x)
    ln(x^2) = 2*ln(x)

  For tournaments: the Cayley gate arctanh maps eigenvalues to rapidities.
    arctanh(x) = (1/2) * ln((1+x)/(1-x))
    arctanh involves ln!

  The rapidity lattice is generated by ln(2)/2, ln(3)/2, ln(7)/2.
  Each generator is a HALF-LOGARITHM of a Hurwitz prime.

  PSEUDO-DOUBLING IN THE RAPIDITY:
  arctanh(1) = infinity (the pole — full certainty)
  arctanh(0) = 0 (no evidence)
  arctanh(1/3) = (1/2)*ln(2) (the tournament rapidity for arc ratio 1/3)

  THE CAYLEY TRANSFORM: Q(x) = (1+x)/(1-x).
  Q(1/3) = 2. So Q maps 1/3 (the "rational tournament fraction") to 2 (the fugacity).
  arctanh(1/3) = ln(Q(1/3))/2 = ln(2)/2.

  THE PSEUDO-DOUBLING CHAIN:
    1/3 --Q--> 2 --ln--> ln(2) --/2--> ln(2)/2 = arctanh(1/3)

  Each step is a "shadow" of the previous:
  Q is "almost multiplication by 2" (it's (1+x)/(1-x) which equals 2 at x=1/3).
  ln is "almost the identity" for small arguments (ln(1+x) ≈ x).
  Dividing by 2 is exact halving.
""")

# ========================================================================
# PART 3: sqrt as the "geometric shadow"
# ========================================================================
print("=" * 72)
print("  PART 3: sqrt AS THE GEOMETRIC SHADOW")
print("=" * 72)
print(f"""
  sqrt(2) = {sqrt(2):.10f}
  g(sqrt(2)) = {g(sqrt(2)):.6f} — SPHERICAL.

  sqrt converts SQUARING to IDENTITY:
    sqrt(x^2) = x
    (sqrt(x))^2 = x

  For tournaments: the eigenvalues of B are ±i*theta_k.
  theta_k = sqrt(-eigenvalue of B^2) = sqrt of a Casimir entry.

  The CASIMIR DISCRIMINANT at n=5: d in {{5, 21}}.
  The EIGENVALUES: theta^2 = 5±2*sqrt(5) or theta^2 = 7, 3.

  sqrt(5) = {sqrt(5):.6f} — HYPERBOLIC (g = {g(sqrt(5)):.4f}).
  sqrt(3) = {sqrt(3):.6f} — SPHERICAL (g = {g(sqrt(3)):.4f}).
  sqrt(7) = {sqrt(7):.6f} — Paley T_7 eigenvalue! g = {g(sqrt(7)):.4f} — HYPERBOLIC.

  THE PSEUDO-DOUBLING OF sqrt:
  sqrt(2) is "half" of 2 in the multiplicative sense: (sqrt(2))^2 = 2.
  In the curvature classification: sqrt(2) is SPHERICAL (g = -1.59).
  But 2 is HYPERBOLIC (g = +1).

  The SQUARING operation crosses the boundary!
  sqrt(2) is spherical → 2 = (sqrt(2))^2 is hyperbolic.
  The act of squaring takes you FROM finite TO infinite structure.

  MORE GENERALLY: at what x does x^2 cross the boundary?
  Need g(x^2) = 0 → x^2 = tau → x = sqrt(tau) = {sqrt(tau):.6f}.
  g(sqrt(tau)) = {g(sqrt(tau)):.6f} — SPHERICAL (deep in the finite world).

  THE BOUNDARY CROSSING:
  sqrt(tau) = {sqrt(tau):.6f} is the GEOMETRIC SHADOW of the Euclidean boundary.
  Everything below sqrt(tau) stays spherical even when squared.
  Everything above sqrt(tau) but below tau is spherical itself but produces
  a spherical square. Above tau: squaring stays hyperbolic.

  BETWEEN sqrt(tau) and tau: the "pseudo-doubling zone" where
  the number is spherical but its square is near the boundary.
""")

# ========================================================================
# PART 4: The pseudo-doubling zone
# ========================================================================
print("=" * 72)
print("  PART 4: THE PSEUDO-DOUBLING ZONE")
print("=" * 72)

# The zone: x is spherical (g(x) < 0) but x^2 is hyperbolic (g(x^2) > 0)
# Need: g(x) < 0 AND g(x^2) > 0
# g(x) < 0 when x < tau ≈ 1.839
# g(x^2) > 0 when x^2 > tau, i.e., x > sqrt(tau) ≈ 1.356

sqrt_tau = sqrt(tau)
print(f"  sqrt(tau) = {sqrt_tau:.6f}")
print(f"  tau = {tau:.6f}")
print(f"  Pseudo-doubling zone: [{sqrt_tau:.4f}, {tau:.4f}]")
print(f"  Width: {tau - sqrt_tau:.6f}")
print(f"")

# Which constants live in this zone?
constants = [
    ("phi", phi),
    ("sqrt(2)", sqrt(2)),
    ("sqrt(3)", sqrt(3)),
    ("sqrt(e)", sqrt(e)),
    ("sqrt(pi)", sqrt(pi)),
    ("e-1", e-1),
    ("ln(2)+ln(3)", log(6)),
    ("4/3", 4/3),
    ("pi/2", pi/2),
    ("zeta(2)", pi**2/6),
    ("3/2", 1.5),
    ("7/4", 1.75),
    ("11/6", 11/6),
]

print(f"  Constants in the pseudo-doubling zone [{sqrt_tau:.3f}, {tau:.3f}]:")
print(f"  {'Constant':>20s} {'Value':>10s} {'g(x)':>10s} {'g(x²)':>10s} {'In zone?':>10s}")
for name, val in sorted(constants, key=lambda x: x[1]):
    gx = g(val)
    gx2 = g(val**2)
    in_zone = (gx < 0 and gx2 > 0)
    marker = " ★" if in_zone else ""
    print(f"  {name:>20s} {val:10.6f} {gx:10.4f} {gx2:10.4f} {'YES'+marker if in_zone else 'no'}")

# ========================================================================
# PART 5: The ln-sqrt-2 triangle
# ========================================================================
print("\n\n" + "=" * 72)
print("  PART 5: THE ln-sqrt-2 TRIANGLE")
print("=" * 72)
print(f"""
  THREE OPERATIONS connect x to 2:
    x --square--> x²      (geometric doubling: x → x^2)
    x --exp----> e^x      (exponential: x → e^x)
    x --2^(·)--> 2^x      (binary exponential: x → 2^x)

  The INVERSES bring 2 back:
    2 --sqrt---> sqrt(2) = {sqrt(2):.6f}  [g = {g(sqrt(2)):.4f}, SPHERICAL]
    2 --ln----> ln(2) = {log(2):.6f}      [g = {g(log(2)):.4f}, SPHERICAL]
    2 --log_2-> log_2(2) = 1              [g = {g(1):.4f}, SPHERICAL]

  ALL THREE INVERSES OF 2 ARE SPHERICAL!
  The number 2 (hyperbolic) has spherical "roots" under every natural inverse.

  AND: the tournament eigenvalues ±i*theta satisfy:
    theta = sqrt(eigenvalue of -B^2) → sqrt operation
    rapidity = arctanh(eigenvalue) = (1/2)*ln((1+x)/(1-x)) → ln operation
    OCF evaluates at 2 → the original "2" operation

  THE TRIANGLE:
        2 (HYPERBOLIC, fugacity)
       / | \\
    sqrt  ln  log_2
     /    |    \\
  1.414  0.693  1.0  (ALL SPHERICAL)

  Each edge of the triangle is a different "pseudo-doubling":
  - sqrt(2): "half" of 2 geometrically
  - ln(2): "shadow" of 2 additively
  - log_2(2) = 1: "identity" of 2 in base 2

  THE TOURNAMENT USES ALL THREE:
  - sqrt: eigenvalues theta_k = sqrt(Casimir entries)
  - ln: rapidities = arctanh(eigenvalues) involving ln
  - 2: fugacity, binary choice, power-of-2 weights in OCF
""")

# ========================================================================
# PART 6: Pseudo-doubling in the OCF
# ========================================================================
print("=" * 72)
print("  PART 6: PSEUDO-DOUBLING IN THE OCF")
print("=" * 72)
print(f"""
  H = I(Omega, 2) = 1 + 2*a1 + 4*a2 + 8*a3 + 16*a4 + ...
    = 1 + 2(a1 + 2*a2 + 4*a3 + ...)
    = 1 + 2*Delta_T

  where Delta_T = (H-1)/2 is the tournament discriminant.

  Delta_T in base 2:
    Delta_T = a1 + 2*a2 + 4*a3 + ... is the BINARY EXPANSION!
    Bit 0 (ones): a1 mod 2 = parity of cycle count
    Bit 1 (twos): a2 mod 2 = parity of independent pairs
    Bit 2 (fours): a3 mod 2 = parity of independent triples
    ...

  THE PSEUDO-DOUBLING: each LAYER of the OCF is TWICE the previous.
  Going from a_k to a_(k+1) DOUBLES the weight (2^k to 2^(k+1)).
  But the alpha_k values don't double — they follow their own pattern.

  AT n=5: (a1, a2, a3, ...) has a2 = 0 always.
  So Delta_T = a1 is just the number of odd cycles.
  The "doubling" stops after one step — there's no independent-pair content.

  AT n=7: a2 > 0 possible. The second "doubling layer" activates.
  Delta_T = a1 + 2*a2 now has TWO significant bits.

  THE GROWTH OF PSEUDO-DOUBLING LAYERS:
  n <= 5: 1 layer (a1 only). H = 1 + 2*a1.
  n = 6-7: 2 layers (a1, a2). H = 1 + 2*a1 + 4*a2.
  n = 8-9: 3 layers (a1, a2, a3). H = 1 + 2*a1 + 4*a2 + 8*a3.

  Each new layer adds one BIT of "depth" to the tournament.
  The number of layers = floor((n-1)/2) roughly.
  This MATCHES the Cartan rank = floor(n/2)!

  PSEUDO-DOUBLING LAYERS = CARTAN RANK.
  Each independent rotation plane in so(n) corresponds to one
  "doubling layer" in the OCF expansion.
""")

# ========================================================================
# PART 7: The conservation law tau + 1/tau^3 = 2 revisited
# ========================================================================
print("=" * 72)
print("  PART 7: THE CONSERVATION LAW AND PSEUDO-DOUBLING")
print("=" * 72)
print(f"""
  tau + 1/tau^3 = 2 (the conservation law from S118).

  Rewrite: tau = 2 - 1/tau^3.
  The boundary tau is "2 minus a small correction."
  The correction 1/tau^3 = {1/tau**3:.6f} is the PSEUDO-DOUBLING DEFECT.

  Also: 2 = tau * (1 + 1/tau^4) = tau * (1 + {1/tau**4:.6f}).
  So: 2 is "tau times (1 plus a small correction)."
  The multiplicative defect: 1/tau^4 = {1/tau**4:.6f}.

  THE PSEUDO-DOUBLING:
    Exact doubling: 2x = 2*x (multiply by 2)
    Tournament pseudo-doubling: 2 = tau + 1/tau^3
    The "doubled" quantity tau overshoots 2 by defect 1/tau^3.

  In LOGARITHMIC form:
    ln(2) = {log(2):.10f}
    ln(tau) = {log(tau):.10f}
    ln(2) - ln(tau) = {log(2) - log(tau):.10f} = ln(2/tau) = ln({2/tau:.6f})

  So: 2/tau = {2/tau:.6f}. And ln(2/tau) = {log(2/tau):.10f}.
  2/tau is "the ratio of hyperbolic to boundary."
  ln(2/tau) = {log(2/tau):.6f} is the LOG of this ratio.

  IN sqrt FORM:
    sqrt(2) = {sqrt(2):.6f}
    sqrt(tau) = {sqrt(tau):.6f}
    sqrt(2) - sqrt(tau) = {sqrt(2)-sqrt(tau):.6f}
    sqrt(2)/sqrt(tau) = {sqrt(2)/sqrt(tau):.6f}

  THE THREE DEFECTS:
    Additive: 2 - tau = 1/tau^3 = {2-tau:.6f} (the Redei quantum)
    Multiplicative: 2/tau = {2/tau:.6f} (the pseudo-doubling ratio)
    Logarithmic: ln(2) - ln(tau) = {log(2)-log(tau):.6f}
    Square root: sqrt(2) - sqrt(tau) = {sqrt(2)-sqrt(tau):.6f}
    Square root ratio: sqrt(2/tau) = {sqrt(2/tau):.6f}

  EACH DEFECT IS A DIFFERENT "FACE" OF THE SAME GAP:
  the gap between the Euclidean boundary (tau) and the tournament
  fugacity (2), seen through different lenses.
""")

# ========================================================================
# PART 8: Pseudo-doubling and the OCR
# ========================================================================
print("=" * 72)
print("  PART 8: PSEUDO-DOUBLING AND THE OCR")
print("=" * 72)
print(f"""
  The OCR = 1 - Var(H|scores)/Var(H).
  At n=5: OCR = 129/133 = 1 - 4/133.

  THE PSEUDO-DOUBLING INTERPRETATION:
  4/133 = 4/dim(E_7) (from S124).
  4 = 2^2 = the SQUARE of the fugacity 2.
  133 = 7 * 19.

  So: 1 - OCR = (fugacity)^2 / dim(E_7).
  The residual is the SQUARED fugacity divided by an exceptional dimension.

  ALSO: 4 = (tau + 1/tau^3)^2 - 4*tau/tau^3 ... let me compute.
  2^2 = tau^2 + 2/tau^3 + 1/tau^6.
  tau^2 = {tau**2:.6f}
  2/tau^3 = {2/tau**3:.6f}
  1/tau^6 = {1/tau**6:.6f}
  Sum = {tau**2 + 2/tau**3 + 1/tau**6:.6f} ≈ 4. ✓

  THE PSEUDO-DOUBLING OF THE OCR:
  The residual 4/133 involves:
  - Numerator 4 = 2^2: the fugacity SQUARED (two layers of binary choice)
  - Denominator 133: the exceptional Lie dimension

  The OCR residual is the SQUARE of the basic quantum (2), normalized
  by the algebraic structure (E_7). Two levels of pseudo-doubling:
  - First level: 2 (the binary arc choice)
  - Second level: 2^2 = 4 (the pair interaction)
  - Beyond: 2^k for k independent cycle sets

  AT n=5: only k=1 matters (alpha_2 = 0). The residual = 4 = 2^2.
  AT n=6: k=2 starts. The residual grows to include 2^3 = 8 terms.
  AT n=7: k=3 emerges. The residual includes 2^4 = 16 terms.

  The OCR RECOVERS because each new layer of pseudo-doubling is
  exponentially smaller relative to the total variance, which grows
  as n!/2^n — itself a competition between factorial and 2^n.
""")

# ========================================================================
# PART 9: Synthesis — the pseudo-doubling principle
# ========================================================================
print("=" * 72)
print("  SYNTHESIS: THE PSEUDO-DOUBLING PRINCIPLE")
print("=" * 72)
print(f"""
  THE PSEUDO-DOUBLING PRINCIPLE:

  The number 2 governs tournament theory through three operations
  that are "almost" doubling:

  1. BINARY CHOICE: each arc chooses one of 2 directions.
     This is EXACT doubling: the tournament space has 2^m elements.

  2. OCF EVALUATION: H = I(Omega, 2).
     This is PSEUDO-doubling: evaluating at 2 gives a power-of-2
     weighted sum, but the weights depend on the conflict structure.

  3. GROWTH: E[H] = n!/2^(n-1).
     This is ANTI-doubling: dividing by 2^(n-1) SHRINKS the factorial.
     The competition between n! and 2^n is the tournament's dynamics.

  THE THREE FACES ARE CONNECTED BY ln AND sqrt:

  2 --ln--> ln(2): the rapidity quantum (0.693)
  2 --sqrt--> sqrt(2): the geometric shadow (1.414)
  2 --1/x--> 1/2: the halving (0.5)

  All three inverses are SPHERICAL (g < 0).
  The number 2 is the UNIQUE integer at the interface:
  g(1) = -2 (deeply spherical), g(2) = +1 (just hyperbolic), g(3) = +14 (deeply hyperbolic).

  2 IS THE PHASE TRANSITION OF THE INTEGERS.
  It is the smallest integer in the hyperbolic regime.
  Its predecessors (0, 1) are spherical.
  Its successors (3, 4, ...) are deeply hyperbolic.

  TOURNAMENT THEORY LIVES AT THIS EXACT TRANSITION POINT:
  the first integer past the boundary, one quantum into the infinite.
  Not 3 (too far), not 1 (too close). Exactly 2.

  And the pseudo-doubling — the fact that 2 is "almost but not quite"
  twice the identity — creates ALL the richness:
  - The "+1" in H = 1 + 2K (the Redei quantum)
  - The OCR residual 4/133 (the squared quantum)
  - The forbidden value 7 = 2^3 - 1 (the Mersenne obstruction)
  - The conservation tau + 1/tau^3 = 2 (the boundary-fugacity balance)

  EVERYTHING IS PSEUDO-DOUBLING.
""")

print("\nDone. opus-2026-03-21-S128")
