#!/usr/bin/env python3
"""rapidity_computing_s116e.py — Computer science, cryptography, and information theory
through the rapidity lens.

Rapidity = arctanh(v) = logit/2 = ln(Q)/2 where Q(x)=(1+x)/(1-x).
Key theorem: f(n)=(n+1)/n is a multiplicative homomorphism for rapidity composition.
"""
from math import sqrt, log, pi, exp, atanh, tanh, comb, factorial, log2
from fractions import Fraction

print("COMPUTER SCIENCE AND INFORMATION THEORY THROUGH RAPIDITY")
print("="*70)
print()

# ============================================================
print("="*70)
print("1. BINARY REPRESENTATIONS AND RAPIDITY")
print("="*70)
print()
print("  A binary string of length n represents a number in [0, 2^n - 1].")
print("  The information content = n bits = n * ln(2) nats.")
print("  rapidity(2^n) = n * ln(2)/2 = n * octave.")
print()
print("  EACH BIT ADDS ONE OCTAVE OF RAPIDITY.")
print("  This is the same as: each cell division adds one octave (biology).")
print("  And: each DNA base adds one octave of sequence space.")
print()
print("  Standard data types and their rapidity:")
print("  Type      Bits   Max value        rapidity(max)")
print("  " + "-"*55)
for name, bits in [("byte", 8), ("short", 16), ("int", 32), ("long", 64),
                    ("uint128", 128), ("uint256", 256)]:
    maxval = 2**bits - 1
    rap = log(maxval)/2
    print(f"  {name:<10s} {bits:4d}   2^{bits}-1            {rap:10.2f} ({bits:.0f} octaves)")

print()
print("  Cryptographic key lengths in rapidity:")
print("  AES-128: rapidity = {:.0f} octaves".format(128 * log(2)/2 / (log(2)/2)))
print("  AES-256: rapidity = {:.0f} octaves".format(256))
print("  RSA-2048: rapidity = {:.0f} octaves".format(2048))
print("  The security level IS the rapidity in octaves!")
print()

# ============================================================
print("="*70)
print("2. HASH FUNCTIONS AND BIRTHDAY PARADOX IN RAPIDITY")
print("="*70)
print()
print("  A hash function with n-bit output has 2^n possible values.")
print("  Birthday collision after ~2^{n/2} hashes.")
print("  rapidity(collision threshold) = n/2 * ln(2)/2 = n*ln(2)/4")
print("  = half the rapidity of the output space.")
print()
print("  For SHA-256: output space rapidity = 256 octaves.")
print("  Collision threshold rapidity = 128 octaves.")
print("  The birthday paradox HALVES the rapidity!")
print()
print("  For SHA-3-512: output space = 512 octaves, collision = 256.")
print()

# ============================================================
print("="*70)
print("3. SORTING AND COMPARISON COMPLEXITY")
print("="*70)
print()
print("  Sorting n items requires at least log2(n!) comparisons.")
print("  Stirling: log2(n!) ~ n*log2(n) - n*log2(e)")
print("  In rapidity: rapidity(n!) = ln(n!)/2 ~ n*ln(n)/2 - n/2")
print("  = n * rapidity(n) - n/2")
print()
print("  The information-theoretic lower bound for sorting")
print("  IS the rapidity of n! (times 2/ln(2) for bits).")
print()
print("  n    n!           rapidity(n!)   log2(n!)    n*log2(n)")
print("  " + "-"*60)
for n in [2, 3, 4, 5, 7, 10, 20, 52]:
    fn = factorial(n) if n <= 20 else float('inf')
    if fn < float('inf'):
        rap = log(fn)/2
        lg = log2(fn)
        nlgn = n * log2(n)
        print(f"  {n:3d}  {fn:14.0f}   {rap:10.2f}      {lg:8.1f}      {nlgn:8.1f}")
    else:
        rap = n * log(n)/2 - n/2
        lg = n * log2(n) - n/log(2)
        nlgn = n * log2(n)
        print(f"  {n:3d}  {'(huge)':>14s}   {rap:10.2f}      {lg:8.1f}      {nlgn:8.1f}")

print()
print("  Sorting a deck of 52 cards: rapidity ~ 116.")
print("  Compare: rapidity of the observable universe in Planck units ~ 140.")
print("  A deck of cards is {:.0f}% of the universe's rapidity!".format(116/140*100))
print()

# ============================================================
print("="*70)
print("4. CHANNEL CAPACITY AND RAPIDITY")
print("="*70)
print()
print("  Shannon's channel capacity: C = B * log2(1 + SNR)")
print("  where B = bandwidth, SNR = signal-to-noise ratio.")
print()
print("  In rapidity: log2(1+SNR) = 2*rapidity(SNR/(SNR+2)) / ln(2)")
print("  Actually: 1+SNR = Q(SNR/(SNR+2)), so")
print("  log2(1+SNR) = 2*rapidity(SNR/(SNR+2)) / ln(2)")
print()
print("  But more directly: define v = (SNR)/(SNR+2) = (1+SNR-1)/(1+SNR+1).")
print("  Then Q(v) = 1+SNR, and rapidity(v) = ln(1+SNR)/2.")
print("  So C/B = 2*rapidity(v)/ln(2).")
print()
print("  Channel capacity per bandwidth = rapidity / (ln(2)/2).")
print()
print("  SNR(dB)  SNR(linear)  v=SNR/(SNR+2)  rapidity   C/B (bits/Hz)")
print("  " + "-"*65)
for snr_db in [0, 3, 6, 10, 20, 30, 40, 60]:
    snr = 10**(snr_db/10)
    v = snr/(snr+2)
    rap = atanh(v) if v < 0.9999 else log(1+snr)/2
    c_per_b = log2(1+snr)
    print(f"  {snr_db:5d}     {snr:10.1f}    {v:10.6f}    {rap:8.4f}    {c_per_b:8.2f}")

print()

# ============================================================
print("="*70)
print("5. ERROR CORRECTING CODES AND RAPIDITY")
print("="*70)
print()
print("  A code with rate R = k/n transmits k bits over n symbols.")
print("  The code rate R in [0,1] has rapidity arctanh(2R-1).")
print()
print("  Shannon limit: R < C/B for reliable transmission.")
print("  In rapidity: rapidity(2R-1) < rapidity(2C/B - 1).")
print()
print("  For binary symmetric channel with crossover p:")
print("  Capacity C = 1 - H(p) where H(p) = -p*log2(p) - (1-p)*log2(1-p)")
print()
print("  Common code rates and their rapidity:")
print("  Rate    rapidity    interpretation")
print("  " + "-"*45)
for R in [1/2, 2/3, 3/4, 4/5, 7/8, 1/3, 1/4]:
    f = Fraction(R).limit_denominator(100)
    rap = atanh(2*R - 1)
    print(f"  {str(f):>5s}   {rap:+8.4f}     {'repetition' if R < 0.4 else 'standard' if R < 0.8 else 'high rate'}")

print()
print("  The rapidity of 1/2 rate = 0 (the FAIR POINT).")
print("  Above 1/2: positive rapidity (more data than redundancy).")
print("  Below 1/2: negative rapidity (more redundancy than data).")
print()

# ============================================================
print("="*70)
print("6. FLOATING POINT AND RAPIDITY")
print("="*70)
print()
print("  IEEE 754 floating point: x = m * 2^e (mantissa * 2^exponent).")
print("  The EXPONENT e IS a rapidity (in octaves):")
print("  rapidity(x) = ln(x)/2 = (e*ln(2) + ln(m))/2")
print("  ~ e * ln(2)/2 = e * octave (for m ~ 1)")
print()
print("  So floating point representation IS rapidity representation!")
print("  The exponent = rapidity in octaves.")
print("  The mantissa = fine structure within the octave.")
print()
print("  This is WHY floating point works well for physical quantities:")
print("  physical laws involve RATIOS (rapidity differences),")
print("  and floating point preserves rapidity structure.")
print()
print("  Float types and their rapidity range:")
print("  Type       Exp bits   Rapidity range (octaves)")
print("  " + "-"*50)
for name, exp_bits, bias in [("float16", 5, 15), ("float32", 8, 127),
                               ("float64", 11, 1023), ("float128", 15, 16383)]:
    min_exp = 1 - bias
    max_exp = (2**exp_bits - 2) - bias
    print(f"  {name:<10s}   {exp_bits:4d}      [{min_exp}, {max_exp}]")

print()

# ============================================================
print("="*70)
print("7. PROBABILITY CALIBRATION AND RAPIDITY")
print("="*70)
print()
print("  A classifier outputs probability p. Its calibration measures")
print("  how well p matches the true frequency of positive outcomes.")
print()
print("  In rapidity space, perfect calibration means:")
print("  rapidity(predicted) = rapidity(observed)")
print()
print("  The calibration ERROR in rapidity:")
print("  delta_rapidity = arctanh(2*p_pred - 1) - arctanh(2*p_obs - 1)")
print()
print("  This is BETTER than raw probability difference because:")
print("  - It handles extreme probabilities correctly (0.001 vs 0.002 is big!)")
print("  - It's symmetric in log-odds space")
print("  - It's equivalent to the natural parameter of the Bernoulli family")
print()
print("  Example: classifier on rare events")
print("  Predicted  Observed  Raw diff   Rapidity diff")
print("  " + "-"*50)
for p_pred, p_obs in [(0.01, 0.02), (0.10, 0.11), (0.50, 0.55),
                       (0.90, 0.91), (0.99, 0.995)]:
    raw = p_pred - p_obs
    rap = atanh(2*p_pred-1) - atanh(2*p_obs-1)
    print(f"  {p_pred:.3f}      {p_obs:.3f}     {raw:+.4f}     {rap:+.4f}")

print()
print("  Rapidity calibration reveals that 0.01->0.02 is a MUCH bigger")
print("  error than 0.50->0.55, unlike raw probability difference.")
print()

# ============================================================
print("="*70)
print("8. SEARCH ALGORITHMS AND RAPIDITY")
print("="*70)
print()
print("  Binary search on n items: log2(n) comparisons.")
print("  = 2*rapidity(n)/ln(2) comparisons.")
print()
print("  Each binary search step HALVES the search space,")
print("  which SUBTRACTS one octave of rapidity.")
print("  Binary search = walking DOWN the rapidity ladder, one octave at a time.")
print()
print("  Grover's quantum search: sqrt(n) evaluations.")
print("  = n^{1/2} evaluations.")
print("  rapidity(sqrt(n)) = rapidity(n)/2.")
print("  Grover's algorithm HALVES the rapidity (not the search space).")
print()
print("  Comparison:")
print("  n         Binary: log2(n)   Grover: sqrt(n)   Classical: n")
print("  " + "-"*60)
for n in [16, 256, 65536, 2**20, 2**30]:
    bin_search = log2(n)
    grover = sqrt(n)
    print(f"  2^{int(log2(n)):2d}      {bin_search:8.0f}         {grover:12.0f}        {n:>12d}")

print()
print("  Binary search: rapidity decreases by 1 octave per step.")
print("  Grover: rapidity decreases by HALF per step (quadratic speedup).")
print("  Linear search: rapidity decreases by 0 per step (just decrement).")
print()

# ============================================================
print("="*70)
print("9. BLOCKCHAIN AND PROOF OF WORK")
print("="*70)
print()
print("  Bitcoin mining: find nonce such that SHA256(block||nonce) < target.")
print("  The target has d leading zero bits.")
print("  Expected attempts: 2^d.")
print("  rapidity(2^d) = d * ln(2)/2 = d octaves.")
print()
print("  The mining DIFFICULTY in rapidity = d octaves.")
print("  Each additional bit of difficulty = one more octave of work.")
print()
print("  Bitcoin difficulty adjustment: target rate = 1 block / 10 min.")
print("  If blocks come too fast, increase d (add rapidity).")
print("  If blocks come too slow, decrease d (remove rapidity).")
print("  The difficulty IS a rapidity dial.")
print()
print("  Current Bitcoin difficulty ~ 2^76:")
print("  rapidity = 76 octaves = 76 * ln(2)/2 = {:.1f} rapidity units".format(76*log(2)/2))
print()

# ============================================================
print("="*70)
print("10. THE RAPIDITY OF ALGORITHMIC COMPLEXITY CLASSES")
print("="*70)
print()
print("  For input size n, the runtime of different complexity classes:")
print()
print("  Class        Runtime f(n)     rapidity(f(n))")
print("  " + "-"*50)
print("  O(1)         constant         0 (at rest)")
print("  O(log n)     log n            ln(ln(n))/2 (doubly slow)")
print("  O(n)         n                ln(n)/2 (linear in rapidity)")
print("  O(n log n)   n*log(n)         ln(n*log(n))/2")
print("  O(n^2)       n^2              ln(n) (quadratic = double rapidity)")
print("  O(n^3)       n^3              3*ln(n)/2 (triple rapidity)")
print("  O(2^n)       2^n              n*ln(2)/2 (linear in n octaves!)")
print("  O(n!)        n!               n*ln(n)/2 - n/2 (superlinear)")
print()
print("  KEY INSIGHT: polynomial classes have rapidity ~ c*ln(n)/2 = c*rapidity(n).")
print("  Exponential classes have rapidity ~ c*n = LINEAR in n (not log n).")
print("  The P vs NP question in rapidity:")
print("  P:  rapidity(runtime) = O(rapidity(n))")
print("  NP: rapidity(runtime) = O(n) (rapidity grows with INPUT, not log)")
print("  The gap between P and NP IS the gap between logarithmic and linear rapidity.")
print()

# ============================================================
print("="*70)
print("11. REED-SOLOMON CODES AND THE CAYLEY TRANSFORM")
print("="*70)
print()
print("  Reed-Solomon codes evaluate polynomials at roots of unity.")
print("  We proved: Q maps the n-th root of unity e^{2pi*i*k/n}")
print("  to i*cot(pi*k/n) on the imaginary axis.")
print()
print("  So the Cayley transform of a Reed-Solomon codeword is a")
print("  set of points on the imaginary axis!")
print()
print("  The SYNDROME computation (detecting errors) becomes:")
print("  evaluation of Q-transformed polynomial at cotangent points.")
print()
print("  This might give a new perspective on RS decoding:")
print("  errors in the codeword = perturbations of cotangent values.")
print("  The error-locator polynomial in Cayley coordinates might")
print("  have nicer properties than in the standard formulation.")
print()

# ============================================================
print("="*70)
print("12. MACHINE LEARNING: TEMPERATURE SCALING = RAPIDITY SCALING")
print("="*70)
print()
print("  In softmax with temperature T:")
print("  P_i = exp(z_i/T) / sum exp(z_j/T)")
print()
print("  For binary classification (2 classes):")
print("  P = sigmoid(z/T) = sigmoid(logit/T)")
print("  Since logit = 2*rapidity:")
print("  P = sigmoid(2*rapidity/T)")
print()
print("  Temperature scaling DIVIDES the rapidity by T.")
print("  T = 1: standard rapidity")
print("  T > 1: compressed rapidity (less confident)")
print("  T < 1: expanded rapidity (more confident)")
print("  T -> 0: argmax (infinite rapidity expansion)")
print("  T -> inf: uniform (rapidity compressed to 0)")
print()
print("  MODEL CALIBRATION by temperature scaling:")
print("  Find T* that minimizes calibration error IN RAPIDITY SPACE.")
print("  This is EXACTLY the standard temperature scaling recipe,")
print("  but the rapidity interpretation shows WHY it works:")
print("  you're finding the right rapidity SCALE for the problem.")
print()

# ============================================================
print("="*70)
print("GRAND SUMMARY: CS THROUGH RAPIDITY")
print("="*70)
print()
print("  CS CONCEPT               RAPIDITY IS")
print("  " + "-"*55)
print("  bits                     octaves of rapidity")
print("  floating point exponent  rapidity in octaves")
print("  binary search step       -1 octave")
print("  Grover quantum step      -1/2 of remaining rapidity")
print("  sorting lower bound      rapidity of n!")
print("  channel capacity         rapidity / (ln(2)/2)")
print("  code rate                arctanh(2R-1)")
print("  hash collision           half the output rapidity")
print("  mining difficulty        d octaves")
print("  P vs NP gap              log(rapidity) vs linear rapidity")
print("  temperature scaling      rapidity division by T")
print("  calibration error        rapidity difference")
print()
print("  EVERYTHING in CS that uses log2 is using rapidity in octaves.")
print("  EVERYTHING that uses log-odds is using rapidity directly.")
print("  The bit IS the octave. The logit IS twice the rapidity.")
