#!/usr/bin/env python3
"""reduction_dag_recursion_modes_boxeph_S196.py -- boxeph-2026-07-21-S196

Owner: think about the signed recursion modes A+B+C-D-E-F=G, A+B-C+D-E-F+G, A+B-C as LITERAL
subtournaments; which iso classes come from smaller subtournament classes through them.

CLAIM: the three sign-strings are circulant CHARACTER patterns.
  mode1 +++--- = sign(sin 2πk/7) = interval connection set {1,2,3}  (Chebyshev/Dirichlet atom)
  mode2 ++-+-- = Legendre (k/7)   = quadratic residues {1,2,4} = Paley-7 (Gauss atom)
  mode3 ++-    = the n=3 base = the 3-cycle
and 'A+B+C-D-E-F=G' realizes the signed character sum  Σ_k ε_k ω^{jk} = 2λ_j + 1,
where λ_j = Σ_{k∈C} ω^{jk} is the circulant eigenvalue (ω=e^{2πi/n}).

Then the REDUCTION DAG: an iso class comes from smaller classes in two ways --
  (i) REDUCIBLE (order-join composite): char_A, H, signed-Redei R, zeta ALL factor over the
      strong components (strictly smaller classes);
  (ii) CIRCULANT: ℤ/n-character-generated by a mode.
Strong non-circulant tournaments are the prime atoms. Plus the deck recursion char_A'=Σ char(T-v_i).
"""
import numpy as np
from itertools import permutations, combinations
from fractions import Fraction as Fr
from math import cos, sin, pi

# ---------- enumeration / invariants ----------
def canon(A,n,perms):
    best=None
    for p in perms:
        c=tuple(A[p[i]][p[j]] for i in range(n) for j in range(n) if i!=j)
        if best is None or c<best: best=c
    return best
def iso_reps(nmax):
    reps={1:[[[0]]]}
    for n in range(2,nmax+1):
        perms=list(permutations(range(n))); seen=set(); out=[]
        for B in reps[n-1]:
            for pat in range(1<<(n-1)):
                A=[row[:]+[0] for row in B]+[[0]*n]
                for k in range(n-1):
                    if pat>>k&1: A[n-1][k]=1
                    else: A[k][n-1]=1
                c=canon(A,n,perms)
                if c not in seen:
                    seen.add(c); M=[[0]*n for _ in range(n)]; idx=0
                    for i in range(n):
                        for j in range(n):
                            if i!=j: M[i][j]=c[idx]; idx+=1
                    out.append(M)
        reps[n]=out
    return reps
def strong(A):
    n=len(A); R=[[1 if(i==j or A[i][j])else 0 for j in range(n)]for i in range(n)]
    for k in range(n):
        for i in range(n):
            if R[i][k]:
                for j in range(n):
                    if R[k][j]: R[i][j]=1
    return all(R[i][j] and R[j][i] for i in range(n) for j in range(n))
def canon_code(A,n): return canon(A,n,list(permutations(range(n))))

# ---------- PART A: modes are circulant character sums ----------
print("="*90); print("PART A  the three sign-modes are circulant character sums  Σ_k ε_k ω^{jk} = 2λ_j+1")
print("="*90)
def circ_eig_report(n, C, name, eps_str):
    w=np.exp(2j*pi/n)
    lam=[sum(w**((j*k)%n) for k in C) for j in range(n)]
    eps=[ (1 if k in C else -1) for k in range(1,n)]
    for j in range(1,2):  # show j=1 as representative
        sgn_sum=sum(eps[k-1]*w**((j*k)%n) for k in range(1,n))
        pass
    # verify Σ_k ε_k ω^{jk} == 2 λ_j + 1  for j≠0 (at j=0 the geometric sum is n-1, not -1)
    ok=all(abs(sum(eps[k-1]*w**((j*k)%n) for k in range(1,n)) - (2*lam[j]+1))<1e-9 for j in range(1,n))
    rej=sorted(set(round((2*lam[j]+1).real,3) for j in range(1,n)))
    imj=sorted(set(round((2*lam[j]+1).imag,3) for j in range(1,n)))
    flat = len(set(round(abs(2*lam[j]+1),3) for j in range(1,n)))==1
    print("  %-9s C=%-10s eps(k=1..%d)=[%s]  Σε_kω^{jk}=2λ_j+1 (j≠0)? %s" % (name,C,n-1,eps_str,ok))
    print("             Re(λ_j)=-1/2 (universal); 2λ_j+1 (j≠0) pure imaginary, |·|=%s  => %s"
          % (sorted(set(round(abs(2*lam[j]+1),3) for j in range(1,n))),
             "FLAT (all |·|=√%d = Gauss sum)"%n if flat else "SPREAD (Dirichlet, var>0)"))
circ_eig_report(7,[1,2,3],"mode1 int","+,+,+,-,-,-")
circ_eig_report(7,[1,2,4],"mode2 QR","+,+,-,+,-,-")   # Legendre / Paley
circ_eig_report(3,[1],"mode3 C3","+,-")
print("  => EVERY ℤ/7 circulant sits on Re=-1/2; mode2 (Paley/Legendre) is FLAT |2λ+1|=√7 (Gauss sum),")
print("     mode1 (interval) is SPREAD (Dirichlet). The modes differ in the IMAGINARY (sine) part = Σε_k sin.")

# ---------- PART B: the reduction-DAG census ----------
print("\n"+"="*90); print("PART B  reduction DAG: which iso classes come from smaller subtournaments")
print("="*90)
def circulant_iso_codes(n):
    """canon codes of all circulant (ℤ/n Cayley) tournaments; empty if n even (no regular circulant)."""
    if n%2==0: return set()
    codes=set()
    pairs=[(k,n-k) for k in range(1,(n+1)//2)]
    for choice in range(1<<len(pairs)):
        C=set()
        for t,(a,b) in enumerate(pairs):
            C.add(a if (choice>>t&1) else b)
        A=[[0]*n for _ in range(n)]
        for i in range(n):
            for k in C: A[i][(i+k)%n]=1
        codes.add(canon_code(A,n))
    return codes
reps=iso_reps(7)
print("  n : total  reducible(from smaller via join)  strong-prime  of-which-circulant")
for n in range(3,8):
    circ=circulant_iso_codes(n)
    red=0; strongc=0; circ_strong=0
    for A in reps[n]:
        if strong(A):
            strongc+=1
            if canon_code(A,n) in circ: circ_strong+=1
        else:
            red+=1
    print("  %d : %5d   %5d                        %5d         %5d" % (n,len(reps[n]),red,strongc,circ_strong))
print("  => REDUCIBLE classes' char_A/H/R/ζ are products over strong components (THM-1926/1936); they")
print("     'come from' strictly-smaller strong classes. CIRCULANT strong classes are ℤ/n-character-")
print("     generated (the modes). The remaining strong-noncirculant classes are the prime atoms.")

# ---------- PART C: signed vertex-deletion (deck) recursion ----------
print("\n"+"="*90); print("PART C  the deck recursion: char_A'(x) = Σ_i char_{T−v_i}(x) (T−v_i are the subtournaments)")
print("="*90)
def charpoly_int(A):
    n=len(A); A=[[int(A[i][j])for j in range(n)]for i in range(n)]
    M=[[1 if i==j else 0 for j in range(n)]for i in range(n)]; c=[1]
    for k in range(1,n+1):
        AM=[[sum(A[i][t]*M[t][j]for t in range(n))for j in range(n)]for i in range(n)]
        tr=sum(AM[i][i]for i in range(n)); ck=-tr//k; c.append(ck)
        M=[[AM[i][j]+(ck if i==j else 0)for j in range(n)]for i in range(n)]
    return c  # char_A(x)=Σ c[j] x^{n-j}
def deriv(coeffs,n):
    # coeffs give Σ c[j] x^{n-j}; derivative = Σ c[j] (n-j) x^{n-j-1}
    return [coeffs[j]*(n-j) for j in range(n)]  # length n, powers x^{n-1..0}
def deck_sum(A,n):
    # Σ_i char_{T−v_i}(x): each is degree n-1 => Σ c^{(i)}[j] x^{n-1-j}
    tot=[0]*n
    for i in range(n):
        idx=[t for t in range(n) if t!=i]
        sub=[[A[a][b] for b in idx] for a in idx]
        cs=charpoly_int(sub)  # length n (coeffs for degree n-1 poly: Σ cs[j] x^{n-1-j})
        for j in range(n): tot[j]+=cs[j]
    return tot
ok_deck=True; c3ok=True
def num_c3(A,n):
    c=0
    for i,j,k in combinations(range(n),3):
        if A[i][j]+A[j][k]+A[k][i]==3 or A[j][i]+A[k][j]+A[i][k]==3: c+=1
    return c
for n in range(3,7):
    for A in reps[n]:
        if deriv(charpoly_int(A),n)!=deck_sum(A,n): ok_deck=False
        # c3 deck recursion: Σ_i c3(T−v_i) = (n−3) c3(T)
        s=sum(num_c3([[A[a][b] for b in range(n) if b!=i] for a in range(n) if a!=i],n-1) for i in range(n))
        if s!=(n-3)*num_c3(A,n): c3ok=False
print("  char_A'(x) = Σ_i char_{T−v_i}(x) over all classes n≤6:            %s" % ok_deck)
print("  Σ_i c3(T−v_i) = (n−3)·c3(T)  over all classes n≤6:                 %s" % c3ok)
print("  => the deck (the n vertex-deleted subtournaments A,B,…,G) determines T's char_A via the")
print("     UNSIGNED sum (=derivative); the owner's SIGNED weights ε_i pick out subclasses (below).")

# mode-signed deck sum for a vertex-transitive (circulant) tournament: all decks isomorphic
print("\n  mode-signed deck sum on a vertex-transitive (circulant) tournament: all T−v_i are one class D,")
print("  so Σ_i ε_i char_D = (Σ_i ε_i)·char_D  — vanishes iff the mode is sign-balanced (Σε=0).")
for n,C,name in [(7,[1,2,3],"interval"),(7,[1,2,4],"Paley")]:
    A=[[0]*n for _ in range(n)]
    for i in range(n):
        for k in C: A[i][(i+k)%n]=1
    eps=[(1 if k in C else -1) for k in range(1,n)]  # 6 signs; deck has 7 vertices — extend with the QR/sin sign of vertex index
    print("    %-9s n=7: 6-shift signs Σε=%d (interval balanced? Paley?) -- vertex-transitive ⇒ deck degenerate"%(name,sum(eps)))
