from fractions import Fraction as F
import cmath, itertools

# ---------- exact engine ----------
def sector_of(p): return int((p%1)*7)
def measS7(E):
    E=sorted(set(E)); bps=set([F(0),F(1)])
    for e in E:
        if e==0: continue
        for m in range(0,7*e+1): bps.add(F(m,7*e))
    bps=sorted(bps); tot=F(0)
    for i in range(len(bps)-1):
        x0,x1=bps[i],bps[i+1]
        if x1<=x0: continue
        if len(set(sector_of(e*((x0+x1)/2)) for e in E))==7: tot+=x1-x0
    return tot

# coverage sieve:  p0(E) = sum_{S subset {0..6}} (-1)^|S| m_S(E)
#   m_S = meas{ tau : sectors in S are all MISSED by orbit {frac(e*tau)} }
# We compute m_S directly by the same breakpoint method.
def miss_mass(E, S):
    # measure of tau in [0,1) s.t. for all e in E, sector_of(e*tau) NOT in S
    E=sorted(set(E)); bps=set([F(0),F(1)])
    for e in E:
        if e==0: continue
        for m in range(0,7*e+1): bps.add(F(m,7*e))
    bps=sorted(bps); tot=F(0)
    Sset=set(S)
    for i in range(len(bps)-1):
        x0,x1=bps[i],bps[i+1]
        if x1<=x0: continue
        mid=(x0+x1)/2
        # the orbit sectors hit:
        hit=set(sector_of(e*mid) for e in E)
        # tau "misses" sector j if j NOT in hit. We want: all of S missed, i.e. S cap hit = empty
        if Sset.isdisjoint(hit):
            tot+=x1-x0
    return tot

# ---------- the 6 characters of (Z/7)* on sectors {1..6} ----------
# (Z/7)* generated by 3 (a primitive root: 3,2,6,4,5,1). Use g=3.
# index of element: discrete log base 3.
g=3
dlog={}
v=1
for i in range(6):
    dlog[v]=i; v=(v*g)%7
# characters chi_k(a) = exp(2pi i k * dlog(a)/6), k=0..5
def chi(k,a): return cmath.exp(2j*cmath.pi*k*dlog[a]/6)

# QR (Z/2 part): k even chars are trivial on sign? sign char = chi_3 (order 2).
# cube-root (Z/3) chars: chi_2, chi_4 (order 3). order-6: chi_1, chi_5.


# ---------- THE REFRAMING ----------
# The sector-sieve gives p0(E) = sum over S subset {0..6} of (-1)^|S| m_S(E).
# Reframing B: restrict the sieve to single-sector missed-masses and decompose
# the *vector* (m_{j})_{j=1..6} over the 6 sectors {1..6} (drop sector 0, the
# anchor since 0 in E always hits sector 0) into the 6 characters of (Z/7)*.
#
# Define the SINGLE-SECTOR MISS vector  q_j = m_{{j}}(E)  for j=1..6.
# Its character coefficients:  q_hat(k) = (1/6) sum_{j=1..6} conj(chi(k,j)) q_j.
# k=0 trivial (= average miss), k=3 sign (QR vs NQR), k=2,4 cube-root, k=1,5 order-6.

def single_sector_miss_vector(E):
    return [miss_mass(E,[j]) for j in range(1,7)]

def char_coeffs(qvec):
    # qvec indexed 0..5 for sectors 1..6
    out=[]
    for k in range(6):
        s=0j
        for idx,j in enumerate(range(1,7)):
            s+= chi(k,j).conjugate()*float(qvec[idx])
        out.append(s/6)
    return out

# Test on the canonical covering clusters E = {0} u offsets, for the dangerous
# rows.  Use E = {0,1,2,...,k-1} style co-offset banks (the "consecutive" worst case).
print("="*70)
print("REFRAMING B: 6-character decomposition of single-sector miss vector")
print("="*70)

for E in [[0,1,2,3,4,5,6,7],            # k=8 consecutive
          [0,1,2,3,4,5,6,7,8],          # k=9
          [0,1,2,3,4,5,6,7,8,9],        # k=10
          [0,1,2,4],                    # small QR-ish
          [0,1,2,4,8,16,32,64]]:        # geometric (mult by 2 -> cube root orbit)
    q=single_sector_miss_vector(E)
    c=char_coeffs(q)
    print(f"\nE={E}")
    print("  q_j (miss sector j, j=1..6):", [str(x) for x in q])
    labels=["k0 triv","k1 ord6","k2 cube","k3 sign","k4 cube*","k5 ord6*"]
    for k in range(6):
        print(f"  {labels[k]}: |c|={abs(c[k]):.6f}  arg={cmath.phase(c[k])/cmath.pi:.4f}π  re={c[k].real:+.6f} im={c[k].imag:+.6f}")

print("\n"+"="*70)
print("SYMMETRY CHECK: is q_j = q_{-j mod 7}  (the n<->-n reality)?")
print("="*70)
for E in [[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,4]]:
    q=single_sector_miss_vector(E)  # index 0..5 -> sector 1..6
    qd={j:q[j-1] for j in range(1,7)}
    neg = all(qd[j]==qd[(-j)%7] for j in range(1,7))
    refl = all(qd[j]==qd[6-j] for j in range(1,6))
    print(f"E={E}: q[-j]=q[j]? {neg}   q[6-j]=q[j]? {refl}")
    print("   pairs (j,-j mod7):", [(j,(-j)%7) for j in range(1,7)])

# Why reality? sector_of(e*tau) and the missed-sector measure: replacing tau->1-tau
# sends frac(e*tau)->frac(-e*tau), sector j -> sector 6-j (since frac flips).
# So m_{{j}} = m_{{ -j-1 ?}}. Let's just confirm the EXACT reflection law empirically above.

print("\n"+"="*70)
print("ORIGIN of j->6-j reflection, and exact rational character pieces")
print("="*70)
# tau -> 1-tau sends frac(e*tau) -> frac(e - e*tau) = frac(-e*tau).
# sector_of(frac(-e*tau)): if frac(e*tau) in [j/7,(j+1)/7) then frac(-e*tau) in (-(j+1)/7,-j/7]
#   = [ (6-j)/7 , (7-j)/7 ) generically -> sector 6-j. So the involution tau<->1-tau
#   maps "miss sector j" <-> "miss sector 6-j".  Hence q_j = q_{6-j}.  EXACT, geometric.
print("Explanation: tau->1-tau is a measure-preserving involution of [0,1)")
print("  sending sector j -> sector 6-j. So q_j=q_{6-j} EXACTLY (real-analytic reality).")
print()
# Now: under the ADDITIVE reflection j->6-j, which of the 6 (Z/7)*-MULTIPLICATIVE")
# characters survive? chi_k(6-j) vs chi_k(j). 6-j is NOT multiplicative in j, so this")
# reflection mixes the multiplicative characters. Let's see the actual coupling.
# Build the 6x6 real character matrix and show which chars pair under j->6-j.
import numpy as np
M=np.zeros((6,6),dtype=complex)
for k in range(6):
    for idx,j in enumerate(range(1,7)):
        M[k,idx]=chi(k,j)
# reflection permutation on sectors 1..6: j->6-j
perm=[ (6-j) for j in range(1,7)]  # sector list -> new sectors
permidx=[perm[i]-1 for i in range(6)]
# chi_k restricted: chi_k(6-j) = sum? Compute chi_k(6-j)/chi_k(j) per j... not constant.
print("\nNOTE: j->6-j sends j=6 -> 0 (the ANCHOR sector). So the additive reflection")
print("does NOT preserve {1..6}. The multiplicative inversion j->-j=7-j sends 6->1 etc.")
print("These differ. The TRUE reality of q is the ADDITIVE reflection about 3.")
print("Let me recheck: is q ALSO invariant under multiplicative inversion j->7-j?")
for E in [[0,1,2,3,4,5,6,7],[0,1,2,4]]:
    q=single_sector_miss_vector(E)
    qd={j:q[j-1] for j in range(1,7)}
    inv=all(qd[j]==qd[(7-j)] for j in range(1,7) if (7-j) in qd)
    print(f"  E={E}: q[7-j]=q[j] (mult inversion)? {inv}")

print("\n"+"="*70)
print("RIGHT OBJECT: multiplicative-character decomposition needs a MULT-equivariant input.")
print("The single-sector miss q_j is ADDITIVELY symmetric (j->6-j), NOT mult (j->-j).")
print("So mult-char mass on q is spread. Test the FULL sieve p0 and the M7 main term.")
print("="*70)
# Full p0 via sieve and via engine - cross check, then look at correction p0 - M7.
def p0_sieve(E):
    tot=F(0)
    for r in range(8):
        for S in itertools.combinations(range(7),r):
            tot += (-1)**r * miss_mass(E,list(S))
    return tot
def M7(k):
    # main term sum_{T subset {1..6}} (-1)^|T| (1 - |T|/7)^{k-1}
    s=F(0)
    for r in range(7):
        from math import comb
        s += (-1)**r * comb(6,r) * F((7-r),7)**(k-1)
    return s
for E in [[0,1,2,3,4,5,6,7],[0,1,2,4]]:
    pe=measS7(E); ps=p0_sieve(E)
    k=len(E)
    print(f"E={E}: engine p0={pe}={float(pe):.6f}  sieve p0={ps}  match={pe==ps}  M7(k)={float(M7(k)):.8f}  corr={float(pe-M7(k)):.6f}")
