"""opus-2026-07-20-S404 -- SEIDEL SWITCHING CLASSES OF GRAPHS, UP TO ISOMORPHISM.

COMPLEMENT to kind-pasteur's THM-1415, NOT a duplicate.  THM-1415 computed switching
classes of TOURNAMENTS up to isomorphism -- 1, 2, 2, 6 at n = 3..6 -- and proved that
this is NOT A002854 (2,3,7,16), so the classical two-graph theorem has no tournament
analogue.  kps flagged their own guess (that the base-path-free quotient lands on the
repo's E_n) as REFUTED.

This script does the OTHER side, which nobody has run: Seidel switching of undirected
GRAPHS.  Prediction to test: the graph side DOES land on E_n exactly, i.e. the repo's
"even graph" objects ARE two-graphs, which would explain where V(E_n) = 2,3,7,16,54
comes from and import the whole two-graph literature.

Definitions used (Seidel):
  switch sigma_S(G): complement every edge between S and V\\S; leave edges inside S
  and inside V\\S alone.  Switching class = orbit under all 2^n switches.
  two-graph Delta(G) = { T in C(V,3) : G has an ODD number of edges inside T }.
  Delta is a complete switching invariant (classical).
"""
import itertools, sys
from collections import defaultdict

# ---------- graph plumbing: graphs on k vertices as bitmasks over C(k,2) ----------
def pairs(k):   return list(itertools.combinations(range(k), 2))
def triples(k): return list(itertools.combinations(range(k), 3))

def perm_action_on_pairs(k):
    """for each permutation of [k], the induced index map on pair-slots"""
    P = pairs(k); idx = {p: i for i, p in enumerate(P)}
    out = []
    for s in itertools.permutations(range(k)):
        out.append([idx[tuple(sorted((s[a], s[b])))] for (a, b) in P])
    return out

_PA_CACHE = {}
def canon_graph(g, k):
    """canonical form of a k-vertex graph bitmask: min over all relabelings"""
    if k not in _PA_CACHE: _PA_CACHE[k] = perm_action_on_pairs(k)
    best = None
    for act in _PA_CACHE[k]:
        h = 0
        for i in range(len(act)):
            if (g >> i) & 1: h |= 1 << act[i]
        if best is None or h < best: best = h
    return best

def all_graphs_upto_iso(k):
    seen = {}
    for g in range(1 << len(pairs(k))):
        c = canon_graph(g, k)
        if c not in seen: seen[c] = g
    return sorted(seen)

# ---------- two-graph of a graph ----------
def two_graph(g, k):
    """odd-triple set as a bitmask over C(k,3)"""
    P = pairs(k); idx = {p: i for i, p in enumerate(P)}
    m = 0
    for j, (a, b, c) in enumerate(triples(k)):
        e = ((g >> idx[(a, b)]) & 1) + ((g >> idx[(a, c)]) & 1) + ((g >> idx[(b, c)]) & 1)
        if e & 1: m |= 1 << j
    return m

def switch(g, k, S):
    """Seidel switch of g by vertex subset S (bitmask over vertices)"""
    P = pairs(k); h = g
    for i, (a, b) in enumerate(P):
        if ((S >> a) & 1) ^ ((S >> b) & 1): h ^= (1 << i)
    return h

def degrees(g, k):
    P = pairs(k); d = [0]*k
    for i, (a, b) in enumerate(P):
        if (g >> i) & 1: d[a] += 1; d[b] += 1
    return d

# ---------- census by DESCENDANTS (fast: avoids canonicalising n-vertex objects) ----
def descendant(g, k, v):
    """switch g so that v becomes isolated, then delete v -> graph on k-1 vertices"""
    P = pairs(k); idx = {p: i for i, p in enumerate(P)}
    S = 0
    for u in range(k):
        if u != v and (g >> idx[tuple(sorted((u, v)))]) & 1: S |= 1 << u
    h = switch(g, k, S)
    rest = [u for u in range(k) if u != v]
    ridx = {u: i for i, u in enumerate(rest)}
    P2 = pairs(k-1); idx2 = {p: i for i, p in enumerate(P2)}
    out = 0
    for i, (a, b) in enumerate(P):
        if a == v or b == v: continue
        if (h >> i) & 1:
            out |= 1 << idx2[tuple(sorted((ridx[a], ridx[b])))]
    return out

def switching_classes_upto_iso(n):
    """
    Every switching class on n vertices contains a graph with vertex n-1 isolated,
    so classes <-> graphs on n-1 vertices, modulo the identifications generated by
    'these two (n-1)-graphs are descendants of one common two-graph'.  Union-find those.
    """
    k = n - 1
    reps = all_graphs_upto_iso(k)
    parent = {g: g for g in reps}
    def find(x):
        while parent[x] != x: parent[x] = parent[parent[x]]; x = parent[x]
        return x
    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb: parent[max(ra, rb)] = min(ra, rb)
    # lift a (n-1)-vertex bitmask into the n-vertex pair indexing (orderings differ!)
    Pk, Pn = pairs(k), pairs(n)
    nidx = {p: i for i, p in enumerate(Pn)}
    lift_map = [nidx[p] for p in Pk]
    def lift(g):
        G = 0
        for i, bit in enumerate(lift_map):
            if (g >> i) & 1: G |= 1 << bit
        return G
    for g in reps:
        G = lift(g)                # graph on n vertices: g plus isolated vertex k
        for v in range(n):
            d = descendant(G, n, v)
            union(g, canon_graph(d, k))
    comps = defaultdict(list)
    for g in reps: comps[find(g)].append(g)
    return comps

A002854 = {1:1, 2:1, 3:2, 4:3, 5:7, 6:16, 7:54, 8:243, 9:2038, 10:33120}

print("="*78)
print("(1) SEIDEL SWITCHING CLASSES OF GRAPHS, UP TO ISOMORPHISM")
print("="*78)
print("   n   classes   A002854(n)   match   [= two-graphs on n vertices]")
NMAX = int(sys.argv[1]) if len(sys.argv) > 1 else 8
results = {}
for n in range(3, NMAX+1):
    comps = switching_classes_upto_iso(n)
    c = len(comps); results[n] = comps
    exp = A002854.get(n)
    print(f"  {n:2d}   {c:7d}   {str(exp):>10s}   {'OK' if c==exp else '**MISMATCH**'}")

print()
print("="*78)
print("(2) DOES EACH SWITCHING CLASS CONTAIN A UNIQUE EVEN GRAPH?")
print("="*78)
print("  classical (Seidel): for n ODD each switching class has exactly one even graph.")
print("  This is the bridge to the repo's E_n.  Test it, and see what n EVEN does.")
print("   n  parity  #classes  even-graphs-per-class (multiset of counts)")
for n in range(3, min(NMAX, 8)+1):
    k = n - 1
    counts = []
    Pk, Pn = pairs(k), pairs(n)
    nidx = {p: i for i, p in enumerate(Pn)}
    lift_map = [nidx[p] for p in Pk]
    for root, members in results[n].items():
        g = members[0]
        G = 0
        for i, bit in enumerate(lift_map):
            if (g >> i) & 1: G |= 1 << bit
        tot = 0
        for S in range(1 << n):
            h = switch(G, n, S)
            if all(d % 2 == 0 for d in degrees(h, n)): tot += 1
        # each graph counted once per switching subset; classes have 2^(n-1) distinct
        # graphs (S and its complement give the same graph), so halve
        counts.append(tot // 2)
    dist = defaultdict(int)
    for c in counts: dist[c] += 1
    print(f"  {n:2d}  {'odd ' if n%2 else 'even'}   {len(counts):7d}   "
          f"{dict(sorted(dist.items()))}")
print()
print("  reading: value v with multiplicity m means m classes contain v even graphs.")
