# opus-2026-07-17-S369 -- HYP-7520: THE SHORT-VECTOR BOUND FOR |S| >= 3.
#
# THM-1075 left delta(S) = sum over full-support n in Lam(a_S) of prod hhat(n_i)
# unbounded for |S| >= 3.  Since |hhat(n)| <= 1/(pi|n|) and hhat vanishes on 7Z,
# the controlling quantity is the MULTIPLICATIVE MINIMUM over vectors with no
# coordinate divisible by 7:
#       m7(Lam) = min { prod |n_i| : n in Lam, all n_i != 0, 7 does not divide n_i }
# and the predicted bound is |delta| ~ C / (pi^k * m7).
#
# WHY THIS IS THE RIGHT INVARIANT: at k=2 the lattice is generated by
# (b/g, -a/g), so m7 = ab/g^2 exactly, and 1/(pi^2 m7) = g^2/(pi^2 ab) -- which
# S368 measured as the true deviation up to 1.2-1.6x, and which is THM-1025's
# sawtooth floor g^2/(4ab).  So m7 reproduces the known k=2 answer.
#
# NOTE ON THE LITERATURE: min prod |n_i| over a lattice is the MULTIPLICATIVE
# minimum -- the quantity in the LITTLEWOOD CONJECTURE and the theory of
# products of linear forms (Cassels-Swinnerton-Dyer; Einsiedler-Katok-
# Lindenstrauss).  Our lattices are RATIONAL, so m7 > 0 always and is attained;
# the question is how small it can be, which is a well-studied shape.
from math import sin, pi, gcd
import itertools
LAM = 1.0/14

def hhat(n):
    if n == 0: return 2*LAM
    return sin(2*pi*n*LAM)/(pi*n)

def delta(A, N):
    tot = 0.0
    for n in itertools.product([x for x in range(-N,N+1) if x != 0], repeat=len(A)):
        if sum(ni*ai for ni,ai in zip(n,A)) == 0:
            p = 1.0
            for ni in n: p *= hhat(ni)
            tot += p
    return tot

def m7(A, N):
    """multiplicative minimum over full-support 7-free lattice vectors."""
    best = None; arg = None
    for n in itertools.product([x for x in range(-N,N+1) if x != 0], repeat=len(A)):
        if any(ni % 7 == 0 for ni in n): continue
        if sum(ni*ai for ni,ai in zip(n,A)) != 0: continue
        p = 1
        for ni in n: p *= abs(ni)
        if best is None or p < best: best, arg = p, n
    return best, arg

print("(1) DOES m7 CONTROL delta AT k=3?   predicted |delta| ~ 1/(pi^3 m7)")
print("    family            |delta|      m7   witness            1/(pi^3 m7)   ratio")
for A in [(2,3,5),(3,4,5),(2,5,7),(3,5,8),(11,13,17),(31,37,41),(101,103,107),(5,7,11)]:
    d = delta(A, 40); mm, arg = m7(A, 40)
    if mm is None:
        print(f"    {str(A):16s} {abs(d):.6f}      NONE (delta should be 0)")
        continue
    pred = 1.0/(pi**3 * mm)
    print(f"    {str(A):16s} {abs(d):.6f}  {mm:6d}   {str(arg):16s} {pred:.6f}    {abs(d)/pred:6.2f}")

print()
print("(2) MY DIRECTION A -- THE EXACT k-FOLD INDEPENDENCE CRITERION")
print("    hhat kills any vector with a coordinate divisible by 7, so")
print("        delta(S) = 0 EXACTLY  <=>  every n in Lam(a_S) has some 7 | n_i.")
print("    That is a condition on Lam mod 7 -- a finite check.  At k=2 it")
print("    reduces to 7|(a/g) or 7|(b/g), the S368 criterion.  Test at k=3:")
def lam_mod7_all_have_zero(A, N):
    """true iff every full-support lattice vector has some coord divisible by 7"""
    for n in itertools.product([x for x in range(-N,N+1) if x != 0], repeat=len(A)):
        if any(ni % 7 == 0 for ni in n): continue
        if sum(ni*ai for ni,ai in zip(n,A)) == 0: return False
    return True
print("    family            predict delta=0    |delta| measured")
for A in [(1,7,14),(7,14,21),(2,3,5),(7,7,7),(1,2,7),(7,1,2),(14,21,35),(3,5,7)]:
    p = lam_mod7_all_have_zero(A, 30); d = delta(A, 30)
    flag = "" if (p == (abs(d) < 1e-9)) else "  <-- MISMATCH"
    print(f"    {str(A):16s} {str(p):10s}         {abs(d):.8f}{flag}")
