"""Move-type DECOMPOSITION of the signed-LRC deficiency, with subgroup-lattice labeling.
monad-explorer-S708.

Confirms: deficiency = sum over collision classes (size-1) = sum over (base-relative) silent-move
occurrences.  Each silent move is a flip of a UNION of subgroup half-systems (H_d for prime-power
divisors d|C), i.e. an element of the elementary-abelian 2-group generated by {H_d}.  We label each
observed move by the subset of generators {H_d} whose XOR equals it, and tabulate occurrences.

deficiency(C) = sum_{nonempty subset B of generators} occ(H_B),  H_B = XOR_{d in B} H_d.
This is the explicit subgroup-lattice inclusion-exclusion the THM-417 handoff asked for.
"""
import numpy as np
import math
from collections import Counter, defaultdict


def factor_str(C):
    f, m, d = [], C, 2
    while d * d <= m:
        while m % d == 0:
            f.append(d); m //= d
        d += 1
    if m > 1:
        f.append(m)
    return "x".join(map(str, f))


def prime_power_divisors_proper(C):
    """ALL proper divisors d with 1<d<C (each gives a subgroup half-system generator H_d)."""
    return [d for d in range(2, C) if C % d == 0]


def halfset(C, d, n1):
    """Half-system of K_d\\{0} as a frozenset of speeds in 1..n1."""
    g = C // d
    Kd = set((g * j) % C for j in range(d))
    half = frozenset(x for x in Kd if 0 < x <= n1)  # x<=n1=(C-1)/2 are the runners in the half
    return half


def analyze(C, verbose=True):
    n1 = (C - 1) // 2
    H = np.arange(1, n1 + 1)
    S = np.sin(2 * math.pi * np.outer(H, H) / C)
    nfree = n1 - 1
    total = 1 << nfree
    # generators
    gens = prime_power_divisors_proper(C)
    gen_sets = {d: halfset(C, d, n1) for d in gens}
    # map XOR of generator subsets -> label
    sub_label = {}
    from itertools import combinations
    for r in range(1, len(gens) + 1):
        for combo in combinations(gens, r):
            s = frozenset()
            for d in combo:
                s = s ^ gen_sets[d]  # symmetric difference
            # canonicalize mod global complement
            comp = frozenset(range(1, n1 + 1)) - s
            key = min(s, comp, key=lambda z: (len(z), sorted(z)))
            sub_label[key] = combo

    # build cuts and classes
    eps = np.ones((n1, total), dtype=np.int8)
    idx = np.arange(total, dtype=np.uint64)
    for b in range(nfree):
        bit = ((idx >> np.uint64(b)) & np.uint64(1)).astype(np.int8)
        eps[b + 1, :] = np.where(bit == 1, 1, -1)
    Phi2 = np.round((S @ eps) ** 2, 6)
    classes = defaultdict(list)
    for j in range(total):
        classes[Phi2[:, j].tobytes()].append(j)
    del Phi2

    occ = Counter()        # label(combo) -> occurrences
    unknown = Counter()
    size_hist = Counter()
    full_n1 = frozenset(range(1, n1 + 1))
    for members in classes.values():
        sz = len(members); size_hist[sz] += 1
        if sz == 1:
            continue
        base = members[0]
        for m in members[1:]:
            diff = frozenset(int(i + 1) for i in np.nonzero(eps[:, base] != eps[:, m])[0])
            comp = full_n1 - diff
            key = min(diff, comp, key=lambda z: (len(z), sorted(z)))
            combo = sub_label.get(key)
            if combo is None:
                unknown[key] += 1
            else:
                occ[combo] += 1
    defic = total - len(classes)
    if verbose:
        print(f"=== C={C} ({factor_str(C)}) total={total} defic={defic} "
              f"size-hist={dict(sorted(size_hist.items()))}")
        print(f"    generators (prime-power half-systems) {gens}")
        for combo, c in sorted(occ.items(), key=lambda kv: (-kv[1])):
            print(f"      move {combo}  occ={c}")
        if unknown:
            print(f"    UNLABELED moves (not XOR of generators!): {dict(list(unknown.items())[:10])} "
                  f"(total {sum(unknown.values())})")
        chk = sum(occ.values()) + sum(unknown.values())
        print(f"    sum occ = {chk}  (== defic? {chk == defic})")
    return defic, occ, unknown, dict(size_hist)


import sys
targets = [int(x) for x in sys.argv[1:]] if len(sys.argv) > 1 else [9, 15, 21, 25, 27, 45]
for C in targets:
    analyze(C)
    print(flush=True)
