"""Signed-LRC collision COUNT LAW via the subgroup lattice of Z/C  (monad-explorer-S708).

Builds on THM-417 / HYP-2270 (closed) / HYP-2273.  Goal: crack the prime-power / mixed
count law that THM-417 left open (C=27->69, C=45->8728), so we can PREDICT C=63,81,105,...

Ground truth is EXACT (integer difference-multiset hashing, NO floats):
  config AP_n -> signed half-system S_eps = { eps_i * i mod C : i=1..n-1 }, eps_0=+1 fixed.
  Two cuts collide (homometric) iff equal difference multiset over Z/C.
  deficiency = 2^{n-2} - #classes.

For each non-singleton class we extract the SILENT FLIP GROUP: the set of XOR-difference
patterns D (subsets of magnitudes {1..n-1}) connecting class members.  We then test whether
every such D is generated (XOR) by the subgroup half-systems H_K = K cap {1..n-1}, K<=Z/C a
proper subgroup of order d|C, d>1.  H_K is the THM-417 silent generator for subgroup K.
"""
import math
from itertools import product
from collections import defaultdict, Counter


def proper_subgroup_halves(C):
    """dict d -> frozenset(H_d), H_d = positive half of the order-d subgroup, for each d|C, 1<d<C."""
    out = {}
    for d in range(2, C):
        if C % d:
            continue
        K = set((C // d * j) % C for j in range(d))
        Hd = frozenset(x for x in K if 1 <= x <= (C - 1) // 2)
        out[d] = Hd
    return out


def diff_signature(S, C):
    cnt = [0] * C
    for a in S:
        for b in S:
            if a != b:
                cnt[(a - b) % C] += 1
    return tuple(cnt)


def analyze(n, verbose=True):
    C = 2 * n - 1
    runners = list(range(1, n))           # magnitudes 1..n-1
    nfree = n - 2                          # eps_0 (runner 1) fixed = +1
    halves = proper_subgroup_halves(C)
    sig2members = defaultdict(list)        # signature -> list of flip-sets (frozenset of magnitudes negated)
    for bits in range(1 << nfree):
        eps = [1] * (n - 1)
        flipped = set()
        for b in range(nfree):
            if not (bits >> b) & 1:
                eps[b + 1] = -1
                flipped.add(runners[b + 1])
        S = sorted((eps[i] * runners[i]) % C for i in range(n - 1))
        sig2members[diff_signature(S, C)].append(frozenset(flipped))
    classes = list(sig2members.values())
    sizes = [len(c) for c in classes]
    hist = Counter(sizes)
    defic = (1 << nfree) - len(classes)

    # Silent-flip group analysis: collect all XOR differences within classes.
    gens_seen = Counter()        # XOR pattern -> how many ordered/representative occurrences
    unexplained = []             # XOR patterns not generated by subgroup halves
    half_set = {d: h for d, h in halves.items()}
    # build a quick decomposition check: is pattern D in the GF(2) span of {H_d}?
    half_list = sorted(half_set.items())  # (d, frozenset)

    def in_span(D):
        """Greedy GF(2) check: is D a XOR of the H_d ?  Return decomposition (list of d) or None."""
        # represent as set of magnitudes; basis = halves (may be dependent). Do Gaussian elim over GF2.
        target = set(D)
        # build matrix rows = halves, columns = magnitudes 1..(C-1)/2
        cols = list(range(1, (C - 1) // 2 + 1))
        col_idx = {c: i for i, c in enumerate(cols)}
        rows = []
        labels = []
        for d, h in half_list:
            r = 0
            for x in h:
                r |= 1 << col_idx[x]
            rows.append(r)
            labels.append((d,))
        tgt = 0
        for x in target:
            tgt |= 1 << col_idx[x]
        # gaussian elimination tracking labels
        basis = []  # (pivotbit, rowval, labelset)
        for r, lab in zip(rows, labels):
            cur = r
            curlab = set(lab)
            for pb, rv, lb in basis:
                if (cur >> pb) & 1:
                    cur ^= rv
                    curlab ^= lb
            if cur:
                pb = cur.bit_length() - 1
                basis.append((pb, cur, curlab))
        # reduce target
        cur = tgt
        curlab = set()
        for pb, rv, lb in basis:
            if (cur >> pb) & 1:
                cur ^= rv
                curlab ^= lb
        if cur == 0:
            return sorted(curlab)
        return None

    for members in classes:
        if len(members) == 1:
            continue
        base = next(iter(members))
        for m in members:
            D = base ^ m
            if not D:
                continue
            gens_seen[D] += 1
            if in_span(D) is None:
                unexplained.append((C, sorted(D)))

    if verbose:
        fac = factor_str(C)
        print(f"\n=== C={C} = {fac}  (n={n}, 2^(n-2)={1<<nfree}) ===")
        print(f"  deficiency = {defic}")
        print(f"  class-size histogram: {dict(sorted(hist.items()))}")
        # which subgroup-half patterns occur as single-flip differences
        single = {d: (h in gens_seen) for d, h in sorted(half_set.items())}
        print(f"  subgroup halves H_d present as a within-class flip: {single}")
        # report distinct XOR patterns and their decomposition
        distinct = sorted(set(gens_seen), key=lambda s: (len(s), sorted(s)))
        decomp = Counter()
        for D in distinct:
            dec = in_span(D)
            if dec is None:
                decomp['UNEXPLAINED'] += 1
            else:
                decomp[tuple(dec)] += 1
        print(f"  #distinct within-class XOR patterns = {len(distinct)}")
        print(f"  decomposition multiset (by subgroup-d set): {dict(decomp)}")
        if unexplained:
            print(f"  !!! UNEXPLAINED patterns (not in span of subgroup halves): "
                  f"{len(unexplained)} e.g. {unexplained[:3]}")
        else:
            print(f"  ALL within-class differences lie in the GF(2) span of subgroup halves H_d. (HYP-2273-general OK)")
    return C, defic, hist, gens_seen


def factor_str(C):
    f, m, d = [], C, 2
    while d * d <= m:
        while m % d == 0:
            f.append(d); m //= d
        d += 1
    if m > 1:
        f.append(m)
    return "x".join(map(str, f))


if __name__ == "__main__":
    # composite C that are brute-forceable (n-2 <= 18 -> C <= 39; plus do 45,49 separately/coarsely)
    for n in [5, 8, 11, 13, 14, 17, 18, 20]:   # C=9,15,21,25,27,33,35,39
        analyze(n)
