#!/usr/bin/env python3
"""
Verify the algebraic identity that makes C(H) self-orthogonal and doubly-even
for a skew-Hadamard H of order n with 8 | n. Fresh code.

Let b_i = i-th row of B=(J-H)/2 in {0,1}^n (a real 0/1 vector). For 0/1 vectors,
the F_2 inner product <b_i,b_j> mod 2 = (b_i . b_j) mod 2 (ordinary dot).

We use the +-1 picture. H_ij in {+1,-1}; b_i has a 1 exactly where H_ij=-1, i.e.
b_i = (1 - H[i])/2 entrywise. Then for the ordinary real dot product:
   b_i . b_j = sum_t (1-H_it)/2 * (1-H_jt)/2
             = (1/4) sum_t (1 - H_it - H_jt + H_it H_jt)
             = (1/4)[ n - rowsum_i - rowsum_j + (H H^T)_{ij} ]
where rowsum_i = sum_t H_it, and (HH^T)_{ij} = n*[i==j] (Hadamard) ... but careful:
sum_t H_it H_jt = (H H^T)_{ij}. For Hadamard H H^T = nI so this is n if i==j else 0.

So:
  i==j:  b_i.b_i = (1/4)[ n - 2 rowsum_i + n ] = (1/4)[2n - 2 rowsum_i]
                 = (n - rowsum_i)/2 = wt(b_i)   (consistency: weight = #(-1) in row i)
  i!=j:  b_i.b_j = (1/4)[ n - rowsum_i - rowsum_j ]

For the TOURNAMENT/skew gauge, rows of H: row i has the diagonal +1 and the rest
form a tournament; rowsum_i = 1 + (#(+1 off-diag) - #(-1 off-diag)). For a skew
matrix the off-diagonal splits: in row i there are (n-1) off-diagonal +-1 entries
and the score structure gives rowsum_i. We just COMPUTE rowsum_i and verify:

  doubly-even  <=>  wt(b_i) = (n - rowsum_i)/2 ≡ 0 mod 4 for all i AND the code
                    is generated by such words with pairwise even intersections.

We verify directly:
  (1) wt(b_i) ≡ 0 mod 4 for every row i  (=> all generators doubly-even), and
  (2) b_i.b_j even for all i,j (=> self-orthogonal),
for the tower orders 8,16,32,64; and we print rowsum_i values + the formula
b_i.b_j = (n - rs_i - rs_j)/4 to expose WHY: with 8|n and rs_i ≡ n mod ... .
"""

def transpose(M):
    n=len(M); m=len(M[0]); return [[M[i][j] for i in range(n)] for j in range(m)]
def double(H):
    m=len(H); HT=transpose(H)
    top=[H[i]+H[i] for i in range(m)]
    bot=[[-HT[i][j] for j in range(m)]+HT[i][:] for i in range(m)]
    return top+bot
def skew_tower(k):
    H=[[1]]
    for _ in range(k): H=double(H)
    return H

def analyze(k):
    n=1<<k
    H=skew_tower(k)
    rs=[sum(H[i]) for i in range(n)]           # row sums
    wt=[(n-rs[i])//2 for i in range(n)]         # weight of binarized row i
    # check (n-rs_i) divisible by 2 (always) and wt divisible by 4
    wt_div4 = all(w%4==0 for w in wt)
    # pairwise dot via formula (n - rs_i - rs_j)/4 for i!=j ; integer & even?
    # NOTE this formula assumes HH^T = nI exactly (Hadamard) which we have.
    pair_even=True
    pair_integer=True
    for i in range(n):
        for j in range(i+1,n):
            num = n - rs[i] - rs[j]
            if num % 4 != 0: pair_integer=False
            dot = num//4
            if dot % 2 != 0: pair_even=False
    # distinct row-sum values
    from collections import Counter
    rs_sig=Counter(rs)
    return {
        "order":n,
        "rowsum_values":dict(sorted(rs_sig.items())),
        "all_weights_div4":wt_div4,
        "weight_values":dict(sorted(Counter(wt).items())),
        "pair_dot_integer_via_formula":pair_integer,
        "pair_dot_even_via_formula":pair_even,
        "n_mod_8": n%8,
    }

if __name__=="__main__":
    for k in (3,4,5,6):
        r=analyze(k)
        print(f"=== order {r['order']} (n mod 8 = {r['n_mod_8']}) ===")
        print(f"  row-sum multiset: {r['rowsum_values']}")
        print(f"  binarized-weight multiset: {r['weight_values']}")
        print(f"  all generator weights divisible by 4: {r['all_weights_div4']}")
        print(f"  pairwise dot integer (formula):        {r['pair_dot_integer_via_formula']}")
        print(f"  pairwise dot EVEN (self-orthogonal):   {r['pair_dot_even_via_formula']}")
        print()
