#!/usr/bin/env python3
"""special_constants_s116f.py — Investigate 1/4, 1/2, ln(2), 7/8

Four numbers. What are they in rapidity space? What do they connect?
"""
from math import sqrt, log, pi, exp, atanh, tanh, cosh, sinh, log2
from fractions import Fraction

phi = (1+sqrt(5))/2
ln2 = log(2)

print()
print("  FOUR NUMBERS: 1/4, 1/2, ln(2), 7/8")
print()
print("="*70)
print()

# ============================================================
print("  FIRST: WHAT ARE THEY?")
print("  " + "-"*40)
print()
print(f"  1/4   = 0.25")
print(f"  1/2   = 0.5")
print(f"  ln(2) = {ln2:.10f}")
print(f"  7/8   = 0.875")
print()
print(f"  Rapidity of each (as a point on [-1,1]):")
print(f"  arctanh(1/4) = {atanh(0.25):.10f}")
print(f"  arctanh(1/2) = {atanh(0.5):.10f} = ln(3)/2 = {log(3)/2:.10f}")
print(f"  arctanh(ln2) = {atanh(ln2):.10f}")
print(f"  arctanh(7/8) = {atanh(0.875):.10f}")
print()
print(f"  Q-value of each:")
print(f"  Q(1/4) = {(1+0.25)/(1-0.25):.10f} = 5/3")
print(f"  Q(1/2) = {(1+0.5)/(1-0.5):.10f} = 3")
print(f"  Q(ln2) = {(1+ln2)/(1-ln2):.10f}")
print(f"  Q(7/8) = {(1+0.875)/(1-0.875):.10f} = 15")
print()

# ============================================================
print("  THE CAYLEY VALUES")
print("  " + "-"*40)
print()
q_quarter = Fraction(5, 3)
q_half = Fraction(3, 1)
q_78 = Fraction(15, 1)
print(f"  Q(1/4) = 5/3 = major sixth (musical interval!)")
print(f"  Q(1/2) = 3   = perfect twelfth (octave + fifth)")
print(f"  Q(7/8) = 15  = ... let's see: 15 = 3*5")
print()
print(f"  Q(1/4) = 5/3. In music: the major sixth.")
print(f"  Q(1/2) = 3.   In music: the perfect twelfth.")
print(f"  Q(7/8) = 15.  In music: 15 = 3*5 = twelfth * major third.")
print()
print(f"  And Q(ln(2)) = (1+ln2)/(1-ln2) = {(1+ln2)/(1-ln2):.10f}")
print(f"  This is NOT a nice rational number.")
print(f"  But: 1+ln2 = {1+ln2:.10f}")
print(f"       1-ln2 = {1-ln2:.10f}")
print(f"  Q(ln2) ~ 5.518. Not obviously musical.")
print()

# ============================================================
print("  THE CHAIN: 1/4 -> 1/2 -> ln(2) -> 7/8")
print("  " + "-"*40)
print()
print(f"  Is there a pattern connecting these four numbers?")
print()
print(f"  1/4 = (1/2)^2. Square.")
print(f"  1/2 = 1/2. The midpoint.")
print(f"  ln(2) = 0.6931... Transcendental. Between 1/2 and 1.")
print(f"  7/8 = 1 - 1/8 = 1 - (1/2)^3. Almost 1.")
print()
print(f"  Differences:")
print(f"  1/2 - 1/4 = 1/4")
print(f"  ln(2) - 1/2 = {ln2 - 0.5:.10f}")
print(f"  7/8 - ln(2) = {7/8 - ln2:.10f}")
print()
print(f"  The gaps: 0.25, 0.193, 0.182. Decreasing but not geometric.")
print()

# ============================================================
print("  RAPIDITY RELATIONSHIPS")
print("  " + "-"*40)
print()
r_quarter = atanh(0.25)
r_half = atanh(0.5)
r_ln2 = atanh(ln2)
r_78 = atanh(0.875)

print(f"  arctanh(1/4) = {r_quarter:.10f}")
print(f"  arctanh(1/2) = {r_half:.10f}")
print(f"  arctanh(ln2) = {r_ln2:.10f}")
print(f"  arctanh(7/8) = {r_78:.10f}")
print()
print(f"  Ratios:")
print(f"  arctanh(1/2) / arctanh(1/4) = {r_half/r_quarter:.10f}")
print(f"  arctanh(ln2) / arctanh(1/2) = {r_ln2/r_half:.10f}")
print(f"  arctanh(7/8) / arctanh(ln2) = {r_78/r_ln2:.10f}")
print()
print(f"  arctanh(7/8) / arctanh(1/4) = {r_78/r_quarter:.10f}")
print(f"  arctanh(7/8) / arctanh(1/2) = {r_78/r_half:.10f}")
print()

# ============================================================
print("  WHERE THEY APPEAR IN THE PROJECT")
print("  " + "-"*40)
print()
print("  1/4:")
print("    - Kleiber exponent = 3/4, so 1-Kleiber = 1/4")
print("    - Stevens brightness exponent = 0.33 ~ 1/3 (not 1/4)")
print("    - Rapidity of sqrt(n) = rapidity(n)/2 = half rapidity")
print("    - The semitone rapidity = ln(2)/24 = octave/12")
print("    - In music: Q(1/4) = 5/3 = major sixth")
print("    - In rapidity algebra: Q^{-1}(5/3) = 1/4")
print(f"    - 1/4 = rapidity of 4th root: rapidity(n^{1/4}) = rapidity(n)/4")
print()

print("  1/2:")
print("    - The FAIR COIN. Rapidity = 0 at p=1/2.")
print("    - But arctanh(1/2) = ln(3)/2 != 0")
print("    - This DISTINCTION is crucial:")
print("      1/2 as a PROBABILITY has rapidity 0 (via 2p-1 = 0)")
print("      1/2 as a POINT ON [-1,1] has rapidity ln(3)/2")
print("    - The two roles of 1/2 are DIFFERENT.")
print("    - As probability: the center, zero rapidity, maximum uncertainty")
print("    - As velocity: v = c/2, rapidity = ln(3)/2 = one musical twelfth")
print()
print("    - Q(1/2) = 3 = the curvature quantum")
print("    - The velocity c/2 gives Q-value 3 = the smallest odd cycle size")
print("    - C-H / C-C stretch = 3:1 = Q(1/2)")
print(f"    - arctanh(1/2) = {atanh(0.5):.10f} = ln(3)/2")
print()

print("  ln(2):")
print(f"    - THE OCTAVE in rapidity: ln(2)/2 = {ln2/2:.10f}")
print("    - Rapidity of v=3/5 = arctanh(3/5) = ln(2) (the Doppler octave!)")
print(f"    - Verify: arctanh(3/5) = {atanh(0.6):.10f}, ln(2) = {ln2:.10f}")
print(f"    - Match: {abs(atanh(0.6) - ln2) < 1e-10}")
print()
print("    - So ln(2) appears as BOTH:")
print("      (a) half the octave rapidity: ln(2)/2 = rapidity gap for doubling")
print("      (b) THE FULL rapidity of v=3/5: arctanh(3/5) = ln(2)")
print()
print("    - As a point on [-1,1]: ln(2) = 0.693... lives between 1/2 and 1")
print(f"    - Q(ln2) = {(1+ln2)/(1-ln2):.6f}")
print(f"    - arctanh(ln2) = {atanh(ln2):.6f}")
print()
print("    - ln(2) = the constrained channel capacity (0,2)-RLL code")
print("    - ln(2) ~ arg(lambda_c)/pi for the transfer matrix (near-coincidence)")
print("    - Information content of one bit = ln(2) nats")
print()

print("  7/8:")
print("    - 7/8 = 1 - 1/8 = 1 - 2^{-3}")
print("    - The Cayley address of 15: (15-1)/(15+1) = 14/16 = 7/8")
print(f"    - Q(7/8) = (1+7/8)/(1-7/8) = (15/8)/(1/8) = 15")
print(f"    - 15 = 3*5 = H(T_5) for the cyclic tournament on 5 vertices!")
print()
print("    - 7/8 is the Cayley address of 15 = max H at n=5")
print("    - Also: 7/8 = 7 * (1/8) = forbidden number * 2^{-3}")
print("    - Also: 7/8 = (2^3 - 1)/2^3 = Mersenne-like")
print()
print(f"    - arctanh(7/8) = {atanh(7/8):.10f}")
print(f"    - = ln(15)/2 = {log(15)/2:.10f}")
print(f"    - = ln(3)/2 + ln(5)/2 = {log(3)/2 + log(5)/2:.10f}")
print(f"    - = rapidity(3) + rapidity(5)")
print(f"    - = rapidity of the curvature quantum + rapidity of the pentagon!")
print()

# ============================================================
print()
print("  THE DEEP CONNECTIONS")
print("  " + "-"*40)
print()
print("  1. THE COMPOSITION CHAIN")
print()
print("  1/4 (+) 1/2 = ?")
v1, v2 = Fraction(1,4), Fraction(1,2)
composed = (v1+v2)/(1+v1*v2)
print(f"     (1/4 + 1/2)/(1 + 1/8) = (3/4)/(9/8) = {composed}")
print(f"     = 2/3")
print(f"     Q(2/3) = (1+2/3)/(1-2/3) = (5/3)/(1/3) = 5")
print()
print(f"  1/4 (+) 1/2 = 2/3, and Q(2/3) = 5 = the number of Platonic solids!")
print()

print("  1/2 (+) 7/8 = ?")
v1, v2 = Fraction(1,2), Fraction(7,8)
composed = (v1+v2)/(1+v1*v2)
print(f"     (1/2 + 7/8)/(1 + 7/16) = (11/8)/(23/16) = {composed}")
print(f"     = {composed} = {float(composed):.10f}")
print(f"     Q({composed}) = {(1+composed)/(1-composed)} = {float((1+composed)/(1-composed)):.4f}")
print()

# What about 1/4 (+) 7/8?
v1, v2 = Fraction(1,4), Fraction(7,8)
composed = (v1+v2)/(1+v1*v2)
print(f"  1/4 (+) 7/8 = {composed} = {float(composed):.10f}")
print(f"  Q({composed}) = {float((1+composed)/(1-composed)):.4f}")
print()

# ============================================================
print()
print("  2. THE BINARY STRUCTURE")
print("  " + "-"*40)
print()
print("  1/4 = 2^{-2}")
print("  1/2 = 2^{-1}")
print("  ln(2) = log of 2^1")
print("  7/8 = 1 - 2^{-3}")
print()
print("  They all involve powers of 2.")
print("  1/4 and 1/2 are negative powers.")
print("  ln(2) is the natural log of the base.")
print("  7/8 is one minus a negative power.")
print()
print("  In binary:")
print("  1/4 = 0.01")
print("  1/2 = 0.1")
print("  ln(2) = 0.10110001... (irrational)")
print("  7/8 = 0.111")
print()
print("  1/4 has one bit set (position 2).")
print("  1/2 has one bit set (position 1).")
print("  7/8 has three bits set (positions 1,2,3).")
print("  ln(2) has infinitely many bits set.")
print()
print("  The RAPIDITY of 2^{-k}:")
for k in range(0, 5):
    x = 2**(-k)
    if x < 1:
        rap = atanh(x)
        q = (1+x)/(1-x)
        print(f"    2^{{-{k}}} = {x:.4f}: rapidity = {rap:.6f}, Q = {q:.4f}")
    else:
        print(f"    2^{{-{k}}} = {x}: AT THE POLE")

print()
print("  The RAPIDITY of 1 - 2^{-k}:")
for k in range(1, 6):
    x = 1 - 2**(-k)
    rap = atanh(x)
    q = (1+x)/(1-x)
    n = int(q + 0.5)
    print(f"    1-2^{{-{k}}} = {x:.5f}: rapidity = {rap:.6f}, Q = {q:.4f} = {2**(k+1)-1}")

print()
print("  Q(1 - 2^{-k}) = (2 - 2^{-k}) / 2^{-k} = 2^{k+1} - 1 = MERSENNE NUMBER!")
print()
print("  So 7/8 maps to Q = 15 = 2^4 - 1 = Mersenne M_4.")
print("  And 3/4 maps to Q = 7 = 2^3 - 1 = Mersenne M_3 = FORBIDDEN!")
print("  And 1/2 maps to Q = 3 = 2^2 - 1 = Mersenne M_2 = curvature quantum!")
print()
print("  THE PATTERN: x = 1 - 2^{-k} maps to Q = 2^{k+1} - 1 = M_{k+1}.")
print()
print("  k=1: x=1/2, Q=3 (Mersenne prime, curvature)")
print("  k=2: x=3/4, Q=7 (Mersenne prime, FORBIDDEN)")
print("  k=3: x=7/8, Q=15 (not prime: 3*5)")
print("  k=4: x=15/16, Q=31 (Mersenne prime)")
print("  k=5: x=31/32, Q=63 (not prime: 7*9)")
print("  k=6: x=63/64, Q=127 (Mersenne prime)")
print()
print("  The Cayley transform maps 1 - 2^{-k} to Mersenne numbers!")
print("  Mersenne PRIMES correspond to 'prime' positions near the pole.")
print("  The first non-trivial Mersenne prime Q-value is 7 = THE FORBIDDEN NUMBER.")
print()

# ============================================================
print()
print("  3. THE ln(2) BRIDGE")
print("  " + "-"*40)
print()
print("  ln(2) sits between 1/2 and 7/8.")
print("  It is the ONLY transcendental number in the list.")
print("  The others are all rational (dyadic).")
print()
print("  ln(2) is the bridge between:")
print("  - The discrete (1/4, 1/2, 7/8 = binary fractions)")
print("  - The continuous (ln, exp, the real line)")
print()
print("  In rapidity:")
print(f"  arctanh(1/2) = ln(3)/2 = {atanh(0.5):.6f}")
print(f"  arctanh(ln2) = {atanh(ln2):.6f}")
print(f"  arctanh(7/8) = ln(15)/2 = {atanh(7/8):.6f}")
print()
print(f"  arctanh(ln2) - arctanh(1/2) = {atanh(ln2) - atanh(0.5):.6f}")
print(f"  arctanh(7/8) - arctanh(ln2) = {atanh(7/8) - atanh(ln2):.6f}")
print()
print("  ln(2) as a velocity: v = ln(2) = 0.693c.")
print("  This is a very fast velocity — 69.3% of light speed.")
print(f"  Doppler factor at v=ln(2): D = sqrt(Q(ln2)) = {sqrt((1+ln2)/(1-ln2)):.6f}")
print(f"  = {sqrt((1+ln2)/(1-ln2)):.6f}")
print()

# What is Q(ln2) exactly?
print("  Q(ln(2)) = (1+ln2)/(1-ln2)")
print(f"  = {(1+ln2)/(1-ln2):.10f}")
# Check: is this e^something?
q_ln2 = (1+ln2)/(1-ln2)
print(f"  ln(Q(ln2)) = {log(q_ln2):.10f}")
print(f"  2*arctanh(ln2) = {2*atanh(ln2):.10f}")
print(f"  Compare: pi = {pi:.10f}")
print(f"  Compare: e = {exp(1):.10f}")
print(f"  Compare: 2*phi = {2*phi:.10f}")
print(f"  Q(ln2) ~ 5.518. Not a recognizable constant.")
print()

# ============================================================
print()
print("  4. THE QUADRUPLE AS INFORMATION ARCHITECTURE")
print("  " + "-"*40)
print()
print("  1/4 = probability of two independent fair coins both heads")
print("  1/2 = probability of one fair coin heads")
print("  ln(2) = information content of one bit (in nats)")
print("  7/8 = probability of NOT getting three tails in a row")
print()
print("  REWRITTEN:")
print("  1/4 = P(HH)     = the probability of FULL AGREEMENT (2 coins)")
print("  1/2 = P(H)      = the probability of ONE AGREEMENT")
print("  ln(2) = I(coin)  = the INFORMATION in one agreement")
print("  7/8 = 1-P(TTT)  = the probability of AT LEAST ONE agreement (3 coins)")
print()
print("  They encode:")
print("  1/4 = AND (both agree)")
print("  1/2 = MAYBE (one agrees)")
print("  ln(2) = BIT (the measure of one agreement)")
print("  7/8 = OR (at least one agrees)")
print()
print("  AND < MAYBE < BIT < OR")
print("  0.25 < 0.50 < 0.693 < 0.875")
print()
print("  This is the HIERARCHY OF LOGICAL CONNECTIVES as numbers!")
print("  AND is the most restrictive: both must agree.")
print("  MAYBE is the fair point: one agrees, one doesn't.")
print("  BIT is the transcendental bridge: the COST of one distinction.")
print("  OR is the most permissive: at least one agrees.")
print()

# ============================================================
print()
print("  5. THE MERSENNE LADDER")
print("  " + "-"*40)
print()
print("  x_k = 1 - 2^{-k} maps to Q = 2^{k+1} - 1 = M_{k+1}.")
print()
print("  The ladder:")
print("    x_0 = 0     -> Q = 1   (identity)")
print("    x_1 = 1/2   -> Q = 3   (Mersenne prime, curvature)")
print("    x_2 = 3/4   -> Q = 7   (Mersenne prime, FORBIDDEN)")
print("    x_3 = 7/8   -> Q = 15  (composite: 3*5)")
print("    x_4 = 15/16 -> Q = 31  (Mersenne prime)")
print("    x_5 = 31/32 -> Q = 63  (composite: 7*9)")
print("    x_6 = 63/64 -> Q = 127 (Mersenne prime)")
print()
print("  1/4 = x_2/x_3 = (3/4)/(7/8) = 6/7.")
print("  Wait, 1/4 is NOT on the Mersenne ladder (it's x=1/4, not 1-2^{-k}).")
print()
print("  But 1/4 = 2^{-2} IS the STEP SIZE of the ladder at level 2:")
print("  x_2 - x_1 = 3/4 - 1/2 = 1/4.")
print("  x_3 - x_2 = 7/8 - 3/4 = 1/8.")
print("  x_4 - x_3 = 15/16 - 7/8 = 1/16.")
print()
print("  The step from level 1 to level 2 IS 1/4.")
print("  The step from level 2 to level 3 IS 1/8.")
print("  Each step halves. The ladder is GEOMETRIC with ratio 1/2.")
print()
print("  So our four numbers participate in the Mersenne ladder:")
print("  1/2 = x_1 (start of the ladder)")
print("  1/4 = step from x_1 to x_2")
print("  3/4 = x_2 (the FORBIDDEN rung)")
print("  7/8 = x_3 (the next rung)")
print()
print("  And ln(2) = the NATURAL UNIT of the ladder.")
print("  Each rung is separated by ln(2)/2 of rapidity? Let's check:")
print(f"  arctanh(1/2)  = {atanh(1/2):.6f}")
print(f"  arctanh(3/4)  = {atanh(3/4):.6f}")
print(f"  arctanh(7/8)  = {atanh(7/8):.6f}")
print(f"  arctanh(15/16)= {atanh(15/16):.6f}")
print()
print(f"  Gaps: {atanh(3/4)-atanh(1/2):.6f}, {atanh(7/8)-atanh(3/4):.6f}, {atanh(15/16)-atanh(7/8):.6f}")
print()
print("  The gaps are NOT constant. They INCREASE.")
print("  The ladder accelerates in rapidity as it approaches the pole.")
print()

# ============================================================
print()
print("  6. THE SYNTHESIS")
print("  " + "-"*40)
print()
print("  The four numbers 1/4, 1/2, ln(2), 7/8 are:")
print()
print("  1/4 = the AND gate = two coins agreeing = Q^{-1}(5/3) = major sixth")
print("  1/2 = the MAYBE = one coin = Q^{-1}(3) = twelfth = curvature velocity")
print("  ln(2) = the BIT = the cost of one distinction = the octave in nats")
print("  7/8 = the OR gate = at least one coin agreeing = Q^{-1}(15) = Mersenne M_4")
print()
print("  Together they trace the Mersenne ladder from Q=3 to Q=15,")
print("  passing through Q=7 (the forbidden rung) at x=3/4.")
print()
print("  3/4 is not in the original list. But it is BETWEEN 1/2 and 7/8.")
print("  And 3/4 is the Kleiber exponent. And Q(3/4) = 7 = forbidden.")
print("  The four numbers BRACKET the forbidden number on both sides.")
print()
print("  1/2 < 3/4 < 7/8: the forbidden 3/4 sits between 1/2 and 7/8.")
print("  ln(2) also sits between 1/2 and 7/8: 1/2 < ln(2) < 7/8.")
print("  And ln(2) ~ 0.693 while 3/4 = 0.750.")
print("  They are CLOSE but not equal.")
print()
print(f"  3/4 - ln(2) = {3/4 - ln2:.10f}")
print(f"  ln(2)/(3/4) = {ln2/(3/4):.10f}")
print(f"  The gap between ln(2) and 3/4 is only {(3/4-ln2)*100:.1f}% of the interval.")
print()
print("  ln(2) is the TRANSCENDENTAL shadow of 3/4.")
print("  3/4 is the RATIONAL shadow of ln(2).")
print("  One is the bit. The other is the biological threshold.")
print("  They are two versions of the same thing:")
print("  THE BOUNDARY BETWEEN ORDER AND COMPLEXITY.")
print()
print("  ln(2) says: this is the COST of one distinction (information).")
print("  3/4 says: this is the THRESHOLD of complexity (biology/tournaments).")
print("  Both live at rapidity ~ 0.5-1.0, the crossover region.")
print()
print("  And the four numbers 1/4, 1/2, ln(2), 7/8 are the")
print("  SCAFFOLD around this crossover:")
print("  1/4 and 1/2 below it, 7/8 above it, ln(2) inside it.")
