#!/usr/bin/env python3
"""Exact symbolic controls for THM-3038's split-order conductor theorem."""

import sympy as sp


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


T, W = sp.symbols("T W")
a, c0, c1, c2 = sp.symbols("a c0 c1 c2")
p, u, v, r = sp.symbols("p u v r")

# Universal monic cubic complement and split quartic.
g = T**3 + c2 * T**2 + c1 * T + c0
f = sp.expand((T - a) * g)
cross = sp.expand(g.subs(T, a))
# SymPy's PRS convention contributes the harmless odd-by-one sign; the
# principal resultant ideal is generated by g(a).
require(sp.expand(sp.resultant(T - a, g, T) + cross) == 0, "cross resultant")
require(
    sp.expand(sp.discriminant(f, T) - sp.discriminant(g, T) * cross**2) == 0,
    "split discriminant product",
)

# The coefficient-lattice map A -> R x R[T]/(g).  Its determinant is the
# cross-resultant, hence its DVR colength is v(g(a)).
columns = []
for exponent in range(4):
    h = T**exponent
    remainder = sp.rem(h, g, T)
    columns.append(
        sp.Matrix(
            [sp.expand(h.subs(T, a))]
            + [sp.expand(remainder.coeff(T, degree)) for degree in range(3)]
        )
    )
lattice_map = sp.Matrix.hstack(*columns)
require(sp.expand(lattice_map.det() + cross) == 0, "lattice determinant")

# g(T)/g(a) is the generic singleton idempotent.  Its numerator relation is
# integral exactly after the cross-resultant is inverted.
require(sp.rem(g * (g - cross), f, T) == 0, "idempotent relation")
require(sp.expand(g.subs(T, a) - cross) == 0, "idempotent singleton value")

# Independently verify the standard monic quartic/resolvent discriminant law.
B, C, D, E = sp.symbols("B C D E")
quartic = T**4 + B * T**3 + C * T**2 + D * T + E
resolvent = (
    W**3
    - C * W**2
    + (B * D - 4 * E) * W
    + 4 * C * E
    - B**2 * E
    - D**2
)
require(
    sp.expand(sp.discriminant(quartic, T) - sp.discriminant(resolvent, W)) == 0,
    "quartic resolvent discriminant",
)

# For the split quartic f=(T-a)g, the standard matching-resolvent coordinate
# on the complementary cubic is
#
#       w = y^2 + (a+c2)y + c1.
#
# Substitution annihilates the standard resolvent.  In the bases
# (1,w,w^2) and (1,y,y^2), the inclusion of the resolvent order into the
# complementary cubic order has determinant g(a).  Its nontrivial lower
# 2-by-2 block is elementary-equivalent to diag(1,-g(a)); hence the entire
# cokernel is the same single cyclic gluing defect R/(g(a)).
B_split = c2 - a
C_split = c1 - a * c2
D_split = c0 - a * c1
E_split = -a * c0
resolvent_split = sp.expand(
    W**3
    - C_split * W**2
    + (B_split * D_split - 4 * E_split) * W
    + 4 * C_split * E_split
    - B_split**2 * E_split
    - D_split**2
)
w_complement = T**2 + (a + c2) * T + c1
require(
    sp.rem(sp.expand(resolvent_split.subs(W, w_complement)), g, T) == 0,
    "complementary resolvent coordinate",
)
w2_remainder = sp.rem(sp.expand(w_complement**2), g, T)
resolvent_to_complement = sp.Matrix(
    [
        [1, c1, sp.expand(w2_remainder.coeff(T, 0))],
        [0, a + c2, sp.expand(w2_remainder.coeff(T, 1))],
        [0, 1, sp.expand(w2_remainder.coeff(T, 2))],
    ]
)
require(
    sp.expand(resolvent_to_complement.det() - cross) == 0,
    "resolvent-order index determinant",
)
lower_block = resolvent_to_complement[1:3, 1:3]
require(
    lower_block
    == sp.Matrix([[a + c2, c2 * c1 - c0], [1, a**2 + c1]]),
    "resolvent-order lower block",
)
# Swap rows, clear the lower-left entry, then clear the upper-right entry.
smith_control = sp.Matrix([[1, a**2 + c1], [a + c2, c2 * c1 - c0]])
smith_control[1, :] = smith_control[1, :] - (a + c2) * smith_control[0, :]
smith_control[:, 1] = smith_control[:, 1] - (a**2 + c1) * smith_control[:, 0]
require(
    all(sp.expand(entry) == 0 for entry in smith_control - sp.diag(1, -cross)),
    "resolvent cyclic Smith defect",
)

# Sharp order-mismatch hostile: the complementary cubic is already maximal
# at p=0, but the singleton sheet is glued with length one.  The standard
# matching resolvent absorbs that length in its own nonmaximal order.
g_hostile = T**3 - T + p
f_hostile = sp.expand(T * g_hostile)
resolvent_hostile = W**3 + W**2 - p**2
disc_complement = sp.factor(sp.discriminant(g_hostile, T))
disc_quartic = sp.factor(sp.discriminant(f_hostile, T))
disc_resolvent = sp.factor(sp.discriminant(resolvent_hostile, W))
require(disc_complement == 4 - 27 * p**2, "hostile complement discriminant")
require(
    sp.expand(disc_quartic - p**2 * (4 - 27 * p**2)) == 0,
    "hostile quartic discriminant",
)
require(
    sp.expand(disc_resolvent - disc_quartic) == 0,
    "hostile raw discriminant equality",
)
require(sp.resultant(T, g_hostile, T) == -p, "hostile cross resultant")
hostile_idempotent = sp.together(g_hostile / p)
require(
    sp.expand(hostile_idempotent.as_numer_denom()[1] - p) == 0,
    "hostile idempotent has p denominator",
)

# Sharp affine-owner hostile from THM-3037: the conductor stage succeeds, but
# the singleton boundary trace can still be removed from the Zariski-main open.
g_owner = T**3 - 3 * u * T - 2 * v
cross_owner = sp.expand(g_owner.subs(T, 1))
require(cross_owner == 1 - 3 * u - 2 * v, "owner cross unit")
require(
    sp.expand(sp.discriminant(g_owner, T) - 108 * (u**3 - v**2)) == 0,
    "owner cusp discriminant",
)
g_cusp = sp.expand(g_owner.subs({u: r**2, v: r**3}))
require(
    sp.expand(g_cusp - (T - 2 * r) * (T + r) ** 2) == 0,
    "owner cusp factorization",
)
derivative = sp.diff(g_cusp, T)
require(sp.expand(derivative.subs(T, -r)) == 0, "ramified double branch")
require(sp.expand(derivative.subs(T, 2 * r) - 9 * r**2) == 0, "simple branch")

# THM-2570's concrete source-coordinate owner test: the survivor coordinate
# has a pole of exact order two at its conductor prime.
theta, c_source = sp.symbols("theta c_source")
source_coordinate = 2 * c_source / theta**2
require(
    sp.together(source_coordinate).as_numer_denom()[1] == theta**2,
    "source-coordinate pole order",
)

print("THM3038 split monogenic order conductor exact certificate")
print("fiber_product=A=R_x_(R/(g(a)))_R[T]/(g)")
print("cross_resultant_ideal=(Res(T-a,g))=(g(a))")
print("lattice_determinant=-g(a);dvr_gluing_length=v(g(a))")
print("singleton_conductor_slice=(g(a))*R*e;idempotent=e=g(T)/g(a)")
print("split_discriminant=Disc(g)*g(a)^2")
print("complement_resolver=W=y^2+(a+c2)y+c1;basis_det=g(a)")
print("cyclic_defects=quartic_gluing=resolvent_order=R/(g(a))")
print("order_mismatch=f=T*(T^3-T+p);complement_disc=4-27p^2")
print("order_mismatch=resolvent=W^3+W^2-p^2;raw_disc=p^2*(4-27p^2)")
print("owner_hostile=g(1)=1-3u-2v;local_unit=1")
print("owner_cusp=108*(u^3-v^2);branches=(T-2r)*(T+r)^2")
print("thm2570_source_coordinate_pole_order=-2")
print("all_exact_controls=PASS")
