#!/usr/bin/env python3
"""
death-star-2026-07-20-S61 (HYP-8265) -- the base-path-INDEPENDENT resolution:
the FULL cut space (Seidel switching: reverse all arcs at v) is base-path-free,
and its 2^{C(n-1,2)} switching classes ARE the tiling hypercube. Switching classes
UP TO ISO = a genuine base-path-independent tournament invariant. Compute + compare
to iso classes (A000568) and merged classes.
"""
from itertools import combinations, permutations
from math import comb

def run(n):
    edges=list(combinations(range(n),2)); idx={e:k for k,e in enumerate(edges)}; m=len(edges)
    def bits_to_adj(b):
        a=[[0]*n for _ in range(n)]
        for k,(i,j) in enumerate(edges):
            if (b>>k)&1: a[i][j]=1
            else: a[j][i]=1
        return a
    def switch(b,v):  # reverse all arcs at v = flip all edges incident to v
        for u in range(n):
            if u!=v: b^= (1<<idx[(min(u,v),max(u,v))])
        return b
    def switch_class_rep(b):
        # canonical rep of the switching class: min over all 2^n switch subsets? 
        # switching group generated by single-vertex switches; orbit size 2^{n-1}.
        seen=set([b]); frontier=[b]
        while frontier:
            x=frontier.pop()
            for v in range(n):
                y=switch(x,v)
                if y not in seen: seen.add(y); frontier.append(y)
        return min(seen)
    def canon_iso(b):
        a=bits_to_adj(b); best=None
        for p in permutations(range(n)):
            f=tuple(a[p[i]][p[j]] for i in range(n) for j in range(n))
            if best is None or f<best: best=f
        return best
    # count switching classes and switching-classes-up-to-iso
    sc_reps=set(); sc_iso=set()
    seen_sc=set()
    for b in range(1<<m):
        if b in seen_sc: continue
        rep=switch_class_rep(b)
        # mark whole class seen
        cls=set([rep]); fr=[rep]
        while fr:
            x=fr.pop()
            for v in range(n):
                y=switch(x,v)
                if y not in cls: cls.add(y); fr.append(y)
        seen_sc|=cls
        sc_reps.add(rep)
    # switching classes up to iso: canonicalize the switching-class rep under iso
    for rep in sc_reps:
        # iso-canonical form of the switching class = min canon over the class
        cls=set([rep]); fr=[rep]
        while fr:
            x=fr.pop()
            for v in range(n):
                y=switch(x,v)
                if y not in cls: cls.add(y); fr.append(y)
        sc_iso.add(min(canon_iso(x) for x in cls))
    n_switch=len(sc_reps); n_switch_iso=len(sc_iso)
    n_iso=len(set(canon_iso(b) for b in range(1<<m)))
    print(f"  n={n}: switching classes = {n_switch} (= 2^C(n-1,2) = {2**comb(n-1,2)} = #tilings), "
          f"switching-classes-up-to-iso = {n_switch_iso}, iso classes = {n_iso}")
    return n_switch, n_switch_iso, n_iso

print("=== switching classes (= tiling hypercube) and switching-classes-up-to-iso ===")
data=[]
for n in [3,4,5]:
    data.append(run(n))
print("\n  switching classes = 2^C(n-1,2) = the tiling hypercube (VERIFIED): base-path-FREE")
print("    (Seidel switching references no path; the base path only picks the class representative).")
print("  switching-classes-up-to-iso: a base-path-INDEPENDENT tournament invariant -- coarser than")
print("    iso classes. This is the RIGHT base-path-free star object; kp's cap Gamma(P)=0 because the")
print("    tile-restricted star DROPS the path edges. Full switching keeps them and is invariant.")
print("  => the tiling hypercube = switching classes = the base-path-independent 'nature of numbers'")
print("     structure; iso quotient + switching = two independent base-path-free quotients.")
