"""
Does M[a,b] = M[b,a] require the tournament constraint t_ij + t_ji = 1?

If symmetry holds for GENERAL digraphs (no constraint), then the proof
must be purely combinatorial (about paths and subsets).

If it ONLY holds for tournaments, then t_ij + t_ji = 1 is essential,
and we should look for a proof that uses this constraint explicitly.
"""

from itertools import permutations
from sympy import symbols, expand, simplify
from collections import defaultdict

# ==========================================================
# Part 1: n=4 — test with INDEPENDENT t_ij and t_ji
# ==========================================================
print("=" * 70)
print("SYMMETRY AND THE TOURNAMENT CONSTRAINT")
print("=" * 70)

print("\n--- Part 1: n=4 with independent variables ---")

n = 4
# Create INDEPENDENT variables for each ordered pair (i,j)
t = {}
for i in range(n):
    for j in range(n):
        if i != j:
            t[(i,j)] = symbols(f't{i}{j}')

def ham_paths_sym(vertex_set, end=None, start=None):
    """Count Hamiltonian paths symbolically with independent arc variables."""
    vlist = sorted(vertex_set)
    k = len(vlist)
    if k == 0: return 0
    if k == 1:
        if start is not None and vlist[0] != start: return 0
        if end is not None and vlist[0] != end: return 0
        return 1
    total = 0
    for perm in permutations(vlist):
        if start is not None and perm[0] != start: continue
        if end is not None and perm[-1] != end: continue
        prod = 1
        for i in range(len(perm)-1):
            prod *= t[(perm[i], perm[i+1])]
        total += prod
    return expand(total)

a, b = 0, 1
U = [v for v in range(n) if v != a and v != b]

# Compute M[a,b] and M[b,a] with INDEPENDENT variables
M_ab = 0
M_ba = 0
for mask in range(1 << len(U)):
    S = [U[i] for i in range(len(U)) if mask & (1 << i)]
    R = [U[i] for i in range(len(U)) if not (mask & (1 << i))]
    sign = (-1) ** len(S)

    ea = ham_paths_sym(set(S) | {a}, end=a)
    bb = ham_paths_sym(set(R) | {b}, start=b)
    eb = ham_paths_sym(set(S) | {b}, end=b)
    ba = ham_paths_sym(set(R) | {a}, start=a)

    M_ab += sign * ea * bb
    M_ba += sign * eb * ba

M_ab = expand(M_ab)
M_ba = expand(M_ba)

diff_general = expand(M_ab - M_ba)
print(f"  M[0,1] - M[1,0] (general digraph) = {diff_general}")
print(f"  Is zero? {diff_general == 0}")

if diff_general != 0:
    print(f"\n  Symmetry FAILS for general digraphs!")
    print(f"  The difference has {len(diff_general.as_ordered_terms())} terms.")

    # Now substitute the tournament constraint: t_ji = 1 - t_ij for i < j
    subs = {}
    for i in range(n):
        for j in range(i+1, n):
            subs[t[(j,i)]] = 1 - t[(i,j)]

    diff_tournament = expand(diff_general.subs(subs))
    print(f"\n  After tournament constraint (t_ji = 1 - t_ij):")
    print(f"  M[0,1] - M[1,0] = {diff_tournament}")
    print(f"  Is zero? {diff_tournament == 0}")

    if diff_tournament == 0:
        print(f"\n  => SYMMETRY REQUIRES THE TOURNAMENT CONSTRAINT!")
        print(f"  => The proof MUST use t_ij + t_ji = 1.")

# ==========================================================
# Part 2: Analyze the difference more carefully
# ==========================================================
print(f"\n--- Part 2: Structure of the general-digraph difference ---")

if diff_general != 0:
    # Collect monomials
    poly = diff_general.as_coefficients_dict()
    print(f"  Number of monomials in diff: {len(poly)}")

    # Group by which (i,j) pairs appear
    for monom, coeff in sorted(poly.items(), key=lambda x: str(x[0])):
        if coeff != 0:
            print(f"    {'+' if int(coeff) > 0 else ''}{int(coeff)} * {monom}")

# ==========================================================
# Part 3: What happens with the WEAKER constraint t_ij * t_ji = 0?
# ==========================================================
print(f"\n--- Part 3: Weaker constraint t_ij * t_ji = 0 (no mutual edges) ---")
# This constraint says: for each pair {i,j}, at most one of t_ij, t_ji is nonzero
# But doesn't require exactly one (allows both zero = no edge)

# We can test by checking if diff vanishes modulo the ideal (t_ij * t_ji : i < j)
# Rather than computing with ideals, let's substitute t_ji = c_ji * (1 - t_ij)
# where c_ji is a new variable (0 or 1). If t_ij = 1, then t_ji = 0; if t_ij = 0,
# t_ji = c_ji (could be 0 or 1).

# Actually let's just check: is the diff in the ideal generated by
# (t_ij + t_ji - 1) for all i < j?

# The tournament constraint says t_ji = 1 - t_ij. The weaker "no mutual" says
# t_ij * t_ji = 0. Let's check the latter.

if diff_general != 0:
    # Substitute t_ji = 1 - t_ij - epsilon_ij where epsilon captures the deviation
    # from tournament constraint
    eps = {}
    for i in range(n):
        for j in range(i+1, n):
            eps[(i,j)] = symbols(f'e{i}{j}')

    subs_eps = {}
    for i in range(n):
        for j in range(i+1, n):
            subs_eps[t[(j,i)]] = 1 - t[(i,j)] + eps[(i,j)]

    diff_with_eps = expand(diff_general.subs(subs_eps))
    print(f"  Substituting t_ji = 1 - t_ij + eps_ij:")
    print(f"  diff = {diff_with_eps}")

    # Collect by powers of epsilon
    # The constant term (eps=0) should be 0 (tournament case)
    # The linear terms in eps tell us how the symmetry breaks

    # Set all eps to 0 to verify
    eps_zero = {e: 0 for e in eps.values()}
    const_term = expand(diff_with_eps.subs(eps_zero))
    print(f"\n  Constant term (eps=0, tournament): {const_term}")

    # Linear terms
    for (i,j), e in sorted(eps.items()):
        # Coefficient of eps_ij
        deriv = expand(diff_with_eps.diff(e))
        deriv_at_0 = expand(deriv.subs(eps_zero))
        if deriv_at_0 != 0:
            print(f"  d(diff)/d(eps_{i}{j}) at eps=0 = {deriv_at_0}")

# ==========================================================
# Part 4: n=3 check (simpler case)
# ==========================================================
print(f"\n--- Part 4: n=3 check ---")
n3 = 3
t3 = {}
for i in range(n3):
    for j in range(n3):
        if i != j:
            t3[(i,j)] = symbols(f's{i}{j}')

def hp3(vset, end=None, start=None):
    vl = sorted(vset)
    if len(vl) <= 1:
        if start is not None and (len(vl)==0 or vl[0] != start): return 0
        if end is not None and (len(vl)==0 or vl[0] != end): return 0
        return 1 if len(vl)==1 else 0
    total = 0
    for p in permutations(vl):
        if start and p[0] != start: continue
        if end and p[-1] != end: continue
        prod = 1
        for i in range(len(p)-1):
            prod *= t3[(p[i], p[i+1])]
        total += prod
    return expand(total)

a3, b3 = 0, 1
U3 = [2]
M3_ab = 0
M3_ba = 0
for mask in range(1 << len(U3)):
    S = [U3[i] for i in range(len(U3)) if mask & (1 << i)]
    R = [U3[i] for i in range(len(U3)) if not (mask & (1 << i))]
    sign = (-1)**len(S)
    ea = hp3(set(S)|{a3}, end=a3)
    bb = hp3(set(R)|{b3}, start=b3)
    eb = hp3(set(S)|{b3}, end=b3)
    ba = hp3(set(R)|{a3}, start=a3)
    M3_ab += sign * ea * bb
    M3_ba += sign * eb * ba

M3_ab = expand(M3_ab)
M3_ba = expand(M3_ba)
diff3 = expand(M3_ab - M3_ba)
print(f"  M[0,1] = {M3_ab}")
print(f"  M[1,0] = {M3_ba}")
print(f"  Diff (general) = {diff3}")
print(f"  Is zero? {diff3 == 0}")

if diff3 != 0:
    subs3 = {t3[(j,i)]: 1 - t3[(i,j)] for i in range(n3) for j in range(i+1, n3)}
    diff3_tour = expand(diff3.subs(subs3))
    print(f"  Diff (tournament) = {diff3_tour}")

# ==========================================================
# Part 5: What if we relax to t_ij + t_ji = c (constant)?
# ==========================================================
print(f"\n--- Part 5: Relaxation t_ij + t_ji = c ---")
c = symbols('c')
if diff_general != 0:
    subs_c = {}
    for i in range(n):
        for j in range(i+1, n):
            subs_c[t[(j,i)]] = c - t[(i,j)]

    diff_c = expand(diff_general.subs(subs_c))
    print(f"  With t_ij + t_ji = c:")

    # Collect by powers of c
    from sympy import Poly as SPoly, degree as sdeg
    p = SPoly(diff_c, c)
    print(f"  Polynomial in c: degree {p.degree()}")
    for power in range(p.degree() + 1):
        coeff = expand(p.nth(power))
        if coeff != 0:
            print(f"    c^{power}: {coeff}")

    # At c=1 (tournament): should be 0
    at_1 = expand(diff_c.subs(c, 1))
    print(f"\n  At c=1 (tournament): {at_1}")
    # At c=0 (mutual exclusion possible):
    at_0 = expand(diff_c.subs(c, 0))
    print(f"  At c=0: {at_0}")

# ==========================================================
# Part 6: Numerical test — does symmetry hold for random digraphs?
# ==========================================================
print(f"\n--- Part 6: Numerical test with random digraphs ---")
import random
random.seed(42)

for n_test in [4, 5]:
    failures = 0
    for trial in range(100):
        # Random digraph (each arc independently with prob 0.5)
        T = [[0]*n_test for _ in range(n_test)]
        for i in range(n_test):
            for j in range(n_test):
                if i != j:
                    T[i][j] = random.randint(0, 1)

        # Check M[0,1] vs M[1,0]
        a_t, b_t = 0, 1
        U_t = [v for v in range(n_test) if v != a_t and v != b_t]
        m_ab = 0
        m_ba = 0
        for mask in range(1 << len(U_t)):
            S = [U_t[i] for i in range(len(U_t)) if mask & (1 << i)]
            R = [U_t[i] for i in range(len(U_t)) if not (mask & (1 << i))]
            sign = (-1)**len(S)

            def hp_n(vset, start=None, end=None):
                vl = sorted(vset)
                c = 0
                for p in permutations(vl):
                    if start is not None and p[0] != start: continue
                    if end is not None and p[-1] != end: continue
                    ok = True
                    for ii in range(len(p)-1):
                        if T[p[ii]][p[ii+1]] != 1:
                            ok = False
                            break
                    if ok: c += 1
                return c

            ea = hp_n(set(S)|{a_t}, end=a_t)
            bb = hp_n(set(R)|{b_t}, start=b_t)
            eb = hp_n(set(S)|{b_t}, end=b_t)
            ba = hp_n(set(R)|{a_t}, start=a_t)
            m_ab += sign * ea * bb
            m_ba += sign * eb * ba

        if m_ab != m_ba:
            failures += 1

    print(f"  n={n_test}: {failures}/100 random digraphs have M[0,1] != M[1,0]")

# Now test tournaments
for n_test in [4, 5, 6, 7]:
    failures = 0
    for trial in range(200):
        T = [[0]*n_test for _ in range(n_test)]
        for i in range(n_test):
            for j in range(i+1, n_test):
                if random.random() < 0.5:
                    T[i][j] = 1
                else:
                    T[j][i] = 1

        a_t, b_t = 0, 1
        U_t = [v for v in range(n_test) if v != a_t and v != b_t]
        m_ab = 0
        m_ba = 0
        for mask in range(1 << len(U_t)):
            S = [U_t[i] for i in range(len(U_t)) if mask & (1 << i)]
            R = [U_t[i] for i in range(len(U_t)) if not (mask & (1 << i))]
            sign = (-1)**len(S)

            def hp_n2(vset, start=None, end=None):
                vl = sorted(vset)
                c = 0
                for p in permutations(vl):
                    if start is not None and p[0] != start: continue
                    if end is not None and p[-1] != end: continue
                    ok = True
                    for ii in range(len(p)-1):
                        if T[p[ii]][p[ii+1]] != 1:
                            ok = False
                            break
                    if ok: c += 1
                return c

            ea = hp_n2(set(S)|{a_t}, end=a_t)
            bb = hp_n2(set(R)|{b_t}, start=b_t)
            eb = hp_n2(set(S)|{b_t}, end=b_t)
            ba = hp_n2(set(R)|{a_t}, start=a_t)
            m_ab += sign * ea * bb
            m_ba += sign * eb * ba

        if m_ab != m_ba:
            failures += 1

    print(f"  n={n_test}: {failures}/200 random TOURNAMENTS have M[0,1] != M[1,0]")

print(f"\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)
