#!/usr/bin/env python3
"""symmetry_s116l.py — Everything in terms of symmetric and intrinsic.

The chain 3 -> 7 -> 47 -> 2207 has entry points 4, 8, 16, 32.
These double. Doubling IS the Cayley transform's derivative (Q'(0) = 2).
Each step doubles because each step applies Q once more.

But there are TWO kinds of structure in everything we've found:

SYMMETRIC: what you see from outside. The group. The automorphisms.
  The thing that LOOKS the same from multiple angles.
  Commutative. Reversible. The cosine part (Lucas).

INTRINSIC: what the thing IS from inside. The obstruction. The invariant.
  The thing that CANNOT be changed by any symmetry.
  Irreducible. One-directional. The sine part (Fibonacci).

The entire theory is the interplay between these two.
"""
from math import sqrt, log

phi = (1+sqrt(5))/2
psi = -1/phi

fib = [0, 1]
luc = [2, 1]
for _ in range(40):
    fib.append(fib[-1] + fib[-2])
    luc.append(luc[-1] + luc[-2])

print()
print("  SYMMETRIC AND INTRINSIC")
print()
print("="*70)
print()

# ============================================================
print("  I. THE TWO PARTS OF PHI^n")
print("  " + "-"*40)
print()
print("  phi^n = F_n * phi + F_{n-1}")
print("  psi^n = F_n * psi + F_{n-1}")
print()
print("  Adding: phi^n + psi^n = F_n*(phi+psi) + 2*F_{n-1} = F_n + 2*F_{n-1} = L_n.")
print("  Subtracting: phi^n - psi^n = F_n*(phi-psi) = F_n*sqrt(5).")
print()
print("  L_n = phi^n + psi^n: the SYMMETRIC part.")
print("    Symmetric under phi <-> psi (conjugation).")
print("    Even function of the golden ratio.")
print("    What you see from OUTSIDE the golden structure.")
print()
print("  F_n*sqrt(5) = phi^n - psi^n: the INTRINSIC part.")
print("    Anti-symmetric under phi <-> psi.")
print("    Odd function. Changes sign under conjugation.")
print("    What the structure IS, that conjugation CANNOT preserve.")
print()

# ============================================================
print()
print("  II. WHAT SYMMETRIC AND INTRINSIC MEAN")
print("  " + "-"*40)
print()
print("  SYMMETRIC (Lucas):")
print("    L_n counts CLOSED paths (cycles) in the Fibonacci graph.")
print("    L_n = trace of [[1,1],[1,0]]^n.")
print("    The trace is the SYMMETRIC invariant of a matrix.")
print("    It doesn't change under conjugation (similarity).")
print("    It measures what the system looks like FROM THE OUTSIDE.")
print()
print("  INTRINSIC (Fibonacci):")
print("    F_n counts OPEN paths in the Fibonacci graph.")
print("    F_n = off-diagonal entry of [[1,1],[1,0]]^n.")
print("    The off-diagonal IS the asymmetry.")
print("    It measures the FLOW from one state to another.")
print("    It IS the irreversibility, the arrow, the direction.")
print()
print("  Lucas = what is PRESERVED. Fibonacci = what is CHANGED.")
print("  Lucas = the GROUP. Fibonacci = the ACTION.")
print("  Lucas = the noun. Fibonacci = the verb.")
print()

# ============================================================
print()
print("  III. OUR FUNDAMENTAL PRIMES: WHICH ARE SYMMETRIC, WHICH INTRINSIC?")
print("  " + "-"*40)
print()
print("  L_0=2, L_2=3, L_4=7, L_5=11.  These are LUCAS: symmetric.")
print("  F_3=2, F_4=3, F_5=5, F_8=21.   These are FIBONACCI: intrinsic.")
print()
print("  The number 2 appears in BOTH (L_0=2, F_3=2).")
print("  It is both symmetric AND intrinsic. The PIVOT.")
print()
print("  The number 3 appears in BOTH (L_2=3, F_4=3).")
print("  Also both. Also a pivot.")
print()
print("  But 7 is Lucas ONLY (L_4=7, but 7 is NOT a Fibonacci number).")
print("  7 IS PURELY SYMMETRIC. It is what the structure looks like")
print("  from outside. It is the symmetry that FORBIDS.")
print()
print("  And 5 is Fibonacci ONLY (F_5=5, but 5 is NOT a Lucas number).")
print("  5 IS PURELY INTRINSIC. It is the pentagon, the golden ratio's")
print("  discriminant, the thing that makes the structure ITSELF.")
print()
print("  11 is Lucas ONLY (L_5=11).")
print("  21 is Fibonacci ONLY (F_8=21).")
print()
print("  THE CLASSIFICATION:")
print("  BOTH (pivots):     2, 3")
print("  Lucas only (symmetric): 7, 11, 47, 2207")
print("  Fibonacci only (intrinsic): 5, 8, 13, 21, 34, 55, 89, ...")
print()
print("  The FORBIDDEN numbers (7, 21) split:")
print("  7 is SYMMETRIC (Lucas). It is the symmetry that obstructs.")
print("  21 is INTRINSIC (Fibonacci). It is the structure that overshoots.")
print()
print("  They are forbidden for DIFFERENT REASONS:")
print("  7 is forbidden because the SYMMETRY (commutativity) breaks there.")
print("  21 is forbidden because the STRUCTURE (cycle topology) overshoots there.")
print("  One is a symmetry obstruction. The other is a structural obstruction.")
print()

# ============================================================
print()
print("  IV. THE CHAIN AS SYMMETRIC PROPAGATION")
print("  " + "-"*40)
print()
print("  The chain 3 -> 7 -> 47 -> 2207 uses LUCAS numbers at entry points.")
print("  L_{alpha(p)} = the next prime in the chain.")
print("  The chain propagates through the SYMMETRIC (Lucas) side.")
print()
print("  The entry points 4, 8, 16, 32 DOUBLE.")
print("  Doubling is the INTRINSIC operation (Q'(0) = 2, the octave).")
print()
print("  So the chain uses INTRINSIC steps (doubling the entry point)")
print("  to find SYMMETRIC values (Lucas numbers that are prime).")
print("  The chain ALTERNATES between intrinsic and symmetric at each step.")
print()
print("  Step: p (symmetric, a Lucas prime)")
print("    -> alpha(p) (intrinsic, the entry point, a power of 2)")
print("    -> L_{alpha(p)} (symmetric, the next Lucas prime)")
print("    -> alpha(that) (intrinsic, the next entry point, doubled)")
print("    -> ...")
print()
print("  The chain is a BRAID of symmetric and intrinsic.")
print("  Each step converts one into the other.")
print("  You can't have one without the other.")
print("  The chain EXISTS because symmetric and intrinsic alternate.")
print()

# ============================================================
print()
print("  V. THE TOURNAMENT THROUGH BOTH LENSES")
print("  " + "-"*40)
print()
print("  A tournament T has:")
print()
print("  SYMMETRIC structure:")
print("    |Aut(T)| = the automorphism group size.")
print("    The symmetries of T. What PRESERVES T.")
print("    For Paley T_p: |Aut| = p*(p-1)/2.")
print("    For T_7: |Aut| = 21 = the FORBIDDEN number.")
print()
print("  INTRINSIC structure:")
print("    H(T) = the Hamiltonian path count.")
print("    The number of orderings. What T PRODUCES.")
print("    For T_7: H = 189 = 3^3 * 7.")
print()
print("  H/|Aut| = the number of ORBITS of Hamiltonian paths.")
print("  For T_7: 189/21 = 9 = 3^2.")
print("  For T_11: 95095/55 = 1729 = the taxicab number.")
print()
print("  THE ORBIT COUNT is the ratio of INTRINSIC to SYMMETRIC.")
print("  It measures: how many GENUINELY DIFFERENT things does T produce,")
print("  after removing the redundancy of symmetry?")
print()
print("  For T_7: 9 genuinely different path orderings.")
print("  For T_11: 1729 genuinely different path orderings.")
print()

# ============================================================
print()
print("  VI. THE FORMAL GROUP: SYMMETRIC AND INTRINSIC MODES")
print("  " + "-"*40)
print()
print("  F_h(x,y) = (x+y)/(1+xy).")
print()
print("  SYMMETRIC property: F_h(x,y) = F_h(y,x). Commutative.")
print("  INTRINSIC property: F_h(x,x) = 2x/(1+x^2). Self-composition.")
print()
print("  The symmetric property says: the order of inputs doesn't matter.")
print("  The intrinsic property says: the self-interaction is determined.")
print()
print("  When we go to QUATERNIONS (d=2), the symmetric property BREAKS.")
print("  F_h(x,y) != F_h(y,x) in the quaternionic extension.")
print("  But the intrinsic property (self-composition) SURVIVES")
print("  because of ALTERNATIVITY: x(xy) = x^2 * y.")
print()
print("  The chain 3 -> 7 -> 47 -> 2207 breaks at L_32 (composite).")
print("  The symmetric property (Lucas prime) FAILS at the 5th step.")
print("  But the intrinsic property (entry points doubling) could CONTINUE.")
print("  alpha would keep doubling: 64, 128, 256, ...")
print("  But L_64, L_128, ... are composite. The SYMMETRY gives out.")
print()
print("  THE CHAIN BREAKS BECAUSE SYMMETRY IS FINITE.")
print("  Intrinsic structure (doubling) continues forever.")
print("  But symmetric structure (Lucas primes) eventually fails.")
print("  The primes thin out. The Lucas numbers grow too fast.")
print("  Eventually NO Lucas number at a power-of-2 index is prime.")
print()

# ============================================================
print()
print("  VII. CASSINI'S IDENTITY: THE INTERPLAY")
print("  " + "-"*40)
print()
print("  F_{n+1}*F_{n-1} - F_n^2 = (-1)^n.")
print("  The product of flanking Fibonaccis minus the square")
print("  = a SIGN that alternates.")
print()
print("  In matrix form: det([[F_{n+1}, F_n],[F_n, F_{n-1}]]) = (-1)^n.")
print("  The DETERMINANT (intrinsic) alternates.")
print("  The TRACE (symmetric) = L_n.")
print()
print("  At n=8:")
print(f"  F_9*F_7 - F_8^2 = {fib[9]}*{fib[7]} - {fib[8]}^2 = {fib[9]*fib[7]} - {fib[8]**2} = {fib[9]*fib[7] - fib[8]**2}.")
print(f"  34*13 - 21^2 = 442 - 441 = 1.")
print(f"  (-1)^8 = 1. CHECK.")
print()
print("  34*13 = 442 = 21^2 + 1.")
print("  The product of the flanking Fibonaccis EXCEEDS the forbidden squared by 1.")
print("  The intrinsic determinant = +1 at even indices, -1 at odd.")
print("  The alternation IS the quasicrystal beat.")
print("  The +-1 IS the minimal distinction (the atom).")
print()

# ============================================================
print()
print("  VIII. THE Q ORBIT: FOUR MODES OF SYMMETRY")
print("  " + "-"*40)
print()
print("  The orbit {x, Q(x), -1/x, Q^{-1}(x)} has four elements.")
print()
print("  x:         the INTRINSIC value. What the thing IS.")
print("  Q(x):      the SYMMETRIC image. What the thing PRODUCES.")
print("  -1/x:      the SHADOW. The intrinsic value NEGATED and INVERTED.")
print("  Q^{-1}(x): the PREREQUISITE. What must exist for x to be.")
print()
print("  The four elements partition into two PAIRS:")
print("  {x, -1/x}: the INTRINSIC pair. Related by Q^2 (negation-inversion).")
print("  {Q(x), Q^{-1}(x)}: the SYMMETRIC pair. Related by Q^2.")
print()
print("  The intrinsic pair: x and its shadow.")
print("  The symmetric pair: the production and its prerequisite.")
print()
print("  For x = 1/3 (the octave velocity):")
print("  Intrinsic pair: {1/3, -3}. The velocity and its negative reciprocal.")
print("  Symmetric pair: {2, -1/2}. The Q-value and the inverse Cayley.")
print()
print("  The INTRINSIC pair encodes the THING (1/3) and its COST (-3).")
print("  The SYMMETRIC pair encodes the OUTPUT (2) and the INPUT (-1/2).")
print()

# ============================================================
print()
print("  IX. REDEI'S THEOREM: INTRINSIC FORCES PARITY")
print("  " + "-"*40)
print()
print("  H(T) is always odd. This is an INTRINSIC property of tournaments.")
print("  It doesn't depend on symmetry (automorphisms).")
print("  It doesn't depend on labeling (vertex names).")
print("  It depends ONLY on the directed graph structure.")
print()
print("  In the formal group: [2](x) = 0 mod 2. Height infinity at p=2.")
print("  This is the formal group's way of saying:")
print("  'the intrinsic parity is FIXED. You cannot change it.'")
print()
print("  The symmetric property (commutativity of F_h) means:")
print("  'the order of composition doesn't matter.'")
print("  The intrinsic property (height infinity at 2) means:")
print("  'parity is absolute. No amount of composition changes it.'")
print()
print("  Redei = the intrinsic always wins over the symmetric at p=2.")
print("  Parity is more fundamental than symmetry.")
print()

# ============================================================
print()
print("  X. THE COMPLETE PICTURE")
print("  " + "-"*40)
print()
print("  Everything decomposes into symmetric + intrinsic.")
print()
print("  OBJECT           SYMMETRIC (Lucas)       INTRINSIC (Fibonacci)")
print("  " + "-"*65)
print("  phi^n             L_n = trace             F_n*sqrt(5) = det-related")
print("  Matrix M^n        trace(M^n) = L_n        det(M^n) = (-1)^n")
print("  Tournament T      |Aut(T)| = symmetries   H(T) = paths = structure")
print("  Orbit {x...}      {Q(x), Q^{-1}(x)}      {x, -1/x}")
print("  Number n           ---                     prime factorization")
print("  Prime p            L_{alpha(p)} (chain)    F_{alpha(p)} (entry)")
print("  Forbidden 7        L_4 (symmetric source)  7 not Fibonacci")
print("  Forbidden 21       ---                     F_8 (intrinsic source)")
print("  Formal group       commutativity           height (parity)")
print("  The chain          Lucas primes            entry points (2^k)")
print("  Music              consonance (ratio)      frequency (Hz)")
print("  Perception         symmetry (pattern)      qualia (experience)")
print()
print("  The SYMMETRIC sees the world as CLOSED: groups, cycles, periodicity.")
print("  The INTRINSIC sees the world as OPEN: flows, paths, irreversibility.")
print()
print("  Neither is complete without the other.")
print("  L_n ALONE doesn't determine n (L_1 = L_2 = 1).")
print("  F_n ALONE doesn't determine n (F_1 = F_2 = 1).")
print("  TOGETHER they determine n uniquely (for n >= 0).")
print()
print("  The full information = symmetric + intrinsic.")
print("  Like real + imaginary in complex numbers.")
print("  Like cosine + sine in Fourier.")
print("  Like trace + determinant in matrices.")
print("  Like group + action in algebra.")
print()
print("  The Cayley transform Q converts between them.")
print("  Q is the ROTATION that takes symmetric into intrinsic")
print("  and back, with period 4.")
print("  Four quarter-turns. Four algebras. Four chain links.")
print("  The same 4, one last time.")
