#!/usr/bin/env python3
"""ten_levels_s116f.py — Understanding the ten levels fully.

Not exploring new domains. Sitting with what we found.
Understanding each level completely and how they connect.
"""
from math import sqrt, log, pi, exp, atanh, tanh, cosh, sinh, acos
from fractions import Fraction

phi = (1+sqrt(5))/2

print()
print("  THE TEN LEVELS OF RAPIDITY")
print("  understood fully")
print()
print("="*70)
print()

# ============================================================
print("  LEVEL 0: THE FUNCTION")
print("  " + "-"*40)
print()
print("  Q(x) = (1+x)/(1-x)")
print()
print("  This is not just any function. It is the answer to a question.")
print("  The question: what is the simplest map from [-1,1] to [0,inf]")
print("  that preserves the GROUP STRUCTURE of composition?")
print()
print("  Composition meaning: if x and y combine as (x+y)/(1+xy),")
print("  then Q(x)*Q(y) = Q((x+y)/(1+xy)).")
print()

# Verify
x, y = Fraction(1,3), Fraction(1,5)
composed = (x+y)/(1+x*y)
Qx = (1+x)/(1-x)
Qy = (1+y)/(1-y)
Qc = (1+composed)/(1-composed)
print(f"  Verify: x=1/3, y=1/5")
print(f"  x (+) y = {composed}")
print(f"  Q(x)*Q(y) = {Qx}*{Qy} = {Qx*Qy}")
print(f"  Q(x(+)y) = Q({composed}) = {Qc}")
print(f"  Equal: {Qx*Qy == Qc}")
print()
print("  Q is the UNIQUE function (up to powers) with this property.")
print("  It is the exponential map of the velocity addition group.")
print("  Everything else we discovered flows from this one fact.")
print()

# ============================================================
print()
print("  LEVEL 1: THE THREE WORLDS")
print("  " + "-"*40)
print()
print("  The interval (-1, 1) is bounded.")
print("  The points {-1, +1} are the boundary.")
print("  The complement R \\ [-1,1] is unbounded.")
print()
print("  Q maps (-1,1) to (0,inf). This is not symmetric.")
print("  The bounded world is COMPACT (every sequence has a limit).")
print("  The unbounded world is NON-COMPACT (sequences can escape).")
print()
print("  The boundary {-1, +1} maps to {0, inf}.")
print("  These are the FIXED POINTS of the dynamics.")
print("  Every trajectory in the bounded world oscillates between them.")
print("  Every trajectory in the unbounded world escapes toward them.")
print()
print("  THE DEEP POINT:")
print("  The three worlds are not three PLACES.")
print("  They are three MODES OF BEING.")
print()
print("  Bounded = FINITE. Measurable. Observable. Verifiable.")
print("  Boundary = LIMITING. Asymptotic. Ideal. Unreachable.")
print("  Unbounded = INFINITE. Generative. Potential. Inexhaustible.")
print()
print("  Every physical quantity lives in the bounded world.")
print("  Its MEANING lives on the boundary.")
print("  Its STRUCTURE lives in the unbounded world.")
print()
print("  Example: a probability p in (0,1) is bounded.")
print("  Certainty (p=0 or p=1) is the boundary. Never truly reached.")
print("  The log-odds ln(p/(1-p)) lives in the unbounded world (-inf, inf).")
print("  The structure (linear regression, independence, Bayes) is THERE.")
print()

# ============================================================
print()
print("  LEVEL 2: THE PERIOD-4 SYMMETRY")
print("  " + "-"*40)
print()
print("  Q^4 = identity.")
print()
print("  This is not just a curiosity. It says:")
print("  THERE ARE EXACTLY FOUR WAYS TO LOOK AT ANYTHING.")
print()

x = Fraction(1,3)
orbit = [x]
for _ in range(3):
    x = (1+x)/(1-x)
    orbit.append(x)

print(f"  The orbit of 1/3: {orbit[0]} -> {orbit[1]} -> {orbit[2]} -> {orbit[3]} -> {orbit[0]}")
print()
print("  Face 1: x = 1/3       (the thing itself)")
print("  Face 2: Q(x) = 2      (what it produces)")
print("  Face 3: -1/x = -3     (what it costs)")
print("  Face 4: Q^{-1}(x) = -1/2  (what it requires)")
print()
print("  In any domain:")
print("  Face 1: the measurement (velocity, probability, concentration)")
print("  Face 2: the RATIO it generates (energy, odds, pH)")
print("  Face 3: the INVERSE COST (what you give up)")
print("  Face 4: the PREREQUISITE (what must exist for it to be)")
print()
print("  These four faces are related by Q, which rotates between them.")
print("  The rotation is NOT continuous. It is DISCRETE (order 4).")
print("  You cannot smoothly interpolate between the four views.")
print("  They are four COMPLEMENTARY perspectives.")
print()
print("  This is structurally identical to:")
print("  - The four DNA bases (A, T, G, C) with Watson-Crick pairing")
print("  - The four seasons (each the Q-transform of the previous)")
print("  - The four arithmetic operations (+, *, -, /) as a group")
print("  - The four elements of the Klein four-group Z_2 x Z_2")
print()
print("  Wait — Q generates Z_4, not the Klein four-group.")
print("  Z_4 is CYCLIC: 0 -> 1 -> 2 -> 3 -> 0.")
print("  Klein is ACYCLIC: every element is its own inverse.")
print("  Q^2 = -1/x is its own inverse: (-1/x)^{Q^2} = -1/(-1/x) = x. Yes!")
print("  But Q is NOT its own inverse: Q(Q(x)) = -1/x, not x.")
print("  So the four faces have a PREFERRED DIRECTION (chirality).")
print("  You can go 1->2->3->4, but NOT 1->4->3->2 (that would be Q^{-1}).")
print()

# ============================================================
print()
print("  LEVEL 3: WHY ARCTANH")
print("  " + "-"*40)
print()
print("  arctanh is the logarithm of Q.")
print("  ln(Q(x)) = ln((1+x)/(1-x)) = 2*arctanh(x).")
print()
print("  But WHY does the logarithm of Q have a name?")
print("  Because arctanh is the INVERSE of tanh,")
print("  and tanh is the UNIQUE bounded sigmoid that is:")
print("  - Odd: tanh(-x) = -tanh(x)")
print("  - Monotone: tanh'(x) > 0 for all x")
print("  - Asymptotic: tanh(x) -> +/-1 as x -> +/-inf")
print("  - Has derivative 1 at 0: tanh'(0) = 1")
print()
print("  There are infinitely many functions satisfying conditions 1-3.")
print("  Condition 4 (unit derivative at origin) normalizes the scale.")
print("  What makes tanh SPECIAL among all such functions?")
print()
print("  It is the ONLY one where the ADDITION THEOREM holds:")
print("  tanh(a+b) = (tanh(a)+tanh(b))/(1+tanh(a)*tanh(b))")
print()
print("  This addition theorem IS velocity addition in special relativity.")
print("  tanh is the UNIQUE sigmoid that makes velocity addition LINEAR.")
print()
print("  So: arctanh is the UNIQUE unbounding that linearizes")
print("  the UNIQUE bounded sigmoid with an addition theorem.")
print()
print("  The chain of uniqueness:")
print("  Addition theorem => tanh")
print("  Inversion => arctanh")
print("  Doubling => ln(Q)")
print("  Exponentiation => Q")
print()
print("  Q is forced. arctanh is forced. Rapidity is forced.")
print("  There is NO CHOICE in the matter.")
print("  Given that you want a group structure on a bounded interval,")
print("  you MUST get rapidity. It is the only option.")
print()

# ============================================================
print()
print("  LEVEL 4: THE HOMOMORPHISM")
print("  " + "-"*40)
print()
print("  f(n) = (n+1)/n satisfies f(a(+)b) = f(a)*f(b).")
print()
print("  This is the deepest algebraic result.")
print("  Let me understand what it MEANS.")
print()
print("  The composition a(+)b = ab/(a+b+1).")
print("  Define g(n) = 1 + 1/n = f(n). Then:")
print("  g(a(+)b) = 1 + 1/(ab/(a+b+1)) = 1 + (a+b+1)/(ab)")
print("           = 1 + 1/a + 1/b + 1/(ab)")
print("           = (1 + 1/a)(1 + 1/b)")
print("           = g(a)*g(b). QED.")
print()
print("  The proof is THREE LINES. That's how natural this is.")
print()
print("  What this means: the map n -> 1+1/n = (n+1)/n")
print("  converts the ADDITIVE structure of rapidity composition")
print("  into the MULTIPLICATIVE structure of ordinary arithmetic.")
print()
print("  This is exactly what the EXPONENTIAL function does:")
print("  exp converts addition to multiplication.")
print("  So f = 'exp' for rapidity composition.")
print()
print("  And indeed: f(n) = (n+1)/n = Q(1/(2n+1)) (for the right input).")
print("  f IS Q restricted to the right inputs.")
print("  The homomorphism IS the Cayley transform, viewed correctly.")
print()
print("  The INVERSE: if f(a)*f(b) = f(c), then a(+)b = c.")
print("  Multiplying superparticular ratios = composing rapidities.")
print("  This is why musical intervals MULTIPLY to give new intervals:")
print("  fifth * fourth = (3/2)*(4/3) = 2 = octave.")
print("  In rapidity: 2(+)3 = 6/(6) = 1. Yes! f(1) = 2 = octave.")

# Verify
a, b = 2, 3  # fifth and fourth
c = a*b // (a+b+1)
print(f"\n  Verify: a=2(fifth), b=3(fourth)")
print(f"  a(+)b = 2*3/(2+3+1) = 6/6 = {Fraction(a*b, a+b+1)} = 1")
print(f"  f(1) = 2/1 = octave. Correct!")
print()

# ============================================================
print()
print("  LEVEL 5: THE SUM OVER GEOMETRIES")
print("  " + "-"*40)
print()
print("  arctanh(x) = x + x^3/3 + x^5/5 + x^7/7 + ...")
print()
print("  The k-th term has coefficient 1/(2k+1).")
print("  And Q(1/(2k+1)) = (k+1)/k.")
print("  So the COEFFICIENT of the k-th term is the Cayley")
print("  pre-image of the k-th musical interval.")
print()
print("  This means: arctanh is a sum where each term is WEIGHTED")
print("  by the reciprocal of a musical frequency ratio.")
print("  The weight of the octave (2/1) term is 1/3.")
print("  The weight of the fifth (3/2) term is 1/5.")
print("  The weight of the fourth (4/3) term is 1/7.")
print()
print("  Higher intervals get LESS weight (1/(2k+1) decreases).")
print("  The octave dominates. Then the fifth. Then the fourth.")
print("  This is the OVERTONE SERIES of rapidity.")
print()
print("  At a deeper level: each term x^{2k+1}/(2k+1) is the")
print("  contribution of the (k+1)-gon to the coupling.")
print("  The triangle (k=1) contributes x.")
print("  The square (k=2) contributes x^3/3.")
print("  The pentagon (k=3) contributes x^5/5.")
print()
print("  When x is small, only the triangle matters.")
print("  When x approaches 1, all polygons contribute equally")
print("  and the sum diverges (the pole).")
print()
print("  THE POLE IS WHERE ALL GEOMETRIES ACTIVATE SIMULTANEOUSLY.")
print("  It is the point of MAXIMUM complexity.")
print("  No finite number of polygons can produce it.")
print("  It takes ALL of them, at once, to reach infinity.")
print()

# ============================================================
print()
print("  LEVEL 6: DISTINCTION")
print("  " + "-"*40)
print()
print("  This is the philosophical core.")
print()
print("  Before you can measure anything, you need TWO things")
print("  that are DIFFERENT. Measurement is comparison.")
print("  Without distinction, there is no information.")
print()
print("  Rapidity quantifies distinction.")
print("  rapidity = 0 means 'identical' (no distinction).")
print("  rapidity = infinity means 'maximally different'.")
print()
print("  The key insight: distinction is always RELATIVE.")
print("  There is no absolute 'amount of difference'.")
print("  Only ratios of differences are meaningful.")
print("  And ratios are what rapidity measures.")
print()
print("  Q(x) = (1+x)/(1-x) is a RATIO.")
print("  The numerator 1+x = the 'similarity' (what's shared).")
print("  The denominator 1-x = the 'dissimilarity' (what differs).")
print("  Q = similarity / dissimilarity.")
print()
print("  When x=0: Q=1. Similarity = dissimilarity. No distinction.")
print("  When x->1: Q->inf. All similarity, no dissimilarity. Total distinction.")
print("  When x<0: Q<1. More dissimilarity than similarity. Reversed.")
print()
print("  THIS IS WHAT Q COMPUTES: the ratio of sameness to difference.")
print("  And rapidity = ln(Q)/2 = half the log of that ratio.")
print("  The factor of 2 is because distinction is TWO-SIDED:")
print("  you can measure from A toward B, or from B toward A.")
print("  The average of the two perspectives gives the factor 1/2.")
print()

# ============================================================
print()
print("  LEVEL 7: SL(2,R)")
print("  " + "-"*40)
print()
print("  Q as a matrix: [[1,1],[-1,1]] acting on the projective line.")
print("  This matrix has determinant 1*1 - 1*(-1) = 2.")
print("  Normalized: (1/sqrt(2)) * [[1,1],[-1,1]], determinant 1.")
print("  This is an element of SL(2,R).")
print()
print("  SL(2,R) is the group of 2x2 real matrices with determinant 1.")
print("  It is the symmetry group of:")
print("  - The hyperbolic plane (isometries)")
print("  - The upper half-plane (Mobius transforms)")
print("  - The unit disk (biholomorphisms)")
print("  - 1+1 dimensional spacetime (Lorentz boosts + rotations)")
print("  - The projective line RP^1")
print()
print("  Its Lie algebra sl(2,R) has dimension 3.")
print("  Generators: H = [[1,0],[0,-1]], E = [[0,1],[0,0]], F = [[0,0],[1,0]].")
print("  [H,E] = 2E, [H,F] = -2F, [E,F] = H.")
print()
print("  The rapidity parameter phi corresponds to the BOOST generator:")
print("  exp(phi * [[0,1],[1,0]]) = [[cosh(phi), sinh(phi)],[sinh(phi), cosh(phi)]]")
print()
print("  This is a HYPERBOLIC ROTATION in the (t,x) plane.")
print("  Rapidity = the angle of hyperbolic rotation.")
print()
print("  EVERY time rapidity appears, the Lie group SL(2,R) is acting.")
print("  The 20+ domains where we found rapidity are 20+")
print("  REPRESENTATIONS of SL(2,R) on different spaces.")
print()
print("  The music space: SL(2,R) acts on frequency ratios.")
print("  The probability space: SL(2,R) acts on odds.")
print("  The chemistry space: SL(2,R) acts on EN ratios.")
print("  The computation space: SL(2,R) acts on search spaces.")
print()
print("  They are ALL the same group, acting on different sets.")
print("  Rapidity is the Lie algebra parameter that labels the action.")
print()

# ============================================================
print()
print("  LEVEL 8: THE TRINITY")
print("  " + "-"*40)
print()
print("  Three domains. Three maps. One triangle.")
print()
print("       Disk D (bounded)")
print("       /          \\")
print("      Q            exp")
print("     /              \\")
print("  Half-plane H --- Circle S^1")
print("        \\        /")
print("         log (= inverse exp)")
print()
print("  D = {|z| < 1}: the domain of PARAMETERS.")
print("  H = {Re(z) > 0}: the domain of VALUES.")
print("  S^1 = {|z| = 1}: the domain of PHASES.")
print()
print("  Q: D -> H converts parameters to values.")
print("  exp: R -> S^1 converts real numbers to phases.")
print("  log: H -> R converts values to real numbers.")
print()
print("  Rapidity = log . Q: D -> R.")
print("  It converts PARAMETERS directly to REAL NUMBERS.")
print("  It bypasses the intermediate domain (H).")
print()
print("  The trinity is not a decoration. It is the MINIMAL structure")
print("  needed to have both BOUNDEDNESS (D) and PERIODICITY (S^1)")
print("  in the same framework. The half-plane (H) mediates between them.")
print()
print("  In physics: D = velocities (bounded by c).")
print("              S^1 = phases (periodic, 2pi).")
print("              H = energies (positive, unbounded).")
print("  The Wick rotation (t -> it) is the map D -> S^1 via H.")
print("  It converts real rapidities to imaginary phases.")
print("  This is WHY quantum mechanics uses complex amplitudes:")
print("  the same group SL(2,R) acts on real boosts AND imaginary phases.")
print()

# ============================================================
print()
print("  LEVEL 9: THE INFORMATION PHASE TRANSITION")
print("  " + "-"*40)
print()
print("  The KL divergence from fair: D(p || 1/2).")
print("  In rapidity coordinates (phi = arctanh(2p-1)):")
print("  D = phi*tanh(phi) - ln(cosh(phi))")
print()

# Compute and show the transition
print("  phi     tanh(phi)   D_KL        D_KL/phi^2   D_KL/|phi|")
print("  " + "-"*60)
for phi_val in [0.01, 0.05, 0.1, 0.2, 0.5, 0.8, 1.0, 1.2, 1.5, 2.0, 3.0, 5.0]:
    t = tanh(phi_val)
    D = phi_val * t - log(cosh(phi_val))
    ratio_quad = D / phi_val**2 if phi_val > 0 else 0
    ratio_lin = D / abs(phi_val) if phi_val > 0 else 0
    print(f"  {phi_val:5.2f}   {t:8.5f}    {D:10.6f}    {ratio_quad:8.4f}       {ratio_lin:8.4f}")

print()
print("  For small phi: D ~ phi^2/2 (Gaussian regime).")
print("  For large phi: D ~ |phi| - ln(2) (exponential regime).")
print("  The crossover: where phi^2/2 ~ |phi|, i.e., phi ~ 2.")
print()
print("  But the PRACTICAL crossover (where the quadratic and linear")
print("  contributions are EQUAL) is at phi ~ 1.")
print()
tanh_1 = tanh(1.0)
print(f"  At phi = 1: tanh(1) = {tanh_1:.6f}")
print(f"  p = (1 + tanh(1))/2 = {(1+tanh_1)/2:.6f}")
print(f"  Q(tanh(1)) = (1+tanh(1))/(1-tanh(1)) = {(1+tanh_1)/(1-tanh_1):.6f}")
print(f"  = e^2 = {exp(2):.6f}")
print()
print(f"  At phi such that p = 3/4: phi = arctanh(1/2) = {atanh(0.5):.6f}")
print(f"  Q(1/2) = 3. tanh(arctanh(1/2)) = 1/2. p = 3/4.")
print()
print("  Kleiber's 3/4 corresponds to phi = arctanh(1/2) = ln(3)/2 = 0.549.")
print("  This is NOT at the crossover (phi ~ 1-2).")
print("  But Q(3/4) = 7 corresponds to phi = arctanh(3/4) = ln(7)/2 = 0.973.")
print("  THIS is near the crossover.")
print()
print("  So the forbidden number 7 sits AT the information crossover.")
print("  And 3/4 = the Cayley address of 7 = the probability where")
print("  the Q-value first reaches the impossible.")
print()
print("  Biology's 3/4 law may reflect that living systems operate")
print("  at the boundary where their internal information processing")
print("  transitions from Gaussian (predictable) to exponential (chaotic).")
print("  The organism must be complex enough to adapt (phi > 0)")
print("  but not so complex that it becomes unpredictable (phi < crossover).")
print("  The optimum is at the EDGE: phi ~ 1, p ~ 3/4, Q ~ 7.")
print()

# ============================================================
print()
print("  LEVEL 10: SELF-REFERENCE")
print("  " + "-"*40)
print()
print("  Q(Q(x)) = -1/x.")
print()
print("  Applying Q twice does not return to x.")
print("  It gives the NEGATIVE RECIPROCAL.")
print("  This is NOT the identity. It is something deeper.")
print()
print("  -1/x is the map that:")
print("  - Sends large things to small things (and vice versa)")
print("  - Reverses the sign (flips the orientation)")
print("  - Is its own inverse: -1/(-1/x) = x")
print()
print("  So Q^2 is an INVOLUTION. It divides the world into")
print("  pairs (x, -1/x) that are 'Q^2-related'.")
print("  These pairs are: (1/3, -3), (1/2, -2), (1/5, -5), ...")
print("  Each pair consists of a number and its 'shadow'.")
print()
print("  The self-reference: when we ANALYZE rapidity, we apply")
print("  a kind of Q to our understanding. The analysis produces")
print("  something that is NOT what we started with (x),")
print("  but its COMPLEMENT (-1/x).")
print()
print("  Understanding a thing fully means seeing BOTH it and its shadow.")
print("  1/3 (the velocity) and -3 (the negative reciprocal).")
print("  The bounded and the unbounded.")
print("  The concrete and the abstract.")
print()
print("  And after TWO more steps (Q^3, Q^4), we return to the start.")
print("  The cycle is: thing -> product -> shadow -> prerequisite -> thing.")
print("  Understanding completes in four steps, not two.")
print("  You must go around the full orbit to see all four faces.")
print()

# ============================================================
print()
print("="*70)
print()
print("  HOW THE TEN LEVELS CONNECT")
print()
print("="*70)
print()
print("  The levels are not a LIST. They are a LATTICE.")
print()
print("  Level 0 (function) supports Level 2 (symmetry) and Level 3 (uniqueness).")
print("  Level 1 (three worlds) supports Level 8 (trinity).")
print("  Level 2 (period 4) connects to Level 10 (self-reference) via Q^2.")
print("  Level 3 (uniqueness) supports Level 7 (SL(2,R)).")
print("  Level 4 (homomorphism) supports Level 5 (geometry sum).")
print("  Level 5 (geometry sum) supports Level 6 (distinction).")
print("  Level 6 (distinction) is the SUMMIT — the meaning.")
print("  Level 7 (SL(2,R)) is the FOUNDATION — the structure.")
print("  Level 8 (trinity) UNIFIES Levels 1 and 7.")
print("  Level 9 (phase transition) APPLIES Levels 6 and 7 to biology.")
print("  Level 10 (self-reference) CLOSES the circle.")
print()
print("  The lattice has two pillars:")
print("  LEFT PILLAR (structure): 0 -> 2 -> 3 -> 7 -> 8")
print("  RIGHT PILLAR (meaning):  0 -> 4 -> 5 -> 6 -> 9")
print("  BRIDGE: Level 1 connects both pillars via Level 8.")
print("  CAPSTONE: Level 10 closes both pillars into a cycle.")
print()
print("  The structure pillar says: THIS IS WHAT RAPIDITY IS.")
print("  The meaning pillar says: THIS IS WHAT RAPIDITY DOES.")
print("  The bridge says: THE TWO ARE THE SAME.")
print("  The capstone says: AND IT KNOWS IT.")
print()

# ============================================================
print()
print("="*70)
print()
print("  THE SINGLE SENTENCE")
print()
print("="*70)
print()
print("  If the ten levels must be compressed to one sentence:")
print()
print("  Rapidity is the logarithm of the ratio of sameness to difference,")
print("  and it is the same function everywhere because comparison itself")
print("  is the same operation everywhere.")
print()
print("  If even that is too long:")
print()
print("  Rapidity counts doublings.")
print()
print("  If even THAT is too long:")
print()
print("  Q.")
