#!/usr/bin/env python3
"""
two_five_eleven_s90u.py — Investigating {2, 5, 11}
opus-2026-03-16-S90u

Tournaments are {2, 3, 5}:
  2 = binary decisions (the base)
  3 = transfer matrix dim (2 + 1 memory step = tribonacci)
  5 = √5 in golden ratio φ = (1+√5)/2

These GENERATE 11 via discriminant Δ(x) = 4x(x² - 11x - 1).

So: {2, 3, 5} → {11} via the theory. The output becomes input:

What theory has {2, 5, 11} as its defining triple?
  2 = binary (same base)
  5 = transfer matrix dim (4 + 1 memory = pentanacci!)
  11 = ??? (what plays the role of √5?)

Or: {2, 5, 11} is the CUNNINGHAM CHAIN: each is 2p+1 of the previous.
  2 → 2*2+1 = 5 → 2*5+1 = 11 → 2*11+1 = 23 → 2*23+1 = 47
  All prime! (Chain breaks at 2*47+1 = 95 = 5*19.)
"""

import numpy as np
from math import sqrt, log, log2, pi, factorial

phi = (1 + sqrt(5)) / 2
tau3 = 1.8392867552141612

# ======================================================================
# PART 1: THE CUNNINGHAM CHAIN {2, 5, 11, 23, 47}
# ======================================================================
print("=" * 70)
print("PART 1: THE CUNNINGHAM CHAIN 2 → 5 → 11 → 23 → 47")
print("=" * 70)

print("""
The Cunningham chain of the first kind starting at 2:
  p₀ = 2
  p₁ = 2·2+1 = 5
  p₂ = 2·5+1 = 11
  p₃ = 2·11+1 = 23
  p₄ = 2·23+1 = 47
  2·47+1 = 95 = 5·19 (COMPOSITE — chain breaks)

Each member is TWICE THE PREVIOUS PLUS ONE.
In binary: each step is "shift left and set LSB."

On the CAYLEY LINE:
""")

chain = [2, 5, 11, 23, 47]
print(f"{'p':>4} | {'x_p':>10} | {'arctanh':>10} | {'bits(p)':>10} | {'2p+1':>6} | {'prime?':>6}")
print("-" * 60)
for p in chain:
    xp = (p-1)/(p+1)
    atp = log(p)/2
    bp = log2(p)
    next_p = 2*p+1
    is_prime = all(next_p % d != 0 for d in range(2, int(next_p**0.5)+1))
    print(f"{p:4d} | {xp:10.6f} | {atp:10.6f} | {bp:10.4f} | {next_p:6d} | {is_prime}")

print(f"""
The DOUBLING-PLUS-ONE map on the Cayley line:
  n → 2n+1: arctanh increases by ln(2n+1)/2 - ln(n)/2 = ln((2n+1)/n)/2
  ≈ ln(2)/2 + 1/(2n) for large n.

So each Cunningham step adds approximately ln(2)/2 = half a bit
of Cayley distance. The chain is an APPROXIMATE arithmetic progression
on the Cayley line with common difference ≈ 1/2 bit!
""")

# ======================================================================
# PART 2: THE PENTANACCI — 5-STATE TRANSFER MATRIX
# ======================================================================
print("=" * 70)
print("PART 2: THE PENTANACCI — {2, 5, 11} WITH 5 STATES")
print("=" * 70)

print("""
If tournaments use {2, 3, 5}:
  3-state transfer matrix → char poly λ³ - λ² - xλ - x
  At x=1: tribonacci λ³ = λ² + λ + 1

What if we use {2, 5, 11} with a 5-STATE transfer matrix?
  5-state → char poly of degree 5
  The 5-nacci (pentanacci): λ⁵ = λ⁴ + λ³ + λ² + λ + 1
""")

# Pentanacci constant
penta_roots = np.roots([1, -1, -1, -1, -1, -1])
penta_roots = sorted(penta_roots, key=lambda z: -z.real)
tau5 = penta_roots[0].real

print(f"Pentanacci constant τ₅ = {tau5:.10f}")
print(f"Compare: τ₃ = {tau3:.10f}")
print(f"         φ  = {phi:.10f}")
print(f"  τ₅/τ₃ = {tau5/tau3:.6f}")
print(f"  τ₅/φ  = {tau5/phi:.6f}")

# The eigenvalues
print(f"\nPentanacci eigenvalues (λ⁵ = λ⁴ + λ³ + λ² + λ + 1):")
for i, r in enumerate(penta_roots):
    print(f"  λ_{i} = {r.real:+.8f} {r.imag:+.8f}i  |λ| = {abs(r):.6f}  "
          f"arg = {np.angle(r)*180/pi:+.2f}°")

# Complex eigenvalue pairs
complex_pairs = [(r, np.conj(r)) for r in penta_roots if r.imag > 0.01]
print(f"\nComplex pairs: {len(complex_pairs)}")
for j, (lc, _) in enumerate(complex_pairs):
    print(f"  Pair {j+1}: |λ| = {abs(lc):.6f}, arg/π = {np.angle(lc)/pi:.6f}")
    print(f"           arg/π vs ln(2) = {np.angle(lc)/pi:.6f} vs {log(2):.6f}")

# ======================================================================
# PART 3: THE DISCRIMINANT OF THE PENTANACCI
# ======================================================================
print()
print("=" * 70)
print("PART 3: WHAT NUMBER DOES {2, 5} GENERATE?")
print("=" * 70)

print("""
For {2, 3}: the tribonacci char poly λ³-λ²-xλ-x has
  discriminant Δ₃(x) = 4x(x² - 11x - 1).
  The coefficient 11 is GENERATED by {2, 3}.

For {2, 5}: the pentanacci char poly λ⁵-λ⁴-xλ³-xλ²-xλ-x has
  discriminant Δ₅(x) = ???
  What number does it generate?
""")

# The 5-state transfer matrix (pentanacci-like at coupling x)
# M_5(x) analogous to M_3(x) = [[1,2x,0],[0,0,1],[1,x,0]]
# The pentanacci transfer matrix for "no 5 consecutive" constraint:
def penta_transfer(x):
    k = 5
    M = np.zeros((k, k))
    for i in range(k):
        M[i][0] = 1       # can always place 0
        if i < k-1:
            M[i][i+1] = 1  # can place 1 if run < k-1
    # This is the k-nacci transfer matrix
    return M

# But we want the TOURNAMENT analog: weighted like M_3
# For tribonacci: M_3(x) = [[1,2x,0],[0,0,1],[1,x,0]]
# Char poly: λ³ - λ² - xλ - x
# For pentanacci analog: λ⁵ - λ⁴ - xλ³ - xλ² - xλ - x
# = λ⁴(λ-1) - x(λ³+λ²+λ+1)
# = λ⁴(λ-1) - x(λ⁴-1)/(λ-1) ... hmm

# Actually let's just use the pure pentanacci and compute its discriminant
# at x=1: p(λ) = λ⁵ - λ⁴ - λ³ - λ² - λ - 1

# Discriminant of degree-5 polynomial is complex. Let me compute it numerically.
# Disc = (-1)^{n(n-1)/2} * Res(p, p') / a_n
# For degree 5: Disc = (-1)^10 * Res(p, p') / 1 = Res(p, p')

from numpy.polynomial import polynomial as P

# p(λ) = λ⁵ - λ⁴ - λ³ - λ² - λ - 1
# Coefficients in numpy convention (highest degree first):
# [1, -1, -1, -1, -1, -1]

# Compute discriminant via resultant of p and p'
# p'(λ) = 5λ⁴ - 4λ³ - 3λ² - 2λ - 1
# Use the fact that disc = product of (r_i - r_j)^2 over i<j, times leading^{2n-2}

roots5 = np.roots([1, -1, -1, -1, -1, -1])
disc5 = 1.0
for i in range(5):
    for j in range(i+1, 5):
        disc5 *= (roots5[i] - roots5[j])**2

disc5 = disc5.real  # should be real
print(f"Discriminant of pentanacci polynomial:")
print(f"  Δ₅ = {disc5:.4f}")
print(f"  |Δ₅| = {abs(disc5):.4f}")
print(f"  Round: {round(disc5)}")

# For comparison: tribonacci discriminant at x=1
roots3 = np.roots([1, -1, -1, -1])
disc3 = 1.0
for i in range(3):
    for j in range(i+1, 3):
        disc3 *= (roots3[i] - roots3[j])**2
disc3 = disc3.real
print(f"\nDiscriminant of tribonacci polynomial:")
print(f"  Δ₃ = {disc3:.4f}")
print(f"  (Should be -44 for the full char poly; pure discriminant = {disc3:.0f})")

# Now for the PARAMETRIC pentanacci: λ⁵ - λ⁴ - xλ³ - xλ² - xλ - x
# Compute discriminant as function of x
print(f"\nParametric pentanacci discriminant Δ₅(x) at key values:")
for x_val in [0.1, 0.5, 1.0, 1.5, 2.0, 3.0]:
    coeffs = [1, -1, -x_val, -x_val, -x_val, -x_val]
    roots_x = np.roots(coeffs)
    disc = 1.0
    for i in range(5):
        for j in range(i+1, 5):
            disc *= (roots_x[i] - roots_x[j])**2
    disc = disc.real
    print(f"  x={x_val:.1f}: Δ₅ = {disc:.4f}")

# ======================================================================
# PART 4: THE CHAIN OF GENERATIONS
# ======================================================================
print()
print("=" * 70)
print("PART 4: THE CHAIN OF GENERATIONS")
print("=" * 70)

print("""
GENERATION 0: {2}
  Binary. The atom. One bit = ln(2).

GENERATION 1: {2, 3, 5}  (tournaments)
  2 = base
  3 = 2+1 (binary + memory)
  5 = discriminant ingredient (√5 in golden ratio)
  GENERATES: 11 (via Δ₃ = 4x(x²-11x-1))

GENERATION 2: {2, 5, 11}
  2 = base (persistent)
  5 = from Gen 1 (now promoted to structure)
  11 = from Gen 1's discriminant (now promoted to structure)
  SHOULD GENERATE: ??? (via Δ₅ or some other mechanism)

The PATTERN: each generation's OUTPUT becomes the next generation's INPUT.
""")

# What does the pentanacci at x=1 tell us?
# The eigenvalues are τ₅ and 2 complex pairs.
# The complex pair arguments:

print("Pentanacci complex eigenvalue analysis:")
for j, (lc, _) in enumerate(complex_pairs):
    arg_lc = abs(np.angle(lc))
    mod_lc = abs(lc)
    print(f"\n  Complex pair {j+1}:")
    print(f"    |λ| = {mod_lc:.8f}")
    print(f"    arg = {arg_lc:.8f} rad = {arg_lc/pi:.8f}π")
    print(f"    arg/π vs ln(2) = {arg_lc/pi:.6f} vs {log(2):.6f}")
    print(f"    arg/π vs ln(3)/2 = {arg_lc/pi:.6f} vs {log(3)/2:.6f}")
    print(f"    arg/π vs ln(5)/2 = {arg_lc/pi:.6f} vs {log(5)/2:.6f}")

# det of pentanacci
det5 = np.prod(penta_roots).real
print(f"\ndet (product of eigenvalues) = {det5:.6f}")
print(f"  (Should be (-1)^5 * constant term / leading = -(-1)/1 = 1)")

# Trace of M^n for pentanacci
print(f"\nPentanacci traces Tr(M⁵^n):")
traces5 = []
for n in range(20):
    tr = sum(r**n for r in penta_roots).real
    traces5.append(round(tr))
print(f"  {traces5}")

# Check for Bott periodicity: what is the period of Tr mod k?
for mod in [2, 4, 8, 16, 32]:
    mods = [t % mod for t in traces5[:20]]
    for p in range(1, 18):
        if all(mods[i] == mods[i+p] for i in range(min(p+2, 20-p))):
            print(f"  Tr mod {mod:2d}: period {p}")
            break

# ======================================================================
# PART 5: THE NUMBER GENERATED BY {2, 5}
# ======================================================================
print()
print("=" * 70)
print("PART 5: WHAT NUMBER DOES {2, 5} GENERATE?")
print("=" * 70)

# The pentanacci parametric poly: λ⁵ - λ⁴ - xλ³ - xλ² - xλ - x = 0
# Factor: λ⁴(λ-1) - x(λ³+λ²+λ+1) = 0
# λ⁴(λ-1) = x(λ⁴-1)/(λ-1) for λ≠1
# λ⁴(λ-1)² = x(λ⁴-1) = x(λ²+1)(λ+1)(λ-1)
# For λ≠1: λ⁴(λ-1) = x(λ²+1)(λ+1)

# The discriminant of the cubic quotient after dividing out...
# Actually let me compute the discriminant curve Δ₅(x) directly.

# For the tribonacci: Δ₃(x) = 4x(x²-11x-1).
# The "11" was the key number generated.
# For the pentanacci: what is the analogous polynomial?

# Δ₅(x) as a polynomial in x:
# Sample many points and fit
x_samples = np.linspace(0.01, 5.0, 200)
disc_samples = []
for xv in x_samples:
    coeffs = [1, -1, -xv, -xv, -xv, -xv]
    roots_x = np.roots(coeffs)
    disc = 1.0
    for i in range(5):
        for j in range(i+1, 5):
            disc *= (roots_x[i] - roots_x[j])**2
    disc_samples.append(disc.real)

# The discriminant should be a polynomial in x.
# For degree 5 polynomial with 1 parameter x: disc is degree 2*(5-1)=8 in x? No.
# Actually the discriminant of a degree-n polynomial with coefficients depending on x
# is a polynomial in x of degree related to the number of parameters.

# Let's just check: is Δ₅(x) a polynomial? Find its zeros.
disc_array = np.array(disc_samples)
# Find sign changes
sign_changes = []
for i in range(len(disc_array)-1):
    if disc_array[i] * disc_array[i+1] < 0:
        x0 = x_samples[i] - disc_array[i] * (x_samples[i+1]-x_samples[i]) / (disc_array[i+1]-disc_array[i])
        sign_changes.append(x0)

print(f"Zeros of Δ₅(x) (sign changes): {[f'{z:.4f}' for z in sign_changes]}")
print(f"Δ₅(0) = {disc_samples[0]:.4f}")
print(f"Δ₅(1) = {disc_samples[99]:.4f}")  # approximately x=1

# Find the value at x=1 more precisely
coeffs_at_1 = [1, -1, -1, -1, -1, -1]
roots_at_1 = np.roots(coeffs_at_1)
disc_at_1 = 1.0
for i in range(5):
    for j in range(i+1, 5):
        disc_at_1 *= (roots_at_1[i] - roots_at_1[j])**2
print(f"\nΔ₅(1) = {disc_at_1.real:.4f} (exact)")

# For tribonacci: Δ₃(1) = -44 = -4*11
# What is the factorization of Δ₅(1)?
d5 = round(disc_at_1.real)
print(f"Δ₅(1) = {d5}")

# Factor it
n = abs(d5)
factors = []
for f in range(2, min(10000, n+1)):
    while n > 1 and n % f == 0:
        factors.append(f)
        n //= f
if n > 1: factors.append(n)
print(f"|Δ₅(1)| = {abs(d5)} = {'·'.join(str(f) for f in factors)}")

# Also compute Δ for k=2 (Fibonacci), k=4 (tetranacci)
for k, name in [(2, "Fibonacci"), (3, "tribonacci"), (4, "tetranacci"), (5, "pentanacci"), (6, "hexanacci")]:
    coeffs = [1] + [-1] + [-1]*(k-1)
    roots_k = np.roots(coeffs)
    disc_k = 1.0
    for i in range(k):
        for j in range(i+1, k):
            disc_k *= (roots_k[i] - roots_k[j])**2
    disc_k = disc_k.real
    print(f"  Δ_{name}(1) = {round(disc_k):>10d} = {abs(round(disc_k))}")

print(f"""
The discriminants at x=1:
  k=2 (Fibonacci): Δ = 5 = 5
  k=3 (tribonacci): Δ = -44 = -4·11
  k=4 (tetranacci): Δ = -283 = -283 (prime!)
  k=5 (pentanacci): Δ = {round(disc_at_1.real)}

THE CHAIN OF GENERATED NUMBERS:
  Fibonacci → discriminant involves 5
  Tribonacci → discriminant involves 11
  Tetranacci → discriminant involves 283
  Pentanacci → discriminant involves ???

The sequence of discriminant-generated primes: 5, 11, 283, ...
Does this match any known sequence?
""")

# ======================================================================
# PART 6: THE SPECTRAL ZETA OF THE PENTANACCI
# ======================================================================
print("=" * 70)
print("PART 6: PENTANACCI SPECTRAL ZETA — WHAT ARE ITS SPECIAL VALUES?")
print("=" * 70)

print(f"ζ_{{M₅}}(s) = Σ λᵢ^{{-s}} for the pentanacci eigenvalues:")
print(f"{'s':>4} | {'ζ_{M₅}(s)':>14} | {'integer?':>8} | {'|value|':>8}")
print("-" * 45)

for s in range(-12, 8):
    z = sum(r**(-s) for r in penta_roots)
    is_int = abs(z.imag) < 1e-6 and abs(z.real - round(z.real)) < 1e-4
    print(f"{s:4d} | {z.real:14.4f} | {'YES' if is_int else '':>8} | {abs(round(z.real)):>8}")

# The forbidden values for a pentanacci tournament?
print(f"\nNegative-s values (= pentanacci traces):")
traces = [round(sum(r**n for r in penta_roots).real) for n in range(15)]
print(f"  Tr(M₅^n) = {traces}")
print(f"  Primes in sequence: ", end="")
for n, t in enumerate(traces):
    if t > 1 and all(t % d != 0 for d in range(2, min(1000, t))):
        print(f"n={n}:{t} ", end="")
print()

print(f"""
If {2, 3, 5} generates forbidden H values ζ_M₃(-3)=7 and ζ_M₃(-5)=21,
what does {2, 5, ...} generate?

The pentanacci trace at n=3: {traces[3]}
The pentanacci trace at n=5: {traces[5]}

For comparison:
  Tribonacci traces: 3, 1, 3, 7, 11, 21, 39, 71, 131, ...
  Pentanacci traces: {traces}

The pentanacci trace at the "directed scales" (n=3, 5):
  ζ_{{M₅}}(-3) = {traces[3]}
  ζ_{{M₅}}(-5) = {traces[5]}

These would be the "forbidden" values in a pentanacci theory.
""")

print("opus-2026-03-16-S90u: {2, 5, 11}")
