#!/usr/bin/env python3
"""universal_s116i.py — The universal zone.

We proved: F_h is isomorphic to F_m.
The hyperbolic formal group IS the multiplicative formal group.
tanh IS exp (in different coordinates).
arctanh IS log (in different coordinates).

But this isomorphism itself — what IS it?
It is Q-1 = 2x/(1-x).
The Cayley transform, shifted by 1.

So: the isomorphism between bounded and unbounded
IS the Cayley transform.
The bridge between the two coordinate systems
IS the object we started with.

The map IS the territory.
"""
from math import log, exp, sqrt, pi, atanh, tanh, cosh, sinh

phi = (1+sqrt(5))/2

print()
print("  THE UNIVERSAL ZONE")
print()
print("="*70)
print()

print("  tanh and exp are the same function.")
print("  arctanh and log are the same function.")
print("  The bounded and the unbounded are the same world.")
print()
print("  This is not metaphor. It is isomorphism.")
print()

# ============================================================
print()
print("  I. THE ISOMORPHISM, STATED PLAINLY")
print("  " + "-"*40)
print()
print("  exp(t) = 1 + 2*tanh(t/2) / (1 - tanh(t/2))")
print("         = Q(tanh(t/2))")
print()
print("  That is: exp = Q composed with tanh(./2).")
print("  The exponential IS the Cayley transform of the half-tanh.")
print()

# Verify
for t in [0.5, 1.0, 1.5, 2.0, 3.0]:
    lhs = exp(t)
    rhs = (1 + tanh(t/2)) / (1 - tanh(t/2))
    print(f"  t={t}: exp(t) = {lhs:.8f}, Q(tanh(t/2)) = {rhs:.8f}, match: {abs(lhs-rhs)<1e-10}")

print()
print("  And inversely:")
print("  log(x) = 2*arctanh((x-1)/(x+1))")
print("         = 2*arctanh(Q^{-1}(x))")
print()

for x in [2.0, 3.0, 7.0, phi, exp(1)]:
    lhs = log(x)
    rhs = 2*atanh((x-1)/(x+1))
    print(f"  x={x:.4f}: log(x) = {lhs:.8f}, 2*arctanh(Q^-1(x)) = {rhs:.8f}, match: {abs(lhs-rhs)<1e-10}")

print()
print("  log = 2 * arctanh * Q^{-1}.")
print("  exp = Q * tanh(./2).")
print()
print("  These are not two functions. They are ONE function (Q)")
print("  composed with itself (tanh = Q^{-1} * exp, essentially).")
print()

# ============================================================
print()
print("  II. WHAT THE ISOMORPHISM IS MADE OF")
print("  " + "-"*40)
print()
print("  Q^{-1}(x) = (x-1)/(x+1). The INVERSE Cayley transform.")
print()
print("  Q^{-1} maps (0, inf) -> (-1, 1).")
print("  It takes a POSITIVE NUMBER and returns a VELOCITY.")
print("  It takes a RATIO and returns a COMPARISON.")
print()
print("  log(x) = 2 * arctanh(Q^{-1}(x)).")
print("  = 2 * arctanh((x-1)/(x+1)).")
print("  = 2 * (half the rapidity of the comparison (x-1)/(x+1)).")
print("  = the rapidity of the comparison between x and 1.")
print()
print("  THE LOGARITHM MEASURES HOW x COMPARES TO 1.")
print("  It does this by:")
print("  1. Computing the comparison: (x-1)/(x+1) (Cayley inverse)")
print("  2. Measuring the comparison: arctanh (rapidity)")
print("  3. Doubling: factor of 2 (from the order of Q)")
print()
print("  Three steps. Compare, measure, double.")
print("  That is ALL the logarithm does.")
print()

# ============================================================
print()
print("  III. THE DUALITY")
print("  " + "-"*40)
print()
print("  tanh: BOUNDED -> BOUNDED.    Input: rapidity. Output: velocity.")
print("  arctanh: BOUNDED -> UNBOUNDED. Input: velocity. Output: rapidity.")
print()
print("  exp: UNBOUNDED -> UNBOUNDED. Input: exponent. Output: value.")
print("  log: UNBOUNDED -> UNBOUNDED. Input: value. Output: exponent.")
print()
print("  The isomorphism Q-1 maps BETWEEN the two pairs:")
print("  Q^{-1}: unbounded -> bounded. (Contracts.)")
print("  Q:      bounded -> unbounded. (Expands.)")
print()
print("  So the duality is:")
print()
print("      BOUNDED WORLD              UNBOUNDED WORLD")
print("    (velocities, probabilities)  (energies, odds)")
print("         tanh <-->                    exp")
print("         arctanh <-->                 log")
print("              \\       Q          /")
print("               \\     -->        /")
print("                \\   <--        /")
print("                 Q^{-1}")
print()
print("  Q and Q^{-1} are the FERRY between the two worlds.")
print("  tanh and exp are the SAME function, one on each shore.")
print("  arctanh and log are the SAME function, one on each shore.")
print()

# ============================================================
print()
print("  IV. THE UNIVERSAL PROPERTY")
print("  " + "-"*40)
print()
print("  Q is the UNIQUE Mobius transformation that:")
print("  1. Maps -1 to 0 (sends 'total disagreement' to 'nothing')")
print("  2. Maps 0 to 1 (sends 'neutral' to 'unity')")
print("  3. Maps 1 to infinity (sends 'total agreement' to 'everything')")
print()
print("  Any function satisfying 1-3 is Q (up to reparametrization).")
print("  There is no choice. The three fixed points determine Q.")
print()
print("  And these three points are:")
print("  -1: the MINIMUM (total negation)")
print("   0: the CENTER (perfect balance)")
print("  +1: the MAXIMUM (total affirmation)")
print()
print("  Q maps minimum -> zero, center -> one, maximum -> infinity.")
print("  It maps the three QUALITATIVE states (no, maybe, yes)")
print("  to the three QUANTITATIVE landmarks (0, 1, infinity).")
print()
print("  This is WHY Q is universal.")
print("  Any system with a bounded parameter has a min, center, max.")
print("  Q is the unique map that translates these to 0, 1, infinity.")
print("  It is the CANONICAL coordinate change from bounded to unbounded.")
print()

# ============================================================
print()
print("  V. THE DUALITY OF tanh AND arctanh IS SELF-KNOWLEDGE")
print("  " + "-"*40)
print()
print("  tanh: given effort, predict progress.")
print("  arctanh: given progress, reconstruct effort.")
print()
print("  They are INVERSE functions. But more than that:")
print("  they are the TWO DIRECTIONS of understanding.")
print()
print("  FORWARD (tanh): I know how hard I've worked (rapidity).")
print("  How much have I achieved (velocity)?")
print("  Answer: tanh(rapidity). Always less than 1. Diminishing returns.")
print()
print("  BACKWARD (arctanh): I can see where I am (velocity).")
print("  How much effort did it take to get here (rapidity)?")
print("  Answer: arctanh(velocity). Grows without bound near 1.")
print()
print("  The forward direction is HUMBLE: you never reach 1.")
print("  The backward direction is HONEST: the cost was infinite-feeling.")
print()
print("  Together they form a LOOP:")
print("  effort -> progress -> recognize progress -> realize effort -> ...")
print()
print("  This loop is self-knowledge.")
print("  tanh says: this is what you've done.")
print("  arctanh says: this is what it cost.")
print("  The loop says: doing and costing are the same thing")
print("  seen from two directions.")
print()

# ============================================================
print()
print("  VI. THE FORMAL GROUP IS SELF-KNOWLEDGE SHARED")
print("  " + "-"*40)
print()
print("  F_h(x,y) = (x+y)/(1+xy).")
print()
print("  This is what happens when TWO self-knowing agents combine.")
print("  Agent A has velocity x (their progress).")
print("  Agent B has velocity y (their progress).")
print("  Together: F_h(x,y) = combined progress.")
print()
print("  The combination is NOT x+y (linear addition).")
print("  It is (x+y)/(1+xy) (nonlinear, bounded by 1).")
print("  Two 0.8s give F_h(0.8, 0.8) = {:.4f}, not 1.6.".format(
    (0.8+0.8)/(1+0.8*0.8)))
print("  The whole is LESS than the sum of the parts.")
print("  This is the price of BOUNDEDNESS.")
print()
print("  But in rapidity (after arctanh): the efforts ADD.")
print("  arctanh(F_h(x,y)) = arctanh(x) + arctanh(y).")
print("  In effort-space, combination is HONEST addition.")
print("  The bounded world conceals this. The unbounded world reveals it.")
print()

# ============================================================
print()
print("  VII. THE THREE TRANSCENDENTALS AS THREE KINDS OF COMBINATION")
print("  " + "-"*40)
print()
print("  e: what you get when you combine CONTINUOUSLY.")
print("     exp(t) = lim (1+t/n)^n as n -> infinity.")
print("     Infinitely many infinitesimal contributions.")
print("     The result of PATIENT accumulation.")
print()
print("  pi: what you get when you combine CYCLICALLY.")
print("     exp(2*pi*i) = 1. The accumulation that returns to start.")
print("     The result of COMPLETE rotation.")
print()
print("  phi: what you get when you combine SELF-SIMILARLY.")
print("     phi = 1 + 1/phi. The fixed point of x -> 1 + 1/x.")
print("     The result of RECURSIVE accumulation.")
print()
print("  Three modes of accumulation:")
print("  e:   accumulate SMALL things patiently. -> growth.")
print("  pi:  accumulate EQUAL things cyclically. -> rotation.")
print("  phi: accumulate YOURSELF recursively.   -> self-similarity.")
print()
print("  These are the only three things you can do with accumulation:")
print("  grow, rotate, or self-reflect.")
print("  And each mode has its own transcendental constant.")
print()

# ============================================================
print()
print("  VIII. THE ISOMORPHISM AT THE META LEVEL")
print("  " + "-"*40)
print()
print("  We sought the 'fundamental isomorphism at the most meta level'.")
print()
print("  Here it is:")
print()
print("  THE BOUNDED AND THE UNBOUNDED ARE ISOMORPHIC.")
print("  THE ISOMORPHISM IS Q.")
print("  Q IS THE ACT OF COMPARISON ITSELF.")
print()
print("  This is not a mathematical statement about a specific function.")
print("  It is a statement about the STRUCTURE OF KNOWING.")
print()
print("  To know something is to COMPARE it to a reference.")
print("  The comparison produces a bounded quantity (how alike/different).")
print("  The bounded quantity maps to an unbounded one (the log-odds).")
print("  The unbounded quantity is where structure lives (linearity, additivity).")
print()
print("  But the bounded and unbounded quantities are THE SAME INFORMATION.")
print("  They are isomorphic. Q witnesses the isomorphism.")
print("  Knowing this — that the two worlds are one — is the meta-level insight.")
print()
print("  And the duality of tanh/arctanh is the duality of:")
print("  DOING (tanh: effort -> limited progress)")
print("  UNDERSTANDING (arctanh: progress -> unbounded meaning)")
print()
print("  They are inverse functions.")
print("  They are the two halves of a single act of comprehension.")
print("  Neither is complete without the other.")
print()

# ============================================================
print()
print("  IX. WHY THERE IS EXACTLY ONE FORMAL GROUP")
print("  " + "-"*40)
print()
print("  Over Q (rational numbers), all 1-dimensional commutative")
print("  formal groups are isomorphic. There is only ONE.")
print()
print("  The additive group (F_a), the multiplicative group (F_m),")
print("  and the hyperbolic group (F_h) are all the SAME GROUP")
print("  in different coordinate systems.")
print()
print("  Addition, multiplication, and velocity composition")
print("  are THREE NOTATIONS for ONE operation.")
print()
print("  This is the deepest fact:")
print("  THERE IS ONLY ONE WAY TO COMBINE THINGS COMMUTATIVELY")
print("  IN ONE DIMENSION OVER THE RATIONALS.")
print()
print("  Every 'different' operation you think you see")
print("  (adding, multiplying, composing velocities, stacking intervals,")
print("  combining probabilities, mixing chemicals, breeding organisms)")
print("  is the SAME operation in different coordinates.")
print()
print("  The coordinates differ.")
print("  The operation does not.")
print()
print("  Q is the map between coordinates.")
print("  arctanh is the map to the universal coordinate (where it's addition).")
print("  tanh is the map FROM the universal coordinate (to whatever you're working in).")
print()
print("  There is only one group. There is only one map. There is only one duality.")
print("  Everything else is notation.")
print()

# ============================================================
print()
print("="*70)
print()
print("  THE FINAL STATEMENT")
print()
print("="*70)
print()
print("  Over the rationals, in one dimension, commutatively:")
print()
print("  There is one group.")
print("  It has one logarithm (arctanh) and one exponential (tanh).")
print("  It is bounded on one side (tanh) and unbounded on the other (exp).")
print("  The bridge between sides is Q.")
print("  The bridge has period 4.")
print("  The logarithm's Taylor series sums over all odd numbers.")
print("  Each odd number is the sum of two consecutive integers.")
print("  The consecutive pair is the atom.")
print("  The atom can't be split.")
print("  Some assemblies of atoms are forbidden.")
print("  The forbidden assemblies are where the topology overshoots.")
print("  The overshoot is a cascade.")
print("  The cascade is the structure asserting itself.")
print("  The structure is the formal group.")
print("  The formal group is the one group.")
print()
print("  It goes in a circle.")
print("  That is the period-4 symmetry.")
print("  That is Q^4 = identity.")
print("  That is the final statement: it returns to itself.")
