#!/usr/bin/env python3
"""
verify_moon_realizability_fresh_opus_0614.py

FRESH, independent verification (NOT reusing h_realizability_goldbach_macmini_0611s2.py).
Different implementation choices throughout:
  - Hamiltonian-path counter implemented two independent ways and cross-checked:
      (a) brute-force permutation enumeration (ground truth, small n)
      (b) bitmask DP (Held-Karp style) written from scratch
  - Tournament representation: store arcs as a frozenset of ordered pairs / a beats-set per vertex.
  - gentourng decoding written independently.

Claims under test:
 (1) MOON multiplicativity: H(T1 => T2) = H(T1)*H(T2) for dominance join.
 (2) R_5 = {1,3,5,9,11,13,15}; 7 only odd gap below 15; 7,21 not realizable for n<=7;
     49 IS realizable at n=7.
 (3) strong-tournament minH over m vertices = 3,5,9,15,23 for m=3..7; formula m^2-5m+9.
 (4) Realizable set vs multiplicative semigroup generated by strong-tournament H atoms.
"""
import sys, subprocess, itertools
from math import comb

GEN = "/opt/homebrew/bin/gentourng"


# ------------------------------------------------------------------
# gentourng decoding (independent implementation)
# ------------------------------------------------------------------
def gen_iso_tournaments(n, strong_only=False):
    """Yield 'beats' adjacency as list of int bitmasks: beats[i] has bit j set if i->j.
    Decoded from gentourng default ascii upper-triangle row-by-row output."""
    args = [GEN]
    if strong_only:
        args.append("-c")
    args.append(str(n))
    out = subprocess.run(args, capture_output=True, text=True)
    pairs = list(itertools.combinations(range(n), 2))   # (0,1),(0,2),...,(0,n-1),(1,2),...
    L = len(pairs)
    for line in out.stdout.split():
        bits = line.strip()
        if len(bits) != L:
            continue
        beats = [0] * n
        for (i, j), b in zip(pairs, bits):
            if b == '1':
                beats[i] |= (1 << j)   # i -> j
            else:
                beats[j] |= (1 << i)   # j -> i
        yield beats


# ------------------------------------------------------------------
# Hamiltonian path counter -- METHOD A: brute force over permutations
# ------------------------------------------------------------------
def H_bruteforce(beats):
    n = len(beats)
    cnt = 0
    for perm in itertools.permutations(range(n)):
        ok = True
        for a in range(n - 1):
            u, v = perm[a], perm[a + 1]
            if not (beats[u] >> v) & 1:   # need arc u->v
                ok = False
                break
        if ok:
            cnt += 1
    return cnt


# ------------------------------------------------------------------
# Hamiltonian path counter -- METHOD B: bitmask DP (independent code)
# count directed Ham paths in a tournament = sum over all (start,end) of paths
# dp[mask][v] = number of directed paths covering exactly vertices in mask, ending at v.
# ------------------------------------------------------------------
def H_dp(beats):
    n = len(beats)
    full = (1 << n) - 1
    # incoming[v] = bitmask of u with u->v
    incoming = [0] * n
    for u in range(n):
        bm = beats[u]
        v = 0
        while bm:
            if bm & 1:
                incoming[v] |= (1 << u)
            bm >>= 1
            v += 1
    dp = [[0] * n for _ in range(1 << n)]
    for v in range(n):
        dp[1 << v][v] = 1
    for mask in range(1, 1 << n):
        row = dp[mask]
        for v in range(n):
            if not (mask >> v) & 1:
                continue
            cv = row[v]
            if cv == 0:
                continue
            # extend by w with v->w (w not in mask)
            succ = beats[v] & ~mask & full
            w = 0
            s = succ
            while s:
                if s & 1:
                    dp[mask | (1 << w)][w] += cv
                s >>= 1
                w += 1
    return sum(dp[full])


# ------------------------------------------------------------------
# Dominance join T1 => T2 (every vertex of T1 beats every vertex of T2)
# ------------------------------------------------------------------
def dominance_join(beats1, beats2):
    n1, n2 = len(beats1), len(beats2)
    n = n1 + n2
    beats = [0] * n
    # T1 vertices 0..n1-1 keep their internal arcs
    for i in range(n1):
        beats[i] = beats1[i]
    # T2 vertices shifted by n1
    for i in range(n2):
        bm = beats2[i]
        shifted = 0
        v = 0
        while bm:
            if bm & 1:
                shifted |= (1 << (v + n1))
            bm >>= 1
            v += 1
        beats[n1 + i] = shifted
    # every T1 vertex beats every T2 vertex
    t2mask = 0
    for j in range(n1, n):
        t2mask |= (1 << j)
    for i in range(n1):
        beats[i] |= t2mask
    return beats


# ------------------------------------------------------------------
# CLAIM 1: Moon multiplicativity
# ------------------------------------------------------------------
def claim1():
    print("=" * 70)
    print("CLAIM 1: MOON multiplicativity H(T1=>T2)=H(T1)H(T2)")
    print("=" * 70)
    # cross-check the two counters on all iso tournaments n=3..6 first
    print("\n[1a] Cross-check brute-force vs DP counter, all iso classes n=3..6:")
    mismatch = 0
    for n in range(3, 7):
        for beats in gen_iso_tournaments(n):
            hb = H_bruteforce(beats) if n <= 7 else None
            hd = H_dp(beats)
            if hb is not None and hb != hd:
                mismatch += 1
                print(f"  MISMATCH n={n}: brute={hb} dp={hd}")
        print(f"  n={n}: OK (both counters agree on all {sum(1 for _ in gen_iso_tournaments(n))} classes)")
    print(f"  total mismatches: {mismatch}")

    # Now multiplicativity: take ALL iso classes T1 of size a, T2 of size b,
    # form join, check H(join)==H(T1)*H(T2). Use a,b up to total <=7.
    print("\n[1b] H(T1=>T2)=H(T1)*H(T2) over iso classes, |T1|+|T2|<=7:")
    fails = 0
    tested = 0
    for a in range(1, 7):
        for b in range(1, 7):
            if a + b > 7:
                continue
            T1s = list(gen_iso_tournaments(a)) if a >= 3 else [trivial(a)]
            T2s = list(gen_iso_tournaments(b)) if b >= 3 else [trivial(b)]
            for beats1 in T1s:
                for beats2 in T2s:
                    h1 = H_dp(beats1)
                    h2 = H_dp(beats2)
                    j = dominance_join(beats1, beats2)
                    hj = H_dp(j)
                    tested += 1
                    if hj != h1 * h2:
                        fails += 1
                        print(f"  FAIL a={a} b={b}: H1={h1} H2={h2} prod={h1*h2} Hjoin={hj}")
    print(f"  tested {tested} join pairs, failures: {fails}")

    # explicit examples
    print("\n[1c] Explicit examples:")
    examples = []
    c3 = list(gen_iso_tournaments(3))   # cyclic (H=3) and transitive (H=1)
    for beats in c3:
        examples.append((3, beats, H_dp(beats)))
    # pick the 3-cycle (H=3) and transitive (H=1)
    cyc3 = [b for _, b, h in examples if h == 3][0]
    tr3 = [b for _, b, h in examples if h == 1][0]
    for (name1, t1, h1), (name2, t2, h2) in [
        (("C3", cyc3, 3), ("C3", cyc3, 3)),
        (("C3", cyc3, 3), ("Tr3", tr3, 1)),
        (("Tr3", tr3, 1), ("C3", cyc3, 3)),
    ]:
        j = dominance_join(t1, t2)
        hj = H_dp(j)
        print(f"  H({name1}=>{name2}) = {hj}, H1*H2 = {h1*h2}  {'OK' if hj==h1*h2 else 'FAIL'}")
    return fails == 0 and mismatch == 0


def trivial(a):
    """trivial/transitive tournament on a vertices as beats list (i beats j iff i<j gives a path);
    for a=1 single vertex, a=2 single arc."""
    beats = [0] * a
    for i in range(a):
        for j in range(i + 1, a):
            beats[i] |= (1 << j)
    return beats


# ------------------------------------------------------------------
# CLAIM 2: Realizable sets, gaps, 7/21 forbidden, 49 realizable
# ------------------------------------------------------------------
def claim2():
    print("\n" + "=" * 70)
    print("CLAIM 2: Realizable sets R_n, gaps, 7/21 forbidden, 49 realizable")
    print("=" * 70)
    R = {}
    for n in range(1, 8):
        vals = set()
        if n <= 2:
            vals.add(H_dp(trivial(n)) if n >= 1 else 0)
            # n=1 -> 1 path (single vertex), n=2 -> 1 path
        else:
            for beats in gen_iso_tournaments(n):
                vals.add(H_dp(beats))
        R[n] = vals
        print(f"  R_{n} = {sorted(vals)}")
    print()
    print(f"  R_5 == {{1,3,5,9,11,13,15}} ? {sorted(R[5]) == [1,3,5,9,11,13,15]}")
    # 7 only odd gap below 15 in R_5
    odds_below_15 = set(range(1, 16, 2))
    gaps5 = sorted(odds_below_15 - R[5])
    print(f"  odd gaps below 15 in R_5: {gaps5}  (7 only? {gaps5==[7]})")
    # 7 and 21 not realizable at any n<=7
    seven_any = any(7 in R[n] for n in R)
    twentyone_any = any(21 in R[n] for n in R)
    print(f"  7 realizable at any n<=7? {seven_any}")
    print(f"  21 realizable at any n<=7? {twentyone_any}")
    # 49 realizable at n=7
    print(f"  49 in R_7? {49 in R[7]}")
    # is 49 a strong-tournament H value directly?
    strongH7 = set()
    for beats in gen_iso_tournaments(7, strong_only=True):
        strongH7.add(H_dp(beats))
    print(f"  49 a STRONG-tournament H value at n=7 (not a product)? {49 in strongH7}")
    return R


# ------------------------------------------------------------------
# CLAIM 3: strong-tournament minimum H = 3,5,9,15,23 ; formula m^2-5m+9
# ------------------------------------------------------------------
def claim3():
    print("\n" + "=" * 70)
    print("CLAIM 3: strong-tournament min H per m, formula m^2-5m+9")
    print("=" * 70)
    minH = {}
    strongH = {}
    for m in range(3, 8):
        vals = set()
        for beats in gen_iso_tournaments(m, strong_only=True):
            vals.add(H_dp(beats))
        strongH[m] = vals
        minH[m] = min(vals)
        formula = m * m - 5 * m + 9
        print(f"  m={m}: minH={minH[m]:>4}  formula(m^2-5m+9)={formula:>4}  "
              f"{'OK' if minH[m]==formula else 'MISMATCH'}   strongH set={sorted(vals)}")
    seq = [minH[m] for m in range(3, 8)]
    print(f"  minH sequence m=3..7: {seq}  expected [3,5,9,15,23]? {seq==[3,5,9,15,23]}")
    return strongH


# ------------------------------------------------------------------
# CLAIM 4: realizable set = multiplicative semigroup of strong-H atoms?
# ------------------------------------------------------------------
def claim4(R, strongH):
    print("\n" + "=" * 70)
    print("CLAIM 4: R_n as multiplicative closure of strong-tournament H atoms")
    print("=" * 70)
    # atoms: strong-tournament H-values for m=1..7.
    # m=1 (single vertex) is strong by convention, H=1 -> multiplicative identity.
    # build atom list with their vertex sizes
    atoms = {1: {1}}            # m=1 -> H=1
    # m=2 is NOT strong (no strong tournament on 2 vertices); skip
    for m in range(3, 8):
        atoms[m] = set(strongH[m])
    print("  Strong-H atom sets:")
    for m in sorted(atoms):
        print(f"    m={m}: {sorted(atoms[m])}")

    # multiplicative closure: products of strong-H values where the TOTAL vertex
    # count (sum of m's) <= N. A tournament on n vertices decomposes uniquely into
    # strong components in a transitive order (condensation is transitive), and H
    # is multiplicative over them (Claim 1). So R_n should equal the set of products
    # h_{m1}*...*h_{mk} with m1+...+mk = n, each h_{mi} a strong-H value on mi verts
    # (mi=1 contributes factor 1; mi>=3 contributes a strong-H atom; mi=2 impossible
    #  as a strong component).
    def closure_for_n(N):
        # dp over vertex budget: reachable[v] = set of products achievable using
        # strong components summing to exactly v
        reach = {0: {1}}
        for v in range(1, N + 1):
            s = set()
            # last strong component has size c (c=1, or c>=3)
            for c in list([1]) + list(range(3, v + 1)):
                if c not in atoms:
                    continue
                if (v - c) in reach:
                    for p in reach[v - c]:
                        for a in atoms[c]:
                            s.add(p * a)
            if s:
                reach[v] = s
        return reach.get(N, set())

    print("\n  Compare closure(n) vs R_n for n=3..7 (sanity, should match exactly):")
    for n in range(3, 8):
        cl = closure_for_n(n)
        print(f"    n={n}: closure==R_n ? {cl==R[n]}   "
              f"(closure {sorted(cl)[:12]}{'...' if len(cl)>12 else ''})")

    # Now the real test: R_8 interior via closure (we cannot easily gentourng n=8
    # iso classes = 6880, but we CAN: 6880 is fine. Let's actually compute R_8 directly
    # too for a hard check, plus closure.)
    print("\n  Building R_8 directly via gentourng (6880 classes) ...")
    R8 = set()
    cnt = 0
    for beats in gen_iso_tournaments(8):
        R8.add(H_dp(beats))
        cnt += 1
    print(f"    enumerated {cnt} classes; R_8 = {sorted(R8)}")
    cl8 = closure_for_n(8)
    print(f"    closure(8) = {sorted(cl8)}")
    print(f"    closure(8) == R_8 ? {cl8 == R8}")
    if cl8 != R8:
        print(f"      in R_8 not in closure: {sorted(R8 - cl8)}")
        print(f"      in closure not in R_8: {sorted(cl8 - R8)}")

    # permanent gaps: which odd numbers never appear?
    # Gather all realizable up to n=8
    allR = set()
    for n in R:
        allR |= R[n]
    allR |= R8
    maxv = max(allR)
    odd_gaps = sorted(set(range(1, maxv + 1, 2)) - allR)
    print(f"\n  All realizable H up to n=8: {sorted(allR)}")
    print(f"  Max realizable (n<=8): {maxv}")
    print(f"  Odd gaps below max (n<=8): {odd_gaps}")
    print(f"  Are 7 and 21 the only gaps that look permanent? "
          f"{set([g for g in odd_gaps if g<=21])}")
    return R8, cl8


if __name__ == "__main__":
    ok1 = claim1()
    R = claim2()
    strongH = claim3()
    R8, cl8 = claim4(R, strongH)
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"  Claim1 multiplicativity holds & counters agree: {ok1}")
