#!/usr/bin/env python3
"""
verify_thm481_golay_agentv.py  --  ADVERSARIAL verification of THM-481 claim.

CLAIM under attack:
  Let H be the order-24 skew-Hadamard matrix bordered from the Paley
  tournament on F_23:
      H[inf,inf] = 1, H[inf,j] = 1, H[i,inf] = -1, H[i,i] = 1,
      H[i,j] = chi(j-i)   (chi = quadratic character mod 23).
  Then the binary code spanned over GF(2) by the rows of (J-H)/2 is the
  extended binary Golay code [24,12,8].

ADVERSARIAL STRATEGY (everything built from scratch, no imports from any
project script):
  1. Build H from the definition; CHECK it really is skew-Hadamard
     (H + H^T = 2I, H H^T = 24 I).  If not, the claim's premise fails.
  2. Build C_paley = rowspan_{GF(2)} (J-H)/2.
  3. INDEPENDENT Golay construction: factor x^23 - 1 over GF(2) by brute
     force trial division (all 2^10 monic degree-11 candidates), obtain the
     two degree-11 irreducible factors g1, g2; build BOTH cyclic [23,12]
     QR codes <g1>, <g2>; extend each by overall parity (parity bit = inf
     coordinate).  Verify each is [23,12,7] -> [24,12,8] by full
     enumeration (4096 codewords).
  4. Identify which cyclic code is the "QNR-idempotent" QR code: the one
     containing (and generated by) the idempotent E_N(x) = sum_{n in QNR} x^n.
     (Check E_N^2 = E_N mod x^23-1, membership, and that <E_N> has dim 12.)
  5. Check subspace EQUALITY (canonical RREF basis) of C_paley against each
     extended QR code; if equal to the "other" one instead, test equality
     up to the negation permutation j -> -j (fixing inf) and report which.
  6. Verify on C_paley: dim = 12, doubly-even, self-dual, d = 8,
     weight distribution {0:1, 8:759, 12:2576, 16:759, 24:1}.

Coordinates: bit j (0..22) = field element / exponent j;  bit 23 = inf.

Author: agent verifier (fresh code), 2026-06-11.
"""

import sys

P = 23
INF = 23          # bit index of the inf coordinate
NBITS = 24
X23P1 = (1 << 23) | 1          # x^23 + 1 over GF(2)

FAILURES = []

def check(name, ok, detail=""):
    status = "PASS" if ok else "FAIL"
    print(f"[{status}] {name}" + (f"  -- {detail}" if detail else ""))
    if not ok:
        FAILURES.append(f"{name}: {detail}")

# ----------------------------------------------------------------------
# 0. quadratic residues mod 23
# ----------------------------------------------------------------------
QR = sorted({(i * i) % P for i in range(1, P)})
QNR = sorted(set(range(1, P)) - set(QR))
print("QR  mod 23:", QR)
print("QNR mod 23:", QNR)
check("|QR| = |QNR| = 11", len(QR) == 11 and len(QNR) == 11)
check("chi(-1) = -1 (23 = 3 mod 4, needed for skewness)", (P - 1) in QNR)

def chi(a):
    a %= P
    assert a != 0
    return 1 if a in QR else -1

# ----------------------------------------------------------------------
# 1. Build bordered H exactly per the claim; verify skew-Hadamard
# ----------------------------------------------------------------------
# index 0..22 = field elements, index 23 = inf
H = [[0] * NBITS for _ in range(NBITS)]
H[INF][INF] = 1
for j in range(P):
    H[INF][j] = 1          # H[inf, j] = 1
    H[j][INF] = -1         # H[i, inf] = -1
for i in range(P):
    for j in range(P):
        H[i][j] = 1 if i == j else chi(j - i)

# H H^T = 24 I
ok_had = all(
    sum(H[i][k] * H[j][k] for k in range(NBITS)) == (24 if i == j else 0)
    for i in range(NBITS) for j in range(NBITS)
)
check("H is Hadamard: H H^T = 24 I", ok_had)
ok_skew = all(
    H[i][j] + H[j][i] == (2 if i == j else 0)
    for i in range(NBITS) for j in range(NBITS)
)
check("H is skew: H + H^T = 2 I", ok_skew)

# ----------------------------------------------------------------------
# 2. C_paley = rowspan of (J - H)/2 over GF(2), rows as 24-bit ints
# ----------------------------------------------------------------------
def row_to_mask(row):
    m = 0
    for j in range(NBITS):
        v = (1 - row[j]) // 2          # (J-H)/2 entrywise
        assert v in (0, 1)
        if v:
            m |= 1 << j
    return m

paley_rows = [row_to_mask(H[i]) for i in range(NBITS)]
check("row inf of (J-H)/2 is all-zero", paley_rows[INF] == 0)
check("each field row of (J-H)/2 has weight 12",
      all(bin(r).count('1') == 12 for r in paley_rows[:P]))

def rref(vectors):
    """Reduced row echelon basis (canonical) of span over GF(2)."""
    basis = []
    for v in vectors:
        for b in basis:
            v = min(v, v ^ b)
        if v:
            basis.append(v)
            basis.sort(reverse=True)
    # full reduction
    for i in range(len(basis)):
        for j in range(len(basis)):
            if i != j:
                lead = 1 << (basis[j].bit_length() - 1)
                if basis[i] & lead:
                    basis[i] ^= basis[j]
    return sorted(basis, reverse=True)

C_paley = rref(paley_rows)
check("dim C_paley = 12", len(C_paley) == 12, f"dim = {len(C_paley)}")

def span_words(basis):
    words = [0]
    for b in basis:
        words += [w ^ b for w in words]
    return words

paley_words = span_words(C_paley)

# ----------------------------------------------------------------------
# 3. INDEPENDENT construction: factor x^23 - 1 over GF(2) by brute force
# ----------------------------------------------------------------------
def pmulmod(a, b, mod=None):
    r = 0
    bb = b
    sh = 0
    while bb:
        if bb & 1:
            r ^= a << sh
        bb >>= 1
        sh += 1
    if mod is not None:
        r = pmod(r, mod)
    return r

def pmod(a, b):
    db = b.bit_length() - 1
    while a.bit_length() - 1 >= db and a:
        a ^= b << (a.bit_length() - 1 - db)
    return a

# all monic degree-11 polynomials with constant term 1 dividing x^23+1
deg11_factors = []
for c in range(1 << 10):
    cand = (1 << 11) | (c << 1) | 1
    if pmod(X23P1, cand) == 0:
        deg11_factors.append(cand)
check("exactly two degree-11 factors of x^23+1", len(deg11_factors) == 2,
      f"found {len(deg11_factors)}")
g1, g2 = deg11_factors

def poly_str(g):
    return " + ".join(f"x^{k}" if k > 1 else ("x" if k == 1 else "1")
                      for k in range(g.bit_length() - 1, -1, -1)
                      if (g >> k) & 1)

print(f"g1 = {poly_str(g1)}   (mask {g1:#x})")
print(f"g2 = {poly_str(g2)}   (mask {g2:#x})")
check("(x+1)*g1*g2 = x^23+1",
      pmulmod(pmulmod(g1, g2), 0b11) == X23P1)
check("g1, g2 are reciprocals of each other",
      int(format(g1, '012b')[::-1], 2) == g2)

def cyclic_code(g):
    """[23, 23-deg(g)] cyclic code generated by g: rows x^i * g."""
    dim = P - (g.bit_length() - 1)
    return rref([g << i for i in range(dim)])

def parity_extend_basis(basis23):
    out = []
    for v in basis23:
        w = v
        if bin(v).count('1') & 1:
            w |= 1 << INF
        out.append(w)
    return rref(out)

Q1 = cyclic_code(g1)
Q2 = cyclic_code(g2)
check("dim <g1> = dim <g2> = 12", len(Q1) == 12 and len(Q2) == 12)

# min distance of the length-23 codes (full enumeration, 4096 words each)
def wdist(words, nbits):
    d = {}
    for w in words:
        wt = bin(w).count('1')
        d[wt] = d.get(wt, 0) + 1
    return d

wd1 = wdist(span_words(Q1), 23)
wd2 = wdist(span_words(Q2), 23)
check("<g1> is a [23,12,7] code", min(k for k in wd1 if k > 0) == 7)
check("<g2> is a [23,12,7] code", min(k for k in wd2 if k > 0) == 7)

eQ1 = parity_extend_basis(Q1)
eQ2 = parity_extend_basis(Q2)

# ----------------------------------------------------------------------
# 4. Which cyclic code is the QNR-idempotent QR code?
# ----------------------------------------------------------------------
E_N = 0
for n in QNR:
    E_N |= 1 << n
E_Q = 0
for r in QR:
    E_Q |= 1 << r

check("E_N = sum_{n in QNR} x^n is idempotent mod x^23-1",
      pmulmod(E_N, E_N, X23P1) == E_N)
check("E_Q = sum_{r in QR} x^r is idempotent mod x^23-1",
      pmulmod(E_Q, E_Q, X23P1) == E_Q)

en_in_g1 = pmod(E_N, g1) == 0
en_in_g2 = pmod(E_N, g2) == 0
eq_in_g1 = pmod(E_Q, g1) == 0
eq_in_g2 = pmod(E_Q, g2) == 0
print(f"E_N in <g1>: {en_in_g1};  E_N in <g2>: {en_in_g2}")
print(f"E_Q in <g1>: {eq_in_g1};  E_Q in <g2>: {eq_in_g2}")
check("E_N lies in exactly one of <g1>, <g2>", en_in_g1 != en_in_g2)

g_N = g1 if en_in_g1 else g2          # generator of the QNR-idempotent code
g_Q = g2 if en_in_g1 else g1
name_N = "g1" if g_N == g1 else "g2"
name_Q = "g1" if g_Q == g1 else "g2"

# E_N must GENERATE that code (idempotent generator), i.e. <E_N> has dim 12
ideal_EN = rref([pmod(pmulmod(E_N, 1 << i), X23P1) for i in range(P)])
check(f"<E_N> = <{name_N}> (E_N generates the QNR-idempotent QR code)",
      ideal_EN == cyclic_code(g_N), f"dim <E_N> = {len(ideal_EN)}")
print(f"QNR-idempotent QR code generator: {name_N} = {poly_str(g_N)}")

eQ_N = parity_extend_basis(cyclic_code(g_N))
eQ_Q = parity_extend_basis(cyclic_code(g_Q))

# ----------------------------------------------------------------------
# 5. Subspace equality tests
# ----------------------------------------------------------------------
eq_with_N = (C_paley == eQ_N)
eq_with_Q = (C_paley == eQ_Q)
check("C_paley = parity-extended QNR-idempotent QR code  <-- MAIN CLAIM",
      eq_with_N)
print(f"  (C_paley == extended <{name_Q}> [the QR-idempotent one]: {eq_with_Q})")

def negate_coords(v):
    w = v & (1 << INF)                 # inf fixed
    for j in range(P):
        if (v >> j) & 1:
            w |= 1 << ((-j) % P)
    return w

neg_eQ_N = rref([negate_coords(v) for v in eQ_N])
neg_eQ_Q = rref([negate_coords(v) for v in eQ_Q])
print(f"  negation j->-j maps extended <{name_N}> to extended <{name_Q}>: "
      f"{neg_eQ_N == eQ_Q}")
check("negation permutation swaps the two extended QR codes",
      neg_eQ_N == eQ_Q and neg_eQ_Q == eQ_N)
if not eq_with_N and eq_with_Q:
    print("  NOTE: Paley code equals the OTHER QR code; equal to the "
          "QNR-idempotent one only after j -> -j.")

# cross-check: the two extended QR codes are distinct subspaces
check("the two extended QR codes are distinct subspaces", eQ_N != eQ_Q)

# ----------------------------------------------------------------------
# 6. Intrinsic properties of C_paley (independent of equality test)
# ----------------------------------------------------------------------
wd = wdist(paley_words, NBITS)
print("weight distribution of C_paley:", dict(sorted(wd.items())))
expected_wd = {0: 1, 8: 759, 12: 2576, 16: 759, 24: 1}
check("weight distribution = {0:1, 8:759, 12:2576, 16:759, 24:1}",
      wd == expected_wd, f"got {dict(sorted(wd.items()))}")
check("minimum distance d = 8", min(k for k in wd if k > 0) == 8)
check("doubly-even (all weights = 0 mod 4)",
      all(k % 4 == 0 for k in wd))

# self-dual: dim 12 = 24/2 and C subset of C^perp (all pairwise inner
# products of codewords even) -- enough to check on a basis
ok_sd = len(C_paley) == 12 and all(
    bin(a & b).count('1') % 2 == 0 for a in C_paley for b in C_paley
)
check("self-dual (dim 12, all basis inner products = 0 over GF(2))", ok_sd)

# extra adversarial cross-check: extended QR weight dist must also match
check("extended QNR-idempotent QR code has the same weight distribution",
      wdist(span_words(eQ_N), NBITS) == expected_wd)

# ----------------------------------------------------------------------
# 7. Uniqueness citation (stated, not computable)
# ----------------------------------------------------------------------
print("""
UNIQUENESS CITATION
-------------------
The precise classical result: any binary LINEAR [24,12,8] code is
equivalent (up to coordinate permutation) to the extended binary Golay
code.  This is due to:

  V. Pless, "On the uniqueness of the Golay codes,"
  Journal of Combinatorial Theory 5 (1968), 215-228.
  (Proves uniqueness of the [23,12,7] and [24,12,8] binary linear codes.)

A Type II (doubly-even self-dual) [24,12] code with d=8 is in particular
a binary linear [24,12,8] code, so Pless (1968) already gives uniqueness;
no Type II hypothesis is needed.  The stronger NONLINEAR statement --
any binary (24, 2^12, 8) code, linear or not, is equivalent to the
extended Golay code -- is due to:

  S. L. Snover, "The uniqueness of the Nordstrom-Robinson and the Golay
  binary codes," Ph.D. thesis, Michigan State University, 1973;
  see also P. Delsarte and J.-M. Goethals, "Unrestricted codes with the
  Golay parameters are unique," Discrete Mathematics 12 (1975), 211-224.

(Within the Type II world: Pless and Sloane, JCTA 18 (1975) 313-335,
classify all nine Type II [24,12] codes; only the Golay code has d=8.)
""")

# ----------------------------------------------------------------------
print("=" * 70)
if FAILURES:
    print(f"RESULT: {len(FAILURES)} FAILURE(S) -- CLAIM HAS DISCREPANCIES:")
    for f in FAILURES:
        print("  -", f)
    sys.exit(1)
else:
    print("RESULT: ALL CHECKS PASSED -- claim CONFIRMED, refutation FAILED.")
    sys.exit(0)
