"""
vitali_holonomy_composition.py -- kind-pasteur-2026-03-13-S61

Can we COMPOSE multiple Vitali atoms? If T has two overlapping
Vitali-compatible subsets S1 and S2, what happens when we reverse both?

Questions:
1. If S1 and S2 are disjoint: do the effects commute?
2. If S1 and S2 overlap: does the composition create new structure?
3. Is there a "holonomy" — reversal around a closed loop of atoms
   that gives a net non-trivial transformation?
4. Can we build a "Vitali group" — the group generated by all Vitali reversals?

Also: the microscopic D<->S, D<->P, L<->S, L<->P transitions
must encode dc7. Let me find the exact formula.
"""

import numpy as np
from itertools import combinations
from collections import Counter, defaultdict

def bits_to_adj(bits, n):
    A = np.zeros((n, n), dtype=int)
    idx = 0
    for i in range(n):
        for j in range(i+1, n):
            if bits & (1 << idx):
                A[i][j] = 1
            else:
                A[j][i] = 1
            idx += 1
    return A

def lambda_graph(A, n):
    L = np.zeros((n, n), dtype=int)
    for u in range(n):
        for v in range(u+1, n):
            for w in range(n):
                if w == u or w == v:
                    continue
                if (A[u][v] and A[v][w] and A[w][u]) or (A[v][u] and A[u][w] and A[w][v]):
                    L[u][v] += 1
                    L[v][u] += 1
    return L

def reverse_subtournament(A, n, subset):
    B = A.copy()
    for i in subset:
        for j in subset:
            if i != j:
                B[i][j] = A[j][i]
    return B

def sub_scores(A, n, subset):
    k = len(subset)
    return tuple(sorted([sum(A[subset[i]][subset[j]] for j in range(k) if i != j) for i in range(k)]))

def count_directed_k_cycles(A, n, k):
    Ak = np.linalg.matrix_power(A, k)
    return int(np.trace(Ak)) // k

def find_all_vitali_subsets(A, n, L=None):
    """Find all 4-vertex subsets that form a Vitali atom."""
    if L is None:
        L = lambda_graph(A, n)
    vitali_subsets = []
    for subset in combinations(range(n), 4):
        ss = sub_scores(A, n, list(subset))
        if ss != (1, 1, 2, 2):
            continue
        B = reverse_subtournament(A, n, list(subset))
        if np.array_equal(L, lambda_graph(B, n)):
            vitali_subsets.append(subset)
    return vitali_subsets

# =====================================================
# PART 1: Multiple Vitali Atoms in One Tournament
# =====================================================
n = 7
total_bits = n * (n-1) // 2

print("=" * 60)
print("MULTIPLE VITALI ATOMS AND COMPOSITION")
print("=" * 60)

np.random.seed(42)
multi_atom_examples = []

for trial in range(3000):
    bits = np.random.randint(0, 1 << total_bits)
    A = bits_to_adj(bits, n)
    L = lambda_graph(A, n)

    vitali_subs = find_all_vitali_subsets(A, n, L)
    if len(vitali_subs) >= 2:
        multi_atom_examples.append({
            'bits': bits,
            'A': A.copy(),
            'L': L.copy(),
            'vitali_subsets': vitali_subs,
        })

    if len(multi_atom_examples) >= 50:
        break

print(f"Found {len(multi_atom_examples)} tournaments with >= 2 Vitali atoms")

# Distribution of atom count
atom_count_dist = Counter(len(ex['vitali_subsets']) for ex in multi_atom_examples)
print(f"Atom count distribution: {dict(sorted(atom_count_dist.items()))}")

# =====================================================
# PART 2: Commutativity and Overlap
# =====================================================
print(f"\n{'='*60}")
print("COMMUTATIVITY OF VITALI OPERATIONS")
print(f"{'='*60}")

for ex_idx in range(min(10, len(multi_atom_examples))):
    ex = multi_atom_examples[ex_idx]
    A = ex['A']
    vitali_subs = ex['vitali_subsets']

    # Check all pairs of atoms
    for i, S1 in enumerate(vitali_subs):
        for j, S2 in enumerate(vitali_subs):
            if j <= i:
                continue

            overlap = len(set(S1) & set(S2))

            # Apply S1 then S2
            B1 = reverse_subtournament(A, n, list(S1))
            B12 = reverse_subtournament(B1, n, list(S2))

            # Apply S2 then S1
            B2 = reverse_subtournament(A, n, list(S2))
            B21 = reverse_subtournament(B2, n, list(S1))

            commute = np.array_equal(B12, B21)

            c7_A = count_directed_k_cycles(A, n, 7)
            c7_12 = count_directed_k_cycles(B12, n, 7)
            c7_21 = count_directed_k_cycles(B21, n, 7)

            if ex_idx < 3 or not commute:
                print(f"  S1={S1}, S2={S2}, overlap={overlap}, commute={commute}, "
                      f"c7: A={c7_A}, S1S2={c7_12}, S2S1={c7_21}")

# =====================================================
# PART 3: Self-Inverse and Group Structure
# =====================================================
print(f"\n{'='*60}")
print("SELF-INVERSE PROPERTY")
print(f"{'='*60}")

# Each Vitali reversal is an involution: applying it twice returns the original
# But does B = reverse(A, S) also have S as a Vitali atom?
# i.e., is the reverse also lambda-preserving?

self_inverse_count = 0
reverse_also_vitali = 0

for ex in multi_atom_examples[:20]:
    A = ex['A']
    L = ex['L']
    for S in ex['vitali_subsets'][:3]:
        B = reverse_subtournament(A, n, list(S))

        # Check: is SS also (1,1,2,2) in B?
        ss_B = sub_scores(B, n, list(S))

        # Check: is reversal of S in B lambda-preserving?
        LB = lambda_graph(B, n)
        C = reverse_subtournament(B, n, list(S))  # should equal A

        self_inverse = np.array_equal(C, A)
        self_inverse_count += int(self_inverse)

        # Also check if S is Vitali in B
        ss_is_1122 = (ss_B == (1, 1, 2, 2))
        reverse_preserves = np.array_equal(LB, lambda_graph(C, n))
        if ss_is_1122 and reverse_preserves:
            reverse_also_vitali += 1

        if not self_inverse:
            print(f"  SELF-INVERSE FAILS! S={S}")

print(f"\nSelf-inverse: {self_inverse_count} / {self_inverse_count} (always true by construction)")
print(f"Reverse also Vitali: {reverse_also_vitali} (does B also have S as Vitali atom?)")

# Under reversal, (1,1,2,2) stays (1,1,2,2) (scores just permute).
# And the lambda graph is preserved (that's the definition).
# So B should ALWAYS have S as a Vitali atom!

# =====================================================
# PART 4: The "Vitali Orbit" — how many distinct tournaments?
# =====================================================
print(f"\n{'='*60}")
print("VITALI ORBIT SIZE")
print(f"{'='*60}")

for ex_idx in range(min(5, len(multi_atom_examples))):
    ex = multi_atom_examples[ex_idx]
    A = ex['A']
    vitali_subs = ex['vitali_subsets']

    # BFS to find the orbit
    seen = set()
    queue = [A.copy()]
    key = lambda M: tuple(M.flatten())
    seen.add(key(A))

    while queue:
        current = queue.pop(0)
        L_cur = lambda_graph(current, n)

        for S in combinations(range(n), 4):
            ss = sub_scores(current, n, list(S))
            if ss != (1, 1, 2, 2):
                continue
            B = reverse_subtournament(current, n, list(S))
            if not np.array_equal(L_cur, lambda_graph(B, n)):
                continue

            k = key(B)
            if k not in seen:
                seen.add(k)
                queue.append(B.copy())

    orbit_c7s = []
    for t_key in seen:
        M = np.array(t_key).reshape(n, n)
        orbit_c7s.append(count_directed_k_cycles(M, n, 7))

    print(f"  Example {ex_idx}: {len(vitali_subs)} atoms, orbit size = {len(seen)}, "
          f"c7 values = {sorted(Counter(orbit_c7s).items())}")

# =====================================================
# PART 5: The Exact dc7 via Microscopic Transitions
# =====================================================
print(f"\n{'='*60}")
print("dc7 FROM MICROSCOPIC WITNESS TRANSITIONS")
print(f"{'='*60}")

# We know dc7 depends on the full tournament structure.
# The microscopic witness transitions (D<->S, D<->P, L<->S, L<->P)
# rearrange how vertices witness 3-cycles.
#
# dc7 counts the change in Hamiltonian cycles.
# Hamiltonian cycles at n=7 = directed 7-cycles.
# tr(A^7)/7 counts these.
#
# Let's see if dc7 can be expressed in terms of the witness transition counts
# when broken down by the SPECIFIC (u,v,w) triples that change.

np.random.seed(42)
transition_features = []
dc7_values = []

for trial in range(5000):
    bits = np.random.randint(0, 1 << total_bits)
    A = bits_to_adj(bits, n)
    L = lambda_graph(A, n)

    for subset in combinations(range(n), 4):
        ss = sub_scores(A, n, list(subset))
        if ss != (1, 1, 2, 2):
            continue
        B = reverse_subtournament(A, n, list(subset))
        if not np.array_equal(L, lambda_graph(B, n)):
            continue

        S = set(subset)
        c7_A = count_directed_k_cycles(A, n, 7)
        c7_B = count_directed_k_cycles(B, n, 7)
        dc7 = c7_B - c7_A

        # For each SX pair (s,x), count the transitions by type
        # and also by which S-witness w changes
        sx_features = np.zeros(12)  # 4 S-vertices * 3 outside = 12 SX pairs
        pair_idx = 0

        for s in sorted(S):
            for x in sorted(set(range(n)) - S):
                # The dsig for this pair
                dsig = 0
                for w in sorted(S):
                    if w == s:
                        continue
                    sign_sw = int(A[s][w]) - int(A[w][s])
                    sign_xw = int(A[x][w]) - int(A[w][x])
                    dsig -= sign_sw * sign_xw

                sx_features[pair_idx] = dsig
                pair_idx += 1

        transition_features.append(sx_features)
        dc7_values.append(dc7)
        break

    if len(transition_features) >= 300:
        break

X = np.array(transition_features, dtype=float)
y = np.array(dc7_values, dtype=float)

from numpy.linalg import lstsq, matrix_rank

print(f"Feature matrix: {X.shape}, rank: {matrix_rank(X)}")
coeffs, _, _, _ = lstsq(X, y, rcond=None)
err = np.max(np.abs(X @ coeffs - y))
print(f"dc7 = linear(dsig per SX pair)?  Max error: {err:.6f}")

# The 12 SX pairs have dsig in {-3, -1, 1, 3} but we know all are +-1.
# These 12 binary (+-1) values have rank at most... let's see.
# They're structured: each column corresponds to one (s,x) pair.

# Can we reduce? The dsig values are structured:
# dsig(s,x) = -sum_{w in S, w!=s} sign(s->w)*sign(x->w)
# = -<sign_s, sign_x> where sign_s and sign_x are 3-vectors of +-1.

# There are 4 sign_s vectors (one per S-vertex) and 3 sign_x vectors (one per outside vertex).
# dsig is the negative dot product, a bilinear form.

# The sign_s vectors are constrained by the (1,1,2,2) structure:
# Two vectors have coordinate-sum +1 (winners), two have coordinate-sum -1 (losers).
# And they're determined by the internal tournament on S.

# The sign_x vectors are unconstrained (each outside vertex has its own S-projection).

# So the dsig matrix M[s,x] = -<sign_s, sign_x> has:
#   rank(M) <= min(rank(sign_s matrix), rank(sign_x matrix))
#   sign_s is 4×3 with rows in {-1,+1}^3. Max rank = 3.
#   sign_x is 3×3 with rows in {-1,+1}^3. Max rank = 3.
#   But we showed M has rank 1 or 2 (from earlier analysis).

# Try: dc7 = f(sign_x vectors) where sign_x is the "external coupling"
# The 3 sign_x vectors have 9 entries total (3 outside × 3 S-vertices)
X_signx = np.zeros((len(transition_features), 12))
for i in range(len(transition_features)):
    # Reconstruct the sign_x vectors from the dsig matrix
    # dsig_matrix[s, x] = transition_features[i]
    X_signx[i] = transition_features[i]

# Already done above. Let me try a different decomposition:
# dc7 = function of (sign_x1 . sign_x2, sign_x1 . sign_x3, sign_x2 . sign_x3)?
# i.e., the mutual information between outside vertices' S-projections

# Actually, let me try to find what COMBINATION of the 12 dsig values gives dc7.
# From earlier: the linear fit has error ~1.2. Not exact.
# But the EXACT formula needs the full tournament (including XX arcs).

# Let me include the XX arcs as features
np.random.seed(42)
all_features = []
all_dc7 = []

for trial in range(5000):
    bits = np.random.randint(0, 1 << total_bits)
    A = bits_to_adj(bits, n)
    L = lambda_graph(A, n)

    for subset in combinations(range(n), 4):
        ss = sub_scores(A, n, list(subset))
        if ss != (1, 1, 2, 2):
            continue
        B = reverse_subtournament(A, n, list(subset))
        if not np.array_equal(L, lambda_graph(B, n)):
            continue

        S = set(subset)
        S_sorted = sorted(S)
        outside = sorted(set(range(n)) - S)

        c7_A = count_directed_k_cycles(A, n, 7)
        c7_B = count_directed_k_cycles(B, n, 7)
        dc7 = c7_B - c7_A

        # Features: 12 SX dsig values + 6 XX arc directions + 12 SX arc directions
        feats = []

        # SX dsig values
        for s in S_sorted:
            for x in outside:
                dsig = 0
                for w in S_sorted:
                    if w == s:
                        continue
                    sign_sw = int(A[s][w]) - int(A[w][s])
                    sign_xw = int(A[x][w]) - int(A[w][x])
                    dsig -= sign_sw * sign_xw
                feats.append(dsig)

        # XX arcs (signed: +1 if x_i -> x_j, -1 otherwise)
        for i in range(3):
            for j in range(i+1, 3):
                feats.append(int(A[outside[i]][outside[j]]) * 2 - 1)

        # SX arcs (signed)
        for s in S_sorted:
            for x in outside:
                feats.append(int(A[s][x]) * 2 - 1)

        all_features.append(feats)
        all_dc7.append(dc7)
        break

    if len(all_features) >= 300:
        break

X_full = np.array(all_features, dtype=float)
y_full = np.array(all_dc7, dtype=float)

# Linear fit with all features
coeffs_full, _, _, _ = lstsq(X_full, y_full, rcond=None)
err_full = np.max(np.abs(X_full @ coeffs_full - y_full))
print(f"\nFull features (dsig + XX + SX arcs): shape={X_full.shape}, rank={matrix_rank(X_full)}")
print(f"Linear fit error: {err_full:.6f}")

# Try quadratic features
X_quad = []
for row in X_full:
    quad = list(row)
    # Add all pairwise products
    for i in range(len(row)):
        for j in range(i, len(row)):
            quad.append(row[i] * row[j])
    X_quad.append(quad)
X_quad = np.array(X_quad, dtype=float)

coeffs_quad, _, _, _ = lstsq(X_quad, y_full, rcond=None)
err_quad = np.max(np.abs(X_quad @ coeffs_quad - y_full))
print(f"Quadratic features: shape={X_quad.shape}, rank={matrix_rank(X_quad)}")
print(f"Quadratic fit error: {err_quad:.6f}")

if err_quad < 0.01:
    print("dc7 IS a quadratic function of (dsig, XX arcs, SX arcs)!")
    # Find the nonzero coefficients
    n_lin = X_full.shape[1]
    print(f"\nNonzero linear coefficients:")
    for i in range(n_lin):
        if abs(coeffs_quad[i]) > 0.01:
            if i < 12:
                s_idx = i // 3
                x_idx = i % 3
                print(f"  dsig[S{s_idx},X{x_idx}]: {coeffs_quad[i]:.4f}")
            elif i < 15:
                print(f"  XX arc {i-12}: {coeffs_quad[i]:.4f}")
            else:
                print(f"  SX arc {i-15}: {coeffs_quad[i]:.4f}")

    print(f"\nNonzero quadratic coefficients (top 20):")
    quad_idx = n_lin
    top_quads = []
    for i in range(n_lin):
        for j in range(i, n_lin):
            if abs(coeffs_quad[quad_idx]) > 0.01:
                top_quads.append((abs(coeffs_quad[quad_idx]), i, j, coeffs_quad[quad_idx]))
            quad_idx += 1
    top_quads.sort(reverse=True)
    for _, i, j, c in top_quads[:20]:
        print(f"  feature[{i}]*feature[{j}]: {c:.4f}")

# Try: dc7 = function of just XX arcs + SX arcs (without dsig)
X_arcs = np.array([feats[12:] for feats in all_features], dtype=float)
coeffs_arcs, _, _, _ = lstsq(X_arcs, y_full, rcond=None)
err_arcs = np.max(np.abs(X_arcs @ coeffs_arcs - y_full))
print(f"\nJust arcs (XX + SX): shape={X_arcs.shape}, rank={matrix_rank(X_arcs)}")
print(f"Linear fit error: {err_arcs:.6f}")

# Quadratic of just arcs
X_arcs_quad = []
for row in X_arcs:
    quad = list(row)
    for i in range(len(row)):
        for j in range(i, len(row)):
            quad.append(row[i] * row[j])
    X_arcs_quad.append(quad)
X_arcs_quad = np.array(X_arcs_quad, dtype=float)
coeffs_aq, _, _, _ = lstsq(X_arcs_quad, y_full, rcond=None)
err_aq = np.max(np.abs(X_arcs_quad @ coeffs_aq - y_full))
print(f"Quadratic of arcs: shape={X_arcs_quad.shape}, rank={matrix_rank(X_arcs_quad)}")
print(f"Quadratic fit error: {err_aq:.6f}")

print("\nDone.")
