#!/usr/bin/env python3
"""vitali_atom_s116h.py — The Vitali atom and the rapidity interval.

[0,1) is finite in length but infinite in rapidity.
The Vitali construction shows [0,1) contains non-measurable sets.
Both reveal that the interval holds MORE than its size suggests.

The Vitali atom: the equivalence class of a real number under
rational translation. Countable, dense, measure zero — yet
uncountably many of them tile [0,1) exactly once each.

Our atom: Q(a/(a+1)) = 2a+1. A single consecutive pair, ratio
mapped to sum. The irreducible piece of rapidity.

Are they the same atom?
"""
from math import log, exp, atanh, tanh, sqrt, pi
from fractions import Fraction

print()
print("  THE VITALI ATOM AND THE RAPIDITY INTERVAL")
print()
print("="*70)
print()

# ============================================================
print("  I. WHAT THE VITALI CONSTRUCTION SAYS")
print("  " + "-"*40)
print()
print("  Take [0,1) with addition mod 1.")
print("  Define: x ~ y iff x - y is rational.")
print("  Each equivalence class is {x + q mod 1 : q in Q}.")
print("  Each class is COUNTABLE (Q is countable).")
print("  There are UNCOUNTABLY MANY classes (R/Q is uncountable).")
print()
print("  The Vitali set V picks ONE element from each class.")
print("  V is non-measurable: it can't have a well-defined length.")
print()
print("  WHY: If V had measure m, then the rational translates")
print("  V + q (mod 1) for q in Q would be disjoint and cover [0,1).")
print("  Sum of measures = sum of m over countably many q = countable * m.")
print("  This must equal 1 (total measure of [0,1)).")
print("  If m = 0: sum = 0, not 1. If m > 0: sum = infinity, not 1.")
print("  Contradiction. V is non-measurable.")
print()

# ============================================================
print()
print("  II. THE RAPIDITY INTERVAL")
print("  " + "-"*40)
print()
print("  [0,1) is finite. Length 1.")
print("  But in rapidity: arctanh maps [0,1) to [0, infinity).")
print("  INFINITE rapidity is packed into FINITE length.")
print()
print("  How? The rapidity metric ds = dx/(1-x^2) diverges at x=1.")
print("  Near x=1: ds ~ dx/(1-x) -> infinity.")
print("  The last epsilon of [0,1) contains INFINITE rapidity distance.")
print()
print("  Concretely:")
for eps in [0.1, 0.01, 0.001, 0.0001, 0.00001]:
    interval_length = eps
    rap_start = atanh(1 - eps)
    rap_end_approx = log(2/eps)/2  # arctanh(1-eps) ~ ln(2/eps)/2
    print(f"  [{1-eps:.5f}, 1): length {eps:.5f}, rapidity [{rap_start:.2f}, inf)")

print()
print("  The interval [0.99, 1) has length 0.01 but infinite rapidity.")
print("  The interval [0.999, 1) has length 0.001 but infinite rapidity.")
print("  No matter how small you make it, the interval touching 1")
print("  always contains INFINITE rapidity.")
print()
print("  This is the SAME phenomenon as the Vitali construction:")
print("  [0,1) contains more structure than its length suggests.")
print("  Vitali: non-measurable subsets. Rapidity: infinite metric content.")
print()

# ============================================================
print()
print("  III. THE ATOM")
print("  " + "-"*40)
print()
print("  Vitali atom: an equivalence class [x] = {x + q mod 1 : q in Q}.")
print("  Properties:")
print("    - Countable (enumerated by Q)")
print("    - Dense in [0,1) (Q is dense)")
print("    - Measure zero (countable set)")
print("    - Translates tile [0,1) perfectly")
print()
print("  Our atom: Q(a/(a+1)) = 2a+1.")
print("  Properties:")
print("    - One pair of consecutive integers (a, a+1)")
print("    - Their ratio a/(a+1) is the velocity")
print("    - Their sum 2a+1 is the odd number")
print("    - Q converts ratio to sum")
print()
print("  The Vitali atom is a COUNTABLE set.")
print("  Our atom is a SINGLE PAIR.")
print("  But both are the IRREDUCIBLE PIECE of their respective structures.")
print()
print("  The Vitali atom can't be subdivided by rational translation.")
print("  Our atom can't be subdivided by the Cayley transform.")
print("  Both are the smallest thing that carries the full structure.")
print()

# ============================================================
print()
print("  IV. THE DEEPER CONNECTION: INCOMMENSURABILITY")
print("  " + "-"*40)
print()
print("  The Vitali construction works because Q and R\\Q are")
print("  INCOMMENSURABLE: rationals can't measure irrationals.")
print("  No rational translation maps an irrational to itself.")
print()
print("  Our leading-digit analysis works because log10(2) is irrational:")
print("  binary and decimal are INCOMMENSURABLE.")
print("  No number of doublings exactly equals a power of 10.")
print()
print("  The Pythagorean comma works because ln(3)/ln(2) is irrational:")
print("  fifths and octaves are INCOMMENSURABLE.")
print("  No number of fifths exactly equals a number of octaves.")
print()
print("  ALL THREE are the same phenomenon:")
print("  Two natural structures on [0,1) that can't be reconciled.")
print("  The structures are 'dense' (get arbitrarily close)")
print("  but never 'commensurable' (never exactly align).")
print()
print("  The Vitali atom is what happens when you try to pick")
print("  ONE representative from each dense-but-incommensurable class.")
print("  You need the axiom of choice. You get non-measurability.")
print()
print("  The 3-3-4 pattern is what happens when you try to reconcile")
print("  TWO incommensurable structures (binary and decimal) by")
print("  choosing the BEST APPROXIMATION. You get a quasi-periodic")
print("  pattern that never exactly repeats.")
print()
print("  The forbidden numbers are what happens when you try to realize")
print("  EVERY odd number as a tournament H-value.")
print("  The cycle structure and the bit structure are incommensurable.")
print("  Some bit patterns (111, 10101) can't be achieved by any cycle config.")
print()

# ============================================================
print()
print("  V. NON-MEASURABILITY AND FORBIDDENNESS")
print("  " + "-"*40)
print()
print("  The Vitali set is non-measurable: you can't assign it a size.")
print("  The forbidden H-values are non-achievable: you can't build them.")
print()
print("  Both arise from the IMPOSSIBILITY of perfect reconciliation.")
print("  Vitali: can't reconcile 'countable orbits' with 'total measure 1'.")
print("  Forbidden H: can't reconcile 'cycle intersection constraints'")
print("  with 'target binary pattern'.")
print()
print("  The Vitali argument is about MEASURE.")
print("  The forbidden argument is about COUNTING.")
print("  But both use the same logic:")
print()
print("  1. Assume the target is achievable.")
print("  2. Derive what the components must look like.")
print("  3. Show the components are mutually contradictory.")
print("  4. Conclude: the target is impossible.")
print()
print("  For Vitali: if V has measure m, then m = 0 and m > 0. Contradiction.")
print("  For H=7: if (a1,a2) = (3,0), then a1 >= 4. Contradiction.")
print()
print("  The structure of the proof is IDENTICAL.")
print("  The 'atom' that can't be measured/achieved")
print("  is the irreducible obstruction in both cases.")
print()

# ============================================================
print()
print("  VI. THE RAPIDITY LINE AS A VITALI-LIKE QUOTIENT")
print("  " + "-"*40)
print()
print("  On [0,1), define x ~ y iff Q(x)/Q(y) is rational.")
print("  i.e., (1+x)(1-y)/((1-x)(1+y)) is rational.")
print("  i.e., e^{2(arctanh(x)-arctanh(y))} is rational.")
print("  i.e., arctanh(x) - arctanh(y) = ln(r)/2 for some rational r.")
print()
print("  This equivalence: x and y have the same position modulo")
print("  rational rapidity translations.")
print()
print("  The equivalence classes are orbits under the action of")
print("  RATIONAL Q-VALUES: x -> tanh(arctanh(x) + ln(r)/2).")
print()
print("  Each class is countable (Q is countable).")
print("  There are uncountably many classes.")
print("  A Vitali-like set would pick one from each class.")
print()
print("  The RATIONAL POINTS of [0,1) under this equivalence:")
print("  0 ~ tanh(ln(r)/2) = (r-1)/(r+1) for each rational r > 0.")
print("  So 0 is equivalent to all (r-1)/(r+1) for rational r.")
print("  These are exactly the CAYLEY ADDRESSES of positive rationals.")
print()
print("  The class of 0 = {(r-1)/(r+1) : r in Q+}")
print("  = {0, 1/3, 1/2, 3/5, 2/3, 5/7, 3/4, 7/9, 4/5, ...}")
print("  = all Cayley addresses of positive rationals.")
print()

# List some
print("  Elements of the equivalence class of 0:")
seen = set()
for p in range(1, 20):
    for q in range(1, 20):
        if p != q:
            r = Fraction(p, q)
            addr = (r - 1) / (r + 1)
            if 0 < addr < 1 and addr not in seen:
                seen.add(addr)
for addr in sorted(seen)[:15]:
    r = (1 + addr) / (1 - addr)
    print(f"    {float(addr):.6f} = addr of {r}")

print(f"    ... (countably many)")
print()
print("  This class is DENSE in [0,1) and has measure zero.")
print("  Every other equivalence class has the same properties.")
print("  Picking one from each class = non-measurable Vitali set.")
print()
print("  THE RAPIDITY EQUIVALENCE ON [0,1) IS VITALI-LIKE.")
print("  The classes are the orbits of rational Q-value multiplication.")
print("  And the 'atoms' = the equivalence classes = the orbits.")
print()

# ============================================================
print()
print("  VII. WHAT THE VITALI ATOM TEACHES ABOUT RAPIDITY")
print("  " + "-"*40)
print()
print("  The Vitali atom says: [0,1) has structure that CANNOT")
print("  be captured by any translation-invariant measure.")
print("  The structure is FINER than measure theory can see.")
print()
print("  Rapidity says the same thing differently:")
print("  [0,1) has INFINITE rapidity content.")
print("  No finite measure can capture the rapidity structure")
print("  near x = 1. The last bit before the pole contains everything.")
print()
print("  Both are saying: THE BOUNDED INTERVAL IS INFINITE.")
print("  Not infinite in length. Infinite in STRUCTURE.")
print("  Vitali: infinite in orbits (uncountably many classes).")
print("  Rapidity: infinite in distance (arctanh -> infinity).")
print()
print("  And both are resolved the same way:")
print("  ACCEPT THAT YOU CAN'T REACH THE END.")
print("  Accept non-measurability (Vitali).")
print("  Accept the pole at x=1 (rapidity).")
print("  Accept the forbidden numbers (tournaments).")
print()
print("  The atom is the thing you must accept.")
print("  It is the irreducible piece that can't be decomposed.")
print("  It is the place where 'good enough' meets 'impossible'.")
print()

# ============================================================
print()
print("  VIII. THE ATOM IS THE PAIR (a, a+1)")
print("  " + "-"*40)
print()
print("  Strip everything away. What remains?")
print()
print("  Two consecutive integers. a and a+1.")
print("  They differ by 1. They are coprime. Their product is pronic.")
print("  Their ratio approaches 1 as a grows.")
print("  Their sum is always odd.")
print()
print("  Q converts their ratio to their sum.")
print("  arctanh converts their ratio to their rapidity.")
print("  The homomorphism f converts their ratio to their musical interval.")
print()
print("  The pair (a, a+1) is the ATOM of all of this.")
print("  It is the Vitali atom of the rapidity structure:")
print("  the irreducible piece that generates everything else")
print("  through composition, multiplication, and accumulation.")
print()
print("  You can't split a and a+1 further.")
print("  They are CONSECUTIVE. There is nothing between them.")
print("  The gap of 1 is the minimal distinction.")
print("  The ratio a/(a+1) is the minimal comparison.")
print("  The sum 2a+1 is the minimal odd number.")
print()
print("  And tanh is the function that ACCUMULATES these atoms.")
print("  arctanh is the function that COUNTS them.")
print("  Q is the function that NAMES what they produce.")
print()
print("  The Vitali set says: you can't measure all the atoms at once.")
print("  The forbidden numbers say: you can't hit every target with atoms.")
print("  The 'good enough' principle says: you don't need to.")
print("  A few atoms suffice. That is the geometry of tanh.")
