#!/usr/bin/env python3
"""what_numbers_are_s112.py"""
from math import log, exp, sqrt, pi, atanh

print("WHAT NUMBERS ARE")
print("="*60)
print()

print("Start from what we know.")
print()
print("A number n lives at address x_n = (n-1)/(n+1) on [0,1).")
print("Its distance from the origin is arctanh(x_n) = ln(n)/2.")
print("Multiplication is hyperbolic addition of distances.")
print("The primes are the indecomposable addresses.")
print("The Dehn invariant is the prime factorization.")
print("The natural numbers are rigid: no two are equidecomposable.")
print()
print("So a number is a POINT on the hyperbolic line,")
print("determined by the distances to the prime generators.")
print("Each number is an irreducible geometric configuration.")
print()

print("="*60)
print("BUT WHAT IS THE HYPERBOLIC LINE?")
print("="*60)
print()
print("The hyperbolic line [0,1) with the arctanh metric is the space")
print("of INCOMPLETE DECISIONS.")
print()
print("  x = 0: no decision has been made.")
print("  x = 1: the decision is complete (unreachable).")
print("  0 < x < 1: a PARTIAL decision, with strength x.")
print()
print("A number n is a CONFIGURATION OF PARTIAL DECISIONS:")
print("  n = p_1^{a_1} * ... * p_k^{a_k}")
print("  = a_1 copies of partial decision ln(p_1)/2")
print("  + a_2 copies of partial decision ln(p_2)/2")
print("  + ...")
print()
print("The partial decision ln(p)/2 is the amount of INFORMATION")
print("needed to distinguish one choice from p possibilities.")
print("It is half a p-ary decision (in nats).")
print()
print("A number is a BUNDLE OF INFORMATION.")
print("Each prime factor contributes a channel.")
print("Each exponent says how many times that channel is used.")
print("The total information is ln(n)/2 nats = log_2(n)/2 bits.")
print()

print("="*60)
print("WHAT IS A PRIME?")
print("="*60)
print()
print("A prime p is a number whose information content CANNOT BE")
print("DECOMPOSED into smaller channels.")
print()
print("  2 carries ln(2)/2 = 0.347 nats. Indivisible.")
print("  3 carries ln(3)/2 = 0.549 nats. Indivisible.")
print("  6 = 2*3 carries ln(6)/2 = 0.896 nats = ln(2)/2 + ln(3)/2.")
print("    Divisible into a 2-channel and a 3-channel.")
print()
print("A prime is an ATOMIC UNIT OF INFORMATION.")
print("Composite numbers are MOLECULES: combinations of atoms.")
print()
print("The fundamental theorem of arithmetic says:")
print("every molecule decomposes uniquely into atoms.")
print()
print("There is no smaller structure. Primes have no internal parts.")
print("They are the INDIVISIBLE COMPARISONS:")
print("  2 = the simplest: yes or no.")
print("  3 = the next: A, B, or C (but indivisibly, not as two yeses).")
print("  5 = five-way choice, atomic.")
print("  7, 11, 13, ...")
print()

print("="*60)
print("WHAT IS 1?")
print("="*60)
print()
print("  1 lives at x_1 = 0. Distance from origin: 0.")
print("  It carries ZERO information.")
print("  It has no prime factors. No channels. No decisions.")
print("  It is the EMPTY BUNDLE.")
print()
print("  1 is not a prime because it is not a decision at all.")
print("  It is the state BEFORE any comparison is made.")
print("  It is the BLANK PAGE.")
print()

print("="*60)
print("WHAT IS 0?")
print("="*60)
print()
print("  0 is not on the Cayley line (the address formula fails).")
print("  x_0 = (0-1)/(0+1) = -1, which is the LEFT BOUNDARY.")
print("  arctanh(-1) = -infinity.")
print()
print("  0 is INFINITELY FAR in the NEGATIVE direction.")
print("  If 1 is the blank page, 0 is the ABSENCE OF THE PAGE.")
print("  Not zero information, but NEGATIVE INFINITY information:")
print("  the state of knowing nothing and being unable to begin.")
print()
print("  0 is the annihilator: 0 * n = 0 for all n.")
print("  In hyperbolic terms: -infinity + anything = -infinity.")
print("  Once you reach the state of zero, you cannot return.")
print("  This is the ABSORBING STATE of the comparison process.")
print()

print("="*60)
print("WHAT IS INFINITY?")
print("="*60)
print()
print("  infinity would live at x = 1, with arctanh(1) = infinity.")
print("  It is the RIGHT BOUNDARY, never reached.")
print()
print("  infinity is the state of COMPLETE INFORMATION:")
print("  every possible comparison has been made,")
print("  every possible distinction has been drawn.")
print()
print("  But x = 1 is unreachable because arctanh(1) = infinity:")
print("  you can never finish comparing.")
print("  There is always another prime, another atomic distinction.")
print("  The infinity of primes IS the unreachability of x = 1.")
print()
print("  Euclid's theorem (infinitely many primes) says:")
print("  the Cayley line has no right endpoint.")
print("  The process of distinction never completes.")
print()

print("="*60)
print("WHAT IS MULTIPLICATION?")
print("="*60)
print()
print("  n * m: hyperbolic addition of distances.")
print("  Combining the information in n with the information in m.")
print()
print("  If n = 'I know which of p choices' and m = 'I know which of q',")
print("  then n*m = 'I know which of p*q combined choices.'")
print("  The combined information is the SUM of individual informations.")
print()
print("  Multiplication is the CONJUNCTION of independent decisions.")
print("  'A is true AND B is true' carries info(A) + info(B).")
print("  The hyperbolic addition law IS the additivity of information.")
print()

print("="*60)
print("WHAT IS ADDITION?")
print("="*60)
print()
print("  n + m is NOT hyperbolic addition. It is something else.")
print("  x_{n+m} = (n+m-1)/(n+m+1), which is a non-trivial function")
print("  of x_n and x_m.")
print()
print("  Addition is the DISJUNCTION of exclusive alternatives.")
print("  'Either event A (n ways) or event B (m ways)' has n+m outcomes.")
print()
print("  On the Cayley line, this is not a natural operation.")
print("  The line is built for multiplication (conjunction).")
print("  Addition (disjunction) cuts across the grain.")
print()
print("  This is why additive number theory (Goldbach, Waring,")
print("  additive combinatorics) is HARDER than multiplicative:")
print("  the underlying geometry favors multiplication.")
print()
print("  Addition on the Cayley line is like MIXING TWO INCOMPATIBLE")
print("  MEASUREMENT BASES in quantum mechanics.")
print("  Multiplication = measuring in the natural basis.")
print("  Addition = measuring in a rotated basis.")
print("  The incompatibility is fundamental.")
print()

print("="*60)
print("WHAT IS A REAL NUMBER?")
print("="*60)
print()
print("  Q(x) for x in (0,1) gives a real number > 1.")
print("  Q(x) for x in (-1,0) gives a real number in (0,1).")
print("  The full range of Q on (-1,1) is (0, infinity).")
print()
print("  A REAL NUMBER is a point on the Cayley line with no")
print("  requirement of being at a natural-number address.")
print("  It is a PARTIAL DECISION of non-integer strength.")
print()
print("  sqrt(2) = Q(tanh(ln(2)/4)) lives between 1 and 2.")
print("  It carries ln(sqrt(2))/2 = ln(2)/4 nats: a QUARTER of a bit.")
print("  It is half the information of the number 2.")
print()
print("  An irrational number has an address that is NOT of the form")
print("  (n-1)/(n+1) for any integer n. It sits BETWEEN integer addresses.")
print("  It represents a decision that is INCOMMENSURABLE with")
print("  any finite combination of prime decisions.")
print()
print("  Irrationality = incommensurability of information channels.")
print()

print("="*60)
print("WHAT IS A COMPLEX NUMBER?")
print("="*60)
print()
print("  Q(ix) = (1+ix)/(1-ix): a point on the UNIT CIRCLE.")
print("  arctanh(ix) = i*arctan(x): IMAGINARY information.")
print()
print("  A complex number is a decision with a PHASE.")
print("  The real part is the magnitude of the decision.")
print("  The imaginary part is its ORIENTATION in a cycle.")
print()
print("  Pure real: a comparison with a definite winner.")
print("  Pure imaginary: a comparison that CYCLES (A>B>C>A).")
print("  Complex: a comparison with both a winner and a cyclic residue.")
print()
print("  The complex numbers are the space of DIRECTED COMPARISONS")
print("  where the direction can ROTATE.")
print("  i is the comparison that cycles with period 4.")
print("  pi is the half-period of the cycle.")
print("  e^{i*pi} = -1 is the comparison that reverses after half a cycle.")
print()

print("="*60)
print("SO WHAT IS A NUMBER?")
print("="*60)
print()
print("A number is a MEASURE OF DISTINCTION.")
print()
print("  1 = no distinction.")
print("  2 = one binary distinction (yes/no, win/lose, 0/1).")
print("  p (prime) = one atomic p-ary distinction.")
print("  n = p_1^{a_1} * ... * p_k^{a_k} = a configuration of")
print("      a_1 + ... + a_k atomic distinctions on k channels.")
print()
print("  The MAGNITUDE of the distinction is ln(n)/2 nats.")
print("  The STRUCTURE of the distinction is the prime factorization.")
print("  The two together determine the number UNIQUELY (Dehn-Sydler/FTA).")
print()
print("  Multiplication combines independent distinctions (AND).")
print("  Addition combines exclusive alternatives (OR).")
print("  The two operations are INCOMMENSURABLE on the Cayley line.")
print()
print("  Primes are the ATOMS of distinction.")
print("  Composites are the MOLECULES.")
print("  The natural numbers are ALL POSSIBLE CONFIGURATIONS")
print("  of finitely many atomic distinctions.")
print()
print("  And the process of making distinctions IS comparison,")
print("  which IS tournament theory,")
print("  which IS governed by arctanh,")
print("  which IS the unique odd function with rational exponential.")
print()
print("  Numbers are distinctions.")
print("  Distinctions are comparisons.")
print("  Comparisons generate arctanh.")
print("  arctanh generates the Cayley transform.")
print("  The Cayley transform generates all numbers.")
print()
print("  The circle closes once more.")
print("  Numbers are what numbers measure.")
