import TournamentH7.GMC2ConstantTermRelations

/-!
# DvdK from a monomial certificate: eliminating DvdK on the coincident-channel stratum

The unique-channel bypass (`GMC2DvdKUniqueChannel`) covers every support with a single balanced
channel at some mass.  The residual — the coincident-channel / symmetric supports — has ≥2 balanced
channels at *every* mass, so no single power certifies non-vanishing coefficient-independently.  But
DvdK can still be discharged *elementarily* there by a **monomial certificate**:

> if a nonzero monomial `∏ Xᵢ^{eᵢ}` lies in the ideal generated by finitely many constant-term
> relations `CT(f^m)` (`m ∈ M`), then on the coefficient torus (all `cᵢ ≠ 0`) some `CT(f^m)` is
> nonzero — because the monomial evaluates to `∏ cᵢ^{eᵢ} ≠ 0`.

Each `CT(f^m)` is homogeneous of degree `m` in the coefficients, so "the ideal contains a monomial"
is a finite graded linear-algebra question, solved per support by exact rational elimination
(`04-computation/dvdk_monomial_certificate_residual_boxeph_S231.py`).  For the 14 residual straddling
supports of size 3–4 in `[-4,4]` a certificate exists at degree ≤ 6 — so DvdK is discharged for the
*entire* class, no Galois orbit-product (THM-2067) needed.  This module is the reusable engine:
supply the certifying identity, get the DvdK1 conclusion.
-/

open MvPolynomial Finset

namespace GMC2DvdKMonomialCertificate

/-- **DvdK1 from a monomial certificate.**  If the monomial `∏ Xᵢ^{eᵢ}` equals a cofactor
combination `∑_{m∈M} gₘ · CT(f^m)` of constant-term relations, then for any nonzero coefficient
vector `c` some `CT(f^m)` (`m ∈ M`) is nonzero.  No positivity, no uniqueness, no Galois input. -/
theorem exists_ct_ne_zero_of_monomialCertificate
    {ι K : Type*} [Fintype ι] [DecidableEq ι] [Field K] [Algebra ℚ K]
    (q : ι → ℤ) (c : ι → K) (hc : ∀ i, c i ≠ 0)
    (M : Finset ℕ) (e : ι → ℕ) (g : ℕ → MvPolynomial ι ℚ)
    (hcert : (∏ i, (X i : MvPolynomial ι ℚ) ^ e i)
        = ∑ m ∈ M, g m * GMC2ConstantTermRelations.constantTermRelation q m) :
    ∃ m ∈ M, MvPolynomial.aeval c
        (GMC2ConstantTermRelations.constantTermRelation q m) ≠ 0 := by
  by_contra h
  have h' : ∀ m ∈ M, MvPolynomial.aeval c
      (GMC2ConstantTermRelations.constantTermRelation q m) = 0 :=
    fun m hm => not_not.mp (fun hne => h ⟨m, hm, hne⟩)
  have hmono : MvPolynomial.aeval c (∏ i, (X i : MvPolynomial ι ℚ) ^ e i)
      = ∏ i, c i ^ e i := by
    rw [map_prod]
    exact Finset.prod_congr rfl (fun i _ => by rw [map_pow, aeval_X])
  have hz : MvPolynomial.aeval c (∏ i, (X i : MvPolynomial ι ℚ) ^ e i) = 0 := by
    rw [hcert, map_sum]
    exact Finset.sum_eq_zero (fun m hm => by rw [map_mul, h' m hm, mul_zero])
  rw [hmono] at hz
  exact (Finset.prod_ne_zero_iff.mpr (fun i _ => pow_ne_zero _ (hc i))) hz

/-- The DvdK1 existential shape (`∃ m ≥ 1, CT(f^m) ≠ 0`) from a monomial certificate whose masses are
all positive — the input consumed by the GMC(2) spine, discharged with no external axiom. -/
theorem dvdk1_of_monomialCertificate
    {ι K : Type*} [Fintype ι] [DecidableEq ι] [Field K] [Algebra ℚ K]
    (q : ι → ℤ) (c : ι → K) (hc : ∀ i, c i ≠ 0)
    (M : Finset ℕ) (hM1 : ∀ m ∈ M, 1 ≤ m) (e : ι → ℕ) (g : ℕ → MvPolynomial ι ℚ)
    (hcert : (∏ i, (X i : MvPolynomial ι ℚ) ^ e i)
        = ∑ m ∈ M, g m * GMC2ConstantTermRelations.constantTermRelation q m) :
    ∃ m : ℕ, 1 ≤ m ∧ MvPolynomial.aeval c
        (GMC2ConstantTermRelations.constantTermRelation q m) ≠ 0 := by
  obtain ⟨m, hm, hne⟩ := exists_ct_ne_zero_of_monomialCertificate q c hc M e g hcert
  exact ⟨m, hM1 m hm, hne⟩

end GMC2DvdKMonomialCertificate

#print axioms GMC2DvdKMonomialCertificate.exists_ct_ne_zero_of_monomialCertificate
#print axioms GMC2DvdKMonomialCertificate.dvdk1_of_monomialCertificate
