/-
  TournamentH7.LRCAnchor12Certs — positivity anchors for the 13 twelve-element families (hk12 dispatch)
  (mac-mini-2026-07-09-S65 cont.25, MACHINE-GENERATED by
  lrc14_mpcert_codegen_macmini_S65cont25.py from the cont.16 engine).
-/
import Mathlib
import TournamentH7.LRCMomentCitation

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace MPCert

open DenseCovers MeasureTheory MomentFloorRepair

theorem anchor_s12_missing_1 :
    ((1 : ℝ)/28) ≤ (slowμ (safeSet ([2,3,4,5,6,7,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([2,3,4,5,6,7,8,9,10,11,12,13] : List ℤ) [((1/28 : ℝ), (1/14 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/28 : ℝ), (1/14 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/28 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_2 :
    ((11 : ℝ)/728) ≤ (slowμ (safeSet ([1,3,4,5,6,7,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,3,4,5,6,7,8,9,10,11,12,13] : List ℤ) [((85/182 : ℝ), (27/56 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((85/182 : ℝ), (27/56 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (11/728 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_3 :
    ((1 : ℝ)/84) ≤ (slowμ (safeSet ([1,2,4,5,6,7,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,4,5,6,7,8,9,10,11,12,13] : List ℤ) [((29/84 : ℝ), (5/14 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((29/84 : ℝ), (5/14 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/84 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_4 :
    ((9 : ℝ)/1232) ≤ (slowμ (safeSet ([1,2,3,5,6,7,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,5,6,7,8,9,10,11,12,13] : List ℤ) [((29/112 : ℝ), (41/154 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((29/112 : ℝ), (41/154 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (9/1232 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_5 :
    ((1 : ℝ)/140) ≤ (slowμ (safeSet ([1,2,3,4,6,7,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,6,7,8,9,10,11,12,13] : List ℤ) [((29/140 : ℝ), (3/14 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((29/140 : ℝ), (3/14 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/140 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_6 :
    ((5 : ℝ)/1848) ≤ (slowμ (safeSet ([1,2,3,4,5,7,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,7,8,9,10,11,12,13] : List ℤ) [((29/168 : ℝ), (27/154 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((29/168 : ℝ), (27/154 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (5/1848 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_7 :
    ((3 : ℝ)/208) ≤ (slowμ (safeSet ([1,2,3,4,5,6,8,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,8,9,10,11,12,13] : List ℤ) [((15/112 : ℝ), (27/182 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((15/112 : ℝ), (27/182 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (3/208 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_8 :
    ((2 : ℝ)/147) ≤ (slowμ (safeSet ([1,2,3,4,5,6,7,9,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,7,9,10,11,12,13] : List ℤ) [((5/42 : ℝ), (13/98 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((5/42 : ℝ), (13/98 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (2/147 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_9 :
    ((1 : ℝ)/91) ≤ (slowμ (safeSet ([1,2,3,4,5,6,7,8,10,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,7,8,10,11,12,13] : List ℤ) [((3/14 : ℝ), (41/182 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((3/14 : ℝ), (41/182 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/91 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_10 :
    ((4 : ℝ)/637) ≤ (slowμ (safeSet ([1,2,3,4,5,6,7,8,9,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,7,8,9,11,12,13] : List ℤ) [((29/98 : ℝ), (55/182 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((29/98 : ℝ), (55/182 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (4/637 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_11 :
    ((1 : ℝ)/112) ≤ (slowμ (safeSet ([1,2,3,4,5,6,7,8,9,10,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,7,8,9,10,12,13] : List ℤ) [((5/14 : ℝ), (41/112 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((5/14 : ℝ), (41/112 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/112 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_12 :
    ((1 : ℝ)/245) ≤ (slowμ (safeSet ([1,2,3,4,5,6,7,8,9,10,11,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,7,8,9,10,11,13] : List ℤ) [((29/70 : ℝ), (41/98 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((29/70 : ℝ), (41/98 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/245 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem anchor_s12_missing_13 :
    ((1 : ℝ)/168) ≤ (slowμ (safeSet ([1,2,3,4,5,6,7,8,9,10,11,12] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1,2,3,4,5,6,7,8,9,10,11,12] : List ℤ) [((1/14 : ℝ), (13/168 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/14 : ℝ), (13/168 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (1/168 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith
end MPCert
end LRC14
end LonelyRunner
