/-
  TournamentH7.LRCSafeCertSize4_c9 — hB certificate table, |S| = 4
  (mac-mini-2026-07-09-S65 cont.22, MACHINE-GENERATED by
  lrc14_safecert_codegen_macmini_S65cont22.py from the cont.16 engine).

  4 families, 116 components; each theorem floors
  `(slowμ (safeSet S)).toReal` by `capRat 9 = 1979/4004` (the exact per-|S| minimum,
  attained; every certificate is a rational band check).
-/
import Mathlib
import TournamentH7.LRCMomentFloorRepair

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace SafeCert

open DenseCovers MeasureTheory MomentFloorRepair

theorem safe_s4_9_10_11_12 :
    (((1979 : ℝ)/4004)) ≤ (slowμ (safeSet ([9,10,11,12] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([9,10,11,12] : List ℤ) [((1/126 : ℝ), (13/168 : ℝ)), ((5/42 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (3/14 : ℝ)), ((29/126 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (41/140 : ℝ)), ((43/140 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (55/126 : ℝ)), ((71/154 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (83/154 : ℝ)), ((71/126 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (97/140 : ℝ)), ((99/140 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (97/126 : ℝ)), ((11/14 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (37/42 : ℝ)), ((155/168 : ℝ), (125/126 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/126 : ℝ), (13/168 : ℝ)), ((5/42 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (3/14 : ℝ)), ((29/126 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (41/140 : ℝ)), ((43/140 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (55/126 : ℝ)), ((71/154 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (83/154 : ℝ)), ((71/126 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (97/140 : ℝ)), ((99/140 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (97/126 : ℝ)), ((11/14 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (37/42 : ℝ)), ((155/168 : ℝ), (125/126 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (97/180 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s4_9_10_11_13 :
    (((1979 : ℝ)/4004)) ≤ (slowμ (safeSet ([9,10,11,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([9,10,11,13] : List ℤ) [((1/126 : ℝ), (1/14 : ℝ)), ((15/182 : ℝ), (13/154 : ℝ)), ((5/42 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (3/14 : ℝ)), ((43/182 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (41/140 : ℝ)), ((57/182 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (55/126 : ℝ)), ((85/182 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (97/182 : ℝ)), ((71/126 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (125/182 : ℝ)), ((99/140 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (139/182 : ℝ)), ((11/14 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (37/42 : ℝ)), ((141/154 : ℝ), (167/182 : ℝ)), ((13/14 : ℝ), (125/126 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨12, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/126 : ℝ), (1/14 : ℝ)), ((15/182 : ℝ), (13/154 : ℝ)), ((5/42 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (3/14 : ℝ)), ((43/182 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (41/140 : ℝ)), ((57/182 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (55/126 : ℝ)), ((85/182 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (97/182 : ℝ)), ((71/126 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (125/182 : ℝ)), ((99/140 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (139/182 : ℝ)), ((11/14 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (37/42 : ℝ)), ((141/154 : ℝ), (167/182 : ℝ)), ((13/14 : ℝ), (125/126 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (23521/45045 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s4_9_10_12_13 :
    (((1979 : ℝ)/4004)) ≤ (slowμ (safeSet ([9,10,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([9,10,12,13] : List ℤ) [((1/126 : ℝ), (1/14 : ℝ)), ((5/56 : ℝ), (13/140 : ℝ)), ((5/42 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (3/14 : ℝ)), ((43/182 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (41/140 : ℝ)), ((57/182 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (55/126 : ℝ)), ((19/42 : ℝ), (83/182 : ℝ)), ((85/182 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (97/182 : ℝ)), ((99/182 : ℝ), (23/42 : ℝ)), ((71/126 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (125/182 : ℝ)), ((99/140 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (139/182 : ℝ)), ((11/14 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (37/42 : ℝ)), ((127/140 : ℝ), (51/56 : ℝ)), ((13/14 : ℝ), (125/126 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
        · exact ⟨12, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/126 : ℝ), (1/14 : ℝ)), ((5/56 : ℝ), (13/140 : ℝ)), ((5/42 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (3/14 : ℝ)), ((43/182 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (41/140 : ℝ)), ((57/182 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (55/126 : ℝ)), ((19/42 : ℝ), (83/182 : ℝ)), ((85/182 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (97/182 : ℝ)), ((99/182 : ℝ), (23/42 : ℝ)), ((71/126 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (125/182 : ℝ)), ((99/140 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (139/182 : ℝ)), ((11/14 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (37/42 : ℝ)), ((127/140 : ℝ), (51/56 : ℝ)), ((13/14 : ℝ), (125/126 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (8831/16380 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s4_9_11_12_13 :
    (((1979 : ℝ)/4004)) ≤ (slowμ (safeSet ([9,11,12,13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([9,11,12,13] : List ℤ) [((1/126 : ℝ), (1/14 : ℝ)), ((15/154 : ℝ), (13/126 : ℝ)), ((5/42 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (3/14 : ℝ)), ((43/182 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (55/182 : ℝ)), ((57/182 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (55/126 : ℝ)), ((85/182 : ℝ), (83/168 : ℝ)), ((85/168 : ℝ), (97/182 : ℝ)), ((71/126 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (125/182 : ℝ)), ((127/182 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (139/182 : ℝ)), ((11/14 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (37/42 : ℝ)), ((113/126 : ℝ), (139/154 : ℝ)), ((13/14 : ℝ), (125/126 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨9, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
        · exact ⟨10, by norm_num, by norm_num⟩
        · exact ⟨11, by norm_num, by norm_num⟩
        · exact ⟨12, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/126 : ℝ), (1/14 : ℝ)), ((15/154 : ℝ), (13/126 : ℝ)), ((5/42 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (3/14 : ℝ)), ((43/182 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (55/182 : ℝ)), ((57/182 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (55/126 : ℝ)), ((85/182 : ℝ), (83/168 : ℝ)), ((85/168 : ℝ), (97/182 : ℝ)), ((71/126 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (125/182 : ℝ)), ((127/182 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (139/182 : ℝ)), ((11/14 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (37/42 : ℝ)), ((113/126 : ℝ), (139/154 : ℝ)), ((13/14 : ℝ), (125/126 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (19333/36036 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

end SafeCert
end LRC14
end LonelyRunner
