/-
  TournamentH7.LRCSafeCertSize1 — hB certificate table, |S| = 1
  (mac-mini-2026-07-09-S65 cont.22, MACHINE-GENERATED by
  lrc14_safecert_codegen_macmini_S65cont22.py from the cont.16 engine).

  13 families, 91 components; each theorem floors
  `(slowμ (safeSet S)).toReal` by `capRat 12 = 6/7` (the exact per-|S| minimum,
  attained; every certificate is a rational band check).
-/
import Mathlib
import TournamentH7.LRCMomentFloorRepair

set_option maxHeartbeats 3200000

namespace LonelyRunner
namespace LRC14
namespace SafeCert

open DenseCovers MeasureTheory MomentFloorRepair

theorem safe_s1_1 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([1] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([1] : List ℤ) [((1/14 : ℝ), (13/14 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/14 : ℝ), (13/14 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_2 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([2] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([2] : List ℤ) [((1/28 : ℝ), (13/28 : ℝ)), ((15/28 : ℝ), (27/28 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/28 : ℝ), (13/28 : ℝ)), ((15/28 : ℝ), (27/28 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_3 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([3] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([3] : List ℤ) [((1/42 : ℝ), (13/42 : ℝ)), ((5/14 : ℝ), (9/14 : ℝ)), ((29/42 : ℝ), (41/42 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/42 : ℝ), (13/42 : ℝ)), ((5/14 : ℝ), (9/14 : ℝ)), ((29/42 : ℝ), (41/42 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_4 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([4] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([4] : List ℤ) [((1/56 : ℝ), (13/56 : ℝ)), ((15/56 : ℝ), (27/56 : ℝ)), ((29/56 : ℝ), (41/56 : ℝ)), ((43/56 : ℝ), (55/56 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/56 : ℝ), (13/56 : ℝ)), ((15/56 : ℝ), (27/56 : ℝ)), ((29/56 : ℝ), (41/56 : ℝ)), ((43/56 : ℝ), (55/56 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_5 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([5] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([5] : List ℤ) [((1/70 : ℝ), (13/70 : ℝ)), ((3/14 : ℝ), (27/70 : ℝ)), ((29/70 : ℝ), (41/70 : ℝ)), ((43/70 : ℝ), (11/14 : ℝ)), ((57/70 : ℝ), (69/70 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/70 : ℝ), (13/70 : ℝ)), ((3/14 : ℝ), (27/70 : ℝ)), ((29/70 : ℝ), (41/70 : ℝ)), ((43/70 : ℝ), (11/14 : ℝ)), ((57/70 : ℝ), (69/70 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_6 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([6] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([6] : List ℤ) [((1/84 : ℝ), (13/84 : ℝ)), ((5/28 : ℝ), (9/28 : ℝ)), ((29/84 : ℝ), (41/84 : ℝ)), ((43/84 : ℝ), (55/84 : ℝ)), ((19/28 : ℝ), (23/28 : ℝ)), ((71/84 : ℝ), (83/84 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/84 : ℝ), (13/84 : ℝ)), ((5/28 : ℝ), (9/28 : ℝ)), ((29/84 : ℝ), (41/84 : ℝ)), ((43/84 : ℝ), (55/84 : ℝ)), ((19/28 : ℝ), (23/28 : ℝ)), ((71/84 : ℝ), (83/84 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_7 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([7] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([7] : List ℤ) [((1/98 : ℝ), (13/98 : ℝ)), ((15/98 : ℝ), (27/98 : ℝ)), ((29/98 : ℝ), (41/98 : ℝ)), ((43/98 : ℝ), (55/98 : ℝ)), ((57/98 : ℝ), (69/98 : ℝ)), ((71/98 : ℝ), (83/98 : ℝ)), ((85/98 : ℝ), (97/98 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/98 : ℝ), (13/98 : ℝ)), ((15/98 : ℝ), (27/98 : ℝ)), ((29/98 : ℝ), (41/98 : ℝ)), ((43/98 : ℝ), (55/98 : ℝ)), ((57/98 : ℝ), (69/98 : ℝ)), ((71/98 : ℝ), (83/98 : ℝ)), ((85/98 : ℝ), (97/98 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_8 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([8] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([8] : List ℤ) [((1/112 : ℝ), (13/112 : ℝ)), ((15/112 : ℝ), (27/112 : ℝ)), ((29/112 : ℝ), (41/112 : ℝ)), ((43/112 : ℝ), (55/112 : ℝ)), ((57/112 : ℝ), (69/112 : ℝ)), ((71/112 : ℝ), (83/112 : ℝ)), ((85/112 : ℝ), (97/112 : ℝ)), ((99/112 : ℝ), (111/112 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/112 : ℝ), (13/112 : ℝ)), ((15/112 : ℝ), (27/112 : ℝ)), ((29/112 : ℝ), (41/112 : ℝ)), ((43/112 : ℝ), (55/112 : ℝ)), ((57/112 : ℝ), (69/112 : ℝ)), ((71/112 : ℝ), (83/112 : ℝ)), ((85/112 : ℝ), (97/112 : ℝ)), ((99/112 : ℝ), (111/112 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_9 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([9] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([9] : List ℤ) [((1/126 : ℝ), (13/126 : ℝ)), ((5/42 : ℝ), (3/14 : ℝ)), ((29/126 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (55/126 : ℝ)), ((19/42 : ℝ), (23/42 : ℝ)), ((71/126 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (97/126 : ℝ)), ((11/14 : ℝ), (37/42 : ℝ)), ((113/126 : ℝ), (125/126 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/126 : ℝ), (13/126 : ℝ)), ((5/42 : ℝ), (3/14 : ℝ)), ((29/126 : ℝ), (41/126 : ℝ)), ((43/126 : ℝ), (55/126 : ℝ)), ((19/42 : ℝ), (23/42 : ℝ)), ((71/126 : ℝ), (83/126 : ℝ)), ((85/126 : ℝ), (97/126 : ℝ)), ((11/14 : ℝ), (37/42 : ℝ)), ((113/126 : ℝ), (125/126 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_10 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([10] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([10] : List ℤ) [((1/140 : ℝ), (13/140 : ℝ)), ((3/28 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (41/140 : ℝ)), ((43/140 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (97/140 : ℝ)), ((99/140 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (25/28 : ℝ)), ((127/140 : ℝ), (139/140 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨9, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/140 : ℝ), (13/140 : ℝ)), ((3/28 : ℝ), (27/140 : ℝ)), ((29/140 : ℝ), (41/140 : ℝ)), ((43/140 : ℝ), (11/28 : ℝ)), ((57/140 : ℝ), (69/140 : ℝ)), ((71/140 : ℝ), (83/140 : ℝ)), ((17/28 : ℝ), (97/140 : ℝ)), ((99/140 : ℝ), (111/140 : ℝ)), ((113/140 : ℝ), (25/28 : ℝ)), ((127/140 : ℝ), (139/140 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_11 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([11] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([11] : List ℤ) [((1/154 : ℝ), (13/154 : ℝ)), ((15/154 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (69/154 : ℝ)), ((71/154 : ℝ), (83/154 : ℝ)), ((85/154 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (139/154 : ℝ)), ((141/154 : ℝ), (153/154 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨10, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/154 : ℝ), (13/154 : ℝ)), ((15/154 : ℝ), (27/154 : ℝ)), ((29/154 : ℝ), (41/154 : ℝ)), ((43/154 : ℝ), (5/14 : ℝ)), ((57/154 : ℝ), (69/154 : ℝ)), ((71/154 : ℝ), (83/154 : ℝ)), ((85/154 : ℝ), (97/154 : ℝ)), ((9/14 : ℝ), (111/154 : ℝ)), ((113/154 : ℝ), (125/154 : ℝ)), ((127/154 : ℝ), (139/154 : ℝ)), ((141/154 : ℝ), (153/154 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_12 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([12] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([12] : List ℤ) [((1/168 : ℝ), (13/168 : ℝ)), ((5/56 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (55/168 : ℝ)), ((19/56 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (83/168 : ℝ)), ((85/168 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (37/56 : ℝ)), ((113/168 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (51/56 : ℝ)), ((155/168 : ℝ), (167/168 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨11, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/168 : ℝ), (13/168 : ℝ)), ((5/56 : ℝ), (9/56 : ℝ)), ((29/168 : ℝ), (41/168 : ℝ)), ((43/168 : ℝ), (55/168 : ℝ)), ((19/56 : ℝ), (23/56 : ℝ)), ((71/168 : ℝ), (83/168 : ℝ)), ((85/168 : ℝ), (97/168 : ℝ)), ((33/56 : ℝ), (37/56 : ℝ)), ((113/168 : ℝ), (125/168 : ℝ)), ((127/168 : ℝ), (139/168 : ℝ)), ((47/56 : ℝ), (51/56 : ℝ)), ((155/168 : ℝ), (167/168 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

theorem safe_s1_13 :
    (((6 : ℝ)/7)) ≤ (slowμ (safeSet ([13] : List ℤ))).toReal := by
  have h := measGP_ge_of_sorted_bands ([13] : List ℤ) [((1/182 : ℝ), (1/14 : ℝ)), ((15/182 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (41/182 : ℝ)), ((43/182 : ℝ), (55/182 : ℝ)), ((57/182 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (83/182 : ℝ)), ((85/182 : ℝ), (97/182 : ℝ)), ((99/182 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (125/182 : ℝ)), ((127/182 : ℝ), (139/182 : ℝ)), ((141/182 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (167/182 : ℝ)), ((13/14 : ℝ), (181/182 : ℝ))]
    (by decide)
    (by
      intro q hq
      fin_cases hq
      · intro p hp
        fin_cases hp
        · exact ⟨0, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨1, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨2, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨3, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨4, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨5, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨6, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨7, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨8, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨9, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨10, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨11, by norm_num, by norm_num⟩
      · intro p hp
        fin_cases hp
        · exact ⟨12, by norm_num, by norm_num⟩)
    (by intro q hq; fin_cases hq <;> norm_num)
    (by norm_num [List.pairwise_cons])
  have hsum : (([((1/182 : ℝ), (1/14 : ℝ)), ((15/182 : ℝ), (27/182 : ℝ)), ((29/182 : ℝ), (41/182 : ℝ)), ((43/182 : ℝ), (55/182 : ℝ)), ((57/182 : ℝ), (69/182 : ℝ)), ((71/182 : ℝ), (83/182 : ℝ)), ((85/182 : ℝ), (97/182 : ℝ)), ((99/182 : ℝ), (111/182 : ℝ)), ((113/182 : ℝ), (125/182 : ℝ)), ((127/182 : ℝ), (139/182 : ℝ)), ((141/182 : ℝ), (153/182 : ℝ)), ((155/182 : ℝ), (167/182 : ℝ)), ((13/14 : ℝ), (181/182 : ℝ))] : List (ℝ × ℝ)).map (fun q => q.2 - q.1)).sum
      = (6/7 : ℝ) := by
    simp only [List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
    norm_num
  rw [hsum] at h
  linarith

end SafeCert
end LRC14
end LonelyRunner
